### ISSUE TITLE
Quick Start: Make More Readable Code Listings

### ISSUE THREAD

**Issue by commonsguy** [facebook/buck#1]
> The commands in this guide are designed to be copy-pasteable, idempotent, and usable on both Mac OS X and Linux.

While the first and third of those are laudable, your approach suffers from a fatal flaw: lack of readability. Documentation is useless if it cannot be understood.

Your examples:

- Assume the reader is good at shell scripting, which will not be the case for every relevant Android developer

- Assume the reader doesn't get confused by unnecessary departures from the norm, such as the use of single-quoted XML attributes to allow the `echo` commands to work

I strongly encourage you to switch to more conventional documentation styles, so that your documentation is not an impediment to your objectives in releasing the project.

**Comment by sdwilsh** [comment]
This feels "good enough" for now.  We'll probably be heavily revamping our docs in the next two months, so this will get a nice pass over it too, but I'm closing this for now.
