### ISSUE TITLE
audit needs to provide path to dependency

### ISSUE THREAD

**Issue by spearce** [facebook/buck#10]
audit input, classpath and owner don't let me see the path between a java_binary() and why a particular prebuilt_jar() is appearing in the classpath. The path data is necessary to track down the intermediate offending library and fix its deps statement (which may also require fixing code there, but whatever, that isn't buck's problem).

The problem I have right now is two different incompatible versions of the servlet-api appearing in a java_binary()'s classpath. This fails to package because which javax.servlet.Filter do you include? The one from the 2.5 specification or the one from the 3.0 specification? The developer should fix the library usages to be consistent, but they need to know where in the path to start looking.

Since multiple paths may exist to the same dependency, audit should try to print any paths as it can find, but an iterative approach would also be OK, e.g. fix one edge, re-run audit, fix another, etc.

**Comment by sdwilsh** [comment]
`buck audit dependencies` will give you the information that you need.  It wouldn't be hard to write a script to make it display some tree, but in practice, most trees would be massive.

https://facebook.github.io/buck/command/audit.html
