### ISSUE TITLE
merge R resource from another module

### ISSUE THREAD

**Issue by kaitian521** [facebook/buck#1001]
I have many modules in a Project, and some depends on other modules

A: package com.a;
B: package com.b;

A depends on B, and there is a file called TimeUtil.java which referes a string resource called R.string.network_unavailable.

context.getString(com.a.R.string.minutes_ago, delta / Time.MINUTE);

And this can be built by gradle, but cannot build by BUCK:

```
                                                   ^
  符号:   变量 network_unavailable
  位置: 类 com.a.R.string
/Users/XXX/FirstBuck/A/src/main/java/com/a/TimeUtil.java:420: error: 找不到符号
            UIUtils.displayToast(mContext, R.string.network_unavailable);
```

找不到符号 means "can not find symbol" in English

Any suggestion and reply is appreciated

Thanks

**Comment by kaitian521** [comment]
I find  a commit:

https://github.com/facebook/buck/commit/19412312afd2569d2426d51498c3444ee167a58c

but I do not know how to use it

**Comment by sdwilsh** [comment]
#653 provides more context, and has a reference from the OkBuck project where they use this as well.

**Comment by felipecsl** [comment]
Try with `resource_union = True`
