### ISSUE TITLE
Consider using a faster serializer for java objetcs

### ISSUE THREAD

**Issue by kageiit** [facebook/buck#1006]
Currently, the buck codebase uses Jackson's ObjectMapper in several places to read/write java objects to/from json for things like DependencyFiles etc.

There are many more much faster serializers available that be used as drop in replacements for jackson

https://github.com/eishay/jvm-serializers/wiki

Should consider switching buck to use a much faster serializer than jackson to make builds faster

**Comment by dreiss** [comment]
I'd like to see a profile that shows a non-trivial fraction of build time being spent in this code on some real build.  If we can produce that, I'd be in favor of this.

**Comment by plamenko** [comment]
Also, advantage of JSON over some binary format is that it is more or less human readable. @dreiss  said, we should avoid doing any microoptimizations unless it's a real issue.

**Comment by kageiit** [comment]
Will revisit this some other time then. Thanks!
