### ISSUE TITLE
brew formula downloads wrong bottle filename

### ISSUE THREAD

**Issue by elucash** [facebook/buck#1008]
```
Download failed: https://github.com/facebook/buck/releases/download/v2016.11.11.01/buck-2016.11.11.01.yosemite.bottle.tar.gz
```
While filename in release is `buck-2016.11.11.01.yosemite_or_later.bottle.tar.gz`
```
https://github.com/facebook/buck/releases/download/v2016.11.11.01/buck-2016.11.11.01.yosemite_or_later.bottle.tar.gz
```

**Comment by k21** [comment]
The formula specifies yosemite_or_later and the installation works on my end. What does the formula file look like on your machine? It should be in /usr/local/Homebrew/Library/Taps/facebook/homebrew-fb/buck.rb if you have used the default settings for Homebrew. Did you make any changes to that file?

**Comment by elucash** [comment]
Sorry if the report might be misguiding,
but I did nothing to formula, just have run `brew upgrade` and got the error
```
Download failed: https://github.com/facebook/buck/releases/download/v2016.11.11.01/buck-2016.11.11.01.yosemite.bottle.tar.gz
```
literally, there was no such file, `buck-2016.11.11.01.yosemite.bottle.tar.gz`

the formula has such code, of course

```
  bottle do
    root_url "https://github.com/facebook/buck/releases/download/v#{@@buck_version}"
    cellar :any_skip_relocation
    sha256 "d8ea7fd04d45e9d2ec63feaaee26fd0093ff6ccbc995672f179d86ae091d5bb9" => :yosemite_or_later
  end
```

But, despite this, on my osx 10.11.6 it looks for `buck-2016.11.11.01.yosemite.bottle.tar.gz`. I would suggest that `:yosemite_or_later` doesn't always do what it should

**Comment by elucash** [comment]
As it's still possible to build Buck from sources using `brew install buck` (not using bottle), feel free to close this report

**Comment by k21** [comment]
Hm, looks like a breaking change in [Homebrew 1.1.0](https://github.com/Homebrew/brew/releases/tag/1.1.0). I guess I can upload the same bottle both with and without the suffix to fix that.

**Comment by k21** [comment]
Done, let me know if you can install the bottle now.

**Comment by elucash** [comment]
@k21 thank you! I was able to install using bottle
