### ISSUE TITLE
why use "use_split_dex = True,   exopackage_modes = ['secondary_dex'],   primary_dex_patterns ", I can't get more than one .dex file in my apk.

### ISSUE THREAD

**Issue by godeadasdf** [facebook/buck#1010]
![image](https://cloud.githubusercontent.com/assets/13552859/20251007/42d88df6-aa50-11e6-8e8b-d1444452cca4.png)
![image](https://cloud.githubusercontent.com/assets/13552859/20251018/6586c886-aa50-11e6-92f0-f0ea0490564e.png)

**Comment by v-jizhang** [comment]
Sorry we never got back to this! At this point, we are closing this because it is quite out of date and it is not clear if the issue still exists. Please create a new one if you still see the problem. Thank you.
