### ISSUE TITLE
Can't fetch remote file with classifier

### ISSUE THREAD

**Issue by jauco** [facebook/buck#1014]
If I have a buckfile with the following contents:

```
remote_file(
  name = 'groovy-groovysh-indy_remote_jar',
  url = 'mvn:org.codehaus.groovy:groovy-groovysh:jar:indy:2.4.1',
  sha1 = '1600fde728c885cc9506cb102deb1b494bd7c130',
)
```

and I run `buck fetch <the build target>`

I expect the http://search.maven.org/remotecontent?filepath=org/codehaus/groovy/groovy-groovysh/2.4.1/groovy-groovysh-2.4.1-indy.jar jar to be downloaded. However buck instead gives the following error:

```
Can only download maven artifacts over HTTP or HTTPS: org.codehaus.groovy/groovy-groovysh/jar/2.4.1/jar-2.4.1-indy.jar
BUILD FAILED: //buck-test:groovy-groovysh-indy_remote_jar failed with exit code -1:
curl
[-] PROCESSING BUCK FILES...FINISHED 0.0s [100%] 🐌  File removed
[-] DOWNLOADING... (0.00 B/S AVG, TOTAL: 0.00 B, 0 Artifacts)
[-] BUILDING...FINISHED 0.2s [100%] (1/1 JOBS, 0 UPDATED, 0 [0.0%] CACHE MISS)
```

If I use the resolver from this repo to download it:

```
java -jar resolver.jar -repo . -maven https://repo1.maven.org/maven2 org.codehaus.groovy:groovy-groovysh:jar:indy:2.4.1
```

I get a file who'se sha1 is 9d9fc2304f62fb992cdf614c9da406906e802399 instead of 1600fde728c885cc9506cb102deb1b494bd7c130 which is the sha1 of the jar without the classifier

**Comment by jauco** [comment]
I looked into the code, and the problem seems to be that it does not parse the mvn coords as they are usually written. The coords spec as given in several places is `groupId:artifactId[:extension[:classifier]]:version` valid coords are 

```
org.codehaus.groovy:groovy-groovysh:2.4.1
org.codehaus.groovy:groovy-groovysh:jar:2.4.1
org.codehaus.groovy:groovy-groovysh:jar:indy:2.4.1
```
but not
```
org.codehaus.groovy:groovy-groovysh:indy:2.4.1
```

The maven coords as parsed by MavenUrlDecoder are a bit different. Parsing the regex back we get: `[server:]groupId:artifactId:extension:version` i.e. extension is not optional, classifier is not allowed and server is allowed to have colons in it (presumable to allow something like `https://example.org:org.example:something:jar:1.0.0`)

I don't think that regex can be made to work with an optional classifier attribute while also allowing colons in the server part. So at least the javadocs at https://buckbuild.com/javadoc/com/facebook/buck/file/MavenUrlDecoder.html should be fixed. I'd prefer it if maven classifiers where also supported, but I can't think of a backwards compatible way to do so. 

I guess a workaround would be to do the translation myself and simply pass a http url.

Could you verify my reasoning?

**Comment by Coneko** [comment]
cc @shs96c

**Comment by jauco** [comment]
Could someone verify my reasoning? If I'm correct I can make a small PR that fixes the documentation and suggests to use http urls as a workaround (it's what I'm doing right now. This bug is not blocking me)

**Comment by sdwilsh** [comment]
@shs96c is probably the best person to do that.
