### ISSUE TITLE
#930 breaks buck builds on macOS

### ISSUE THREAD

**Issue by dxxchen** [facebook/buck#1017]
#930 switches two scripts from using `readlink` to `realpath`, which is not available by default on macOS.

Given that Buck already requires Python, a one-liner that uses `os.path.realpath` would probably provide maximum portability.

**Comment by Coneko** [comment]
Oh sorry, I didn't even realise because we have realpath installed with brew.

@aarongable Any idea here?

**Comment by dxxchen** [comment]
I unfortunately cannot sign the CLA (yet?), but our fork replaces that line with something like http://stackoverflow.com/a/1115074.

**Comment by demon** [comment]
Hit this as well. As mentioned, the easy workaround is install `coreutils` from homebrew, it provides realpath.

However, rewriting in python would make it more platform-agnostic here I think.

**Comment by kageiit** [comment]
Needing a dependency that is not documented in the docs can be confusing, especially when there are alternatives available with already required dependencies

**Comment by davido** [comment]
Build tool must not have any dependencies. `Ant` is weird enough to depend on to bootstrap Buck. I wonder why #930 wasn't reverted yet?

**Comment by davido** [comment]
@Coneko Thanks.
