### ISSUE TITLE
Add support for custom compiler class names

### ISSUE THREAD

**Issue by kageiit** [facebook/buck#1019]
Currently, the jar backed javac hardcodes `com.sun.tools.javac.api.JavacTool` as the implementation of `JavaCompiler`

https://github.com/facebook/buck/blob/8e3c38fcf5403808aa0529afe16b8e9978c9b427/src/com/facebook/buck/jvm/java/AbstractJavacOptions.java#L149

Proposal is to open that up with a `compiler_class_name` option that can work with `javac_jar` option.

This lets us integrate alternative compilers like Google's Error prone (https://github.com/google/error-prone) into the build process

**Comment by davido** [comment]
Indeed, thanks for the link. I also see that there was already some efforts to integrate Buck with error prone here: https://github.com/google/error-prone/issues/318.
