### ISSUE TITLE
Compile with -fmodules only works with preprocess combined mode

### ISSUE THREAD

**Issue by nguyentruongtho** [facebook/buck#1023]
If I enable modules (`cflags = -fmodules`), without using precompile combined mode (`combined_preprocess_and_compile = false`), buck fails to compile. Following is the error I got:

```
main.m:1:9: fatal error: module 'UIKit' not found
@import UIKit; /* clang -E: implicit import for "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIKit.h" */
 ~~~~~~~^~~~~
1 error generated.
```

**Comment by Coneko** [comment]
There's several things that don't work without combined preprocess and compile on clang, we're removing the other preprocessing mode as soon as possible, just use combined.
