### ISSUE TITLE
Consider to dump the artifact location in build command output

### ISSUE THREAD

**Issue by davido** [facebook/buck#1029]
The output of the `build` command could include the output location of the target:

```
  $ buck build gerrit-acceptance-framework:acceptance-framework
Using watchman.
[-] PROCESSING BUCK FILES...FINISHED 0.6s [100%] 🐳  New buck daemon
[-] DOWNLOADING... (0.00 B/S AVG, TOTAL: 0.00 B, 0 Artifacts)
[-] BUILDING...FINISHED 4.4s [100%] (57/57 JOBS, 2 UPDATED, 2 [3.5%] CACHE MISS)
```

While I'm getting a lot of details in the output above, the most important info is missing: where is the location of the output artifact?

To get this info I'm forced to always issue a second command, to actually figure out where it is (for example to check that the content is sane or to just use it for deployment or what not):

```
  $ buck targets --show_output gerrit-acceptance-framework:acceptance-framework
Using watchman.
[+] PROCESSING BUCK FILES...0.5s [100%] 🐳  New buck daemon
//gerrit-acceptance-framework:acceptance-framework buck-out/gen/gerrit-acceptance-framework/acceptance-framework.jar
```

It would be helpful, if the output location of the final artifact is contained in the output of the `build` command:

```
  $ buck build gerrit-acceptance-framework:acceptance-framework
  [...]
  buck-out/gen/gerrit-acceptance-framework/acceptance-framework.jar
```

And no, it can not be induced from the rule name:

```
  $ buck build headless
Using watchman.
[-] PROCESSING BUCK FILES...FINISHED 3.2s [100%] 🐳  New buck daemon
[-] DOWNLOADING... (0.00 B/S AVG, TOTAL: 0.00 B, 0 Artifacts)
[-] BUILDING...FINISHED 11.6s [100%] (215/215 JOBS, 11 UPDATED, 3 [1.4%] CACHE MISS)
```

and:

```
  $ buck targets --show_output headless
Using watchman.
[+] PROCESSING BUCK FILES...3.0s [100%] 🐳  New buck daemon
//:headless buck-out/gen/headless/headless.war
```

**Comment by Coneko** [comment]
`buck build` supports `--show_output` as well.

Is that acceptable?

**Comment by davido** [comment]
Oh, thanks for pointing this out, I missed it.

```
  $ buck build --show-output headless
[-] PROCESSING BUCK FILES...FINISHED 0.0s 🐇  
[+] DOWNLOADING... (0.00 B/S, TOTAL: 0.00 B, 0 Artifacts)
[+] BUILDING...0.1s [0%] (0/561 JOBS, 0 UPDATED, 0 [0.0%] CACHE MISS)
 |=> //gerrit-server:server...  0.0s (checking local cache)
The outputs are:
//:headless buck-out/gen/headless/headless.war
```

I have three comments, though:

* 1. The `targets` commands also accepts `--show_output`, while `build` command only supports `--show-output` spelling.
* 2. Following the DRY principle, I wouldn't expect the output to be that verbose and dump the rule name, that I asked to build. I know that I asked to dumo the output, and I know, what command i asked to execute. And there can be always at most one command outcome in Buck. So i would expect to `--show-output` to just tell me the output:

```
$ buck build --show-output headless
[-] PROCESSING BUCK FILES...FINISHED 0.0s 🐇  
[+] DOWNLOADING... (0.00 B/S, TOTAL: 0.00 B, 0 Artifacts)
[+] BUILDING...0.1s [0%] (0/561 JOBS, 0 UPDATED, 0 [0.0%] CACHE MISS)
 |=> //gerrit-server:server...  0.0s (checking local cache)
  buck-out/gen/headless/headless.war
```

* 3. It's annoying to always specify `--show-output` option, and i don't want to mess around with shell alias. Please, consider to introduce some means to specify the defaut command options in user specific Buck configuration file, e.g.:

```
  $ cat ~/.buckrc
[...]
[commands]
  build = --show-output
```

**Comment by Coneko** [comment]
Yes hg style aliases are something we've always wanted, alas they're always bumped back by some more important work.

Changing the output of `--show-output` is something we could gate behind a config setting.

**Comment by davido** [comment]
Another alternative is to swap the logic to always show the output but offer "--hide-output" option to suppress it.
