### ISSUE TITLE
IntelliJ plugin source code link points to wrong part of repo

### ISSUE THREAD

**Issue by krschultz** [facebook/buck#1033]
The [IntelliJ Plugin repository](https://plugins.jetbrains.com/plugin/7826) has the wrong link for the Buck plugin's source code.

Expected: 

https://github.com/facebook/buck/tree/master/src/com/facebook/buck/intellij/ideabuck

Actual: 

https://github.com/facebook/buck/tree/master/src/com/facebook/buck/intellij/plugin

**Comment by styurin** [comment]
Thanks!
