### ISSUE TITLE
IntelliJ project language level config breaks in some cases

### ISSUE THREAD

**Issue by seanabraham** [facebook/buck#1035]
After this change https://github.com/facebook/buck/commit/408fcc27738f0fdd9feca67b85b05946d860883a the global java source setting is used to set the language level for intellij when using `buck project`. This breaks in some cases, notably when retrolambda is used. Preferably there would be an option to still set the project language level, or some other logic which automatically sets the project language level to the lowest java source level among all the modules.

cc @styurin

**Comment by styurin** [comment]
Fixed in 6bc1888f83660f2f8f7e81e895803891090faa79
