### ISSUE TITLE
Command line flag to disable watchman

### ISSUE THREAD

**Issue by SirCmpwn** [facebook/buck#1038]
For automated builds, packaging, etc.

**Comment by aiked** [comment]
Hello @SirCmpwn,
Buck does not currently support this. You could use buck without the daemon by using `NO_BUCKD=1 buck <command>` until we actually write the flag, which does not look complicated.
We also accept pull requests if you want to speed this up :)

**Comment by aiked** [comment]
Could I ask why you want this? You don't want to use Watchman? You don't have a Watchman version that works well? You don't want the caches of the daemon? Depending the need the flag will have different behaviour.

**Comment by SirCmpwn** [comment]
NO_BUCKD will do the trick, thanks! As for why, I want the builds to be self contained and scripted. I don't like the idea of a process forking during the build. In fact the build is broken in my fakeroot build environment, NO_BUCKD will probably fix that.

**Comment by aiked** [comment]
Cool, I will close this one but feel free to open it if it's not good enough and you need something more complicated.
