### ISSUE TITLE
error generating manifest xml 

### ISSUE THREAD

**Issue by androidhuoniao** [facebook/buck#1039]
if I delete the  ```android:maxSdkVersion="18"```  in my application module manifest , buck will be ok, anyone can help me，thanks versy much

![image](https://cloud.githubusercontent.com/assets/4191583/20996433/8d0552ce-bd38-11e6-827c-ca8c70d51bd4.png)

**Comment by aiked** [comment]
Hello @androidhuoniao,

It looks like `maxSdkVersion` is no longer supported. Check https://developer.android.com/guide/topics/manifest/uses-sdk-element.html.
The current version of the Merger used by Buck contains the following comments:
`{@code @maxSdkVersion}: obsolete, ignored. Not used in comparisons and not merged.`

You can check #1018 that will update the manifest merger.
