### ISSUE TITLE
Parse error for build file when buck build

### ISSUE THREAD

**Issue by maxczc** [facebook/buck#1046]
I create android project follow the step of "Getting Started（https://buckbuild.com/setup/getting_started.html）" but when i run 
`buck build //apps/myapp:app `
it show error
`Parse error for build file /Users/maxczc/Desktop/Demo/buckDemo/apps/myapp/BUCK:   File "/Users/maxczc/Desktop/Demo/buckDemo/apps/myapp/BUCK", line 8, in <module>
    '//res/com/example/activity:res',
  File "/Users/maxczc/Desktop/Demo/buckDemo/.buckd/tmp/buck_run.90wKbl/buck575205276278955770.py", line 119, in invoke
    return self.func(*args, **updated_kwargs)
TypeError: android_binary() got an unexpected keyword argument 'target'`

**Comment by davido** [comment]
Looks like documentation is stale here, as target attribute nt mentioned in the documentation of `android_binary`: [1]. Try to remove this line and try again.

* [1] https://buckbuild.com/rule/android_binary.html

**Comment by maxczc** [comment]
Thanks, it solved
