### ISSUE TITLE
android studio buck plugin error =13, Permission denied

### ISSUE THREAD

**Issue by maxczc** [facebook/buck#1048]
After I install the buck plugin when I open android studio it always show 
`ProcessNotCreatedException: Cannot run program "/Users/maxczc/buck/bin" (in directory "/Users/maxczc/Desktop/Demo/buckDemo"): error=13, Permission denied`

**Comment by styurin** [comment]
Do you have buck in PATH?

**Comment by maxczc** [comment]
@styurin Yes , i had already configured the buck in Path

**Comment by styurin** [comment]
Can you check that `buck/bin/buck` has executable permissions?

**Comment by maxczc** [comment]
Sorry, it's my problem. I don't check the path carefully in android studio util you said "Can you check that buck/bin/buck has executable permissions?", but my path was "buck/bin", it missing "buck" in the last.
