### ISSUE TITLE
Provide support for worker_tool, genrule etc. macros in postprocess_classes_commands

### ISSUE THREAD

**Issue by kageiit** [facebook/buck#1052]
Currently, the post process classes command only supports bash commands with some additioanl env variables available to it. It would be great to provide macro support to be able reduce the startup cost of tools invoked this way

**Comment by v-jizhang** [comment]
Sorry we never got back to this! At this point, we are closing this because it is quite out of date and it is not clear if the issue still exists. Please create a new one if you still see the problem. Thank you.
