### ISSUE TITLE
resource directory does not exist firebase 

### ISSUE THREAD

**Issue by rahultailor** [facebook/buck#1055]
I am using okbuild for this. 

ERROR: resource directory 'buck-out/bin/.okbuck/cache/__unpack_com.google.firebase.firebase-core-9.6.1.aar#aar_unzip__/res' does not exist

BUILD FAILED: //app:bin_debug#aapt_package failed with exit code 1:
aapt_package
stderr: ERROR: resource directory 'buck-out/bin/.okbuck/cache/__unpack_com.google.firebase.firebase-core-9.6.1.aar#aar_unzip__/res' does not exist

**Comment by kageiit** [comment]
This is an issue with the firebase 9.6.1 aar. It does not include a res directory, which is incorrect according to the aar spec. The directory should always exist even if it is empty. This should be opened as a bug on b.android.bom

**Comment by rahultailor** [comment]
Thanks. I manually created a res folder. And i was able to build and install. but In Mainactivity on firebase initialization it crashed. Its working fine with gradle. Is there other way to add firebase in buck.

**Comment by kageiit** [comment]
I don't think integration of a specific library is an appropriate question for here. If it is a runtime crash, you may need to check the firebase docs or file a bug on the android tracker with the start race to find out more

**Comment by ChaitanyaPramod** [comment]
Facing similar problem with ACRA.
Agreed that /res/ is mandatory to be present in a .aar, but strictly requiring this inconveniences end developer and breaks interop with Gradle android plugin. Library authors tend to not bother as the artefact is usable with gradle-android-plugin.
Having this check is not helping buck or the app developer.

**Comment by kassim** [comment]
several of Google's Android libraries have the same issue

**Comment by ojw28** [comment]
Even if this is a bug in the Android Gradle Plugin (which looks likely), and that bug is fixed at some point, there are still going to be lots of released libraries in the wild that are missing the res directory. Doesn't this imply that a workaround in Buck will be necessary, in practice, to avoid fairly major pain for developers that use it?

**Comment by oleksandroparasc** [comment]
@kageiit I have created a ticket https://partnerissuetracker.corp.google.com/issues/77591523# for them and eventually they will fix it, but as @ojw28 have mentioned buck would need workaround anyway

**Comment by kageiit** [comment]
Latest versions of buck do not have this issue anymore. Its been fixed a few months ago

**Comment by oleksandroparasc** [comment]
@kageiit thank you
