### ISSUE TITLE
Infer configuration and integration is not documented

### ISSUE THREAD

**Issue by davido** [facebook/buck#1058]
It looks like support was added to [FB infer](http://fbinfer.com/) in ecae40a002b06f609817a5be87a8ebb34ae44a7c to Buck Cxx tool chain, but it wasn't documented.

**Comment by sdwilsh** [comment]
cc @martinoluca

**Comment by Coneko** [comment]
It's slated to be removed, and infer will integrate through the cxx compilation database.

**Comment by Coneko** [comment]
In general using infer is done through the infer command line tool, one would never invoke the Buck infer integration directly.

**Comment by davido** [comment]
I do aware of `infer` integration through the CLI:

```
  infer -- buck build foo
```

I'm just scared about tons of undocumented configuration options in Buck.
