### ISSUE TITLE
framework not found UIKit when i build my project

### ISSUE THREAD

**Issue by SwiftlyFly** [facebook/buck#1070]
I have set frameworks as follow，
frameworks= [
    '$SDKROOT/System/Library/Frameworks/UIKit.framework',
    '$SDKROOT/System/Library/Frameworks/Foundation.framework',
  ]

when i build my project, build failed with message "framework not found UIKit".  How can i set SDKROOT manually?
Thanks!

**Comment by SwiftlyFly** [comment]
I have found SDKROOT = /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk, how can i change it?

**Comment by ryu2** [comment]
You'll want to set the config `cxx.default_platform` to a iOS SDK, e.g. `iphonesimulator-x86_64` or `iphoneos-arm64` to get Buck to use a iOS SDKROOT.

**Comment by SwiftlyFly** [comment]
I have set  cxx as follow, but it also didn't work for me.
[cxx]
  default_platform = iphonesimulator-x86_64
  cflags = -g

**Comment by SwiftlyFly** [comment]
Thanks for your reply.
I have set cxx as follow, but it also didn't work for me. And i can't find keyword "default _platform" at Buck website. https://buckbuild.com/concept/buckconfig.html#cxx.
[cxx]
default_platform = iphonesimulator-x86_64
cflags = -g


在2016-12-29，Mark Wang <notifications@github.com> 写道:-----原始邮件-----
 发件人: Mark Wang <notifications@github.com>
 发送时间: 2016年12月29日 星期四
 收件人: facebook/buck <buck@noreply.github.com>
 抄送: SwiftlyFly <fanshuaifei@tju.edu.cn>, Author <author@noreply.github.com>
 主题: Re: [facebook/buck] framework not found UIKit when i build my project (#1070)

You'll want to set the config cxx.default_platform to a iOS SDK, e.g. iphonesimulator-x86_64 or iphoneos-arm64 to get Buck to use a iOS SDKROOT.

**Comment by ryu2** [comment]
What version of Xcode are you running?
Can you build a iOS app normally through Xcode itself?

**Comment by SwiftlyFly** [comment]
The version of Xcode is 8.2.1, and I can build and run a iOS app through Xcode.

Thanks.


在2016-12-29，Mark Wang <notifications@github.com> 写道:-----原始邮件-----
 发件人: Mark Wang <notifications@github.com>
 发送时间: 2016年12月29日 星期四
 收件人: facebook/buck <buck@noreply.github.com>
 抄送: SwiftlyFly <fanshuaifei@tju.edu.cn>, Author <author@noreply.github.com>
 主题: Re: [facebook/buck] framework not found UIKit when i build my project (#1070)

What version of Xcode are you running?
 Can you build a iOS app normally through Xcode itself?

**Comment by SwiftlyFly** [comment]
Thank you very much, I have solved my problem. I have installed buck manually before, maybe there is some questions. Now I install it with homebrew, and everything is OK.  

Thank you again for your answer！
在2016-12-29，Mark Wang <notifications@github.com> 写道:-----原始邮件-----
 发件人: Mark Wang <notifications@github.com>
 发送时间: 2016年12月29日 星期四
 收件人: facebook/buck <buck@noreply.github.com>
 抄送: SwiftlyFly <fanshuaifei@tju.edu.cn>, Author <author@noreply.github.com>
 主题: Re: [facebook/buck] framework not found UIKit when i build my project (#1070)

What version of Xcode are you running?
 Can you build a iOS app normally through Xcode itself?

**Comment by aledalgrande** [comment]
I think this should be added in the `.buckconfig` file of the iOS demo folder.

**Comment by MohamedAlsadek** [comment]
when I tried to set it in .buckconfig like this 

I got the following error 

```
[cxx]
  default_platform = iphoneos-arm64
  cflags = -g -std=c11
  cxxflags = -g -std=c++14
  # Many ARC APIs don't compile with separate preprocess and compile.
  combined_preprocess_and_compile = true

[apple]
  xctool_zip_target = //third-party/ios/xctool:xctool-minimal-zip

[alias]
   my-app = //:BuckDemoApp

[project]
  ide = xcode
  ignore = \
    .git, \
    .hg, \
    .buckd
```

```
Undefined symbols for architecture x86_64:
  "_main", referenced from:
     implicit entry/start for main executable
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

BUILD FAILED: //:BuckDemoAppBinary#binary,iphonesimulator-x86_64 failed with exit code 1:
c++ link
stderr: Undefined symbols for architecture x86_64:
  "_main", referenced from:
     implicit entry/start for main executable
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

[-] PROCESSING BUCK FILES...FINISHED 0.0s [100%] 🏖  Watchman reported no changes
[-] DOWNLOADING... (0.00 B/S AVG, TOTAL: 0.00 B, 0 Artifacts)
[-] BUILDING...FINISHED 0.2s [100%] (2/8 JOBS, 1 UPDATED, 1 [12.5%] CACHE MISS)
```

**Comment by liushuaikobe** [comment]
I installed buck via homebrew. But I also have this problem when I try to build the [buck demo app](https://github.com/fbsamples/bucksamples/tree/master/cross-platform-scale-2015-demo) as the [doc](https://buckbuild.com/setup/getting_started.html) said. 

I checked the [.buckconfig file](https://github.com/fbsamples/bucksamples/blob/master/cross-platform-scale-2015-demo/.buckconfig#L5), it's `iphonesimulator-x86_64` indeed. 

Finally I found that it's my xcodebuild error. More details [here](https://stackoverflow.com/questions/17980759/xcode-select-active-developer-directory-error).

Try 

    $ xcodebuild -version

If you see

    xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory 
    '/Library/Developer/CommandLineTools' is a command line tools instance

Then use

    $ sudo xcode-select -r

Try again, the error disappeared.
