### ISSUE TITLE
Your buck server may be turned off,since the buck daemon is on port.

### ISSUE THREAD

**Issue by liujigang** [facebook/buck#1071]
Environment: Ubuntu 16.04 , AndroidStudio 2.2.3 , plugins buck for idea version 2.7.3.
Project:[conceal](https://github.com/facebook/conceal)

[screenshot](http://liujigang.qiniudn.com/buck-httpserver.png)

I set httpserver port = 0 and restart AndroidStudio,but still has this error.

**Comment by clonetwin26** [comment]
We are seeing this as well on intellij 1.7.2 using the buck IDEA plugin 2.7.7
