### ISSUE TITLE
Manifest files are at the end of jars 

### ISSUE THREAD

**Issue by shs96c** [facebook/buck#1073]
In order for `JarInputStream` to work, manifest files (`META-INF/MANIFEST.MF`) must be one of the first two entries in a jar.

This originally worked in 63dac4b10fe6fbdd36d55506d29299b3d802e0d4, but something has changed recently, and it's no longer the case.

Steps to reproduce:

* Build a `java_library` target
* Examine the built jar.

Expected result:

* Manifest at the start of the jar

Actual result:

* Manifest at the end of the jar

**Comment by shs96c** [comment]
Digging a little. The default compilation mode uses the `JdkProvidedInMemoryJavac` and spools directly to the jar (which is good --- it avoids a chunk of IO). This extends the `Jsr199Javac`, which compiles the classes, then calls `JarDirectoryStepHelper.createJarFile`. Obviously, this means that the classes get written to the jar first, and only afterwards is there a chance for the manifest to be written.

**Comment by v-jizhang** [comment]
Sorry we never got back to this! At this point, we are closing this because it is quite out of date and it is not clear if the issue still exists. Please create a new one if you still see the problem. Thank you.
