### ISSUE TITLE
How to quote the header file？

### ISSUE THREAD

**Issue by SwiftlyFly** [facebook/buck#1080]
Now， I quote the header file as follow:
#include "header_namespace/header_name.h"
 Is there some simple method that I can quote the header file just using the header file name as follow：
#include "header_name.h"

**Comment by ttsugriy** [comment]
assuming you're using [cxx_library](https://buckbuild.com/rule/cxx_library.html), you should be able to use `header_namespace = ''` in order to not have to specify header namespace.

**Comment by marcinkosiba** [comment]
Assuming this is resolved, please re-open if not.

**Comment by SwiftlyFly** [comment]
I am using `apple_library`, and have set `header_namespace = ''`, but it not worked for me. 
When  I am using `prebuilt_cxx_library`, it worked. I am depressed.

**Comment by ttsugriy** [comment]
[apple_library](https://buckbuild.com/rule/apple_library.html) uses a different attribute name - `header_path_prefix`. Please give it a try and it should work.
