### ISSUE TITLE
Changes to Android instrumentation code under androidTest are not picked up by Buck

### ISSUE THREAD

**Issue by felipecsl** [facebook/buck#1085]
Running `./buckw test` will not pick up any changes to Android java test code under `src/androidTest/java`.
In order for the changes to be reflected I have to `rm -rf buck-out` and `./buckw test`again which of course takes forever.
I can reproduce this every time.
Is this a known issue and/or is there any workaround for this?

**Comment by kageiit** [comment]
We have been seeing the same issue for a few months with instrumentation test apks. Changes to source never seem to be picked up.

**Comment by Madhav-S** [comment]
Seconding @kageiit. Several developers on our side have separately seen this issue. Changes to test code are sometimes not reflected in the APKs that are built. We need to `rm -rf buck-out` in order to clear the cache and rebuild.

**Comment by felipecsl** [comment]
I was able to work around the issue by running this before `buck test`:

```
find buck-out -name *instrumentation_debug* | xargs rm -rf
```

**Comment by marcinkosiba** [comment]
Could one of you provide repro steps?

**Comment by Leland-Takamine** [comment]
NO_BUCKD=1 fixed the issue for me.
