### ISSUE TITLE
How to use environment variables in BUCK Rule ?

### ISSUE THREAD

**Issue by ldjhust** [facebook/buck#1090]
Hi, All
    Is there a way to get a environment variable's value in BUCK Rule ? 
eg:
   Assume I have a environment variable: NAME="test_name", and I want to use it in android_resource rule:
  
   android_resource(
        name = # how to get the NAME's value here ?
        ......
    )

thanks very much for any help !

**Comment by marcinkosiba** [comment]
I think it's cleaner to use `.buckconfig' + https://buckbuild.com/function/read_config.html to change the behavior of the build. I suggest you put the information in the `user` section of buckconfig. You can override configuration on the command line (--config) or using a .buckconfig.local

If you have a strong reason to use the environment, then you can get at the variables from your BUCK fike using `os.environ['NAME']` (don't forget to `import os` at the top of the file).

**Comment by aventadorm** [comment]
I am getting the following error : 

parameter 'assembly': cannot coerce 'D:\Tools\companyName\SDKName\SDKVersion\SDKAssembly.dll' to interface com.facebook.buck.core.sourcepath.SourcePath, SourcePath cannot contain an absolute path.

I am using os.environ['NAME'] to reference the env. variable that points to a certain assembly file on all my build machines.
