### ISSUE TITLE
snapshot_reference_images_path can't be verified

### ISSUE THREAD

**Issue by nguyenhuy** [facebook/buck#1091]
I'm trying to use `napshot_reference_images_path` introduced in #1082. Here is the relevant line in my BUCK file:
```
snapshot_reference_images_path='AsyncDisplayKitTests/ReferenceImages',
```

I got this error when I tried to run buck test:
```
BUILD FAILED: //:Tests: parameter 'snapshotReferenceImagesPath': no such file or directory 'AsyncDisplayKitTests/ReferenceImages'
```

If I change the path to a valid path, say `AsyncDisplayKitTests/ReferenceImages_iOS_10`, the build will proceed. But then FBSnapshotTestCase will try to append a suffix to this path, thus turn it into `ReferenceImages_iOS_10_iOS_10` and tests will fail because it's no longer a valid path.

I think `snapshot_reference_images_path` should be either a string or an unverified path. Or maybe I'm using it wrong?

**Comment by nguyenhuy** [comment]
cc @robbertvanginkel

**Comment by robbertvanginkel** [comment]
Hmm, yes. I didn't encounter this as all our tests are agnostic and don't have those suffixes. I do want this to be a `SourcePath` like it is now, so it can be combined with the `export_file` rule.

@Coneko Is there a way to have a sourcepath that is unverified?

**Comment by Coneko** [comment]
Nope, but it can be made an `Either<SourcePath, String>`.
