### ISSUE TITLE
Xcode project for static lib generated with --build-with-buck option fails to build

### ISSUE THREAD

**Issue by ProfessaA** [facebook/buck#1097]
I created a simple buck project with an `apple_library` and ` apple_test` build rule (https://github.com/ProfessaA/BuckStaticLibBuildFailure).

When I follow these steps:
1. `buck project --build-with-buck StaticLib`
1. `open StaticLib/StaticLib.xcworkspace`,
1.  build  through Xcode

The build fails with `Command /bin/sh failed with exit code 64`.  The failure is caused by this line in the generated script:
```
usr/local/bin/buck build --show-output --report-absolute-paths //StaticLib:StaticLib#iphonesimulator-x86_64,static#dwarf-and-dsym,iphonesimulator-i386,iphonesimulator-x86_64
[2017-01-10 11:06:10.193][error][command:null][tid:1204][com.facebook.buck.cli.Main] Uncaught exception at top level
java.lang.IllegalArgumentException: Invalid characters in flavor name: static#dwarf-and-dsym
```

Running `buck build --show-output --report-absolute-paths //StaticLib:StaticLib#iphonesimulator-x86_64,static#dwarf-and-dsym,iphonesimulator-i386,iphonesimulator-x86_64` from the command line fails as well, it looks like the pound sign in front of `dwarf-and-dsym` shouldn't be there.  Any ideas how to fix this?

**Comment by sdwilsh** [comment]
The second pound sign in the target shouldn't be there.  My guess is that somewhere the project generation isn't merging flavors properly.  I'm guessing that `buck build --show-output --report-absolute-paths //StaticLib:StaticLib#iphonesimulator-x86_64,static,dwarf-and-dsym,iphonesimulator-i386,iphonesimulator-x86_64` will work.

**Comment by ProfessaA** [comment]
yeah that buck build line is generated by `build_with_buck.py`:

```
python  buck-out/res/com.facebook.buck.apple.project_generator.ProjectGenerator/build_with_buck.py \ 	/Users/aaron.levine/workspace/buck-prebuilt-cxx \
	/usr/local/bin/buck \
	-- "--show-output --report-absolute-paths" \
	//StaticLib:StaticLib#iphonesimulator-x86_64,static \
	dwarf-and-dsym \
	dwarf-and-dsym
```

That script doesn't expect the `escaped_build_target` param to have flavors, so it always appends a "#" followed by all flavors.  It seems like that param shouldn't have flavors, but in that case the script wouldn't be properly appending the static flavor, which I think is needed.  Is there any documentation on flavors?

**Comment by v-jizhang** [comment]
Sorry we haven't update this issue for more than 3 years. At this point, we are closing this because it is quite out of date and it is not clear if the issue still exists. Please create a new one if you still see the problem. Thank you.
