### ISSUE TITLE
Can't run tests in generated Xcode project

### ISSUE THREAD

**Issue by ProfessaA** [facebook/buck#1103]
This can be reproduced using the quickstart iOS project:
1. `buck quickstart --type ios --dest-dir BuckDemoApp`
1. `cd BuckDemoApp`
1. `buck project --build-with-buck ios:BuckDemoApp`
1. `open ios/BuckDemoApp.xcworkspace`
1. `cmd-U` to run tests

This fails with a linker error:
```
ld: file not found: <path to derived data>/BuckDemoApp-dvmkaejbpzzjbyekwpbmfaslobqn/Build/Products/Debug-iphonesimulator/./BuckDemoApp.app//BuckDemoApp
```

Running and building uses the `BuckDemoApp-Buck` target, which runs a Run Script phase that uses buck to generate the app.  However, testing still seems to run through the normal xcode build path and fails when it expects the container app to have been built in DerivedData.

In general, do you have any recommendations for developing iOS apps using buck?  Do you run the app and tests from the CLI? If so, how do you debug app and test runs?

**Comment by ProfessaA** [comment]
@sdwilsh is the `--build-with-buck` flag intended to make the tests in the generated project runnable from Xcode? If not, how do you recommend developing iOS apps using buck? Should the app be built and run from Xcode but tested from the command line?

**Comment by sdwilsh** [comment]
I really don't know Buck's Apple stuff very well.  @ryu2 or @Coneko might be able to answer your question.

**Comment by Coneko** [comment]
Correct, tests will build using Xcode even when using `--build-with-buck`, so if the build is set up correctly only for Buck, they won't work, but you can run them on the command line.
