### ISSUE TITLE
Please add support for Windows Operating System

### ISSUE THREAD

**Issue by MichaelTamm** [facebook/buck#111]

**Comment by Coneko** [comment]
Support for power shell is improving. We can now run Buck's tests! Most of them still fail though.

**Comment by sdwilsh** [comment]
What do you need, specifically?  At this point, Android stuff is pretty solid on Windows, but I'm interested to know what you might need.

**Comment by Coneko** [comment]
Windows support is not finished yet but it's now at the point where we can file issues for specific bugs and features with it.
