### ISSUE TITLE
How to use the static library with the extension ".framework"?

### ISSUE THREAD

**Issue by MCA-FSF** [facebook/buck#1111]
I know how to use the static library with the extension `".a"`, but what should I do with the extension `".framework"`?
Thanks!

**Comment by alisdair04** [comment]
https://buckbuild.com/rule/apple_library.html

**Comment by MCA-FSF** [comment]
I am very very sorry, i did't express clearly. I know `frameworks` must be a path starting with $SDKROOT or $PLATFORM_DIR.  If i want use static library with the extension `".framework"` that comes from third-party, how to configure build file？

**Comment by ryu2** [comment]
Check out `prebuilt_apple_framework`.  It's currently a work in progress and not documented yet, but you can look at the integration test in 

`test/com/facebook/buck/apple/testdata/prebuilt_apple_framework_static`

for an example.

**Comment by MCA-FSF** [comment]
Is there has field in `prebuilt_apple_framework` that like `header_namespace` in prebuilt_cxx_library?

**Comment by MCA-FSF** [comment]
Hi, @ryu2 , Now we have a Xcode project with three extensions that using swift. I want to know does buck work with swift? 
Another thing that I care about is that there is a [graph](https://buckbuild.com/article/exopackage.html) that comparing performance  improvements in build times for Buck vs. Gradle. Is there some comparation between buck and Xcode? 
Thank you very much.

**Comment by Coneko** [comment]
It's not faster than Xcode on a single machine. You need to use the distributed cache for Buck to be faster.

**Comment by ryu2** [comment]
cc @robbertvanginkel who did the work for `prebuilt_apple_framework`

**Comment by ryu2** [comment]
>  I want to know does buck work with swift?

Yes, we have basic Swift support although it's a work in progress.  If you have specific problems, please open a separate issue.
