### ISSUE TITLE
Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by MCA-FSF** [facebook/buck#1112]
when I build my code,  I got the error that showing below. What should I do？ thanks！！！
**`Undefined symbols for architecture x86_64`**:
Buck
  "_SCNetworkReachabilityCreateWithAddress", referenced from:
      +[Reachability reachabilityWithAddress:] in libReachability.a(Reachability.m.o)
  "_SCNetworkReachabilityCreateWithName", referenced from:
      +[Reachability reachabilityWithHostName:] in libReachability.a(Reachability.m.o)
  "_SCNetworkReachabilityGetFlags", referenced from:
      -[Reachability currentReachabilityStatus] in libReachability.a(Reachability.m.o)
      -[Reachability isReachable] in libReachability.a(Reachability.m.o)
      -[Reachability isConnectionRequired] in libReachability.a(Reachability.m.o)
      -[Reachability isConnectionOnDemand] in libReachability.a(Reachability.m.o)
      -[Reachability isInterventionRequired] in libReachability.a(Reachability.m.o)
      -[Reachability isReachableViaWWAN] in libReachability.a(Reachability.m.o)
      -[Reachability isReachableViaWiFi] in libReachability.a(Reachability.m.o)
      ...
  "_SCNetworkReachabilityScheduleWithRunLoop", referenced from:
      -[Reachability startNotifier] in libReachability.a(Reachability.m.o)
  "_SCNetworkReachabilitySetCallback", referenced from:
      -[Reachability startNotifier] in libReachability.a(Reachability.m.o)
  "_SCNetworkReachabilityUnscheduleFromRunLoop", referenced from:
      -[Reachability stopNotifier] in libReachability.a(Reachability.m.o)
`**ld: symbol(s) not found for architecture x86_64**`
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by alisdair04** [comment]
Thanks for the report.

This looks like a problem with your code and not Buck; the linker is saying that symbols cannot be found. You might also have forgotten to declare some dependencies. 

If you need further help, please provide a minimal project in a zip file and steps for how to reproduce this error.

**Comment by ryu2** [comment]
You need to include the `SystemConfiguration` framework in the `frameworks` section of your `apple_binary`.  I.e.

```

  frameworks = [
...
    '$SDKROOT/System/Library/Frameworks/SystemConfiguration.framework',
...
  ],
```
