### ISSUE TITLE
Buck can't find ANDROID_SDK even though it's set

### ISSUE THREAD

**Issue by bishopmatthew** [facebook/buck#1126]
I'm following the [Android version of the getting started guide](https://buckbuild.com/setup/getting_started.html) and I'm having trouble. I just built buck from source, but then when I try to build the Android sample it fails saying I need to set ANDROID_SDK. The problem is I already have that set. Pretty confused about what could be happening. 

Let me know if you need more info.

```
$ git clone https://github.com/fbsamples/bucksamples.git
Cloning into 'bucksamples'...
remote: Counting objects: 499, done.
remote: Total 499 (delta 0), reused 0 (delta 0), pack-reused 499
Receiving objects: 100% (499/499), 969.56 KiB | 739.00 KiB/s, done.
Resolving deltas: 100% (138/138), done.
$ cd bucksamples/cross-platform-scale-2015-demo/
$ buck build demo_app_android
Using watchman.
[-] PROCESSING BUCK FILES...FINISHED 0.1s [100%] 🐳  New buck daemon
[+] DOWNLOADING... (0.00 B/S, TOTAL: 0.00 B, 0 Artifacts)
[+] BUILDING...1.1s [42%] (6/14 JOBS, 5 UPDATED, 3 [21.4%] CACHE MISS)
 |=> IDLE
 |=> IDLE
 |=> IDLE
 |=> IDLE
 |=> IDLE
 |=> IDLE
 |=> IDLE
 |=> IDLE
BUILD FAILED: Must set ANDROID_SDK to point to the absolute path of your Android SDK directory.
$ echo $ANDROID_SDK
/usr/local/Cellar/android-sdk/24.1.1_1
$
```

It even shows that it found it in the log from that run:
```
buck-out//log/buck-1.log:[2017-01-13 11:42:12.434][debug][command:48c30408-7d14-41ff-8a52-ea09260d3488][tid:44][com.facebook.buck.json.ProjectBuildFileParser] Starting buck.py command: [...] ANDROID_SDK=/usr/local/Cellar/android-sdk/24.1.1_1 [...]
```

**Comment by sdwilsh** [comment]
What are the contents of `/usr/local/Cellar/android-sdk/24.1.1_1`?

**Comment by JoelMarcey** [comment]
@bishopmatthew Can you try setting $ANDROID_SDK to just `/usr/local/Cellar/android-sdk/` and see if you get the same problem?

**Comment by bishopmatthew** [comment]
Really sorry, turns out it was a typo (24.1.1_1 should have been 24.4.1_1). Ugh I spent forever looking at both and never noticed it.

**Comment by JoelMarcey** [comment]
@bishopmatthew Ah -- I didn't notice that either. Good catch!

**Comment by sdwilsh** [comment]
No problem.  My usual trick is to `ls $ANDROID_SDK` and that will fail if it's the wrong path :)
