### ISSUE TITLE
the parent bundle has the same identifier as sub-bundle 

### ISSUE THREAD

**Issue by MCA-FSF** [facebook/buck#1135]
When I run  [simple_app_with_extension](https://github.com/facebook/buck/tree/master/test/com/facebook/buck/apple/testdata/simple_app_with_extension) with target `//:DemoAppWithExtension`，there was some error， error message is：
 An error was encountered processing the command (domain=MIInstallerErrorDomain, code=57):
The parent bundle has the same identifier (com.example.DemoApp) as sub-bundle at /Users/FSF/Library/Developer/CoreSimulator/Devices/8D8299E8-E899-41C3-8DD6-A2A93175929F/data/Library/Caches/com.apple.mobile.installd.staging/temp.Cme0LH/extracted/DemoAppWithExtension.app/PlugIns/DemoExtension.appex
[2017-01-17 16:18:31.425][error][command:37a4cf54-738e-46bf-b3bd-0a7cd128137b][tid:131][com.facebook.buck.apple.simulator.AppleSimulatorController] [/Applications/Xcode.app/Contents/Developer/usr/bin/simctl, install, 8D8299E8-E899-41C3-8DD6-A2A93175929F, /Users/baidu/Desktop/simple_app_with_extension/buck-out/gen/DemoAppWithExtension#dwarf-and-dsym,iphonesimulator-x86_64,no-include-frameworks/DemoAppWithExtension.app] finished with unexpected result:
exit code: 57
stdout:
stderr:
An error was encountered processing the command (domain=MIInstallerErrorDomain, code=57):
The parent bundle has the same identifier (com.example.DemoApp) as sub-bundle at /Users/FSF/Library/Developer/CoreSimulator/Devices/8D8299E8-E899-41C3-8DD6-A2A93175929F/data/Library/Caches/com.apple.mobile.installd.staging/temp.Cme0LH/extracted/DemoAppWithExtension.app/PlugIns/DemoExtension.appex

**Comment by Coneko** [comment]
That's because both https://github.com/facebook/buck/blob/master/test/com/facebook/buck/apple/testdata/simple_app_with_extension/DemoExtension/Info.plist#L10 and https://github.com/facebook/buck/blob/master/test/com/facebook/buck/apple/testdata/simple_app_with_extension/Info.plist#L10 are `com.example.DemoApp`, the second one should probably be `com.example.DemoAppExtension` or something like that.

Feel free to send a PR.

**Comment by MCA-FSF** [comment]
I hope you can help to solve it because when I solved a error, a new error would come. Finally, the error as follows, and i don't know what should i do. Thanks.
PS: It can build correctly, but can't run.

An error was encountered processing the command (domain=MIInstallerErrorDomain, code=4):
Failed to chmod /Users/FSF/Library/Developer/CoreSimulator/Devices/31479CE8-5233-4EAE-8D1A-AD7666A58A64/data/Library/Caches/com.apple.containermanagerd/Bundle/Application/E89580FD-0757-467D-BE37-8E33B6FD3DA2/DemoAppWithExtension.app/PlugIns/DemoExtension.appex/ DemoApp : No such file or directory

**Comment by Coneko** [comment]
What files are in `/Users/FSF/Library/Developer/CoreSimulator/Devices/31479CE8-5233-4EAE-8D1A-AD7666A58A64/data/Library/Caches/com.apple.containermanagerd/Bundle/Application/E89580FD-0757-467D-BE37-8E33B6FD3DA2/DemoAppWithExtension.app/PlugIns/DemoExtension.appex/ `? It should be looking for a `DemoExtension` file there, not `DemoApp`. You need to update the `Info.plist` to reflect that.
