### ISSUE TITLE
name 'cxx_precompiled_header' is not defined

### ISSUE THREAD

**Issue by MCA-FSF** [facebook/buck#1136]
When I run  the [demo](https://github.com/facebook/buck/tree/950bcd2cc2f1dd3140f39771ce1f95c9a4c412ce/test/com/facebook/buck/cxx/testdata/cxx_precompiled_header_rule) with target `//:main`，the error as follows:
BUILD FAILED: Parse error for build file /Users/FSF/Desktop/cxx_precompiled_header_rule/BUCK:
NameError: name 'cxx_precompiled_header' is not defined.

**Comment by Coneko** [comment]
You might be using a version of Buck that is too old: try to build Buck from master and use that.
