### ISSUE TITLE
Xcode project doesn't run when build rules in different build files have the same name

### ISSUE THREAD

**Issue by ProfessaA** [facebook/buck#1139]
In the example project here (https://github.com/ProfessaA/BuckLibsWithSameName), `Lib1/BUCK` and `Lib2/BUCK` each have an `apple_library` rule named `Lib`.  When a third component depends on both `//Lib1:Lib` and `//Lib2:Lib`, it runs fine from the CLI.  However, the resulting xcode project fails to run.  Both targets have a `libLib.a` product and only one gets linked in, resulting in missing symbols.

I would like rule names to be symmetric across different build files so I don't want to have to change the rule names.  Is there a way around this, akin to the `product_name` attribute of `apple_bundle`?

**Comment by ProfessaA** [comment]
@ryu2 @Coneko is there any chance of supporting `product_name` for `apple_library` build rules and not just `apple_bundle`s?  `ProjectGenerator.getProductNameForTargetNode` has special support for `apple_bundles` that looks for the `product_name` attribute and it would be nice to extend that to `apple_library` as well.  

Also, it looks like `ProjectGenerator.generateBinaryTarget` sets the  product name to `getProductNameForBuildTarget`, which always uses the short name, but it seems like that should respect the `product_name` attribute.

Is there any temporary work around? I've tried setting `PRODUCT_NAME` in the `configs` attribute but it creates a disparity between the value in `project.pbxproj` (how it appears in xcode) and in the actual name of the generated lib, so this doesn't quite work.

**Comment by ryu2** [comment]
Yeah, you're right -- there currently isn't a nice way to do it.  What do you mean about "changing the rule names"?

You could try defining a macro that is shared between Lib1 and Lib2 which calls `apple_library` and prepends a unique prefix to the rule name, so you avoid repeating the common bits.

e.g.

```
# In DEFS
def my_apple_library(prefix, *args, **kwargs):
  apple_library(
    name = prefix + kwargs[name],
    kwargs)

# In Lib1/BUCK
my_apple_library('Lib1')

# In Lib2/BUCK
my_apple_library('Lib2')
```

**Comment by ProfessaA** [comment]
Hey, thanks for your response! By "change the rule names", I mean the `name` parameter used for the build rule, e.g. having to change `Lib1:Lib` to `Lib:Lib1Lib`.  Macros make the rule a little more clear during definition, but still require redundant namespacing when making references to the rule, as with`buck build Lib1:Lib1Lib` or having to refer to `:Lib1Lib` rather than just `:Lib1` when specifying dependencies for other rules in `Lib1/BUCK`.  

It seems like a shortcoming of Xcode that it can't distinguish between libraries of the same name produced by different projects.  It would be nice to be able to specify a product name that is only used when constructing xcode projects and is separate from the name parameter of the rule (or maybe to prepend the project name automatically to the product name) , since otherwise xcode imposes an unexpected, artificial constraint on the naming of build rules.

**Comment by v-jizhang** [comment]
Sorry we haven't update this issue for more than 3 years. At this point, we are closing this because it is quite out of date and it is not clear if the issue still exists. Please create a new one if you still see the problem. Thank you.
