### ISSUE TITLE
How to set up info.plist file for extension？

### ISSUE THREAD

**Issue by SwiftlyFly** [facebook/buck#1142]
Here is a today extension [demo](https://github.com/SwiftlyFly/TodayExtensionDemo). And I found it didn't execute the `TodayViewController` file. I have add a label to extension, but it didn't show it. Is there some error in build file or info.plist? 
And if I want to use storyboard to initialize the interface, How to do it ?

**Comment by ryu2** [comment]
For iOS extensions, you actually don't want the `#shared` flavor.

For storyboards, if you include the `xib` in `apple_resources` if should compile it automatically.

**Comment by SwiftlyFly** [comment]
I had set the `binary = ':DemoExtensionLibrary#shared'` for the [demo](https://github.com/SwiftlyFly/TodayExtensionDemo) but it did not work. The today extension is always show `“Unable to Load”` message.  It can't load `TodayViewController` file.
