### ISSUE TITLE
Distribute standalone buck binary

### ISSUE THREAD

**Issue by joewalnes** [facebook/buck#1146]
(feature request, not an issue)

It would be really convenient if as part of the releases https://github.com/facebook/buck/releases/, you shipped a standalone `buck` binary. i.e. The resulting `buck.pex`.

This is how I distribute buck within my organization as it works on both linux and mac environments seamlessly.

**Comment by Coneko** [comment]
cc @sdwilsh

**Comment by styurin** [comment]
Check the readme: https://github.com/facebook/buck#prebuilt-buck-binaries
