### ISSUE TITLE
Getting started documentation

### ISSUE THREAD

**Issue by sn-anura** [facebook/buck#1148]
Hi there,
After installing buck, I tried to follow the steps in "Getting started" in order to build the Java application sample.
Platform: Java
Development OS: macOS
In order to reproduce the problem I did the following:

`MDGBLOCR04-5604:~ anura$ mkdir trying-buck`
`MDGBLOCR04-5604:~ anura$ cd trying-buck/`
`MDGBLOCR04-5604:trying-buck anura$ git clone git@github.com:fbsamples/bucksamples.git`
`Cloning into 'bucksamples'...`
`remote: Counting objects: 516, done.`
`remote: Compressing objects: 100% (4/4), done.`
`remote: Total 516 (delta 0), reused 0 (delta 0), pack-reused 512`
`Receiving objects: 100% (516/516), 971.74 KiB | 816.00 KiB/s, done.`
`Resolving deltas: 100% (142/142), done.`
`MDGBLOCR04-5604:trying-buck anura$ cd bucksamples/hello-buck-java/`
`MDGBLOCR04-5604:hello-buck-java anura$ buck build hello-buck-java`
`Using watchman.`
`BUILD FAILED: No build file at hello-buck-java/BUCK when resolving target //hello-buck-java:hello-buck-java.`
`MDGBLOCR04-5604:hello-buck-java anura$ `

If you replace `-` with `_` it will just work as expected.
Regards

**Comment by JoelMarcey** [comment]
Thank you for noticing this. I will put a fix up asap.
