### ISSUE TITLE
where to define preprocessor macros?

### ISSUE THREAD

**Issue by SwiftlyFly** [facebook/buck#1150]
I want to configure "DEBUG" and "RELEASE" macros, where can i define it?

**Comment by illicitonion** [comment]
Wherever you want in your repo, and use include_defs (https://buckbuild.com/function/include_defs.html) to include them. At Facebook we tend to use files named DEFS or BUILD_DEFS.

**Comment by SwiftlyFly** [comment]
In my project, there is much code like this:
 ```
 #ifdef DEBUG
    NSLog(@"log");
 #endif
```
Now, I need define preprocessor macros to deal with it. It didn't work if i define marcos in file named DEFS.  I had set DEFS file in `buildfile` field.  Do you can give me a example how to define it in DEFS file? Thanks.

**Comment by illicitonion** [comment]
Aha. You need to set the preprocessor_flags attribute on your rules, e.g. https://buckbuild.com/rule/apple_library.html#preprocessor_flags
