### ISSUE TITLE
Add support for multiple dirs in project_res and project_assets args in android_resource rule

### ISSUE THREAD

**Issue by seanabraham** [facebook/buck#1156]
The newly added `project_res` and `project_assets` arguments on the `android_resouce` rule only support one directory but there are cases where you would want to specify multiple, such as in a top level application module that has multiple buildTypes or flavors.

cc @kageiit

**Comment by k21** [comment]
Did you try not specifying those attributes? In that case Buck should generate appropriate symlink trees based on the `res` and `assets` attributes which support an arbitrary number of source directories. The `project_*` attributes should only be useful if artifact building during project generation is disabled.

**Comment by seanabraham** [comment]
Without specifying, the `iml` files generated via `buck project` have a line like 
`<option name="RES_FOLDERS_RELATIVE_PATH" value="/src/debug/res;/src/main/res" />` but it doesn't behave as expected. Resources don't resolve properly in the IDE (they try to reference the IDE generated files in `buck-out/android` which don't have any members (or buck generated if project.disable_r_java_idea_generator = true in `.buckconfig`). Deleting the generated `buck-out/android` folder causes resources to resolve properly but the IDE isn't able to preview them at all.

**Comment by seanabraham** [comment]
With @kageiit I've found that adding a `RES_FOLDER_RELATIVE_PATH` option to all the `iml` files causes IntelliJ to behave better. (cmd+clicking them still hops to the decompiled `.class` file but at least string and drawable previews show up in line).

**Comment by kageiit** [comment]
I have a change ready locally that uses

```    res = res_glob([
        ('src/main/res', '**'),
        ('src/debug/res', '**'),
    ]),
    project_res = ['src/main/res', 'src/debug/res'],
```

in the `BUCK` file and produces `<option name="RES_FOLDERS_RELATIVE_PATH" value="/src/main/res;/src/debug/res" />` in the iml as expected. The resource roots then resolve correctly.

@k21 We do not want to reference resources from the generated folder. In the ide, the resource folders right next to the source in a gradle like project structure are more relevant. The current behavior excludes them and marks them as red and it is very confusing

**Comment by kageiit** [comment]
Actually it seems that Intellij is happy to get a reference to the symlinktree. However the problem is that the folder that it is symlinking to is being excluded. I.e the problem is something like this

```
<option name="RES_FOLDERS_RELATIVE_PATH" value="/../buck-out/gen/fleet/res_debug#resources-symlink-tree/res>

<excludeFolder url="file://$MODULE_DIR$/src/main/res" />
```

This effectively disables the symlinktree from working. Deleting the excludeFolder entry seems to fix that

**Comment by kageiit** [comment]
cc @styurin

**Comment by kageiit** [comment]
For a project with gradle like strcuture, This snippet of change made all the symbols resolve work correctly again.

```
diff --git a/src/com/facebook/buck/jvm/java/intellij/IjProjectTemplateDataPreparer.java b/src/com/facebook/buck/jvm/java/intellij/IjProjectTemplateDataPreparer.java
index dfa588a4c..10682a8ab 100644
--- a/src/com/facebook/buck/jvm/java/intellij/IjProjectTemplateDataPreparer.java
+++ b/src/com/facebook/buck/jvm/java/intellij/IjProjectTemplateDataPreparer.java
@@ -240,7 +240,10 @@ public class IjProjectTemplateDataPreparer {
     ImmutableSortedSet<IjSourceFolder> sourceFolders = simplifiedFolders
         .stream()
         .map(transformToFolder::apply)
+        .filter(folder -> !(folder.getType().equals("excludeFolder")
+            && (folder.getUrl().endsWith("/res") || folder.getUrl().endsWith("/assets"))))
         .collect(MoreCollectors.toImmutableSortedSet(Ordering.natural()));
+
     return ContentRoot.builder()
         .setUrl(url)
         .setFolders(sourceFolders)
diff --git a/src/com/facebook/buck/jvm/java/intellij/ij-module.st b/src/com/facebook/buck/jvm/java/intellij/ij-module.st
index 48f442413..fcc138839 100644
--- a/src/com/facebook/buck/jvm/java/intellij/ij-module.st
+++ b/src/com/facebook/buck/jvm/java/intellij/ij-module.st
@@ -8,6 +8,7 @@
         <option name="GEN_FOLDER_RELATIVE_PATH_AIDL" value="%androidFacet.module_gen_path%" />
         <option name="MANIFEST_FILE_RELATIVE_PATH" value="%androidFacet.android_manifest%" />
         <option name="RES_FOLDERS_RELATIVE_PATH" value="%androidFacet.res%" />
+        <option name="RES_FOLDER_RELATIVE_PATH" value="/src/main/res" />
         <option name="ASSETS_FOLDER_RELATIVE_PATH" value="%androidFacet.asset_folder%" />
         <option name="LIBS_FOLDER_RELATIVE_PATH" value="%androidFacet.libs_path%" />
         <option name="APK_PATH" value="%androidFacet.apk_path%" />
```

There still seem to be many general issues with buck project file generation for projects that have a gradle like structure. Missing paths or paths pointing to the filesystem where there are no generated files (like the `MANIFEST_FILE_RELATIVE_PATH` for a project which is not a library is always set to a file that does not exist yet) even when `buck project` is invoked with building.
