### ISSUE TITLE
Make it possible to share Buck rules between different projects

### ISSUE THREAD

**Issue by davido** [facebook/buck#116]
When a build process for a non trivial project (e. g. Gerrit Code Review) is implemented in Buck, a lot of custom scripts/recipes are created. It turns out that substantial part of these scripts/recipes is very useful and urgently needed for other projects.

Currently there is no built in way in Buck to share/reuse scripts/recipes between projects.
One option would be to use bucklets: number of build.defs and python_scripts files:

Project `foo` defines bucklet `local_jar()` [1] and publishes it with `deploy_bucklet('local_jar')`

Project `bar` (unrelated to project `foo`/or a plugin for project `foo`) reuses that bucklet with: `import_bucklet('local_jar')`.

Gerrit Code Review project has created bucklets [2] project and it is currently hosted on gerrit-review. First project from Gerrit eco system was migrated to Buck (re-)using only bucklets as Git submodule [3].

Please help to upstream that in one or another way. It's urgently needed to move further projects from Gerrit eco system (e. g. Gerrit plugins, JGit, EGit, ...) to Buck without code duplication.

[1] https://gerrit.googlesource.com/bucklets/+/master/local_jar.bucklet
[2] https://gerrit.googlesource.com/bucklets
[3] https://gerrit.googlesource.com/gitiles

**Comment by Coneko** [comment]
You'd have to check out the remote repo locally, maybe as a submodule or something like that.

**Comment by sdwilsh** [comment]
We actually backed out the cross repo stuff as it wasn't working correctly anymore.

**Comment by Coneko** [comment]
We're still planning on adding it, we just decided we are better off rewriting it from scratch.

**Comment by LegNeato** [comment]
Cross repo stuff is in now, right?

**Comment by k21** [comment]
Cross repo (or cross cell, as we are going to call it) is currently under development and although preliminary support has landed in the master branch, most build rules do not support it properly yet.

**Comment by sdwilsh** [comment]
It should be in within a month would be my guess.  You could probably start to play with it seriously as early as next week.
________________________________

**Comment by davido** [comment]
> Cross repo (or cross cell, as we are going to call it) is currently under development and although preliminary support has landed in the master branch, most build rules do not support it properly yet.

Can the `cell` support be extended to non locally cloned repositories? The idea behind plugins or extensions or bucklets concept is to make them first-class citizens in Buck. In similar way, Buck allows to specify what buck version to use in .buckversion file, I would expect to be able to provide some meta data for `cell` without actually cloning it:

```
  [cell name = "bucklets"]
    remote =  https://github.com/davido/bucklets
    version = d2936a48fc559e90b66e83de7ff163202e75486b
    # optional, with sensible default, e.g.
    # local = $HOME/.bucklets
```

in some configuration file, and without cloning this repo, or adding it to my own project as a submodule. I should be able to say `include_defs('//bucklets/gerrit_plugin.bucklet')` and just use `gerrit_plugin` rule. See also how the cross repo rule sharing is implemented in Gerrit plugin by using Git submodule concept: [1]. The problem to solve is, that `buck build foo` would need to take care for checking and cloning the `cell(s)` for me and make them accessible (I call this "mount") from within build rules, like `//foo/bar/baz, where `foo` is a known `cell` and also from the shell, because Eclipse project generation is implemented as a standalone Python script: [2] and currently invoked as:

```
  ./bucklets/tools/eclipse.py
```

Another approach would be to add dedicated Buck command to handle that with say `buck getcell`, something similar is done with Golang's `go get`: [3] command:

```
get download and install packages and dependencies
```

[1] https://github.com/davido/gerrit-oauth-provider/blob/master/BUCK#L1,L24
[2] https://github.com/davido/bucklets/blob/master/tools/eclipse.py
[3] https://golang.org/cmd/go

**Comment by davido** [comment]
I started to implement cross cell support in gerrit, to simplify workflow for integration of WIP stuff across project boundaries. One typical example of it include changes in JGit (main Gerrit dependency and Git implementation in Java programming language), Gerrit itself and dedicated plugin, when the feature implementation is split in core and plugin part, like for example LFS support to allow plugin to provide their own specific protocol implementations: [1]. [2], [3].

I hope that cross cell support, isolating jgit in gerrit project in its own cell, can solve this. It would work as is per default and could be hijacked per CLI option and be routed to JGit development tree. I still have some issues to make it actually work and filed #544 and #545.

Another problem I'm facing is the missing support for `include_def()` across cell boundaries. My hope was, that when fetching of cell is solved, the cross-cell concept would replace git submodules for reusing of Buck build files, see https://github.com/davido/bucklets.

So when a plugin is implemented standalone Buck build (outside of gerrit tree), see for example: https://github.com/davido/gerrit-oauth-provider it's basically consuming pre-defined bucklet: [4]

```
  include_defs('//bucklets/gerrit_plugin.bucklet')
```

Right now I'm getting error: "include should start with '//' or some such" when i was trying to pass cell prefix: `@bucklets//gerrit_plugin.bucklet`to `include_def()`. Is this something that will be supported in future or cell concept is mainly to share rules and not build files? In which case we still don't have any replacement for git submodules? 

* [1] https://git.eclipse.org/r/61472/
* [2] https://gerrit-review.googlesource.com/72891
* [3] https://gerrit-review.googlesource.com/72892
* [4] https://github.com/davido/bucklets/blob/master/gerrit_plugin.bucklet

**Comment by davido** [comment]
Two years later, after this issue was created, I've discovered, that Bazel team released the cross project dependency support, with the ability to fetch the deps from remot repositories, "mount" and re-use them in build toolchain: [1].

```
git_repository(
    name = "io_bazel_rules_scala",
    remote = "https://github.com/bazelbuild/rules_scala.git",
    tag = "0.0.1",
)
load("@io_bazel_rules_scala//scala:scala.bzl", "scala_repositories")
scala_repositories()
```

[...]

This will download all of the tools the rules need to build Scala programs.
Then load and use normally from your BUILD files:

```
load("@io_bazel_rules_scala//scala:scala.bzl", "scala_library")
scala_library(...)
```

We have extracted Bucklets from Gerrit Code Review build tool chain: [2]. Unfortunately, Buck still doesn't have support for fetching and using external Buck scripts. And it's just annoying to link Bucklets as git submodules to each and every Gerrit Code Review plugin: [3].

[1] http://www.bazel.io/blog/2016/02/23/0.2.0-release.html
[2] https://github.com/davido/bucklets
[3] https://github.com/davido/gerrit-oauth-provider

**Comment by v-jizhang** [comment]
Hi, this is is closed because there is no updates for over 3 years. Thanks
