### ISSUE TITLE
 How to adjust Header Search Paths?

### ISSUE THREAD

**Issue by SwiftlyFly** [facebook/buck#1161]
Now I use the library `libxml2.dylib`, in order to work correctly i need to adjust header search paths to point at the libxml headers,  In  Xcode i can set it as `${SDKROOT}/usr/include/libxml2`.  how to do it for Buck?

**Comment by LegNeato** [comment]
What type of rule? This may be relevant:

https://buckbuild.com/rule/prebuilt_cxx_library.html#include_dirs

**Comment by SwiftlyFly** [comment]
The type of rule is `apple_library`, the rule define as 
```
apple_library(
  name = 'example',
  libraries = [
    '$SDKROOT/usr/lib/libxml2.dylib',
  ],
  visibility = ['PUBLIC'],
)
```
When i import the header such as `#import <libxml/HTMLparser.h>`,` HTMLparser.h` can't be found. I should adjust header search paths to `${SDKROOT}/usr/include/libxml2` in order to found header files. The default search path is `${SDKROOT}/usr/include`.

**Comment by Coneko** [comment]
You can add `${SDKROOT}/usr/include/libxml2` to `exported_preprocessor_flags`.

**Comment by SwiftlyFly** [comment]
@Coneko  Assumimg BUCK file at `//dir1/dir2`,  but i want to adjust header search path to `//dir1`, what format i should add to `exported_preprocessor_flags`?  It can be achieved?

**Comment by Coneko** [comment]
If you want to refer to headers inside your source tree you should use https://buckbuild.com/rule/apple_library.html#exported_headers, not `exported_preprocessor_flags`.
