### ISSUE TITLE
Libprojects from different folder error

### ISSUE THREAD

**Issue by Still4** [facebook/buck#1162]
we have multiple andoird apps, 3rd party libs are the same, and sometimes we need to update them, so we have a AndroidLib folder to deal with them.
our settings.gradle is set like this:

> include ':Adjust'
project(':Adjust').projectDir = new File(settingsDir, '../AndroidLib/Adjust')
include ':BaseGameUtils'
project(':BaseGameUtils').projectDir = new File(settingsDir, '../AndroidLib/BaseGameUtils')
include ':FacebookSDK'
project(':FacebookSDK').projectDir = new File(settingsDir, '../AndroidLib/FacebookSDK')
include ':app'
project(':app').projectDir = new File(settingsDir, 'app')

the problem is, in generated buck files, we lose AndroidLib configs, like this
> '//BaseGameUtils:res_BaseGameUtils',
'//BaseGameUtils:src_release',
'//FacebookSDK:res_FacebookSDK',
'//FacebookSDK:src_release',

how do we solve this problem

**Comment by Still4** [comment]
[https://github.com/facebook/buck/issues/838](url)
We found a solution in this issue, but occurred another problem

> * What went wrong:
> Execution failed for task ':okbuck'.
> Local dependencies should be under project root. Dependencies outside the project can cause hard to reproduce builds. Please move dependency: /azclient/AndroidLib/ChatServices/libs/activity_entry_name.jar inside /azclient/Google
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
> 
> BUILD FAILED

**Comment by Coneko** [comment]
It seems this issue relates to https://github.com/uber/okbuck/, not Buck itself.

Please open an issue on that repo instead.
