### ISSUE TITLE
Buck support for vector drawable workaround?

### ISSUE THREAD

**Issue by bgwines** [facebook/buck#1165]
Hi, there,

I've been encountering [this issue](http://stackoverflow.com/questions/35622438/update-android-support-library-to-23-2-0-cause-error-xmlpullparserexception-bin) and the Gradle way around it is to apply the following configuration:

    defaultConfig {
        vectorDrawables.useSupportLibrary = true
    }

Does Buck offer a method to accomplish the same goal? Thanks so much!

**Comment by sdwilsh** [comment]
You'd need to take a dependency on the appropriate jars by either vendoring them in or using a `prebuilt_java_libarary` rule wrapping a `remote_file` rule.

https://developer.android.com/studio/build/dependencies.html#view_the_dependency_tree shows an example dependency tree as a result; you'd need to specify this with Buck.

**Comment by bgwines** [comment]
thanks for the prompt response! :) We found an even simpler solution, actually, just now -- turns out you can pass in `includes_vector_drawables = True` to `android_binary`!

**Comment by sdwilsh** [comment]
Oh hey, that's documented!  https://buckbuild.com/rule/android_binary.html#includes_vector_drawables

**Comment by bgwines** [comment]
haha; yeah -- things in general are hard to find if you don't know the exact name of what you're looking for, unfortunately. Definitely a user error on our end for not finding this, though. Thanks so much!
