### ISSUE TITLE
Jython should be a supported Python interpreter

### ISSUE THREAD

**Issue by shs96c** [facebook/buck#1166]
Many people want to use Buck on (Windows) machines where they don't have admin privileges. For these users, it's advantageous to be able to use jython instead of a system python. Right now, trying this leads to:

https://gist.github.com/ragePowered/d6242af9cc37de882a47a96cc2e720f0

**Comment by sdwilsh** [comment]
That looks like PEX code which is part of twitter-commons.

**Comment by v-jizhang** [comment]
Sorry we never got back to this! At this point, we are closing this because it is quite out of date and it is not clear if the issue still exists. Please create a new one if you still see the problem. Thank you.
