### ISSUE TITLE
Improve scenario for dependencies on external repos

### ISSUE THREAD

**Issue by fkorotkov** [facebook/buck#1167]
It will be nice to have something similar to what [Bazel has](https://bazel.build/versions/master/docs/be/workspace.html#new_http_archive):

```
new_http_archive(
    name = "my_ssl",
    url = "http://example.com/openssl.zip",
    sha256 = "03a58ac630e59778f328af4bcc4acb4f80208ed4",
    build_file = "BUILD.ssl",
)
```

in order to depend on external projects without a need to check then in the repo on every update.

Relates to: https://github.com/facebook/buck/issues/116

**Comment by sdwilsh** [comment]
You should be able to already do this with `remote_file` rules and `genrule` to do the unzipping for you (or write some python to work cross-platform).

**Comment by fkorotkov** [comment]
@sdwilsh what about having a `BUCK` for them? I know I can use genrule to run something. But how for example I can have a `genrule` that will generate sources for my `apple_library` for example?

**Comment by fkorotkov** [comment]
I basically want something like:

```
remote_file(
  name = 'SomePodSources',
  visibility = ['PUBLIC'],
  url = 'https://github.com/ABC/pod/releases/download/0.3.1/pod-v0.3.1.zip',
  sha1 = '3f230c063f2a219605db17af479919f75e4e6926',
  type = 'exploded_zip'
)

apple_library(
  name = 'SomePod',
  context = ':SomePodSources'
  info_plist = 'Info.plist',
  srcs = glob(['*.swift']),
  ...
)
```

in this case `context` field will tell Buck to put outputs of `SomePodSources` so they are available as `srcs`

**Comment by sdwilsh** [comment]
You could write specific `genrule`s to unpack and then reference in other rules, but there's nothing general.  This would be a pretty big change in Buck since it'd require a second stage of parsing.

**Comment by fkorotkov** [comment]
But it will be super nit for OSS projects outside of a monorepo :-)

**Comment by aiked** [comment]
Being honest, I put this under our wish list. But we also accept pull requests.
