### ISSUE TITLE
Import and export support for aar

### ISSUE THREAD

**Issue by dreiss** [facebook/buck#117]
Android has defined the "aar" format for standalone android libraries.  Some very sparse documentation is at http://tools.android.com/tech-docs/new-build-system/aar-format

It would be great if Buck had support for importing these into a project using a "prebuilt_aar" rule and exporting them using a "build_aar" rule (or some other name; "android_library" and "android_binary" are already taken).

Executing prebuilt_aar would probably just involve unzipping the archive.  Then the existing machinery in android_{library,binary,resource,manifest} would need to be updated to
- Treat classes.jar kind of like a prebuilt jar.
- Include AndroidManfiest.xml in manifest merging.
- Include assets and resources in appropriate aapt commands (in android_resource, dummy/uber R.java, and aapt_package).
- Include native libraries in apkbuilder.
- Include proguard.txt in the proguard step.
This might be most easily implemented by exposing all of these components through a generic AndroidPackageComponent interface, and making the existing android rules implement that to expose their own contents.

Producing an aar would entail
- Producing classes.jar like a java_binary.
- (optionally) producing AndroidManifest.xml like an android_manifest
- Assembling proguard.txt like in android_binary
- Manually assembling resources and assets
- Producing R.txt like android_resource

**Comment by Coneko** [comment]
We have this now with android_aar and android_prebuilt_aar.
