### ISSUE TITLE
fatal error: 'pop/POPDefines.h' file not found

### ISSUE THREAD

**Issue by MCA-FSF** [facebook/buck#1170]
When I use [pop](https://github.com/facebook/pop) and  build it, I get the following error:
'fatal error: 'pop/POPDefines.h' file not found'.

**Comment by aiked** [comment]
Why do you assume this is a fault of Buck? Did you change buck versions and that happened?

**Comment by MCA-FSF** [comment]
I don't think it is a fault of Buck and I have updated the Buck to the latest version.

**Comment by aiked** [comment]
Is the file there? Do you know what target actually includes the header somewhere?

**Comment by aiked** [comment]
Open this again if you still have an issues but it doesn't look we can help you with this. It looks like a project specific issue.

**Comment by SwiftlyFly** [comment]
By setting `header_namespace = 'pop'`, the header can be found , but there is a new error happened. Some messages as follows:
BBAPods/ThirdPartyLibs/pop/POPPropertyAnimationInternal.h:262:14: note: built-in candidate operator==(unsigned __int128, int)
BBAPods/ThirdPartyLibs/pop/POPPropertyAnimationInternal.h:262:14: note: built-in candidate operator==(unsigned long long, int)
BBAPods/ThirdPartyLibs/pop/POPPropertyAnimationInternal.h:262:14: note: built-in candidate operator==(unsigned long, int)
BBAPods/ThirdPartyLibs/pop/POPPropertyAnimationInternal.h:262:14: note: built-in candidate operator==(float, int)
BBAPods/ThirdPartyLibs/pop/POPPropertyAnimationInternal.h:262:14: note: built-in candidate operator==(unsigned int, int)
BBAPods/ThirdPartyLibs/pop/POPPropertyAnimationInternal.h:262:14: note: built-in candidate operator==(__int128, int)
