### ISSUE TITLE
Error `test exited before generating results file` when running robolectric tests

### ISSUE THREAD

**Issue by raviagarwal7** [facebook/buck#1172]
seeing this error when running tests in target with more than 1500 test files
```
FAIL    <100ms  0 Passed   0 Skipped   1 Failed   <test-class>
FAILURE <test-class> main: test exited before generating results file

====STANDARD OUT====

====STANDARD ERR====
...
```
Happens for almost half of the test files in the target (similar to above output exits <100 ms) and rest passes successfully.
Running these tests individually using `--test-selectors` works but collectively they fail.

- by default running with ForkMode as `None`.
- tried passing more heap space in vm_args `'-Xmx4g'`.
- tried creating multiple JunitSteps by bucketing test files into groups of 200 but still no luck.

**Comment by marcinkosiba** [comment]
This usually means that the test crashed before the test runner started running. have you looked into the log file? Is there something like a class loading exception?

**Comment by aiked** [comment]
I will close this since we didn't have an answer. @raviagarwal7 feel free to reopen if you have more info.

**Comment by raviagarwal7** [comment]
sorry forgot to respond here. As @marcinkosiba mentioned it was happening because the java process crashed in between the test runs. Fixing individual test classes fixed the overall run.

**Comment by aiked** [comment]
@raviagarwal7 Glad this got resolved.

**Comment by jiangjef** [comment]
@raviagarwal7 Hi I am running into similar problems. How did you find out which tests caused the crash?
