### ISSUE TITLE
Buck fails to get swift 2.3 toolchains identifier for Xcode Beta

### ISSUE THREAD

**Issue by nguyentruongtho** [facebook/buck#1173]
Buck realizes on `ToolchainInfo.plist` and `Info.plist` to get identifiers for the toolchains. It seems that Xcode Beta shipped builtin swift 2.3 without those files.

```
➜  buck git:(tho/test_toolchains) ls -al /Applications/Xcode-beta.app/Contents/Developer/Toolchains/Swift_2.3.xctoolchain/
total 0
drwxr-xr-x  3 thonguyen  staff  102  3 Feb 00:12 .
drwxr-xr-x  4 thonguyen  staff  136  3 Feb 06:31 ..
drwxr-xr-x  3 thonguyen  staff  102  3 Feb 00:13 usr
```

I think we can either ignore this and don't support swift 2.3 in this case or if there is a quick fix for it to get an swift 2.3 identifier in this case, then we should do it. Thought?

**Comment by ryu2** [comment]
@nguyentruongtho Have you filed a radar on Apple yet?  This should really be fixed on their end rather than hardcoding these workarounds in Buck.

**Comment by nguyentruongtho** [comment]
Good point, I'll do that instead. I also don' like changing buck for something like this.
