### ISSUE TITLE
UseConcMarkSweepGC java arg will cause buck daemon to be created every run

### ISSUE THREAD

**Issue by cwoodwar6** [facebook/buck#1175]
Steps to reproduce:
1.) Kill the Buck daemon
2.) In `.buckjavaargs` add the `-XX:+UseConcMarkSweepGC` flag.
3.) Build, new daemon is created.
4.) No changes. Build again, notice the daemon is created yet again with no indication as to why.

Without that flag, daemon is reused.

It also seems to affect the http server. I was not able to host the server with that flag added.

**Comment by v-jizhang** [comment]
Sorry we never got back to this! At this point, we are closing this because it is quite out of date and it is not clear if the issue still exists. Please create a new one if you still see the problem. Thank you.
