### ISSUE TITLE
Feature request: inline keystore properties

### ISSUE THREAD

**Issue by EmielM** [facebook/buck#1177]
For Android releases, I would not like to store release store/alias passwords in my repo. For production builds, I already have a mechanism in place to load a different global configuration object in my `BUCK` file.

It would therefor be convenient to make the password part of this configuration and supply it to the `keystore`'s `properties` instead of a path. Additionally, it would prevent cluttering my file tree with different 3-line files.

A quick look a the source indicates there already is some infrastructure to support this in the form of `KeystoreProperties.java`. It would require changes in `ApkBuilderStep.java` and `AndroidBinary.java` to support the different invocation.

The rule could then look like:
```python
keystore(
  name = 'key_release',
  store = 'keystore',
  properties = {
    'alias': 'androidreleasekey',
    'storepass': 'android',
    'keypass': config._androidReleasePass,
  },
)
```

Thoughts?

**Comment by v-jizhang** [comment]
Sorry we never got back to this! At this point, we are closing this because it is quite out of date and it is not clear if this feature is still needed. Please create a new one if you want this feature. Thank you.
