### ISSUE TITLE
cxx_binary linker_flags bug?

### ISSUE THREAD

**Issue by crylico** [facebook/buck#1182]
BUCK file:
```
cxx_binary(
  name = 'example',
  srcs = glob(['*.c']),
  linker_flags = [
    '<anything>'
  ]
)
```

Run `buck build example`.

`buck-out/bin/example/example#binary.argsfile`:

```
-o
buck-out/gen/example/example
<anything>
"buck-out/gen/example/example#compile-main.c.ofc85ff2c,default/main.c.o"
```

When building the above project (which only contains a single `main.c` file), linker flags are inserted after the -o <binary>, but before the inclusion of all object files.

Is there a way to have buck insert the linker_flags after the object files?

**Comment by Coneko** [comment]
Why do you need them after the object files?

**Comment by crylico** [comment]
I'm developing for Linux, using libcurl. This is effectively my exact situation: http://stackoverflow.com/questions/6302282/how-do-i-link-libcurl-to-my-c-program-in-linux

I was able to work around the issue by creating a "dummy library" with no files, but the linker flags I need in `exported_linker_flags`, then making the dummy library as a buck dependency for the binary. This resulted in `-lcurl` coming after the object files and a successful compilation/execution. 

While this works fine, it seems like a very improper solution. It's also possible that I am misunderstanding some part of the process and would appreciate any input :)

**Comment by v-jizhang** [comment]
Sorry we never got back to this! At this point, we are closing this because it is quite out of date and it is not clear if the issue still exists. Please create a new one if you still see the problem. Thank you.
