### ISSUE TITLE
Android resource generated assets folder is not created upon `buck clean` & `buck build <res-target>`

### ISSUE THREAD

**Issue by raviagarwal7** [facebook/buck#1184]
I am working on passing `assets` folder to robolectric runs similar to how we pass in the `res` folder. Seeing an issue where `res_release#assets-symlink-tree` folder is not created when building the robolectric test rule the second time after a `buck clean`. (although `res_release#resources-symlink-tree` is being created).

Below is the detailed analysis.

BUCK file setup:
```python
android_resource(
	name = 'res_release',
	package = 'com.core',
	res = res_glob([
		('src/main/res', '**'),
	]),
	assets = subdir_glob([
		('src/main/assets', '**'),
	]),
	.
	.
)

android_library(
	name = 'src_release',
	srcs = glob([
		'src/main/java/**/*.java',
	]),
	tests = [
		':test_release',
	],
	deps = [
		'//.okbuck/cache:com.android.support.animated-vector-drawable-25.0.1.aar',
		'//.okbuck/cache:com.android.support.appcompat-v7-25.0.1.aar',
		.
		.
		':res_release',
	],
	.
	.
)

robolectric_test(
	name = 'test_release',
	srcs = glob([
		'src/test/java/**/*.java',
	]),
	deps = [
		'//.okbuck/cache:com.android.support.animated-vector-drawable-25.0.1.aar',
		.
		.
		':res_release',
		':src_release',
	],
	.
	.
)
```

Building above rules & their generated output
```java
╰─$ rm -rf buck-out

╰─$ buck build //library/core:res_release
[-] PROCESSING BUCK FILES...FINISHED 0.0s
[-] DOWNLOADING... (17.56 MB/S AVG, TOTAL: 46.34 MB, 74 Artifacts)
[-] BUILDING...FINISHED 3.4s [100%] (76/76 JOBS, 76 UPDATED, 2 [2.6%] CACHE MISS)
    Details: http://localhost:50170/trace/acbea40f-e720-4dae-b463-31d850e75e77

╰─$ ls buck-out/gen/library/core
__res_release_text_symbols__       res_release#assets-symlink-tree    res_release#resources-symlink-tree

╰─$ buck build //library/core:src_release                                                                                                                
[-] PROCESSING BUCK FILES...FINISHED 0.0s
[-] DOWNLOADING... (16.67 MB/S AVG, TOTAL: 78.79 MB, 124 Artifacts)
[-] BUILDING...FINISHED 5.7s [100%] (189/189 JOBS, 117 UPDATED, 5 [2.6%] CACHE MISS)
    Details: http://localhost:50170/trace/0bd17869-5377-442d-8093-bbcc737be489

╰─$ ls buck-out/gen/library/core
__res_release_text_symbols__                          build_config_release#abi                              lib__src_release__output
__src_release#dummy_r_dot_java__srcs                  build_config_release.classes.txt                      res_release#assets-symlink-tree
__src_release#dummy_r_dot_java_dummyrdotjava_abi__    lib__build_config_release__output                     res_release#resources-symlink-tree
__src_release#dummy_r_dot_java_dummyrdotjava_output__ lib__src_release____working_directory                 src_release#abi,dummy_r_dot_java
__src_release__srcs                                   lib__src_release__abi                                 src_release.classes.txt

╰─$ buck build //library/core:test_release
[-] PROCESSING BUCK FILES...FINISHED 0.0s
[-] DOWNLOADING... (16.08 MB/S AVG, TOTAL: 163.68 MB, 149 Artifacts)
[-] BUILDING...FINISHED 11.3s [100%] (318/318 JOBS, 132 UPDATED, 17 [5.3%] CACHE MISS)
    Details: http://localhost:50170/trace/7730b6ac-8867-4a22-9dcf-c4e97c5d904f

╰─$ ls buck-out/gen/library/core
__res_release_text_symbols__                           build_config_release#abi                               res_release#assets-symlink-tree
__src_release#dummy_r_dot_java__srcs                   build_config_release.classes.txt                       res_release#resources-symlink-tree
__src_release#dummy_r_dot_java_dummyrdotjava_abi__     lib__build_config_release__output                      src_release#abi
__src_release#dummy_r_dot_java_dummyrdotjava_output__  lib__src_release____working_directory                  src_release#abi,dummy_r_dot_java
__src_release__srcs                                    lib__src_release__abi                                  src_release.classes.txt
__test_release#dummy_r_dot_java__srcs                  lib__src_release__output                               test_release
__test_release#dummy_r_dot_java_dummyrdotjava_abi__    lib__test_release#testsjar____working_directory        test_release#abi,dummy_r_dot_java
__test_release#dummy_r_dot_java_dummyrdotjava_output__ lib__test_release#testsjar__abi                        test_release#testsjar.classes.txt
__test_release#testsjar__srcs                          lib__test_release#testsjar__output

╰─$ buck clean

╰─$ buck build //library/core:res_release
[-] PROCESSING BUCK FILES...FINISHED 0.0s
[-] DOWNLOADING... (0.00 B/S AVG, TOTAL: 0.00 B, 0 Artifacts)
[-] BUILDING...FINISHED 0.1s [100%] (1/1 JOBS, 1 UPDATED, 0 [0.0%] CACHE MISS)
    Details: http://localhost:50170/trace/42fb72fc-0674-49a9-8399-6d3b7e5b1f96

╰─$ ls buck-out/gen/library/core
__res_release_text_symbols__

╰─$ buck build //library/core:src_release
[-] PROCESSING BUCK FILES...FINISHED 0.0s
[-] DOWNLOADING... (0.00 B/S AVG, TOTAL: 0.00 B, 0 Artifacts)
[-] BUILDING...FINISHED 0.1s [100%] (1/1 JOBS, 1 UPDATED, 0 [0.0%] CACHE MISS)
    Details: http://localhost:50170/trace/76388a6c-b485-4626-9369-eed6c6a578f8

╰─$ ls buck-out/gen/library/core
__res_release_text_symbols__ lib__src_release__output     src_release.classes.txt

╰─$ buck build //library/core:test_release                                                                                                               
[-] PROCESSING BUCK FILES...FINISHED 0.0s
[-] DOWNLOADING... (0.00 B/S AVG, TOTAL: 0.00 B, 0 Artifacts)
[-] BUILDING...FINISHED 0.4s [100%] (313/313 JOBS, 8 UPDATED, 0 [0.0%] CACHE MISS)
    Details: http://localhost:50170/trace/bc90f428-7771-42b7-a6d1-2997e3253794

╰─$ ls buck-out/gen/library/core
__res_release_text_symbols__                           lib__build_config_release__output                      src_release.classes.txt
__test_release#dummy_r_dot_java_dummyrdotjava_abi__    lib__src_release__output                               test_release
__test_release#dummy_r_dot_java_dummyrdotjava_output__ lib__test_release#testsjar__output                     test_release#abi,dummy_r_dot_java
build_config_release#abi                               res_release#resources-symlink-tree                     test_release#testsjar.classes.txt
build_config_release.classes.txt                       src_release#abi
```

Not sure if `android_resource` rule should generate the res & assets folder. Currently the robolectric_test rule generates it after `buck clean` which is why it works for resources but not for assets.

**Comment by raviagarwal7** [comment]
cc: @k21 @Coneko -- as you last touched this in https://github.com/facebook/buck/commit/3319cd6ce5c0126fea859932cc5c2494e95b63b9.

**Comment by k21** [comment]
This is most likely because the second time the target you built was already present in the cache and so its dependencies did not need to be built. If you want to pass the symlink tree to another rule, then explicitly reference the symlink tree target (e.g. with `:res_release#assets-symlink-tree`), not something that depends on it. Buck does not guarantee to build all dependencies of the target that you have requested.

**Comment by raviagarwal7** [comment]
the `robolectric_test` rule doesn't depend on `res_release#resources-symlink-tree` and the folder is still created when running `buck build //library/core:test_release`, but the assets one is not created. 
Seems like a difference in how resources & assets are handled by the robolectric test rule.

could you point me in buck which creates the `:res_release#resources-symlink-tree` folder -- I can look into the implementing something similar for assets.

Can we reopen the issue as it is still not resolved?

**Comment by k21** [comment]
Both resource and asset symlink trees are created in [AndroidResourceDescription](https://github.com/facebook/buck/blob/822608ad8200be15f74c96d76ea8e1eef1c2edc9/src/com/facebook/buck/android/AndroidResourceDescription.java#L107). It is possible that `robolectric_test` uses one of the two symlink trees directly and only depends on the other one transitively. In particular, [AndroidLibraryGraphEnhancer](https://github.com/facebook/buck/blob/822608ad8200be15f74c96d76ea8e1eef1c2edc9/src/com/facebook/buck/android/AndroidLibraryGraphEnhancer.java#L97) seems to collect all transitive resource dependencies and maybe they get used as direct dependencies later, which would explain why the symlink tree is always created. Assets, on the other hand, probably get aggregated into another rule first so the test rule does not depend on the symlink trees directly. Those are all implementation details though, adding an explicit dependency on the symlink tree you need should solve the problem without having to rely on Buck's internals.

Feel free to reopen the issue if you are planning to work on this, although note that always building all asset symlink trees when a test is built is probably not the right answer as they should not be required in most cases.

**Comment by raviagarwal7** [comment]
Thanks for the explanation @k21, will look into it.

I am adding support for passing assets to robolectric runs - https://github.com/facebook/buck/pull/1180/files. Idea is to create the asset symlink tree only if the assets folder is non-empty. Before passing the assets folder down we need to make sure that the folder is present (https://github.com/facebook/buck/pull/1180/files#diff-8058a85314af62be6be9cf59db009bb9R225) which never fails for resources.

**Comment by k21** [comment]
I see. In that case you will still want to make sure that both of the symlink tree rules are not only direct dependencies of the robolectric test rule, but also [runtime dependencies](https://github.com/facebook/buck/blob/822608ad8200be15f74c96d76ea8e1eef1c2edc9/src/com/facebook/buck/rules/HasRuntimeDeps.java#L40).

**Comment by raviagarwal7** [comment]
thanks @k21, was able to get it working by adding it to the runtime dependencies. could you please review - https://github.com/facebook/buck/pull/1180

**Comment by k21** [comment]
I am not the best person to review the diff, @marcinkosiba, @dreiss, and maybe @styurin are more familiar with it.

**Comment by raviagarwal7** [comment]
the pull request is merged now.
