### ISSUE TITLE
How to compile Objective-C++ file with c++11 feature?

### ISSUE THREAD

**Issue by SwiftlyFly** [facebook/buck#1185]
when I compiled Objective-C++ files, i meet erros like this:
error: no member named 'make_unique' in namespace 'std'
error:use of undeclared dentifier 'nullptr'

`nullptr` and `make_unique` are belong to c++11's feature.
I add `-Wc++11-extensions` to compiler_flags, but not worked.

**Comment by EmielM** [comment]
I'm using the (afaik undocumented) `lang_preprocessor_flags` directive, found by googling on github for more complex buck examples:

```python
apple_binary(
  name = 'myApp',
  preprocessor_flags = ['-fobjc-arc', '-fmodules'],
  lang_preprocessor_flags = {
    'OBJC': ['-std=gnu99'],
    'OBJCXX': ['-std=c++14', '-stdlib=libc++'],
  }
  ...
)
```
