### ISSUE TITLE
Location macro in python env rule breaks buck cache

### ISSUE THREAD

**Issue by nguyentruongtho** [facebook/buck#1186]
**Problem:**

`$(location)` macro always expands location to absolute path, see https://github.com/facebook/buck/blob/master/src/com/facebook/buck/rules/macros/LocationMacroExpander.java#L55, which is not suitable to be used in any rulekey arguments.

However, location macro can be used in [`PythonTest`](https://github.com/facebook/buck/blob/master/src/com/facebook/buck/python/PythonTest.java#L65) `env` arguments, which later on will be expanded to an absolute path before used as a rulekey.

This will breaks the cache consistency.

Propose solutions:

1. Remove `$(location)` macro from list of allowed macro: https://github.com/facebook/buck/blob/master/src/com/facebook/buck/python/PythonTestDescription.java#L70-L73

2. Create another macro for this thing: `$(relative_location)`?

3. Make location macro resolve target to relative path.

I think there must be a reason for location macro to use abs path? so (3) maybe not appropriate. 
Thought?

**Comment by nguyentruongtho** [comment]
@robbertvanginkel has an idea that we can expand the location macro in `PythonTest` instead of in `PythonTestDescription`.

**Comment by v-jizhang** [comment]
Sorry we never got back to this! At this point, we are closing this because it is quite out of date and it is not clear if the issue still exists. Please create a new one if you still see the problem. Thank you.
