### ISSUE TITLE
Watchman glob results contain dotfiles

### ISSUE THREAD

**Issue by nguyentruongtho** [facebook/buck#1187]
`watchman` glob contains dotfiles in its result.
Test case:

```
➜  watchman-test ls -al
total 8
-rw-r--r--   1 thonguyen  staff    0 15 Feb 16:42 .buckconfig
-rw-r--r--   1 thonguyen  staff   60 15 Feb 16:32 BUCK
drwxr-xr-x   3 thonguyen  staff  102 15 Feb 16:41 dummy

➜  watchman-test cat BUCK
python_test(
  name='test',
	resources=glob(['dummy/**']),
)%
➜  watchman-test find dummy
dummy
dummy/dummy
dummy/dummy/.buckconfig.fixture
```

`.buckconfig.fixture` should not be included in the resource files, since `include_dotfiles` is set to `False` by default.

However:

```
➜  watchman-test buck audit rules BUCK --config project.glob_handler=watchman
Using watchman.
# BUCK
python_test(
  name = "test",
...
  resources = [
    "dummy/dummy/.buckconfig.fixture",
  ],
...
)
➜  watchman-test buck audit rules BUCK --config project.glob_handler=python
# BUCK
python_test(
  name = "test",
...
  resources = [
  ],
...
)
```

This inconsistency will lead to different rulekeys of the same target across different machines.

It is very interesting that if I change the folder structure to this:
```
➜  watchman-test find dummy
dummy
dummy/.buckconfig.fixture
```

The results from python & watchman glob handlers are correct.

**Comment by sdwilsh** [comment]
@bhamiltoncx, was this a known limitation of the watchman glob?

**Comment by bhamiltoncx** [comment]
Nope, pretty sure this was working at one point in time.

**Comment by nguyentruongtho** [comment]
Update: I've just verified `watchman 4.6.0` doesn't have this issue.

**Comment by v-jizhang** [comment]
Tested. it has been fixed.
