### ISSUE TITLE
How to specify a file that using ARC Compile?

### ISSUE THREAD

**Issue by SwiftlyFly** [facebook/buck#1188]
Such there are many files in one directory. Now I need to compile `a.m` with non-ARC, and i should use `glob()` function to include source files, how can i configure build rule? I get some message from [here](https://github.com/facebook/buck/blob/8d699a924d67a258b301c5f0d7b4eec3f8c23bbb/test/com/facebook/buck/cxx/testdata/per_file_flags/BUCK.fixture).

**Comment by Coneko** [comment]
Correct, just like in the example, you specify the files you want to disable ARC for as tuples.

You can use `excludes`: https://buckbuild.com/function/glob.html

```
apple_library(
  name = "MyLibrary",
  srcs = glob(["*.m"], excludes=["a.m"]) + ("a.m", ["-fno-objc-arc"]),
)
```
