### ISSUE TITLE
Buck plugin crashes if buck not on $PATH

### ISSUE THREAD

**Issue by shs96c** [facebook/buck#1191]
It's officially Not Cool to have the Buck plugin cause an IDE failure if Buck isn't on the $PATH:

https://gist.github.com/shs96c/cc03869c30a78785b1fdd02c05c89988

Looks like an easy fix :) Might be nice to allow us to specify Buck location per-project via a config setting.

**Comment by Coneko** [comment]
cc @styurin, @mkillianey

**Comment by mkillianey** [comment]
We could certainly catch that exception, yup, although I'm not clear what the right way is to tell the user that the buck plugin can't find a buck executable.  Perhaps it could match the Git plugin.  If that plugin can't make sense out of whatever path to the git executable the user specified, it complains to the Event Log and brings up this message:
![bad-git-path](https://cloud.githubusercontent.com/assets/180863/23201880/766a7b14-f890-11e6-8bc3-3ac37730e14b.png)
(Where the "Fix it" links to the Git preferences page where you set the Git path.)
