### ISSUE TITLE
buck forgot to merge  some manifest

### ISSUE THREAD

**Issue by ldjhust** [facebook/buck#1196]
Hi
    I'm using buck to build my android app，the build process is successful，and the install process is successful too. But when I started it, it crashed. At last, I found the reason was that a AndroidManifest.xml from a dependency aar didn't merged into the final apk package's AndroidManifest.xml.

Does any guy have ideas on this problem?

Thank you for any help!

**Comment by marcinkosiba** [comment]
> Does any guy have ideas on this problem?

It's not a known problem. Could you please provide us with a way to reproduce this? Ideally a .zip file or github repository that contains a minimum working example.

**Comment by ldjhust** [comment]
Sorry, I found the solution on a previous issue.

Thank you for your response!
