### ISSUE TITLE
No successful build in over a month

### ISSUE THREAD

**Issue by brettwooldridge** [facebook/buck#1198]
As far as I can tell, the Travis CI build has not run successfully in over a month.  Anyone at Facebook care to take a look (and maybe fix it)?

**Comment by marcinkosiba** [comment]
I was looking at that yesterday. Multiple things going on:
 - android-integration getting killed (most likely by OOM killer)
 - timeouts
 - not sure what the deal with cxx failures is

**Comment by kageiit** [comment]
it maybe worthwhile to ignore the failing tests and follow up with a fix so that it can unblock contributions to buck and remove false negatives on PRs

**Comment by ilya-klyuchnikov** [comment]
here is the possible solution: https://github.com/ilya-klyuchnikov/buck/commit/861cd1a7ed31a7f9b76794d8f293df8db7eff2e7. Travis in container mode is jealous about resources (especially when multiple JVMs are running). The idea is to run the heaviest tests in a single thread mode. The corresponding successful run is: https://travis-ci.org/ilya-klyuchnikov/buck/builds/240916902

**Comment by sdwilsh** [comment]
In the past, I've pulled tests out to run serially that were causing 
problems like this (via `run_tests__separately` IIRC).
