### ISSUE TITLE
Cmake support for building android ndk modules

### ISSUE THREAD

**Issue by kageiit** [facebook/buck#1203]
The `ndk_library` rule only supports gnu make. Cmake is going to be the official toolchain moving forward and gnu make will no longer be supported. Are there plans to get cmake support into buck?

**Comment by sdwilsh** [comment]
`ndk_library` is there for compatibly reasons.  It's how Buck used to suggest doing native code for Android, but these days folks should be using `cxx_library` instead.

**Comment by kageiit** [comment]
Can cxx_library be used with cmake?

**Comment by sdwilsh** [comment]
`cxx_library`, like `java_library` and `android_library`, requires one to specify the sources, etc.  If one wants to invoke cmake, one should probably use a `genrule`.

I strongly suspect the team will choose to not fix this.

**Comment by kageiit** [comment]
Thanks for clarifying!
