### ISSUE TITLE
JUnit compatible test reporting

### ISSUE THREAD

**Issue by fkorotkov** [facebook/buck#1204]
Right now `buck test --all --xml output.xml` produces a report in a custom format. Many tools has support for JUnit specific format of XML reports. I think it will make sense to change the format to produce a JUnit report.

Is there any objections?

**Comment by kageiit** [comment]
We currently use a tool after the tests are run to perform the conversion - https://github.com/uber/okbuck/tree/master/tools/junit

But im planning to open a change to buck to enable outputting junit xml directly

**Comment by v-jizhang** [comment]
Hi, this issue is closed because it has not been updated for more than 3 years. Thanks
