### ISSUE TITLE
question for '-Objc' link flags

### ISSUE THREAD

**Issue by xiaoaihhh** [facebook/buck#1209]
In Xcode, when i use a static library, i can set `Other linker flags` as `-Objc`.  Now, I use `prebuilt_cxx_library()` rule and want to set `-Objc ` flag, i have set `exported_linker_flags = ['-ObjC']`, but when i use a method, it will crash. It seems not work to me.

**Comment by Coneko** [comment]
What's the message of the crash? Is Buck crashing or the app you're building crashing?

**Comment by SwiftlyFly** [comment]
My app crashed, crass message is `EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)`.

**Comment by ryu2** [comment]
This isn't very helpful.  Please provide a full stack trace at least.
