### ISSUE TITLE
Add Documentation for thrift_library Rule

### ISSUE THREAD

**Issue by paulcavallaro** [facebook/buck#1210]
Currently there aren't any docs on using the thrift_library rule. I'm not sure if that's intentional, but there is documentation for .buckconfig that mentions the [thrift] configuration.

Not sure if buck natively supports thrift, but if it does and you can use the thrift_library rule, would be nice to have documentation for it.

**Comment by Coneko** [comment]
Sorry it's not documented because it's not supported and we're planning on removing it.

**Comment by paulcavallaro** [comment]
@Coneko May I ask what the suggested alternative is? What do people at FB use for generating fbthrift libraries?

**Comment by sdwilsh** [comment]
@andrewjcg mentioned doing a build definition approach here: https://github.com/facebook/buck/commit/5f1432e502f9a04db08361f8b5c565b8048dd8b6#commitcomment-18220864

I think @philipjameson is working on open sourcing this as part of another project.

**Comment by philipjameson** [comment]
@sdwilsh, yes, it's in progress, but no firm timeline yet
