### ISSUE TITLE
Why so many point will crash when i use the method from apple framework?

### ISSUE THREAD

**Issue by xiaoaihhh** [facebook/buck#1212]
Now I am very depressed. As title I have said,  such as `[[UIApplication sharedApplication] setStatusBarHidden:NO withAnimation:UIStatusBarAnimationNone];` will crash, and I can't get crash message. Here is some Call Stack message:
__cxa_throw +0 0x7fff54235f30:1
TFileDescriptorContext::TFileDescriptorContext(char const*) +8e 0x7fff54235f30:1
TFileDataReference::MapOrRead(char const*, int) +1f 0x7fff54235f70:1
TFileDataReference::TFileDataReference(char const*, bool) +f9 0x7fff542363e0:1
TResourceForkFileReference::TResourceForkFileReference(char const*, bool) +16 0x7fff54236410:1

Except these, some myself code also will crash, and I have set the `.m` file in `srcs`, the build is also correct. 
All code is right in Xcode.
Because my  project more than  fifty thousand lines of code, so it not easy to give a demo.
what the reason it may be?

**Comment by ryu2** [comment]
What makes you think this is a Buck issue?  Does the Buck-generated project work properly when built with Xcode?  Is this the same issue you're describing as #1209?
