### ISSUE TITLE
Buck daemon not recognizing file changes on large iOS projects

### ISSUE THREAD

**Issue by ProfessaA** [facebook/buck#1215]
I'm working on a large iOS project built with buck (v2016.11.11.01), and I've noticed that changes don't get picked up by the daemon consistently, forcing me to use `NO_BUCKD=1`.  Everything works fine with smaller sized projects, but for medium and large projects, buck will report cached results after file changes.  For example, after running `buck test /Some/Lib` and seeing all tests pass, I'll invert the assertion in one of the tests for that library, re-run `buck test /Some/Lib` and still see all tests passing with 100% cache hit.

I considered watchman (v4.7.0) as the possible source of failure, but with the subscription:
```
watchman -j --server-encoding=json -p <<-SUBSCRIBE
["subscribe", "path/to/project", "debug-watchman", {
  "expression": ["allof", ["type", "f"]], "fields": ["name"]
}]
SUBSCRIBE
```
I see the filename for the file I'm changing even when buck doesn't seem to pick up the change.

Do you have any ideas about what could be going on? I'm also not sure how to debug this, I tried tailing `buck-out/logs/*.log` but didn't see anything useful.  I'd really appreciate any guidance on how to get better debug info from the buck daemon or on what the underlying issue might be.

Thanks!

**Comment by ryu2** [comment]
What shows up in the watchman logs?  

http://facebook.github.io/watchman/docs/troubleshooting.html

**Comment by ProfessaA** [comment]
@ryu2 I went through the watchman troubleshooting guide and didn't see any of the error messages mentioned being logged.  I also ran the `find-fsevents-bugs` tool and nothing came up.  The watchman logs look fairly normal, and are similar to watchman's log output when files are changed in the smaller projects that the buck daemon catches updates in.  This is the output from watchman when I change the file `/path/to/proj/Libraries/Injector/InjectorTests/InjectorTest.m` to make a test fail:
```
[notify /path/to/proj] fsevents: got /path/to/proj/Libraries/Injector/InjectorTests/4913 0x14300 ItemCreated ItemRemoved ItemChangeOwner ItemIsFile
[notify /path/to/proj] add_pending: /path/to/proj/Libraries/Injector/InjectorTests/4913 VIA_NOTIFY
[notify /path/to/proj] fsevents: got /path/to/proj/Libraries/Injector/InjectorTests/InjectorTest.m~ 0x10a00 ItemRemoved ItemRenamed ItemIsFile
[notify /path/to/proj] add_pending: /path/to/proj/Libraries/Injector/InjectorTests/InjectorTest.m~ RECURSIVE VIA_NOTIFY
[notify /path/to/proj] fsevents: got /path/to/proj/Libraries/Injector/InjectorTests/InjectorTest.m 0x1f900 ItemCreated ItemRenamed ItemModified FinderInfoMod ItemChangeOwner ItemXattrMod ItemIsFile
[notify /path/to/proj] add_pending: /path/to/proj/Libraries/Injector/InjectorTests/InjectorTest.m RECURSIVE VIA_NOTIFY
[io /path/to/proj]  ... wake up (pinged=true)
[io /path/to/proj] processing 3 events in /path/to/proj
[io /path/to/proj] w_lstat(/path/to/proj/Libraries/Injector/InjectorTests/InjectorTest.m) file=0x7fa84ae54840 dir=0x0 res=0 Undefined error: 0
[io /path/to/proj] file changed exists=1 via_notify=1 stat-changed=0 isdir=0 /path/to/proj/Libraries/Injector/InjectorTests/InjectorTest.m
[io /path/to/proj] add_pending: /path/to/proj/Libraries/Injector/InjectorTests
[io /path/to/proj] w_lstat(/path/to/proj/Libraries/Injector/InjectorTests/InjectorTest.m~) file=0x7fa84c321530 dir=0x0 res=-1 No such file or directory
[io /path/to/proj] we're case insensitive, and /path/to/proj/Libraries/Injector/InjectorTests/InjectorTest.m~ is ENOENT, speculatively look at parent dir /path/to/proj/Libraries/Injector/InjectorTests
[io /path/to/proj] w_lstat(/path/to/proj/Libraries/Injector/InjectorTests/4913) file=0x7fa84c321750 dir=0x0 res=-1 No such file or directory
[io /path/to/proj] we're case insensitive, and /path/to/proj/Libraries/Injector/InjectorTests/4913 is ENOENT, speculatively look at parent dir /path/to/proj/Libraries/Injector/InjectorTests
[io /path/to/proj] processing 1 events in /path/to/proj
[io /path/to/proj] opendir(/path/to/proj/Libraries/Injector/InjectorTests) recursive=false
[io /path/to/proj] in crawler calling process_path on /path/to/proj/Libraries/Injector/InjectorTests/.DS_Store
[io /path/to/proj] add_pending: /path/to/proj/Libraries/Injector/InjectorTests
[io /path/to/proj] in crawler calling process_path on /path/to/proj/Libraries/Injector/InjectorTests/Fixtures
[io /path/to/proj] in crawler calling process_path on /path/to/proj/Libraries/Injector/InjectorTests/Info.plist
[io /path/to/proj] in crawler calling process_path on /path/to/proj/Libraries/Injector/InjectorTests/InjectorTest.m
[io /path/to/proj] in crawler calling process_path on /path/to/proj/Libraries/Injector/InjectorTests/Providers
[io /path/to/proj] processing 1 events in /path/to/proj
[io /path/to/proj] w_lstat(/path/to/proj/Libraries/Injector/InjectorTests) file=0x7fa84ad3b9c0 dir=0x7fa84ae183a0 res=0 Undefined error: 0
[io /path/to/proj] file changed exists=1 via_notify=0 stat-changed=1 isdir=1 /path/to/proj/Libraries/Injector/InjectorTests
[io /path/to/proj] poll_events timeout=20ms
[io /path/to/proj]  ... wake up (pinged=true)
[io /path/to/proj] poll_events timeout=20ms
[io /path/to/proj]  ... wake up (pinged=false)
[io /path/to/proj] last=22  pending=35
```

In this case `buck test` continues to report 100% cache hit and all tests passing.  Is there any logging from the buck daemon that might be useful?

**Comment by ryu2** [comment]
Cc @bhamiltoncx who might have an idea.

**Comment by ProfessaA** [comment]
@bhamiltoncx do you have any suggestions on why this might be happening and what logs I can look at to debug? thanks!

**Comment by bhamiltoncx** [comment]
@ProfessaA: Sorry for the delay. You can bump up the log level for `WatchmanSocketClient` to get the full query and response.

Add to the file `.bucklogging.local.properties` in your project directory:

```
com.facebook.buck.io.WatchmanSocketClient.level = FINER
```

The resulting queries and responses should show up in `buck-out/log/buck-0.log` (look for `WatchmanSocketClient`.)

**Comment by ProfessaA** [comment]
@bhamiltoncx that helped a lot since I was able to see the queries being made to watchman (the pertinent logs showed up in `buck-out/log/<timestamp>_testcommand_<uuid>/buck.log`).

It turns out that my buckconfig's `[project] ignore` section had a trailing comma which caused `["dirname", ""]` to be added to the `not` portion of the watchman query.  I guess this causes everything to be ignored.  That's completely my fault, this issue can be closed.  Thanks for your help!

**Comment by bhamiltoncx** [comment]
Ouch! I wonder if we can handle this better. Empty ignores should
definitely be a fatal error.
