### ISSUE TITLE
BUILD FAILED: Must set ANDROID_SDK to point to the absolute path of your Android SDK directory.

### ISSUE THREAD

**Issue by leodeleon22** [facebook/buck#1221]
I'm trying to build the sample but I get the above error. I've unset the ANDROID_HOME variable and my ANDROID_SDK is like that

`ANDROID_SDK=/usr/local/Cellar/android-sdk/24.4.1_1`

Any clues how I get it working on MacOS?

**Comment by leodeleon22** [comment]
I was able to run the demo using 
`ANDROID_SDK=$ANDROID_HOME buck install --run demo_app_android`

How should I set my variables so I don't have this problem anymore?

**Comment by illicitonion** [comment]
My guess is that ANDROID_SDK should point to /usr/local/Cellar/android-sdk not /usr/local/Cellar/android-sdk/24.4.1_1
