### ISSUE TITLE
How to customize buck's build process?

### ISSUE THREAD

**Issue by ldjhust** [facebook/buck#1222]
Hi guys,

When build android project with gradle, there are some hooks we can use to customise the build process  like this:
eg1.
tasks.whenTaskAdded { task ->
    if (task.name.startsWith('xxx')) {
        task.doFirst {
            // do something you want
        }

        task.doLast {
            // do something you want
        }
    }
}

or eg2.
tasks.withType(JavaCompile) {
    options.encoding = "UTF-8"
}

What I want to know is that does buck has a same or similar way to do this ?

Thanks for any help!

**Comment by kageiit** [comment]
You can use `include_defs`to modify the behavior of built in rules via [custom macros](https://buckbuild.com/extending/macros.html) etc. example: https://github.com/facebook/infer/blob/master/DEFS

**Comment by Coneko** [comment]
Note that Buck's model isn't task based, it's rule based, and there's no way to add phony rules like in make, so in practice there's no way to add something at the start and end of the build.

**Comment by kageiit** [comment]
That is not entirely true. If it's just at the start and end of the entire build, you can just wrap the buck invocation in a wrapper script similar to gradlew to do whatever you want.

Example: https://github.com/uber/okbuck/blob/master/buckw

I wish buck just shipped with one in general :)
