### ISSUE TITLE
core_data_model cannot be proper bundled into vanilla apple_test

### ISSUE THREAD

**Issue by liuliusc** [facebook/buck#1226]
**Summary**

For vanilla apple_test (without host app), core_data_model (https://buckbuild.com/rule/core_data_model.html) specified data model doesn't get compiled and bundled into apple_test as resource.

**Step to Reprod**

 * Add a xcdatamodeld to the BUCK project, some apple_library with core_data_model;
 * Add apple_test that has dependency on the apple_library;
 * In the XCTestCase, access data model through `[NSBundle bundleForClass:[self class]]`, similar to `[[NSManagedObjectModel alloc] initWithContentsOfURL:[bundle URLForResource:@"DataModel" withExtension:@"momd"]]`;

**Expected Result**

Would expect the test to run as expected. Without BUCK, what you achieve this is by having the xcdatamodeld file in the Compiled Sources list.

**Actual**

buck test will fail on exception because cannot find the content at the said URL.

**Workaround**

Using genrule and apple_resource, we were able to make Buck to work, but would like to have this resolved at upstream.
```
apple_test(
    deps = [':DataModelMOMC']
)

apple_resource(
    name = 'DataModelMOMC',
    files = glob(['*.momd']),
    dirs = [
        ':CompileDataModel',
    ],
)

# This genrule copied from https://github.com/facebook/buck/issues/467 for the most part.
genrule(
    name = 'CompileDataModel',
    srcs = ['DataModel/DataModel.xcdatamodeld'],
    bash = '/Applications/Xcode.app/Contents/Developer/usr/bin/momc --sdkroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.2.sdk --iphonesimulator-deployment-target 9.0 --module SCDataModelTests $SRCDIR/DataModel/DataModel.xcdatamodeld $OUT',
    out = 'DataModel.momd'
)
```

**Comment by Coneko** [comment]
Looking at the code it should work if you create a `core_data_model` target and add it to the dependencies of your binary or bundle.

How did you set it up?

**Comment by liuliusc** [comment]
Sure. The setup looks like this:
```
apple_library(
    name = 'DataModelLib',
    headers = 'DataModel/**/*.h',
    srcs = 'DataModel/**/*.m',
    deps = [':DataModel']
)

apple_test(
    name = 'DataModelTests',
    srcs = 'DataModelTests/**/*.m',
    deps = [':DataModelLib', ':DataModel'],
)

core_data_model(
    name = 'DataModel',
    path = 'DataModel/DataModel.xcdatamodeld',
)
```

**Comment by Coneko** [comment]
Yeah that looks right, at the very least the code seems like it handles that case.

Can you create a small repro repo or gist and post it on github so I can repro it on my machine?

**Comment by liuliusc** [comment]
Thank @Coneko , verified the tip of buck now passes my example with buck test.

However, I was confused why the generated Xcode project moves the data model to resource copy rather than compile phase. I don't quite understand the implication to be honest.

To help the discussion:
```
> buck -V
buck version bd6565f63b08746c581630ab7a399d1a621334f0
```

**Comment by liuliusc** [comment]
I think the file in resources gets compiled properly. Will close this task. Thank you!
