### ISSUE TITLE
Getting Started page for iOS/Mac needs an update

### ISSUE THREAD

**Issue by aledalgrande** [facebook/buck#1230]
The Getting Started page for iOS/Mac is not up to date. You don't need to run `brew update` now, it will update itself. Also, the command to install Java should be fixed to:
```
brew cask install java
```
instead of
```
brew install java
```

What do you think of putting the docs on Github too, so the community can send pull requests?

**Comment by LegNeato** [comment]
@aledalgrande the docs are checked in 👍. Check out :

https://github.com/facebook/buck/blob/63ad3bf1874ab6dbbc8a3e3ecbc81fc9ba6809e1/docs/setup/getting_started.soy#L139

**Comment by aledalgrande** [comment]
Oh cool, sorry I missed that. I'll send a quick PR.
