### ISSUE TITLE
Unable to cast BitmapDrawable to NinePatchDrawable

### ISSUE THREAD

**Issue by ldjhust** [facebook/buck#1233]
Hi Guys,

I hava an android project which was originally built with gradle. Recently I migrate it to buck, due to buck's advantage in build performance. The build process with buck was successful, but when I tested the apk on my phone, it cashed with some scenes. And the log was here:

```shell
java.lang.RuntimeException: Unable to start activity ComponentInfo{xxx}: java.lang.ClassCastException: android.graphics.drawable.BitmapDrawable cannot be cast to android.graphics.drawable.NinePatchDrawable
```

The code:
```java
mImage = (NinePatchDrawable)Global.getResources().getDrawable(R.drawable.btn_mbarrage);
```

By the way, the apk built with gradle was fine.

Does anyone has any idea about this?

Thanks very much!

**Comment by v-jizhang** [comment]
Hi, This issue is closed because there is no updates for over 3 year. Thanks
