### ISSUE TITLE
Buck package boundary error for BUCK files inside buck-out

### ISSUE THREAD

**Issue by fkorotkov** [facebook/buck#1235]
Hey there,

I'm trying to use `genrule`s for handling React Native and some of RN npm packages contain BUCK files which leads to some weird error even though I have `buck-out` ignored on `.buckconfig`. Here is a small reproducible example with two files:

```
# BUCK.template
android_resource(
  name = 'assets',
  assets = '.',
  visibility = ['PUBLIC'],
)
```

```
# BUCK
genrule(
  name = 'generate_buck_file_unintensionally',
  srcs = ['BUCK.template'],
  bash = 'cp $SRCS $OUT',
  out = 'BUCK'
)
```

If you run `buck build //...` **twice** you'll see this error on the second time:

```
BUILD FAILED: 'buck-out/gen/generate_buck_file_unintensionally' in '//buck-out/gen/generate_buck_file_unintensionally:assets' crosses a buck package boundary.  This file is owned by ''.  Find the owning rule that references 'buck-out/gen/generate_buck_file_unintensionally', and use a reference to that rule instead of referencing the desired file directly.
```

Is there a workaround? Why `buck-out` is not been ignored this case?

**Comment by fkorotkov** [comment]
Worked around it by adding `buck/gen` to `project.ignore` because of https://github.com/facebook/buck/blob/667dc14f7852dfde1d54a43bc7e894a8332cd1c2/src/com/facebook/buck/io/ProjectFilesystem.java#L304

**Comment by Coneko** [comment]
That is a bit funny, thanks for letting us know.
