### ISSUE TITLE
How to migrate from Cocoapods?

### ISSUE THREAD

**Issue by aledalgrande** [facebook/buck#1236]
I wanted to road-test Buck, but I can't find any guide on how to convert from Cocoapods to Buck. Does Buck resolve dependencies graphs? Is it only for local projects or can it access one on, say, Github?

Thanks

**Comment by Coneko** [comment]
It's only for local projects.

Usually pods are simple enough that creating an `apple_library` that has all `.m` files as sources and `.h` files as exported headers will work.

**Comment by aledalgrande** [comment]
Thanks, I'll see if I can come up with a script to generate a `BUCK` file from a Podspec, as they require more or less the same info.

**Comment by aledalgrande** [comment]
@ChristianOrgler blocked by some other stuff atm, I will get to it soon hopefully, but feel free to work on it.

**Comment by nikhilsh** [comment]
Would love to try out any solutions that you guys might have. I'm currently trying to compile a Swift project using Cocoapods with Buck. My `BUCK` file looks like this:

```# iOS

apple_asset_catalog(
  name = 'FjordAssets',
  dirs = ['Assets.xcassets'],
)

apple_resource(
  name = 'FjordResources',
  dirs = [],
  files = glob(['*.png','*.storyboard', '*.xib']),
)

apple_library(
    name = 'FjordPods',
    preprocessor_flags = ['-fobjc-arc'],
    srcs = glob([
      '../Pods/**/*.m',
      '../Pods/**/*.mm',
      '../Pods/**/*.swift',
    ]),
    exported_headers = glob([
      '../Pods/**/*.h',
    ]),
    frameworks = [
    '$SDKROOT/System/Library/Frameworks/UIKit.framework',
    '$SDKROOT/System/Library/Frameworks/Foundation.framework',
    ],
)

apple_binary(
  name = 'FjordBinary',
  configs = {
    'Development': {
    'PRODUCT_NAME' : 'Fjord',
    'PRODUCT_MODULE_NAME' : 'Fjord-iOS',
    'CLANG_ENABLE_MODULES' : 'YES',

    'PROVISIONING_PROFILE_SPECIFIER' : '',
    'DEVELOPMENT_TEAM' : '7JMN9R74Y6',

    'ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES' : 'YES',
    'PRODUCT_BUNDLE_IDENTIFIER' : 'xxxx',
    'ONLY_ACTIVE_ARCH' : 'YES',
    'CODE_SIGN_ENTITLEMENTS' : 'Fjord.entitlements',
    'SWIFT_OPTIMIZATION_LEVEL' : '-Onone',
    'GCC_OPTIMIZATION_LEVEL' : '0',
    'VALIDATE_PRODUCT' : 'NO',
    },
  },
  deps = [
    ':FjordAssets',
    ':FjordResources',
    ':FjordPods',
  ],
  preprocessor_flags = [
    '-fobjc-arc',
    '-fno-objc-arc-exceptions',
    '-Qunused-arguments',
  ],
  srcs = glob([
    '*.m',
    '*.mm',
    '*.swift',
  ]),
  headers = glob([
    '*.h',
  ]),
  bridging_header = 'Fjord-Bridging-Header.h',
  frameworks = [
    '$SDKROOT/System/Library/Frameworks/SystemConfiguration.framework',
    '$SDKROOT/System/Library/Frameworks/OpenGLES.framework',
    '$SDKROOT/System/Library/Frameworks/AVFoundation.framework',
    '$SDKROOT/System/Library/Frameworks/Foundation.framework',
    '$SDKROOT/System/Library/Frameworks/UIKit.framework',
    '$SDKROOT/System/Library/Frameworks/CoreMotion.framework',
    '$SDKROOT/System/Library/Frameworks/CoreLocation.framework',
    '$SDKROOT/System/Library/Frameworks/MobileCoreServices.framework',
    '$SDKROOT/System/Library/Frameworks/CoreMedia.framework',
  ],
  visibility = ['PUBLIC'],
)


apple_bundle(
  name = 'Fjord',
  binary = ':FjordBinary',
  extension = 'app',
  info_plist = 'Info.plist',
)

apple_package(
  name = 'FjordPackage',
  bundle = ':Fjord',
)
```

and I'm getting the following error:
```error: no such module 'Alamofire'
import Alamofire
       ^
BUILD FAILED: //Fjord-iOS:FjordBinary#iphonesimulator-x86_64,swift-compile failed with exit code 1:
swift compile
```

not sure where I'm going wrong. Any ideas?

**Comment by Coneko** [comment]
You can't refer to files with `../`, you need to put the `BUCK` file above them. It should fail the parsing if you use `../`, not sure why it didn't.

**Comment by Coneko** [comment]
Did you set `check_package_boundary` to false?

**Comment by nikhilsh** [comment]
Nope I did not. I placed the `BUCK` file one level higher, but I'm getting the same error again 😢

**Comment by ChristianOrgler** [comment]
@nikhilsh could you fix it?

**Comment by gsabran** [comment]
How do you deal with pods that are not straightforwards? I'm struggling with Realms that has several files with the same name ([SO](https://stackoverflow.com/questions/53846223/how-can-i-use-buck-build-with-a-pod-that-has-several-files-with-the-same-name))

**Comment by gsabran** [comment]
@aledalgrande did you find a way to generate BUCK files from Podspecs? I'm often coming across pods that are not just a bunch of headers but more complex libraries, with dependencies on other pods. It's been quite hard to find how to build them with BUCK so far

**Comment by makadaw** [comment]
We did everything manually :( But after this, we can use cocoapods for updates, just keep your BUCK files. Here is small post install hook

```bash
git diff --name-only --diff-filter=D | grep BUCK | xargs git checkout
```

**Comment by aledalgrande** [comment]
Yeah I had to do manually. Although I tried Buck for the performance, the new iOS build system is fast enough IMHO.
