### ISSUE TITLE
I can't build it, help

### ISSUE THREAD

**Issue by krossford** [facebook/buck#1240]
![image](https://cloud.githubusercontent.com/assets/4727984/23884064/7429a5a8-08a5-11e7-8c79-437641c08053.png)

**Comment by ryu2** [comment]
It looks like you're using Linux javac on Windows through WSL.  This isn't supported; either use native Windows JDK or use a actual Linux system or VM.

**Comment by krossford** [comment]
So....I can run buck on windows without any problem? @ryu2

**Comment by ryu2** [comment]
Yes but it's a work in progress.

https://buckbuild.com/setup/getting_started.html

Sent from my iPhone

On Mar 14, 2017, at 7:27 PM, kross <notifications@github.com<mailto:notifications@github.com>> wrote:


So....I can run buck on windows without any problem? @ryu2<https://github.com/ryu2>
