### ISSUE TITLE
cache.dir_cache_names does not work

### ISSUE THREAD

**Issue by fkorotkov** [facebook/buck#1251]
I'm trying to config two dir caches based on [an example from the docs](https://buckbuild.com/concept/buckconfig.html#cache.dir_cache_names) but Buck is still trying to write to `buck-out/cache` folder no matter what I'm trying.

Here is my sample project: https://github.com/fkorotkov/buck-sandbox/commit/a51d516615a259a88a1cb937d381a749be55b6d8

**Comment by samjoch** [comment]
@fkorotkov it seems that your `.buckversion` file is too old. ([here for more info](https://buckbuild.com/concept/buckversion.html)) ;-)

**Comment by fkorotkov** [comment]
@samjoch updated buck version with no effect. Internally we are using at most two weeks old master and this is just my sandbox for sharing things externally :-)

**Comment by samjoch** [comment]
@fkorotkov you should replace `buck-out, \` with `buck-out` [here](https://github.com/fkorotkov/buck-sandbox/blob/master/.buckconfig#L20).
I noticed the ini validator mixup the `cache` section value with the `project` section values.

**Comment by marcinkosiba** [comment]
thanks for the help @samjoch!
@fkorotkov, you can check if your config is correct by using the `buck audit config cache` command
FWIW if you set both dircaches to readwrite buck will write to both.
