### ISSUE TITLE
Changing a resource id causes runtime crash

### ISSUE THREAD

**Issue by cwoodwar6** [facebook/buck#1252]
We have a large, multidex enabled application. We have one module that exceeds the size of a single dex. When building with Buck, we must disable pre-dex because of this large module.

In our application, when a resource id is changed (for example when changing or adding a view id in a layout) the app will compile but crashes at runtime when trying to inflate the view where the id was changed. To get around this, we have to remove the contents of `buck-out` and build again. This appears to happen every time an id is changed.

We've recently tried moving a large chunk of code out of this module so we could enable pre-dex. Once we have done this, the issue seems to disappear.

I've attached the log from the runtime crash. It would be greatly appreciated if there is a way to work around this, we currently aren't able to keep pre-dex on.

[resource_id_log.txt](https://github.com/facebook/buck/files/849144/resource_id_log.txt)

The most interesting part of this log seems to be: `Caused by: java.lang.NoSuchFieldError: No static field my_view_id of type I in class Lcom/example/app/R$id; or its superclasses (declaration of 'com.example.app.R$id' appears in /data/app/com.example.app-1/base.apk:classes13.dex)`

**Comment by raviagarwal7** [comment]
this seems to be a duplicate of https://github.com/facebook/buck/issues/1325.

@cwoodwar6 a fix has been landed on master, please verify and close this issue if it works.

**Comment by cwoodwar6** [comment]
Thankfully, we no longer have to run with pre-dex disabled.

To verify, I disabled pre-dex, and was able to modify a resource id without a runtime crash. Looks resolved to me.
