### ISSUE TITLE
always failed in smart_dex step

### ISSUE THREAD

**Issue by ldjhust** [facebook/buck#1256]
I'm using buck to build my android project, and the debug mode works fine. However, when I add ProGuard and build the release mode, it will always failed in `smart_dex` step, the reason is `OOM`.
I have already set `-Xmx8g` in `.buckjavaargs` file and also tried `max_heap_size=8g` in `.buckconfig`, but the problem is still there, I don't know what to do now, please help!

```shell
UNEXPECTED TOP-LEVEL ERROR:
java.lang.OutOfMemoryError: GC overhead limit exceeded

There was an error in smart dexing step.
com.facebook.buck.step.StepFailedException: Failed with exit code 3:
dx_&&_write_file
stderr: 
UNEXPECTED TOP-LEVEL ERROR:
java.lang.OutOfMemoryError: GC overhead limit exceeded

com.facebook.buck.step.StepFailedException: Failed with exit code 3:
dx_&&_write_file
stderr: 
UNEXPECTED TOP-LEVEL ERROR:
java.lang.OutOfMemoryError: GC overhead limit exceeded

	at com.facebook.buck.step.StepFailedException.createForFailingStepWithExitCode(StepFailedException.java:63)
	at com.facebook.buck.step.DefaultStepRunner.runStepForBuildTarget(DefaultStepRunner.java:62)
	at com.facebook.buck.android.SmartDexingStep.lambda$2(SmartDexingStep.java:209)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

BUILD FAILED: //:release_apk failed with exit code 1:
smart_dex
```

Thank you very much!

**Comment by Coneko** [comment]
This seems like it's the dx invocation running out of memory, not Buck.

Are you sure you set the `max_heap_size` setting correctly? Buck will not fail if you have a typo or put it in the wrong section.

https://buckbuild.com/concept/buckconfig.html#dx.max_heap_size

**Comment by ldjhust** [comment]
Thanks for your response @Coneko, and here is my `.buckconfig` and `.buckjavaargs`, I'm setting it exactly according to the doc. Is there args that I need to set?

`.buckconfig`
![image](https://cloud.githubusercontent.com/assets/3424674/24129166/9cfa68a2-0e1b-11e7-899d-2c872be756f4.png)

`.buckjavaargs`
![image](https://cloud.githubusercontent.com/assets/3424674/24129179/b6fd839c-0e1b-11e7-97d7-f3f70c0b0cdd.png)

**Comment by kageiit** [comment]
@ldjhust the `max_heap_size` was merged only recently. Please try against the head of buck sha in your `.buckversion`

**Comment by ldjhust** [comment]
@kageiit thank you for your response, I have tried your suggestion, but it failed with a strange exception in the `split_zip` step:

```
BUILD FAILED: //:release_apk failed on step split_zip with an exception:
classpath com/big/location/scheduler/d/a is contained in multiple dex stores
```

I searched it in my project, there was just one `com/big/location/scheduler/d/a` in one of my jar library. I previously used the `buck-v2016.11.11.01` version, and it's fine with `split_zip` step, but failed in `smart_dex` step like above. Do you have opinion about that?

By the way, my `.buckversion` file content is below:
```
eacfc4f0fc372a755d3c4f6c33867e032659c7dc:refs/heads/master
```

**Comment by marcinkosiba** [comment]
@ldjhust I think that error means that you're either using application_module_targets or you somehow convinced buck to put that class into the primary and secondary dex. What does your android_binary rule look like?

**Comment by ldjhust** [comment]
@marcinkosiba thank you for your response, I just use the `use_split_dex` arg, and didn't use other special args. Here is my `android_binary` rule:

```shell
android_binary(
    name = "release_apk",
    keystore = ":release_keystore",
    skip_crunch_pngs = True,
    includes_vector_drawables = True,
    proguard_config = "conf/proguard/proguard.cfg",
    android_sdk_proguard_config = "none",
    package_type = "release",
    use_split_dex = True,
    manifest = ":test",
    deps = [
        ":res",
        ":lib",
    ]
)
```

**Comment by ldjhust** [comment]
@marcinkosiba I find a workaround, add the "-keep class com.big.location.scheduler.**" to the ProGuard config file, and then the `split_dex` error disappeared. But I don't why

**Comment by ldjhust** [comment]
thank you guys, I have already knew it~
