### ISSUE TITLE
Must set ANDROID_SDK to point to the absolute path of your Android SDK directory

### ISSUE THREAD

**Issue by guptasourabh** [facebook/buck#1257]
Getting this error , even after correctly setting the path.

<img width="1249" alt="screen shot 2017-03-20 at 11 08 59 pm" src="https://cloud.githubusercontent.com/assets/4599610/24113668/7f5b5c00-0dc3-11e7-9392-0783cc03b5f2.png">

**Comment by ceozhu** [comment]
![image](https://cloud.githubusercontent.com/assets/5701010/24191359/8d1ca0c4-0f26-11e7-8837-ee6608311000.png)

**Comment by ceozhu** [comment]
![image](https://cloud.githubusercontent.com/assets/5701010/24191397/b0bf1d18-0f26-11e7-818f-f8fe51294e97.png)

I have a local.properties with content of sdk and ndk absolute path  
as same got the error

**Comment by v-jizhang** [comment]
I could not create a repro, it must have been fixed.
