### ISSUE TITLE
The javac flag -proc:only is passed to the compiler when compiling dummy r dot java

### ISSUE THREAD

**Issue by cwoodwar6** [facebook/buck#1260]
When adding the `-proc:only` flag to a target, the flag is also being passed to the java compiler that compiles the dummy r jar. This results in a jar that is empty because only annotation processors were told to run.

Example of the compiler error: 
```
/Users/cwoodward/Development/project/library/src/main/java/com/example/ui/main/ExampleActivity.java:23: error: cannot find symbol
import com.example.library.R;
```

Ideally the flag is not passed to the compiler when compiling the dummy r jar, only when it compiles the target code.

**Comment by dreiss** [comment]
Are you setting -proc:only explicitly or with annotation_processor_only=True?

**Comment by dreiss** [comment]
e1da197cf45cd6846585289767e67989fd31ab8e fixed this in the latter case.

**Comment by cwoodwar6** [comment]
Explicitly, I was not aware of `annotation_processor_only`. Is there an equivalent flag for `-proc:none`?

**Comment by dreiss** [comment]
annotation_processor_only is the structured way to pass -proc:only, so we can automatically remove it when passing flags to the step that compiles dummy R.java.

We should be ready to finalize and document the arguments supporting APs soon.
