### ISSUE TITLE
Compiling a Metal library for iOS

### ISSUE THREAD

**Issue by aledalgrande** [facebook/buck#1262]
Hi,
I couldn't find any mention on how to build a library that has `.metal` files in it, is it not supported currently?

The command to compile the single file would be like:

> /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/usr/bin/metal -arch air64 -emit-llvm -c -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.2.sdk -ffast-math -serialize-diagnostics /xxx/myproj/build/myproj.build/Release-iphoneos/mylib.build/Metal/mymetalfile.dia -o /xxx/myproj/build/myproj.build/Release-iphoneos/mylib.build/Metal/mymetalfile.air -mios-version-min=10.2 "" /xxx/myproj/mylib/mymetalfile.metal -MMD -MT dependencies -MF /xxx/myproj/build/myproj.build/Release-iphoneos/mylib.build/Metal/mymetalfile.dat

Currently a showstopper for me in adopting Buck.

**Comment by ryu2** [comment]
There's currently no built-in rule for Metal but you can work around this via a genrule for now:

```
genrule(
    name = "generate_default_metallib",
    visibility=["PUBLIC"],
    srcs = glob([
        "foo/bar/*.metal",
    ]),
    out = "default.metallib",
    bash = "xcrun -sdk macosx metal $SRCDIR/foo/bar/baz.metal -o $SRCDIR/baz.air;" +
           "xcrun -sdk macosx metal $SRCDIR/foo/bar/baz2.metal -o $SRCDIR/baz2.air;"
           "xcrun -sdk macosx metallib $SRCDIR/*.air -o $OUT",
)
```

**Comment by aledalgrande** [comment]
@ryu2 what is the effort to make a built-in rule for Metal? Maybe I can take a shot at it.

**Comment by ryu2** [comment]
It's not conceptually too difficult; there's just a bunch of boilerplate that needs to be written though.

You can see for an example 7fdaaf2c432e692d9811e3c2a8d299d5cf8ab8c0 and 664a01ee79283db9878181bb281d24903be032a0 which adds support for SceneKit.
