### ISSUE TITLE
Buck doesn't issue a warning when a library has no files

### ISSUE THREAD

**Issue by aledalgrande** [facebook/buck#1264]
While I was experimenting with Buck, I had trouble understanding when a glob command was not working at the beginning, since Buck doesn't issue a warning if there are no headers and no sources for a library. In that case the rule is silently ignored.

I tried to use `buck build --verbose 8` to understand which files were being included by a rule, but to no avail.

For a better UX, would it be possible to warn that a target/rule is empty?

**Comment by aiked** [comment]
@aledalgrande it's a bit more complicated than that.

There are cases where a glob depends on platform or another factor and it's an accepted scenario to not have headers or sources for some cases. Printing a message then it would confuse the user.

What we could do is create a strict mode for the BUCk files that throws in the cases that you never expect an empty glob. I think that would be a good compromise.

cc'ing @Coneko that might care about this, what do you think?

**Comment by Coneko** [comment]
It's not documented but the `build.allow_empty_globs` setting does exactly that.

You can set it in your `.buckconfig` as:

```ini
[build]
allow_empty_globs = false
```

**Comment by aiked** [comment]
Great! I will close this now.
