### ISSUE TITLE
How to support proxy authentication in buck?

### ISSUE THREAD

**Issue by Skilence** [facebook/buck#1265]
[download]
    proxy_host=proxy.example.com
    proxy_port=8080
    proxy_type=HTTP

Where can I set proxy username and password for the proxy authentication?

**Comment by Skilence** [comment]
Proxy requires permission authentication, but can not find the place to set username and password..

So:
[2017-03-27 14:21:18.352][info ][command:58d59f82-ee71-4f04-be9c-83b3385bd7c9][tid:27][com.facebook.buck.file.HttpDownloader] Unable to download https://oss.sonatype.org/content/repositories/snapshots/org/projectfloodlight/openflowj/3.0.0-SNAPSHOT/openflowj-3.0.0-20161029.095322-40.jar: authenticationrequired

**Comment by Coneko** [comment]
You can set the credentials for maven here: https://buckbuild.com/concept/buckconfig.html#credentials but I don't think you can set them for the proxy.

**Comment by Skilence** [comment]
@Coneko Thanks for your help!

I can download maven file because we have the maven mirrors, but other files  need to be downloaded by proxy. So set the credentials can not solve the problem.
I try to download the jar file by manual and put them to buck-out/bin or buck-out/gen dir, but it didn't work. Do you know how to  handle it?

**Comment by Coneko** [comment]
You will need to change the Buck code to support it.

The code lives here: https://github.com/facebook/buck/blob/master/src/com/facebook/buck/cli/DownloadConfig.java#L36 .
