### ISSUE TITLE
Dependency type in dot output

### ISSUE THREAD

**Issue by rspencer01** [facebook/buck#1266]
It would be nice to have some sort of visual distinction between the different types of `dep`, such as `provided_dep`, `dep` and `exported_dep`, such as dashed or different colored lines in the dot graph returned by `buck query --dot`

**Comment by aiked** [comment]
This sounds like a good idea! I will admit that probably won't have time to get to it but if you can hack it up I would be happy to review etc. The code you need is located at https://github.com/facebook/buck/blob/master/src/com/facebook/buck/cli/QueryCommand.java

**Comment by aiked** [comment]
Feel free to re-open if you want to go after it.
