### ISSUE TITLE
$(query_targets) parsing error

### ISSUE THREAD

**Issue by brettwooldridge** [facebook/buck#1267]
I have a genrule that looks like this:
```python
genrule (
  name = 'dist-server',
  bash = """echo $(query_targets "kind('prebuilt_jar', deps(attrfilter(labels, 'server', '//...')))") >$OUT """,
  out = 'dist-server.txt',
)
```
This rule generates the following error from Buck:
```
BUILD FAILED: Error parsing target expression //... for target //:dist-server
```
However, this interactive command from the shell works:
```
bash$ buck query "kind('prebuilt_jar', deps(attrfilter(labels, 'server', '//...')))"
//ThirdParty/deps:lucene-memory
//ThirdParty/deps:lucene-queries
//ThirdParty/deps:lucene-sandbox
...
//ThirdParty/deps:gson
```
The documentation states:
> The query_* macros accepts a quoted query expression which supports the following query functions:
> * attrfilter
> * deps
> * except
> * classpath
> * intersect
> * filter
> * kind
> * set
> * union

Of which the above expression appears to conform.

Ultimately, our goal is to generate a rule that depends (dynamically) on labeled *java_library* targets, and queries their respective outputs via ``$(query_outputs ...)`` for the purposes of copying them into a distribution folder.

Am I missing something?

**Comment by kageiit** [comment]
Make that ``` \\$(``` instead. It is breaking because buck is trying to expand it as a macro instead outputting it as is.

**Comment by brettwooldridge** [comment]
@kageiit Nope.  Because this works:
```python
genrule (
  name = 'dist-server',
 bash = 'echo $(query_targets "deps(//netld/provider.collection:com-dancer-provider-collection-kt)") >$OUT',
  out = 'dist-server.txt',
)
```
If I replace ``//netld/provider.collection:com-dancer-provider-collection-kt`` with ``//...`` it fails the same way.

**Comment by Coneko** [comment]
cc @asp2insp

**Comment by asp2insp** [comment]
the `query_*` macros only support target literals right now (no `//...` or aliases). These could be supported by plumbing a `BuckConfig` object and a `Cell` instance down to the `MacroExpander` so that the macros can resolve  them.

**Comment by asp2insp** [comment]
If you have a list of top-level targets you can specify multiple targets with `set(target_a target_b)` etc. Or you could create a top-level target that has dependencies on the targets that you care about. Expanding `//...` is really expensive during parsing, so after some discussion, we're unlikely to support it.

**Comment by brettwooldridge** [comment]
@asp2insp Thanks.  We sliced the cake in a different way to solve our use case.

**Comment by alexshtin** [comment]
@brettwooldridge, can you share your code snippet?
