### ISSUE TITLE
Time for a buck release

### ISSUE THREAD

**Issue by LegNeato** [facebook/buck#1268]
> v2016.11.11.01 - 1870 commits to master since this release

`v2016.11.11.0` is also the latest release on homebrew:

https://github.com/facebook/homebrew-fb/blob/master/buck.rb

**Comment by LegNeato** [comment]
Looks like there is a script in https://github.com/facebook/buck/blob/master/scripts/updatehomebrew.py

**Comment by aiked** [comment]
hey @LegNeato, I can't promise this will happen today but I putted on the roadmap.

**Comment by aiked** [comment]
facebook/fb/buck: stable 2017.03.29.01 (bottled), HEAD

I think this is done. Check https://github.com/facebook/buck/releases/tag/v2017.03.29.01 and tell me something is broken.

Thank you for reminding us, I will try to make this a scheduled job.

**Comment by aledalgrande** [comment]
@aiked I saw you created a release, but I think you need to also submit a change to https://github.com/facebook/homebrew-fb to make it available in Homebrew, unless I'm missing something.

**Comment by aledalgrande** [comment]
Opened https://github.com/facebook/homebrew-fb/pull/17, but there is an issue with the bottle.

**Comment by aiked** [comment]
@aledalgrande sorry, I just got back from PTO. I will get on it.

**Comment by aiked** [comment]
Done, check facebook/homebrew-fb#17.
