### ISSUE TITLE
Issue with fresh build on Windows: no module named "ng"

### ISSUE THREAD

**Issue by njlr** [facebook/buck#1275]
I have built the latest version ([fca5b9aad...](https://github.com/facebook/buck/commit/fca5b9aadd558e41084fdf4681e10fb11efda272) at the time of writing) with Ant on Windows. I installed the suggested dependencies using Chocolatey. 

The build succeeds, but when I try to run Buck I get this error: 

    File "C:\Users\...\buck\third-party\nailgun\pynailgun\__init__.py", line 1, in <module>
      from ng import NailgunConnection, NailgunException
    ModuleNotFoundError: No module named 'ng'

How (and where) should I install this module?

**Comment by njlr** [comment]
I did `choco install python2`, rebooted, rebuilt and now it works. I think that I installed Python 3 the first time.

Perhaps the docs should be clearer, or maybe the Buck program should check the Python version and throw a warning?

**Comment by ramubhai** [comment]
Gote same error.

**Comment by sdwilsh** [comment]
We should clean up the docs to specify `python2`.  @JoelMarcey can probably help with that.

**Comment by zoom2manoj** [comment]
I'm also getting this issue as below commends : 


`Traceback (most recent call last):
  File "D:\react_native\test_cases\buck\bin\..\programs\buck.py", line 8, in <mo
dule>
    from buck_tool import BuckToolException, RestartBuck, install_signal_handler
s
  File "D:\react_native\test_cases\buck\programs\buck_tool.py", line 15, in <mod
ule>
    from pynailgun import NailgunConnection, NailgunException
  File "D:\react_native\test_cases\buck\third-party\nailgun\pynailgun\__init__.p
y", line 1, in <module>
    from ng import NailgunConnection, NailgunException
ModuleNotFoundError: No module named 'ng'`

**Comment by zoom2manoj** [comment]
Thanks for your support @JoelMarcey
