### ISSUE TITLE
Buck tries to use \usr\bin\gcc on Windows? 

### ISSUE THREAD

**Issue by njlr** [facebook/buck#1276]
I am trying build a hello-world example in C/C++ on Windows using Buck. 

I have installed Buck to `C:\Buck` (the space in `Program Files` seems to cause issues) and I can launch the application in PowerShell via the `PATH`: 

    PS> buck --version
    buck version *5417cc02fc9d6dbe9bd9d9a39e19b6d74f7fb90f

I have installed VS 2017, VS 2015 and LLVM 4.0. I can build the example using these tools directly, so I am confident that they are working.

However, Buck does not find any of these. When I build my `cxx_binary`, I get the following error: 

    ...
    Caused by: java.io.IOException: Cannot run program "\usr\bin\gcc": CreateProcess error=2, 
    The system cannot find the file specified
    ...
 
To verify that the platform is being detected correctly, I checked my `os.name` in Java, and it is `"Windows 10"`. 

What am I missing here?

**Comment by sdwilsh** [comment]
Buck doesn't currently support native code compilation on Windows.

**Comment by Coneko** [comment]
Should be fixed in 8617a746f2cce396bf3e11f5d9a41869fdd3cb30.

**Comment by ilya-klyuchnikov** [comment]
Buck does support native code compilation on Windows. But you have explicitly specify VS toolchain. See examples in https://github.com/ilya-klyuchnikov/buck-windows-cxx. Or you can run buck from VS dev console - then it will pick up `cl.exe`, `link.exe`, etc automatically.
