### ISSUE TITLE
Incremental changes to a class are not being picked by the APK

### ISSUE THREAD

**Issue by raviagarwal7** [facebook/buck#1277]
__Android Binary Rule__:
```
android_binary(
    name = 'bin_debug',
    manifest = ':manifest_debug',
    use_split_dex = True,
    linear_alloc_hard_limit = 16777216,
    primary_dex_patterns = [
        '^android/support/multidex/MultiDex^',
        '^android/support/v7/app/AppCompatActivity^',
        '^android/support/v4/app/FragmentActivity^',
        ...
    ],
    cpu_filters = [
        'ARMV7',
        'X86',
    ],
    includes_vector_drawables = True,
    disable_pre_dex = True,
    trim_resource_ids = True,
    deps = [
        ':res_debug',
        ':src_debug',
    ],
)
```

__Steps to repro__:
 - Add a print statement in a class method whcich doesn't go into the primary dex
 - run install `buck install //app:bin_debug`
 - the print statement doesn't gets picked up in the apk.

__Analysis__:
- buck-out/bin output which differs from 1st run
```
.bin_debug/metadata/RULE_KEY
__bin_debug_split_zip__/primary.jar
__bin_debug_split_zip__/secondary_meta/assets/secondary-program-dex-jars/metadata.txt
__bin_debug_secondary_zip__
```
- buck-out/bin output which doesn't differ from 1st run
```
__bin_debug_smart_dex__/.success/
```
Final apk in gen also remains the same

ideally `.success/classes7.dex` should have changed as the file goes into this dex file.

__First run build trace__:
<img width="1155" alt="screen shot 2017-04-03 at 2 15 47 pm" src="https://cloud.githubusercontent.com/assets/1913956/24632243/48c3c0b4-1878-11e7-8469-b07583579052.png">

__Second run build trace__ (with added print statement):
<img width="1050" alt="screen shot 2017-04-03 at 2 10 43 pm" src="https://cloud.githubusercontent.com/assets/1913956/24632261/5e0cabe8-1878-11e7-9c17-22409162787f.png">

Probably an issue in [SmartDexingStep.java#L375](https://github.com/facebook/buck/blob/master/src/com/facebook/buck/android/SmartDexingStep.java#L375) where `DxPseudoRule.checkIsCached` returns true for `classes7.dex` which should have been false.

I am not able to reproduce this issue when running with `NO_BUCKD=1`, seems like a buck daemon issue.

**Comment by raviagarwal7** [comment]
cc: @dreiss

**Comment by raviagarwal7** [comment]
tried running the build on ~15 different commits from now till 30th dec 2016, this still doesn't work. can't go before that as the app doesn't build with older versions.

**Comment by dreiss** [comment]
Can you try this?  After you build, edit, build (with buckd), and see that the changes were not picked up, can you run "buck verify-caches" and see if it reports any issues?

**Comment by raviagarwal7** [comment]
verify caches returns no errors
```
╰─$ ../buck/bin/buck verify-caches
Verifying file hash caches...
Examined 5 caches.
Examined 36137 files.
No errors
Verifying rule key caches...
```

**Comment by raviagarwal7** [comment]
**Update**
Seems like this https://github.com/facebook/buck/commit/67d8a029f87e4a6324f2286fad53073e104a01b2 introduced a regesssion for the default case i.e when `client.skip-action-graph-cache` is not set or is `false`. 

(A)
```
rm -rf buck-out
buck build //app:bin_debug --config client.skip-action-graph-cache=true
# add a print statement
buck build //app:bin_debug --config client.skip-action-graph-cache=true (change is detected)
```

(B)
```
rm -rf buck-out
buck build //app:bin_debug
# add a print statement
buck build //app:bin_debug (change is not detected)
```

also I noticed that after doing (A) if I do (B) with or without `buck clean` (instead of `rm -rf buck-out`) the change is detected as there is 100% cache hit from (A) run.

cc: @bolinfest

**Comment by bolinfest** [comment]
@raviagarwal7 So are you saying that if you use a version of Buck from before 67d8a029f87e4a6324f2286fad53073e104a01b2, everything worked as intended? That is, adding a print statement caused the change to be detected?

**Comment by raviagarwal7** [comment]
@bolinfest I remember that building from before 67d8a02 doesn't work as intended as well, but setting `client.skip-action-graph-cache=true` works.
I will try again and let you know.

**Comment by cjhopman** [comment]
It could be related to rulekey caching if disabling actiongraph caching doesn't have the problem.

**Comment by dreiss** [comment]
If that were the problem, `buck verify-caches` should have caught it.
