### ISSUE TITLE
Duplicate file for apk errors during buck build

### ISSUE THREAD

**Issue by renchiyansc** [facebook/buck#1278]
Hi I have the exactly same issue with #872 
Do we have flag support this now?
If not, can you guys share how to wrap the prebuilt_jar in a java_binary?

Thanks very much!

**Comment by renchiyansc** [comment]
@kageiit @aiked

**Comment by deadmoto** [comment]
Hitting the same error message with prebuilt jars.
The recipe described in the linked issue (java_library + remove_classes) did not work for me.
My dependencies are set up as following:
//app:apk (android_binary) -> //libs:mockito-core (java_library + remove_classes) -> //libs/mockito-core-jar (prebuilt_jar)

**Comment by henryzx** [comment]
FYI, okbuck also provided a gist for this: https://github.com/uber/okbuck/blob/master/tooling/buck-defs/cleanup.bzl
