### ISSUE TITLE
Does buck support manifestPlaceholders in AndroidManifest.xml?

### ISSUE THREAD

**Issue by ldjhust** [facebook/buck#1279]
In Gradle, manifestPlaceholder is use like below:
AndroidManifest.xml:
```shell
<meta-data 
android:name="InstallChannel" android:value="${InstallChannel}" />
```
build.gradle:
```shell
productFlavors{
    "YingYongBao"{
        manifestPlaceholders = [InstallChannel : "YingYongBao"]
    }
    "360"{
        manifestPlaceholders = [InstallChannel : "360"]
    }
}
```

Does buck support this or a similar feature?

Thank you very much!

**Comment by Coneko** [comment]
You can generate the `AndroidManifest.xml` file from a `genrule` and do whatever you want as far as I can tell: https://buckbuild.com/rule/genrule.html

Alternatively this might be what you are looking for: https://buckbuild.com/rule/android_binary.html#manifest_entries

**Comment by Coneko** [comment]
Oh I just noticed it's not documented: `manifest_entries` can contain a `placeholders` value, which is a map of placeholder names to placeholder values.

**Comment by ldjhust** [comment]
OK, thanks very much @Coneko !
