### ISSUE TITLE
genrule(): Make deps to targets used in $(exe //path/to:target) and $(location //path/to:target) macros implicitly

### ISSUE THREAD

**Issue by davido** [facebook/buck#128]
Buck handles dependencies accross different rules inconistently. For all these rules the dependency to `:foo` will be made implicitly:

```
java_library(
  name = 'lib',
  srcs = [:foo],
)

prebuilt_jar(
  name = 'jar',
  binary_jar = ':foo',
)

java_binary(
  name = 'app',
  manifest_file = ':foo',
)
```

In this light it's kind of unexpected, that macros `$(exe //path/to:target)` and `$(location //path/to:target)` require me to list the dependencies explicitly, as it's stated in the documentation:

```
[...]
Note that all build rules expanded in the command must be listed
in the deps parameter of the genrule().
```

So while this currently has to be:

```
genrule(
  name = 'foo',
  cmd = '$(exe :bar) $(location :baz)',
  deps = [
    ':bar',
    ':baz',
  ],
)
```

this obviously must just be (especially following DRY principle):

```
genrule(
  name = 'foo',
  cmd = '$(exe :bar) $(location :baz)',
)
```

**Comment by spearce** [comment]
The documentation still says the deps is required:

http://facebook.github.io/buck/rule/genrule.html

$(location //path/to:target)
Expands to the location of the output of the build rule. This means that you can refer to these without needing to be aware of how Buck is storing data on the disk mid-build.
Note that all build rules expanded in the command must be listed in the deps parameter of the genrule().
