### ISSUE TITLE
Buck doesn't package java resources in to the android_library rule.

### ISSUE THREAD

**Issue by runningcode** [facebook/buck#1280]
If you add java resources to an android_library rule like so:
```
resources = glob([
     'resources/**',
]),
resources_root = 'resources',
```
They do not get packaged in to the final APK, but if this same android_library rule depends on a prebuilt_jar which contains java resources, they will get packaged in to the final APK.

Here is a sample with a repro of this issue:
https://github.com/fbsamples/bucksamples/compare/master...runningcode:no/resources?expand=1

**Comment by dreiss** [comment]
This was done intentionally to match the behavior of the official Android build system at the time (ant).  What do you think is the proper behavior, and why?

**Comment by runningcode** [comment]
Why does the android_library rule have `resources` and `resources_root` options if they are ignored?

By default, the Android Gradle Plugin includes resources in the `src/main/resources` folder of your build. The resources are included based on the following rules: https://google.github.io/android-gradle-dsl/current/com.android.build.gradle.internal.dsl.PackagingOptions.html

**Comment by dreiss** [comment]
I think it just inherits them from java_library, and they aren't totally ignored.  They would be included in a java_binary. :)

**Comment by dreiss** [comment]
We could probably add support for merging these resources in.  I'm not sure what the unintended consequences would be, though.

BTW, why do you need this?  IIRC, getResourceAsStream allocates a ton of heap memory on Android, and using the AssetManager works much better.

**Comment by runningcode** [comment]
Yeah we're in the process of migrating our code so we stop relying on this, but I can see this being a blocker for other people trying to use buck. It took me a long time to diagnose. 

Also, if an android_library rule depends on a java_library rule with these resources, they don't get picked up in that situation either.

**Comment by kageiit** [comment]
They do get picked up if `android_library` depends on `prebuilt_jar`s though

**Comment by dreiss** [comment]
Discussed this with @kageiit and @runningcode .  Here's a summary:

- Doing this is generally a bad idea because it's bad for build perf and runtime perf.
- Gradle does this by default, so we should probably support it.
- The way to do it is add an option to android_binary to add itself to com.facebook.buck.android.AndroidPackageableCollection#pathsToThirdPartyJars (probably after renaming it).
