### ISSUE TITLE
How to merge same name attribute in different aar module?

### ISSUE THREAD

**Issue by ldjhust** [facebook/buck#1281]
I have a big android project, which depends on some aar modules, and some of these modules have some same name attributes. When I build the project with buck, there are some errors like below:
```
Attribute "xxx" has already been defined
```

As I can't modify the aar module, how can I solve this problem? Has there a solution to merge the attributes in different aar module?

Thank you very much!

**Comment by marcinkosiba** [comment]
> Has there a solution to merge the attributes in different aar module?
no, buck doesn't have a feature like that.

> As I can't modify the aar module,
Can you ask the authors of the .aar modules to use unique names for the attributes? otherwise you can write a genrule that unzips the .aar, removes the attributes that are conflicting and re-zips it.
```
genrule(
  name='fix_aar',
  cmd='', # you need to figure this out
)

android_prebuilt_aar(
  name='aar',
  aar=':fix_aar'
)
```
