### ISSUE TITLE
Buck unable to rebuild from source when used as a git submodule

### ISSUE THREAD

**Issue by mustafasc** [facebook/buck#1284]
If Buck is embedded in a Git repo as a submodule, it is unable to infer that it can rebuild from source. This makes a project's .buckversion unusable since Buck does not respect it nor is it aware to rebuild from source.

```
$ git submodule status
 4f26248a5e8c3102a37812f90afd9f62fce35725 fbuck (v2016.11.11.01)
$ fbuck/bin/buck --version
buck version N/A
```

The source of the problem is this statement:
```
os.path.isdir(dot_git)
```
https://github.com/facebook/buck/blob/master/programs/buck_repo.py#L146

For submodules, `.git` is not a directory but a file:
```
$ cat fbuck/.git
gitdir: ../.git/modules/fbuck
```

The fix should be to also allow `.git` to be a gitdir reference.

Thanks!
Mustafa

**Comment by Coneko** [comment]
Thanks for letting us know!

I don't remember the specifics, but I remember something similar was brought up before.

Unfortunately we're deprecating the self-building feature of Buck in favour of using the built PEX, so we probably won't be looking at this, sorry.

**Comment by mustafasc** [comment]
@Coneko - Can you elaborate on how Buck will bundle built Java classes into PEX (my assumption was that it's for bundling Python code)? 

If there is already documentation on the details, that'd be great. 

Thanks!

**Comment by Coneko** [comment]
The jars are added as a resource, see https://github.com/facebook/buck/blob/master/programs/BUCK .
