### ISSUE TITLE
Linker flag location macros don't get expanded during Xcode project generation

### ISSUE THREAD

**Issue by ProfessaA** [facebook/buck#1294]
I have an `apple_library` with an exported linker flag that uses the location macro.  The macro does not get expanded during xcode project generation resulting in a linker error.  I noticed the project generator is using an `AsIsLocationMacroExpander` to explicitly not expand those macros but don't understand why.  In my case, I'm trying to `-force_load` a prebuilt library via:

```
apple_library(
    ...
    exported_linker_flags = [
        '-force_load $(location :my-library.a)'
   ],
)

genrule(
    name = 'my-library.a',
    srcs = ['my-library.a'],
    cmd = 'cp $SRCS $OUT',
    out = 'my-library.a',
)
```

which works find when building with buck but not when building the resulting xcode project.

**Comment by Coneko** [comment]
cc @dinhviethoa

**Comment by Coneko** [comment]
This is a known issue but I don't know what our plans for this are.

**Comment by ProfessaA** [comment]
@Coneko I've addressed this issue in https://github.com/facebook/buck/pull/1315.  can you take a look and make sure the approach is okay? thanks!

**Comment by ryu2** [comment]
Sorry for the delay; I'll take a look at this tonight.  There might be some hacky stuff we have that may depend on the current behavior, but I'll let you know.

**Comment by ProfessaA** [comment]
Great, thanks!
