### ISSUE TITLE
Feature request: Allow to specify relative build/test targets

### ISSUE THREAD

**Issue by sk-** [facebook/buck#130]
Having to specify the full target when building or testing is really annoying.

It would be nice if when in directory java/src/foo/bar

`buck build test` is equivalent to do `buck build //java/src/foo/bar:test`

This would also normalize a little how targets are defines, as in BUCK files relative specifications are valid.

**Comment by Coneko** [comment]
We recently added build target pattern support from the command line, so specifying relative build and test targets would be even more confusing.

We're going to leave it be.

**Comment by evancox10** [comment]
I know this issue has been closed for a while, but I wanted to double check that this is in fact how Buck determines the project root:

"Mostly what we're missing at this point is an official way to determine the root of your project, the way git looks for the nearest .git directory. Probably we would use .buckconfig for this?"

I couldn't find anything that documents this.

Also, I think I could make a case for a need to use CWD-relative and/or current-BUCK-file-relative paths in my (admittedly very niche) use case. Should I raise a new issue?

**Comment by Coneko** [comment]
I suppose we never documented it, but I think that is how it's determined in the code.

This issue is about CWD relative targets.

Open a new one for targets relative to the current build file.

**Comment by Qix-** [comment]
I've written a pretty thorough explanation of the problem along with two proposed solutions at #939 as some of your here have suggested. I couldn't find anything else in the tracker regarding this other than this ticket.
