### ISSUE TITLE
Improve resolution of symbols in buck project --skip-build

### ISSUE THREAD

**Issue by kageiit** [facebook/buck#1300]
The libraries/xml files have references to jars in buck-out even if they are prebuilt jars/aars

It seems wasteful to have to force users to do a build to resolve those symbols
instead of directly pointing at the prebuilt jar/unzipped aar (unzip should be very cheap to do even with `--skip-build`) location.

It would have more symbols then without building for prebuilts and only codegen symbols would be missing then

**Comment by kageiit** [comment]
cc @styurin @dreiss

**Comment by styurin** [comment]
First of all, `prebuilt_jar` works as you described, the library xml contains a reference to a jar in repo, not in `buck-out`.

`prebuilt_aar` needs to be built because IntelliJ doesn't support aar files (or I am not aware of the way to set it up in libraries / modules).

**Comment by kageiit** [comment]
can we atleast unzip the aar to point at the classes.jar directly?
Im not aware of anything else being needed here to get symbol resolution
except R files, but its better than nothing

**Comment by styurin** [comment]
You can do that without introducing new functionality in buck project, just find prebuilt_aar targets in dependencies of the target and build them.

**Comment by kageiit** [comment]
That sounds like a good idea. Will pursue that further. Thanks!

**Comment by kageiit** [comment]
Was hoping to use `initial_targets` as documented in https://buckbuild.com/concept/buckconfig.html#project.initial_targets

But found out its only for apple projects generation - https://github.com/facebook/buck/blob/93e2aafe9c8031f2b086a589e53bbc068dcf0bf1/src/com/facebook/buck/apple/project_generator/ProjectGenerator.java#L235

:(
