### ISSUE TITLE
Java tests within suites cannot be filtered

### ISSUE THREAD

**Issue by shs96c** [facebook/buck#1301]
At some point in Buck's lifecycle, a test within a suite could be the target of a filter:

```
@RunWith(Suite.class)
@Suite.SuiteClass({
  SomeTest.class,
  SomeOtherTest.class
})
public class SmallTests {}
```

`buck test //:test-target -f SomeTest`

would only run `SomeTest` and not `SomeOtherTest`. This now no longer works, and makes working with test suites incredibly cumbersome.

**Comment by illicitonion** [comment]
@marcinkosiba you changed test filtering a while ago...

**Comment by marcinkosiba** [comment]
a while being a long time ago. I don't recall intentionally changing test suite behavior, but given how magical test running is's possible this changed unintentionally.

**Comment by v-jizhang** [comment]
Hi, I'm closing this issue because it has not been updated form more than 3 years. Thanks
