### ISSUE TITLE
Cannot use cells with gtest_dep

### ISSUE THREAD

**Issue by njlr** [facebook/buck#1309]
I have put my Google Test clone in a cell, and set my `.buckconfig` accordingly: 

    [repositories]
      gtest = ./google/gtest/

    [cxx]
      gtest_dep = gtest//:gtest

However, when I run `buck test`, I get the error: 

    java.lang.IllegalStateException: Raw data claims to come from [google/gtest/], but we tried rooting it at [].

Is this a bug?

**Comment by Coneko** [comment]
cc @mzlee

**Comment by njlr** [comment]
Interestingly if I try to run `buck test` again it succeeds. Perhaps a cache is affecting this?
