### ISSUE TITLE
Resources option for cxx_binary?

### ISSUE THREAD

**Issue by njlr** [facebook/buck#1316]
Sometimes a C/C++ application expects resources relative to the executable. 

For example: 

```
+-- game.exe
    +-- content
        +-- player.png
        +-- coin.wav
        +-- etc... 
```

Is there are way to encode this information into a `cxx_binary`?

I think something like this would be reasonable: 

```
cxx_binary(
  name = 'game',
  header_namespace = '',
  headers = subdir_glob([
    ('include', '**/*.hpp'),
  ]),
  srcs = glob([
    'src/**/*.cpp',
  ]),
  resources = subdir_glob([
    ('', 'content/**/*.png'),
    ('', 'content/**/*.wav'),
  ]),
)
```

**Comment by aiked** [comment]
cc @andrewjcg

**Comment by andrewjcg** [comment]
We don't have a way to support this now, as Buck just generates native executable formats from a `cxx_binary` rule (e.g. ELF, MachO).  I think we'd either need to use a higher-level format (e.g. like `python_binary` rules) or do some trickery with embedding resources in the native executable format (e.g. in a manually added ELF section) and have some library code to access it.  Either way, it's likely not trivial.

**Comment by njlr** [comment]
I don't mean the resources have to be embedded, just put alongside the executable.

**Comment by ryu2** [comment]
The best strategy would be to use a genrule to package your binary and resources as needed.

**Comment by aiked** [comment]
This looks resolved. @njlr feel free to re-open if the genrule solution isn't good enough.

**Comment by njlr** [comment]
@ryu2 Yes, this is the solution I arrived at. What is slightly annoying is that you cannot launch a `genrule` via Buck (or can you?)

```
buck run :game-bundle
```

**Comment by Coneko** [comment]
You can also use `sh_binary` which is undocumented, it has support for resources.
