### ISSUE TITLE
Remove autodetection of IDE in `buck project`

### ISSUE THREAD

**Issue by styurin** [facebook/buck#1324]
`buck project` tries to detect an IDE it's not specified in arguments or in the config.

We need to remove this option in order to avoid any possible confusions when a repo contains both targets for XCode and IntelliJ. Developers will need either specify IDE using command line arguments or in the config.

**Comment by kageiit** [comment]
Can IjProject not just generate the right project files based on the target type?

**Comment by styurin** [comment]
> Can IjProject not just generate the right project files based on the target type?

I'm not sure I understand the question, but this issue doesn't affect how `buck project` works for IntelliJ. It only makes the choice of IDE explicit and removes the autodetection.
