### ISSUE TITLE
Python: bundled pex does not correctly resolve binary wheels

### ISSUE THREAD

**Issue by evanj** [facebook/buck#1330]
I'm trying to use Buck with a set of `prebuild_python_library` rules that include binary dependencies. For example, `grpcio-1.3.0-cp27-cp27m-macosx_10_10_intel.whl`. Unfortunately, the version of pex that is currently bundled with buck (1.1.0 it seems) does not resolve this dependency correctly. The `.pex` that is built includes the files, but does not find them. I suspect this is because my current platform does not exactly match the bundled binary wheel. The resolution to fall back to older versions of OS X was added to pip somewhat recently, so I suspect a newer version of pex would likely fix this.

I tried updating the bundled version of pex, but I got some `TypeError: must be string, not None` error, so I'm not sure this is a trivial upgrade.

Output of running with `PEX_VERBOSE=5` shows that it failed to resolve it, despite containing a correct file:

```
pex: Unresolved requirements:
pex:   - grpcio
pex: Distributions contained within this pex:
pex:   - appdirs-1.4.3-py2.py3-none-any.whl
pex:   - six-1.10.0-py2.py3-none-any.whl
pex:   - protobuf-3.3.0-py2.py3-none-any.whl
pex:   - pyparsing-2.2.0-py2.py3-none-any.whl
pex:   - setuptools-35.0.2-py2.py3-none-any.whl
pex:   - enum34-1.1.6-py2-none-any.whl
pex:   - grpcio-1.3.0-cp27-cp27m-macosx_10_10_intel.whl
pex:   - futures-3.1.1-py2-none-any.whl
pex:   - packaging-16.8-py2.py3-none-any.whl
Failed to execute PEX file, missing compatible dependencies for:
grpcio
```

Exception after attempting to blindly update `buck/third-party/py/pex` to the latest upstream version:

```
stderr: Traceback (most recent call last):
  File "/Users/ej/pythonmono/buck/src/com/facebook/buck/python/make_pex.py", line 181, in <module>
    sys.exit(main())
  File "/Users/ej/pythonmono/buck/src/com/facebook/buck/python/make_pex.py", line 178, in main
    pex_builder.build(output)
  File "/Users/ej/pythonmono/buck/third-party/py/pex/pex/pex_builder.py", line 424, in build
    self.freeze(bytecode_compile=bytecode_compile)
  File "/Users/ej/pythonmono/buck/third-party/py/pex/pex/pex_builder.py", line 408, in freeze
    self._prepare_bootstrap()
  File "/Users/ej/pythonmono/buck/third-party/py/pex/pex/pex_builder.py", line 365, in _prepare_bootstrap
    name='setuptools')
  File "/Users/ej/pythonmono/buck/third-party/py/pex/pex/util.py", line 98, in distribution_from_path
    for dist in find_distributions(path):
  File "/Users/ej/pythonmono/buck/third-party/py/setuptools/pkg_resources/__init__.py", line 1935, in find_distributions
    importer = get_importer(path_item)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pkgutil.py", line 384, in get_importer
    importer = path_hook(path_item)
TypeError: must be string, not None
```

**Comment by mikekap** [comment]
I believe if you want to update pex, you have to do a tiny patch that stops it from bundling setuptools: https://github.com/facebook/buck/commit/ca391dfdb3bf5914f3f5618eb054211507dc3466 . See https://github.com/facebook/buck/blob/master/third-party/py/pex/README.facebook for the full list of local patches - some of those may have been upstreamed as well.

**Comment by evanj** [comment]
YES! That did the trick, and that confirms it fixes this particular bug: I can now include native `.whl` dependencies on my Mac and the resulting build works! Thank you!

I'm willing to submit a pull request with this, however I suspect that this is the sort of change that someone who works on Python support for Buck will probably need to make, since I suspect it could break all sorts of subtle things. :)

**Comment by sdwilsh** [comment]
I think the last time we did this we just relied on tests and hoped for 
the best.  Not the best, but we do have decent test coverage.

**Comment by evanj** [comment]
In that case I will make an attempt the next time I find some time to play with this again, which might take a couple weeks. Thanks!
