### ISSUE TITLE
homebrew-fb/buck.rb references deleted version 2017.05.04.01

### ISSUE THREAD

**Issue by seichert** [facebook/buck#1334]
In the facebook/homebrew-fb repo, the buck.rb file references `2017.05.04.01` .  The tag for this version was deleted.  The most recent tagged version is `2017.03.29.01`

**Comment by aiked** [comment]
I'm sorry for that, that is my fault. The latest release was broken and I had to remove it. I will update with a new version tomorrow. Until then you can follow instructions at https://github.com/facebook/buck/issues/1323

Again, sorry for that :(

**Comment by aiked** [comment]
The new release is https://github.com/facebook/buck/releases/tag/v2017.05.09.01 and it should address any issues.
