### ISSUE TITLE
Trace files created by buck are too large to view

### ISSUE THREAD

**Issue by kageiit** [facebook/buck#1335]
According to https://github.com/catapult-project/catapult/issues/298#issuecomment-223157738 the v8 engine has a hard cap of 250mb for a chrome trace file. This means large builds  cannot be viewed at all in the chrome trace viewer.

Can the trace files be split up somehow if they are larger than the limit in buck? Or is there another viewers buck recommends to use?

**Comment by jkeljo** [comment]
What's your preferred way of viewing traces? Do you use about:tracing or the Buck builtin webserver?

It looks like there was a [change recently](https://github.com/catapult-project/catapult/commit/9e43159fc62c2ba87c5dd5202e38aeb5e207bb68) to enable streaming of gzipped traces, which could help with this.

**Comment by kageiit** [comment]
we use about tracing because some of the traces we collect are from our ci servers. How can we view those traces in the buck builtin web server?

**Comment by aiked** [comment]
I think we fixed that internally by tweaking the source code of tracing. @k21 was the person who knows the most around this.

**Comment by k21** [comment]
The change I made internally was to remove an assert that limited the duration of the trace to ~500 seconds. AFAIK the assert has been either removed or the limit has been increased in the latest released version of the trace viewer so the tweaking should no longer be necessary. I didn't look into working around v8's max string length limit.

**Comment by jkeljo** [comment]
Enable the server and the trace link is printed after the build, or you can navigate to its root page and go from there. However, the buck builtin web server uses a really old version of the viewer, so you're better off with chrome://tracing anyway.

I just tried the new streaming support on a big trace and it seems like it may not actually work yet.

**Comment by marcinkosiba** [comment]
> Can the trace files be split up somehow if they are larger than the limit in buck? Or is there another viewers buck recommends to use?

A while back I wrote scripts/slice_trace.py. It's not perfect as events that span slices are not duplicated, but at least you can view the trace file.

**Comment by msridhar** [comment]
Ah nice, [`slice_trace.py`](https://github.com/facebook/buck/blob/d609be052ddd49a746e185fadf6df08cc19af6d2/scripts/slice_trace.py) looks like a good option; thanks!

**Comment by sleighsoft** [comment]
How can you slice a json?

**Comment by ttsugriy** [comment]
@sleighsoft, the `slice_trace.py` script slices traces into time windows of time that does not exceed Chrome trace limit. You'll get multiple trace file fragments and you'll have to view each separately.

**Comment by sleighsoft** [comment]
It fails for me with "unhashable type". I am using python 2.7

**Comment by sleighsoft** [comment]
Well probably my file is not in the same format that is used by buck. Forget my question
