### ISSUE TITLE
Buck breaks symlinks when restoring from the cache

### ISSUE THREAD

**Issue by seanabraham** [facebook/buck#1336]
For output directories that have symlinks among them buck breaks these symlinks if the directory is restored from a cache. As an example example, if attempting to install `node_modules` from a `package.json` file via a genrule, `npm` creates symlinks if any of the modules created has a binary specified in it's `package.json` https://docs.npmjs.com/files/package.json#bin (`yarn` does this as well). Postinstall scripts that run after `npm install` depend on these symlinks to be linked properly and fail when they are not. Buck seemingly replaces the symlink with the contents of the file that was symlinked, but that usually doesn't not work in these cases since the files themselves reference relatives paths.

Is there a way to maintain symlinks? Tangentially, but also related, is there a recommended way of installing node modules via Buck?

**Comment by v-jizhang** [comment]
Hi, I'm closing this issue because it has not been update for more than 3 years. Thanks
