### ISSUE TITLE
Does 'buck install' support version comparison? 

### ISSUE THREAD

**Issue by duanbouber** [facebook/buck#1348]
For non-exo package, when running 'buck install', sometimes the build step doesn't necessarily do anything because no code change since last build/installation which makes sense. But for this case, the cmd still installs the apk to emulator/device, even the apk installed on emulator/device has been up to date.

Is there a parameter to instruct buck to compare the 'apk installed' the 'apk to install' before pushing the apk to device/emulator? If the 'apk installed' is outdated, then install the newer one; otherwise, does nothing.

**Comment by v-jizhang** [comment]
Hi, This issue is closed because it has not been updated for more than 3 years. Thanks
