### ISSUE TITLE
Option for outputting build commands from buck build

### ISSUE THREAD

**Issue by michaeleiselsc** [facebook/buck#1350]
I want to create a compilation database (https://clang.llvm.org/docs/JSONCompilationDatabase.html) so that I can use it with linters like OCLint and clang static analyzer. However, I don't see any way to get the actual build commands that buck is using, except to parse them out of other input when the verbose flag is on. It would be great to have an option to output the compilation database.

**Comment by Coneko** [comment]
Try `buck build target#compilation-database`.

**Comment by michaeleiselsc** [comment]
Awesome! Now is there any way to get that output without doing a full build? I just want to lint a few of the files in my project each time (those that changed in whatever PR)

**Comment by Coneko** [comment]
What do you mean doing a full build? That command will only build the necessary things to make the compilation database meaningful, like generated headers and sources, header maps, symlink trees and sandboxes.

You won't be able to create the right clang translation units without them.

We used to have a way to create almost equivalent commands skipping many of the steps, but the "almost" part of the equivalence meant there were always subtle differences between what our tooling thought the build would be and what the actual build was so we got rid of it.
