### ISSUE TITLE
Create Installation Package of Buck

### ISSUE THREAD

**Issue by nordlow** [facebook/buck#1359]
Is there a way to create an installation package for buck from its sources?

I can't find an `ant` subcommand that does that.

**Comment by Coneko** [comment]
You can create a single file executable of it by first building it with ant and then running `buck build buck --show-output`.

The resulting file is a self extracting python executable package (https://github.com/pantsbuild/pex).

**Comment by nordlow** [comment]
Doesn't work for me:

```
[$USER:~/ware/buck] master ± bin/buck build buck --show-output
/usr/bin/python2: can't open file './bin /home/per/ware/buck/bin/../programs/buck.py': [Errno 2] No such file or directory
```

**Comment by sdwilsh** [comment]
Did you build it with `ant` first?  Although, that error message seems to imply that `programs/buck.py` in the repository doesn't exist, and it should if you have a clean `git` working copy.
