### ISSUE TITLE
buckd on Windows

### ISSUE THREAD

**Issue by jeeloo** [facebook/buck#1361]
I have been trying to build a C/C++ project on windows and one thing that I have noticed is that there is a new buckd process for each time I invoke "buck build". I just have these two files in a folder

BUCK:
```
cxx_binary(
        name = 'echo',
        srcs = [ 'hello-world.c', ],
)
```
hello-world.c:
```
#include<stdio.h>
main()
{
    printf("Hello World!\n");
}
```
And no matter if it is up to date or not a new buckd process i spawned every time, I have watchman in the path and that is being used

```
> ...\bin\buck build -j 1 //:
Using watchman.
[-] PARSING BUCK FILES...FINISHED 0.0s [100%]
BUILT 1/5 JOBS 0.1s //:echo#default,private-headers
BUILT 2/5 JOBS 0.0s //:echo#default,preprocessor-deps
hello-world.c
BUILT 3/5 JOBS 0.6s //:echo#compile-hello-world.c.obj5c20620a,default
BUILT 4/5 JOBS 0.3s //:echo#binary
BUILT 5/5 JOBS 0.0s //:echo
[-] BUILDING...FINISHED 3.4s [100%] (5/5 JOBS, 5 UPDATED, 3 [60.0%] CACHE MISS)
[-] DOWNLOADING... (0.00 B/S AVG, TOTAL: 0.00 B, 0 Artifacts)
```

**Comment by ilya-klyuchnikov** [comment]
I failed to reproduce it. @jeeloo could you run the following command in Powershell ` Get-WmiObject Win32_Process -filter "CommandLine like 'buck%'"` and put the output here?

**Comment by jeeloo** [comment]
@ilya-klyuchnikov here you go [buckd.txt](https://github.com/facebook/buck/files/1046834/buckd.txt)

**Comment by ilya-klyuchnikov** [comment]
@jeeloo could you try https://github.com/ilya-klyuchnikov/buck/commit/c2a8dcbedf2a63a1f591cc4e33a70fdaa4bdacbd? Thanks

**Comment by jeeloo** [comment]
@ilya-klyuchnikov I still get the same behaviour.

**Comment by ilya-klyuchnikov** [comment]
According to your logs you have Windows 7 Enterprise. 
Internally, buckd on windows uses windows named pipes for communication between client/server. We are testing/supporting it only on Windows 10 reliably so far. It is quite possible that we hit default system settings when we create named pipes and these settings are forbidding to create named pipes on your machine. 

I am sorry, but we don't have any bandwidth to investigate/fix it right now. 

You could enable `NO_BUCKD=1` system var, and use buck without daemon.
