### ISSUE TITLE
Annotation Processors written in Kotlin are not visible to BUCK

### ISSUE THREAD

**Issue by ZacSweers** [facebook/buck#1366]
Here - https://github.com/facebook/buck/blob/master/src/com/facebook/buck/jvm/java/AnnotationProcessorFactory.java#L67-L77

I can't get much interesting stuff from the trace, but I get this
```
:src_main: javac unable to load annotation processor: com.uber.synapse.SynapseProcessor
```

Other services load fine when I write them in kotlin though, this seems something specific to how BUCK does annotation processors and what classloader it's using. I'll try to get a repro case up.

CC @kageiit

**Comment by Coneko** [comment]
cc @dsyang @brettwooldridge

**Comment by brettwooldridge** [comment]
Maybe run dbuck and breakpoint in the catch block.  Is kotlin-stdlib in the classpath?

**Comment by runningcode** [comment]
If the annotation processor is written in kotlin, doesn't it need to be passed to kotlinc?

**Comment by hzsweers** [comment]
stdlib is on the classpath yeah. Dunno about it needing to be passed to kotlinc, the annotation processor is being used in vanilla java projects

**Comment by runningcode** [comment]
Can you tell me if you get a similar error on this branch? https://github.com/facebook/buck/pull/1358

**Comment by thalescm** [comment]
#1584 should fix it
