### ISSUE TITLE
How to install the binary files compiled by buck into my iPhone?

### ISSUE THREAD

**Issue by gongyujun** [facebook/buck#1367]
Everything is okay when I use the simulator as `default_platform=iphonesimulator-x86_64` in the `.buckconfig` file, and also I use the command `buck install demo_app_ios` to install the app into the simulator successfully.

However, I got the failure when I install it into my device. First, I use `buck build demo_app_ios#iphoneos-arm64` to build the project whether I change the `buckconfig` file's platform or not and got no error info, but I got the error log when I use `buck install -d demo_app_ios#iphoneos-arm64`, as the following error, 

```
BUILD FAILED: Cannot install //ios:BuckDemoApp#dwarf-and-dsym,iphoneos-arm64,no-include-frameworks (could not find path to device install helper tool)
```

what's the matter about it? Thank you.

**Comment by aiked** [comment]
Hello @gongyujun,

I'm afraid I can't help on this one but let's see if @beefon or @ryu2 have some insight.

**Comment by ryu2** [comment]
https://buckbuild.com/command/install.html

> For device support, you need to first build the fbsimctl utility from FBSimulatorControl and set apple.device_helper_path to its location.

I'm not sure if the homebrew fbsimctl has the current device support needed; you may need to build fbsimctl from master.

**Comment by gongyujun** [comment]
Okay, thank you so much! I have solved it.

**Comment by varun531** [comment]
Hi,

I'm trying to install and run an app on my physical device with a debugger attached. Is this currently supported? I try to run an app on my device with the following command:

`buck install -d -r calc_free_app`

I've set "device_helper_path" in .buckconfig to point at homebrew-installed simctl v0.4.0. The app IS loaded onto my phone, but it's not running. This is some of my output:

```
Installed //:CalcFreeApp#dwarf-and-dsym,iphoneos-arm64,no-include-frameworks to device 7fa1437093100eaa5b36cfc5d38b6fb8ec3c897c (Varun iPhone  6s | Unknown | iPhone 6s | iOS 10.2.1 | arm64)
'["--json", "7fa1437093100eaa5b36cfc5d38b6fb8ec3c897c", "launch", "secretcalcfree"]' does not match '[fbsimctl {{ [output] | [management] | <set> | --set <directory> }}* [targets]? {{ <format> | --format <Target Format> }}? {{ [action] ... -- [action] }}+
```

Then at the very end of the output:

`BUILD FAILED: Failed to run //:CalcFreeApp#dwarf-and-dsym,iphoneos-arm64,no-include-frameworks on device "7fa1437093100eaa5b36cfc5d38b6fb8ec3c897c" (Varun iPhone  6s | Unknown | iPhone 6s | iOS 10.2.1 | arm64)`

I also get the same error when I build fbsimctl from master:

`brew install fbsimctl --HEAD`

Any thoughts? Have other people gotten buck-built apps to run on the device with a debugger?

Any guidance is appreciated.

**Comment by ryu2** [comment]
@varun531 Thanks for the heads up.  It looks like we may need to update the parameters we pass to fbsimctl for launching.

**Comment by v-jizhang** [comment]
Hi, this issue is closed because there is no updates for over 3 years. Thanks
