### ISSUE TITLE
Method change tracking

### ISSUE THREAD

**Issue by AttwellBrian** [facebook/buck#1375]
**Issue**
Right now buck tracks changes to classes in order to determine whether or not to recompile downstream modules that depend on the changed classes.

Sometimes this results in recompilation of modules that don't actually need to be compiled. For example, consider the following two modules. 
* RootModule, which depends on ChildModule, instantiates class X
* ChildModule, defines class X

If a new method is added to class X then RootModule will be recompiled even though RootModule doesn't depend on the new method. In theory this issue can be avoided if buck tracked method changes instead of class changes.

**Question**
Will buck ever track method changes instead of class changes? Or would it be too expensive to make sense?

**Background**
I'm currently investigating making some big changes to the way we do dependency injection at Uber in order to avoid triggering recompilation of modules. However, if you have plans to add method change tracking to bug maybe I should invest my time somewhere else.

**Comment by Coneko** [comment]
cc @jkeljo

**Comment by jkeljo** [comment]
Sorry for the delay; I was on vacation. ;-)

I'm not gonna say never, but there are no concrete plans right now.

Method usage/change tracking would require a fundamentally different approach to what Buck currently does with class usage/change tracking. 

The class stuff relies on the fact that there is one .class file per class. During compilation, it tracks which class files are actually read by the compiler, and then when generating the dependency file rule key it adds only those class files to the key.

Method tracking would require switching to a static-analysis-based means of detecting dependencies, and some way of hashing single methods into the rule key.

The static analysis is doable and I think we might actually be able to piggyback off work the compiler already does. At some point I think we'll probably want to switch even the class-level stuff to static analysis. The file-based approach to dependency detection was quick to implement, but it does have its blind spots (e.g. technically for correctness adding a class in a module should have a similar effect to what you're seeing with adding a method, though I think we're not doing that right now).

The implications for rulekey computation are less obvious to me. I expect hashing individual methods has some subtleties. It would also add roughly another order of magnitude to the number of things being hashed for a dependency rule key, and those are already kinda slow to compute. I'd probably want to do some performance experiments around that before diving too deeply into the rest of it.

**Comment by AttwellBrian** [comment]
Thanks @jkeljo!

Closing this task since it is more of a question than a Feature Request.
