### ISSUE TITLE
Buck sets -fdiagnostics-color, even when it is not recognized

### ISSUE THREAD

**Issue by njlr** [facebook/buck#1379]
Building a C++ module on Travis CI I get the following error: 

 > g++: error: unrecognized command line option ‘-fdiagnostics-color=always’

According to https://github.com/manio/vdr-plugin-dvbapi/issues/72, the option `-fdiagnostics-color` was only added in GCC 4.9. 

Perhaps Buck should only set this flag once it has checked the GCC version?

**Comment by zorroblue** [comment]
I too am facing the same issue. Would be great if the maintainers could resolve it. :)

**Comment by v-jizhang** [comment]
Color diagnostics output was added in GCC 4.9.0, April 22, 2014. upgrading gcc should fix it. Thanks
