### ISSUE TITLE
name 'project_config' is not defined

### ISSUE THREAD

**Issue by aajn88** [facebook/buck#1382]
The issue is defined in this StackOverflow [question](https://stackoverflow.com/questions/44552381/buck-name-project-config-is-not-defined-how-to-solve-it)

**Comment by Coneko** [comment]
Answered on SO.

**Comment by gamwebdev** [comment]
On Jun 15,  4:06 PM, "Coneko" <notifications@github.com> wrote:

Answered on SO.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/facebook/buck/issues/1382#issuecomment-308694348>, or mute
the thread

**Comment by styurin** [comment]
Created https://github.com/fbsamples/bucksamples/pull/4 to remove these targets.
