### ISSUE TITLE
Update website with kotlin rules documentation

### ISSUE THREAD

**Issue by dsyang** [facebook/buck#1384]
Now that buck:
- can build pure kotlin targets
- can build mixed kotlin + java targets
- supports android
- is actually fast(ish)
- recognizes kotlin rules in buck project

We should add docs on how to use it on the website! 

@kageiit, @brettwooldridge, @runningcode any of you want to pick this up? :)

**Comment by brettwooldridge** [comment]
I've been thinking about that.  I'll take a look.
