### ISSUE TITLE
Kotlin rules cannot be compiled against abi jars

### ISSUE THREAD

**Issue by kageiit** [facebook/buck#1386]
f43e2d20913443d7047fd4219e7559d9108a802a introduced a regression that puts abi jars on the kotlinc classpath instead of full jars. `kotlinc` does not like this and errors out on compilation when using methods from the kotlin standard library with the following stacktrace

```
Caused by: java.lang.IllegalStateException: Couldn't obtain compiled function body for public inline fun <T> mutableListOf(): kotlin.collections.MutableList<T> defined in kotlin.collections[DeserializedSimpleFunctionDescriptor@727380c2]
	at org.jetbrains.kotlin.codegen.inline.InlineCodegen$1.invoke(InlineCodegen.java:280)
	at org.jetbrains.kotlin.codegen.inline.InlineCodegen$1.invoke(InlineCodegen.java:275)
	at org.jetbrains.kotlin.codegen.inline.InlineCacheKt.getOrPut(InlineCache.kt:34)
	at org.jetbrains.kotlin.codegen.inline.InlineCodegen.createMethodNode(InlineCodegen.java:274)
	at org.jetbrains.kotlin.codegen.inline.InlineCodegen.genCallInner(InlineCodegen.java:180)
	... 69 more

    val words = mutableListOf<String>()
                ^
```

A repro case is available here: https://github.com/uber/okbuck/tree/gk_kotlin_abi
Command to run: `./buckw build //libraries/kotlinlibrary/...`
After removing the `compile_against_abis = true` change in `.buckconfig` in the repro, everything works as expected

Seems like this option is not safe for kotlin modules yet. The kotlin compiler is actually introspecting the classes to extract out and inline the method into the compiled code. If we compile against the abi jars, the compiled method body will not be found. I think as part of refactoring and reusing base jvm descriptions etc for f43e2d20913443d7047fd4219e7559d9108a802a , it inadvertently introduced kotlinc to be able to pickup abi jars for compilation

cc @dsyang @runningcode @brettwooldridge

**Comment by kageiit** [comment]
We should add a test case with `compile_against_abis = true` and kotlin sources to prevent this from regressing in the future

**Comment by kageiit** [comment]
Closed in 128baa0

**Comment by kageiit** [comment]
Wait nvm, I remember @jkeljo wanting this to be open.

**Comment by kageiit** [comment]
Similar issue exists with scala compilation

**Comment by kageiit** [comment]
This essentially disables any sort of incremental compilation that we get with abis for kotlin and scala rules

**Comment by brettwooldridge** [comment]
On a possibility related note, I occasionally encounter cross module compilation issues (application runtime errors actually) when Kotlin code has been changed, which indicate that the Kotlin ABI changed but buck did not realize it and therefore did not recompile a dependent class.  I suspect that, even though Kotlin generates valid bytecode, there are some nuances that are missed by bucks ABI hashing.

**Comment by jkeljo** [comment]
@brettwooldridge yes, that's totally true. Buck is still using the ABIs for change detection, even though it's not compiling against them. That's a bug.

**Comment by kageiit** [comment]
There is some discussion around creating abi jars for kotlin correctly in https://github.com/bazelbuild/bazel/issues/4549

**Comment by runningcode** [comment]
Looks like there's a tool called metalava that generates APIs for kotlin libraries. Its being used in the new android extensions library. https://github.com/android/android-ktx/blob/master/build.gradle Look at the `updateApi` task

**Comment by brettwooldridge** [comment]
Unfortunately, metalava is not yet released (according to the commit history)...

**Comment by hzsweers** [comment]
Thanks! I'll take a look.

In the meantime, I think a good start would also be to re-enable ABI jars for pure java projects depending on kotlin projects to allow some progress. For java there's no difference, so I don't think there's a reason for blocking that. It's only kotlin projects depending on other kotlin projects that really need it

**Comment by tyvsmith** [comment]
@IanChilds FYI, the  jvm-abi-gen runs along with the full compilation step, so while good for ABI source jar caching, won't enable build pipelining.

**Comment by IanChilds** [comment]
Yeah I think that's fine for now, the approach for source ABIs on Kotlin will be a bit different for what we do on Java. `SupportsPipelining` is actually deprecated on Buck anyway so perhaps best that we're not taking that approach :)

**Comment by IanChilds** [comment]
Kotlin should now be able to compile against class ABIs. The one known case that it doesn't handle is the `expect` and `actual` keywords, which are currently experimental. The hacky solution here is to just set `generate_abi = False` for the prebuilt jars where they are found (seems to be coroutines for now, perhaps there are other uses too).
