### ISSUE TITLE
Feature Request: Allow Build target Patterns in buck build and buck test

### ISSUE THREAD

**Issue by sk-** [facebook/buck#139]
It would be amazing if [build target patterns](https://facebook.github.io/buck/concept/build_target_pattern.html) would also be allowed in commands like `buck build` or `buck test`.

This would be specially useful to build/test all targets in a folder.

**Comment by sdwilsh** [comment]
@andrewjcg did this in 76178fac5abdb7eacdd04e543d1c7f7890f9c539
