### ISSUE TITLE
C/C++ language standard resolution?

### ISSUE THREAD

**Issue by njlr** [facebook/buck#1396]
I am trying to figure out a good approach for resolving a language standard for C/C++ targets. 

Suppose I have a library `liba` that requires `-std=c++14`, and depends on `libb` that can compile with `-std=c++11`. I might describe this using: 

```python=
cxx_library(
  name = 'liba',
  ...
  compiler_flags = [ 
    '-std=c++14', 
  ], 
  deps = [
    ':libb',
  ],
)

cxx_library(
  name = 'libb',
  ...
  compiler_flags = [ 
    '-std=c++11', 
  ]
)
```

On most targets (e.g. macOS) this works fine, but for other targets, the ABI is different for `c++14` and `c++11`. To fix this, we can change `libb` to `-std=c++14`, but then consumers of `libb` are forced to use the later standard. 

Ideally I would be able to describe my requirements and have Buck figure it out: 

```python=
cxx_library(
  name = 'liba',
  ...
  standard = '>=c++14', 
  deps = [
    ':libb',
  ],
)

cxx_library(
  name = 'libb',
  ...
  standard = '>=c++11',
)
```

When compiling `liba` the standard would be resolved to `-std=c++14` and when compilin `libb` alone the standard would resolve to `-std=c++11`. This could also abstract over GCC args and MSVC args. 

Is there a way to do something like this as Buck stands now?

**Comment by sdwilsh** [comment]
cc @andrewjcg

**Comment by yiding** [comment]
Buck does not do global constraint solving of any kind (except maybe versioned dependencies, which i defer to @andrewjcg ).
