### ISSUE TITLE
.buckconfig project ignore not working

### ISSUE THREAD

**Issue by cwoodwar6** [facebook/buck#1402]
To repo, add a random BUCK file to a directory and add to your `.buckconfig`:
```
[project]
  ignore = your_test_directory/**
```

The newly added BUCK file is not actually being ignored. This can be observed by running `buck targets` and seeing the newly added BUCK file.

According to the [documentation](https://buckbuild.com/concept/buckconfig.html), the parameter should cause the directory to be "ignored in the following contexts" which includes "Filesystem traversal when searching for tests and BUCK files" which isn't happening here.

**Comment by yiding** [comment]
I failed to reproduce this behavior on rev db6deb45da0188f542fa1c2f862522e586abc7bf (the current master).

Here is a terminal transcript (where ~/buck-oss is my checkout)
```
~/tmp/2017-06-27/test
❯ ls -a
.           ..          .buckconfig .buckd      buck-out    foo_test

~/tmp/2017-06-27/test
❯ cat .buckconfig
[project]
ignore = foo_test/**

~/tmp/2017-06-27/test
❯ ls -l foo_test
total 8
-rw-r--r--  1 yiding  THEFACEBOOK\Domain Users  73 Jun 27 16:10 BUCK

~/tmp/2017-06-27/test
❯ cat foo_test/BUCK
genrule(
  name = 'foo',
  srcs = ['foo.c'],
  cmd = '''echo $SRCS''',
)

~/tmp/2017-06-27/test
❯ NO_BUCKD=1 PATH=~/buck-oss/bin:$PATH buck targets --json
Not using buckd because NO_BUCKD is set.
[
]
```

**Comment by kageiit** [comment]
Are you using watchman to search for buck files? If so, you may have to use .watchmanconfig to exclude it as well

**Comment by yiding** [comment]
I tried it with an empty .watchmanconfig, and behavior was still correct.

**Comment by cwoodwar6** [comment]
Here is what I changed: https://github.com/cwoodwar6/okbuck/commit/e6ec0ff9e76baa0966737117a7f4016450df1497

If I run `./buckw targets` I see `//test:res_debug`

**Comment by yiding** [comment]
Your change adds an exclusion for `test` which ignores that particular path, not paths within that directory. This is contrary to what you reported in your initial post here.

**Comment by cwoodwar6** [comment]
The result is the same no matter how I do it: https://github.com/cwoodwar6/okbuck/commit/c8657ff7bd1c968dbfb52cfc47cee41d85d1c5c2

**Comment by yiding** [comment]
Looks like okbuck creates a `.buckconfig.local` which overwrites project.ignore with:

```
[project]
	ignore = .git, **/.svn
```

This is an issue with okbuck, not buck itself.

**Comment by kageiit** [comment]
@yiding Good catch. Fixed in https://github.com/uber/okbuck/commit/2daa553db25139a69fdd1f4119207c0f519a861c
