### ISSUE TITLE
how insert some thing for apk

### ISSUE THREAD

**Issue by guhan121** [facebook/buck#1408]
Hi 
We use modularization for our app.

We build a sub apk for Some function.
Like this
![image](https://user-images.githubusercontent.com/5517369/27787702-5468780a-6018-11e7-8daa-f6ebb221f754.png)

 
For insert sub*.apk for master.apk.

We make a make a aar file.Like this:
sub1-6.4.5-release.aar
.
├── AndroidManifest.xml
├── jni
│    └── armeabi-v7a
│          └── libcom_sub1.so
└── META-INF
└── MANIFEST.MF

We only rename the sub1.apk to libcom_sub1.so ;
And copy the AndroidManifest.xml from the apk for make aar file;

So if I use this aar for BUCK android_resource and android_binary;
•	I want merge AndroidManifest.xml to master.apk;
•	And insert  libcom_sub1.so to master.apk, it save in \libs\armeabi-v7a\

**Comment by styurin** [comment]
Answered in another issue, we don't have plans to support that.
