### ISSUE TITLE
can i use a package id is not 0x7f

### ISSUE THREAD

**Issue by guhan121** [facebook/buck#1413]
when i seek the codes ,i find 
public class ResTablePackage extends ResChunk {
  public static final int HEADER_SIZE = 288;
  public static final int APP_PACKAGE_ID = 0x7F;

  @Override
  public int map(int id) {
    int resPackage = id >> 24;
    if (resPackage != ResTablePackage.APP_PACKAGE_ID) {
      return id;
    }
    int resType = (id >> 16) & 0xFF;
    int resId = id & 0xFFFF;
    int entryCount = resourceTable.getPackage().getTypeSpec(resType).getEntryCount();
    return (id & 0xFFFF0000) | (entryCount - resId - 1);
  }

Does that mean the package id is Always 0x7f ,and the id for a res is 0x7fxxxxxx;

if i want use a Different id like 0x7a ,  Can I modify the source ， add a arg for  android_binary()?

**Comment by styurin** [comment]
why do you need this?

**Comment by cjhopman** [comment]
This is only used for exo-for-resources. It only supports package id of 0x7f because that's the only thing that aapt writes by default.

But what are you trying to do? I really can't tell if this code is even relevant to you.

**Comment by guhan121** [comment]
@styurin @cjhopman because main apk is 0x7f, other apk will build for a plugin , the plugin will package as a lib_plugin_name.so in mian apk libs.we will config some plugins,so res id must be different.

**Comment by styurin** [comment]
I think you need to provide more information about what your are trying to do. What do you mean by plugin?

**Comment by guhan121** [comment]
@styurin we use the a framework like this https://github.com/wequick/Small

**Comment by styurin** [comment]
Ok, I don't think we'll be adding support for this.

**Comment by guhan121** [comment]
@styurin thanks
