### ISSUE TITLE
whether the change in dependency module automatically get affected in main modules

### ISSUE THREAD

**Issue by SMohamedMubarish** [facebook/buck#1416]
Hi,
     I am new to Buck. I have a multimodule project, in which few are dependency modules. I have added those dependency module in other module. whether compiling the changes in dependency module will automatically get affected in my main module? or I need to build every time the other modules once dependency modules are built? 

Any quick response is appreciated?

**Comment by mzlee** [comment]
Hi, Buck maintains a target graph which tracks when dependencies need to be rebuilt and propagates that to each of the other modules that depend on it. If you rebuild the main module, Buck will automatically rebuild the other depending modules it has detected as changed.

If your main modules depends on three other modules, a change to one of the depending modules should result in a rebuild for both the dependent module and the main module when you try to rebuild the main module. If you only try to rebuild the dependent module, the main module will not be rebuilt.

**Comment by SMohamedMubarish** [comment]
Yes lee... Thanks for your input.. if I am using my dependent module in three different modules.. do I need to rebuild each module after building the changes in dependent module.

**Comment by mzlee** [comment]
Yes, you would need to rebuild anything that depends on a module that has changed. But this makes sense because it's not clear whether or not the depending modules needs any of the changes.
