### ISSUE TITLE
Buck IntelliJ plugin won't run instrumentation tests in androidTest

### ISSUE THREAD

**Issue by cwoodwar6** [facebook/buck#1420]
Tests located in the `androidTest` directory have the buck gutter icon but choose the wrong target to invoke. Instead of choosing `//app:instrumentation_debug_test` they by default choose `//app:lint_debug_test`

**Comment by styurin** [comment]
What does `buck query 'owner(filename)'` returns?

**Comment by cwoodwar6** [comment]
```
//app:lint_debug_test
//app:src_debug_test
```

**Comment by styurin** [comment]
I suppose plugin chooses the first target. How do you use `lint_debug_test`?

**Comment by cwoodwar6** [comment]
We actually aren't actively using that target, it is auto generated for us via OkBuck. But basically it runs lint over the androidTest source directory. I suppose I could remove it to get around this. Is the list sorted alphabetically and picks the first one? I could also try renaming the target to hopefully change the ordering.

**Comment by cwoodwar6** [comment]
I also realize the second target is wrong. This is an instrumentation test, I'd need the `android_instrumentation_apk` rule (target of //app:instrumentation_debug_test) in order to run this test. `//app:src_debug_test` is the `android_library` that compiles the code, but not the target I need to run. I'm guessing this is something that `buck query` just isn't set to handle?

**Comment by styurin** [comment]
I think we can add support to exclude targets from testing using specific labels.

As for `android_instrumentation_test`, we would need to add support for such tests. This can be a bit messy because there might be multiple tests for a given library or an apk.

**Comment by v-jizhang** [comment]
This issue is closed because it has not been updated for more than 3 years. Thanks
