### ISSUE TITLE
can i use jcenter or maven

### ISSUE THREAD

**Issue by guhan121** [facebook/buck#1421]
can  buck automatic download  libs or jars ?

like gradle use compile "....."

i find buck have a function remote_file
but user must give it sha1 and url;  it is so difficulty ,Why can't buck download them automatic.

**Comment by sdwilsh** [comment]
It will never be automatic for Buck.  One of the core principles of Buck is build reproduciblity, which means you need to know that the bits you download from the Internet are what you expect them to be (hence the sha1) and how to get it (hence the url).
