### ISSUE TITLE
"applicationId" is not provided as default manifest placeholder 

### ISSUE THREAD

**Issue by silentnuke** [facebook/buck#1425]
@kageiit added manifest placeholders support at this PR https://github.com/facebook/buck/pull/753
However comparing to Gradle it doesn't provide a default placeholder [applicationId](https://developer.android.com/studio/build/manifest-build-variables.html) which should be a final package name.

It's defiantly possible to specify it manually, but would be nice if it would be provided by default.

**Comment by v-jizhang** [comment]
Hi, this issue is closed because it has not been updated for more than 3 years. Thanks
