### ISSUE TITLE
build failure on win: BUILD FAILED: No native platforms detected. Probably Android NDK is not configured properly.

### ISSUE THREAD

**Issue by krossford** [facebook/buck#1426]
windows10 cmd build
my env config:
ANDROID_HOME: D:\dev_programs\android-sdk
ANDROID_SDK: D:\dev_programs\android-sdk
ANDROID_NDK_REPOSITORY: D:\dev_programs\android-ndk-r13b

in D:\dev_programs\android-ndk-r13b
--- build
--- platforms
--- prebuild
--- ndk-build.cmd
--- ndk-depends.cmd
--- etc...

in D:\dev_programs\android-sdk
--- add-ons
--- build-tools
--- docs
--- AVD Manager.exe
--- etc...

so, I just build the demo app, and I got a problem
BUILD FAILED: No native platforms detected. Probably Android NDK is not configured properly.

**Comment by styurin** [comment]
`ANDROID_NDK_REPOSITORY` should point to a folder that contains specific versions of NDK. In your case it's `D:\dev_programs`

**Comment by yiding** [comment]
BTW android rules that uses the NDK doesn't currently work properly on windows, so @ilya-klyuchnikov  tells me.

**Comment by lyrachord** [comment]
both env and project config may be
but this case env was set, so the problem should be at project config.
see [https://buckbuild.com/concept/buckconfig.html#android.build_tools_version](url)

modifiy .buckconfig in project should be ok
f.e. 
[ndk]
  ndk_version = 15.1.4119039

**Comment by erhu** [comment]
@krossford
Add 
```
ANDROID_HOME=/Users/xxx/Library/Android/sdk
ANDROID_NDK=/Users/xxx/Library/Android/sdk/ndk-bundle
```
to your .buckconfig file.

**Comment by shaliniprajeshwynk** [comment]
This wasn't working for me too.After hit and trial, following got this working...
I uninstalled android ndk then installed and added following lines in bash and buckconfig file respectively.

bash file 
export ANDROID_SDK="/Users/<username>/Library/Android/sdk/"
export ANDROID_HOME="/Users/<username>/Library/Android/sdk/"
export ANDROID_NDK="/Users/<username>/Library/Android/sdk/ndk-bundle"
export NDK_HOME="/Users/<username>/Library/Android/sdk/ndk-bundle"

buckconfig file
  ndk_path = /Users/<username>/Library/Android/sdk/ndk-bundle
  ndk_version = 17.1.4828580[note the version while it is installing]

And it worked
