### ISSUE TITLE
reproducibility, system libraries and dynamic compiler-flags

### ISSUE THREAD

**Issue by nikhedonia** [facebook/buck#1430]
on [reddit](https://www.reddit.com/r/cpp/comments/6nu39i/approaches_to_c_dependency_management_or_why_we/dkglgz0/) the following question came up: `how can I use pkg-config with buck?`

a naive solution would be:
```python

cxx_library(
  name='my-test-lib',
  src=['my-test-src.cpp'],
  compiler_flags = ['`pkg-config --cflags --libs lib1 lib2 ... libN`']
)
```

How does buck handle this case?
Does buck hash the flags pre or post-expansion?
Does buck hash the linked system headers and libraries as well?

**Comment by v-jizhang** [comment]
Hi, this issue is closed because it has not been updated for more than 3 years. Thanks
