### ISSUE TITLE
How to build pure C programs?

### ISSUE THREAD

**Issue by weakish** [facebook/buck#1436]
Although in `BUCK`:

- `srcs` only contains `.c` source files, no c++ files.
- `compiler_flags` contains `"-std=c11"`

the output still links against `libstdc++`.

How to write buck rules for pure C programs (without linking libstdc++)?

**Comment by njlr** [comment]
According to [this](https://stackoverflow.com/a/1653057/1256041), `libstdc++` is linked when `g++` is used as the linker. `g++` may well be your default. 

What if you override the linker using a `.buckconfig` ([docs](https://buckbuild.com/concept/buckconfig.html))? 

```bash
[cxx]
  ld = /usr/bin/ld
```


BTW, I have a `BUCK` file for Sodium [here](https://github.com/njlr/libsodium/blob/master/BUCK ).

**Comment by weakish** [comment]
> What if you override the linker using a .buckconfig

@njlr  This does not work. I even removed `g++` and `libstdc++-dev`, which also does not work.

**Comment by njlr** [comment]
How are you testing that the C++ standard library is being linked?

**Comment by weakish** [comment]
ldd

**Comment by njlr** [comment]
I think that setting the linker to `gcc` in `.buckconfig` [does the trick](https://stackoverflow.com/a/45358452/1256041). 

Here is my `ldd` output: 

```
$ ldd ./buck-out/gen/xkcd936
	linux-vdso.so.1 =>  (0x00007fff4afba000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f2239b6d000)
	/lib64/ld-linux-x86-64.so.2 (0x0000559044bf0000)
```

I believe these are just C libraries? 

All of the code is in [my fork](https://github.com/njlr/xkcd936/tree/bugfix/buck-no-stdc%2B%2B).

**Comment by weakish** [comment]
@njlr Thanks a lot! `ld = /usr/bin/gcc` does do the trick.
