### ISSUE TITLE
.fakebuckversion no longer works

### ISSUE THREAD

**Issue by zhan-xiong** [facebook/buck#1438]
After [this](https://github.com/facebook/buck/commit/afe490a8c37f0d045a0e93c3aac1a04008da516f), buck no longer uses the .fakebuckversion file.

**Comment by dinhviethoa** [comment]
We could kill .fakebuckversion altogether.
You can achieve the same effect using the environment variable BUCK_FAKE_VERSION.

What do you think?

**Comment by zhan-xiong** [comment]
Actually after thinking about it, killing it is probably fine, though it does make my life marginally easier (I have a few versions of buck that I need to test in parallel, having different .fakebuckversion files in each one makes it slightly easier for me)
