### ISSUE TITLE
xcode_post_build_script() needs documentation on buckbuild.com

### ISSUE THREAD

**Issue by jonathandann** [facebook/buck#1440]
https://github.com/facebook/buck/blob/master/src/com/facebook/buck/apple/XcodePostbuildScriptDescription.java allows you to run what Xcode calls a "run script build phase", but it's not documented on buckbuild.com, so it's not easy to work out how to do this without knowing what you're grepping for in the buck codebase.

This is necessary for migrating a fair few Xcode projects to being generated with Buck.

**Comment by ttsugriy** [comment]
I assume that it's not documented [because of](https://github.com/facebook/buck/blob/master/src/com/facebook/buck/apple/XcodePostbuildScriptDescription.java#L41-L42):
```
 * <p>This rule is a hack and in the long-term should be replaced with a rule which operates
 * similarly to apk_genrule, or should be removed entirely if possible. Those rules do nothing when
 * building with Buck.
```

**Comment by jonathandann** [comment]
@ttsugriy Without this as a first class citizen, what's the recommended way to migrate projects that use scripts?

**Comment by ttsugriy** [comment]
No idea, @jonathandann :) But all instances I've seen so far could be implemented using genrules.

**Comment by ollieatkinson** [comment]
@ttsugriy would a genrule be used for static analysis, e.g. something like `swiftlint`?

**Comment by ttsugriy** [comment]
Yes, @ollieatkinson, genrules are often used for running custom post-processors.

**Comment by ttsugriy** [comment]
@ollieatkinson, absolutely everything that has at least some value has an output :) Even if it's something written to stderr or an exit code. It's always better to structure everything as a pipeline - inputs -> computation -> outputs (report) -> optional analysis (visualization). This approach makes it possible to reuse intermediate computations and can be integrated with any external tools. For example if your genrule generates a report and not simply returns an exit code, you can integrate it with your linting infra - you can run `buck build //lint/package:report --show-output`, read the output and visualize linter warnings from the report. In build system, you can also create a second genrule that takes a first one (the one that produces the report) as an input and returns a non-zero exit code if report contains any errors.

**Comment by ollieatkinson** [comment]
Makes perfect sense, but I still need to use `xcode_post_build_script` at the moment to have it generate as a post build script in Xcode

```python
  genrule(
    name = 'swiftlint',
    bash = '\$(git rev-parse --show-toplevel)/Scripts/swiftlint.sh',
    out = 'swiftlint-results.txt'
  )
  
  xcode_postbuild_script(
    name = 'swiftlint-xcode',
    cmd = '$(git rev-parse --show-toplevel)/Scripts/swiftlint.sh',
  )
```

**Comment by ttsugriy** [comment]
well, whatever `xcode_postbuild_script` generates, I would just do in a `genrule` instead. Also, you should never access any source files not added as dependencies to your `genrule`. in your case it means that instead of `\$(git rev-parse --show-toplevel)/Scripts/swiftlint.sh` you should be using something like `$(exe //Scripts:swiftlint.sh)` after creating an `export_file` that exports `swiftlint.sh`, since your current setup is technically broken - Buck will eventually add sandboxing support and only dependencies will be available to rules during build.
