### ISSUE TITLE
git clone error

### ISSUE THREAD

**Issue by ashu-22** [facebook/buck#1452]
cd buck
error: RPC failed; curl 56 OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 10054
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

**Comment by styurin** [comment]
Please, provide more details.

**Comment by ashu-22** [comment]
Sir these are the errors I have got yesterday When I was trying to run that command there.
It is quite amazed me that I have not looked anything outside this error's.

**Comment by styurin** [comment]
So you got this error when you run `cd buck`? Did you run `git clone` before that? How did you create that folder?

**Comment by ashu-22** [comment]
Yeah, I already did that thing previously. I never create that folder
