### ISSUE TITLE
Add support for the D8 Dex Compiler

### ISSUE THREAD

**Issue by kageiit** [facebook/buck#1459]
https://android-developers.googleblog.com/2017/08/next-generation-dex-compiler-now-in.html

biggest wins are
- Faster dexing
- Automatic desugaring of java 8 bytecode
- Outputs smaller dex files

**Comment by sdwilsh** [comment]
I'm just going to assume @dreiss or @bertmaher should be the ones to look at this.

**Comment by kageiit** [comment]
Im going to take a look at adding D8 support into buck this weekend and report back.

**Comment by cwoodwar6** [comment]
Looks like this is now done?

**Comment by kageiit** [comment]
Yep
