### ISSUE TITLE
Add support to merge service Descriptor files in java_binary rules

### ISSUE THREAD

**Issue by kageiit** [facebook/buck#1460]
Buck currently provides an option to merge manifests when building java_binary rules, but I am not seeing an option to merge service manifest files as described in http://imperceptiblethoughts.com/shadow/#controlling_jar_content_merging

```
Java libraries often contain service descriptors files in the META-INF/services directory of the JAR. A service descriptor typically contains a line delimited list of classes that are supported for a particular service. At runtime, this file is read and used to configure library or application behavior.

Multiple dependencies may use the same service descriptor file name. In this case, it is generally desired to merge the content of each instance of the file into a single output file.
```

**Comment by kageiit** [comment]
cc @jkeljo @styurin

**Comment by jkeljo** [comment]
This should be really straightforward to do in `JarBuilder`

**Comment by jkeljo** [comment]
Although deciding on the proper ordering will be interesting.

**Comment by kageiit** [comment]
Can we not do the same thing as we do with merging duplicates in the transitive classpath i.e post order traversal?

**Comment by kageiit** [comment]
I am not sure the order matters or not however

**Comment by jkeljo** [comment]
[The docs](https://docs.oracle.com/javase/8/docs/api/java/util/ServiceLoader.html#load(java.lang.Class)) imply, but don't outright state, that the iteration order is the order in which the names appear. The OpenJDK source looks like it's indeed doing it in order. And yeah, following existing precedent makes sense.
