### ISSUE TITLE
'Too many field references' error when using Buck with trim_resource_ids=false

### ISSUE THREAD

**Issue by alonlevih** [facebook/buck#1463]
BUILD FAILED: //main:bin_developDebug#dex_uber_r_dot_java failed with exit code 2:
trouble writing output: Too many field references: 67758; max is 65536.
......

This error shows up in large apps that depend on many modules. The field references of used resources coming from these modules will be counted against each module.
This means that any field in R.txt in any submodule gets treated as if it was declared in the package that is in the module’s manifest. Therefore, the amount of resource fields are multiplied with each submodule reference.
This leads to a situation where all the R.java files cannot fit in a single artifact because the number of field references exceeds 65535.

Notes:
- I cannot use trim_resource_ids = True in the binary rule, because the project uses reflection to bind the fields to the layout classes (like Butterknife)
- Gradle build for the same project succeeded

For now, I implemented a new BUCK parameter named keep_resource_class_pattern (available here: https://github.com/alonlevih/buck) that will allow specifying the resource classes to keep (i.e. '.*id.*'). But I was wondering if there’s a more elegant solution for that (without trimming resources) 

I already delved into https://github.com/facebook/buck/issues/828
https://github.com/facebook/buck/issues/926 but they do not offer any solution for this.

Any help will be appreciated.

**Comment by kageiit** [comment]
@alonlevih There already exists a `keep_resource_pattern` option in android binary for this.

I would recommend looking at the source code `AndroidBinaryDescription` directly next time since all options are not documented. In fact, we use the same approach to keep resources we load using reflection to get around this issue and enable resource trimming.

**Comment by alonlevih** [comment]
@kageiit keep_resource_pattern allows specifying a regular expression for matching the resource name; The thing is I need to apply a regular expression for the resource class (id/string/color/etc). The resource name regular expression does not help much with my issue since there is no template I use for naming resources.
Of course I've taken a look at AndroidBinaryDescription before suggesting this change, I had to do so in order to understand how TrimUberRDotJava works.
