### ISSUE TITLE
debian packaging

### ISSUE THREAD

**Issue by nikhedonia** [facebook/buck#1465]
Would be nice if you would provide a selfcontained debian package for buck.

Many users of Buckaroo complain that its difficult to install Buck on debian jessie as it requires to install openjdk-8-jre which is not included in the default repository.

**Comment by ttsugriy** [comment]
@nikhedonia, I just realized that your PR also packages buckd pex which in effect increases deb package size by 2x. Is this intentional? Do your users use buckd directly?

**Comment by nikhedonia** [comment]
@ttsugriy no I don't know if anyone does. I just wanted to make sure that everything is included.
How usable is buck without buckd ?
It is definetly possible to split the debian package into two...

**Comment by ttsugriy** [comment]
I see, @nikhedonia. Oh well, let's give an existing [release](https://github.com/facebook/buck/releases/tag/v2017.09.04.02) a try and see how it goes :) You can now download deb files from there.
