### ISSUE TITLE
Hook for automatically generated .buckconfig? 

### ISSUE THREAD

**Issue by njlr** [facebook/buck#1470]
In [Buckaroo](https://github.com/LoopPerfect/buckaroo) we are overwritting `.buckconfig.local` with automatically generated values for `[repositories]`. This is less than ideal, because if the user has important configuration there it is lost. 

It would be possible for us to parse and merge the existing `.buckconfig.local` ([discussion](https://github.com/LoopPerfect/buckaroo/issues/130)), but this would be a brittle solution.

Instead, perhaps Buck could provide a hook for this? For example, we could introduce a new `.buckconfig` designed for generated values. For example (in order or precedence): 

 * `.buckconfig`
 * `.buckconfig.generated`
 * `.buckconfig.local`

Would this fit with the overall design direction of Buck?

**Comment by njlr** [comment]
cc @nikhedonia

**Comment by njlr** [comment]
I have created a patch for this (https://github.com/njlr/buck/tree/feature/buckconfig.auto). Happy to send a PR.

**Comment by LegNeato** [comment]
I too would be interested in such a feature

**Comment by LegNeato** [comment]
Though multiple tools may collide...perhaps just look for a .buckconfig.(*).generated regex

**Comment by njlr** [comment]
Interesting idea - we would need a well defined stacking order if multiple configs are possible.

**Comment by ttsugriy** [comment]
Would it be possible for you to use command line arguments for this?

You can create a file args/buckaroo with following content:
```
--config
repositories.<veriable_to_override>=<override_value>
...
```
and can use it when calling buck as follows:
```
buck build @args/buckaroo ...
```

This way it's also easy to use your overrides in any project without having to modify `.buckconfig`.

**Comment by njlr** [comment]
That sounds feasible but I think that it would prove inconvenient for users, since they would always want to pass in the values or the build will fail.

**Comment by ttsugriy** [comment]
well, you can create a buck wrapper script when initializing buckaroo repo, which would call buck and pass appropriate overrides. In fact, it will also give you the maximum flexibility for providing the best experience for buckaroo clients. No matter how many `.buckconfig.*` options we support, there will always be a potential for tools/clients to override or corrupt an existing config.

**Comment by nikhedonia** [comment]
> well, you can create a buck wrapper script when initializing buckaroo repo, which would call buck and pass appropriate overrides

Unfortunately then we would need to call the script using a relative path...
One nice feature of Buck is that you can invoke any buck command from any sub directory and it just works.

**Comment by njlr** [comment]
Would someone from the Buck team be able to provide guidance on this?

**Comment by ttsugriy** [comment]
@nikhedonia, I understand that it's more convenient to be able to use a default buck installation, but Gradle, for example, [wrapper scripts](https://docs.gradle.org/current/userguide/gradle_wrapper.html) and developers seem to be ok with that approach. You can generate similar scripts when initializing buckaroo. This way you could also provide a way to download/install a version of buck that is guaranteed to work for your clients.

Also, would [.buckconfig.d](https://buckbuild.com/concept/buckconfig.html) work for you?

**Comment by njlr** [comment]
@ttsugriy I had a closer look at the `--config` command line option and I don't think it will fit our use-case, since we have different generated `.buckconfig.local` files for each cell. 

So, the top level `.buckconfig.local` might look like this: 

```
[repositories]
  datasift.served = buckaroo/official/datasift/served
  boost.date-time = buckaroo/official/boost/date-time
  boost.config = buckaroo/official/boost/config
```

And `buckaroo/official/datasift/served/.buckconfig.local` might look like this: 

```
[repositories]
  boost.assert = ../assert
  boost.config = ../config
  boost.static-assert = ../static-assert
  boost.throw-exception = ../throw-exception
  boost.utility = ../utility
  boost.functional = ../functional
```

I don't think the `--config` option allows specific overrides for different cells?

**Comment by ttsugriy** [comment]
@njlr, cell specific overrides should be available via `-c cell//foo.bar=baz` syntax. Please let me know if it works for you.

**Comment by ttsugriy** [comment]
FYI: `-c *//foo.bar=baz` should override config setting for all cells.

**Comment by nikhedonia** [comment]
@ttsugriy 
Finally I got around to try your suggestion with `--config`.
Although it is a bit cumbersome, it works.

Things that I noticed:
- it is required `--config` needs to be followed by a new line otherwise it fails parsing.
- it is required to repeat `--config` after every override.

could we make the parser less strict and remove the need of repeating `--config` ?

**Comment by njlr** [comment]
This feature is really powerful, but I think the syntax makes it a bit painful for setting properties used in every build. `buck build :app` is much nicer than `buck build @configs/release :app`, for example. Of course, this could be hidden inside a script (e.g. `buckaroo.sh` containing `buck build @configs/buckaroo :app`), but I think this harms usability because: 

 1. You can no longer easily call Buck from subfolders in the project
 2. You are no longer directly interfacing with Buck, so we have to explain the extra level of indirection to new-comers. This is barrier to entry. 
 3. We would need a build script for each target, which adds friction... or create a more generic script, which is more confusing! 
 4. A script would (probably) be platform-specific. 

For these reasons, I think that `buckconfig.auto` (or similar) is a good solution. What are the thoughts on this from the Buck side?

**Comment by ttsugriy** [comment]
@nikhedonia, flag files are used not just for `--config` so we cannot make any assumptions and skip any requirements, but we can consider adding a separate `--config-file` flag which would allow clients to pass configuration options in some simpler format, although personally I like explicitness, since every time we try to introduce some syntactic sugar like this, we get questions from engineers about how this "magic" works.

@njlr, internally we use configuration files and our engineers are used to calling buck with `@config/some_config` which, btw we're going to replace with `-f config/some_config` very soon, so that there is no confusion about what exactly `config/some_config` is - namely a command line file.

**Comment by njlr** [comment]
It seems that this is no longer possible. 

With this config:

```
--config
repositories.abc=./deps/abc
```

I get the following error: 

> BUILD FAILED: Overriding repository locations from the command line is not supported. Please place a .buckconfig.local in the appropriate location and use that instead.

**Comment by njlr** [comment]
There is now the `.buckconfig.d` folder.

**Comment by styurin** [comment]
`.buckconfig` supports including other files, see "Configuration files can include other files" here: https://buckbuild.com/files-and-dirs/buckconfig.html.

You can create `.buckconfig.generated` file and include it from `.buckconfig`:

```
<?file:.buckconfig.generated>
```

The question mark instructs buck not to fail when that file doesn't exist.
