### ISSUE TITLE
[swift] Proposal: remove delegation from AppleLibraryDescription when the apple_library contains swift

### ISSUE THREAD

**Issue by robbertvanginkel** [facebook/buck#1472]
I've worked on a buck for where we've had swift working for a while. It works for us specifically but contains some hacky workarounds which made us not pursue the opensourcing of that. Instead, we've revisited the approach and I think we need a slight architectural direction change to make this work.

What we currently have is `AppleLibraryDescription`, which will handle all apple related flavors of that buildtarget. If there are no apple specific flavors anymore, the AppleLibraryDescritpion will instantiate a `CxxLibraryDescription` and ask it for buildrules for non-apple specific flavors. `apple_library` essentially wraps `cxx_library` so it can handle apple specific bundle or dsym behaviour, but the creation of rules for object files, archives and links are all in the `Cxx*` code.

The first step to adding swift to buck was with `swift_libray`, a rule for non-mixed swift only targets. It didn't have support for the apple things such as dsyms, and was directly responsible for creating its own object files (with swiftc) and creating archive and link rules for it (note that this isn't implemented). In terms of architecture, the responsibilities of `SwiftLibraryDescription` are very close to those of CxxLibrary description.

With the goal to support mixed swift/objc libraries in `apple_library`, the initial idea was to have two delegates and have `AppleLibraryDescription` wrap both. I don't think this is a good approach for a number of reasons:

- This delegation means instantiating a `{Swift/Cxx}Librarydescription`, and then requiring a specific flavored buildrule from it. This approach lets you require any buildrule that is accessible through passing a combination of flavors into the `getBuildRule` method. These flavors correspond to `UserFlavors` (such as `#static`/`#shared`), but this does not allow you to get to the `InternalFlavors` (as required for building blocks like individual objectfiles). This is tricky because the outputs of the public flavors for these delegates are too far along the build process (for example, when building a single dynamic library you'd want to combine object files from both rules but you can't combine dylibs from the delegated descriptions). The way this is currently avoided is through having a   flavor of the swiftdelegate to be a dependency of the shared flavor of the cxxdelegate.

- The current codebase makes the `CxxLibraryDescription` the 'parent' delegate that has a dependency on the `SwiftLibraryDescription` delegate with a `#swift-companion` flavor. This approach has some issues:

    - The `CxxLibraryDescription` won't make a link rule if it has no object files. Wether it has object files is currently determined by the presence of cxx sourcefiles. Meaning that an `apple_library` containing only swift files will not produce link rules with this approach. Either you need a dummy cxx object or you need to make the delegate `CxxLibraryDescription` aware of it having a swift-companion dependency.

    - To have mixed targets supporting the `-import-underlying-module` flag, the swift compilation needs access to a modulemap describing the obj-c half of the module. This approach would require us to have the swift delegate depend on some flavor of the cxx delegate, but that flavor doesn't really make sense on its own for the cxx delegate. An #objc-module-headers flavor shouldn't belong to `CxxLibraryDescription`, but instead to `AppleLibraryDescription`.

    - Similarly the swift-companion flavor in itself doesn't have a well explainable output on the `SwiftLibraryDescription`. It serves as a sort of proxy to get to the object file rule from the `SwiftLibraryDescription`, but it is unclear to me why you couldn't directly depend on flavor that provides the object files.

    - To properly setup the dependencies between flavors in the swift and cxx code, both code paths need to be able to access those flavors. This means to avoid a cyclic dependency (where the swift and cxx packages in buck depend on each other) you end up putting swift specific details (like flavors and bridging headers) in the cxx package.

    - This responding/propagating of flavors across 3 description classes is very easy to get wrong, and leads to issues like https://github.com/facebook/buck/issues/989

In my opinion, this would all be better if we did away with the delegation and directly required the rules from the corresponding package. This would mean:
- `SwiftLibraryDescription` gets a static method similar to `CxxLibraryDescription`'s `requireObjects()`, that returns a buildrule for the objectfiles.
    - `SwiftLibraryDescription` will handle all public flavors (like `static`, `shared`, `headers`) itself by creating `Archive`, `CxxLink` rules etc.
- `AppleLibraryDescription` removes the delegation to `{Swift/Cxx}`LibraryDescription`.
    - `AppleLibraryDescription` will handle all public flavors (like `static`, `shared`, `headers`) itself by creating `Archive`, `CxxLink` rules etc.
    - For this it will require the correct rules for objectfiles from static methods on `{Swift,Cxx}`LibraryDescription`.

What I am proposing is to cut the instantiation of the `*Description` class middleman and let `AppleLibraryDescription` directly be responsible for creating its buildruiles. This simplifies the code conceptually and makes `{Cxx,Apple,Swift}`LibraryDescription` all follow the same pattern. To validate this idea, I have a branch on a fork at https://github.com/robbertvanginkel/buck/commits/swift_rewrite. This fork breaks some small things, but is capable of the larger swift support requirements that don't work on current master:
- building mixed swift/objc libraries (currently with `-import-underlying-module`, not with bridging headers)
- having modular interfaces to support dependencies between `apple_library` and `swift_library`, regardless of the `apple_library` being mixed or single language. (supporting `@import` in objc, and `import` in swift)

There are a few open questions to consider before going this way:
- How to make this backwards compatible? 
    - Should `AppleLibraryDescription` keep the current architecture/code path if there is no mixed swift?
    - Relevant on how to interpret flavors like #infer and #compilation-database on apple_libraries with mixed source
- Can we break the current swift in `apple_library` for a few weeks on master?

**Comment by milend** [comment]
Thanks for the write-up @robbertvanginkel. As we previously spoke about the correct approach to support Swift, I agree with everything that you've outlined above.

@robbertvanginkel:
> To have mixed targets supporting the `-import-underlying-module` flag, the swift compilation needs access to a modulemap describing the obj-c half of the module.

This also arises if we want to build Swift static libs without using modular imports (so Obj-C would be exposed only through a bridging header). As you say, this would necessitate a flavour on `CxxLibraryDescription` that just exposes existing file headers but this doesn't make much sense in the context of a `CxxLibraryDescription` which should not have the notion of `#headers` being composed of `#file-headers` + another flavour that dynamically generates headers (e.g., `Swift#compile`).

@robbertvanginkel:
> - building mixed swift/objc libraries (currently with -import-underlying-module, not with bridging headers)

Supporting builds without exposing `apple_library` as modular is something that want to officially support. I don't think there's much work that needs to happen here, though, so should be fairly trivial.

@robbertvanginkel:
> Should AppleLibraryDescription keep the current architecture/code path if there is no mixed swift?

Certainly seems wise to do so in the short term with the longer term goal of eliminating the delegation completely.

@robbertvanginkel:
> Relevant on how to interpret flavors like #infer and #compilation-database on apple_libraries with mixed source

I think we have to figure that one out.

@robbertvanginkel:
> Can we break the current swift in apple_library for a few weeks on master?

Swift in `apple_library` is currently broken in some subtle ways. For example, it doesn't correctly pass header maps and doesn't support inclusion of a library's own headers through framework-style imports in the bridging header. This makes it effectively broken for such setups.

So I don't know if usage of Swift in `apple_library` ever worked correctly (or was supposed to). It's certainly not used in such a way inside Facebook. 

I only just recently added project generation support for Swift in `apple_library` when used with Xcode 9b4+, so I'm fairly sure we can proceed and assume usage of Swift in `apple_library` has not been supported officially in any capacity.

**Comment by milend** [comment]
A few more thoughts on the subject:
- We need to support a non-modular setup for mixed libraries using bridging headers. That's because existing code might be exhibiting [anti-patterns](http://clang.llvm.org/docs/Modules.html#id36) that break modules. I have set up an example setup this [here](https://github.com/milend/swift-static-libs).
- `SwiftCompile` rule currently suffers from multiple issues:
    - It does not produce docs (i.e., `Module.swiftdoc`). I'll be addressing this soon.
    - It compiles Swift source code at all once rather than invoking the compiler per source file.
    - The bridging header parameter is passed relatively which means that the generated Obj-C Header might contain a reference to it using that path. Consequently this can break builds when the Obj-C Header is imported by other libraries if the paths are not setup correctly. We have to be careful here to make sure the import path is cacheable and not absolute.
- In order to avoid disruptions to existing users of `apple_library` with Swift, we could control the new behaviour using a config option in the interim.

**Comment by robbertvanginkel** [comment]
There are definitely some things that need to happen after this, I suggest we keep a list in a separate task for things like the swiftdoc, choice for invoking per module / per file, etc.

> In order to avoid disruptions to existing users of apple_library with Swift, we could control the new behaviour using a config option in the interim.

I think since it is undocumented, there are no guarrantees. To not disturb current users we have to keep current code paths, which is exactly what I don't want with this refactor.

I think the best way to go will be to remove the swift delegation, and keep the cxx delegation for now. We then branch based on having mixed swift/obcj sources (and possibly a flag like `apple.new_library_flow` so people can easily switch over to the new path for objc only for testing).

**Comment by milend** [comment]
Closing issue as we've implemented Swift support without the need for the refactor (as discussed offline with @robbertvanginkel).
