### ISSUE TITLE
Changing Android compile SDK is not invalidating cache artifacts

### ISSUE THREAD

**Issue by cwoodwar6** [facebook/buck#1484]
In `.buckconfig` under `[android]` we define `target = android-25`. This is the version of Android which our entire project is compiled against. If we compile the app, then change that to `target = android-26` without any additional changes, nothing is being rebuilt. Changing the compile version should invalidate artifacts and recompile them because it may expose new compiler errors and warnings.

**Comment by cjhopman** [comment]
Yeah, this should definitely be fixed. It's always behaved this way right? It's not a regression?

**Comment by cwoodwar6** [comment]
@cjhopman as far as I can tell it has always been that way, but I haven't tested older versions.

**Comment by v-jizhang** [comment]
Tested and it was fixed.
