### ISSUE TITLE
Request for dynamic Android compile SDK based on target

### ISSUE THREAD

**Issue by cwoodwar6** [facebook/buck#1485]
In `.buckconfig` under `[android]` the target says “This specifies the version of the Android SDK that all Android code in the project should be built against.“. Normally that was fine for us, but now we have 2 apps in the same repo that are compiling against separate SDK versions. Is there any way we can make this dynamic based on what target you are building? Perhaps a way to have a `.buckconfig` per project?

**Comment by cjhopman** [comment]
What we've tended to do for this is to create a directory "mode/" that contains files of command line args that configure buck in different ways.

For example, have a file at mode/android-26 that just contains
```
--config
android.target=android-26
```
and then invoke buck like `buck build @mode/android-26 //my/fancy:apk`.

The biggest reason that we are hesitant to add the ability to configure this at the apk level is that it affects the entire build graph underneath that apk and it makes it easy to accidentally greatly increase build costs.

**Comment by cwoodwar6** [comment]
@cjhopman From what I can tell, this solution would have the same impact on build costs, correct? Because essentially you have to recompile all of the build graph underneath with the new target?

This solution is nice because it at least gives me the ability to configure it on the fly but I'd like to hide this detail from users. Is there some way I can bake this into the target so that users aren't required to pass this additional configuration each time they compile a specific target?

**Comment by kageiit** [comment]
@cwoodwar6 you have access to `buckw` so you can intercept the args and add in extra ones like the config file transparently under the hood.

This is what we do for folks invoking `./buckw project`. We intercept the args and ensure they are not projecting on the entire workspace and we also add some extra flags to speed it up for example

**Comment by cwoodwar6** [comment]
@kageiit So that is currently how I am getting around the issue. But this is only when they invoke the target directly and I know that target should be using a different SDK version.

On CI we run `./buckw test --include unit` which crosses the target boundaries and needs to compile different SDK versions depending on the current target it runs. This is the particular case I am most interested in solving and didn't see an easy way to modify the buck wrapper to help solve that. Any ideas?

**Comment by kageiit** [comment]
buck allows you to set arbitrary labels on any build rules

You can use custom `DEFS` to add a `android-26` label onto the targets that require the new sdk, then use buck query to filter out those targets

Then on ci, you can run two `test` commands with different arguments. One for 26 and one for the rest

**Comment by cwoodwar6** [comment]
Yeah that was going to be my other work around :)
