### ISSUE TITLE
Code signing when running on the device

### ISSUE THREAD

**Issue by isundaylee** [facebook/buck#1489]
I encountered an error as raised in facebook/FBSimulatorControl#438 when I tried to run the app on the real device with `buck install -d -r "//ios:Stun#iphoneos-arm64"`. After some digging it seems the issue is related to an incorrectly signed `.app` file. When I manually sign the `.app` again with 

```
/usr/bin/codesign -f -s "iPhone Developer: Jiahao Li" --entitlements entitlements.plist buck-out/.../Stun.app
```

the `.app` can be successfully installed onto the device.

Are there any options I need to provide explicitly to make buck sign the `.app` when running on the real device? Thanks! :)

**Comment by v-jizhang** [comment]
Hi, this issue is closed because it has bot been updated for more than 3 years. Thanks
