### ISSUE TITLE
Can somebody make a release?

### ISSUE THREAD

**Issue by brettwooldridge** [facebook/buck#1494]
Last release is at the end of May.  Would be nice to have an official release with all of the Kotlin goodness...

**Comment by nikhedonia** [comment]
...and upload a debian package as well.

**Comment by ttsugriy** [comment]
There are a few more changes in flight that we'd like to have in our next release, but we'll create a new release next Monday or Tuesday. Thank you for your patience!

**Comment by ttsugriy** [comment]
resolved with https://github.com/facebook/buck/releases/tag/v2017.09.04.02. Happy bucking! :)

**Comment by nikhedonia** [comment]
can you also build & upload the debian package?

**Comment by ttsugriy** [comment]
@nikhedonia, that's an excellent question! I'll try to use our recently contributed deb packager genrule to create a debian package soon.

**Comment by ttsugriy** [comment]
Debian package is now also available at https://github.com/facebook/buck/releases/tag/v2017.09.04.02

**Comment by nikhedonia** [comment]
awesome, thanks for your efforts
