### ISSUE TITLE
Prebuilt Choco package? 

### ISSUE THREAD

**Issue by njlr** [facebook/buck#1495]
It would be convenient for Windows deployments if a Choco package were made available. 

I have created one [here](https://github.com/njlr/choco-buck), which could be the basis for an official package. However, my implementation is slow because it downloads and builds Buck on the deployment machine. This takes a few minutes on Appveyor. 

 * Are there plans to provide a Choco package for Buck?
 * Are there plans to provide a pre-built Jar (or Pex?) to speed-up deployment?

**Comment by ttsugriy** [comment]
Thank you for bringing this up, @njlr! We do have prebuilt binary for macOS on our [release page](https://github.com/facebook/buck/releases), so it seems fair to provide binaries for Windows as well. @ilya-klyuchnikov, do you happen to know if there are any plans to do so?

**Comment by sdwilsh** [comment]
Last time I tried this, building the PEX on one platform worked on all 
platforms.  I'm not sure if Buck has shifted to a model where there is 
native code, but if not, this might be easy to produce a PEX and upload 
that in addition to the steps we do for macOS.

**Comment by njlr** [comment]
Looks like there is now an [official package](https://chocolatey.org/packages/buck)! :heart:
