### ISSUE TITLE
DsymStep is not reexecuted if object files change

### ISSUE THREAD

**Issue by anoever** [facebook/buck#1508]
DsymStep declares only a dependency on the generated executable, not on the object files from which the executable was build. The comment in `DsymStep.java` nicely explains why this is wrong:

> The linking step for apple executables does not actually embed debug information from the object files that are being linked. Instead, the executable contains paths to object files from which the debug information can be read. {@code dsymutil} reads this section of the executable and collects the debugging information from all the mentioned object files and generates a {@code .dSYM} bundle alongside the executable. This bundle is then loaded automatically by the debugger for its debug information.

Any source modification that changes the object files, but not the executable does not trigger a rebuild of the `ios:BuckDemoAppBinary#apple-dsym,iphoneos-arm64` target. For example if I add a new line in a source file that changes the object file (because it contains debug info) but not the executable (because the code doesn't change).

**Comment by yiding** [comment]
This could very well be the case. It looks like the code sets the deps correctly (which ensures the `.a` are built) but does not set the rule key correctly (which ensures that changes to the .a will change the cache key).

**Comment by v-jizhang** [comment]
Hi, this issue is closed because it has not been updated for more than 3 years. Thanks
