### ISSUE TITLE
Instrumentation target is failing to find APK

### ISSUE THREAD

**Issue by cwoodwar6** [facebook/buck#1510]
Error:
```
BUILD FAILED: Failed to install apk on 192.168.56.101:5555 (Google Nexus 5 - 6.0.0 - API 23 - 1080x1920).
com.android.ddmlib.InstallException: Local path doesn't exist.
    at com.android.ddmlib.Device.installPackage(Device.java:894)
    at com.facebook.buck.android.exopackage.RealAndroidDevice.installApkOnDevice(RealAndroidDevice.java:538)
    at com.facebook.buck.android.exopackage.AndroidDevice.installApkOnDevice(AndroidDevice.java:28)
```
The issue is that the APK being tested is not being generated and thus can't be found.

I've bisected the issue down to this commit: fec4a6293cead2e87553245260c965377487a3de
Before that commit, the issue does not exist.

My instrumentation target:
```
android_instrumentation_apk(
  name = 'instrumentation_debug_apk',
  manifest = ':manifest_debug_test',
  apk = ':bin_debug',
  deps = [
    ':res_debug_test',
    ':src_debug_test',
  ],
  visibility = [
    'PUBLIC',
  ],
)
```

`bin_debug.apk` never gets created. Building it with `buck build app:bin_debug` works fine.

**Comment by cwoodwar6** [comment]
cc @cjhopman - Perhaps you could provide more context? Am I missing something that I need to do with that new change?

**Comment by kageiit** [comment]
We have fec4a62 in our version and do not see this issue. strange

**Comment by cwoodwar6** [comment]
@kageiit The test APK build doesn't fail, it just never builds the main APK. The same exception occurs on: https://travis-ci.org/uber/okbuck/builds/274047893?utm_source=github_status&utm_medium=notification but I'm not sure if it is the same root cause.

**Comment by kageiit** [comment]
we build all apk targets in the travis config before the ui test command is run. It is strange that buck errors out like that.

We do not rely on buck to run ui test commands, but have our own wrapper, that is probably why we did not see this particular error.

**Comment by cwoodwar6** [comment]
This has been blocking us from using the latest buck changes since that commit is now the foundation for later commits and I cannot revert it. We have a custom wrapper that we can use to get around it but would prefer if we could continue to use the test command.

**Comment by cjhopman** [comment]
Should be a straightforward fix, the test apk just needs a runtime dep on the tested apk.

**Comment by kageiit** [comment]
@cjhopman Does https://github.com/facebook/buck/commit/a2620209dc574a2833dce64cf163da3dd9c656d8 fix this?

**Comment by cjhopman** [comment]
@kageiit it should.

**Comment by cwoodwar6** [comment]
Confirmed cfdefd2 fixes this issue.
