### ISSUE TITLE
Profiled builds of static_pic/shared Haskell libraries

### ISSUE THREAD

**Issue by dajmaki** [facebook/buck#1512]
https://github.com/facebook/buck/blob/4e1230300da735942d3251cd391ceb7099611ee1/src/com/facebook/buck/haskell/HaskellCompileRule.java#L146

What would be missing in order to make this work?

**Comment by watashi** [comment]
This should be supported now.
But it requires ghc-8.6 or newer, which supports the `-fexternal-dynamic-refs` flag.
You may actually need ghc-8.8 or newer as a bunch of issues related to profiling pic is only fixed there.

**Comment by v-jizhang** [comment]
@watashi Thank you.
