### ISSUE TITLE
Java BUCK file has laughable deps for "autodeps"

### ISSUE THREAD

**Issue by shs96c** [facebook/buck#1513]
Ahahahahahahaha! It doesn't need all that!

https://github.com/facebook/buck/blob/master/src/com/facebook/buck/jvm/java/BUCK#L591

**Comment by shs96c** [comment]
Also, that target name looks wonky.

**Comment by ttsugriy** [comment]
@shs96c, you're absolutely right! Unfortunately currently there is no tool that automatically detects and removes unused dependencies, this is not entirely uncommon :( Will you send a PR? If not, I already have the changes ready for review.

**Comment by ttsugriy** [comment]
fixed by https://github.com/facebook/buck/commit/5ac825e0767211778ca0f7d25945297cc1bb91b9
