### ISSUE TITLE
Docs: `flavors` are never explained or listed

### ISSUE THREAD

**Issue by LegNeato** [facebook/buck#1526]
Nowhere in the docs are `flavors` explained or listed. Sometimes there is a vague reference to them or noting a particular flavor can be used for a particular goal...but there is never an explanation or a list of them.

This seems like a large omission.

**Comment by shybovycha** [comment]
It is not possible to build OSX bundle without providing a flavor. But it is neither described (what are flavors? where and how to provide them? how to use them?) nor clear what flavors are available.

**Comment by 0x5e** [comment]
Same issue.
