### ISSUE TITLE
Run "google-java-format" automatically as a pre-commit hook

### ISSUE THREAD

**Issue by shs96c** [facebook/buck#1530]
It's a barrier to community contribution to have an otherwise acceptable PR be rejected because of code formatting issues that could be completely automated.

I'd suggest checking in a git precommit hook so that no-one has to think about this stuff any more. An alternative is to modify FB's internal import mechanism to run this change itself, but that makes it harder to give non-FB staff the commit bit.

**Comment by styurin** [comment]
> I'd suggest checking in a git precommit hook so that no-one has to think about this stuff any more. 

Pre commit hooks cannot be checked-in, they need to be configured by users manually.

> An alternative is to modify FB's internal import mechanism to run this change itself, but that makes it harder to give non-FB staff the commit bit.

We'll eventually do that, but for now we ask developers to either manually run google-java-format or manually configure pre commit hook as described in https://github.com/facebook/buck/blob/master/CONTRIBUTING.md#code-style

**Comment by msridhar** [comment]
A hack might be to have `ant` install the pre-commit hook on the first build of the code

**Comment by shs96c** [comment]
Or run the formatting as part of the "default" build target in ant.

**Comment by v-jizhang** [comment]
This issue is closed because there is no update for 3 years.
