### ISSUE TITLE
Feature Request: Ability to use string macros in more rule parameters

### ISSUE THREAD

**Issue by lelandrichardson** [facebook/buck#1536]
We are trying to build an `apple_library` rule that has source files that are provided by a `genrule`. In an ideal world, we'd be able to specify the location of these source files by using the `$(location ...)` string macros, but these appear to not be supported in the `apple_library` rule and others.  There may be a more correct way to do this, but I don't see it. To describe more clearly what we are trying to do, here's an example:

So we have a rule that generates the fully populated node_modules directory of an npm/yarn application:

```python
genrule(
  name = 'node_modules',
  visibility = ['PUBLIC'],
  srcs = [
    '.yarnrc',
    'yarn.lock',
    'package.json',
    'scripts/yarn-1.0.2.js'
  ] + glob([
    'npm-packages-offline-cache/**',
  ]),
  bash = 'cd $SRCDIR && ' \
    'node scripts/yarn-1.0.2.js install --offline && ' \
    'cp -a $SRCDIR/node_modules/ $OUT',
  out = 'node_modules_out',
)
```

Then lets say we have a handful of node modules that have native code in them (say, for react native) that we want to build some `apple_library` rules out of.  In an ideal world, we could do something like this:

```python
  apple_library(
    name = 'some_native_node_module',
    visibility = ['PUBLIC'],
    exported_headers = glob([
      '$(location :node_modules)/some-native-node-module/**/*.h',
    ]),
    srcs = glob([
      '$(location :node_modules)/some-native-node-module/**/*.m',
    ]),
  )
```

Is there any way to achieve this currently that we aren't thinking of? Any help would be appreciated. Thanks!

**Comment by shs96c** [comment]
A long time ago, there had been a plan to allow indexing into the outputs
of build rules using glob patterns:

//some:target["**/*.h"]

That was to address this kind of case.

Downloading modules using yarn midway through the build breaks the
hermeticism and repeatability of the build. Why not just check the modules
in and create a BUCK file in `some-native-node-module`? If you use yarn to
manage all the modules, you could automate updates pretty painlessly.

Simon

On Wed, Sep 20, 2017 at 3:28 AM, Leland Richardson <notifications@github.com

**Comment by LegNeato** [comment]
Not sure how supported/extensible they are, but there are some `js` rules already in Buck:

https://github.com/facebook/buck/tree/b404f1321cb0638f004016d5ff529ff33e1cc802/test/com/facebook/buck/js

**Comment by kageiit** [comment]
Does naming the genrule output to `src.zip` help?

There are examples in python integration tests that use this mechanism for example. I have used this approah for java rules and it seems to work as well.

https://github.com/facebook/buck/blob/8d699a924d67a258b301c5f0d7b4eec3f8c23bbb/test/com/facebook/buck/python/testdata/src_zip/BUCK.fixture

**Comment by seanabraham** [comment]
@shs96c — Indexing would be perfect, yeah. As far as node_modules, we prefer to not check them into the repo if possible to prevent bloat. Maybe we should revisit that decision? However, we considered using yarn's offline mirror mechanism which would have us check in tarballs of all the node dependencies and would then populate node_modules from those tarballs when running `yarn install`. This leads us back to this problem though, as the sources we need only become available somewhere in the output of the rule that runs `yarn install`

@LegNeato — I've looked at those once in the past and they look interesting! However, they don't really address the problem we're having here which is needing to pass along some Objective C source + headers that come packaged with a node_module to an `apple_library` rule.

@kageiit — Cool suggestion! We can give that a try. Based on my cursory glance of the repo it only looks supported for the `srcs` field in a couple build rules like `java_library` and `python_library` but I'll give it a shot anyway.

**Comment by lelandrichardson** [comment]
@shs96c FYI, using yarn should not ruin the hermetic nature of the build, since we are using it with yarn's `--offline` option using an local offline cache of all of the package tarballs. as a result, it should be a pure operation.

Either way, I'm using yarn in this example as it's our actual use case, but I feel like this is easily generalizable into something that takes some set of files (in our case a package.json and a set of tarballs) and produces a set of source files (.m and .h). This could definitely apply to various forms of code generation in the same way. (ie, some transformation of json src => generated .java / .objc files etc)

**Comment by v-jizhang** [comment]
This issue is closed because there is no update for the last 3 years.
