### ISSUE TITLE
Recent buck changes around deps to android library rules broke robolectric tests

### ISSUE THREAD

**Issue by kageiit** [facebook/buck#1537]
The `robolectric_test` 's `#dummy_r_dot_java.jar` is no longer added to the compilation classpath. This causes compilation failures due to missing `R` symbols.

This seems related to the recent refactoring around these rules done by @jkeljo

**Comment by jkeljo** [comment]
Thanks for the report. Looking into it now.

**Comment by jkeljo** [comment]
Fix coming shortly.
