### ISSUE TITLE
New cxx_library 'static_pic_lib' option not properly supported 

### ISSUE THREAD

**Issue by voznesenskym** [facebook/buck#1538]
I am working on upgrading our BUCK to the latest version, and when making a prebuilt_cxx_library, the static_pic_lib command does not work properly.

Example:
`
prebuilt_cxx_library (
    name = 'icu',
    static_pic_lib = 'linux/x86/libicu/libicuuc.a',
    exported_deps = [
        ':icuuc_headers',
    ],
    header_namespace = '',
    visibility = [
        'PUBLIC'
    ],
)
`

**Context**
This lib is included with other libs into a top level static pic library. However, when I attempt to link it into a shared library with -fPIC flags (for JNI), it tells me that the generated library is invalid and that I should recompile with -fPIC.

**Investigation**
This means that the static_pic_lib command does not actually do anything, it just makes a static_lib.

I decided to dig into the BUCK source code to find the issue, and it appears as though everything is wired up under the hood, except the getStaticPicLibrary method in AbstractNewPrebuiltCxxLibraryPaths never gets called. 

This is because of line 740 in CxxDescriptionEnhancer, `args.getLinkStyle().orElse(Linker.LinkableDepType.STATIC),` basically forces any cxx_prebuilt_library to be static. The args.getLinkStyle() it checks (CxxBinaryDescription.CommonArg) always seems to return null and does not even appear to be implemented.  

**Solution?**
Changing line 740 mentioned above to force a Linker.LinkableDepType.STATIC_PIC does work. This means everything is indeed wired up properly under the hood, there just needs to be some resolution at wherever we parse the BUCK files. 

I plan to have a fix up in the next few days, but wanted to open this issue up as soon as I found it.

**Comment by voznesenskym** [comment]
cc @Mmatheson, we found this together.

**Comment by asp2insp** [comment]
Thank you! Please let us know if you need any help with the PR

**Comment by voznesenskym** [comment]
Will do, but should be ok :) Just need to get a little better at figuring out how BUCK parses the files, and then I should be able to hook it all up.

**Comment by voznesenskym** [comment]
@asp2insp 

NVM. The parsing fucked my shit up pretty good.

public static CxxLinkAndCompileRules createBuildRulesForCxxBinaryDescriptionArg

Where do args come from for that? I would like to add a new one. 

I guess i have all the pieces here, the critical piece of logic is:

`Linker.LinkableDepType linkStyle = args.getLinkStyle().orElse(
        args.getStaticPicLib().isPresent()
            ? Linker.LinkableDepType.STATIC_PIC
            : Linker.LinkableDepType.STATIC);`

However, I have no idea how to get the current staticPicLib at that point. I know it is there because at

`public NativeLinkable.Linkage getPreferredLinkage(CxxPlatform cxxPlatform) {`

if I log what I have, I can see the values.

`PrebuiltCxxLibraryDescriptionArg{staticPicLib=/Users/michaelvoznesensky/Uber/mapdisplay/libs/linux/x86/libicu/libicuuc_pic.a, headerOnly=false, exportedHeaders=SourceList{type=UNNAMED, unnamedSources=[]}, exportedPlatformHeaders=com.facebook.buck.rules.coercer.PatternMatchedCollection@1, headerNamespace=, provided=false, linkWhole=false, forceStatic=false, exportedPreprocessorFlags=[], exportedPlatformPreprocessorFlags=com.facebook.buck.rules.coercer.PatternMatchedCollection@1, exportedLangPreprocessorFlags={}, exportedLinkerFlags=[], exportedPlatformLinkerFlags=com.facebook.buck.rules.coercer.PatternMatchedCollection@1, linkWithoutSoname=false, canBeAsset=false, frameworks=[], libraries=[], exportedDeps=[//libs:icuuc_headers], supportsSharedLibraryInterface=false, labels=[], licenses=[], name=icu, deps=[]}`

**Comment by asp2insp** [comment]
Good question! Here's the declaration for [`AbstractCxxBinaryDescriptionArg`](https://github.com/facebook/buck/blob/ac18a41de02f6b7f326eedcd9233d60c87bb5db6/src/com/facebook/buck/cxx/CxxBinaryDescription.java#L397) (which inherits from [`CommonArg`](https://github.com/facebook/buck/blob/ac18a41de02f6b7f326eedcd9233d60c87bb5db6/src/com/facebook/buck/cxx/CxxBinaryDescription.java#L388) The concrete implementation is generated by the [immutables](http://immutables.github.io/) annotation processor, so `getter` methods are synthesized into fields/builders/getter/setter methods.

It sounds like this option should go in [`LinkableCxxConstructorArg`](https://github.com/facebook/buck/blob/ac18a41de02f6b7f326eedcd9233d60c87bb5db6/src/com/facebook/buck/cxx/LinkableCxxConstructorArg.java). Just add a new getter decorated with `@Value.Default`. Once you re-build the new arg will show up. camelCase getters are automatically converted into snake_case python params. Let me know if you need a deeper dive into any piece of the puzzle :)

**Comment by voznesenskym** [comment]
Ahh, thats exactly where I had but I missed the decorator! Thanks, will try.

**Comment by voznesenskym** [comment]
Fixed it. PR after beer.

**Comment by voznesenskym** [comment]
@asp2insp PR is up. It does not appear as though I have permissions to resolve conflicts or push. LMK what next steps are.

**Comment by andrewjcg** [comment]
Sorry, I think I'm missing some additional context here.  From the original issue mentioned above, it sounds like the original `libicuuc.a` library is *not* PIC-enabled, yet you're specifying it via the `static_pic_lib` (this field is only meant for prebuilt static archives which *are* PIC enabled)?

**Comment by voznesenskym** [comment]
The lib mentioned above is indeed PIC enabled. I can make an example
project if you like.

**Comment by andrewjcg** [comment]
Ah yeah, that'd be great thanks.

**Comment by voznesenskym** [comment]
It will be a couple of weeks to make the example project.

**Comment by voznesenskym** [comment]
Im at conferences, hence the delay in making a project. I cannot send you my current project as it belongs to Uber and not myself. Until then, more than happy to explain the bug further. 

libiccuc.a is a full pic-enabled library. All my dependencies are.  The whole output of the BUCK target is a pic-enabled compiled lib inside a cxx binary. Let me know any and all questions you may have about what I am trying to do!

**Comment by v-jizhang** [comment]
No updates for a long time, closing it. Thanks
