### ISSUE TITLE
buckd should restart if java binary changes

### ISSUE THREAD

**Issue by dborowitz** [facebook/buck#154]
/usr/bin/java on my Mac changed to point to a non-JDK JRE. Buck understandably complained:

```
BUILD FAILED: //gitiles-servlet:servlet failed on step javac with an exception:
If using JRE instead of JDK, ToolProvider.getSystemJavaCompiler() may be null.
```

My usual fix is to rewrite the symlink to point to a JDK; I was surprised when this did not fix the problem. Then I remembered to manually kill buckd. (Which was moderately annoying in itself because "killall buckd" didn't work.) It would be nice if the buck launcher could detect if it's running under a different Java than buckd and restart the latter if that's the case.

**Comment by facebook-github-bot-9** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.
