### ISSUE TITLE
google java format pre commit hook is consuming a lot of cpu

### ISSUE THREAD

**Issue by kageiit** [facebook/buck#1544]
A bunch of java vms are running trying to format files and not cleaning up after themselves. This is causing a lot of system performance degradation

<img width="1426" alt="screen shot 2017-09-27 at 4 41 54 pm" src="https://user-images.githubusercontent.com/291148/30936753-cea47baa-a3a2-11e7-9598-5494e9ba5986.png">

**Comment by kageiit** [comment]
cc @styurin

**Comment by kageiit** [comment]
the precommit hook seems to be formatting one file at a time rather than all at once. When working on large changes/big rebases, it seems to take forever to run for each changed java file

**Comment by v-jizhang** [comment]
No updates for almost 3 years, closing it now. Thanks
