### ISSUE TITLE
Buck to use Robolectric build system api

### ISSUE THREAD

**Issue by jongerrish** [facebook/buck#1549]
In Robolectric we'd like to move configuration of resources, assets and manifest to our build system api

https://github.com/robolectric/robolectric.github.io/blob/master/build-system-integration.md

Rather than having per build system strategies live in Robolectric.

Right now AGP3.0 supports this and we're currently adding support into Bazel.

The present implementation of the build system api for Robolectric runs against a single set of merged resources, assets and manifest and we believe this offers better correctness as the same merging strategy that is used for the APK is used for unit tests rather than Robolectric's own merging logic.

I think we had some discussion previously about this and there was concern from the buck side about copying large number of symlinked resource files for unit tests. The same issue exists in Bazel I believe and the present solution is that we are providing the merged resources from bazel in a zip file, but this is just an intermediate step before we switch to processing binary resources....

We are in the middle (actually nearly complete) of support for binary resources and an arsc table in Robolectric. Part of the motivation is that with the switch to aapt2 (and namespaced resources) AGP (from 3.1ish?) will cease to produce a single merged resource directory. Loading binary resources is significantly faster (for framework resources on api 23 we're seeing resource processing times come down from 1-2 seconds to ~10ms) and depending on the the size of the project expect similar gains for application resources.

Is this support something you'd be open to providing, or is there anything we can do to help make that happen?

**Comment by dreiss** [comment]
I think this is doable.

My main concern here is the case where a test depends on a lot of code that depends on a lot of resources, but the test doesn't actually load any resources at runtime (or loads very few).  In that case, we'd spend a lot of time before the test merging all of those resources, only to use (almost) none of them.  Any concerns about that?  (For context, our aapt2 link takes much longer than 1-2 seconds.)

**Comment by jongerrish** [comment]
With the current implementation Robolectric has to load all the value resources in the test runner at startup and process the R class as we need to build a complete resource table, so the more resources you have in your dependencies the more raw XML parsing Robolectric has to do, for example, even if you just want to load a single string, we have no idea what resource file that string lives in so need to real all files.

There is the option of specifying @Config(manifest = Config.NONE) which caused Robolectric not to load any resources, but the problem there is that if any code in your test execution path suddenly changes to load a resource the test will fail, so we don't recommend that (ideally we'd remove it at some point).

Our hope is if we can make Robolectric's resource loading time negligible (i.e: ~10-20ms for app and framework) we would benefit from build caching of merged / binary resources between test run invocations and any performance improvements upstream in the tool chain.

**Comment by dreiss** [comment]
Makes sense, thanks.  We'll probably get to this at some point.  Happy to look at PRs as well.

**Comment by kageiit** [comment]
Robolectric 3.6 is out and according to the plan in http://robolectric.org/blog/2017/11/13/resources-for-real/ , users of buck will not be able to use robolectric 3.8 and higher without these changes.

**Comment by jongerrish** [comment]
Hi, just an update on this. The final API for build systems to integrate with Robolectric is documented here:-

http://robolectric.org/build-system-integration/

This API supports both merged raw resources, assets + manifest and also will soon support consuming a binary resources.ap_ file.

This is now supported in Bazel via the android_local_test rule https://docs.bazel.build/versions/master/be/android.html#android_local_test and support will be coming to Gradle, hopefully soon.

Switching to a resources.ap_ is really compelling as we're seeing around a two second improvement in startup time for the interactive use case, plus there is an increase in resource fidelity as we are no longer emulating aapt behaviour.

We will keep the existing support around for as long as we can, but we'd like to remove it sooner rather than later.

**Comment by jongerrish** [comment]
Just a friendly ping on this issue.

Binary resource support is now enabled for both Gradle (AGP) and Bazel.

I'd strongly urge implementing this functionality as we've seen 20-35% performance gains internally on test start up time, plus there is a whole lot of resources bugs that can be avoided just by using binary resources (we're not actively fixing any bugs in the old raw resource implementation which will be removed probably sometime in the 3-6 month time period)

**Comment by kageiit** [comment]
Thanks for the info @jongerrish cc @raviagarwal7 @thalescm

**Comment by kageiit** [comment]
Commit in bazel that enabled this
https://github.com/bazelbuild/bazel/commit/da51eb327c39b64357faa85ce5c884d51a58c003

**Comment by xiphirx** [comment]
As of 257e8469bd81ed167850c15d5b5fdeb443b2d954 Buck will now output a unit test properties file as described by http://robolectric.org/build-system-integration/ when utilizing binary resources mode via `use_binary_resources = True`. This feature is still experimental so please report any issues you see.
