### ISSUE TITLE
Homebrew version mismatch

### ISSUE THREAD

**Issue by shybovycha** [facebook/buck#1553]
I was just about to figure out my Buck version I've installed with Homebrew and here's what I've found out: Homebrew states version `v2017.09.04.02` but `buck --version` gives me `v2017.09.04.01`:

<img width="750" alt="screen shot 2017-10-02 at 2 18 09 pm" src="https://user-images.githubusercontent.com/137882/31063254-1d2b4a8c-a77d-11e7-8087-902c22423c7c.png">

**Comment by ttsugriy** [comment]
I will cut a new release today or tomorrow to resolve this and include some important new features like partial support for using buck with Java 9. Thank you for investigating @shybovycha!

**Comment by ttsugriy** [comment]
@shybovycha, I've pushed the new release to homebrew. Please give it a try and let me know if it works for you and feel free to reopen the task in case it does not.

**Comment by shybovycha** [comment]
Everything works fine, brew installs `v2017.10.01.01` and upgrades buck to this version.

Good job! Thanks!

**Comment by shybovycha** [comment]
Just wondering: what is in `master` what's not in that release?

**Comment by ttsugriy** [comment]
release was cut from https://github.com/facebook/buck/commit/2025fd74327477728b524eafdd4619a0170a24ea so everything before that commit is in release and everything after - not :) Glad to know that everything works now :)
