### ISSUE TITLE
go_unittest cannot depend on non go_library() target

### ISSUE THREAD

**Issue by lloyd** [facebook/buck#1556]
I am trying to build a golang unittest that depends on a non `go_library` target.  I need the side effects of the target to run.  I see the error: 

```
BUILD FAILED: //:generated_asset (needed for //:main#compile,darwin_amd64) is not an instance of go_library!
```

Is this just a missing feature of the golang support in buck?  Is there another way to create a manual dependency between a golang targets and something else that does not imply the golang target should *link* the targeted thing as if it were a go library? 

Note, I have create a sample project demonstrating the issue: https://github.com/lloyd/buckissue

**Comment by ttsugriy** [comment]
Normally in order to add a dependency on resources `resources` attribute is used, but `go_library` does not have support for it. Maybe @nemith would have some suggestion or would like to add missing features :)

**Comment by kageiit** [comment]
cc @ mkaczanowski

**Comment by kageiit** [comment]
We encountered a similar issue when trying to add support for thrift in go. We would like to have a genrule generate a sources zip that a go library can then depend on. This is supported by the java and python library rules today already

**Comment by kageiit** [comment]
cc @mkaczanowski

**Comment by mkaczanowski** [comment]
@lloyd you should be able to include the genrule to "srcs" with [this change](https://github.com/facebook/buck/commit/1e63bd9fade3ac4f0bc396de7ad013f12df60077)

please let me know if that fits your usecase

**Comment by kageiit** [comment]
Legit :)

<img width="787" alt="screen shot 2018-04-02 at 4 29 24 pm" src="https://user-images.githubusercontent.com/291148/38221192-1a319610-3693-11e8-9d6f-cbf82d50f32e.png">

**Comment by mkaczanowski** [comment]
Second thought: I forked the buckissue repo but this won't work.
The expectation is to have an asset generated in the main directory where binary is present (not for compile time - like it is with srcs).

This shouldn't be difficult to fix (I think)

**Comment by mkaczanowski** [comment]
I modified the buckissue [main paths](https://github.com/mkaczanowski/buckissue/blob/master/main.go):

```
$ ./buck-out/gen/buckissue/main/main 
Hello World! ./buck-out/gen/buckissue/main/../generated_asset/generated_asset
We're in /home/mkaczanowski
My Asset: hello generated asset world
```

The path needs point to the target directory, which sounds legit enough for this use case (it doesn't change the fact that genrules in deps should be a valid case - the behavior would be the same to as if you define genrule dep in srcs). 

Python uses [pkg_resources API](http://setuptools.readthedocs.io/en/latest/pkg_resources.html), with go we don't have such feature so I believe this case is "mitigated". This is:
1. you can use srcs to define the genrule dependency (you need to refer to the build target directory of genrule)
2. we need to allow genrules in the deps since it feels more correct (srcs should be used to generate the compile time required .go files etc)

@ttsugriy  @nemith does it sound legit to you?

**Comment by nemith** [comment]
Can genrules be referenced in resources?  Seems like a better place than srcs or deps.

https://buckbuild.com/rule/go_test.html#resources

**Comment by mkaczanowski** [comment]
It can but only for go_test. Buck will symlink the output to current directory while running buck test, for example:
```
...
go_test_link_tree @ buck-out/gen/buckissue/__test_main_test_output__/working_dir
go test
...
```
so the asset can be referenced within current directory. However this is only during buck test execution, so if you try to run:
```
./buck-out/gen/buckissue/main_test#test-main/main_test -test.v
```
it won't find the file.

Let's say we add "resources" to go_binary then we could mimic the go_test behavior with:
```
$ buck run ... 
```

**Comment by mkaczanowski** [comment]
With [https://github.com/facebook/buck/commit/d9d6c6f2b3d45ff1d3181b3af8ff501bb91415c9](https://github.com/facebook/buck/commit/d9d6c6f2b3d45ff1d3181b3af8ff501bb91415c9)

you're able to add resources to go_binary and go_test
