### ISSUE TITLE
Possible Memory leak when using the buck daemon

### ISSUE THREAD

**Issue by kageiit** [facebook/buck#1557]
<img width="755" alt="screen shot 2017-10-03 at 11 57 28 am" src="https://user-images.githubusercontent.com/291148/31143402-19b7c8de-a832-11e7-9d6a-a609146f4536.png">

The `com.facebook.buck.util.FileSystemMap` is not being cleared even after a full GC run after the build finishes in the buck daemon.

**Comment by yiding** [comment]
As you can see in the screenshot, this is used for the FileHashCache, which... caches the hashes of files. There doesn't seem to be an option to disable it though, so if you don't want to spend the memory for this you can probably add an option to `build.file_hash_cache_mode` to disable it (probably replacing it with a noop cache).

**Comment by kageiit** [comment]
Thanks. I think its fine to have. Thats what I labelled the issue as a `potential` leak. It does not look like it is actually
