### ISSUE TITLE
export compilation database for c++ projects

### ISSUE THREAD

**Issue by nikhedonia** [facebook/buck#1558]
It would be very useful for external tools to be able to query buck how to build a certain file/library.
Eg. I would like to know which compiler flags are required to build my main.cpp.
Does buck provide any facilities to extract this information for each file?

I've discovered that you can compile with `#compilation-database` flavour which creates a compilation-database.json for a particular target.

Is there any way to instruct buck to create one compilation database for the whole dependency graph of one target?

**Comment by scottrice** [comment]
This actually already exists - its a semi-secret "compilation-database" flavor. Its only briefly mentioned in the docs, and not in a very useful location - https://buckbuild.com/concept/buckconfig.html#client.skip-action-graph-cache

Anyway, you use it like:

```
buck build --show-output //lib/FooKit:FooKit#compilation-database,iphonesimulator-x86_64,static
```
