### ISSUE TITLE
NDK resolution has become more brittle

### ISSUE THREAD

**Issue by hzsweers** [facebook/buck#1565]
Recently (I haven't narrowed down where), buck became more strict around NDK version mapping, such tat I see a lot of these issues now

`BUILD FAILED: Buck is configured to use Android NDK version r16 at ndk.dir or ANDROID_NDK or NDK_HOME. The found version is 16.0.4293906-beta1 located at /Users/zsweers/dev/android/android-sdk/ndk-bundle`

The flexibility around ndk matching as it pertains to new versions being installed has already been documented a couple times, but I'd argue whatever change caused this has made it even more brittle. The above issue fails both `project` and `build` commands for me now

**Comment by styurin** [comment]
Buck has hard-coded logic to detect NDK version. We are working on a generic approach to allow toolchain configuration to live in the target graph.

Short term solution would be extend parsing logic to support v16.

**Comment by hzsweers** [comment]
Why not support the modern prefixing pattern? It hasn't changed in some time

**Comment by hzsweers** [comment]
NDK r16 has been released

**Comment by hzsweers** [comment]
17 is now out, this is broken again :/

**Comment by styurin** [comment]
16 and 17 should work fine.
