### ISSUE TITLE
`buck project --view` will be removed

### ISSUE THREAD

**Issue by styurin** [facebook/buck#1567]
`buck project --view` is another implementation of IntelliJ project generation. We plan to remove it from open source repository mainly because we believe no one outside of Facebook is using it.

If you use this functionality, please, let us know.

We plan to remove it by October 16.

**Comment by styurin** [comment]
@kageiit Do you use `buck project --view`?

**Comment by kageiit** [comment]
We are not using it. We wanted to at some point but the implementation seemed very fb specific so we didn't end up pursuing it. Thanks for the heads up!
