### ISSUE TITLE
`./bin/buck build buck` fails on master

### ISSUE THREAD

**Issue by jiangty-addepar** [facebook/buck#1573]
```
$ ./bin/buck build buck

~/git/buck-addepar/src/com/facebook/buck/android/AbstractAndroidGraphEnhancementResult.java:61: error: incompatible types: inferred type does not conform to upper bound(s)
    return getDexMergeRule().transform(left -> Optional.of(left), right -> Optional.empty());
                                      ^
    inferred: java.util.Optional<? extends java.lang.Object>
    upper bound(s): java.util.Optional<com.facebook.buck.android.PreDexMerge>,java.lang.Object
/home/damien/git/buck-addepar/src/com/facebook/buck/android/AbstractAndroidGraphEnhancementResult.java:73: error: incompatible types: inferred type does not conform to upper bound(s)
        .transform(left -> ImmutableList.of(), right -> right.getAdditionalRedexInputs());
                  ^
    inferred: com.google.common.collect.ImmutableList<? extends java.lang.Object>
    upper bound(s): com.google.common.collect.ImmutableList<com.facebook.buck.rules.SourcePath>,java.lang.Object
Errors: 2. Warnings: 21.

    When running <javac_jar>.
    When building rule //src/com/facebook/buck/android:rules.
```

`ant` works, but `buck` doesn't :( I'm using Oracle JDK 1.8.0_45 on Ubuntu 16.04, trying to build deda86ea2dcf8457aa0e702b87f8e0759324f459.

**Comment by ttsugriy** [comment]
your java version seems pretty old. I'd recommend trying a recent JDK version 1.8.0_144 for example and letting us know how it goes.

**Comment by jiangty-addepar** [comment]
@ttsugriy I upgraded to `1.8.0_144` and get the same error.

**Comment by jiangty-addepar** [comment]
also, maybe my IntelliJ settings are wrong, but the `buck` IntelliJ project isn't building in IntelliJ either.

**Comment by ttsugriy** [comment]
ant is using eclipse compiler that is bundled with Buck so it should be less dependent on environment, so it's expected to work always. At this point I can only recommend either using `ant` or spending some time to understand what is wrong with your local environment.

**Comment by jiangty-addepar** [comment]
Hmm... after multiple cycles of `ant clean` -> `ant`, `ant` found one additional java file to build, and now compilation works.

Very strange.

IntelliJ is still confused, though.
