### ISSUE TITLE
`buck project` test source roots

### ISSUE THREAD

**Issue by jiangty-addepar** [facebook/buck#1579]
I wish I could ask smaller questions in an irc channel or something, but Github issues still seem like the best way to ask... I'll probably have a lot of questions as we try to upgrade Buck from our very old fork to somewhere close to master.

It seems like `buck project` uses the `tests = [ '//module:test1', '//module:test2' ]` option in `java_library` (*) to know whether to mark certain directories as test source roots / resource roots.

In our project, many of our `java_library` targets have multiple `java_test` targets associated with them. Also, we often have "test utils" files that aren't actually tests that we mark as `java_library`, since including them in `java_test` would spam our test logs with a bunch of `NO TESTS`, which we found annoying.

So I tried doing something like
```python
TEST_SRCS = glob('foo/test/fast/**/*Test.java') + glob('foo/test/fast2/**/*Test.java')
SLOW_TEST_SRCS = glob('foo/test/**/*SlowTest.java')
TEST_UTILS_SRCS = glob('foo/test/**/*.java', excludes = glob('foo/test/**/*Test.java')

java_library(
  name = 'test_utils',
  srcs = TEST_UTILS_SRCS,
  deps = TEST_UTILS_DEPS
)

java_test(
  name = 'test',
  srcs = TEST_SRCS,
  deps = TEST_DEPS,
  resources = TEST_RESOURCES,
)

java_test(
  name = 'slow_test'
  srcs = SLOW_TEST_SRCS,
  deps = TEST_DEPS,
  resources = TEST_RESOURCES,
)

java_library(
  name = 'mytarget',
  srcs = SRCS,
  deps = DEPS,
  resources = RESOURCES,
  tests = [':test', 'slow_test', ':test_utils']
)
```

The `test_utils` are not all in their own packages (let's say that there are some `test_utils` inside `foo/fast2`), but the union of `TEST_SRCS, SLOW_TEST_SRCS, TEST_UTILS` should be all of `foo/test`.

However, the resulting test roots marked are just `foo/fast`; in particular, if the union of two targets comprise all the files in a directory (like `foo/fast2`), that directory is _not_ marked as a test root.

What code is picking the project roots (ModuleBuildContext::addSourceFolder?) Should I not have any `test_utils`? Should we generally not have multiple targets containing files from the same directories / packages?

(*) Does this `tests` option also exist for `java_binary`?

**Comment by styurin** [comment]
Can you create a simple integration test in `buck project` tests to show your case?

**Comment by jiangty-addepar** [comment]
@styurin https://github.com/Addepar/buck/commit/0fcb0d1d86131aa7630c32f7acf41b05bbf5e2ae

Unfortunately when I run the integration test it says `TESTS PASSED (with some assumption violations)`, and I can't run the integration test in IntelliJ because it complain about the Android SDK (which I don't have.)

However, I know the test doesn't pass, because I ran `buck project` with this `BUCK` file and it gave me something like
```
<?xml version="1.0" encoding="UTF-8"?>
<module type="JAVA_MODULE" version="4">
  <component name="NewModuleRootManager" inherit-compiler-output="true">
    <exclude-output />
    <content url="file://$MODULE_DIR$">
      <sourceFolder url="file://$MODULE_DIR$" isTestSource="false" packagePrefix="com.facebook.buck.ide.intellij.testdata.project_with_mixed_library_and_test.modules" />
      <sourceFolder url="file://$MODULE_DIR$/test" isTestSource="false" />
      <sourceFolder url="file://$MODULE_DIR$/test/test2" isTestSource="true" packagePrefix="test2" />
    </content>
    <orderEntry type="inheritedJdk" />
    <orderEntry type="sourceFolder" forTests="false" />
    <orderEntry type="module" module-name="src_com_facebook_buck_cli_bootstrapper" scope="COMPILE" />
  </component>
</module>
```

(I'm not worried about the `packagePrefix` because I run `buck project` from the root, but this is more about the XML structure: `/test/` is treated as a non-test source, whereas `test2` is a test source.)

Maybe this is on purpose, since `:test_util` is a `java_library`? But it's included in the `tests = [...]` list...

**Comment by jiangty-addepar** [comment]
I think I figured some stuff out -- I got the Android SDK (which is required for all of these tests for some reason? Might be able to refactor it so that android project integration tests are in one place, but that's minor) and I realized I didn't specify `.idea/modules.xml.expected`.

However, I still get the error `Project IDE is not specified` when trying to run the test. Also, when I edit test fixtures and re-run `./bin/buck test test/com/facebook/buck/ide/intellij:intellij`, buck very often, but not always, decides it needs to rebuild _the whole project_, and I don't understand why.

**Comment by jiangty-addepar** [comment]
Ok, I think I know what's going on now. When Buck sees a common ancestor of some sources / test sources dir, it tries to combine them into one sources dir. I don't really agree with this behavior.

I think I still prefer the old behavior from `project_config` where we could specify some `src_roots` and some `test_roots` :(

Alternatively, things in `tests = [ ... ]` should "take precedence": in the first pass, we do the computation for marking source root types for everything without the `tests = [ ... ]`, and in the second pass, we do the computation for the members of `tests = [ ... ]`, marking them all as `test_sources` / `test_resources` and overwriting what the first pass did.

**Comment by jiangty-addepar** [comment]
Bump: still haven't really found a way to replicate our old behavior of marking everything in `src/test/java` as a test source root, since `src/test/java` contains both `java_library` and `java_test` targets. It'd be nice to be able to do this again.

**Comment by jiangty-addepar** [comment]
Never mind, this is actually blocking. We have a directory structure like
```
test
|_ java
   |_ foo
      |_ bar
      |  |_ FooBarTest.java
      |_ FooTest.java
      |_ FooTestUtils.java
```

where `FooTest.java` imports a public static inner class from `FooBarTest.java`.

Previously, when `test/java` was marked as a Test Source Root, this would compile.

But now `test/java/foo/bar` is marked as a Test Source Root, while `/test/java` is only marked as a normal Source Root; IntelliJ then fails to compile the "source" file `FooTest.java` because it can't see the inner class of the "test" file `FooBarTest.java`.

One could argue that this isn't a good way to structure code, and that's probably true, but it's going to be a lot of work to clean up cases like this when things previously would "just work."

**Comment by styurin** [comment]
Sorry for long delay.

In your example, could you also add information about which targets do you have, where and their type?

**Comment by jiangty-addepar** [comment]
```python
TEST_SRCS = glob(['test/java/foo/**/*Test.java])
TEST_UTILS_SRCS = glob(['test/java/foo/**/*.java], excludes = TEST_SRCS)

java_library(
  name = 'test_utils',
  srcs = TEST_UTILS_SRCS
)

java_test(
  name = 'test',
  srcs = TESTS_SRCS,
  deps = ':test_utils',
)

SRCS = glob(['src/java/foo/**/*.java'])

java_library(
  name = 'foo',
  srcs = SRCS,
  tests = [':test'] # or [':test', ':test_utils']; doesn't seem to change anything? but it might
)
```

**Comment by styurin** [comment]
Oh, it was earlier in the post, my apologizes.

> IntelliJ then fails to compile the "source" file FooTest.java because it can't see the inner class of the "test" file FooBarTest.java.

Do you have this problems when you try to build code in IntelliJ? Most developers at Facebook do not build code using IntelliJ native Java compilation. We either use buck in the command line or invoke Buck build using IntellIJ Buck plugin. Given that, majority of our developers do not have this problem.

We also do not aim to provide the capability to build Buck project using IntelliJ native builder and the main reason is that IntelliJ module model is based on directories while Buck model uses files as a minimal entity in inputs of a target. This means that fundamentally Buck dependency graph cannot be represented in IntelliJ and therefore built properly.

We've done some work to integrate Buck functionality into IntelliJ UI via Buck plugin, but it only provides basic capabilities like syntax highlight and building/testing targets.

> Should I not have any test_utils?

It's up to you, but we use test utils targets to separate test code and test utilities.

> Should we generally not have multiple targets containing files from the same directories / packages?

The general motivation behind this behavior is to mark production sources properly when prod and test targets are in the same directory.

To solve you case we can add an option to .buckconfig to control this behavior.

Is this structure consistent across the whole repository? In other words, do you have places where you need different behavior or what you described is what you want to be applied to the whole project?

**Comment by styurin** [comment]
> What code is picking the project roots (ModuleBuildContext::addSourceFolder?)

I'm not sure what you mean by picking project roots, but I think you're right about the place where the changes should happen. `addSourceFolder` calls `mergePromotingToSourceIfDifferent` and that's the place where folders are merged into a `SourceFolder` so you'll need to change that method.

**Comment by jiangty-addepar** [comment]
I think for us, if we have a test and srcs in the same directory, we would actually prefer to merge them together under a test root (i.e. the opposite behavior of what it currently is.) The way our code is structured, `src` files never depend on anything underneath a `test/` directory.

**Comment by v-jizhang** [comment]
This issue is closed because there is no update for almost 3 years.
