### ISSUE TITLE
apple_bundle framework does not contain transitive dependencies

### ISSUE THREAD

**Issue by anoever** [facebook/buck#1580]
Hi, I'm trying to build a `.framework` bundle. 

```
cxx_library(
    name='cxx',
    ...
)

apple_library(
    name='lib',
    deps = [':cxx'],
    ...
)

apple_bundle(
  name = 'framework',
  binary = ':lib#static',
  extension = 'framework',
  info_plist = 'Dummy.plist',
  ...
)
```

The generated file contains the symbols from `lib` but not from `cxx` (verified with `nm buck-out/gen/framework#dwarf-and-dsym\,no-include-frameworks/framework.framework/framework`).

How can I force all transitive dependencies to be included? 

I have tried messing around with `link_style` and `preferred_linkage`. No luck so far.

**Comment by yiding** [comment]
"Static" frameworks are not really supported by apple, and there isn't a built-in method for creating them in buck. The `#static` flavor simply denotes the archive (.a) output containing the library object files, without transitive includes.

If you mean to use this for creating a distributable SDK, I would suggest a shell script involving buck query to get transitive dependencies, a buck build to build them, and using `ar` or `ld -r` on the result to generate a large `.o` or `.a`.

If you want to implement this capability in buck, I would suggest adding a rule which can perform the archive merging or ld -r'ing of a listed set of dependencies, or support a deps_query, as opposed to automatically including all transitives, as that's very rarely how software tends to be packaged, and may lead to duplicate symbols when composing such libraries with common dependencies.

**Comment by v-jizhang** [comment]
This issue is closed because there is no update for almost 3 years.
