### ISSUE TITLE
Python3 support

### ISSUE THREAD

**Issue by anoever** [facebook/buck#1581]
Is Python3 supported for `python_test`?

I have a python3 section in my `.buckconfig`
```
[python#py3]
  interpreter = /usr/local/bin/python3.6
```

I get:
```
 buck test //test#py3
Action graph will be rebuilt because files have been added or removed.
BUILD FAILED: The following flavor(s) are not supported on target //test:
py3.

Please try to remove them when referencing this target.
```

If I explicitly set `platform` in `BUCK`:
```
python_test(
    name="test",
    deps=[':main'],
    srcs=glob([...]),
    platform="py3",
)
```
```
Build failed: Command failed with exit code 1.
stderr: Traceback (most recent call last):
  File ".../tools/buck/src/com/facebook/buck/python/make_pex.py", line 181, in <module>
    sys.exit(main())
  File ".../tools/buck/src/com/facebook/buck/python/make_pex.py", line 156, in main
    raise Exception("Failed to add {}: {}".format(src, e))
Exception: Failed to add `.../buck-out/res/com.facebook.buck.python.PythonBuckConfig/__test_main__.py: [Errno 2] No such file or directory
```

**Comment by anoever** [comment]
Interestingly this was fixed by `buck clean`   (but not by `rm -rf buck-out/`)

**Comment by yiding** [comment]
`#py3` is not a flavor. The interpreter used is based purely on the `platform` attribute of the binary/test rule.

The error when you tried is due to the fact that that support file is not re-extracted into `buck-out/res` if you delete the directory, and don't restart buck. As nuking buck-out is not a rare operation, that behavior should probably be changed.

**Comment by anoever** [comment]
Thanks for the explanation.

> #py3 is not a flavor. The interpreter used is based purely on the platform attribute of the binary/test rule.

https://buckbuild.com/concept/buckconfig.html#python should probably be updated then.

-----

In case anyone else experiments with python3: Setting `python.interpreter` to a python 3 binary makes BUCK file parsing fail (`ModuleNotFoundError: No module named '__builtin__'`). Additionally setting `parser.python_interpreter` to python 2 makes parsing work, but building pex packages still fails (`make_pex.py` is executed with with `python.interpreter`).
-> If you want to use python 3 add a separate `[python#py3]` section and a `platform` attribute on every `python_binary/test` rule.

**Comment by ttsugriy** [comment]
I'm sorry to hear about this @anoever. You can try using our new experimental parser that uses a Skylark language. It does not use python so should not in any way interfere with python interpreter used for python rules. If you'd like to give it a try you can add following lines to your `.buckconfig`:
```
[parser]
  polyglot_parsing_enabled=true
```
and either make Skylark your default language for build files by appending another parser config entry:
```
  default_build_file_syntax=skylark
```
or add a following first line to each build file you'd like to use Skylark parser for:
```
# BUILD FILE SYNTAX: SKYLARK
```
