### ISSUE TITLE
Failing - When running <generate_resource_ids>

### ISSUE THREAD

**Issue by mohammed-safiq** [facebook/buck#1586]
Please find the following error when trying to build my own app

The following resources were not found when processing Pair(//app:res_lollipopDebug#resources-symlink-tree, buck-out/gen/app/res_lollipopDebug#resources-symlink-tree/res):
RDotTxtEntry{idType=int, type=string, name=summary_checkbox_preference, idValue=0x00000000, parent=summary_checkbox_preference}
RDotTxtEntry{idType=int, type=string, name=title_checkbox_preference, idValue=0x00000000, parent=title_checkbox_preference}
RDotTxtEntry{idType=int, type=string, name=default_value_edittext_preference, idValue=0x00000000, parent=default_value_edittext_preference}
RDotTxtEntry{idType=int, type=string, name=dialog_title_edittext_preference, idValue=0x00000000, parent=dialog_title_edittext_preference}
RDotTxtEntry{idType=int, type=string, name=summary_edittext_preference, idValue=0x00000000, parent=summary_edittext_preference}
RDotTxtEntry{idType=int, type=string, name=title_edittext_preference, idValue=0x00000000, parent=title_edittext_preference}
RDotTxtEntry{idType=int, type=string, name=default_value_list_preference, idValue=0x00000000, parent=default_value_list_preference}
RDotTxtEntry{idType=int, type=string, name=dialog_title_list_preference, idValue=0x00000000, parent=dialog_title_list_preference}
RDotTxtEntry{idType=int, type=array, name=entries_list_preference, idValue=0x00000000, parent=entries_list_preference}
RDotTxtEntry{idType=int, type=array, name=entryvalues_list_preference, idValue=0x00000000, parent=entryvalues_list_preference}
RDotTxtEntry{idType=int, type=string, name=summary_list_preference, idValue=0x00000000, parent=summary_list_preference}
RDotTxtEntry{idType=int, type=string, name=title_list_preference, idValue=0x00000000, parent=title_list_preference}

Build failed: Command failed with exit code 1.
When running <generate_resource_ids>.
When building rule //app:res_lollipopDebug.

What does this error mean?

**Comment by yiding** [comment]
I believe this means that you have references to resources without corresponding definitions.
