### ISSUE TITLE
Buck Failing - Resource not found exception

### ISSUE THREAD

**Issue by mohammed-safiq** [facebook/buck#1590]
I builded my target and its throwing hell lot of resource not found issues. Please refer one of the issue below.

buck-out/gen/app/res_lollipopDebug#resources-symlink-tree/res/menu/***.xml:3: error: Error: No resource found that matches the given name (at 'title' with value '@string/***').

Please refer this also

```
android_resource(
  name = 'res_lollipopDebug',
  package = 'com..',
  res = res_glob([
    ('src/main/res', ""),
   ('src/debug/res', ""),
  ]),
  assets = subdir_glob([
    ('src/main/assets', "**"),
  ]),
  resource_union = True,
  deps = [...]
)
```

What is the problem here?

**Comment by styurin** [comment]
We need more information, what's the content of files with resources? What is the exact error?

By the way, what's up with the package name? Is that the actual value you use in code?
