### ISSUE TITLE
build_file_import_whitelist = os.path doesn't work

### ISSUE THREAD

**Issue by jiangty-addepar** [facebook/buck#1591]
```
[project]
  build_file_import_whitelist = os.path
```

doesn't work---I get the error
```
AttributeError: Using function expanduser is forbidden in the safe version of module os.path. If you really need to use this function read about allow_unsafe_import() documented at: https://buckbuild.com/function/allow_unsafe_import.html
```

Is this because the module name has multiple parts? Is it because Buck already imports the "safe" version of `os.path`? How can I whitelist `os.path` methods without using `allow_unsafe_import()` everywhere?

**Comment by ttsugriy** [comment]
are you saying that you cannot import `os.path` directly? It should be possible.

**Comment by jiangty-addepar** [comment]
oh, maybe it's because I'm doing `from os import path`! Let me try `import os.path` instead

**Comment by jiangty-addepar** [comment]
Nope, still fails.

Sorry if I didn't make this clear: I want to import the "unsafe" version of `os.path` without using `with allow_unsafe_imports()` in a lot of different places.

**Comment by jiangty-addepar** [comment]
Well, I got around the problem by just going back to using `with allow_unsafe_import()`, but it turned out pretty ugly :(

**Comment by ttsugriy** [comment]
it's supposed to look ugly - using unsafe APIs is strongly discouraged and in our new Skylark parser we won't support any unsafe methods, so please consider not using them ;)

**Comment by jiangty-addepar** [comment]
Hmm...
- We're using a somewhat custom version of `remote_file` (taken from some old Gerrit code from back when they used Buck) that does local caching outside of Buck. We could try switching to `remote_file` instead.
- We've also been playing around with dynamically getting dependencies from internal artifacts we upload to Maven; this is probably an antipattern in Buck :(
- We have a macro that's used as a "template" for hundreds of targets to reduce code duplication. In the macro, we use `os.path.exists()` to check if a test resources directory exists, to let us know whether to include `resources`+`resources_root` in our `java_test`; maybe this wouldn't be needed if we could (a) glob an empty set of resources and (b) set a possibly nonexistent resources root without Buck complaining?
- In another macro, we search the filesystem to check if a file exists; this can probably be done via genrule?

**Comment by ttsugriy** [comment]
using `os.path.exists()` to check for test resources directory is a bad idea, because buck is not aware of this and would have no way to know what exactly should be invalidated and in you can easily end up in a situation with non-reproducible and hard to understand failure. If nothing else you can probably at least use something like:
```
test_resources = glob(['your_pattern'])
if test_resources:
  # handle test resources
else:
  # there are no test resources
```

**Comment by jiangty-addepar** [comment]
Oh, that's even simpler than what I was thinking! Nice :)
