### ISSUE TITLE
Is [project] temp_files = ... in .buckconfig still supported?

### ISSUE THREAD

**Issue by jiangty-addepar** [facebook/buck#1598]
There's still a test for it in `ParserTest`, but the `.buckconfig` in this repo just puts all the temp file patterns under `ignore = ...`; is the `temp_files = ...` config still supported?

**Comment by ttsugriy** [comment]
support for `temp_files` was removed in favor of `project.ignore` I'm going to remove a reference to this obsolete configuration option.

**Comment by jiangty-addepar** [comment]
Thanks!
