### ISSUE TITLE
Interpolate bash variable into a genrule's string parameter macro

### ISSUE THREAD

**Issue by jiangty-addepar** [facebook/buck#1599]
We'd like to do something like
```python
# foo/BUCK
for i in ['Linux', 'Darwin']:
  genrule(
    name = 'bar-' + i,
    # blah
  )

genrule(
  name = 'bar',
  cmd = 'cp $(location :bar-$(uname -s)) $OUT',
  out = 'my-plat-bar'
)
```
where we want to let people refer to `//foo:bar` that's specific to their own system's platform, but also allow them to refer to `//foo:bar-Linux` and `//foo:bar-Darwin` if they want to explicitly build the genrule for the other architecture.

Unfortunately, using bash interpolation within a string parameter macro like `$(location {})` doesn't work; it'd be nice if it did.

Maybe we just shouldn't have the convenience of having a single build rule refer have different outputs depending on platform? Seems unfortunate, though :(

(Context: we currently use `import sys`, an unsafe import, to do this from python instead of inside the genrule itself.)

**Comment by jiangty-addepar** [comment]
wait... there's `command_alias()`

let me try that!

**Comment by jiangty-addepar** [comment]
oh, that doesn't quite work, since this is a genrule and not a sh_binary :(

**Comment by jiangty-addepar** [comment]
ok, I guess one idea for this, since `foo:bar` runs some shell script, is:
```bash
#!/bin/bash
# bar-generate.sh
# run plat-dependent stuff that takes in the plat as an argument generates some output
```

```python
# foo/BUCK
sh_binary(
  name = 'bar-generate',
  src = "bar-generate.sh"
)

for i in ['macos', 'linux']:
  export_file(
    name = 'bar-' + i,
    cmd = "do_expensive_setup && $(exe :;bar-generate) {} $OUT".format(i),
    out = 'bar-'+i,
  )

command_alias(
  name = 'bar',
  platform_exe = {
    'macos': ':bar-macos',
    'linux': ':bar-linux',
  },
)
```

**Comment by ttsugriy** [comment]
I'm not sure what are you using `sh_binary` for, since having a dependency on a `genrule` is sufficient to create its output for the rule that depends on it. I think adding an `executable = True`to your `genrule` is all you need to use genrules directly.

**Comment by jiangty-addepar** [comment]
Oh, that helps! Thanks :)
