### ISSUE TITLE
genrule issues

### ISSUE THREAD

**Issue by utkudiril** [facebook/buck#1600]
Hi,

I am trying to use genrule to generate some files using an external script which is also tracked by buck. The problem is that I couldn't find a way to express the dependency and also use the python file that is generated by the other BUCK file in another directory.

genrule(
    name = 'thing',
    out = 'thing.generated',
    srcs = [
        'thing.source',
    ],
    _deps = [
        "//scripts/generators:the_generator",
    ],_
    cmd = "$(exe //scripts/generators:the_generator) -i $SRCS -o $OUT",
)

Deps does not work. So I removed it. Then I got this error:

>buck build //dir/common/... --show-output
BUILD FAILED: //dif/common:thing depends on //scripts/generators:the_generator, which is not visible

I tried visibility but it had no effect.

**Comment by utkudiril** [comment]
Actually I figured it out. Visibility has to be for the library that the "thing" rule depends on.

**Comment by ttsugriy** [comment]
you're correct, all dependencies must be visible to rules that depend on them
