### ISSUE TITLE
Unable to run "buck test" on desired simulator

### ISSUE THREAD

**Issue by varun531** [facebook/buck#1601]
I'm currently unable to run "buck test" on my apple_test target and specify what simulator I want it to run on. It always runs on the iPhone 5s. My command:

`buck test //path/to/test:Target -n "iPhone 7 Plus"`

Has anyone else had success running "buck test" on the simulator of their choice?

Buck version: v2017.10.01.01
XCode: XCode 9 (though I've also tried it with Xcode 8)

**Comment by varun531** [comment]
An update:

After digging through the source code, it turns out you CAN control the choice of simulator like this:

```
apple_test(
  name = 'TestName,
  destination_specifier = {'platform': 'iOS Simulator', 'OS': '11.0', 'name': 'iPhone 6'},
)
```

However, this isn't documented anywhere on the [apple_test](https://buckbuild.com/rule/apple_test.html) page, so I am hesitant to start relying on it.

I must be missing something. What is the tried and true way to control what simulator an _apple_test_ runs on.

**Comment by robbertvanginkel** [comment]
There's a documented `apple.xctool_default_destination_specifier`, see
https://buckbuild.com/concept/buckconfig.html#apple.xctool_default_destination_specifier

**Comment by varun531** [comment]
@robbertvanginkel 

Yeah I saw this.

What I wanted was a way to run the same _apple_test_ on multiple simulators, programmatically (if I had view tests, for example, where I take a snapshot of screens across various screen sizes to ensure there are no regressions).

**Comment by v-jizhang** [comment]
This issue is closed because there is no update for almost 3 years.
