### ISSUE TITLE
Researching Build Breakage

### ISSUE THREAD

**Issue by devbridie** [facebook/buck#1602]
Dear developers of the facebook/buck project,

We are MSc students from the Delft University of Technology doing research on why builds break in open source projects. To do this, we are analyzing Travis build statistics and build history of buck.

By analyzing the build history of buck, we found the following:
* The project has 61% failing builds in the history
* The project has a high amount of build failures compared to other similar projects

When looking at buck’s build metrics, we could not find clear factors that are highly correlated with this result.

To identify the reasons behind build breakage, we would like to collect developer insights into the reasons why build breakage occurs. If you have five minutes, please answer the [survey](https://www.surveymonkey.com/r/PQ7XTGM) we have created. Your response will be very useful in our study.

Thank you.

**Comment by styurin** [comment]
The main reason is that this project has internal tests which are not exposed to public and we rely on them to verify the correctness.
