### ISSUE TITLE
Support for Annotation Processor Options [Android/Java]

### ISSUE THREAD

**Issue by jchensc** [facebook/buck#1606]
### Feature request
Currently buck only support "annotation_processors", "annotation_processor_deps", "annotation_processor_params", and "annotation_processor_only" as described in https://github.com/azatoth/buck/blob/master/src/com/facebook/buck/java/JavaLibraryBuildRuleFactory.java. However, it's unable to process `annotationProcessorOptions` as it is in gradle. This will cause some issues while importing some third party libraries.

e.g. 
Objectbox (http://objectbox.io/documentation/introduction/) requires the model file being updated along with annotation processing. By default this file will be put under project root, and this will cause issue during buck sub-module building. 
```error: [ObjectBox]Could not find project root to create model file``` 
Objectbox provided `objectbox.modelPath` as an annotation processor argument to provide an absolute path, if we could pass this argument through buck, this problem could be solved. But currently we are unable do this. 

Thanks in advance for your help on this issue.

**Comment by kageiit** [comment]
You can use javac arguments to pass in apt options like `-Aobjectbox.modelPath=...` to javac so its already supported. I would advise not to pass in absolute paths, but use project root relative paths instead as it keeps your cache keys the same across multiple machines

**Comment by jchensc** [comment]
@kageiit thanks it works

**Comment by jkeljo** [comment]
Just saw this. `annotation_processor_params` will do this as well.

**Comment by taotaoping** [comment]
@jchensc @kageiit  I have the same issue, after add '-Aobjectbox.modelPath=xxxx' to android_library extra_arguments, still have same issue, could you tell me how to make it work?
