### ISSUE TITLE
.buckconfig [project]: ignore 1 file, but not others with the same name

### ISSUE THREAD

**Issue by jiangty-addepar** [facebook/buck#1608]
Background:

We have our own buck wrapper script checked in as `./buck` in our project root. We also have a lot of developers on OSX who have case-insensitive filesystems.

Our old version of buck was somehow able to realize that `./buck` was not a `BUCK` build file, even despite the case-insensitivity of the filesystem, but upon upgrading buck, we now get an error message about how it can't parse the shell script as a `BUCK` build file.

The options we came up with were:

1. forcing everyone to create a case-sensitive partition (painful)
2. renaming `./buck` to something like `./buckw` (would require us to change a large number of deployment and testing scripts, and get developers used to the new name of the command)
3. ignore `buck` inside `.buckconfig`, like so:

```
[project]
  ignore = buck
```

Unfortunately, the 3rd option didn't seem to actually work: even on my case-sensitive filesystem, buck began ignoring changes to actual `BUCK` build files! Is there a way I could ignore just the file I want? (`./buck` didn't seem to work...)

**Comment by jiangty-addepar** [comment]
Also, a tangentially related question: what does this comment mean?
https://github.com/facebook/buck/blame/master/src/com/facebook/buck/io/filesystem/impl/DefaultProjectFilesystemFactory.java#L90

**Comment by jiangty-addepar** [comment]
Came up with a horrendous 4th solution as well: get the file to be syntactically correct in both bash and python.

```bash
#!/bin/bash

a=''' '
# body of shell script
b=' '''
```

**Comment by sdwilsh** [comment]
Option five (eww about four): rename your `BUCK` files to something else and set this to something different: https://buckbuild.com/concept/buckconfig.html#buildfile.name

**Comment by styurin** [comment]
It seems like this problem is specific to one project only and we don't really want to support cases like this.

As to your problem, you can rename all BUCK files to something else thought it might be too disruptive to do.

My recommendation is to pay one time cost of moving `./buck` to something else rather dealing with workarounds. The more time use spend with that the more problems you'll have later.

> get the file to be syntactically correct in both bash and python.

We are moving to Skylark soon and it can break with that migration.

**Comment by jiangty-addepar** [comment]
Thanks for the recommendations! I'll probably do hack #4 for now and figure out a transition plan for renaming `./buck` after I finish the upgrade.
