### ISSUE TITLE
Incoming changes in the format of SRCS env variable passed to genrules

### ISSUE THREAD

**Issue by styurin** [facebook/buck#1610]
As part of the sandboxing effort we will be tightening genrule access to the project tree.

`SRCS` environment variable contains a list of absolute paths to inputs specified in `srcs` parameter of a genrule. This list will be replaced with a list of absolute paths to symlinks in genrule's srcs directory. This directory is created during genrule execution and resembles the directory structure of inputs specified in `srcs`.

Please, let me know if you have questions or concerns.

**Comment by kageiit** [comment]
cc @msridhar to check if it affects any of our genrules

**Comment by msridhar** [comment]
cc @lazaroclapp can you take a quick look on this one?

**Comment by styurin** [comment]
14f7eb4cc927eea4ab861b3bb88b52037149f783 adds an ability to change this behavior for the whole project or by target.

**Comment by styurin** [comment]
The diff was reverted because there is a bug in the procedure that creates symlinks. When multiple targets in the same package create files with the same name Buck creates one symlink. The current issue is on hold till I fix that bug.
