### ISSUE TITLE
Rename `buck cache` to `buck cache fetch`

### ISSUE THREAD

**Issue by stepancheg** [facebook/buck#1617]
`buck cache` is going to be `buck cache fetch` soon, and after several days `buck cache` command without `fetch` argument will stop working.

This is necessary to implement other `buck cache` command like `buck cache delete`.

**Comment by kageiit** [comment]
Pretty sure we dont use this command. @robbertvanginkel what abt you guys?

**Comment by robbertvanginkel** [comment]
No, we don't either.
