### ISSUE TITLE
Unexpected behavior when including platform dependent libraries (e.g. prebuilt_cxx_library)

### ISSUE THREAD

**Issue by pjrader1** [facebook/buck#1622]
I have discovered an unexpected behavior when using `prebuilt_cxx_library`. I have several libraries in my project, one of which is GLFW (yes I could use Buckaroo for this library, but Buckaroo still has some kinks to work out, plus I have the same issue for other libraries). So using `prebuilt_cxx_library` I set up different static libraries based on the platform:
```
prebuilt_cxx_library(
    name = 'glfw',
    platform_static_lib = [
        ('^windows.*', 'glfw/build/lib/glfw3.lib'),
        ('^macos.*'. 'glfw/build/lib/libglfw3.a')
    ],
    exported_headers = subdir_glob([
        ('glfw/build/include/GLFW', '**/*.h')
    ]),
    preferred_linkage = 'static',
    header_namespace = 'GLFW',
    visibility = [
        'PUBLIC'
    ]
)
```
The reason for this is so that I can have GLFW as a submodule in my repository and build it on the local machine instead of having the binaries and header files (this makes it easier to update GLFW to a newer version quite easily, as well as any of my other libraries that my project depends on).

Regardless of reasoning, this does not build, on either Windows or macOS. I get the following error:
```
BUILD FAILED: //:glfw: parameter 'platformStaticLib': no such file or directory 'glfw/build/lib/glfw3.lib'

This error happened while trying to get dependency '//:glfw' of target '//:project#macosx-x86_64'
```
This was when I built on macOS, a similar error occurs for `libglfw3.a` when I build on Windows. I specify the platform when I build (#macosx-x86_64 and #windows-x86_64)

After some investigating it appears that in this case, Buck is checking that the file exists first before deciding to include it in the build on a specific platform. From an outside speculation, this makes sense if `platform_static_lib` is derived from `static_lib`; `static_lib` runs, and then since the file isn't found it throws an error and stops the build. I don't know exactly.

Anyway, to me this is unexpected behavior. My thinking would be it would only attempt to include the file if the platform matches, and if it doesn't it straight up ignores it. If it's intentional, it would be valuable to include this note in the documentation. I was quite confused when I first ran into the error. 

I created a sample repository [here](https://github.com/pjrader1/BuckCxxPlatformStaticLibraryEx) if anybody wants to reproduce. Edit the root BUCK file, the `glfw` target has a Linux platform specified but no library files for it, so it will fail. Commenting out lines specifying Linux will build as expected.

**Comment by v-jizhang** [comment]
This issue is closed because there is no update for almost 3 years.
