### ISSUE TITLE
--flaky_test_attempts support for buck

### ISSUE THREAD

**Issue by romanoid** [facebook/buck#1625]
Hi Buck team, 

I wanted to contribute and support `--flaky_test_attempts=` in Buck and were looking for advice on my approach: 

I were going to support it for Java specifically:
1. Update `JUnitRunner` to be able to re-run failing tests
2. Pass additional flag all the way from `TestCommand` to `JUnitRunner`
3. (maybe): introduce new `ResultType`: `FLAKY` and support reporting of which tests were Flaky

Cons of this approach: similar to `--code-coverage` flag, this will be supported only for some of the possible targets (specifically java test targets), which is less then ideal. 

Thanks for feedback,
Roman

**Comment by styurin** [comment]
Have you thought about using an external runner for that? Check this config section to learn how to configure a test runner: https://buckbuild.com/concept/buckconfig.html#test.external_runner

**Comment by romanoid** [comment]
I were considering using external runner, but here's what stopped me: 
1. Existing runner already handles a lot of corner cases and re-implementing these sounded less then optimal for me. Copy-pasting existing one and diverging sounds like a nightmare too, since we're not going to receive all the upstream goodness. 
2. --flaky_test_attempts seems to be useful for community, flaky tests are always problem for any big enough repo and having some built-in support for it sounds like a great idea.

**Comment by styurin** [comment]
Different projects have different strategies around flaky tests and don't want to force one way or another. An ability to use external testrunner looks ideal for such functionality and this is what we do internally. I don't think we are going to do any changes here.

What would be useful for community is to create a test runner outside of buck repository which can be configured however you want.

**Comment by romanoid** [comment]
Here's few comments: 
"don't want to force one way or another" – I were not proposing forcing anything, but instead optional flag similar to Bazel's one that you can pass when running tests. (as `buck test my/target/...  --flaky_test_attempts=3`)
" I don't think we are going to do any changes here." – I understand that this request is very custom to limited amount of use cases and were wondering if you will be ok with me contributing this functionality, I'd rather have conversation we have now then on PR. 
" What would be useful for community is to create a test runner outside of buck repository which can be configured however you want." – that's an awesome idea, if we end up going the custom runner direction, we probably should publish "BaseExternalRunner" or something that is easy to start from when creating own runners.

**Comment by uri-canva** [comment]
> if we end up going the custom runner direction, we probably should publish "BaseExternalRunner" or something that is easy to start from when creating own runners.

Custom runners would be invoked through the `test.external_runner` config, so they wouldn't necessarily have to be written in Java or have anything to do with the Buck codebase.

**Comment by romanoid** [comment]
Thank you for all the suggestions and discussion, I'm closing the issue for now.

**Comment by styurin** [comment]
We use an approach where a test runner controls which tests needs to be executed and skipped and how many times they need to be retried.

Another approach is to ask buck to run tests and then analyze test results to detect if some failures needs to be skipped, etc. In this approach adding re-trying logic to Buck seems reasonable.

Since we don't use the second approach, we aren't going to do any improvements here. If you want to add support for that, we'd like to get better understanding of what you want to add and how that would affect test reporting.

**Comment by ttsugriy** [comment]
it's super unfortunate to have flaky tests, but since it's a reality, we are open to PRs with `flaky` attribute support similar to how it's done in [bazel](https://docs.bazel.build/versions/master/be/common-definitions.html#test.flaky)

**Comment by alxn** [comment]
Good effort @romanoid I was surprised there wasn't a solution like in [surefire](https://maven.apache.org/surefire/maven-surefire-plugin/examples/rerun-failing-tests.html).
