### ISSUE TITLE
Moving to a modular Buck

### ISSUE THREAD

**Issue by styurin** [facebook/buck#1626]
We are working on a solution to move Buck to a module-based architecture where core functionality is separated from particular rule type functionality. Domain-specific logic will be moved to a stand-alone modules which will be packaged as jars and loaded using a plugin framework.

We plan to use this separation to replace git commit hash in rule keys with the hash of binaries used by Buck. This should reduce the rate of rebuilding artifacts when updating Buck to a new version.

I'm going to use this issue to track the progress, give updates and notify about possible changes

**Comment by styurin** [comment]
ec3aee5f6d69ca4c50847de46b49dd2cfdef489e moved a module with zip rules into a stand-alone module.

**Comment by kageiit** [comment]
Can we make it possible to load custom modules via a plugin framework without needing to hack the bootclasspath of buck?

**Comment by kageiit** [comment]
Another question is if the hash of the cxx module changes, does that mean that java rules will be unaffected upon updating buck?

**Comment by shs96c** [comment]
Is there a public, stable API that I can use for my plugins? I'll need
that, since these appear to be java code.

Can I redefine existing rules?

How do I refer to functionality in other plugins from my own? For example,
if I want to use the FIleBundler from the zip rules, how is this done?

**Comment by shs96c** [comment]
Can extensions be built and loaded as part of a single build?

The original plans for extensions included allow each cell to define its own extensions. I'm hoping this will be retained.

**Comment by styurin** [comment]
> The original plans for extensions included allow each cell to define its own extensions.

Yeah, it's possible, but it's not on a plan right now. I'll take a look at lazy / per-cell loading of modules after the implementation in a better state.

**Comment by jiangty-addepar** [comment]
Exciting! :)

**Comment by styurin** [comment]
> Can we make it possible to load custom modules via a plugin framework without needing to hack the bootclasspath of buck?

It's not a priority right now, but I see no reason why we can't do that. I'd wait for APIs to stabilize before doing that though, otherwise it'll be difficult to maintain.

> Another question is if the hash of the cxx module changes, does that mean that java rules will be unaffected upon updating buck?

If java rules do not depend on cxx than yes, updating cxx rules will not affect java. Right now java rules depend on cxx, not sure if we can refactor them to remove this dependency. There are very few rules that do not depend on cxx so this is not the best example. For instance, changing Android code should not affect Java rules.

> Is there a public, stable API that I can use for my plugins?

Not yet, this a step towards extracting core API for rules and decoupling non-related rules. There might be other injection points not related to rules and I think we can discuss adding them to solve your use cases.

> Can I redefine existing rules?

The way how it's implemented right now no, and I think we'd better keep it that way. I think a better approach here is to enhance existing rules using build defs and SkyLark.

> How do I refer to functionality in other plugins from my own? For example, if I want to use the FIleBundler from the zip rules, how is this done?

I'm working on adding support for dependencies between modules so you'll have to explicitly declare that your module depends on a module with zip rules.

> Can extensions be built and loaded as part of a single build?

Could you explain this scenario, please?

**Comment by shs96c** [comment]
> > Can extensions be built and loaded as part of a single build?
> Could you explain this scenario, please?

I think it'll be something needed to enable extensions to continue working despite a shift in ABI in Buck's core. Right now, Skylark rules in Bazel are immune from changes in Bazel's core since they're interpreted. Given how extensions are being developed here, this won't be the case for Buck.

More practically, the Selenium project has rules for packaging Firefox extensions defined as things like "`mozilla_extension`". This doesn't feel like a good fit for Buck itself (as it builds a XPI, which Mozilla have just EOL'd), but it's really useful to be able to refer to these in our own build. Something like this in the `BUCK` file would be splendid:

```
# Contains the extension definition for mozilla_extension
load_extension("//java/buck/src/org/openqa/buck/mozilla:mozilla")


mozilla_extension(name = "webdriver.xpi",
  ...
)
```

I was looking at the rules deleted in 5fcf326a4b8d22fbbd5ce8e593b58fdbe7f7d425 but it doesn't look like that shows injecting a new build rule into `KnownBuildRules`

**Comment by styurin** [comment]
@shs96c I just added an ability to use dependent modules (see 49cb16e9caa76830a66e30842a4204906fab7e93 for an example). You can also use [DescriptionProvider](https://github.com/facebook/buck/blob/45169c281d7d74601b85edc6025153b7b75e1139/src/com/facebook/buck/rules/DescriptionProvider.java) to register new build rule types without touching `KnownBuildRuleTypes`. Note that at this point we cannot guarantee the stability of the API, it can be changed in future.

> Something like this in the BUCK file would be splendid:

What stops you right now to write custom build rules using Skylark?

**Comment by shs96c** [comment]
> What stops you right now to write custom build rules using Skylark?

I need to use the zip functionality, and I can't rely on that being installed on the machine, or that the generated zips will be repeatable (with timestamps cleared, etc). In addition, I need this to work on Windows, Linux, and OS X, which makes using `genrules` a Really Bad Idea.

**Comment by styurin** [comment]
> In addition, I need this to work on Windows, Linux, and OS X, which makes using genrules a Really Bad Idea.

Python can give you system-independent functionality :)

What exactly do you do with zip files? Should Buck support that?

**Comment by shs96c** [comment]
Python is a PITA. I run training sessions where I tell people to install Python 2.7 and they _still_ install the latest python 3.x. It's also slow as heck on Windows. Fortunately, the skylark build file parser helps an awful lot.

**Comment by shs96c** [comment]
The zip files? It's the `FileBundler` I'm keen to use. As of the latest versions of Buck, I can start the move to modules, but there's one small problem: some of my `Description` instances need access to the `BuckConfig`.

Writing a simple method to find the longest public constructor and shoving values into it isn't particularly taxing --- it's a handful of lines of code. I'm not quite sure where to hook it in.

Also, it'd be nice if there was a `PluginManager` per `Cell` rather than globally....

**Comment by styurin** [comment]
> some of my Description instances need access to the BuckConfig.

This should be easy to add access to config. I'm going to migrate some descriptions that require BuckConfig so there should be support for that soon.

> Also, it'd be nice if there was a PluginManager per Cell rather than globally....

Do you mean loading external plugins per cell configuration? This means adding a way to load external plugins and we don't have plans to do that though I don't see a reason why we shouldn't do that if you want to add support for that.

**Comment by styurin** [comment]
@shs96c 2988b70363ef2ae556f37ab244e05c4baf35bce7 added an ability to access `BuckConfig` when creating descriptions.

**Comment by shs96c** [comment]
Got this working with Selenium's code base. Lovely.

The next shiny it'd be great to have are:

1/ Provide a stable API to build extensions against (ModernBuildRule, Step,
and "anything that transitively leads to these" are required. Things like
the file copying steps are incredibly useful primitives too)

2/ Allow us to specify a path to extensions in .buckconfig and have these
be loaded per-cell.

3/ Allow a build to bind an extension "mid-build"

The third case would allow us to ship the extensions to Buck that Selenium
uses as part of our own tree.
