### ISSUE TITLE
Support for embedded proguard files inside android_prebuilt_aars

### ISSUE THREAD

**Issue by kageiit** [facebook/buck#1628]
The [aar format](https://developer.android.com/studio/projects/android-library.html#aar-contents) specifies they can optionally contain a `proguard.txt` file that should be merged into the final proguard file used for obfuscating releases.

I plan to add support for this into buck via a PR. opening this issue to gather feedback from the maintainers.

**Comment by kageiit** [comment]
cc @styurin @dreiss

**Comment by dreiss** [comment]
Discussed on Slack.  This should already be working.

**Comment by kageiit** [comment]
will confirm and close this if its already working

**Comment by kageiit** [comment]
@dreiss is right. They proguard files from aars do get included in the final obfuscation step.
