### ISSUE TITLE
WorkspaceUpdater forces full IntelliJ restart every time `buck project` is run

### ISSUE THREAD

**Issue by jiangty-addepar** [facebook/buck#1629]
https://github.com/facebook/buck/blob/master/src/com/facebook/buck/ide/intellij/WorkspaceUpdater.java uses `XPath` to manipulate `workspace.xml` in order to work around a performance bug in IntelliJ. However, it ends up rearranging properties on some xml nodes in `workspace.xml`, confusing IntelliJ and forcing users to reload the project if they have certain plugins like `ToolWindowManager`, `CoverageDataManage`, etc.

Having to constantly restart IntelliJ, while probably not much of an actual time loss given the time it takes IntelliJ to index files, is quite an annoyance.

Further info: we get a popup with the text

```
Project 'PROJECT' components were changed externally and cannot be reloaded:

ToolWindowManager

Would you like to reload project?
```

The diff between (before the reload) and (after the reload) has a bunch of lines that look something like
```
<       <provider selected="true" editor-type-id="text-editor">
---
>       <provider editor-type-id="text-editor" selected="true">
```

**Comment by jiangty-addepar** [comment]
@styurin

**Comment by v-jizhang** [comment]
This issue is closed because there is no update for almost 3 years.
