### ISSUE TITLE
export_file behavior change

### ISSUE THREAD

**Issue by kageiit** [facebook/buck#1630]
`export_file` broke behavior recently that breaks proguard for us.

Before, we could do something like this

```
for file in glob(['proguard.pro', 'proguard.map']):
  export_file(
    name = file,
    visibility = ['PUBLIC'],
  )
```

Then depend on the proguard config normally. We need the `proguard.map` file to reside side by side to the `proguard.pro` file as the only way to use such file is to do

`-applymapping proguard.map` in the config file (proguard provides no cli flags to pass in mapping files)

Before, both the files would be exported to the same location, but recently, it seems like there is a nested directory being created for every file so we end up with

```
proguard.pro/proguard.pro
proguard.map/proguard.map
```

In the output directory which breaks the previous behavior

**Comment by kageiit** [comment]
cc @styurin @cjhopman

**Comment by kageiit** [comment]
We were able to workaround this by always using `export_file` in reference mode. But this behavior is still a change and should probably be documented/fixed for other use cases. Having some tests should be good to ensure future behavior changes are not done uncaught.

**Comment by styurin** [comment]
The solution here is to use a `genrule` to place files in locations you need them to be. You can also use `filegroup` which should place these two files together.
