### ISSUE TITLE
BUILD FAILED: No native platforms detected. Probably Android NDK is not configured properly.

### ISSUE THREAD

**Issue by zk1393943039** [facebook/buck#1631]
windows10 cmd build  

use the cross-platform-scale-2015-demo

my env config:
ANDROID_HOME: D:\dev_programs\android-sdk
ANDROID_SDK: D:\dev_programs\android-sdk
ANDROID_NDK_REPOSITORY: G:\android-ndk-r10e
PATH:
C:\MinGW\bin
%ANDROID_HOME%
%ANDROID_SDK%
%ANDROID_NDK_REPOSITORY%

1.defunt 
C:\Users\Administrator\Desktop\bucksamples-master\cross-platform-scale-2015-demo\\.buckconfig
[ndk]
  ndk_version = r10e
  app_platform = android-21

result:  
BUILD FAILED: No native platforms detected. Probably Android NDK is not configured properly.

2.change

android studio ndkVersion is  16.0.4442984
I changed the ANDROID_NDK_REPOSITORY path to D:\Users\Administrator\AppData\ndk-bundle
this is the android studio ndk directory

C:\Users\Administrator\Desktop\bucksamples-master\cross-platform-scale-2015-demo\\.buckconfig
[ndk]
  ndk_version = 16.0.4442984
  app_platform = android-21

result: 
 BUILD FAILED: No native platforms detected. Probably Android NDK is not configured properly.

**Comment by michelgb** [comment]
i have similar issue

**Comment by mohammed-rampurawala** [comment]
Any resolution found for this issue?

**Comment by michelgb** [comment]
Actually no. Androin NDK was installed using chocolatey.

**Comment by erhu** [comment]
Add 
```
ANDROID_HOME=/Users/xxx/Library/Android/sdk
ANDROID_NDK=/Users/xxx/Library/Android/sdk/ndk-bundle
```
to your .buckconfig file.
