### ISSUE TITLE
Make compilation error events be emitted for other compiler types

### ISSUE THREAD

**Issue by kageiit** [facebook/buck#1632]
Need to do more of https://github.com/facebook/buck/blob/19be87a4ce61989a04bb158d055fc146bdf97553/src/com/facebook/buck/jvm/java/JavacStep.java#L107 for other compiler types we care about. Just creating this issue as a placeholder. PR for this functionality will come soon.

**Comment by kageiit** [comment]
cc @edsilfer

**Comment by v-jizhang** [comment]
No PR yet, closing this issue.
