### ISSUE TITLE
Adding support for getting the abi classpath in genrule macros

### ISSUE THREAD

**Issue by kageiit** [facebook/buck#1635]
There are several cases where getting access to the abi classpath is enough to run certain genrules like android lint. Buck currently has no way to obtain this as a macro. This proposal would like to add such functionality so we can take advantage of it in lint and in other such genrules

**Comment by kageiit** [comment]
cc @dreiss @jkeljo

**Comment by raviagarwal7** [comment]
pull request for adding abi classpath macro - https://github.com/facebook/buck/pull/1780/
