### ISSUE TITLE
Specifying location of `export_file` resource in jar

### ISSUE THREAD

**Issue by jiangty-addepar** [facebook/buck#1636]
I have a logging config `logback.xml` that I'd like to share among different jars. It's recommended to have individual runnable jars each contain their own `logback.xml` due to potential classpath pollution, but most `logback.xml`s are roughly the same, so I decided to create a file `utils/logback.template.xml`.

In `utils/BUCK`:
```python
export_file(
  name = 'logback.xml',
  src = 'logback.template.xml',
  out = 'logback.xml',
  visibility = ['PUBLIC'],
)
```

In `foo/bar/BUCK`:
```python
java_library(
  name = 'bar_lib',
  srcs = SRCS,
  resources = RESOURCES + ['//utils:logback.xml'],
  resources_root = 'src/main/resources',
  deps = DEPS,
)

java_binary(
  name = 'bar',
  deps = [':bar_lib'],
  # other stuff
)
```

Unfortunately, `logback.xml` gets placed at `utils/logback.xml` within `bar.jar`, when I want it to be placed at the root of the jar. Is there a way to do this?

I don't think this is a dupe of #1630 since our current version of Buck doesn't have the commit https://github.com/facebook/buck/commit/b1f3f9fbee92e90cf62293d13e2a4bd3ade7f874#diff-0eac0fc574859fa0c2ad0c8e59b9c1da.

**Comment by jiangty-addepar** [comment]
P.S. `mode = 'REFERENCE'` isn't documented :(

**Comment by jiangty-addepar** [comment]
Another thing that seems to be weird:

Say I use `mode = 'REFERENCE'` in the `export_file` definition, i.e.
```python
export_file(
  name = 'logback.xml',
  src = 'logback.template.xml',
  mode = 'REFERENCE',
  visibility = ['PUBLIC'],
)
```

Now, say I change the `export_file` target's name to `logback.xml.2` and update the reference in the definition of `//foo:bar_lib`. Buck does _not_ rename `utils/logback.xml` to `utils/logback.xml.2` inside the `bar_lib` jar! (In fact, it doesn't rebuild the jar at all.)

Buck correctly rebuilds the jar if `mode = 'COPY'`. Also, I have artifact caching disabled.

**Comment by jiangty-addepar** [comment]
I have a sort-of-workaround if I create a new jar
```python
java_library(
  name = 'logback',
  resources = ['//utils:logback.xml'],
  resources_root = './',
  visibility = ['PUBLIC'],
)
```

and add that jar to the dependencies. Kind of sad to do that though :(

**Comment by styurin** [comment]
`export_file` is going to be replaced by `filegroup`. The output of `filegroup` is placed in a directory so it wouldn't work for you. The solution is to use a genrule with output set to `logback.xml`, that genrule would copy the file from the original location.
