### ISSUE TITLE
Buck.pex is gigantic

### ISSUE THREAD

**Issue by shs96c** [facebook/buck#1642]
As of a705f2c5afbf395e6342c0b7c9e5b8f8d2d7ed10, the buck.pex weighs in at a healthy 97MB. This is somewhat chunky. Examining the pex and sorting the fields numerically, the big hitters are:

```
   485642  11-23-2017 23:10   programs/path_to_pex
  3571820  11-23-2017 23:10   programs/report_generator_jar
 17313603  11-23-2017 23:10   programs/external_executor_jar
 83408608  11-23-2017 23:11   programs/buck_server
```

Things like a full installation of jetty (including the servlet APIs) might contribute, two different HTTP client libraries (apache's and okhttp), and the surprisingly large `it/unimi/dsi/fastutil` package (used by `./src/com/facebook/buck/android/BUCK`) might be good starting places to begin looking in order to reduce the size of the beast.

**Comment by rmaz** [comment]
Is it possible to build a pex with functionality removed?

**Comment by styurin** [comment]
@rmaz what kind of functionality do you want to remove?

**Comment by rmaz** [comment]
Anything contributing significantly to the pex size that we do not use (eg the distbuild command). Just curious if it is easy to build without support for features that we do not use to help with keeping this binary small.

**Comment by ttsugriy** [comment]
Ideally buck should only provide a core and everything has to be configured separately as an extension, so unused functionality is free, but unfortunately we are still somewhat far from having extensions. More realistic may be using plugins to either have a configuration page where clients can use a checkbox to decide which plugins should end up in downloaded buck or shipping buck with minimum set of plugins and providing a way to download them using some mechanism like command or something else. @styurin, do you think it's realistic?

**Comment by styurin** [comment]
It's possible to disable some modules right now though I don't know how much of a win you would get from that. I started moving some features to modules, but it's mostly some languages that do not add a lot to the binary size.

Here's the list of modules: https://github.com/facebook/buck/blob/master/programs/BUCK#L87-L96 You can remove some of these modules if you don't use them and see how big is the difference.

**Comment by ttsugriy** [comment]
Yes, I suspect that android is the largest contributor in terms of binary size and is probably the hardest one to disable :(
