### ISSUE TITLE
Header-only libraries not included in `buck project --ide xcode` output

### ISSUE THREAD

**Issue by isundaylee** [facebook/buck#1644]
I am using two header-only C++ libraries (`cxxopts` and `json`) in my buck iOS project as two separate buck targets. I confirmed that the main iOS target which depends on these two library targets builds successfully with `buck build`. 

However, when I try to use `buck project --ide xcode` to generate a Xcode project file for the iOS target, I notice that these two header-only libraries are not included in the generated `.xcworkspace` file. All other dependency targets are included. This causes me to get `'json/json.hpp' file not found` error when I try to build the iOS target in Xcode. 

Any idea why those two header-only libraries might not be excluded in the generated Xcode workspace? Thanks! :)

**Comment by v-jizhang** [comment]
This issue is closed because there is no update in almost 3 years.
