### ISSUE TITLE
SIGPIPE is not available on Windows

### ISSUE THREAD

**Issue by barancev** [facebook/buck#1645]
Commit a271a23a24a63e88decba55e176d623717628719 introduced use of signals that are not Windows-compatible:
https://github.com/facebook/buck/commit/a271a23a24a63e88decba55e176d623717628719#diff-b484e7cff2cafb2d99d8825a35e1f10eR112

According to the docs [1]

> On Windows, signal() can only be called with SIGABRT, SIGFPE, SIGILL, SIGINT, SIGSEGV, or SIGTERM. A ValueError will be raised in any other case.

[1] https://docs.python.org/2/library/signal.html

**Comment by ttsugriy** [comment]
Thanks for reporting this, @barancev! @bertmaher, could you please take a look?

**Comment by bertmaher** [comment]
Sure, will fix on Monday.

**Comment by barancev** [comment]
Ping! Another monday is coming soon ;)

**Comment by ttsugriy** [comment]
@barancev , the issue should have already been resolved by https://github.com/facebook/buck/commit/a3b0fe723402e67a84eeb23d3f244d3f2e89846e. Are you still experiencing this issue?

**Comment by barancev** [comment]
Yes, fixed, thanks!
