### ISSUE TITLE
BUCK and cross compiling on different platforms

### ISSUE THREAD

**Issue by marekcirkos** [facebook/buck#1647]
Hey,
I want to use BUCK to cross compile code for Arduino. I made it work for OSX by overwriting compiling tools in `.buckconfig`, which works great. However I also need to make it work on different platforms e.g. Linux for CI etc. I can still use same tools etc, but paths and flags passed for cross compiling would be different. So my question here is: 
- How do you handle cross compilation for different platforms? 
- Do I need to create different `.buckconfig` for different platforms or there is better way of doing this?

**Comment by dreiss** [comment]
The way we do this at Facebook is to use different .buckconfig files, or use Buck's `@` argument syntax to easily pass options on the command-line.  For example, you could check in a file called `mode/arduino` that contains

```
--config
cxx.cxxflags="-std=gnu++14 -Os"
```

then compile with `buck build @mode/arduino //my:target` to get that configuration option set on the command-line.

What flags need to be different per-platform?  The include path locations?  For Android, we have native support for relocating the NDK, but another option is to just require the header files to be installed in a fixed location.

**Comment by marekcirkos** [comment]
That approach would work like a charm! Thank you.
