### ISSUE TITLE
Add support for using another target's output as input to a `prebuilt_native_library`.

### ISSUE THREAD

**Issue by plinehan** [facebook/buck#1649]
I have a `prebuilt_native_library` that I'd like to be based on an `exploded_zip` `remote_file`, but unfortunately `prebuilt_native_library` only supports literal file paths for the `native_libs` parameter.

It would be incredibly handy if `native_libs` supported referencing another target's outputs.

**Comment by plinehan** [comment]
If anyone knows of a comparable commit I could steal/borrow from I could take a swing at a PR for this.

**Comment by v-jizhang** [comment]
This issue is closed because there is no update in almost 3 yeras.
