### ISSUE TITLE
Support for Headers build phase

### ISSUE THREAD

**Issue by hongjaic** [facebook/buck#1652]
Hello,

I have been digging around for a while now to add Headers build phase when generating an xcode project. I'm doing this so that I can generate a project that I can use for creating a modular framework. Without the Headers build phase, build outputs don't have the headers and the modulemap in the right place.

Does buck already have a rule for adding Headers build phase? If not, is there a work-around?

Thanks.

**Comment by v-jizhang** [comment]
This issue is closed because there is no update in almost 3 years.
