### ISSUE TITLE
Set required C++ standard in platform/compiler independent manner

### ISSUE THREAD

**Issue by biasmv** [facebook/buck#1660]
I'm currently looking into replacing part of our cmake-based build system with buck. cmake has a feature called compile feature detection (https://cmake.org/cmake/help/v3.8/manual/cmake-compile-features.7.html) which allows to query/set certain compile features in a compiler and platform independent manner. In particular, I'm interested in setting the required standard (C++11, C++14, C++17) for c++ library targets. Does buck offer something similar? #1396 seems to suggest that it's not supported yet. Is this something that is planned?

**Comment by biasmv** [comment]
Is my understanding correct that currently C++ code can only be built with clang/gcc? If so, setting the standard is the same for all supported compilers. What I'm asking for will only become relevant once compilers that don't provide the same CLI interface as clang/gcc are supported.

**Comment by njlr** [comment]
One option is to apply a configuration file to your project. You can have a config file for each compiler you support. This is not _quite_ as automatic as what you describe, but it gives you lots of control. 

This discussion explains how configs can be used: https://github.com/facebook/buck/issues/1470
