### ISSUE TITLE
Buck Daemon should be restarted in certain scenarios

### ISSUE THREAD

**Issue by kageiit** [facebook/buck#1674]
There are several cases where keeping a buck daemon alive can cause issues and make the local build crash till we can run `killall java`

1. A new javac option is added to a DEFS that applies to all java targets
2. An annotation processor is updated
3. Buck version is updated

We handle the last case by killing all daemons in a wrapper script when we detect the buck version has changed. The fix is not very straightforward for the other cases. Daemons like Gradle handle this gracefully by spawning a new daemon for the set of java/project specific args passed in when starting a build. We should potentially look at building something into buck to handle these kind of cases by restarting the daemon or by spawning a new one.

**Comment by msridhar** [comment]
Perhaps less common, but daemon also needs to be restarted if an external `javac_jar` is changed
