### ISSUE TITLE
Is there a way to communicate with Buck package maintainers other than via Github?

### ISSUE THREAD

**Issue by jiangty-addepar** [facebook/buck#1676]
I tried joining `#buck` on freenode at some point, but it was dead. Is there an irc / Slack / etc channel that's used?

**Comment by ryu2** [comment]
We have a slack at https://buckbuild.slack.com/

**Comment by jiangty-addepar** [comment]
Wow, thanks! Was this posted anywhere that I should've seen?

**Comment by jiangty-addepar** [comment]
Oh, it looks like it's restricted to certain email domains; can an admin add the `@addepar.com` domain to the whitelist?

**Comment by sdwilsh** [comment]
Done.

**Comment by jiangty-addepar** [comment]
Thanks!

**Comment by mgrebenets** [comment]
Same here, the list of email domains is pretty restricting and I don't happen to own any of those :)
Is that list of domains limited to companies using Buck?

I guess adding `gmail.com` would be too much then.
In that case, could it be possible to add `@cba.com.au`?
We are looking into using buck and I have tons of questions to ask around :)
