### ISSUE TITLE
'./bin/buck build buck' failing on Mac OS X 10.9.5

### ISSUE THREAD

**Issue by thoughton** [facebook/buck#1677]
Hi,

I'm an interested new user, and I'm trying to install `buck` on Mac OS X 10.9.5.

Unfortunately I'm encountering an error during the `./bin/buck build buck` stage (which is a step that `Homebrew` performs, although I've not found any documentation about it specifically).

The error output appears as follows:
```
~/GitHub/buck$ ant

~/GitHub/buck$ ./bin/buck build buck

2017-12-13 19:13:49,745 [WARNING][buck_tool.py:398] Not using buckd because watchman isn't installed.
Build failed: Command failed with exit code 1.
stderr: ~/GitHub/buck/buck-out/gen/third-party/java/guava/guava#class-abi/guava-abi.jar(com/google/common/collect/Multimap.class):-1: warning: Cannot find annotation method 'value()' in type 'com.google.errorprone.annotations.CompatibleWith': class file for com.google.errorprone.annotations.CompatibleWith not found

~/GitHub/buck/buck-out/gen/third-party/java/guava/guava#class-abi/guava-abi.jar(com/google/common/collect/Multimap.class):-1: warning: Cannot find annotation method 'value()' in type 'com.google.errorprone.annotations.CompatibleWith'

~/GitHub/buck/src/com/facebook/buck/graph/MutableDirectedGraph.java:165: error: incompatible types: cannot infer type-variable(s) E
    Iterable<ImmutableSet<T>> immutableCycles = Iterables.transform(cycles, ImmutableSet::copyOf);
                                                                   ^
    (argument mismatch; ? super java.util.Set<T> cannot be converted to java.util.Collection<? extends E>)
Errors: 1. Warnings: 2.

    When running <javac_jar>.
    When building rule //src/com/facebook/buck/graph:graph.
Parsing buck files: finished in 4.3 sec (100%)
Creating action graph: finished in 1.2 sec (100%)
Building: finished in 53.8 sec (100%) 352/1350 jobs, 352 updated, 24.4% cache miss
  Total time: 59.3 sec

~/GitHub/buck$
```
The above is from manually trying to build a fresh checkout from GitHub, which gives the same error as when I try to install from `Homebrew`.

Here's some info about my system:
```
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.9.5
BuildVersion:	13F1911

$ uname -a
Darwin local 13.4.0 Darwin Kernel Version 13.4.0:
Mon Jan 11 18:17:34 PST 2016;
root:xnu-2422.115.15~1/RELEASE_X86_64 x86_64

$ ant -version
Apache Ant(TM) version 1.10.1 compiled on February 2 2017

$ python --version
Python 2.7.5

$ java -version
java version "1.8.0_31"
Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)
```
Is anyone able to help solve this problem I'm having? I'd very much like to give `buck` a try.

Please let me know if there's any other info that may be useful.  Thanks in advance!

**Comment by styurin** [comment]
Try to update java to the latest 8 version, 31 is quite old.

**Comment by thoughton** [comment]
Hi, thanks for the quick reply!

I've just updated to `"9.0.1"` but I'm now getting a different error...

However I've just re-read your reply and noticed you'd specifically said `"8"`, so should I ideally have stuck with `Java 8` rather than have taken the big step to `9`?

**Comment by styurin** [comment]
Yeah, we haven't migrated to Java 9, please, use the latest java 8.

**Comment by thoughton** [comment]
Ah great, installing `1.8.0_152` has allowed me to manually build successfully! :)

Unfortunately I still can't install via Homebrew though (which I think I'd prefer to do) as I think Homebrew is still trying to use Java 9, even though the rest of my environment is setup to use Java 8 - and I can't for the life of me work out how to tell it not to...

**Comment by thoughton** [comment]
OK I've gone with the simplest solution - I've just uninstalled Java 9 from my system, and now buck installs via Homebrew fine. :-)

I guess the problem could be that the buck Homebrew formula at https://github.com/facebook/homebrew-fb/blob/master/buck.rb lists its Java dependency as `"1.8+"`, whereas it sounds like it needs to somehow be `"1.8+ && <9"` - but I've honestly no idea whether Homebrew even supports the concept of `"maximum versions"` in its dependencies...

I'm happy close this issue now - thanks for your help!
