### ISSUE TITLE
Rust dependencies for iOS projects

### ISSUE THREAD

**Issue by michaeleiselsc** [facebook/buck#1678]
I've tried making an apple_library dependent on a rust_library, but the project's build steps don't include anything for rust. Is there any existing easy way to get iOS projects to build rust? If not, +1 for this as a feature.

**Comment by jsgf** [comment]
Yeah, that use-case hasn't come up here. I'm not sure what it would take - my gut feeling is that it shouldn't be too hard because they're all within the scope of C/C++/ObjC targets.

**Comment by michaeleiselsc** [comment]
yeah, you basically just need to build for the correct architectures, package it up with libtool and link it in at the end

**Comment by v-jizhang** [comment]
Rust is supported now.
