### ISSUE TITLE
Build stamping

### ISSUE THREAD

**Issue by shs96c** [facebook/buck#1687]
When releasing software to the public, it's useful to have the build tool somehow provide the following information in a "build stamp":

* Time of build
* Source control revision number (git or hg)
* Whether the tree was clean
* Who built it

Obviously, this information changes with every build. Fortunately, "things released to the public" are anything that `buck publish` can push (so `java_library` rules with maven coordinates), and any `*_binary` rule.

One way to do this may be a `post build` step where the artifacts pulled from cache or built locally are modified after the rule key is generated for them.

**Comment by shs96c** [comment]
For Java, it makes sense to put the build stamp in the manifest. That should be fine when building an binary from several publishable libraries --- we only need the information once, and for the most recent build.

**Comment by styurin** [comment]
We have the same problem in Buck where we add git information to the package. The problem with having this logic as part of Buck build is that we cannot express the state of the repository in the target graph. It seems that having this logic outside of a target graph is a better approach.
