### ISSUE TITLE
linux brew cannot build properly on Ubuntu 16.04

### ISSUE THREAD

**Issue by HsuanTingLu** [facebook/buck#1696]
error message:

$ brew update; brew upgrade buck

Already up-to-date.
==> Upgrading 1 outdated package, with result:
facebook/fb/buck 2017.11.16.01
==> Upgrading facebook/fb/buck 
==> Downloading https://api.github.com/repos/facebook/buck/tarball/v2017.11.16.01
Already downloaded: /home/Yoda/.cache/Homebrew/buck-2017.11.16.01.01
==> ant
Last 15 lines from /home/Yoda/.cache/Homebrew/Logs/buck/01.ant:
    [javac] 	                             ^^^^^^^
    [javac] Element cannot be resolved to a type
    [javac] ----------
    [javac] 218. ERROR in /tmp/buck-20171224-6503-ft34sc/facebook-buck-1531ce7/src/com/facebook/buck/module/annotationprocessor/BuckModuleVisitor.java (at line 173)
    [javac] 	return processingEnv.getElementUtils().getPackageOf(element).getQualifiedName().toString();
    [javac] 	       ^^^^^^^^^^^^^
    [javac] ProcessingEnvironment cannot be resolved to a type
    [javac] ----------
    [javac] 218 problems (218 errors)

BUILD FAILED
/tmp/buck-20171224-6503-ft34sc/facebook-buck-1531ce7/build.xml:479: The following error occurred while executing this line:
/tmp/buck-20171224-6503-ft34sc/facebook-buck-1531ce7/build.xml:411: Compile failed; see the compiler error output for details.

Total time: 2 seconds

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/facebook/homebrew-fb/issues

**Comment by ttsugriy** [comment]
which version of JDK are you using? Make sure you're using a recent version of JDK8.

**Comment by HsuanTingLu** [comment]
yes it is

' java -version' gets

java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

**Comment by JoakimCh** [comment]
I have the same problem on Debian 9.
Turns out linuxbrew installed JDK 9 and tried to use that. Solution was to download the .deb package instead.

**Comment by HsuanTingLu** [comment]
but my java is installed from Oracle not linuxbrew
(and this used to work

**Comment by JoakimCh** [comment]
I also have a Java installed by Debian on my system, but linuxbrew still installed another one without asking me about it. So are you really sure it didn't do that on your computer also? It should be in the "/home/linuxbrew/.linuxbrew/Cellar" folder I think, as "JDK" maybe.

**Comment by matthargett** [comment]
same issue on MacOS using homebrew installed cask/java.

**Comment by dread-uo** [comment]
It is still reproducible on Ubuntu 16.04

```
➜  ~ brew install facebook/fb/buck       
==> Installing buck from facebook/fb
==> Downloading https://api.github.com/repos/facebook/buck/tarball/v2017.11.16.01
Already downloaded: /home/litten/.cache/Homebrew/buck-2017.11.16.01.01
==> ant
Last 15 lines from /home/litten/.cache/Homebrew/Logs/buck/01.ant:
    [javac] 	                             ^^^^^^^
    [javac] Element cannot be resolved to a type
    [javac] ----------
    [javac] 218. ERROR in /tmp/buck-20180123-17675-44bouf/facebook-buck-1531ce7/src/com/facebook/buck/module/annotationprocessor/BuckModuleVisitor.java (at line 173)
    [javac] 	return processingEnv.getElementUtils().getPackageOf(element).getQualifiedName().toString();
    [javac] 	       ^^^^^^^^^^^^^
    [javac] ProcessingEnvironment cannot be resolved to a type
    [javac] ----------
    [javac] 218 problems (218 errors)

BUILD FAILED
/tmp/buck-20180123-17675-44bouf/facebook-buck-1531ce7/build.xml:479: The following error occurred while executing this line:
/tmp/buck-20180123-17675-44bouf/facebook-buck-1531ce7/build.xml:411: Compile failed; see the compiler error output for details.

Total time: 1 second

```

**Comment by HsuanTingLu** [comment]
in my original case, I dont have java installed by linuxbrew, which the method suggested by @JoakimCh works, imma close this one
