### ISSUE TITLE
buckd + watchman incorrectly thinks no files have changed

### ISSUE THREAD

**Issue by dborowitz** [facebook/buck#170]
Since upgrading to 620fdf494f66c2876cfc7cae6f6feb9d36e45df4, I've been observing intermittently that doing a `git rebase -i origin/master -x 'buck test'` will give me all cached test results on runs after the first, as if it's not detecting any files change. Replacing `buck test` with `buckd kill && buck test` produces the expected results, so I'm guessing it has to do with the buckd/watchman integration.

This is buck on Linux with watchman at 35466dc6e8cca28b0eedcdc4c67474fee806c3e8.

**Comment by Coneko** [comment]
I'm closing this as the issue has been resolved.

Follow ups are:
#172 to print warnings when the inotify limits are too low.
#330 to remove the need for users to configure `.watchmanconfig`.
