### ISSUE TITLE
Platform sources for Go

### ISSUE THREAD

**Issue by linzhp** [facebook/buck#1701]
Is there a way to have go_binary and go_library to include only the source files compatible with current platform (OS/arch)? The native `go build <package>` command does that automatically, but I don't know how to configure buck to have the same behavior.

For example, the following command shows the list of files included in `go build` when I am building the package:

`go list -f '{{.GoFiles}}' github.com/jessevdk/go-flags`

**Comment by nemith** [comment]
Not yet.   Internally at facebook we use a utility that generates the BUCK files and build rules using the `build` package, but this is useful only if you support a single platform.

Ideally some sort of source file filtering would be included into Buck, but doesn't exist yet.

**Comment by linzhp** [comment]
OK. We are planning to implement some improvement on this

**Comment by linzhp** [comment]
It turned out to be an easy config: if I specify directory name like  `srcs=['.']` of go_binary and go_library, then buck will behave like `go build <package>` and only build the files relevant to the current platform.

**Comment by linzhp** [comment]
`srcs=['.'] ` doesn't work.

**Comment by nemith** [comment]
Yes, the sources are just passed directly into the compiler.  The compiler itself doesn't do any filtering of files, all that is inside the `go` tool which buck bypasses.

You could wrap the compiler with a small go program that would take all source, inspect them and only pass the ones that match the current build context on.   Maybe it could be another step inside buck itself which would allow automatic cgo builds, etc as well.

**Comment by linzhp** [comment]
The native Go compiler does filter files. If you run `go build github.com/jessevdk/go-flags`, only source files in the package compatible with the current platform are included. I am trying to figure out how Buck turns that filtering off and how I can turn it on again. Any hint?

**Comment by nemith** [comment]
That functionality doesn't exist yet.  At facebook we wrote a small go utility that creates BUCK files with the correct files based off of build.Package (https://golang.org/pkg/go/build/#Context.Import)

Less than ideal but it works.  Buck doesn't inspect the contents of files so it cannot work the same as `go build`.
