### ISSUE TITLE
xcworkspace generated with buck project fails to build with apple_library containing Swift code

### ISSUE THREAD

**Issue by AttilaTheFun** [facebook/buck#1709]
Hi folks! I'm testing out Buck for a personal project written in Swift and it's pretty awesome. I'm able to build and run Swift projects from the command line in the simulator just fine. Unfortunately, the xcworkspace generated with `buck project` fails to build with the following error:

```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: /Users/lshire/Documents/myfork/bucksamples/cross-platform-scale-2015-demo/ios/DerivedData/BuckDemoApp/Build/Intermediates.noindex/ios.build/Debug-iphonesimulator/Example.build/Objects-normal/x86_64/Example.o (No such file or directory)
```

I forked the bucksamples repo and was able to reproduce the issue in the fork here:
https://github.com/AttilaTheFun/bucksamples
When you run `buck project demo_app_ios ide=xcode`, running the main target in the xcworkspace produces the above error, even though `buck install --run demo_app_ios` still works.

**Comment by mgrebenets** [comment]
UPD, the buck version is `2017.11.16.01`.

**Comment by mgrebenets** [comment]
I've done a bit more digging.

Firstly, some of the build settings in autogenerated `xcconfig`s have duplicated entries: #1777.
That's not a bug though.

Anyways, I've compared these build settings to build settings of a "vanilla" static library project created via Xcode. After experimenting with build settings, I finally discovered that the culprit for me is `-whole-module-optimization` flag in `OTHER_SWIFT_FLAGS`.

If I remove this flag the Xcode build will succeed.
Kind of sounds logical, `-whole-module-optimization` will cause Swift compiler to create one big whole module "Result.o" and not separate object files "Result.o" and "ResultProtocol.o".

But then, if I move this flag to where it belongs, that is to `SWIFT_OPTIMIATION_LEVEL` like so:

```c
SWIFT_OPTIMIATION_LEVEL = -O -whole-module-optimization
```

Then everything works fine again.

I think this is something that Apple changed in Xcode (I'm using 9.2) and buck hasn't caught up with the changes yet.
Another example, is upcoming changes in Xcode 9.3:

> The choice for compiling Swift code by file or by module moved from the Optimization Level
setting to Compilation Mode, which is a new setting for the Swift compiler in the Build Settings
pane of the Project editor.

From https://download.developer.apple.com/Developer_Tools/Xcode_9.3_beta_2/Release_Notes_for_Xcode_9.3_beta_2.pdf

I'm not sure how buck would solve this. 
Buck knows the user's Xcode version, either detecting it with `xcode-select` or by looking at `xcode_developer_dir`, so it should be possible to generate different `xcconfig` files based on Xcode version. 🤷‍♂️

**Comment by dinhviethoa** [comment]
cc @milend what's your opinion on it?

**Comment by milend** [comment]
If an `apple_library` has Swift sources, it needs a `swift_version = "4"` declaration, otherwise `buck project` won't work (there's certain logic that only kicks it once you've defined you want Swift support using that declaration).

Let me know if that fixes your issue.

**Comment by mgrebenets** [comment]
Hi @milend 

You pointed me in the right direction :)
The `-whole-module-optimization` is defined in my `.buckconfig`:

```ini
[swift]
  version = 4
  compiler_flags = -DBUCK -whole-module-optimization -enable-testing -suppress-warnings
```

That's how it ended up in generated Xcode project's `OTHER_SWIFT_FLAGS`.

I think I got this from AirBnB samples.

Removing the option fixes build issues in Xcode project.

I tried to add one more entry to build config like this

```ini
optimization = -whole-module-optimization
```

or this

```ini
optimization_level = -whole-module-optimization
```

It doesn't really help that Swift support is part of latest `buck` available in Homebrew, but is not documented on official https://buckbuild.com page :(

Do you know if there's a way to get latest documentation? Can I generate it from `buck` source maybe?

It's not related to the original issue, but I'd appreciate any help.

Thanks again for helping 👍

**Comment by milend** [comment]
@mgrebenets:
> Do you know if there's a way to get latest documentation? Can I generate it from buck source maybe?

The docs have not been updated, the most authoritative source of truth would be the examples included as part of the integration tests (e.g., `AppleLibraryIntegrationTest.java`) and `ProjectGeneratorTest.java` for the Xcode project generation.

@mgrebenets:
> None worked.

If you want to generate Xcode projects with WMO, you need to add the following to `.buckconfig`:

    [swift]
    project_wmo = true

Note that `buck build` will compile all Swift sources using a single compiler invocation, so there's no need to enable WMO there.

**Comment by mgrebenets** [comment]
Just giving an update on where I ended up here.
Firstly I figured out it's absolutely a must to use `swift_version` in `apple_library` rule. Not sure about `apple_test` but I added it there too.

Since I had a lot of buckfiles, I've added `DEFS` file with the following overrides:

```python

# TODO: Read this value from .buckconfig instead.
swift_version_from_config = '4'

original_apple_library = apple_library
def apple_library(
  name,
  swift_version = swift_version_from_config,
  **kwargs
):
  original_apple_library(
    name=name,
    swift_version=swift_version,
    **kwargs
  )

# TODO: Is this really required?
original_apple_test = apple_test
def apple_test(
  name,
  swift_version = swift_version_from_config,
  **kwargs
):
  original_apple_test(
    name=name,
    swift_version=swift_version,
    **kwargs
  )
```

To get Swift and Objective-C properly linked I had to add `-ObjC` flag to `linker_flags`:

```python
linker_flags = [
    '-ObjC',
]
```

Finally, I had to do the `***-Public-Swift.h` trick as well to use Swift code in Objective-C tests.

Here's the sample project:
https://github.com/mgrebenets/buck-mix-n-match

There's more to do yet, e.g. set all optimizations to "none" for Debug configuration to be able to debug code properly, etc.
