### ISSUE TITLE
buckversion checking no longer happening

### ISSUE THREAD

**Issue by michaeleiselsc** [facebook/buck#1733]
Hi, I was curious why .buckversion checking was no longer happening in new versions of buck. It's important to my team to synchronize our buck versions to have reproducible builds.

**Comment by kageiit** [comment]
@michaeleiselsc if its important for your team to synchronize buckversions, you should consider moving to prebuilt buck binaries instead. Buck publishes releases on github now, you can also fetch buck built at any git sha from [jitpack](https://github.com/facebook/buck/pull/1712) like `https://jitpack.io/com/github/facebook/buck/<buck-repo-git-sha>/buck-<buck-repo-git-sha>.pex`

The logic to download buck should be administered via a wrapper script [example](https://github.com/uber/okbuck/blob/master/buckw#L184). The logic was removed from buck originially as it adds overhead to always check the buck version against the git in the source copy.

**Comment by michaeleiselsc** [comment]
Got it, thanks!

**Comment by kageiit** [comment]
@michaeleiselsc feel free to close the issue :)
