### ISSUE TITLE
Documentation is outdated, is it time to start worrying

### ISSUE THREAD

**Issue by mgrebenets** [facebook/buck#1737]
Hi there.

I've noticed that official documentation on https://buckbuild.com is outdated.
For example, iOS rules like `apple_binary` and `apple_test` have no mention of options like `configs`, `bridging_header` and so on.

I don't want to sound too dramatic, but is it time to start worrying that `buck` may end up like `FBSnapshotTests`?
It seems like I'd have to browse source code to find out all possible configuration options.

**Comment by sdwilsh** [comment]
Buck has historically not documented things that are not stable or the 
project isn't sure it won't likely change in the future.  Basically, if 
it's not documented, you can use it, but the API may change in the future.
