### ISSUE TITLE
Writing custom test rules

### ISSUE THREAD

**Issue by sk-** [facebook/buck#174]
In #150 I asked for a `gentestrule` and @bolinfest pointed me to `sh_test`, however as replied there, it only works for very specific use cases. And there are many missing pieces to successfully use this in a general scenario.

Currently `sh_test` only allows you to run an executable with no arguments, so its very limited when compared to the `sh` option of a `genrule`, as one does not even have access to the dependencies or sources. One workaround for this would be to create a function that first calls a `genrule`and then calls `sh_test` on the result (although even that requires some awful work as sh_test does not take any arguments). 

Additionally there's no way to pass the arguments of buck test to the underlying executable. The options that are very important to be able to pass to the tests, are: --code-coverage, --filter, --test-selectors and --dry-run. For the boolean options, a possible solution would be something like $(if-code-coverage --with-coverage), where that string will translate to --with-coverage only if the --code-coverage option was specified. That method could also work for non boolean options. In addition non boolean options values could be accessed with something like $(filter).

Then one could write the sh option like:
sh = 'test_exe $(if-coverage --with-coverage) $(if-filter --test-filter=$(filter))'

And finally the output of a `sh_test` in case of failure is quite different to the one of a java test. It just prints the stdout and stderr with a separator. Instead it would be much nicer if one could generate the output of the test in a specific way such that `BUCK` understands it and the output is normalized across all tests.

ps: I resubmit this with some more information as the other issue was closed even though `sh_test` is not enough for my use case.

**Comment by sk-** [comment]
Thanks, for pointing that out. However, I still think that having a `gettestrule` as detailed above will certainly make `BUCK` much more powerful.

The problem with `python_test` is that it does not understand test filters or provide code coverage. additionally it is  bound to the unittest runner. But what if I would like to allow `pytest` tests?

Also, what if I want to support test for an unsupported language like `Javascript`, or even `D` as `flint` requires?

**Comment by sdwilsh** [comment]
I'm not necessarily opposed to `gentestrule`, but I don't think it's something we're planning to do any time soon.  @shs96c has talked about an extension API in the past that would allow for folks to implement unsupported things more easily, but it hasn't been a big priority for us to implement.

**Comment by sdwilsh** [comment]
Upon further thought, we don't want to support this.  There are too many nobs and dials to support in a generic way, and it'd be much better to either a) support specific test rules that are needed, or b) have an extension API that could implement rules.

**Comment by RemiTorracinta** [comment]
Has the priority of an extension API changed?  My organization has hundreds of pytest unit-tests, and this is a bit of a blocker for switching over.
