### ISSUE TITLE
Python_library does not generate output

### ISSUE THREAD

**Issue by sk-** [facebook/buck#176]
The `python_library` does not generate any output so it is not possible to use it as a dependency in custom made rules. For example one could think of repacking `python_library`s as an appengine package or as package ready to upload to pypi.

This is also required if one wants to write a rule for testing python.

**Comment by sdwilsh** [comment]
@shs96c, possibly, yeah, although we wouldn't want to produce that as part of a build unless this was what you targeted.

**Comment by v-jizhang** [comment]
Sorry we haven't update this issue for more than 3 years. At this point, we are closing this because it is quite out of date and it is not clear if the issue still exists. Please create a new one if you still see the problem. Thank you.
