### ISSUE TITLE
Rules for aars are too strict

### ISSUE THREAD

**Issue by hzsweers** [facebook/buck#1775]
Currently, Buck operates on the rules defined here: https://developer.android.com/studio/projects/android-library.html#aar-contents

It seems though, in practice and from talking to some devrel on play services, this is not actually a hard spec. Play services 11.8.0 for example has AARs that don't have resources (and subsequently no `/res` dir. Buck currently fails hard on this, and I think should be relaxed.

**Comment by kageiit** [comment]
Fixed by #1778

**Comment by kageiit** [comment]
I think we can close this as the pr has merged
