### ISSUE TITLE
OpenJDK

### ISSUE THREAD

**Issue by Mehran-Abghari** [facebook/buck#1786]
Hello
I'm using Ubuntu Budgie 17.10 and installed OpenJDK, I want to use Buck as build tools, I must install Oracle JDK ? or i can use OpenJDK ?
Thanks

**Comment by kageiit** [comment]
OpenJDK should work fine

**Comment by ttsugriy** [comment]
@Mehran-Abghari, both JDKs should be supported as long as they are JDK8, since Java 9 is currently not supported.
