### ISSUE TITLE
Binary bloat

### ISSUE THREAD

**Issue by brettwooldridge** [facebook/buck#1793]
Anyone have a clear explanation for the bloating of the buck binary?

* ``v2017.05.31.01`` - 58.4 MB
* ``v2017.09.04.02`` - 78.5 MB
* ``v2017.10.01.01`` - 82.6 MB
* ``v2018.02.16.01`` - 90.6 MB

**Comment by kageiit** [comment]
Time to run proguard on buck? :)

**Comment by ttsugriy** [comment]
a lot of bloat is coming from d8 and fastutil :( Hopefully one day we'll be able to drop support of android once it can be implemented with extensions.
```
du -h third-party/java/fastutil/fastutil-7.2.0.jar
 17M	third-party/java/fastutil/fastutil-7.2.0.jar
```

Ironically d8 itself is way smaller
```
2.2M	third-party/java/d8/d8.jar
```

**Comment by ttsugriy** [comment]
after removing some unnecessary deps from testrunner current binary size is ~86M. I don't see an easy way to significantly shrink it without dropping support for some of android features :(

**Comment by ttsugriy** [comment]
btw, running proguard when creating dx jar to remove all unnecessary classes from fastutil would probably help a lot
