### ISSUE TITLE
"Android NDK is not configured properly" even though it is SDK which is missing

### ISSUE THREAD

**Issue by dmitry-zaitsev** [facebook/buck#1798]
Steps to reproduce:

- Define a valid `ANDROID_NDK_REPOSITORY` environment variable.
- Make sure `ANDROID_SDK` (or any other variable which points to the SDK) is not defined.
- Try to build the sample project (`demo_app_android`). Get error `BUILD FAILED: No native platforms detected. Probably Android NDK is not configured properly.`
- Define a valid `ANDROID_SDK` variable.
- Try to build the sample project. It works.

Some context - I was trying to fix the issue by setting `ndk_path` in `.buckconfig` without any result just to find out that my SDK path was actually not set.

**Comment by styurin** [comment]
Cannot reproduce, it shows an error about SDK:

```
BUILD FAILED: Android SDK could not be found. Make sure to set one of these environment variables: ANDROID_SDK, ANDROID_HOME, or android.sdk_path in your .buckconfig
```

We did a few changes around that logic and it probably fixed the problem.
