### ISSUE TITLE
@classpath and @classpath_abi macros do not produce deterministic output when the project root moves

### ISSUE THREAD

**Issue by kageiit** [facebook/buck#1800]
Repro: 
[repro.zip](https://github.com/facebook/buck/files/1795519/repro.zip)

Unzip the repro zip, There are two folders `repro1`and `repro2`. In each folder run

`buck build //:bar`

Compare the output of the file in `buck-out/tmp/genrule-****.sh`. Observe that the `.macro` file is named differently in both cases.

<img width="1432" alt="screen shot 2018-03-08 at 7 17 32 pm" src="https://user-images.githubusercontent.com/291148/37188714-61ae6c4e-2305-11e8-8170-037202e3a64f.png">

This leads to cache key inconsistencies (compared using `scripts/diff_rulekeys.py`)
```
buck run //scripts:diff_rulekeys ~/Desktop/repro/repro1/buck-out/log/last_buildcommand/buck.log ~/Desktop/repro/repro2/buck-out/log/last_buildcommand/buck.log //:bar
Building: finished in 0.0 sec (100%) 3/3 jobs, 0 updated, 0.0% cache miss
  Total time: 0.0 sec
Loading /Users/kage/Desktop/repro/repro1/buck-out/log/last_buildcommand/buck.log
Loaded 12 rules
Loading /Users/kage/Desktop/repro/repro2/buck-out/log/last_buildcommand/buck.log
Loaded 12 rules
Comparing rules...
Change details for [//:bar->bash->args]
  (prefix):
    -[string("9fcf53043744dfddd5071259dba6b15218b5ab14b9caf276add68bc76fbd97be")]
    +[string("33a6da1c6558cc4d557b56e8886615743cd233c872b92f36f78bf03fe4a56094")]
```

This is especially problematic if cache population CI jobs do not setup the repo in the same path

**Comment by kageiit** [comment]
This seems to affect all macro expanders that use `WriteToFileArg`

**Comment by kageiit** [comment]
cc @styurin @ttsugriy @cjhopman

**Comment by ttsugriy** [comment]
I think an easy and a reasonable way to handle this is to use a content hash instead of a temporary file https://github.com/facebook/buck/blob/1ca7183e88f987e6e616fc88c106ccf158a252a1/src/com/facebook/buck/rules/args/WriteToFileArg.java#L53

**Comment by cjhopman** [comment]
Are the stringified args being added to the rulekey? That doesn't seem right.

**Comment by ttsugriy** [comment]
doh, but the rulekey differs is explicitly saying that the problem is with `prefix`, which is a hash of inputs and a class name. I'm going to check that instead.

**Comment by ttsugriy** [comment]
thanks to @kageiit's data we've established that the problem is actually caused by macro inputs being non-determinstic - most likely due to usage of absolute paths.

**Comment by cjhopman** [comment]
Ok, here's what happens:
https://github.com/facebook/buck/blob/master/src/com/facebook/buck/rules/args/WriteToFileArg.java#L35 adds prefix to rulekey
https://github.com/facebook/buck/blob/master/src/com/facebook/buck/rules/macros/AbstractStringWithMacrosConverter.java#L124 computes that including the macro hashCode()
https://github.com/facebook/buck/blob/master/src/com/facebook/buck/rules/macros/AbstractClasspathAbiMacro.java is a BuildTargetMacro. It's hashCode is then just basically target.hashCode();
https://github.com/facebook/buck/blob/master/src/com/facebook/buck/model/AbstractBuildTarget.java#L50 will include the unflavored buildtarget's hashCode
https://github.com/facebook/buck/blob/master/src/com/facebook/buck/model/AbstractUnflavoredBuildTarget.java#L71 includes the absolute path of the cell in its hashCode.
