### ISSUE TITLE
Buck's ClassUsageTracker marks more files as used than necessary for compilation in some cases

### ISSUE THREAD

**Issue by kageiit** [facebook/buck#1801]
When running tools like error prone or other javac plugins, there can be cases where classes can be loaded for performing error checks etc. These classes are loaded outside the parse/enter and annotation processing phases and are not really required for compilation i.e their presence/absence does not change the compiler output.

This leads to buck marking more classes as used than necessary leading to targets being invalidated more than necessary.

One way to deal with this would be to stop class usage tracking just before the analyze and generate phases run. Open to hearing other ideas as well

**Comment by kageiit** [comment]
cc @jkeljo @styurin

**Comment by jkeljo** [comment]
Hmmm...it might not change the output, but could it change the result? I.e., might error prone fail the build in response to a change in one of those otherwise-unnecessary classes?

**Comment by kageiit** [comment]
error prone will not fail the build. We tested by removing all the deps that were being marked as used but not actually necessary and javac ran correctly with error prone enabled

**Comment by kageiit** [comment]
Also, loading classes that are not actually required during parse/enter and annotation processing whether via errorprone or any javac plugin is something we should not allow/avoid

**Comment by kageiit** [comment]
If such classes are really needed, then they can be put on the processorpath

**Comment by jkeljo** [comment]
Do you know why error-prone is loading these things? Is it doing any analysis on them that could result in it outputting errors?

Eventually I think the used-classes stuff should move to a language-level analysis rather than its current expedient implementation, but if EP is doing some transitive data flow analysis or something that could throw a wrench in things.

**Comment by kageiit** [comment]
Its our custom checkers, not EP's own checkers that are loading annotations on types and checking if they extend other types etc.

**Comment by jkeljo** [comment]
Unfortunately I don't think stopping before analyze works...the compiler will read classes during that phase that it hasn't read before. Stopping before generate might be OK.

**Comment by kageiit** [comment]
Makes sense. We will audit our custom checkers to see if we can remove this extra loading of classes. If we cannot stop before analyze, it might be tricky to exclude loads by just ep and its checkers. Will report back
