### ISSUE TITLE
New gradle2buck script: read a build.gradle config and generates a Buck config skeleton

### ISSUE THREAD

**Issue by maxme** [facebook/buck#181]
Since Android Studio exists, a lot of Android projects have converted their old ant / maven project to use the gradle build system. To be honest, it's a pain in the ass to switch to Buck when you have a relatively big Android project that is already building with gradle. One thing that could help: a `gradle2buck` script that read for well known definition and calls to the android-gradle plugin in a build.gradle file and spouts out a Buck config skeleton (.buckconfig and BUCK files), plus a bucklets to help with basic gradle tasks (like fetch a .jar from maven central).

Ref: https://github.com/facebook/buck/issues/64

**Comment by st-f** [comment]
:+1: Seconding

**Comment by facebook-github-bot-9** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by maarek** [comment]
Would love to have an update on this!

**Comment by sdwilsh** [comment]
Nobody on the core team is working on this currently, but we'd be happy to help someone put together a pull request.

**Comment by Cococ** [comment]
how can I use it ?

**Comment by Piasy** [comment]
Maybe this gradle plugin? [OkBuck](https://github.com/Piasy/OkBuck).

OkBuck is a gradle plugin, aiming to help developers utilize the super fast build system: BUCK, based on the existing project with Android Studio + gradle, and keep both build systems work, with less to only 10 lines of configuration.

**Comment by ashu-22** [comment]
So What should we contribute to this thing!
