### ISSUE TITLE
Variables in .buckconfig

### ISSUE THREAD

**Issue by leandroBorgesFerreira** [facebook/buck#1814]
Hi, 

I am trying to implement distributed cache and I would like to to pass variable in the .buckbuild. A environmental variable would be great in this file. Is it possible?

Thanks!

**Comment by ttsugriy** [comment]
I'm not sure what you mean by passing a variable in the `.buckbuild`. You probably meant `.buckconfig` instead. In any case environment variables are super evil and should never be used. That's exactly the reason why buck uses `.buckconfig`. You can pass a value using `-c your_section.your_key=your_value` and read it from BUCK file using https://buckbuild.com/function/read_config.html or from Buck using `com/facebook/buck/config/BuckConfig.java`

**Comment by leandroBorgesFerreira** [comment]
Hi, ttsugrly. You're right, I meant buckconfig. This `buckconfig` is very good, but I would like to use a token for auth to use distributed cache and insert the token directly in the `buckconfig` did not seam to be the correct option. 
I would like to pass a value an read it in the .buckconfig, not in the BUCK file. Like this:

```
[cache]
  mode = http
  http_url = http://localhost:6457
  http_mode = readwrite
  http_write_headers = Authorization: $MY_TOKEN_HERE 
```

**Comment by leandroBorgesFerreira** [comment]
This answer was pointed to me bu @kageiit at Slack. 

One can use: `buck build foo --config cache.http_write_headers=$MY_TOKEN`

**Comment by ttsugriy** [comment]
oh I see. Some also use `.buckconfig.local` to pass configuration options, but `--config` is definitely more preferable
