### ISSUE TITLE
Parameterized Java tests cannot be run with `--filter`

### ISSUE THREAD

**Issue by collenjones** [facebook/buck#1822]
If a Java test class has parameterized tests, `--filter` can only filter up to the test class, not down to specific test methods.

Runs all tests in the class:
`buck test //:test-target -f ParameterizedTestClass`

Filtered test method `testMethod` will not be run:
`buck test //:test-target -f ParameterizedTestClass#testMethod`

**Comment by ttsugriy** [comment]
I'm pretty sure it's by design and is because JUnit Parameterized infra gives strange test methods. You can read more about how parameterized test classes are named in https://www.javacodegeeks.com/2013/04/junit-naming-individual-test-cases-in-a-parameterized-test.html
