### ISSUE TITLE
Android KAPT in-process compilation class loader conflict

### ISSUE THREAD

**Issue by eggman87** [facebook/buck#1829]
While testing new KAPT support in buck (alongside [okbuck](https://github.com/uber/okbuck)), I came across a issue that surfaced due to my Android project using Butterknife. 

While running a build, a exception happens during kotlinc:  
```
error: [kapt] An exception occurred: java.lang.AssertionError: java.lang.ClassCastException: com.sun.tools.javac.api.JavacTrees cannot be cast to com.sun.source.util.Trees
    at com.sun.source.util.Trees.getJavacTrees(Trees.java:84)
    at com.sun.source.util.Trees.instance(Trees.java:73)
    at butterknife.compiler.ButterKnifeProcessor.init(ButterKnifeProcessor.java:124)
```

After some research, it appears this is due to a classloader conflict when running kotlinc "in-process". The same issue actually happened in the kotlin gradle plugin ([issue link](https://youtrack.jetbrains.com/issue/KT-20233#comment=27-2788056)) and was fixed by the kotlin team in [this commit](https://github.com/JetBrains/kotlin/commit/a1939c093c8c87f7f0c5e899c2a8e6e40448d8b0). 

Butterknife internally has a dependency on the JDK tools jar, which is where the classes in conflict are coming from. 
`compileOnly files(org.gradle.internal.jvm.Jvm.current().getToolsJar())`

Project Setup:
- mixed java/kotlin android project. 
- used local builds of buck and okbuck with the latest kapt support. 

Going to investigate further and see if I can help come up with a fix, but I am pretty green with Buck/OkBuck and was just investigating usage on our Android project now that kapt is officially supported. Any direction or guidance will be much appreciated. 

**Note:** there is a sample project that demonstrated the issue with gradle located at https://github.com/damianw/KaptInProcessBug I am going to create a sample that uses okbuck and update this issue once it is on github.

**Comment by bobyangyf** [comment]
We do not encourage doing this in process.
This really should be done out of process, to avoid complications.
