### ISSUE TITLE
[Bug]Broken support for android ndk build when deal with arm64

### ISSUE THREAD

**Issue by gengjiawen** [facebook/buck#1836]
If you want to build arm64 with armeabv7a, you have to set  `app_platform = android-21`  above.

Repro repo: https://github.com/gengjiawen/android-jsc/tree/feature/abi_support.

Suggest fix: when deal with arm64, automatically use `android-21`, in other case, use `android-16` or something like that.

**Comment by sdwilsh** [comment]
Doesn't this have other implications?  I have concerns if the user specifies that they want `android-16`, but then Buck decides they really want something different.

It's quite possible that we should just bump up the default from `android-16` (which is pretty old), but I think morphing what was requested to something else is an approach that doesn't fit with how Buck generally works.

**Comment by sdwilsh** [comment]
You are still doing what I said, but for a small subset of options.  It would likely be better to provide a descriptive error message to the user telling them they need to be on `android-21` or newer.  Otherwise, if someone builds their application with Buck, they'll ship their native code with different `android` targets, which could introduce other non-obvious problems.

**Comment by LegNeato** [comment]
RN doesn't want to bump wholesale to 21. I think the risk is acceptable as Google is forcing it.

**Comment by sdwilsh** [comment]
I know it says `Owner` next to my name, but that's just because I am an admin to the facebook organization here on GitHub.  My comments here aren't authoritative, and someone who actually works on Buck should make the call here.

**Comment by gengjiawen** [comment]
Let's put it in another way. If without buck, we build native module using Android.mk and Application.mk or cmake and gradle to get arm64 support, do I have to set app_modules to android-21 ?

Nope.

The reason arm64 need android-21 to build is because with 21 we have arm64 support.

An example you can see is [fresco](https://github.com/facebook/fresco). It supports Android 2.3 (Gingerbread) and later with arm64 support.

**Comment by gengjiawen** [comment]
It can be a solution. A fix to this is all I needed.

**Comment by gengjiawen** [comment]
@styurin Any action on this issue ?

**Comment by styurin** [comment]
As I said in #1843 we shouldn't change the configuration and instead let user know that the configuration is incorrect.

**Comment by gengjiawen** [comment]
Did you have looked the discussion in this issue ? I think the configuration is correct. It's buck which handle the build wrong.

**Comment by styurin** [comment]
Again, we are not going to have any kind of magic logic in Buck that would change the configuration from what's defined in `.buckconfig`. If this configuration is not flexible enough you can add additional options, for example, platform level by ABI.

**Comment by gengjiawen** [comment]
> If this configuration is not flexible enough you can add additional options, for example, platform level by ABI
Can you be more specific, in this way can I still have one aar with multi abi in it.
