### ISSUE TITLE
Significant performance regression in 005dd2a03

### ISSUE THREAD

**Issue by sheldonneuberger** [facebook/buck#1838]
This commit 005dd2a03a634e5f38eb5ab2ac680c77448a287e regresses a large iOS build of mine from total elapsed time ~12:30 to ~16:30. There's also something in the earlier range 145f10a7d6..ace7495dd (26 commits) that regresses the build from ~10:00 to ~12:30. It looks like most of these commits were made on the same day as part of a larger change.

This is with dir cache on and http cache off, on a mac pro running 24 threads.

Any ideas on what's happening here? Tagging @cjhopman because he's the author of most of those commits.

**Comment by styurin** [comment]
@cjhopman

**Comment by cjhopman** [comment]
I think we'd need more information, we haven't seen any such regression on very large iOS builds and I don't really see how this would cause such a regression.

Could you compare (or even better, share) build traces from these builds to get some better idea of what regressed?
