### ISSUE TITLE
How to print from buck file ?

### ISSUE THREAD

**Issue by aneesv** [facebook/buck#184]
How to print any custom messages to terminal from buck file ? Also is it possible to get terminal output as static (line by line) instead of real time out put on a single line

**Comment by nickdai** [comment]
output_file = open("/tmp/my_output_file", "a")  # note "a" for append mode
output_file.write("some stuff\n")

this work, thanks!

but how to print the value of  variable? 
eg: "$ANDROID_HOME",  

when I try to print it ,  failed :
 
output_file.write($ANDROID_HOME)
                      ^
SyntaxError: invalid syntax

**Comment by saleeh93** [comment]
You can use this simple hack,I am pretty sure there will be better ways,
For now you can try this

```shell
import os;
output_file = open("out", "a") # note "a" for append mode
output_file.write("some stuff\n")
output_file.write(os.popen('echo $PATH').read())

**Comment by nickdai** [comment]
@saleeh93 @oconnor663  
I am very curious why BUCK don't support "print" ,since it is based on Jython.

**Comment by saleeh93** [comment]
@nickdai In my experience,It support print but we can't see output,
Well said by @oconnor663 
> When buck executes the Python code in a BUCK file, that code prints JSON to stdout, which buck reads as build rules. So if you print inside of a BUCK file, you won't see the output, and you will probably confuse the JSON parser and cause errors. Printing to stderr should work though. You could also create a temporary file, have your Python code append to that, and tail -f it from another terminal. Bear in mind that your Python code will run when the build files are parsed, not when the build is actually happening.

**Comment by nickdai** [comment]
@saleeh93  
I understand, thanks for your answer.
