### ISSUE TITLE
buck daemon hangs trying to cleanup dir artifact cache

### ISSUE THREAD

**Issue by kageiit** [facebook/buck#1842]
After a buck command, the daemon hangs for a period of time before returning control of the shell back to the user. Yourkit says there is a potential deadlock

```
Potential deadlock: frozen threads found

It seems that the following threads have not changed their stack for more than 10 seconds.
These threads are possibly (but not necessarily!) in a deadlock or hung.

NGSession 1: com.facebook.buck.cli.Main (NGCommunicator reader) <--- Frozen for at least 21s
com.martiansoftware.nailgun.NGUnixDomainSocketLibrary.read(int, ByteBuffer, int) NGUnixDomainSocketLibrary.java (native)
com.martiansoftware.nailgun.NGUnixDomainSocket$NGUnixDomainSocketInputStream.doRead(ByteBuffer) NGUnixDomainSocket.java:125
com.martiansoftware.nailgun.NGUnixDomainSocket$NGUnixDomainSocketInputStream.read() NGUnixDomainSocket.java:98
java.io.DataInputStream.readInt() DataInputStream.java:387
com.martiansoftware.nailgun.NGCommunicator.readChunk() NGCommunicator.java:327
com.martiansoftware.nailgun.NGCommunicator.lambda$null$0() NGCommunicator.java:124
com.martiansoftware.nailgun.NGCommunicator$$Lambda$12.call()
java.util.concurrent.FutureTask.run() FutureTask.java:266
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor$Worker) ThreadPoolExecutor.java:1149
java.util.concurrent.ThreadPoolExecutor$Worker.run() ThreadPoolExecutor.java:624
java.lang.Thread.run() Thread.java:748
```

cc @msridhar @sbalabanov @styurin

**Comment by sbalabanov** [comment]
Didn't it show the same before the upgrade? socket.read() is a blocking operation and supposed to 'hang'

**Comment by kageiit** [comment]
We are seeing it hang for several seconds. Is that expected? Was not sure if its related to the update or not

**Comment by sbalabanov** [comment]
What I meant is that YourKit is probably wrong detecting that the issue is in socket.read() operation. So the issue might be somewhere else.
If that happens after the build completes, then there might be several reasons for that, let me list a few
- Deinitialization of thread pools (various executors) may be time consuming
- If build results in error, Buck closes event listeners and output traces synchronously and that may be time consuming

It is hard to say without having your particular case in hands, I would probably look at the YourKit data but only for the afterbuild portion. It will probably require instrumentation, not sampling, method to get right data.

**Comment by kageiit** [comment]
The hang does not seem to be because of nailgun. I traced the buck daemon with truss and it seems to be stat'ing tons of files in the dir artifact cache. Looking at the config, the machine seemed to have reached the limit at which it tries to cleanup

https://github.com/facebook/buck/blob/master/src/com/facebook/buck/artifact_cache/DirArtifactCache.java#L62

but it is unable to do so since the cleanup has a very short timeout and the operation never completes

This seems to be related to #803

**Comment by kageiit** [comment]
Running the build command with `./buckw build foo --config cache.mode=""` got rid of the problem, but this should be handled more gracefully by buck. It should atleast print some log that disk log cleanup is happening

**Comment by kageiit** [comment]
After attaching the debugger, the buck jvm goes into https://github.com/facebook/buck/blob/3730801723060665c4cb766bc24aa206251949fc/src/com/facebook/buck/util/DirectoryCleaner.java#L52

But is killed and never enters the loop

**Comment by sbalabanov** [comment]
So what is happening here is that at the end of each command, dir artifact cache is closed and it tries to clean dir cache by removing last accessed file. To do so, it traverses dir cache directory and stats each file there (in fact it stats each file twice, on traversal first and in a cleaner second). In case of a big directory this can be really slow. It then sorts all files by date accessed and removes oldest file until a threshold is met.

It tries to do it asynchronously by executing ArtifactCaches.close() on a separate executor service, but in fact Buck still waits for the service to complete all tasks before returning control to the user.

As a short term solution we can try to find a way to walk directory tree without stat, currently it uses Files.walkFileTree(). I doubt we can do it as traversal itself wants to know if the entry is a file or directory.

A longer term solution is to have Buck support post-command asynchronous tasks and submit cleaner job there, not doing anything on artifact cache shutdown.

A quickfix solution may be to totally purge dir cache folder and limit it's size.

cc @bobyangyf

**Comment by kageiit** [comment]
@sbalabanov do folks at FB not use the disk cache?

"A quickfix solution may be to totally purge dir cache folder and limit it's size." Is not something that can be easily rolled out across all dev laptops without friction.

Can someone point us in the right direction where we can add the post-command workflows? We would be happy to make a PR

cc @styurin

**Comment by sbalabanov** [comment]
@kageiit they do but for some reason this is not that of a problem. May be faster drives?

Buck right now is pretty vague in scheduling cleanup jobs - each function does it on its own way. What we want to have instead is a unified piece of infrastructure with some sort of API that allows functions to submit cleanup jobs to daemon in a more less unified and supported way, and close all the resources synchronously. This in in plans for Buck team but at the moment we are not giving it a top pri, still happy to accept a PR, though it's probably be a set of PRs most likely.

Another short fix might be to move executor service timeout to configuration then increase the value in your case:
https://github.com/facebook/buck/blob/012a59d5d2e5a45b483e85fb190d2b67ea0c56ab/src/com/facebook/buck/cli/Main.java#L246
Actually, I'd rather introduce a brand new setting for io executor service, not reuse this one.

**Comment by sbalabanov** [comment]
I am happy to accept a PR, please include relevant comments in the code.

**Comment by sbalabanov** [comment]
You will still have to close an executor and increase timeout.
