### ISSUE TITLE
Missing source files does not fail a build

### ISSUE THREAD

**Issue by R1kk3r** [facebook/buck#1846]
I am just playing with macro that wrap some cxx_library. When a cxx_library contains source files that does not exist, the target is "built" (nothing is built but it appears like a successful build) without any errors. It is a bit confusing, it is the same behaviour as when a target is up-to-date and nothing need to be rebuilt. Is it expected? Why not failing the build and telling the user about an invalid path inside the source files?

**Comment by andrewjcg** [comment]
This isn't expected and Buck should fail the build when input sources do not exist.  Do you have a an example/repro you can paste/post?

**Comment by andrewjcg** [comment]
Ah, that makes sense.  FWIW, there is a (apparently undocumented) `[build] allow_empty_globs = false` config setting which will fail when globs do not evaluate to any sources.
