### ISSUE TITLE
Server disconnected unexpectedly.

### ISSUE THREAD

**Issue by artem-zinnatullin** [facebook/buck#1854]
After updating Buck https://github.com/facebook/buck/compare/996fc3c1f0c6415477cbbf76aea005286dc4d6ab...02e709184fbd0534817c1e73f7db71b13093e4dd I'm observing CI build errors with following log:

```console
[ERROR][buck.py:173] Server disconnected unexpectedly: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File ".okbuck/cache/buck_binary/buck-d6c66ee7d0.pex/programs/buck.py", line 147, in <module>
  File ".okbuck/cache/buck_binary/buck-d6c66ee7d0.pex/programs/buck.py", line 134, in main
  File ".okbuck/cache/buck_binary/buck-d6c66ee7d0.pex/programs/buck_tool.py", line 408, in launch_buck
    if running_version != buck_version_uid or not self._is_buckd_running():
  File ".okbuck/cache/buck_binary/buck-d6c66ee7d0.pex/programs/buck_tool.py", line 615, in _is_buckd_running
    c.send_command('ng-stats')
  File ".okbuck/cache/buck_binary/buck-d6c66ee7d0.pex/pynailgun/ng.py", line 438, in send_command
    NailgunException.CONNECTION_BROKEN)
NailgunException: Server disconnected unexpectedly: [Errno 104] Connection reset by peer
```

Our Buck CI job makes few sequential `buck` invocations, this particular one is `buck project` and build fails pretty consistently on this stage.

**Comment by sbalabanov** [comment]
Might be related to https://github.com/facebook/nailgun/pull/131 but at this point not sure how. It seems that buckd server just crashes on `ng-stats` request. Is it possible for you to debug the failure?

**Comment by sbalabanov** [comment]
I do not know if any logs are generated; what you can do is to get the latest source codes from github and then run buckd with debugger
BUCK_DEBUG_MODE=1 buck project <your args> then connect a debugger (like IntelliJ).
I am prepping a change that will give some more logs in this case but it is not in trunk yet.

**Comment by ryanrhee** [comment]
cc @mzlee do y'all not see this often in fbsource?

**Comment by buildbreaker** [comment]
We're having this problem too on my team. Is there a recommendation on what we can do to avoid merge conflicts?

**Comment by artem-zinnatullin** [comment]
Short update, cherry-picking following commits fixed this issue

(append facebook/buck/commit):

- e1d4e585b93e8cf5cb10d4c788af5a354f892bc4 Upgrade Nailgun and tune daemon integration tests
- d01f49fd4d0e929d182b0e45bda5de9ba870dad3 Improve daemon termination by hard killing a process
- 3f53c4853ba7d79215c36ed9ac3abb48aa7a33a2 Add CONNECTION_BROKEN Nailgun exception to fail buckd presence check
- 58a9e88a689484a3ecf333c4bc59cf938b11f31e update Nailgun (fix broken pipe problem)

**Comment by artem-zinnatullin** [comment]
Forgot to close the issue back then, sorry
