### ISSUE TITLE
Pull requests backing up.

### ISSUE THREAD

**Issue by brettwooldridge** [facebook/buck#1861]
This is a "project" issue, not a "product" issue.  Due to the continually failing build, pull requests seem to be backing up significantly.  This occurred approximately 2 years ago as well, if I recall...

Can those with commit privilages either make an effort to get the build green, and/or push back on submitters responsible for breaking it?

**Comment by brettwooldridge** [comment]
Commit [267719c5]() seems to have broken the AppVeyor build roughly [two months ago](https://ci.appveyor.com/project/Facebook/buck/build/6238).

![screen shot 2018-04-21 at 4 38 28](https://user-images.githubusercontent.com/1538661/39070343-0559915e-451e-11e8-861b-238a715c4276.png)

**Comment by sdwilsh** [comment]
cc @ilya-klyuchnikov who landed that
