### ISSUE TITLE
Link error with __android_log_print

### ISSUE THREAD

**Issue by R1kk3r** [facebook/buck#1864]
To reproduce the bug, simply take the buck samples (https://github.com/fbsamples/bucksamples) and go into 'cross-platform-scale-2015-demo'. I'm using the NDK 15c (since the 16b is not supported by Buck) and set the `ndk.compiler = clang` in the buckconfig.

We can build the android demo easily
`buck build demo_app_android`

But if you add "#include <android/log.h>" and some `__android_log_print()` inside `Hello.cpp`, the linking phase will fail. Even with `-llog` added in the linker_flags.

```
buck-out/gen/android/cxx/jni#android-arm64,compile-pic-Hello.cpp.o11bd3722/Hello.cpp.o: In function `JNI_OnLoad':                                                                        
./android/cxx/Hello.cpp:35: undefined reference to `__android_log_print'
```

It seems that the `--as-needed` parameter is causing the error. I ran the raw `ld` command directly (I used the `--verbose 10` to see the command executed) without `--as-needed` and it worked just fine. I also tried moving the parameter after `-llog` and it worked too. So the issue is that the `--as-needed` is placed before `-llog`. In addition, I compared with a standard gradle build and the `--as-needed` is not present in the link command.

As the `--as-needed` parameter is autogenerated by Buck, any idea on how to fix that ? Or am I missing something?

EDIT : For the moment, it is working with `-Wl,--no-as-needed`:
```
cxx_library(
  name = 'jni',
  srcs = glob(['*.cpp']),
  soname = 'libjni.so',
  compiler_flags = [
    '-fvisibility=hidden',
    '-v',
    '-DDEBUG',
  ],
  linker_flags = ['-Wl,--no-as-needed', '-llog'],
  deps = [
    '//common:hello',
  ],
  visibility = [
    '//android/java/com/facebook/buck/demo:lib',
    '//android:demo-app-aar',
  ],
)
```

**Comment by LLITCHEV** [comment]
Thanks for the report! I tried to repro it and I could not. Relatively recently we have made changes to our linker flags and I see (in the code) that the --no-as-needed flag is passed with the "-Wl," prefix. Could you please the code from get master and try with that? Or if you give me the version of Buck (buck --version) I can go back to that version and try to reproduce the problem. Thanks again!

**Comment by R1kk3r** [comment]
Thank you for your reply I will try with master and see if it works. In the mean time, here’s my version of buck: 
‘’’
$ buck --version
buck version v2018.03.26.01
‘’’
and I am using the NDK 15c and Androïd SDK 26.0.2. Also I have this in my buckconfig:

‘’’
[ndk]
cpu_abis = armv7, arm64
compiler = clang
cxx_runtime = libcxx
‘’’

**Comment by andrewjcg** [comment]
Yeah, I think the fundamental thing is that `*linker_flags` isn't really a great way to model library dependencies (e.g. `-lz`) since, as you mentioned, Buck puts them on the link line *before* the object files, which seems like it causes issues with `--as-needed` on some backends (and probably correctly so).

It might be worth adding a class of `post_*linker_flags` parameters which get added *after* the object files for this use case.  For better or worse, we at least avoid this internally by using "wrapper" rules to abstract the packaged NDK libs, and depend on those rules instead of using linker flags:

```
# third-party/android-ndk/BUCK
prebuilt_cxx_library(
    name = "z",
    exported_linker_flags = ["-lz"],
    header_only = True,
    visibility = ["PUBLIC"],
)
```

This at least guarantees and dependents add `-lz` onto the link *after* all their objects/libs.

**Comment by SergeyJames** [comment]
-DCMAKE_CXX_FLAGS="-llog"  helps me
