### ISSUE TITLE
Build failed: No system compiler found. Did you install the JRE instead of the JDK?

### ISSUE THREAD

**Issue by Ziv-Barber** [facebook/buck#1865]
I have the (official) 1.8 JDK + JAVA_HOME + it's in the system path.

Windows: 8.1
java version "1.8.0_141"
Java(TM) SE Runtime Environment (build 1.8.0_141-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.141-b15, mixed mode)

**Comment by ttsugriy** [comment]
please include full error message with stack and paste the output of `java -version`

**Comment by Ziv-Barber** [comment]
bin\buck build --show-output buck
PARSING BUCK FILES: FINISHED IN 0.1s
CREATING ACTION GRAPH: FINISHED IN 0.0s
Build failed: No system compiler found. Did you install the JRE instead of the JDK?
    When running <javac_jar>.
    When building rule //src/com/facebook/buck/apple/xcode:xcode.
DOWNLOADED 0 ARTIFACTS, 0.00 BYTES
BUILDING: FINISHED IN 0.5s 468/1107 JOBS, 4 UPDATED, 0.4% CACHE MISS
BUILD FAILED

Windows 8.1
JDK 1.8 172 64 bit

java -version
java version "1.8.0_172"
Java(TM) SE Runtime Environment (build 1.8.0_172-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.172-b11, mixed mode)

The JDK version of java.exe is the first in my path setting (to the same version above).

**Comment by sbalabanov** [comment]
Are you building buck with buck? which version is "bin\buck" and where does it come from?
Also, could you please the full output of `cat src/com/facebook/buck/apple/xcode/BUCK`
