### ISSUE TITLE
Bitcode support for iOS 

### ISSUE THREAD

**Issue by mgrebenets** [facebook/buck#1867]
I hope I'm wrong, but there doesn't seem to be bitcode support available in `apple_***` rules.

Or is there a tricky set of compiler and linker flags that I have to specify to enable bitcode support?

**Comment by ttsugriy** [comment]
what kind of support would you like, @mgrebenets? Embedding bitcode is just a compiler flag `-fembed-bitcode` away :)

**Comment by mgrebenets** [comment]
Hm... I’m pretty sure I tired that... I’ll fibe it another go to be 100% sure.
