### ISSUE TITLE
IntelliJ modules now exclude any folder containing a BUCK file that does not contain a project_config

### ISSUE THREAD

**Issue by mread** [facebook/buck#188]
This commit abd06e22bb6f7696e3b0687eba4a2d591a7dd1ae appears to have changed the behaviour of `buck project` as per the issue title. Could someone confirm whether this is as intended please? And if so, how to configure a module with child directories containing BUCK files that we do not wish to be separate IntelliJ modules? @Coneko @oconnor663

**Comment by sdwilsh** [comment]
@mkonicek is totally revamping our IntelliJ stuff and making it much better.  It's behind an experimental flag right now, but it's probably worth checking out so you don't have to have a post-process script.

**Comment by mread** [comment]
Not sure how far along the IntelliJ work is but there are still issues that stop us using it without post-processing. Let me know if it would be useful to list them.

**Comment by sdwilsh** [comment]
It sure would.  I also meant to tag @marcinkosiba...

**Comment by marcinkosiba** [comment]
So the new thing is `buck project --experimental-ij-generation` and I'd be interested to hear your opinions. It may not solve your problem though - if a particular directory doesn't contain source code necessary to compile the targets it will be excluded from the project (the logic is based on the actual targets, not on project_config, so results will be different).
IntelliJ still lets you edit excluded files, is the issue that they will not get syntax highlighting?
We could generate excludes for sources only if you explicitly pass a target to `buck project`, would that work for you guys?

**Comment by mread** [comment]
Sorry, it took a while to get round to this. Our first run through failed an assertion here:

**Comment by marcinkosiba** [comment]
I don't suppose you're working on an open-source project or can share the BUCK files that cause this?

**Comment by mread** [comment]
No, I can't share the project that produces that error. I will try to step through at some point as try to work out what the issue is.

There may be another project that I could share, I'll get back to you on that.

**Comment by mread** [comment]
If you were to do the following:
```
git clone https://github.com/mread/spark-redis-bootstrap-buck.git
cd spark-redis-bootstrap-buck
rm -rf .idea
buck project --experimental-ij-generation
```

First issue is that it seems to attempt to build the project, not just configure it so you get a failure due to missing nodejs deps. To fix that
```
npm install
buck project --experimental-ij-generation
```

1. Every package under src/main/java appears to get an entry in the sourcs, this is unnecessary and for very large projects a bit confusing
2. Exclude folders include lib/, build/ and node_modules/, I'm not sure where this list is coming from but I don't think I want to exclude those. Is it just excluding everything that isn't explicitly part of a rule?
3. If misc.xml doesn't exist then it doesn't create one. If it does then it defaults the JDK to
```
<component name="ProjectRootManager" version="2" languageLevel="JDK_1_6" assert-keyword="true" jdk-15="true" />
```
even though we have specified the following in `.buckconfig`
```
[java]
    source_level = 8
    target_level = 8
```
4. Likewise project language level is 6, not 8
5. No output directory set.

That's it for now. Hope it's helpful.

**Comment by marcinkosiba** [comment]
Thanks Matt! I created issue 350 for discussing your second comment. I'm assuming the project you linked there doesn't actually reproduce the IllegalStateException.

**Comment by alsutton** [comment]
Commit 8d3848685f958b7289a03e2ae330495a85b3d790 switches project generation to a new generator which doesn't require the project_config option to be present.
