### ISSUE TITLE
Buck doesn't print out the error messages for failing Go tests

### ISSUE THREAD

**Issue by linzhp** [facebook/buck#1882]
A typical message for failed Go tests looks like this

```
TESTING //:test-failure
BUILT 19/19 JOBS 0.0s //:test-failure
FAIL    <100ms  0 Passed   0 Skipped   1 Failed   //:test-failure
FAILURE go_test TestAdd2: 

====STANDARD OUT====

====STANDARD ERR====

TESTS FAILED: 1 FAILURE
Failed target: //:test-failure
FAIL //:test-failure
```

The standard output and error are both empty. [This commit](https://github.com/linzhp/buck/commit/523323ad387c7b5f1ebb3f5e69dd2b167b5a13ae) can help reproducing the issue

**Comment by kageiit** [comment]
This gives a clue - https://github.com/facebook/buck/blob/master/src/com/facebook/buck/step/AbstractTestStep.java#L71

Seems like the output is redirected to a file

**Comment by linzhp** [comment]
That goest to `buck-out/gen/test/com/facebook/buck/features/go/testdata/go_test/__test_test-failure_output__/results`, which is separate from what buck test prints out on the terminal. I am trying to figure out what goest to the termimal.
