### ISSUE TITLE
Ignore warnings for cxx_library headers

### ISSUE THREAD

**Issue by sheldonneuberger** [facebook/buck#1906]
If we copy the source of a third party library into our repo, make a cxx_library target for it, then include its headers in our other targets, we'll see warnings for the third party library's headers.

prebuilt_cxx_library includes its headers with -isystem to fix this, but in our case it's not a prebuilt because we're copying the whole source into the repo.

Having a systemInclude=true/false flag on cxx_library (and similar, e.g., apple_library) targets would let us solve this. Does that sound like the right path? Any reasonable alternative that I'm missing?

**Comment by philipjameson** [comment]
Is there any reason you can't create a prebuilt_cxx_library that has header_dirs set and header_only set to true, and then depend on that in your cxx_library?

**Comment by sheldonneuberger** [comment]
Ah I see, so specify the headers in a prebuilt_cxx_library and specify the source in a cxx_library. We just gave that a try but prebuilt_cxx_library doesn't work with generated xcode projects (https://github.com/facebook/buck/issues/1098).

**Comment by styurin** [comment]
The issue you linked seems to be resolved, do you still have a problem with using `prebuilt_cxx_library` with XCode projects?

**Comment by sheldonneuberger-sc** [comment]
The linked issue was closed because the workaround was to use cxx_library instead of prebuilt_cxx_library.

**Comment by sheldonneuberger** [comment]
The linked issue was closed because the workaround was to use cxx_library instead of prebuilt_cxx_library.

**Comment by styurin** [comment]
> prebuilt_cxx_library doesn't work with generated xcode projects

Maybe it's worth fixing XCode project generator?

**Comment by styurin** [comment]
@williamtwilson can you help with adding support for prebuilt_cxx_library to Xcode project generator?
