### ISSUE TITLE
Uninformative error message when toolchain not on PATH

### ISSUE THREAD

**Issue by robertquitt** [facebook/buck#1920]
On Windows, when, for example, "lib.exe" is not on the PATH, then the error message is "Failed to transform Path to SourcePath, path not found:  lib". I think this could be a bit more informative, e.g. "Could not find executable "lib", check if it is on your PATH and restart buckd" 

https://github.com/facebook/buck/blob/65158aa884a38c6072ff4e6275d0e532be1dd29b/src/com/facebook/buck/config/BuckConfig.java#L363

**Comment by timmych** [comment]
With 63369ad239f737c39c510da974dca712f8aa4691 this error message will be "File not found: {path}" and it should be more informative now.  

It is a bit hard to make it specific about executable and PATH because SourcePath can be any kind of files.
