### ISSUE TITLE
Dependent unable to find dependency output

### ISSUE THREAD

**Issue by aventadorm** [facebook/buck#1922]
I have a target1 that depends on a target2. Buck builds target2 first and then tries building target1 which is great but then the output dll of target2 is needed by target1 which it is unable to find. I added a dependency to the dll file by hardcoding the reference to the buck-out folder which works but doesn't look like good practice. I looked at src/.../rules/coercer/PathTypeCoercer.java and if I am getting it right, the target2 output directory should be present in the LoadingCache for target1 ? I do not know if this is correct and if it is , then I am not really sure how to proceed ahead.

**Comment by styurin** [comment]
Could you share your target definitions?

You cannot reference the output by path, you need to use target name instead.

**Comment by aventadorm** [comment]
Project1, Project2, Project3 and Project4 all have their own folders, BUCK files, csharp source files and .csproj files each.
Here are BUCK files for each of them : 

csharp_library(
  name = 'Project1',
  dll_name = 'Project1.dll',
  framework_ver = 'net45',
  srcs = [
    'Project11.cs',
    'Project12.cs',
    'Project13.cs',
    'Project14.cs',
    'Project15.cs'
  ],
  resources = {},
  deps=[
  '//:Project3',
  '//:Project4'
  ],
  visibility =[
    'PUBLIC'
  ]
)

csharp_library(
  name = 'Project2',
  dll_name = 'Project2.dll',
  framework_ver = 'net45',
  srcs = [
    'Project21.cs',
    'Project22.cs',
    'Project23.cs',
    'Project24.cs',
    'Project25.cs',
    'Project26.cs'
  ],
  resources = {},
  deps=[
    '//:Project3',
    '//:Project4'
  ],
  visibility =[
    'PUBLIC'
  ]
)

csharp_library(
  name = 'Project3',
  dll_name = 'Project3.dll',
  framework_ver = 'net45',
  srcs = [
  'Project31.cs',
  'Project32.cs'
  ],
  resources = {},
  deps=[
  ],
  visibility =[
    'PUBLIC'
  ]
)

csharp_library(
  name = 'Project4',
  dll_name = 'Project4.dll',
  framework_ver = 'net45',
  srcs = [
    'Project41.cs',
    'Project42.cs',
    'Project43.cs',
    'Project44.cs'
  ],
  resources = {},
  deps=[
  ],
  visibility =[
    'PUBLIC'
  ]
)

Here is the BUCK file in the main directory that houses the main solution file. This BUCK file is a sibling to the Project1/2/3/4 folders.
csharp_library(
  name = 'main',
  dll_name = 'main.dll',
  framework_ver = 'net45',
  srcs = [
    'main.cs'
  ],
  resources = {},
  deps=[
    '//Runtime/Project1:Project1',
    '//Runtime/Project2:Project2',
    '//Runtime/Project3:Project3',
    '//Runtime/Project4:Project4'
  ]
)
csharp_library(
  name = 'Project3',
  framework_ver = 'net45',
  deps=[
  '//Runtime/Project3:Project3'
  ],
  visibility =[
    'PUBLIC'
  ]
)

csharp_library(
  name = 'Project4',
  framework_ver = 'net45',
  deps=[
  '//Runtime/Project4:Project4'
  ],
  visibility =[
    'PUBLIC'
  ]
)
Now, when I run : buck build main
It starts with Project1 sees 3 and 4 as dependencies, builds them first. 
Then when it continues with Project1, it fails because it is not able to see Project3.dll and Project4.dll.
If I put a prebuilt_dotnet_library() target referencing those DLLs just by name and add these as additional targets to Project1, it searches for the DLLs in Project1 folder. Now, one way ahead is to add these additional assembly references so the deps of Project1 will be 
deps=[
    '//:Project3',
    '//:Project4',
    ':Project3',
    ':Project4'
  ],
with prebuilt_dotnet_library() references in the same BUCK file for the last two assembly references.
However, this would need BUCK to search for these assemblies inside the buck-out folder and not just in the Project1 folder.
Another option is to just have target build references and not assembly references and somehow make BUCK recognise these assembly references through the target references.
