### ISSUE TITLE
Generate BUCK files from podspec

### ISSUE THREAD

**Issue by wjmelements** [facebook/buck#1923]
This is a feature request for generating BUCK files from podspecs. Podspecs contain enough information to build a BUCK file, so this would help with maintaining projects that use cocoapods alongside BUCK.

**Comment by mgrebenets** [comment]
Afaik, a lot of companies have their own in-house scripts for that which is used during migration from CocoaPods to Buck and then never used again.

That totally would be an awesome feature to have as part of Buck.

We have our own as well, which is not very sharable at the current state, but what we do is this:

1. Read podspec into JSON which is as easy as

```ruby
require "cocoapods-core"
require "json"
puts Pod::Specification.from_file(path).to_json
```

1. Pass that JSON to a python script which is using `jinja2` template to convert JSON to `BUCK` file.

I guess we could do all of it in Ruby or in any other language.

**Comment by styurin** [comment]
We would probably avoid including this functionality as part of main binary, but we can include it as separate scripts in buck repository. Internally we don't have needs for this feature so it's unlikely we're going to work on that, but we would definitely take a look at any PRs.
