### ISSUE TITLE
buck targets command is broken

### ISSUE THREAD

**Issue by kageiit** [facebook/buck#1930]
Something changed between

46bc9ad6c6861759894ad73bbfce41f4e45196ce and 55e63f2f86

That caused `./buckw targets` to error out with
```
BAD ARGUMENTS: Must specify at least one build target pattern. See https://buckbuild.com/concept/build_target_pattern.html
```

It seems only `./buckw targets ...` works now as an alternative. Filing bug to confirm if its intended breaking change or a regression

**Comment by kageiit** [comment]
cc @styurin @ttsugriy

**Comment by styurin** [comment]
Yeah, it was intentional. If you want to run `targets` for all targets in a repository you can use `//...`. af4694a7cfaedc957f56db6bd3822b56a618587e is the change.

**Comment by kageiit** [comment]
Thanks for confirming!

**Comment by robbertvanginkel** [comment]
Previously `buck targets` without a specifier would also return explicitly flavored targets. Considering this buckfile: https://gist.github.com/robbertvanginkel/28055312f0e93f8ee9a6d89862c9281c

```
$ buck targets
//:dep
//:dep#default
//:rule
```
Wheras with `...` this is omitted.
```
$ buck targets ...
Parsing buck files... 0.7 sec
//:dep
//:rule
```

Is there a way to get this behaviour back if you're interested in listing all targets that have explicitly defined flavors?

**Comment by TonyTangAndroid** [comment]
`./buckw targets ...` does not work now. Only `./buckw targets //...` works.
