### ISSUE TITLE
Include sources from other directories 

### ISSUE THREAD

**Issue by aventadorm** [facebook/buck#1933]
I have a parent buck and two folders with just one having its own buck. I want the child buck to be able to list files from the non-buck sibling in its sources. I tried adding these src files in the parent buck and referencing them from the child buck but it just compiles these src files separately and tries accessing its assembly in the child buck. Is there a way to do this or should I just list all these source files and their target in the parent buck ?

**Comment by styurin** [comment]
Could you show the structure?
