### ISSUE TITLE
Generated Xcode project doesn't set Target dependencies

### ISSUE THREAD

**Issue by brentleyjones** [facebook/buck#1943]
For a test that uses `TEST_HOST` it needs to have it's Target dependency set to the app it will be hosted in. Also, with Xcode's new build system, explicit targets are desired.

**Comment by brentleyjones** [comment]
Related, it seems that the `BUNDLE_LOADER` needs to be `BUNDLE_LOADER = $BUILT_PRODUCTS_DIR/App.app/Binary` for iOS. The more complicated form confuses Xcode because it includes `//`.

**Comment by mgrebenets** [comment]
We've just experienced same issue with `//`.
Xcode actually resolves the path and displays it correctly in the error message, but it can't _find_ it however.
![image](https://user-images.githubusercontent.com/350654/47059184-ed2a8b00-d213-11e8-9b12-834e42b78ad6.png)


@brentleyjones do you have any nice way to massage generated Xcode projects and xcconfigs after buck has done its job?

or should it be the job of buck wrapper shell script?

**Comment by mgrebenets** [comment]
Another related issue is that autogenerated projects will have `ONLY_ACTIVE_ARCH` set to `NO` for all configurations.

Which causes build folder to be `Debug-iphoneos` even if simulator is selected as a target.
I guess it's not a big deal as long as tests can find its host app the actual path doesn't matter much.
Still not having the flag set will cause some extra build time.

**Comment by brentleyjones** [comment]
@mgrebenets Sorry, I moved on from trying to get buck to work.

**Comment by ghvg1313** [comment]
This might be fixed by https://github.com/facebook/buck/pull/2055

**Comment by mgrebenets** [comment]
Cool. Thanks @ghvg1313 .
I'll keep an eye on when it's imported and test it then.
