### ISSUE TITLE
Buck doesn't run on Cygwin

### ISSUE THREAD

**Issue by davido** [facebook/buck#195]
Gerrit Code Review Buck driven build process heavily relies on *nix commands. The hope was to support Buck driven build for Gerrit project on Windows on top of Unix emulation layer, like Cygwin. On most recent master (0cd750f6443412992bf1add8a73ad8d914917ff6) Buck doesn't start on Cygwin:

```
$ buck
Traceback (most recent call last):
  File "/home/david/bin/buck", line 30, in <module>
    main()
  File "/home/david/bin/buck", line 16, in main
    with Tracing("main"):
  File "/cygdrive/c/Users/david/projects/buck/bin/tracing.py", line 34, in __enter__
    now_us = monotonic_time_nanos() / 1000
  File "/cygdrive/c/Users/david/projects/buck/bin/timing.py", line 15, in monotonic_time_nanos
    raise Exception('Unsupported platform: ' + platform.system())
Exception: Unsupported platform: CYGWIN_NT-6.1-WOW64
````

**Comment by Coneko** [comment]
Have you tried using Buck in powershell? We're working on support for that rather than cygwin. Does Gerrit need other tools that are only available in cygwin on windows?

**Comment by sdwilsh** [comment]
I've done a lot of work to get Buck working well with Power Shell.  Do you hit the same issues there?

**Comment by davido** [comment]
No. On Powershell it works as expected.

**Comment by sdwilsh** [comment]
Honestly, I'm pretty tempted to wontfix this.  Supporting cygwin is a huge mess because sometimes it uses Windows semantics, and sometimes Unix, and it doesn't feel very consistent.

**Comment by davido** [comment]
Closing it then.
