### ISSUE TITLE
Bug in NDK unified header test

### ISSUE THREAD

**Issue by R1kk3r** [facebook/buck#1952]
https://github.com/facebook/buck/blob/d66d92f3519c34648e2cfdd7f923ec3471c9a4d2/test/com/facebook/buck/android/AndroidBinaryCxxIntegrationTest.java#L239

Should be "ndk" not "nkd".

**Comment by styurin** [comment]
thanks, I'll fix it

**Comment by styurin** [comment]
Thanks for reporting.
