### ISSUE TITLE
Build tools version update doesn't rerun aapt steps

### ISSUE THREAD

**Issue by raviagarwal7** [facebook/buck#1953]
[Aapt2Compile](https://github.com/facebook/buck/blob/master/src/com/facebook/buck/android/Aapt2Compile.java#L45) rule doesn't add build tools version as a dependency causing build inconsistency when tools version are updated. 
```
╰─$ cat .buckconfig.local | grep build_tools_version
    build_tools_version = 27.0.3

╰─$ ../buck/bin/buck build app
2018-07-03 12:32:33,094 [INFO][buck_tool.py:460] Restarting Buck daemon because Buck version has changed...
Parsing buck files: finished in 4.6 sec (100%)
Creating action graph: finished in 0.6 sec (100%)
Building: finished in 2.9 sec (100%) 3/3 jobs, 3 updated
  Total time: 8.2 sec

╰─$ cat .buckconfig.local | grep build_tools_version
    build_tools_version = 28.0.0

╰─$ ../buck/bin/buck build app
Shutting down and restarting buck daemon: Buck configuration options changed between invocations
Parsing buck files: finished in 3.8 sec (100%)
Building: finished in 1.5 sec (100%) 2/2 jobs, 0 updated
  Total time: 5.7 sec
```

To fix this we need to add [build_tools_version](https://github.com/facebook/buck/blob/02140ab447c63631e90c8e23c9ebcf311ae55a0f/src/com/facebook/buck/android/toolchain/impl/AndroidBuildToolsResolver.java#L59) as a RuleKey to all the rules which uses AndroidPlatformTarget.

Suggestion:
- Add build tools version as a property to `AndroidPlatformTarget` and make it a rule key for all rules using it. (but this could be error prone if someone forgets to annotate when using `AndroidPlatformTarget`) 
- Add the `build_tools_version` rulekey as a global?

**Comment by brianduff** [comment]
The aapt executable was added to the rulekey in https://github.com/facebook/buck/commit/aa927ccc0077b870b190c3d61623b5e383578fee#diff-887fedb4b0ad49cd55fc3882abf905f3
