### ISSUE TITLE
install -r fails when another simulator is running

### ISSUE THREAD

**Issue by wjmelements** [facebook/buck#1964]
While the iPhone 8 simulator was running, buck failed to start the iPhone 5s simulator.

```
buck install -r myapp_ios
Action graph will be rebuilt because files have been added or removed.
Building: finished in 0.0 sec (100%) 1/1 jobs, 0 updated
  Total time: 0.0 sec
Installing... 39.1 sec
BUILD FAILED: Cannot install //:MyApp#dwarf-and-dsym,no-include-frameworks (could not start simulator iPhone 5s within 20000 ms)
make: *** [run] Error 6
```

Killing the iPhone 8 simulator fixed this.

Perhaps it could prefer the currently-running simulator, or say that the desired simulator couldn't start because another is running.

**Comment by v-jizhang** [comment]
That behavior is by design. Thank you.
