### ISSUE TITLE
What is the best way to produce fat static lib binary?

### ISSUE THREAD

**Issue by ildarsharafutdinov** [facebook/buck#1969]
Let's say I have a number of libs which are build from source with buck. 
E.g.
```
apple_binary(
   name = 'LibA',
   ...
)

apple_binary(
   name = 'LibB',
   ...
)
```

When I build them, they produce `libLibA.a` and `libLibB.a` in `buck-out/gen/<platform>/...`  as expected.

But what I want to is to produce a single `libFatBinary.a` with contents of both `LibA` and `LibB`, where each of them is built for arm64 and simulator.

I can probably achieve that with a custom build rule which builds both libs for each platform and then `lipo`s them in a single static library.

However, I guess there is a better way to achieve that.

I tried `prebuilt_apple_framework` which has both `deps = [':LibA', ':LibB']`.
`buck build FatBinary` finished without errors, but didn't produce any output.

Any hint is greatly appreciated.

**Comment by ttsugriy** [comment]
Please try adding platform flavors you'd like to have binaries for when adding dependencies. For example, `:LibA#iphoneos-arm64,iphonesimulator-x86_64`.

**Comment by ildarsharafutdinov** [comment]
@ttsugriy ,

Thank you.

However, it results in:

```//:Texture#iphoneos-arm64,iphonesimulator-x86_64: Fat binaries can only be generated from binaries compiled for the same SDK.```

Which makes me think the only way to go is to build separately for `iphoneos-arm64`, `iphonesimulator-x86_64` and then `lipo` results into a single fat binary.

**Comment by ttsugriy** [comment]
@ildarsharafutdinov, doh, I didn't realize that those are for different SDKs. In such case you can indeed use a `genrule` that invokes `lipo` tool.
```
genrule(
  name = "fat",
  cmd = "lipo ... $(location :Texture#iphoneos-arm64) $(location :Texture#iphonesimulator-x86_6) -o $OUT",
  out = "fat.bin",
)
```

**Comment by ildarsharafutdinov** [comment]
thank you.
