### ISSUE TITLE
Regression in dex split for non predexed apps

### ISSUE THREAD

**Issue by kageiit** [facebook/buck#1978]
`isAllowRDotJavaInSecondaryDex` in `AndroidGraphEnhancerArgs` needs to be defaulted to `true`.

This commit https://github.com/facebook/buck/commit/8c331339d4484f90c8888db175af805887a01015 broke apps that have a large number of R classes . This is a regression and can affect any apps in the wild using buck. The previous behavior should be the default to prevent this from happening.

cc @dreiss @styurin

**Comment by kageiit** [comment]
also cc @asp2insp

**Comment by asp2insp** [comment]
@kageiit Can you provide more information about what exactly broke? That commit should have been a no-op for apps that do not set the flag.

**Comment by asp2insp** [comment]
After discussion via slack we found the issue -- this change was supposed to affect pre-dexed builds, but is breaking non-pre-dexed builds. Fix will be #1980

**Comment by kageiit** [comment]
Fixed in 6bb508bd20e494cd3173dc6d968ffe9e90381803
