### ISSUE TITLE
[cpp] Question: How does BUCK cope with multiple artifacts and each with its own compile flags?

### ISSUE THREAD

**Issue by AntonioL** [facebook/buck#1983]
I am considering BUCK, I really like its declarative approach.

From the website I don't understand what kind of assumption it makes when putting together artifacts built with different compile flags. So I thought to open a ticket in which to describe a scenario, and hopefully someone more familiar with the tool would explain me what happens in the aforementioned scenario.

64 bit_machine:
cxx_library A - built for a 32bit machine
cxx_binary B - this depends on the "A" artifact and it pulls up the running machine's architecture info and it builds for 64 bits.

Linking however will fail, what does BUCK do in that regard? I would expect that BUCK would make sure that all the artifacts would get built at least with the same compile flags to avoid such a clash.

Thank you for your patience.

**Comment by njlr** [comment]
> cxx_library A - built for a 32bit machine

Do you mean `prebuilt_cxx_library`? A `cxx_library` would be built from source to the target machine.

**Comment by AntonioL** [comment]
The question is how the target machine would be resolved in the above case?

**Comment by njlr** [comment]
By default, Buck will build for the machine that you are running on. 

To cross-compile, you put a "flavour" on the end. 

For example, if you are on macOS: 

```bash=
# macOS build
buck build :my-lib

# iOS simulator build
buck build :my-lib#iphonesimulator-x86_64
```

Make sure you have this enabled in your `.buckconfig`: https://buckbuild.com/files-and-dirs/buckconfig.html#cxx.should_remap_host_platform

**Comment by njlr** [comment]
`prebuilt_cxx_library` allows you to specify different binaries for different target platforms. https://buckbuild.com/rule/prebuilt_cxx_library.html#platform_shared_lib
