### ISSUE TITLE
Buck fails to build samples from the bucksamples repo

### ISSUE THREAD

**Issue by nroberson** [facebook/buck#1989]
I started following the [Buck: Getting Started](https://buckbuild.com/setup/getting_started.html) guide today and ran into the following. 

I installed `buck` via brew, and attempted running the samples located at https://github.com/fbsamples/bucksamples

On each sample I get the following error message
```
2018-08-02 18:12:15,434 [INFO][buck_tool.py:457] Starting new Buck daemon...
WARNING: Output when parsing /private/var/folders/n0/349798rj38g7lg8rz4pbvd780000gn/T/tmp.pfsjK3qh/bucksamples/cross-platform-scale-2015-demo/ios/BUCK:
| Traceback (most recent call last):
|   File "/private/var/folders/n0/349798rj38g7lg8rz4pbvd780000gn/T/tmp.pfsjK3qh/bucksamples/cross-platform-scale-2015-demo/.buckd/tmp/buck_run._eUkBj/buck_python_program8401278799560665088/__main__.py", line 10, in <module>
|     from buck_parser import buck
|   File "/private/var/folders/n0/349798rj38g7lg8rz4pbvd780000gn/T/tmp.pfsjK3qh/bucksamples/cross-platform-scale-2015-demo/.buckd/resources/2018.07.23.01/buck_server/buck_parser/buck.py", line 3, in <module>
| ModuleNotFoundError: No module named '__builtin__'
Parsing buck files: finished in 0.9 sec
Buck wasn't able to parse /private/var/folders/n0/349798rj38g7lg8rz4pbvd780000gn/T/tmp.pfsjK3qh/bucksamples/cross-platform-scale-2015-demo/ios/BUCK:
No content to map due to end-of-input
 at [Source: com.google.common.io.CountingInputStream@5e151245; line: 1, column: 0]
```

`buck --version` reports `buck version 2018.07.23.01`

Here's a screenshot of the output as well.

<img width="959" alt="buck-fail" src="https://user-images.githubusercontent.com/1251112/43614345-1592c158-9681-11e8-9772-67691886f944.png">

**Comment by ttsugriy** [comment]
this is most likely because you're probably not using the version 2.7 of Python as mentioned in https://buckbuild.com/setup/getting_started.html

You can probably get away with using a different version if you enable [Skylark parser] instead of Python DSL.

**Comment by ttsugriy** [comment]
I've sent a PR to enable Skylark parser for all of our buck samples - https://github.com/fbsamples/bucksamples/pull/13/files You can use it to unblock yourself.

**Comment by nroberson** [comment]
Ah, you're right. Python 3 is default on my path. I'll give it another go.
Sorry for the noise.
