### ISSUE TITLE
XAR support?

### ISSUE THREAD

**Issue by djakobsson** [facebook/buck#1992]
Is there any plan on built-in support (PEX-style) for [XARs](https://code.fb.com/data-infrastructure/xars-a-more-efficient-open-source-system-for-self-contained-executables/)?

**Comment by philipjameson** [comment]
Yep, we're definitely planning first class support for this (in fact, we use it internally at FB though some wrapper scripts). We want to be careful about promoting it before it works on windows, so the timeline is a little squishy.

**Comment by v-jizhang** [comment]
Sorry, we still don't have a plan on built-in support but as commented internally from @philipjameson, "one /can/ use them by setting make_xar to be the par builder."
