### ISSUE TITLE
Stale prefix-header files cause redefinition errors from clang.

### ISSUE THREAD

**Issue by keithprestonsc** [facebook/buck#2000]
Currently BUCK only uses file content instead of timestamps for precompiled headers.   However clang uses timestamps to invalidate the precompile headers.   If you use a precompile header with a stale timestamp, clang will error out.     BUCK uses no-validate-pch to get past this error and continue compilation.  This generally works, however, there is a single situation in which redefinition errors will happen.    Changing the timestamps on headers that are included in both the prefix header and source files and forcing recompilation of that source file will fail with redefinition errors.
Sample Project included:

buck build :TestApp
#Success
touch lib.h #Change timestamp
echo " " >> main.m #Force source recompilation
buck build :TestApp
#Failed to build

[TestApp.zip](https://github.com/facebook/buck/files/2292075/TestApp.zip)

**Comment by keithprestonsc** [comment]
Clang issues link
https://bugs.llvm.org/show_bug.cgi?id=38600

**Comment by v-jizhang** [comment]
This is can't be fixed unless either BUCK or clang change the way they handle precompiled headers but that is unlikely.
