### ISSUE TITLE
BUCK test runner sometimes silently skips tests if it failed to initialize the class

### ISSUE THREAD

**Issue by romanoid** [facebook/buck#2007]
I'll create repro / add more details as I investigate.

I've discovered that if error happens during loading/initialization of test class, BUCK ends up silently ignoring the test instead of reporting this failure.

Also interestingly enough it properly reports the error with connected debugger, so some race condition may be happening too. 
Note: with debugger not connected behavior is 100% consistent, it always skips.

**Comment by bobyangyf** [comment]
Is this for JUnitTest 3/4?

**Comment by romanoid** [comment]
To be more specific, this is Scalatest (which is compatible with both) and is used in junction with Junit4.

**Comment by romanoid** [comment]
I found how the problem manifests itself and will have PR with remedy shortly.

**Comment by romanoid** [comment]
the problem I found only fixes some of the examples (that behave the same with debugger and without). I'm perplexed by one test that fails correctly if (`--debug` or `--filter` are applied, but not otherwise)

**Comment by romanoid** [comment]
PR is UP: https://github.com/facebook/buck/pull/2009
