### ISSUE TITLE
BUCK has assumption of TestClassName = TestFileName[.java | .scala]

### ISSUE THREAD

**Issue by romanoid** [facebook/buck#2008]
BUCK determines set of all tests based on source files rather than resulting classes.

This assumption works perfectly fine with java, but breaks for scala where classes can be arranged arbitrarily within files. 

At the moment BUCK detects the potential test classes by matching them to the source classes. 

Potentially we can change this logic to just detect all top level classes in module output and assume any of them can be a test. 

Please advice if this change makes sense or if it to cause some adverse consequences.

**Comment by bobyangyf** [comment]
@romanoid I forgot if we fixed/addressed this.

But it should be fine if we assume top level classes "could" be a test.
We still have to verify that they are actual test-classes by ensuring they have `@Test` tags for Java

**Comment by romanoid** [comment]
We never did. Unfortunately I did not have time to investigate more / fix it and instead had put some lint/safeguards on our side.  

I think overall this one: https://github.com/facebook/buck/issues/2036 is much more dangerous.
