### ISSUE TITLE
ideabuck 3.5 contains a preference file at .idea/ideabuck.xml

### ISSUE THREAD

**Issue by mkillianey** [facebook/buck#2015]
The next release of the ideabuck plugin (3.5) writes a new preference file to .idea/ideabuck.xml that stores project-specific preferences.  The preferences are user-specific and it is unlikely that users will want that file to be committed to source control.

Users should be informed that they should check their `.gitignore`, `.hgignore`, etc. patterns to avoid inadvertently checking in that file.

[edit]  This change is now slightly more disruptive, in that all of the application-level prefs have been moved to project-level prefs, so upgrading from 3.4 (or older) to 3.5 (or newer) will cause the user to (effectively) lose their preferences on upgrade.

**Comment by kageiit** [comment]
We would actually like to commit that file to source control for things like project specific buck binary aliases (we typically have a buck wrapper at project root that we would like to configure)

**Comment by mkillianey** [comment]
To continue this conversation, our long-term plan is to move these prefs into `.idea/ideabuck/`...for example...

https://github.com/facebook/buck/blob/424039c55f6411d2b567b7d2c1f967008b2f9705/tools/ideabuck/src/com/facebook/buck/intellij/ideabuck/config/BuckCellSettingsProvider.java#L38

...so that users can pick/choose which of ideabuck's preferences to persist to source control.  For now, we're claiming both `.idea/ideabuck.xml` and `.idea/ideabuck/**`, and the long-term plan is to eventually drop `.idea/ideabuck.xml` and store all prefs in the `.idea/ideabuck/` directory.
