### ISSUE TITLE
Make buckd restart if buck java args change

### ISSUE THREAD

**Issue by kageiit** [facebook/buck#2021]
Similar to changes in buck version triggering this [behavior](https://github.com/facebook/buck/blob/38153bd670a98a1bf6e41bdd2fbfe2afe4953b41/programs/buck_tool.py#L480), changes to java args should as well since they affect compilation output when running compilers in memory

**Comment by kageiit** [comment]
@sbalabanov @ttsugriy I intend to upstream a pr for this. Let me know if this looks ok

cc @msridhar @romanoid  FYI

**Comment by sbalabanov** [comment]
lgtm. I will review.

**Comment by styurin** [comment]
Fixed in dde7baf6c5a5d14acc60a145000eaceb18ae2246
