### ISSUE TITLE
Circular dependencies in go and cgo code

### ISSUE THREAD

**Issue by vitarb** [facebook/buck#2027]
It seems that it's normal for go code to depend on cgo and for cgo depend on go at the same time.

Consider this package as an example:
https://github.com/mattn/go-sqlite3

sqlite3_go18.go depends on SQLiteConn that is defined in the cgo file sqlite3.go, while sqlite3.go depends on CryptEncoderSHA<XXX> from a normal go file sqlite3_func_crypt.go

This creates a loop in dependency graph, since now cgo needs to be defined as a dependency of go.

Is there any work-around for this issue or should we consider it a bug?

**Comment by mkaczanowski** [comment]
I am not sure if I see the problem. The go and cgo files are passed explicitly via ["srcs"](https://buckbuild.com/rule/cgo_library.html#srcs) and go files via [go_srcs](https://buckbuild.com/rule/cgo_library.html#go_srcs).

If you split the files into those two separate sections will that solve the issue? The cgo sources are compiled first (OSS go build) and later on linked against the "go archive" (generated via go compile).

**Comment by mkaczanowski** [comment]
per discussion on slack. I think we can close this issue.

You should use "go_srcs" to provide the go source files.
