### ISSUE TITLE
Tests cannot access internal functions in same package

### ISSUE THREAD

**Issue by mmdango** [facebook/buck#2029]
There was a similar issue previously with IntelliJ/Kotlin a while back: https://youtrack.jetbrains.com/oauth?state=%2Fissue%2FKT-16497

It has been fixed sense, but when running tests with Buck, we still see errors like:

`lib.mvrx/src/test/java/com/airbnb/android/lib/mvrx/MockBuilderTest.kt:49:34: error: cannot access 'fragmentMocks': it is internal in 'MockBuilder'`

**Comment by sbalabanov** [comment]
Sorry, Kotlin is not currently in Buck team support path. However you are very welcome to debug the issue and come up with the fix :)

**Comment by IanChilds** [comment]
For anyone else who stumbles upon this, you need to use `friend_paths` to specify the modules that you want to see internal methods of. The reason that these are not available by default is that internal and package-private are not the same thing - internal means that it is visible to anything in the same module, and per the definition here: https://kotlinlang.org/docs/reference/visibility-modifiers.html#modules a test module is a different module (separate kotlinc invocation), and therefore the internal methods are not visible by default. 

Added in https://github.com/facebook/buck/pull/2197
