### ISSUE TITLE
Recursive globs no longer allowed?

### ISSUE THREAD

**Issue by njlr** [facebook/buck#2035]
The behaviour of `glob` (and `subdir_glob`) seems to have changed in Buck `2018.08.27.01`. 

For example, this will no longer build: https://github.com/njlr/buck-recursive-globs

 > BuildFileFailError: Recursive globs are prohibited at top-level directory

What was the rationale behind this restriction?

**Comment by styurin** [comment]
IIRC it was restricted to avoid dealing with buck-out. cc @bobyangyf

**Comment by bobyangyf** [comment]
Yes. There's no way to stop native globs from traversing all directories, which means recursive globs are a super bad idea at the root, since it would traverse all folders, including `buck-out` and `.buckd`
