### ISSUE TITLE
deps but not platform_deps for prebuilt_cxx_library? 

### ISSUE THREAD

**Issue by njlr** [facebook/buck#2038]
It seems that `deps` is supported for `prebuilt_cxx_library` but not `platform_deps`.  

```python=
prebuilt_cxx_library(
  name = 'foo', 
  platform_static_lib = [
    ('^linux.*', ':foo-lib'), 
  ], 
  platform_deps = [], 
  deps = [
    ':foo-headers', 
  ], 
)
```

> Incorrect arguments to prebuilt_cxx_library with name foo: Extra unknown kwargs: platform_deps

Tested on `buck version 2018.08.27.01`.

**Comment by luciang** [comment]
Should be fixed by https://github.com/facebook/buck/commit/587fc6bf2a5af506213ce7d3a7e36a8045111763
