### ISSUE TITLE
cxx_genrule does not seem to generate anything? 

### ISSUE THREAD

**Issue by njlr** [facebook/buck#2044]
I have two rules like this: 

```python=
cxx_genrule(
  name = 'test-file', 
  out = 'hello.txt', 
  cmd = 'echo "Hello, world. " > $OUT', 
)

cxx_genrule(
  name = 'test-folder', 
  out = 'out', 
  cmd = 'mkdir -p $OUT && echo "Hello, world. " > $OUT/hello.txt', 
)
```

Then I build them: 

```bash=
buck build :test-file
buck build :test-folder
```

But `buck-out/gen` is empty. 

If I change them to `genrule` then everything works as expected. 

```bash=
buck --version
buck version 2018.08.20.01
```

**Comment by R1kk3r** [comment]
Not directly related to my issue (https://github.com/facebook/buck/issues/1853) but definitely linked to the flavoured trickiness.

From my understanding, the ```cxx_genrule``` is a flavoured version of a ``genrule``. Calling it without any flavour has no effect. If you call it like ```buck build //:test-file#default```, it will work. I guess ```cxx_genrule``` is most of the time used to generate source code, assembly or object file and should be referenced inside ```srcs``` of a ```cxx_library```/```cxx_binary```. That way, when you build the top target, it magically propagate the flavour to your ```cxx_genrule```.

**Comment by njlr** [comment]
Thanks @R1kk3r, it seems to work with a flavour specified: 

```bash=
buck build :test-file#default
buck build :test-file#macosx-x86_64
```

Odd that it behaves like this... I would have expected `buck build :test-file` and `buck build :test-file#macosx-x86_64` to be equivalent with [`should_remap_host_platform`](https://buckbuild.com/files-and-dirs/buckconfig.html#cxx.should_remap_host_platform) enabled.

**Comment by timmych** [comment]
I think this is in the [documentation](https://buckbuild.com/rule/cxx_genrule.html):

> Note that if you specify the cxx_genrule as a command-line target to buck build, you must include a platform flavor.

**Comment by njlr** [comment]
@timmych So it is! Although arguably the behaviour should be to take the host flavour when no flavour is specified (particularly with `should_remap_host_platform`).
