### ISSUE TITLE
`buck --help` should work outside of project directories

### ISSUE THREAD

**Issue by rivy** [facebook/buck#2050]
```
C:> ver
Microsoft Windows [Version 10.0.16299.611]
C:> buck version
buck version 2018.08.27.01
```

Currently, `buck --help` gives an error if executed outside of a project directory containing ".buckconfig".

```
C:> buck --help
This does not appear to be the root of a Buck project. Please 'cd'
to the root of your project before running buck. If this really is
the root of your project, run
'touch .buckconfig'
and then re-run your buck command.
Traceback (most recent call last):
...
...
NoBuckConfigFoundException: This does not appear to be the root of a Buck project. Please 'cd'
to the root of your project before running buck. If this really is
the root of your project, run
'touch .buckconfig'
and then re-run your buck command.
```

IMO, this is newbie unfriendly.

Additionally, the error message shouldn't, in general, include a "Traceback" unless requested by the user (via a debug option). It distracts from the actual message.

**Comment by abranhe** [comment]
Yeah it sucks that we need to be inside a buck project with a `.buckconfig` file to be able to run 

```
buck --help
``` 

and 

```
buck --version
```

@rivy I guess `--version` should also work outside the project directory along with `--help`

**Comment by HamidRiazi** [comment]
Hi I have a problem with buck.
I've installed buck on my Ubuntu.
Although it runs in BUCK directory, it doesn't run in ONOS directory.

**Comment by rivy** [comment]
# ☠️ 
* no response for greater than 6 months ; closing as DOA
