### ISSUE TITLE
binary packages

### ISSUE THREAD

**Issue by dulmandakh** [facebook/buck#2053]
is buck stopped producing binary builds, like Debian packages, brew bottles since the latest version? or is it a mistake?

**Comment by ttsugriy** [comment]
@philipjameson

**Comment by dulmandakh** [comment]
I'm working to use Debian package for React Native CI, instead of source code clone.

**Comment by kageiit** [comment]
@dulmandakh you can also use https://github.com/facebook/buck#prebuilt-buck-binaries

**Comment by philipjameson** [comment]
So for specific commits, you can definitely use the stuff that @kageiit  mentioned. As far as binary releases, it's a little manual at this point (I'll probably be fixing that up in the coming months as time allows to automate it completely), and the build hosts I was using were a little broken, so I didn't get back around to adding the binary packages.

Sorry for the confusion, and I'm cutting a release right now (https://github.com/facebook/buck/releases/tag/v2018.10.17.01) that should have the packages. 

Going forward we should have binaries on each release, and they should happen more frequently.

**Comment by dulmandakh** [comment]
Thank you for the response
