### ISSUE TITLE
Buck client hanging whenever a new daemon is started.

### ISSUE THREAD

**Issue by plinehan** [facebook/buck#2063]
I'm seeing hangs in Buck client whenever it starts a new daemon.  For example, after outputting this...

```
buck build foo
Starting new Buck daemon...
Parsing buck files: finished in 2.6 sec (100%)
Creating action graph: finished in 1.0 sec (100%)
Building: finished in 2.0 sec (100%) 4/4 jobs, 0 updated
  Total time: 5.7 sec
```

... the Buck client just hangs, sometimes for seconds, sometimes "forever".  If I execute `buck kill` in another terminal, the buck client exits immediately without an error code.

CTRL-C-ing out of the client works and doesn't kill the daemon, so the next time I run it doesn't hang.

I'm running off version e11805a973a817a5dd69e9cfd375bd2980a507fa, pre-built via https://jitpack.io/com/github/facebook/buck.

**Comment by bobyangyf** [comment]
Do you have daemon.flush_events_before_exit=true in your config?

**Comment by plinehan** [comment]
I did not.

I added it, and it seems to help... I can still induce the hang by being overzealous with `buck kill` invocations, but it doesn't seem to hang as much in the natural course of events.

To be explicit, this is what I added to `.buckconfig`:

```
[daemon]
        flush_events_before_exit = true
```

**Comment by bobyangyf** [comment]
I meant that it should not be set to true, because it would make for the daemon to wait for all cleanup tasks before exiting.

If you can capture jstack or get any logs uploaded to us, we can try to take a look at what might be causing the hang.

**Comment by plinehan** [comment]
Ha!  I think I figured it out.

I'm invoking Buck from inside a Makefile (don't ask) and when `make` is run in parallel (e.g. `make -j 4`) it hangs forever.  It is erroneously waiting for the (detached) Buck server process to exit.  That's why `buck kill` causes it to get unstuck.

Running make in non-parallel mode doesn't have this problem. Switching to `gmake -j 4` (I'm on a Mac) also fixes the problem.

Thanks, and sorry for the false alarm!
