### ISSUE TITLE
AAR that contains R.class has that class overwritten by Buck assumptions

### ISSUE THREAD

**Issue by jhansche** [facebook/buck#207]
The scenario here is an AAR file that has **no** resources in its `res/` directory, and has **no** `R.txt` file.  The AAR has a classes.jar that includes an `R.class` that was created as a result of what appears to be an obfuscation pass (proguard or otherwise) -- that assumption is made based on the fact that there are several other adjacent classes with single-character names:  `Q.class`, `R.class`, `S.class`, etc.  Ordinarily, if there is no R.txt, then no _resources_-related R.class should be generated for it (and this works correctly in a Gradle build, for example:  there is no `build/generated/source/r/debug/com/crashlytics/android/R.java` file, because the AAR contains no `R.txt`).

Buck appears to be assuming that **all** AAR files require an `R.class`, even if it has an empty `res/` and missing `R.txt`, so it ends up generating an empty `R.class` for that package.  However, in this case, that class ends up overwriting the `R` class that already exists in classes.jar.  That causes an error with the caching system, reporting an error due to "Multiple entries with the same key":

```
Multiple entries with same key: com/crashlytics/android/R=3040495ca6cb51bd19a9878a5a73ae8093cdb0fd and com/crashlytics/android/R=2dd42ddb490ce969a59fcfd0e692f3ee1accafad
```

Checking the `buck-out/` directory shows that the entries come from two different places:

```
buck-out//gen/aars__crashlytics-2.0.3#aar_prebuilt_jar.classes.txt:com/crashlytics/android/R 2dd42ddb490ce969a59fcfd0e692f3ee1accafad
buck-out//bin/__app#aapt_package_rdotjava_classes__/classes.txt:com/crashlytics/android/R 3040495ca6cb51bd19a9878a5a73ae8093cdb0fd
```

Presumably, the one in `#aar_prebuilt_jar.classes.txt` is the true R.class that exists in the `classes.jar` of the AAR.  The one in `#aapt_package_rdotjava_classes__/classes.txt` appears to be the automatically generated R.class as a result of the aapt resources processing.

In an effort to get past this error just to get the project to compile, I deleted the entry from the `#aapt_package_` version, and that allowed it to continue to the `smart_dex` step.  At this point I hit a `GC overhead limit exceeded` error (this is caused by `dx` not having a large enough heap size: my project requires a 3GB heap for dex to succeed).  But that's a separate issue.

After adjusting the heap size in the `dx` shell script, the dex tool itself then hit an error with:

```
java.lang.IllegalArgumentException: already added: Lcom/crashlytics/android/R;
```

It's already added because it is still trying to add both the real (obfuscated) R.class and the generated (R.txt) R.class.

I'm not sure if this should be reported as an issue to the Crashlytics team (since having an R.class in the library's own package scope can be seen as risky and should probably be avoided).  However, since all other build tools seem to work perfectly fine with this scenario, I'm going to assume that it's a bug in buck in that it generates the resources R.class for an AAR that does not want one.

An AAR that exhibits this behavior is the Crashlytics SDK (both versions 1.2.0 and 2.0.3).  The URL to download the AAR from their Maven repository:  [crashlytics-2.0.3.aar](https://sdk-user:5Y|3-ViTSt*8Hxu7Jj*97zzaC6+RUK9MPw_4kqbPMfWe4Iwc^$@twittersdk.artifactoryonline.com/twittersdk/repo/com/twitter/sdk/android/crashlytics/2.0.3/crashlytics-2.0.3.aar).

**Comment by joshzana** [comment]
Bringing this up again - this is currently breaking my code.  I want a single codebase that is buildable by both gradle and buck users.

My code depends on appCompat-v7 and consumes the following resource:

android.support.v7.appcompat.R.attr.colorPrimary

If I fully specify it like that, buck is happy, but gradle is not:

Error:(38, 55) error: package android.support.v7.appcompat.R does not exist

For the gradle build, I have to have:

com.mypackagename.R.attr.colorPrimary

But then buck is unhappy:
error: cannot find symbol
        int[] attrs = { com.mypackagename.R.attr.colorPrimary, android.R.attr.actionBarSize };
                              ^

Which I suspect is because in gradle land this resource actually gets merged into my own project's package.  

This issue has been open for a while.  Can we get an update?  Any plans to address this?

**Comment by sdwilsh** [comment]
It hasn't been a priority for the core team, to be perfectly honest.  If someone wanted to work on a PR, I'd be help to help get it merged in.

**Comment by facebook-github-bot-9** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by polycoder** [comment]
@joshzana you may want to take a look at https://github.com/facebook/buck/issues/643, we also had the same requirement of getting something to work in buck and bazel, so we made a change that allowed merging R.txt contents. Using this approach we were able to build a very large app (with several related android libraries), and still support both buck and gradle simultaneously.

**Comment by v-jizhang** [comment]
Sorry we haven't update this issue for more than 3 years. At this point, we are closing this because it is quite out of date and it is not clear if the issue still exists. Please create a new one if you still see the problem. Thank you.
