### ISSUE TITLE
[regression] 'no such module' error for '@testable import' in iOS app unit tests 

### ISSUE THREAD

**Issue by mgrebenets** [facebook/buck#2074]
So I've a project that has been built successfully with buck before.
The version of buck was `f09152d`.
Recently I've upgraded buck to commit `e1b8293` and the same project no longer builds.

The project is a mix-n-match Swift + ObjC app.
The Swift code is using some ObjC code via bridging headers.
Unit tests are written in Swift and test the app by using `import AppModule` or `@testable import AppModule`.

Since upgrading buck to `e1b8293` Swift unit tests can no longer find the host app module and compiler (`swiftc`) command fails with "no such module AppModule" error.

**Comment by mgrebenets** [comment]
The generated Xcode still works.
Well, after patching generated project wiht workarounds for https://github.com/facebook/buck/issues/1944 and https://github.com/facebook/buck/issues/1943.

**Comment by mgrebenets** [comment]
Comparing the build.trace from before and after I do see a lot of changes

the older version of buck has way more compiler flags
for example, each framework used by the host app is added to tests bundle compile command like so:

> -I -Xcc path/to/static-library-used-by-host-app.hmap
> -I -Xcc path/to/static-library-folder

now all of those entry are gone, which is probably good since test bundle doesn’t need to see those frameworks (or does it?)
e.g. CocoaPods has `inherit! :search_paths` to make all frameworks visible to host app available to tests bundle too

next is more interesting
the older version also has this flag:

> -I -Xcc path/to/host-app-binary-folder
and
> -I full/path/to/host-app-binary-folder

> -I -Xcc path/to/host-app/Bridging-Header.h

I’d assume these changes were intentional, I vaguely remember some conversation about not being able to mix bridging headers and modules
not sure exactly

but it seems that some of these flags missing is what causes the compile error I’m seeing

**Comment by mgrebenets** [comment]
It's most likely related to https://github.com/facebook/buck/issues/1918.

If I'd try to sum it up.

# Buck

If you want to `import MyApp` in your Swift tests, then `MyApp` must be built with `modular=True`.
If you want to use `modular=True`, then you *can't* use `bridging_header` (there's an error message for that now).
So if you happen to have an existing mix-n-match project with bridging header and unit tests written in Swift, you can't really use `buck`, at least the latest version.

One workaround would be to refactor all the Objective-C code exposed via bridging header into separate modules, in which case there's no need for bridging header any more.

I would love for `buck` to have the "I know what I'm doing, please add -I options for all private headers and host app modules to compile command" flag, which would bring back previous behavior.

**Comment by mgrebenets** [comment]
I've updated the sample to have super flat setup: https://github.com/mgrebenets/test-app-with-bridging-header

@robbertvanginkel Would you have any idea on what I'm doing wrong?

I've enabled `modular=True` for `apple_binary`.

<details>
<summary>BUCK</summary>
```python

apple_binary(
    name='AppBinary',
    module_name='App',
    modular=True,
    visibility=['PUBLIC'],
    entitlements_file='Sources/Entitlements.entitlements',
    preprocessor_flags=[
        '-fobjc-arc',
        '-Wno-objc-designated-initializers',
    ],
    headers=glob([
        'Sources/**/*.h',
    ]),
    exported_headers=glob([
        'Sources/**/*.h',
    ]),
    srcs=glob([
        'Sources/**/*.swift',
        'Sources/**/*.m'
    ]),
    frameworks=[
        '$SDKROOT/System/Library/Frameworks/Foundation.framework',
        '$SDKROOT/System/Library/Frameworks/UIKit.framework',
    ]
)



apple_bundle(
    name='App',
    visibility=['PUBLIC'],
    binary=':AppBinary',
    extension='app',
    info_plist='Sources/Info.plist',
    tests=[':Tests']
)

apple_test(
    name='Tests',
    # modular=True,
    info_plist='Tests/Info.plist',
    info_plist_substitutions={
        'PRODUCT_BUNDLE_IDENTIFIER': 'org.' + 'Tests',
    },
    srcs=glob([
        'Tests/**/*.swift',
        'Tests/**/*.m',
    ]),
    # test_host_app=':App',
    deps=[
        ':App',
    ],
    frameworks=[
        '$SDKROOT/System/Library/Frameworks/Foundation.framework',
        '$SDKROOT/System/Library/Frameworks/UIKit.framework',
        '$PLATFORM_DIR/Developer/Library/Frameworks/XCTest.framework',
    ]
)
```
</details>

**Comment by mgrebenets** [comment]
In the sample I’ve shared, if I capture the `swiftc` command produced by `buckw build tests`, then add `-I buck-out/gen/AppBinary\#iphonesimulator-x86_64,swift-compile`

the compilation then succeeds

`-I buck-out/gen/AppBinary\#iphonesimulator-x86_64,swift-compile` is where the following files are sitting:

```
App-Swift.h
App.o
App.swiftmodule
```

[build-command-scripts.zip](https://github.com/facebook/buck/files/2722367/build-command-scripts.zip)

**Comment by mgrebenets** [comment]
It appears to be the case only for `apple_binary` / `apple_bundle` and `apple_test` combination.

There's absolutely no issue with using `@testable import MyLib` when working with `apple_library` and `apple_test`.

**Comment by edias** [comment]
I'm having the same issue importing a mixed Objective-C/C app on another modular App with Swift and Objective-C.

The second App(Swift and Objective-C) just try to import the module `import MyModule` and I'm getting `no such module MyModule`.I already tried the bridging-header but it did not work.

Does anybody have a clear example of how to import a mixed (Objective-C/C) library as a dependency of another mixed library( Objective-C/Swift) where one of the header from the first library is imported in one fo the swift files on the second one?

**Comment by edias** [comment]
I'm actually having the same issue  in a mixed project where Swift imports Objective-C and get ` use of undeclared type`. The project is already flagged as modular but the issue remains.

Does anybody have a solution for this problem?

**Comment by v-jizhang** [comment]
Looks like we have a solution in #1918 and #1932. Please also see example https://medium.com/airbnb-engineering/building-mixed-language-ios-project-with-buck-8a903b0e3e56.
