### ISSUE TITLE
Slack workspace invitation

### ISSUE THREAD

**Issue by marlonandrade** [facebook/buck#2075]
Hello there,

Can I get an invite to join the buck slack workspace (buckbuild.slack.com)?

Also, what would be the approach to allow @booking.com to directly signup?

Cheers!

**Comment by styurin** [comment]
I've change the settings to allow @booking.com to sign-up directly. Can you try?

**Comment by marlonandrade** [comment]
Done :metal: thank you :)

**Comment by muizidn** [comment]
@styurin how can I get invitation? I am not one of the listed email domain holder.
