### ISSUE TITLE
.svn directories copied into buck-out/bin

### ISSUE THREAD

**Issue by mread** [facebook/buck#208]
Some time in the last few weeks there has been a commit which causes .svn directories to be copied into buck-out/bin. This is only an issue with Subversion 1.6 which scatters .svn directories around liberally but unfortunately we have an environment that is doing that. It appears to invalidate caches unnecessarily. Could anyone help point me at the code that might be doing this?

Thanks,
Matt.

**Comment by sdwilsh** [comment]
Are you still seeing this @mread?

**Comment by mread** [comment]
Yes I am, only older versions of subversion that dump .svn directories everywhere. If a resource pattern matches .svn then it will get included in the jar.

**Comment by sdwilsh** [comment]
One of @Coneko's two changes are the likely culprits here: https://github.com/facebook/buck/commits/f0759b0bfff1368bc715371c383dfd8c873f9991/src/com/facebook/buck/java/CopyResourcesStep.java

Neither of e0b54ac8bf0cc7a7d6cb5925cc36faab8da37d78 or da29cbe8c2bfcd9627ac229b5655d8da3940dc2d look particularly suspicious to me, however.

**Comment by sdwilsh** [comment]
Although, I'm wondering if this wasn't getting picked up before by accident.  We've not had any filtering code there.  Are you passing `include_dot_files` in your `glob`?  http://buckbuild.com/function/glob.html

**Comment by mread** [comment]
No, this was happening without explicit any include_dotfiles.

A quick hack of com.facebook.buck.java.ResourcesRootIntegrationTest where I add a directory called .dotdir and then ensure that it's not in the resulting jar file fails whether i set include_dotfiles = False or not so it looks like that parameter is being ignored completely.

Let me know if you want a patch to show that.

**Comment by sdwilsh** [comment]
If you want to give me a patch for a test, that will certainly help me get it fixed :)

**Comment by mread** [comment]
How about this?
https://github.com/LMAX-Exchange/buck/commit/cd6975def0e7805ce0c03a59b6fe9f612e209c14

**Comment by sdwilsh** [comment]
That'll do it.  Probably won't get to this until next week, however.

**Comment by marcinkosiba** [comment]
This should be fixed now. Are you still seeing this?

**Comment by mread** [comment]
Not in a position to check anymore I'm afraid. If the test in the commit I linked to above passes then we're all good. @grumpyjames may need to help make that repo visible again though as it seems to have gone dark.

**Comment by grumpyjames** [comment]
Who is this @mread guy that keeps referencing me? I have a faint memory of someone of that name, but it's starting to fade. Joking aside, it looks like we deleted LMAX-Exchange/buck in a fit of excitement at being close enough to stock buck to not need our own fork.

@marcinkosiba : Please feel free to close this, we haven't seen this problem recently, to the best of my knowledge
