### ISSUE TITLE
Publish release v2018.10.29.01 to brew

### ISSUE THREAD

**Issue by dulmandakh** [facebook/buck#2082]
Publish release v2018.10.29.01 to brew. @ttsugriy

**Comment by dulmandakh** [comment]
the new dependency for React Native

**Comment by ttsugriy** [comment]
this release has already been pushed to homebrew - https://github.com/facebook/buck/releases/tag/v2018.10.29.01 Could you please elaborate on what this task is about? :)

**Comment by philipjameson** [comment]
Should be published now, sorry about that, looks like we had some tooling fail during the publish.
