### ISSUE TITLE
[Question] buck shell commands are slow - JVM tuning needed?

### ISSUE THREAD

**Issue by benjamingorman** [facebook/buck#2092]
Hi, I've installed `buck` for the first time (very excited to try it out). However I have found that all of the buck commands are quite slow to execute in the shell. I assume this is because it takes significant time to start up the JVM to run buck.

e.g.

```
$ time buck --help &> /dev/null

real	0m0.990s
user	0m1.349s
sys	0m0.232s
```

It takes nearly a second just to run the help command. I've also tried cloning the buck-samples (https://github.com/fbsamples/bucksamples) repo and building one of the sample there. With the `hello-buck-cxx` example, buck reports the build time as `0.0 sec` however it actually takes around 5.5secs to run the command (again I assume this is due to JVM startup).

```
$ time buck run :main
Building: finished in 0.0 sec (100%) 3/3 jobs, 0 updated
  Total time: 0.0 sec
Hello, Buck

real	0m5.579s
user	0m0.268s
sys	0m0.172s
```

What can I do to ensure that buck starts up quickly?

Buck version: `2018.10.29.01`
Java version: ```java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)```
OS: `MacOS Mojave 10.14`

**Comment by mikeandmore** [comment]
I have similar issues, but I think once you have watchman installed, buck will reuse the JVM process. So it should not invoke a new JVM.

I suspect it's PEX is slow to boot.

**Comment by mikeandmore** [comment]
I just did a no-op build with no source modified at all. It takes buck 1.1 seconds to exit.

```
[nix-shell:~/workspace/dolly]$ time ./buck.pex build db_release                                                                                                                                              
Building: finished in 0.3 sec (100%) 3/3 jobs, 0 updated
  Total time: 0.3 sec

real    0m1.145s
user    0m0.499s
sys     0m0.661s
```

In contrast, if I call nailgun directly, it takes 0.6 seconds.

```
[nix-shell:~/workspace/dolly]$ time NAILGUN_SERVER=local:.buckd/sock ng com.facebook.buck.cli.Main build db_release                                                                                          
Building: finished in 0.4 sec (100%) 3/3 jobs, 0 updated
  Total time: 0.4 sec

real    0m0.634s
user    0m0.001s
sys     0m0.006s
```

**Comment by v-jizhang** [comment]
Please install watchman, buck can help you to speed up your builds.
