### ISSUE TITLE
Root logger is no longer streaming compilation errors

### ISSUE THREAD

**Issue by edsilfer** [facebook/buck#2095]
Hello! 

Compilation errors used to be send through buck's root logger, allowing users to parse them in real time by adding a custom `Handler` in `.bucklogging.properties`. After commit 16c5471c358084f63b3642b364284c63671e54f4 got merged, these logs (that were being sent with `WARNING` level) are no longer available to the custom `Handler`. After reverting the aforementioned commit, I'm able to see the logs again. A repro scenario is:

1. Write a custom `java.util.logging.Handler` and add it to `handlers` option in `.bucklogging.properties`. In this handler, override the `publish` method to print all the received logs (add no filter to it);
2. If the `Handler` is not already in the classpath, kill the daemon so that changes can take effect;
3. Add a compilation error in some target and try to build it;
4. Before 16c5471c358084f63b3642b364284c63671e54f4 the handler would receive the compilation error, after, the error log is not propagated;

Please let me know if you need any extra information, I'll be happy to provide it.

**Comment by kageiit** [comment]
cc @sbalabanov @ttsugriy

**Comment by sbalabanov** [comment]
Yes we removed custom logging (and custom exception processing) from build command in favor of generic error handler which should do all the logging and exit code transformation. This change is by design. Doesn't it work for you to hook into generic logger?

**Comment by sbalabanov** [comment]
I believe ErrorLogger does log into java logging api here:
https://github.com/facebook/buck/blob/018eaa6b2e8752655cc767cc8cd20310bdccb845/src/com/facebook/buck/cli/Main.java#L495
 
If you look to the log you will see things like that:

  [2018-11-13 11:53:04.831][warn ][command:null][tid:13][com.facebook.buck.cli.Main] Command failed:
com.facebook.buck.command.Build$BuildExecutionException: com.facebook.buck.util.exceptions.BuckUncheckedExecutionException: When building rule //src/com/facebook/buck/util/cache:cache#source-abi.
	at com.facebook.buck.command.Build.waitForBuildToFinish(Build.java:323)
	at com.facebook.buck.command.Build.waitForBuildToFinishAndPrintFailuresToEventBus(Build.java:421)
	at com.facebook.buck.command.Build.executeAndPrintFailuresToEventBus(Build.java:144)

So it reports to com.facebook.buck.cli.Main logger. Will not it suffice? If not, we can dup errors to a separate logger specifically, defaulting to devnull.

**Comment by edsilfer** [comment]
@sbalabanov we found what you mean, at first we did not understand that the error log was being published inside `LogRecord` as one of its causes. We are now looping through `LogRecord` and it works as expected. Thanks for the support!
