### ISSUE TITLE
buck doesn’t expand ${SDKROOT} in exported_preprocessor_flags defined in an apple_library rule

### ISSUE THREAD

**Issue by littlebobert** [facebook/buck#2098]
The build fails on `#import <libxml/xmlmemory.h>`. I tried the suggestion in https://github.com/facebook/buck/issues/1161 to add `-I${SDKROOT}/usr/include/libxml2` to `exported_preprocessor_flags` but that didn’t work. I also tried `-I {SDKROOT}/usr/include/libxml2` (with a space). buck doesn’t seem to expand SDKROOT, so I also tried `-I /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/include/libxml2` but that didn’t work.

Here is the entry in my BUCK file for compiling the module in question:

```
apple_library(
    name = "Core",
    visibility = ["PUBLIC"],
    swift_version = "4.2",
    bridging_header = "Core/_module/Core.h",
    headers = glob([
        "Core/**/*.h",
    ]),
    exported_headers = glob([
        'Core/**/*.h',
    ]),
    srcs = glob([
        "Core/**/*.c",
        "Core/**/*.m",
        "Core/**/*.swift",
    ], exclude = [
        "Core/API/Legacy/Resources/ProjectSettingResource.swift",
        "Core/Model/Extensions/Submittal+Helpers.swift",
    ]),
    exported_preprocessor_flags = [
        "-I /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/include/libxml2",
    ],
    deps = [
        ":Utilitu",
        "//:Starscream",
        "//:LaunchDarkly",
        "//:MagicalRecord",
        "//:Fabric",
        "//:Crashlytics",
        "//:SSZipArchive",
        "//:GoogleAnalytics",
        ":Analytics",
    ],
)
```

**Comment by littlebobert** [comment]
Ah, `exported_preprocessor_flags = ['-I/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/include/libxml2']` works, but `exported_preprocessor_flags = ['-I${SDKROOT}/usr/include/libxml2']` doesn’t. buck doesn’t seem to expand ${SDKROOT}.

**Comment by njlr** [comment]
Might be best to pull the path from the config (with a default): 

```
xcode_developer_dir = read_config('apple', 'xcode_developer_dir', '/Applications/Xcode.app/Contents/Developer')

include_path = xcode_developer_dir + '/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/include/libxml2'

...
```

I think you can pull the SDK out also, but should give you the idea.
