### ISSUE TITLE
sh_binary does not allow passing arguments to shell script

### ISSUE THREAD

**Issue by cwardgar** [facebook/buck#2099]
This isn't so much a defect report as it is a question: is it intentional that `sh_binary` does not allow one to pass command-line arguments to a shell script?

I'm aware that you can wrap `sh_binary` in a `command_alias` to provide arguments. It just seems awkward to have to do that, given that passing arguments to a `sh_binary` must be a super common use case.

**Comment by ghvg1313** [comment]
I believe you can do `buck run [sh_binary_rule] -- [args]

**Comment by cwardgar** [comment]
Very cool. It looks like the double dash isn't required; you can simply do: `buck run [sh_binary_rule][args]`. Furthermore, you can set environment variables, which will then be made available to the script, e.g. `VAR=foo buck run [sh_binary_rule] [args]`.

But suppose that you have arguments to an `sh_binary` that you want to hard-code, as part of a target definition. The only way to do that is to wrap it in a `command_alias`, correct?

**Comment by v-jizhang** [comment]
@cwardgar You are correct, that's the only way and we don't have a plan to add hard-coded args.
