### ISSUE TITLE
Deleting a file that matches the resources glob from a previously built rule fails the build until buckd is kill

### ISSUE THREAD

**Issue by mread** [facebook/buck#210]
For example a java_test rule like this:
```
java_test(
    name='my-test',
    resources=glob( 'src/test/resources/**/*' ),
)
```
is run successfully, then a file is deleted under `src/test/resources`. On the subsequent build we see:
```
BUILD FAILED: //my-test: parameter 'resources': no such file or directory 'src/test/resources/my-file'
```
Which can be cleared by a `buckd --kill`

**Comment by Coneko** [comment]
Seems to work now, probably related to the issues we had with watchman when Buck was invoking it incorrectly.

Let us know if it happens again.
