### ISSUE TITLE
Buck created too many threads

### ISSUE THREAD

**Issue by mikeandmore** [facebook/buck#2103]
Buck daemon created 138 threads when it's idle. Even though it's a java process, it's still too much.
When invoking even an no-op build, I can see all my cores are waken up, takes around 1% of CPU utilization and then fallback to sleep again.

I'm running buck on a 32 core machine.

**Comment by mikeandmore** [comment]
I just realized that it might be JVM's internal threads. So I `-XX:ParallelGCThreads=4 -XX:ConcGCThreads=4` and now there are only 83 threads for buck.

Maybe add this into the tuning guide?

**Comment by v-jizhang** [comment]
@mikeandmore Feel free to submit if you have a fix. Thanks
