### ISSUE TITLE
Buck doesn't fetch cxx_library from cache before linking go_binary

### ISSUE THREAD

**Issue by linzhp** [facebook/buck#2104]
When Buck's cache is configured to a directory outside buck-out, `buck clean` will not clean the cache (assuming this is by design), but buck-out/gen and buck-out/bin are cleaned. So during next `buck build`, Buck will fetch artifacts from cache and populate buck-out/gen and buck-out/bin whenever possible. This works in most cases except when there is a cxx_library to be linked with a go_binrary. Steps to reproduce the problem

```shell
git clone git@github.com:linzhp/buck_go_examples.git
cd buck_go_examples
buck build sqliteTest:version
buck clean
echo " " >> sqliteTest/main.go
buck build sqliteTest:version
```
Then there will be an error from the linker:
```
/usr/local/Cellar/go/1.11.2/libexec/pkg/tool/darwin_amd64/link: running /usr/bin/clang++ failed: exit status 1
ld: file not found: buck-out/gen/vendor/github.com/mattn/go-sqlite3/cxx_lib#default,static-pic/libcxx_lib.a
clang: error: linker command failed with exit code 1 (use -v to see invocation)


Building: finished in 1.2 sec (100%) 7/7 jobs, 7 updated
  Total time: 1.8 sec
Command failed with exit code 2.
stderr: /usr/local/Cellar/go/1.11.2/libexec/pkg/tool/darwin_amd64/link: running /usr/bin/clang++ failed: exit status 1
ld: file not found: buck-out/gen/vendor/github.com/mattn/go-sqlite3/cxx_lib#default,static-pic/libcxx_lib.a
clang: error: linker command failed with exit code 1 (use -v to see invocation)


    When running <go link>.
    When building rule //sqliteTest:version.
```

The issue is, during the second build, Buck fetched all go_library dependencies from the cache during the compilation, but it didn't fetch from the cache during the linking.

@mkaczanowski

**Comment by linzhp** [comment]
@nemith

**Comment by mkaczanowski** [comment]
@linzhp I am having troubles with reproducing it internally (however I have seen this behavior multiple times). Can you tell me if:
1. you can still repro it
2. do you use buckd and if yes, does the buckd restart when you run buck clean?

**Comment by linzhp** [comment]
Yes, I can still reproduce it with latest Buck from master. I use buckd, and it restarts when I run `buck clean`

**Comment by mkaczanowski** [comment]
@linzhp thanks for great repro! I found the issue and the solution.
You should expect the fix to land soon

**Comment by linzhp** [comment]
That's great! Thanks!

**Comment by mkaczanowski** [comment]
fixed in revision: https://github.com/facebook/buck/commit/afecad16e8d2ef5ed058794adca7c626e2561fa2
