### ISSUE TITLE
Cannot run DemoApp in the Simulator

### ISSUE THREAD

**Issue by Itaybre** [facebook/buck#2107]
I am trying to run the Buck sample repo but Buck doesn't seem to be able to find any simulator.
I am able to build the app, but when trying to install it in the simulator, it fails:
<img width="822" alt="captura de pantalla 2018-11-26 a la s 12 24 25" src="https://user-images.githubusercontent.com/860036/49023553-3e645d80-f176-11e8-99d5-00385de7770b.png"> 

I have `fbsimctl` installed, and running with Xcode 10.1

This is `xcrun simctl list` output: [here](https://pastebin.com/JCexvcK9)
And this is part of buck's verbose output: [here](https://pastebin.com/2E6QbEcE)
Looks like the parser doesn't expect my simctl ouput

**Comment by Itaybre** [comment]
Compiled from HEAD and it worked, seems to be a problem with the version from Homebrew

**Comment by chrisczupak** [comment]
Thanks for posting this. I ran in to this same issue as well. It took me a while to come across this thread, but re-installing Buck from HEAD worked for me also.
