### ISSUE TITLE
Buck now requires all cells to be declared at the top-level?

### ISSUE THREAD

**Issue by njlr** [facebook/buck#2108]
It seems that Buck now requires you to declare all cells at the top-level or you get this error:

> repositories.vendor-bar must exist in the root cell's cell mappings.

This is a hindrance because now you cannot nest cells without figuring out the transitive cell declarations, for example when doing sub-modules. 

I _think_ the old behaviour was to bail on conflicts, but basically allow the cells to be declared anywhere, which made more sense! 

Will this be changed back? 

Demo repo: https://github.com/njlr/buck-cells-test

**Comment by njlr** [comment]
Relavent commit:https://github.com/facebook/buck/commit/0114639193efc4934b43e00536c6dc17a8c300a8

**Comment by njlr** [comment]
Proposed solution: 

 - Starting from the root `repositories` list, we can recursively explore the cells, discovering new ones along the way. 
 - If 2 cell names point to different locations, then we can throw an error (this way cells are still canonical)
 - If a cell is not "reachable" from the root config, then we also throw an error. 

I have made an implementation here: https://github.com/njlr/buck/commit/8c5d3d417d19b5487f05f55fd93fd4d8299f6261

**Comment by nikhedonia** [comment]
Did you guys had a chance to look at this?

**Comment by bobyangyf** [comment]
This is intended behaviour. We want all cells to be declared at the root
