### ISSUE TITLE
Add support for multiple resource directories

### ISSUE THREAD

**Issue by vovkab** [facebook/buck#211]
It would be really nice if we could specify multiple resource directories, like this:

```
android_resource(
  name = 'app-res-debug',
  res = [
    'main/res',
    'debug/res',
  ]
)
```

Or allow `android_resource` to be incomplete, like:

```
android_resource(
  incomplete = true,
)
```

this way buck knows that this resource can have missed dependencies. And we can specify incomplete resources as dependencies somewhere else.

This is one of the basic features in gradle, and moving project from gradle to buck is real pain because of it. 

Here is related discussion:
https://groups.google.com/forum/#!topic/buck-build/YEu95J252rc

**Comment by csandeep** [comment]
We face the same problem as the resources are spread over gradle build variants and there is a bit of shared resources (colors etc). Would be great to have workaround / fix for this issue.

**Comment by facebook-github-bot-9** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by styurin** [comment]
It was implemented some time ago, check `android_resource` documentation: https://buckbuild.com/rule/android_resource.html
