### ISSUE TITLE
Ability to specify a build target for kotlin_home

### ISSUE THREAD

**Issue by raviagarwal7** [facebook/buck#2121]
Currently kotlin compilation can happen using the external kotlinc tool or in memory using the `kotlin_home` buck config. 
The current implementation assumes that the `kotlin_home` will always be a path in the filesystem. 

Proposal is to remove that assumption and make `kotlin_home` support a source path. The changes would mostly be to `JarBackedReflectedKotlinc`. `ExternalKotlinc` will not change much. 

Also planning to remove all the complex lookups for magically finding kotin libraries. looking at the current kotlin installation in mac (version `1.2.71`) all kotlin libraries can be found in `KOTLIN_HOME/libexec/lib` and all the executables can be found in `KOTLIN_HOME/bin`. So, we can just only lookup in `libexec/lib` subfolder and remove all other custom logic. 

we also have corresponding pull request in okbuck to move to using source paths - https://github.com/uber/okbuck/pull/748

**Comment by raviagarwal7** [comment]
cc @kageiit, @cwoodwar6, @thalescm

**Comment by thalescm** [comment]
👍 I agree with the suggested changes. 
My guess is that all this custom logic was made to support different version of kotlin on the beginning, when things weren't too stable. Seems like it's pretty safe to remove it now

**Comment by raviagarwal7** [comment]
could we please re-open it since the PR was reverted.
I can work on creating a PR on the latest master.
