### ISSUE TITLE
RFC: passing environment variables to go_test

### ISSUE THREAD

**Issue by linzhp** [facebook/buck#2125]
Some Go tests need to read some environment variables to load a different set of configurations for test environment. There is no way to pass environment variables to Go tests.

We may need to implement a `env` parameter to `go_test`, just like [java_test](https://buckbuild.com/rule/java_test.html#env).

An alternative may be making `--test-runner-env` of `buck test` available for Go. It is currently only available for Apple tests.

@mkaczanowski @nemith @styurin @philipjameson @bobyangyf @LLITCHEV What do you think?

**Comment by mkaczanowski** [comment]
I think the java_test approach is reasonable. @philipjameson @styurin what do you think?

**Comment by linzhp** [comment]
Bazel has a `--test_env` flag to pass environment variables into tests, which is another option.

**Comment by linzhp** [comment]
Looking forward to it

**Comment by mkaczanowski** [comment]
Solved in: https://github.com/facebook/buck/commit/09f844339628ff7505af416ae265844074c5842c

**Comment by linzhp** [comment]
Tested it. It works. Thank you!
