### ISSUE TITLE
Contradictory documentation around relative targets

### ISSUE THREAD

**Issue by pdillinger** [facebook/buck#2127]
I'm relatively new to buck and was trying to figure out the meaning of the recommended build command,

    buck build myapp

in what I understood to be the project root of the repository. I tried these:

    buck build :myapp
    buck build //myapp
    buck build //myapp:myapp
    ls myapp

All of which failed, which seemed incongruous based on reading https://buckbuild.com/concept/build_target.html and no (non-hidden) files in the current directory made reference to 'myapp' for buck purposes.

So I did some more reading and discovered .buckconfig files, which were hiding from my efforts to figure out with reverse engineering. Now I see that "myapp" is under an [alias] section of .buckconfig. Seems reasonable, except... the "syntax" for buck build is this:

    buck build { <build target> | <build target pattern> } . . .

And if you follow the doc links for "build target" and "build target pattern", there is no mention of aliases. In fact, the "build target" documentation says a valid build target has to contain "//" and then says two sentences later says a relative build target doesn't contain that part. Is a relative build target "valid" or not?

Anyway, between the documentation for buck build, build targets, and build target patterns, there is a missing reference to aliases.

**Comment by pdillinger** [comment]
OK - it looks like the main confusion was fixed in 402ec57a15890d423bef074bf19601abf96bb39f which has not been published to the web site. But the contradictory stuff around relative targets remains.

**Comment by carljparker** [comment]
Hi Peter, thanks for calling this out. I am working on a rewrite of the **Build Target** topic today and will address this issue. I will publish that sometime tomorrow (Friday).

**Comment by carljparker** [comment]
The updates to **Build Target** did not make it into today's doc push . . . :-P
They will be up on the public site on Monday.

**Comment by carljparker** [comment]
The new **Build Target** topic is on the site. Please take a look and let me know if you have any feedback.

https://buckbuild.com/concept/build_target.html
