### ISSUE TITLE
Buck not picking up when user toggles --java11-test-mode

### ISSUE THREAD

**Issue by claui** [facebook/buck#2156]
# Description

When I toggle the `--java11-test-mode` option, Buck sometimes doesn’t seem to notice that the mode has changed. This may lead to builds passing even though they should have failed, and builds failing even though they should have passed.

# Example

Check out the `hello-buck-java` example and change its source and target level to 11:

```
$ git clone https://github.com/fbsamples/bucksamples
[…]
$ cd bucksamples/hello-buck-java
$ sed -i.bak s/6/11/ .buckconfig
```

The changed `.buckconfig` now reads as follows:

```
[…]

[java]
  src_roots = /
  source_level = 11
  target_level = 11
```

Building the Java 11 target using Java 8 fails as expected:

```
$ jenv shell 1.8
$ java -version
java version "1.8.0_192"
Java(TM) SE Runtime Environment (build 1.8.0_192-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.192-b12, mixed mode)
$ buck build hello_buck_java
[…]
java.lang.IllegalArgumentException: invalid source release: 11
[…]
```

However, unless I run `buck clean`, **building the same Java 11 target using Java 11 fails unexpectedly:**

```
$ jenv shell 11.0
$ java -version
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment 18.9 (build 11.0.1+13)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.1+13, mixed mode)
$ buck --java11-test-mode build hello_buck_java
[…]
java.lang.IllegalArgumentException: invalid source release: 11
[…]
```

It takes `buck clean` to have the build pass again:

```
$ buck --java11-test-mode clean
$ buck --java11-test-mode build hello_buck_java
Building: finished in 1.2 sec (100%) 2/2 jobs, 2 updated
  Total time: 1.7 sec
```

But after that, **building with Java 8 succeeds even though it should fail:**

```
$ jenv shell 1.8
$ buck build hello_buck_java
Building: finished in 0.0 sec (100%) 1/1 jobs, 0 updated
  Total time: 0.0 sec
```

I need to run `buck clean` one more time if I want the Java 8 build to fail as expected:

```
$ buck clean
$ buck build hello_buck_java
[…]
java.lang.IllegalArgumentException: invalid source release: 11
[…]
```

# My environment

```
$ echo "${JAVA_HOME}"

$ /usr/libexec/java_home -v 1.8
/Library/Java/JavaVirtualMachines/jdk1.8.0_192.jdk/Contents/Home
$ /usr/libexec/java_home -v 11.0
/Library/Java/JavaVirtualMachines/openjdk-11.0.1.jdk/Contents/Home
```

# See also

Related: https://github.com/facebook/buck/issues/2037#issuecomment-452916905

> I expect to find a few more issues with additional testing.

Pinging @jtorkkola for visibility.

**Comment by jtorkkola** [comment]
`--java11-test-mode` is not a supported config option. It exists only to allow users to try the experimental Java 11 support. So we probably won't be adding any mode change detection. You need to `buck clean` before using it. Will make this clear in my original comment. Thanks for trying it out!

**Comment by claui** [comment]
@jtorkkola Can I still file issues related to the experimental Java 11 support?

**Comment by jtorkkola** [comment]
> @jtorkkola Can I still file issues related to the experimental Java 11 support?

Yes, absolutely. That would be very much appreciated! Just edited my comment to include that as well.
