### ISSUE TITLE
Transitive R resources no longer respected, is this intended? 

### ISSUE THREAD

**Issue by edisonw** [facebook/buck#218]
The following commit broke the transitive property on R resources, it looks like it's intentional but this breaks current Android projects as they are meant to be used with the transitive property. 

@natthu 

5ae51dee8043eb80c89af9242e6c937ed10ad02e is the first bad commit
commit 5ae51dee8043eb80c89af9242e6c937ed10ad02e
Author: Natthu Bharambe natthu@fb.com
Date:   Fri Aug 22 16:19:45 2014 -0700

```
Use mini-aapt to generate R.txt of android resources.

Summary:
Previously, we were invoking `aapt` to generate the R.txt file for an
android_resource() rule, and passing it resource directories from all the
transitive android_resource depenedencies.

With this diff, we use `MiniAaptStep` to generate a similar `R.txt` file,
but it only contains symbols from the android resource module and not its
transitive dependencies. Also, we only pass the first order dependencies
of the android resource rule. As a result, the ABI key also includes just
the first order deps now.
```

**Comment by reondz** [comment]
how to use resource ids from pre built aars such as AppCompact v7's "R.drawable.abc_ic_ab_back_holo_dark" as pacakge name can't be changed there.

How to solve this problem?

**Comment by sdwilsh** [comment]
See #375

**Comment by cgrushko** [comment]
Given that `android_library` only look at first-order dependencies, what is the purpose of the `android_library.deps` attribute?
