### ISSUE TITLE
Migrate the PEX code to Python 3?

### ISSUE THREAD

**Issue by njlr** [facebook/buck#2187]
Currently the PEX file launches with `#!/usr/bin/env python`, which on modern installations will be Python 3: 

https://github.com/facebook/buck/blob/master/programs/buck.py#L1

It would be preferable if Buck just worked with Python 3. 

This would also considerably simplify `timing.py`, since Python 3 includes a monotonic clock function (https://docs.python.org/3/library/time.html#time.monotonic_ns)

https://github.com/facebook/buck/blob/master/programs/timing.py

This is currently a blocker for MinGW support (https://github.com/njlr/buck/tree/feature/mingw), since we do not have `librt.so` there (only `librt.a`). 

**Would the Buck team have any objections to migrating to the PEX code to Python 3?**

It seems this process can be mostly automatic: https://docs.python.org/2/library/2to3.html

**Comment by njlr** [comment]
Probably related https://github.com/facebook/buck/issues/2184

**Comment by njlr** [comment]
Related https://github.com/facebook/buck/issues/195

**Comment by timmych** [comment]
There isn't a plan to upgrade to Python3. However, if you'd like to contribute and keep it compatible with both Python 2 and 3, feel free to submit a PR.

**Comment by v-jizhang** [comment]
Buck is compatible with Python3 now.
