### ISSUE TITLE
genrule() should support non-idempotent execution

### ISSUE THREAD

**Issue by spearce** [facebook/buck#22]
I want to use this sort of idiom to embed the version into my binary:

```python
genrule(
  name = 'git_describe',
  cmd = 'mkdir -p $(dirname $OUT); git describe HEAD >$OUT',
  srcs = [],
  out = 'resources/com/google/gerrit/common/Version',
)
```

However this requires BUCK to support an uncacheable genrule.

**Comment by Coneko** [comment]
@spearce That might not work because buckd caches the build files in memory.

Has that not been a problem?

**Comment by bolinfest** [comment]
@nickpalmer We fixed your specific case with a custom rule that does smart things: http://facebook.github.io/buck/rule/android_build_config.html

**Comment by sdwilsh** [comment]
We don't want `genrule` to be able to do this, but I filed an issue for the feature you need out of this.
