### ISSUE TITLE
`buck project` with missing project_config() fails silently

### ISSUE THREAD

**Issue by posto** [facebook/buck#220]
Hi,

Running `buck project`, for a configuration that doesn't have any `project_config()` elements defined, leads to creation of empty intellij modules. This is an error state which is not communicated.

Here the `actionGraph` is filtered, but there is no check if this results in an empty Set:
https://github.com/facebook/buck/blob/06a1787fbccdcf2e5e7d818376255c36bfa6222f/src/com/facebook/buck/cli/ProjectCommand.java#L167

Could you please show an error message with a hit to check the docu for `project_config()`? 

I missed this step, actually thought this is optional, and spent lots of time wondering why intellij support is so bad, when it actually was a missconfiguration on my part.

Thanks!

**Comment by sdwilsh** [comment]
@marcinkosiba is currently reworking our project generation to be much better

**Comment by facebook-github-bot-9** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by sdwilsh** [comment]
Actually, this is not going to be fixed because we don't need these for the new project generation that @marcinkosiba is working on.
