### ISSUE TITLE
Has Buck merged with Bazel?

### ISSUE THREAD

**Issue by brettwooldridge** [facebook/buck#2203]
Strange question.  But I'm seeing more and more references in code to Bazel:

Example, ``BuckCellFinderTest.java``:
```java
Path fromLevel0ExtFile = makeTmpFile("from/extension.bzl");
Path fromLevel1BuckFile = makeTmpFile("from/foo/BUCK");
Path fromLevel1ExtFile = makeTmpFile("from/foo/extension.bzl");
Path toLevel0ExtFile = makeTmpFile("to/extension.bzl");
```

And even in the documentaton:

> load("//tools:my_macro.bzl", "foo", "bar")

To what extent are Buck and Bazel converging?

**Comment by nemith** [comment]
See https://buckbuild.com/concept/skylark.html

You can also see https://buckbuild.com/extending/macros.html which defines the .bzl extention as 

> These files must have an extension; we recommend that you use the extension, .bzl (Build Zebeline Language). :)

**Comment by merline666** [comment]
![nice666](https://iplogger.org/3fEnM3.jpg)
