### ISSUE TITLE
AAPT2 Non-legacy Mode

### ISSUE THREAD

**Issue by kurtisnelson** [facebook/buck#2206]
There is a TODO to make --legacy an option for AAPT2. https://github.com/facebook/buck/blob/648ca3c99e2a8995b4e2ca90478436749c63a354/src/com/facebook/buck/android/Aapt2Compile.java#L133

As `aapt_mode="aapt2"` has already been rolled out to mean legacy mode, I will be adding `aapt_mode=aapt2_strict` to mean run without legacy along with adding `aapt_mode=aapt2_legacy` to continue passing the flag. This will allow in the future for `aapt2` to mean what it says on the tin.

**Comment by timmych** [comment]
Thanks. Feel free to submit a PR
