### ISSUE TITLE
SourceVersionUtils missing case labels error(s)

### ISSUE THREAD

**Issue by thoughton** [facebook/buck#2212]
Hi,

Attempting to upgrade buck via linuxbrew results in a compile error that suggests the following line requires a `//$CASES-OMITTED$` comment (or the missing cases added).

https://github.com/facebook/buck/blob/62e54e688e6e1bd7f811cbe709d53ed3ca4626c1/src/com/facebook/buck/jvm/java/abi/java8/SourceVersionUtils.java#L46

Here's the error output:
```
compile:
    [javac] Compiling 2665 source files to /tmp/buck-20190303-26433-1yxp2m4/buck-2019.01.10.01/ant-out/classes
    [javac] [compiled 589674 lines in 19272 ms: 30597.4 lines/s]
    [javac] [5002 .class files generated]
    [javac] ----------
    [javac] 1. ERROR in /tmp/buck-20190303-26433-1yxp2m4/buck-2019.01.10.01/src/com/facebook/buck/jvm/java/abi/java8/SourceVersionUtils.java (at line 27)
    [javac]     switch (version) {
    [javac]             ^^^^^^^
    [javac] The enum constant RELEASE_10 should have a corresponding case label in this enum switch on SourceVersion. To suppress this problem, add a comment //$CASES-OMITTED$ on the line above the 'default:'
```

Note there's an identical error but for `RELEASE_9` immediately afterwards too.

Version info:
```
$ javac --version
javac 10.0.2
$ java --version
openjdk 10.0.2 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4)
OpenJDK 64-Bit Server VM (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4, mixed mode)

$ brew upgrade buck
==> Upgrading 1 outdated package:
facebook/fb/buck 2018.10.29.01 -> 2019.01.10.01
^C
```

**Comment by styurin** [comment]
Compiling with Java 10 requires special flags, adding support is in the process right now.

cc @jtorkkola

**Comment by thoughton** [comment]
Ah great, thanks! That'd explain it.
Is there anywhere I can find which flags are required?

**Comment by jtorkkola** [comment]
Compiling buck with Java 10 is not and will not be supported. You can try Java 11, which will be fully supported soon.

**Comment by v-jizhang** [comment]
Buck can be built by java 11:
```
ant
./bin/buck build --config java.target_level=11 --config java.source_level=11 buck
```
