### ISSUE TITLE
  Reflective XSS

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [facebook/buck#2219]
HI！
      I am a member of the 360 Code Security Team and found two reflective XSS vulnerabilities in Buck in our Open Source Detection Project.Details are as follows：
      
![default](https://user-images.githubusercontent.com/39950310/53934883-5174bb00-40df-11e9-8fcc-73edf7ef4927.png)

    The "callback" parameter in the request is received at line 75 of the TraceDataHandler. Java , but is output directly on the page at line 80 without verification，resulting in reflective XSS。

A similar situation exists at line 69 of Reference CountedWriter. Java

**Comment by timmych** [comment]
I think this should be safe because callback is validated by CALLBACK_PATTERN regex
