### ISSUE TITLE
How to load .fbstr?

### ISSUE THREAD

**Issue by DzMonster** [facebook/buck#222]
I found a param to set in android_binary(maybe other) that could generate the .fbstr file which is no-english string.So I wonder how can I use it to load in my application so that I can reduce the resource.arsc file.
And I found resource.arsc is compressed  in Facebook Android app. That will cause extra allocation in every process.I think the team of Facebook Android certainly know about it, So why compress it?
Thanks in advance.

**Comment by sdwilsh** [comment]
It's not documented, and it's actually pretty specific to our own infrastructure.  You can't use it without replicating all that, and that isn't opened sourced.
