### ISSUE TITLE
Can ExopackageApplication/DefaultApplicationLike implements dagger's HasActivityInjector?

### ISSUE THREAD

**Issue by pedroimai** [facebook/buck#2224]
I'm configuring exopackage in my android project, now my Application is like:

 ```class QDCApplication(val appContext: Application) : DefaultApplicationLike(), HasActivityInjector{...}```

and my ExopackageApplication:
```
public class AppShell extends ExopackageApplication {
    public AppShell() {
        super(BuildConfig.EXOPACKAGE_FLAGS);
    }
}
```

When I run the app, i get the error: `java.lang.RuntimeException: br.com.querodecasamento.application.AppShell does not implement dagger.android.HasActivityInjector`.

I implemented the HasActivityInjector in the AppShell:
```
public class AppShell extends ExopackageApplication implements HasActivityInjector  {
    @Inject
    DispatchingAndroidInjector<Activity> activityDispatchingAndroidInjector;

    public AppShell() {
        super(BuildConfig.EXOPACKAGE_FLAGS);

    }

    @Override
    public DispatchingAndroidInjector<Activity> activityInjector() {
        return activityDispatchingAndroidInjector;
    }
}
```

And now the problem is:
` java.lang.NullPointerException: br.com.querodecasamento.application.AppShell.activityInjector() returned null`.

I'd like to know if Is it possible to use AndroidInjector and exopackage together. If it is, how can I configure it properly?

**Comment by Blisse** [comment]
`DispatchingAndroidInjector<>` should work fine without issues. You still need to create the Dagger `Component` to inject the class inside your `AppShell` class, before you can call `activityInjector()`, which doesn't look like you're doing in the code snippet.
