### ISSUE TITLE
Travis failure after commit "Pass in bucked id to smartdexingstep..."

### ISSUE THREAD

**Issue by brettwooldridge** [facebook/buck#2230]
@kageiit A bunch of travis-ci tests started failing after this commit cd5ceb2d70d312aa3e5dbbc677398ca46d1a1443 .

Can you take a look?

**Comment by kageiit** [comment]
Looking at the master build results - https://travis-ci.org/facebook/buck/builds/521034384

It seems the failing tests are unrelated to the changes made

**Comment by styurin** [comment]
It's no longer failing for that reason.
