### ISSUE TITLE
Slack invitation

### ISSUE THREAD

**Issue by aleksandergrzyb** [facebook/buck#2236]
Hello, [at Allegro](https://allegro.pl) we start to explore Buck for our iOS builds. 🙂 Could `@allegro.pl` be accepted as a sign up email for Buck's Slack?

Thank you!

**Comment by thedavidharris** [comment]
We are also looking into this at Ford if it's possible to allow for @ford.com emails

**Comment by StevenArmandLee** [comment]
hi, we are also looking into this. wondering if you could possibly add @fundingsocieties emails

**Comment by styurin** [comment]
Added allegro.pl, ford.com and fundingsocieties.com
