### ISSUE TITLE
how to use google-service.json with buck?

### ISSUE THREAD

**Issue by DarksKnight** [facebook/buck#2249]
how to use google-service.json with buck?

**Comment by asp2insp** [comment]
Hi, the Google Services Plugin (which consumes the google-services.json file) is built for the Gradle build system, and can't be used inside of Buck. If you can generate the resources XML files that would have been produced by the plugin, then you can include them in a Buck build using the `android_resource` rule

**Comment by DarksKnight** [comment]
> Hi, the Google Services Plugin (which consumes the google-services.json file) is built for the Gradle build system, and can't be used inside of Buck. If you can generate the resources XML files that would have been produced by the plugin, then you can include them in a Buck build using the `android_resource` rule

ok,thanks
