### ISSUE TITLE
loading buck.build docs pages results in "too many redirects" error

### ISSUE THREAD

**Issue by nergdron** [facebook/buck#2261]
when following documentation links from buck.build to pages like https://buck.build/setup/getting_started.html, chrome and firefox both error our with errors about too many redirects.

**Comment by philipjameson** [comment]
cc @JoelMarcey who moved the domain over earlier this morning. It seems something may be hanging around in cache from an incorrect configuration.

**Comment by JoelMarcey** [comment]
@nergdron Are you still getting the redirect error? I have invalidated caches, etc. and wanted to see if things are starting to become normal again. Another test is if you can check that page on another browser as well?

```
$ curl -I https://buck.build/setup/getting_started.html
HTTP/2 200 
content-type: text/html; charset=utf-8
content-length: 51198
server: GitHub.com
last-modified: Thu, 16 May 2019 16:57:43 GMT
etag: "5cdd9687-c7fe"
access-control-allow-origin: *
expires: Thu, 16 May 2019 20:38:25 GMT
cache-control: max-age=600
x-github-request-id: 3A8E:7774:6DB92B:8DE34A:5CDDC7E9
accept-ranges: bytes
date: Thu, 16 May 2019 20:28:25 GMT
via: 1.1 varnish, 1.1 673a0b042f2d20e956868556adc5417e.cloudfront.net (CloudFront)
age: 0
x-served-by: cache-bwi5039-BWI
x-cache-hits: 0
x-timer: S1558038505.332873,VS0,VE18
x-fastly-request-id: 3f16f605d87c2ba540b37d11a4ae00d70bcb80ce
vary: Accept-Encoding
x-cache: Miss from cloudfront
x-amz-cf-pop: DFW3
x-amz-cf-id: dbUCw0LQW8HhRnAzdFTlof9SgRy5p08tYioEx8uPvitkRjZWYHyFpQ==
```

**Comment by nergdron** [comment]
nope, looks good now on my end! thanks for the quick fix! :)
