### ISSUE TITLE
BUILD FAILED: the problems in category 'unused' is not analysed due to a compiler option being ignored

### ISSUE THREAD

**Issue by yangquan1982** [facebook/buck#2262]
MacOS V10.14.4 with jdk 1.8.0_212 and xcode installed.
> ==> Installing buck from facebook/fb
> ==> Cloning https://github.com/facebook/buck.git
> Updating /Users/quan.yang/Library/Caches/Homebrew/buck--git
> From https://github.com/facebook/buck
>    6109222..a7a9566  master     -> origin/master
> ==> Checking out branch master
> Already on 'master'
> Your branch is behind 'origin/master' by 1 commit, and can be fast-forwarded.
>   (use "git pull" to update your local branch)
> HEAD is now at a7a9566 Allow loading extra CA certificates for http cache
> ==> Bootstrapping buck with ant
> ==> ant
> Last 15 lines from /Users/quan.yang/Library/Logs/Homebrew/buck/01.ant:
>     [javac] At least one of the problems in category 'unused' is not analysed due to a compiler option being ignored
>     [javac] ----------
>     [javac] ----------
>     [javac] 9. INFO in /private/tmp/buck-20190519-45171-1it0w2h/src/com/facebook/buck/rules/modern/builders/ModernBuildRuleRemoteExecutionHelper.java (at line 619)
>     [javac] 	@SuppressWarnings("unused")
>     [javac] 	                  ^^^^^^^^
>     [javac] At least one of the problems in category 'unused' is not analysed due to a compiler option being ignored
>     [javac] ----------
>     [javac] 9 problems (1 error, 0 warnings, 0 info)
> 
> BUILD FAILED
> /private/tmp/buck-20190519-45171-1it0w2h/build.xml:568: The following error occurred while executing this line:
> /private/tmp/buck-20190519-45171-1it0w2h/build.xml:513: Compile failed; see the compiler error output for details.

**Comment by styurin** [comment]
It works fine for me, which version of `ant` do you use?
