### ISSUE TITLE
Not able to access Java-style resources from dependent modules in Android environment

### ISSUE THREAD

**Issue by kirillzh** [facebook/buck#2264]
I’m having an issue with loading java-style resources from another module, can’t tell if it’s okbuck or buck problem but it works in gradle with no issues. Basically I have module `A` with custom `resources` directory that contains some raw resources. The same module also provides a factory that converts some of those resources to pojos by resource name. Then I have a module `B` which is not an android app nor an instrumentation test (does have Android plugin applied though). That module `B` has unit tests that uses factory from `A` to load pojos from resources, that works fine, no issues. However, if I try to load resources from an app or instrumentation test (that depend on `A` module as well), it doesn’t see resources. As I mentioned, this works perfectly with Gradle, not sure if okbuck doesn’t generate something or if it’s simply not supported by buck…

Module `A` has this config in Gradle:
```
android {
  sourceSets {
    main.resources.srcDir 'src/resources'
  }
}
```

Which makes OkBuck generate this Buck config in module `A`:
```
original_android_library(
    name = 'src_debug',
    srcs = glob([
        'src/main/java/**/*.java',
        'src/main/java/**/*.kt',
    ]),
    source = '8',
    target = '8',
    resources = glob([
        'src/resources/**',
    ]),
    resources_root = 'src/resources',
    unbundled_resources_root = 'src/resources'
    # ...
)
```

**Comment by kirillzh** [comment]
Seems to be related to https://github.com/facebook/buck/issues/1280.

**Comment by styurin** [comment]
As mentioned in #1280, resources from `prebuilt_jar` should be including in the apk. Can you try to wrap the `A` library in `prebuilt_jar` and depend on it from the app or instrumentation test?
