### ISSUE TITLE
Genrate R.java error with some strange R.id translate

### ISSUE THREAD

**Issue by liuxyc** [facebook/buck#228]
hi,
i'm trying to move my android project to BUCK,but i got error like this:
by compare with the R.java which generated by Ant, i think the "list.name/.address/.select" should be "list_name, list_select, list_address".

is this a bug?
-------------------------error output-----
/home/liuxy/myproject/buck-out/bin/**src#dummy_r_dot_java_rdotjava_src**/com/xxxx/android/xxxx/R.java:361: error: ';' expected
    public static int list.address=0x07f01152;
                          ^
/home/liuxy/myproject/buck-out/bin/**src#dummy_r_dot_java_rdotjava_src**/com/xxxx/android/xxxx/R.java:361: error: <identifier> expected
    public static int list.address=0x07f01152;
                                  ^
/home/liuxy/myproject/buck-out/bin/**src#dummy_r_dot_java_rdotjava_src**/com/xxxx/android/xxxx/R.java:362: error: ';' expected
    public static int list.name=0x07f01153;
                          ^
/home/liuxy/myproject/buck-out/bin/**src#dummy_r_dot_java_rdotjava_src**/com/xxxx/android/xxxx/R.java:362: error: <identifier> expected
    public static int list.name=0x07f01153;
                               ^
/home/liuxy/myproject/buck-out/bin/**src#dummy_r_dot_java_rdotjava_src**/com/xxxx/android/xxxx/R.java:363: error: ';' expected
    public static int list.select=0x07f01154;
                          ^
/home/liuxy/myproject/buck-out/bin/**src#dummy_r_dot_java_rdotjava_src**/com/xxxx/android/xxxx/R.java:363: error: <identifier> expected
    public static int list.select=0x07f01154;

**Comment by keger** [comment]
No Android platform target specified. Using default: Google Inc.:Google APIs:21
The following resources were not found when processing res: 
RDotTxtEntry{idType=int, type=color, name=background, idValue=0x00000000}

**Comment by sdwilsh** [comment]
Without seeing the code, it's hard to help you.

**Comment by facebook-github-bot-9** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by sdwilsh** [comment]
This might be the same issue as #443, actually.
