### ISSUE TITLE
Buck reorders LD_PRELOAD deps

### ISSUE THREAD

**Issue by tomdz** [facebook/buck#2282]
[This code](https://github.com/facebook/buck/blob/4e4c5b7411131116bc333eb865bcf8967e9e937b/src/com/facebook/buck/features/python/PythonUtil.java#L338-L348) sorts the shared libraries intended to be preloaded before executing the python binary. This is incorrect behavior as `LD_PRELOAD` is inherently order sensitive. Since the code uses the order-preserving `ImmutableSet` everywhere to pass these along, the code should simply emit the deps in the same order.

**Comment by gnuthor** [comment]
Fixed with commit 4e29b82a429a5c2f39003cc98d4498d8e6833f7e
by @andrewjcg

**Comment by drafnel** [comment]
@tomdz have you verified that the above commit resolves this problem? @gnuthor can this issue be closed?

**Comment by gnuthor** [comment]
@drafnel Yes I think this can be closed, I assumed adding the "fixed with" after we forgot to add that to the original the commit would  autoclose but apparently it didn't
