### ISSUE TITLE
Should i try buck with kotlin android projects? 

### ISSUE THREAD

**Issue by sh3lan93** [facebook/buck#2283]
I am an android engineer and I will have to try buck for android development. I have build buck on my machine but before trying it into a real project I have some curiosity of seeing issues opened in the repo and I have found a lot of people asking about issues related to kotlin! 

So, Should I give a try to buck with kotlin or buck still not supporting kotlin yet?

**Comment by bolinfest** [comment]
Buck does support building Android apps in Kotlin. It is not as battle-tested as building Android apps in Java (and also lacks an equivalent to https://code.fb.com/android/rethinking-android-app-compilation-with-buck/), but it definitely works!

**Comment by mochadwi** [comment]
would love to try buck on personal project first
