### ISSUE TITLE
Broken links to examples in docs

### ISSUE THREAD

**Issue by Wilfred** [facebook/buck#2284]
Looking at https://buck.build/rule/ocaml_library.html

The following links ('this test' and 'for example'):

* https://github.com/facebook/buck/test/com/facebook/buck/ocaml/testdata/ocaml/clib/BUCK.fixture
* https://github.com/facebook/buck/test/com/facebook/buck/ocaml/testdata/ocaml/calc/BUCK.fixture
* https://github.com/facebook/buck/test/com/facebook/buck/ocaml/testdata/compiler_flag_macros/BUCK.fixture

Are all 404s.

**Comment by philipjameson** [comment]
Hey @Wilfred, thanks for pointing this out! I've got a diff landing shortly and I'll push the documentation after that. In the mean time, the correct links are:

https://github.com/facebook/buck/tree/master/test/com/facebook/buck/features/ocaml/testdata/ocaml/clib/BUCK.fixture
https://github.com/facebook/buck/tree/master/test/com/facebook/buck/features/ocaml/testdata/ocaml/calc/BUCK.fixture
https://github.com/facebook/buck/tree/master/test/com/facebook/buck/features/ocaml/testdata/compiler_flag_macros/BUCK.fixture
https://github.com/facebook/buck/tree/master/test/com/facebook/buck/features/ocaml/testdata/ocaml/ocaml_native_plugin/BUCK.fixture
https://github.com/facebook/buck/tree/master/test/com/facebook/buck/features/ocaml/testdata/
