### ISSUE TITLE
How to present logs when running buck tests in debug mode real time?

### ISSUE THREAD

**Issue by yiboliu** [facebook/buck#2296]
We would like to see log messages when running buck tests in debug mode. Right now we can only see test logs after the test is finished. In cases that we want to see how other threads are going when the test stops at a breakpoint, it will be way easier if we can see log messages. We can go to call stack and find those threads but in cases when threads are too many, it will be difficult to do so. Can we see log messages in runtime of buck tests?

**Comment by yiboliu** [comment]
Is this issue due to Junit bufferring all log messages and release after test is done?

**Comment by v-jizhang** [comment]
buck uses https://github.com/facebook/nailgun to start build and test, which buffers the log messages. Currently we can't check log messages in runtime.
