### ISSUE TITLE
Slack workspace invite

### ISSUE THREAD

**Issue by jeffctown** [facebook/buck#2297]
Hi!

Can I please get an invite to join the buck slack workspace?

Also, what would be the approach to allow @pandora.com to directly signup?

Thanks!

**Comment by timmych** [comment]
I added @pandora.com domain. You (and other pandora.com folks) should be able to [sign up](https://join.slack.com/t/buckbuild/signup) now.

**Comment by jeffctown** [comment]
Thank you.  👍
