### ISSUE TITLE
No library manifests found. Aborting manifest merge step.

### ISSUE THREAD

**Issue by 79144876** [facebook/buck#230]
https://github.com/facebook/buck/issues/229
How to fix it ??
Thanks.

**Comment by 79144876** [comment]
I have put my project here : https://github.com/79144876/FacebookBuckExample
You can clone it ,and then run buck build.it will error again.
May be you will find some error.
Thanks.

**Comment by sdwilsh** [comment]
Is this just a dupe of #229 ?

**Comment by FrancisToth** [comment]
Is this still an issue ? I thought this was resolved considering the e-mails we've exchanged. Would it be possible to get the example back ?

**Comment by 79144876** [comment]
Sorry.I have fix it.
Thanks.
