### ISSUE TITLE
//:main#arm: cannot coerce 'helloworld.cxx' to class com.google.common.collect.ImmutableList

### ISSUE THREAD

**Issue by AlexDreyfuss** [facebook/buck#2301]
Hey for some reason i cannon parse my main.cxx anymore. I ran: buck build :main
Can anyone assist?
Has this spmething to do with linker?
Before that i got: gnueabihf-ld: warning: cannot find entry symbol _start; defaulting to 00000000000100b8

**Comment by AlexDreyfuss** [comment]
addimd '[ ]' around the sources solved it

**Comment by philipjameson** [comment]
Hey @AlexDreyfuss, thanks for the followup. In the future it'd be handy to have an example of the build files, but we'll try to make this failure case a bit more obvious. Can you let us know what type of build rule you were trying to build?
