### ISSUE TITLE
buck error message is not explicit

### ISSUE THREAD

**Issue by pvandwalle** [facebook/buck#2318]
I'm getting this error message, which is not very explicit and not searchable on Google...
Cannot find any previous buck versions in local dewey cache

vandwalle-mbp:DBbuilder vandwalle$ buck build db-builder:
Cannot find any previous buck versions in local dewey cache
vandwalle-mbp:DBbuilder vandwalle$ more .buckconfig 
[project]
  ignore = .git, .buckd
vandwalle-mbp:DBbuilder vandwalle$ more .buckversion 
last
vandwalle-mbp:DBbuilder vandwalle$ more BUCK
COMPILER_FLAGS = [
    "-Wall",
    "-std=c++14",
    "-O3",
]

cxx_binary(
    name = "db-builder",
    headers = ["src/DictBuilder.h"],
    srcs = ["src/db-builder.cc", "src/Dictbuilder.cc", "src/pinyin_convert.cc"],
    compiler_flags = COMPILER_FLAGS,
    linker_flags = ["-lsqlite3"],
)
vandwalle-mbp:DBbuilder vandwalle$ buck --version
Cannot find any previous buck versions in local dewey cache
vandwalle-mbp:DBbuilder vandwalle$ buck --help
Cannot find any previous buck versions in local dewey cache

**Comment by philipjameson** [comment]
This is related to facebook specific infrastructure. Please use Facebook support channels for this.
