### ISSUE TITLE
Buck installation with brew tries to hit an invalid url and throws 404

### ISSUE THREAD

**Issue by mazgagan** [facebook/buck#2319]
brew install buck throws curl: (22) The requested URL returned error: 404 Not Found Trying a mirror... ==> Downloading https://www-us.apache.org/dist/commons/bcel/binaries/bcel-6.3.1-bin.tar.gz and finally gives an error Error: An exception occurred within a child process: DownloadError: Failed to download resource "ant--bcel" Download failed: https://www-us.apache.org/dist/commons/bcel/binaries/bcel-6.3.1-bin.tar.gz

The version bcel-6.3.1-bin.tar.gz does not exist in the binary- https://www-us.apache.org/dist/commons/bcel/binaries/

**Comment by gmazumder** [comment]
Looks like a homebrew issue- 
PR- https://github.com/Homebrew/homebrew-core/pull/44581

**Comment by v-jizhang** [comment]
Tested. The following commands work on macos
$ `sw_vers`
ProductName:	Mac OS X
ProductVersion:	10.14.4
BuildVersion:	18E226

```
brew tap facebook/fb
brew install buck
```
