### ISSUE TITLE
java8 no longer available?

### ISSUE THREAD

**Issue by nastymachine** [facebook/buck#2323]
I tried to  go through the getting started instructions and it asked that i run the command:
"brew cask install java8" and got the error "Error: Cask 'java8' is unavailable: No Cask with this name exists."
I did a bit of digging and discovered this thread:
https://github.com/Homebrew/homebrew-cask-versions/issues/7253

**Comment by bobyangyf** [comment]
Hello. You can use any available JDK8 for now. e.g. adoptopenjdk8
