### ISSUE TITLE
How can we profile tests that run through `buck test` ?

### ISSUE THREAD

**Issue by rarestg** [facebook/buck#2329]
Posting here because I haven't found any resources elsewhere. I'm compiling unit tests and running them with `buck test //proj/module/...`. But I want to see a flame graph of what execution calls are taking the most time.
I've integrated buck with intellij but the built-in profiler doesn't output anything. I suppose it doesn't understand what buck is doing.
Is there any way to run a profiler such as `async-profiler` (https://github.com/jvm-profiling-tools/async-profiler) on a buck test?
Thanks!

**Comment by jtorkkola** [comment]
There's no first-class support for specifically doing this, but depending on how the profiler in question works, you may have a few options here:

1. Run `buck test` with the [`--debug`](https://buck.build/command/test.html) switch, which will suspend the spawned test process and allow you to attach a debugger/tool that uses the JDWP protocol. I don't know if this applies to `async-profiler`.
2. Buck spawns external `java` processes for test runs. Point [tools.java_for_tests](https://buck.build/files-and-dirs/buckconfig.html#tools) at your own shim script that launches `java` under your profiler of choice.
3. Just manually launch JUnit under your profiler and point it at your test JAR(s).
