### ISSUE TITLE
Kotlin broken for newer SDKs due to jar file rename in sdk

### ISSUE THREAD

**Issue by elucash** [facebook/buck#2330]
Facing following problem building Kotlin projects with Buck.

```
$ buck build //...
Parsing buck files: finished in 0.6 sec
Building: finished in 0.4 sec
  Total time: 1.1 sec
Could not resolve annotations JAR location (kotlin home:/usr/local/Cellar/kotlin/1.3.50/libexec).
    When creating rule //mod/some:rule.
```

It appears that newer Kotlin SDKs have this file named as `annotations-13.0.jar`, but Buck have it specified in code literally as "annotations" (with lib-path and jar extension added)

```java
// KotlinBuckConfig.java
Path getPathToAnnotationsJar() {
   return getPathToJar("annotations");
}
```

Frankly, I have no idea what to do with it to "fix" it, how to guess versions of this jar file, what policies should be for finding it in general, etc.

For now, the workaround was to copy or symlink `annotations-13.0.jar` to `annotations.jar`. I thought I will leave it here for reference. Thank you!

**Comment by IanChilds** [comment]
Ah yes, I will fix this and have Buck look for `annotations-13.0.jar`. Thanks!
