### ISSUE TITLE
Kotlin internal modifier wired incorrectly

### ISSUE THREAD

**Issue by tyvsmith** [facebook/buck#2334]
The -module-name argument used to specify the name mangling used for Kotlin bytecode generation is incorrect. It's currently using the invokingRule shortname, which usually results in methods like

`myMethod$src_release()`

This will frequently conflict and allow expanded access from Kotlin.

The documentation states "a Gradle source set (with the exception that the test source set can access the internal declarations of main);"

Gradle uses the fully qualified module, we should probably use the full invokingRule sans the specific action after the ":" to allow tests and all other targets within one BUCK file to have access.

[KotlincToJarStepFactory.java](https://github.com/facebook/buck/blob/master/src/com/facebook/buck/jvm/kotlin/KotlincToJarStepFactory.java)

**Comment by tyvsmith** [comment]
@IanChilds @kageiit @thalescm @kurtisnelson @leland-takamine

**Comment by v-jizhang** [comment]
I believe this issue was fixed by https://github.com/facebook/buck/commit/7ddc43c4ab5883d17208e930207028144ec5b856#diff-311c95e6c277e00e1457a5ba290e0739
```
private static String getModuleName(BuildTarget invokingRule) {
    return new StringBuilder()
        .append(invokingRule.getBasePath().toString().replace(File.separatorChar, '.'))
        .append(".")
        .append(invokingRule.getShortName())
        .toString();
  }

```
