### ISSUE TITLE
How to test using the previous build?

### ISSUE THREAD

**Issue by NZ-Jaybird** [facebook/buck#2345]
If I want to run "buck test" several times without rebuilding in between, is this possible?

**Comment by NZ-Jaybird** [comment]
Alternatively is it possible to have a --filter apply to only one of the --include's in a unitTest command?

**Comment by NZ-Jaybird** [comment]
The problem is I'll modify some files during the first test run but I don't want those modifications to be included in the second test run. Therefore I need a way of running them both together or without a rebuild.

**Comment by NZ-Jaybird** [comment]
The two commands are essentially as follows.
    unitTest --all --include label1 --include label2
    unitTest --all --include label3 --filter com.package.Test

**Comment by v-jizhang** [comment]
It's not possible. As long as your modifications are in the dependency graph, they will be rebuilt.
