### ISSUE TITLE
No colors in buck output any more

### ISSUE THREAD

**Issue by davido** [facebook/buck#235]
Since last upgrade fcf6eac2ded897981abe0cfb1ed866350c4f8510 i don't see any colors in Buck output:

```
$ buck test 
Using buckd.
[-] PARSING BUCK FILES...FINISHED 0,9s
[-] BUILDING...FINISHED 0,9s
TESTING ALL TESTS
PASS     26,9s  2 Passed   0 Skipped   0 Failed   com.google.gerrit.acceptance.api.change.CheckIT
PASS     27,5s  2 Passed   0 Skipped   0 Failed   com.google.gerrit.acceptance.git.DraftChangeBlockedIT
PASS     34,1s  5 Passed   0 Skipped   0 Failed   com.google.gerrit.acceptance.api.project.ProjectIT
PASS     34,9s  3 Passed   0 Skipped   0 Failed   com.google.gerrit.acceptance.api.accounts.AccountIT
[...]
```

**Comment by sdwilsh** [comment]
I bet we have this fixed internally.  MOE didn't like some changes that I think I just managed to work through, so let's see how this looks on Monday.

**Comment by davido** [comment]
Thx. Monday sounds promising :)

**Comment by sdwilsh** [comment]
You can take a look now.  I suspect one of 416e81b5a6b13585378e05204f020be54774e728 or c1b2dd005113b30c827f32c062d72715715d3a10 fixed this for you (assuming you are using buckd).

**Comment by davido** [comment]
Thx, works now again.
