### ISSUE TITLE
XCScheme for iMessage extensions is not generated automatically

### ISSUE THREAD

**Issue by bogo** [facebook/buck#2353]
Unlike other extension types, iMessage apps do not appear to have a scheme automatically generated for them by Buck. 

This seens to be due to the fact that iMessage extensions use a different Xcode extension identifier, `com.apple.product-type.app-extension.messages`, instead of the typical `com.apple.product-type.app-extension`.

This can be worked around by manually generating the scheme, but can be confusing to a new user, since all the extensions, except for the iMessage ones, will be available for running and debugging after the initial `buck project` invocation.

Fixed by #2348.

**Comment by swgillespie** [comment]
cc @williamtwilson

**Comment by bogo** [comment]
Fixed by #2348.
