### ISSUE TITLE
`buck audit ruletype -h` causes Infinite recursion (StackOverflowError)

### ISSUE THREAD

**Issue by amonshiz** [facebook/buck#2360]
Pretty easy to replicate, just try to show help text for `buck audit ruletype`

Maybe because that class uses `@Argument` instead of `@Option`? https://github.com/facebook/buck/blob/c56e56a5977550f05feaf7a70d271f5508faa195/src/com/facebook/buck/cli/AuditRuleTypeCommand.java#L47-L48

This gist has the crash stack trace: https://gist.github.com/amonshiz/358e4d5eea2eaaa66cb96e53e2e7e634

**Comment by v-jizhang** [comment]
Hi @amonshiz, could you submit a PR?

**Comment by gracequnli** [comment]
This is fixed.
