### ISSUE TITLE
link errors resolved when cache deleted

### ISSUE THREAD

**Issue by AlexDreyfuss** [facebook/buck#2363]
Hi,

I'm running into a repetitive problem. Sometimes my application doesn't build properly. i compile C++ on linux with local cache dir
[cache]
  dir = /home/local/cache/buck
  mode = dir, http
  #http_url = http://127.0.0.1:8080
  #http_mode = readwrite
  #serve_local_cache = true
  #served_local_cache_mode = readwrite
[httpserver]
  port = 8080
I get linker errors. test.cxx:(.text.startup+0x6f0): undefined reference to `some_func'.
When i run buck clean the error returns.
But when i run buck clean and delete the cache folder then it builds fine with no error.
For some reason it uses the cache when it shouldnt.
Has anyone encountered this problem?

thanks!

**Comment by v-jizhang** [comment]
Hi @AlexDreyfuss,
I've tested using the same configuration as yours for a C++ project but could not repro the issue.
I'm using the latest buck on Ubuntu 19.10.
Do you still see the problem?

**Comment by AlexDreyfuss** [comment]
yes! i think sometimes, my code changes and buck still uses the binary in the cache even the code changed which should result in a different library.
For example, when the signature of a function in a library changes. the buck build fails at the link stage.
Buck doesn't rebuild the library which means the new signature doesn't exist yet in the library. this will result that the binary which uses the binary cannot find a certain function with the certain signature.
This will result in a link error!

Has anyone found the same problem?

**Comment by v-jizhang** [comment]
I changed a signature of a function but still could not repro the issue. Could you update to the latest buck and try again?

**Comment by AlexDreyfuss** [comment]
Yea, will try that
