### ISSUE TITLE
TrustKit pod to BUCK file issue

### ISSUE THREAD

**Issue by edias** [facebook/buck#2366]
I'm trying to convert TrustKit pod to BUCK but I'm getting

`
Pods/TrustKit/TrustKit/Pinning/public_key_utils.m:208:16: error: implicit conversion of 'int' to 'NSData *' is disallowed with ARC
`

Here is my BUCK file

```
apple_library(
    name = 'TrustKit',
    visibility = ['PUBLIC'],
    headers = glob(['TrustKit/**/*.h']),
    compiler_flags =  ['-Wno-implicit-function-declaration'],
    srcs = glob(['TrustKit/**/*.m', 'TrustKit/**/*.c']),
    frameworks = [
      "$SDKROOT/System/Library/Frameworks/UIKit.framework",
      "$SDKROOT/System/Library/Frameworks/Foundation.framework",
      "$SDKROOT/System/Library/Frameworks/Foundation.Security"
  ],
)
```

Any help will be welcome

**Comment by edias** [comment]
There was an issue on the version I was using(1.4.0), updating to latest one solved the problem

**Comment by v-jizhang** [comment]
Thank you @edias.
