### ISSUE TITLE
Modular App fails to import Objective-C file in Swift

### ISSUE THREAD

**Issue by edias** [facebook/buck#2368]
I have a mixed project(Objective-C/Swift) with the following setup.

```
apple_library(
    name = "MyLib",
    visibility = ['PUBLIC'],
    modular = True,
    exported_headers = glob(['MyLib/Source/**/*.h']),
    srcs = glob(["MyLib/Source/**/*.m", "MyLib/Source/**/*.swift"]),
    frameworks = [
        '$SDKROOT/System/Library/Frameworks/Security.framework',
        '$SDKROOT/System/Library/Frameworks/Foundation.framework',
        '$SDKROOT/System/Library/Frameworks/UIKit.framework'
  ]
)
```

Some of the Swift files on this project uses Objective-C but it fails throwing `use of unresolved identifier`

**Comment by v-jizhang** [comment]
@edias I found a very good post about mixed Object-C and swift:
https://medium.com/airbnb-engineering/building-mixed-language-ios-project-with-buck-8a903b0e3e56
