### ISSUE TITLE
Accepting Tilde (~) More Generally in .buckconfig

### ISSUE THREAD

**Issue by cpsauer** [facebook/buck#2374]
Is there any way we could accept tilde (~ or $HOME) more generally in .buckconfig? It's allowed in some flags, but breaks others, like [android].sdk_path, for example.

**Comment by v-jizhang** [comment]
buck saves the configurations as immutable maps in sections and itself does not substitute any shell variables. Depending on where a configuration is used, for example, in a shell command, the variable is substituted by the shell and you will see it is allowed. On the other hand, if it is used internally, you will see it breaks.
~ is more problematic, use it directly or in a shell variable produces different results. for example, the following commands are not the same:
`mkdir -p ~/tmp/tmp1` and 
`MY_DIR=~/tmp/tmp1 mkdir -p ${MY_DIR}`
