### ISSUE TITLE
Make name of BUCK file configurable.

### ISSUE THREAD

**Issue by jart** [facebook/buck#238]
It would be awesome if I could say in my `.buckconfig`:

    [buildfile]
    name = BUILD

So I could have all my build files name BUILD instead of BUCK. Would you guys be interested in implementing such a feature? Thanks :smiley:

**Comment by Coneko** [comment]
Do you have a particular use case in mind?

Is the default file name conflicting with something in your repo?

I can see how big open source projects that want to have configurations for multiple build systems might support Buck and Pants with the same files using an option like that.

**Comment by jart** [comment]
This feature would be extremely useful for anyone working on a large existing project using a Python build system, except their build files are named BUILD and they don't want to have to rename them in order to use Buck.

**Comment by sdwilsh** [comment]
Does the syntax actually match?  We are going though this internally (we have a build system with a similar, but different syntax in `TARGETS` files), and we've used a linter and a conversion script to keep them in sync.

**Comment by jart** [comment]
It's close enough that I can write polyfills in Python that get loaded by `buildfile.includes`.

**Comment by Coneko** [comment]
It sounds reasonable enough to me. Would it be possible for you to submit a PR?

**Comment by jart** [comment]
I took a look into implementing this already and it appears to be nontrivial. Right now "BUCK" is defined as `BuckConstants#BUILD_RULES_FILE_NAME` which is referenced by a whole bunch of places. I'm guessing we'd want to move this to a method on `BuckConfig` like:

    private static final String DEFAULT_BUILD_RULES_FILE_NAME = "BUCK";

    public String getBuildRulesFileName() {
      ImmutableMap<String, String> entries = getEntriesForSection("buildfile");
      return MoreObjects.firstNonNull(entries.get("name"), DEFAULT_BUILD_RULES_FILE_NAME);
    }

The problem is that nearly all the places that reference this constant don't have access to the `BuckConfig` instance. So it then becomes a question of whether or not we want to kludge it with a static mutable variable, or refactor a whole bunch of classes to have access to `BuckConfig`, or perhaps make `BuckConfig` a singleton enum class.

These are decisions better left to the project owners. I can still do the PR if you want, but I'd appreciate guidance on the best way to proceed.

Also what's your process for assignment of copyright? Since I'd need to get the patched cleared with mine employer.

**Comment by Coneko** [comment]
Yep, new method on `BuckConfig` is the way to go.

Option two sounds great: I've just verified all the uses of `BuckConstants#BUILD_RULES_FILE_NAME` and they're either in contexts with more or less direct access to a `BuckConfig` or one of its wrappers, or they're using it to print error messages which can be modified to read "build configuration file" instead of "BUCK file".

Import statements are arranged however IntelliJ does it.
@bolinfest You use Eclipse, can you share your configurations for the Buck project?

As for the legal aspects the CLA (https://code.facebook.com/cla) should have most answers.

**Comment by jart** [comment]
Hmm, unfortunately the Facebook CLA is rejected by my employer because they couldn't agree on the terms. I wish I could write the PR for you guys, but I guess now that's out of the question :cry:

**Comment by Coneko** [comment]
Oh that's too bad. I'll do it then.

**Comment by jart** [comment]
You're amazing; thank you! :dancer:

**Comment by bolinfest** [comment]
@jart FYI, if you work at Google (which your GitHub profile says you do), then I'd talk to @spearce who is your coworker and has already navigated this and gotten approval to sign our CLA to make commits to Buck. (It took him awhile, though.)

**Comment by Coneko** [comment]
It took a while longer than expected, but I've done this, it's going to be available next time we push to github.

**Comment by jart** [comment]
I've confirmed it works. Kudos @Coneko.

**Comment by pjjw** [comment]
omg

you guys

**Comment by sdwilsh** [comment]
@pjjw - I hope that's a good omg :D
