### ISSUE TITLE
count files & lines that go into a build (tried buck audit inputs but that doesnt account for genrules)

### ISSUE THREAD

**Issue by Daij-Djan** [facebook/buck#2386]
Hi,
So based on the docs and my tests doing „buck audit input //MyBuckTarget" gets me all input files to the rule. E. G. File1.c, file2.c, resource.json, modelinput.value ...
It also includes tons of sources consumed by genrules (100s of unrelated py files) but not the files my genrules create (which would be more c files).

I’d love to get the processed results instead of the raw inputs

could also formulate this as:
Can I see all source files that get compiled for my rule?

---
I also tried #compliation-database but that isnt recursive 
I also tried replacing clang but buck invokes it temporary names and I dont know what they are

**Comment by Daij-Djan** [comment]
I also tried #compliation-database but that isnt recursive

**Comment by philipjameson** [comment]
If you set https://buck.build/files-and-dirs/buckconfig.html#build.delete_temporaries to 'false', all of the temporary files that the compiler uses will stick around after a build.

**Comment by Daij-Djan** [comment]
thanks, ill try that :)
