### ISSUE TITLE
GWT build rules pull in unwanted dependencies

### ISSUE THREAD

**Issue by Coneko** [facebook/buck#239]
Quoted from https://github.com/facebook/buck/issues/109#issuecomment-71261664

> I've spent some time to understand why small extension to Gerrit GWT Plugin API worked as expected in standalone build mode, but failed to compile in Gerrit tree mode: [1]. Classpath of GWT compiler invocation was polluted with dozens of pseudo GWT modules, that interfered with this new extension.
> 
> What happened? The easiest way to see the problem is to check the source code: [2].
> 
> It turns out (it wasn't really clear to me) that the implementation reconstructs GWT modules from the dependency graph. In Gerrit tree build //gerrit-plugin-api:lib that was passed here, resolved to dozens of rules and thus the whole Gerrit server stuff was included as GWT modules and passed to the GWT compiler. Even though we used provided deps.
> 
> In standalone mode, that makes use of bucklets, the implementation is different: plugin-api.jar is fetched from Central and is used as module deps. Dependency graph here is empty, so nothing is passed in addition to GWT compiler and the classpath wasn't polluted.
> 
> I think that the reachability resolution algorithm should differentiate between provided deps and normal deps. Another option to consider is to make dependency module resolution configurable.
> 
> [1] https://gerrit-review.googlesource.com/#/c/63489
> [2] https://github.com/facebook/buck/blob/master/src/com/facebook/buck/gwt/GwtBinaryDescription.java#L115,L138

**Comment by facebook-github-bot-9** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by marcinkosiba** [comment]
FYI for anyone watching: we're not going to look at this any time soon (we'll take pull requests, obviously).
