### ISSUE TITLE
Redundant instructions in README.md

### ISSUE THREAD

**Issue by imakedon** [facebook/buck#2392]
At the beginning of the installation instructions, there is a superfluous direction to clone the repo.  I'll submit a PR to fix that in a moment.  It's gonna be my first contribution to this project.  Or anything opens source, in fact. 🤓

**Comment by imakedon** [comment]
Looks like I don't have permissions to push the feature branch addressing this issue.  Or am doing something wrong.  What's the next step?  I didn't see any info about this in the CONTRIBUTING file.

```
$ git push origin dedupInstalInstructions
remote: Permission to facebook/buck.git denied to imakedon.
fatal: unable to access 'https://github.com/facebook/buck.git/': The requested URL returned error: 403
```

**Comment by philipjameson** [comment]
Hey @imakedon . PRs on github don't work by pushing directly to a repository that you are not an administrator of. Take a look at https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request , and let us know if you're still having problems :)

**Comment by imakedon** [comment]
Merging from my fork worked fine in order to create the PR. Thanks for the info.  Now, besides waiting, Is there anything I have to do in order to have change reviewed and merged?  What's the procedure around here?

**Comment by v-jizhang** [comment]
@ imakedon, I'll import your changes to FB Phabricator and get it reviewed. If everything is good, your changes will be landed in FB buck repository and merged back to github.

**Comment by v-jizhang** [comment]
@ imakedon Thank you for your contributions, your diff has been merged.
