### ISSUE TITLE
Buck doesn't display javac warnings on successful builds

### ISSUE THREAD

**Issue by MuminKhan** [facebook/buck#2404]
I'm running a `java_library` rule that compiles but has unchecked conversion warnings. I should be able to see them in the terminal output, but no level of verbosity turns them on. The best I can get is the `javac` invocation. Instead I have to use `-Xlint:all` and `-Werror` to make my build fail so I can see them. 

Is there a buck flag that prints the command output of all invoked commands to the console?

**Comment by v-jizhang** [comment]
HI @MuminKhan , the command output can be found in one of the logs: "buck-out/log/buck-*.log"
