### ISSUE TITLE
how to get the current folder path or root folder of project in the BUCK file?

### ISSUE THREAD

**Issue by dayongfu** [facebook/buck#2408]
I have a rule something like the following, i have to use exported_linker_flags to output some link flag like  -F./ios/Packages/GT3Captcha. But  I want the path be the absolute path instead of relative path, is there any way I can get the root folder path of the project or current BUCK's full path? 

apple_library(
    name = "GT3Captcha",
    visibility = ["PUBLIC"],
    exported_linker_flags = [
        "-F",
        "./ios/Packages/GT3Captcha",
        "-framework",
        "GT3Captcha",
    ],
    exported_headers = glob([
        "GT3Captcha/GT3Captcha.framework/Headers/*.h",
    ]),
    deps = [
        # buildifier: keep sorted
        ":GT3CaptchaBundle",
    ],
)

**Comment by v-jizhang** [comment]
Could you try "$(location //ios/Packages/GT3Captcha"?

**Comment by v-jizhang** [comment]
Please see @philipjameson's comment in #2412, "Generally we don't advise using absolute paths anywhere as they tend to cause non-hermetic builds. If you just need to know what folder, relative to your project root, that the BUCK file is in, give package_name() a shot: https://buck.build/skylark/generated/package_name.html"
