### ISSUE TITLE
import os does not work

### ISSUE THREAD

**Issue by dayongfu** [facebook/buck#2412]
based on https://buck.build/function/allow_unsafe_import.html, we can use "import os" in BUCK file or bzl file, but actually it throws " 'import' not supported, use 'load' instead". Do I miss anything?

**Comment by philipjameson** [comment]
Firstly, we do not suggest you import raw python modules, and you instead use functions written purely in your .bzl files. However, if you absolutely must do this, you should be able to do:

```
with allow_unsafe_import():
    import os
```

**Comment by dayongfu** [comment]
I want to get the current folder, without import os, how can i know get the current folder?

**Comment by philipjameson** [comment]
Generally we don't advise using absolute paths anywhere as they tend to cause non-hermetic builds. If you just need to know what folder, relative to your project root, that the BUCK file is in, give `package_name()` a shot: https://buck.build/skylark/generated/package_name.html
