### ISSUE TITLE
OSO Scrubbing via linker flag

### ISSUE THREAD

**Issue by michaeleisel** [facebook/buck#2434]
I was curious if `-Wl,-oso_prefix` during link-time had been investigated yet for OSO scrubbing rather than a separate step

**Comment by v-jizhang** [comment]
@michaeleisel, If this is an old issue, please link to that issue or give more context. Thanks

**Comment by milend** [comment]
@michaeleisel Yup, it's on my todo list to add support for it! :)

**Comment by milend** [comment]
@michaeleisel: I now landed the feature in https://github.com/facebook/buck/commit/615863ef1145c70533d44f4e04fee1db377eb36c.
