### ISSUE TITLE
cannot specify preferred_linkage for different platforms for prebuilt_cxx_library

### ISSUE THREAD

**Issue by supercoolgreatcoder** [facebook/buck#2444]
an example being
```
prebuilt_cxx_library(
  name = 'mylib',
  platform_shared_lib = [
    ('android-arm', 'android-arm/libmylib.so'),
    ('linux-x86_64', linux-x86_64/libmylib.so'),
  ],
  platform_static_lib = [
    ('linux-x86_64', linux-x86_64/libmylib.a'),
  ],
  exported_headers = [
    'mylib.h',
  ],
)
```
buck complains about missing static library for arm platform:
`static_lib: expected a single match for platform android-armv, but found []`
can preferred_linkage value be specified for different platforms?
buck from 2018 release did not have this issue

**Comment by v-jizhang** [comment]
Currently buck does not support platform_preferred_linkage.
