### ISSUE TITLE
Why no release since Oct 2019?

### ISSUE THREAD

**Issue by kjing** [facebook/buck#2446]
Why there is no release since Oct 2019? What is FB long-term commitment to buck build?

**Comment by brettwooldridge** [comment]
@kageiit It seems like the brakes were suddenly applied in 2020.  The number of commits have dropped off the proverbial cliff.  Is there a change in status of the project from Facebook's side?  Has Facebook switched to a new internal build tool?

**Comment by kageiit** [comment]
I think it has to do with this announcement - https://github.com/facebook/buck/issues/2401

There are some big refactorings and re-work happening to buck which is probably why releases are frozen on the master branch. You can still pickup has from the dev branch using [jitpack](https://github.com/facebook/buck#prebuilt-buck-binaries)

**Comment by brettwooldridge** [comment]
@kageiit Thanks for the pointer!  Good to know.

**Comment by brianduff** [comment]
> I think it has to do with this announcement - #2401

Yep, that's accurate.
