### ISSUE TITLE
Back port commit 2dc13d9 from dev branch

### ISSUE THREAD

**Issue by v-jizhang** [facebook/buck#2457]
This is s fix for #2432 
It seems like Xcode 11.4 linker doesn't allow `-sdk_version` and `-platform_version` or `-<platform>_version_min` flags to be passed together or it throws this warning:
```
ld: warning: -sdk_version and -platform_version are not compatible, ignoring -sdk_version
```
With the 11.4.1 Xcode toolchain, when warnings are treated as fatal (which some apps do), `ld` errors out on both the platform_version and sdk_version being set. 
https://github.com/facebook/buck/commit/2dc13d9c83b78ca911fb31ec4de34c23fe59aeb4

**Comment by shepting** [comment]
Is this this going to be merged back? We are seeing this regularly.

**Comment by v-jizhang** [comment]
Yes, working on it.

**Comment by v-jizhang** [comment]
PR: #2468
