### ISSUE TITLE
When building rule //src/com/facebook/buck/jvm/java/abi/kotlin:kotlin

### ISSUE THREAD

**Issue by cuteworld** [facebook/buck#2466]
When I build buck, using ./bin/buck build --show-output buck, I get an error.I read issue # 2362, but it did not solve my problem.
cmd：
$ ./bin/buck build --show-output buck
Building: finished in 3.9 sec (100%) 750/1470 jobs, 38 updated
  Total time: 3.9 sec
Command failed with exit code 1.

stderr: 
    When running <javac>.
    When building rule //src/com/facebook/buck/jvm/java/abi/kotlin:kotlin.

**Comment by v-jizhang** [comment]
What is OS and java version please?

**Comment by w1217358955** [comment]
I have the same mistake

macOS 10.15.5
openjdk version "1.8.0_252"

**Comment by cuteworld** [comment]
@v-jizhang 
macos 10.15.4
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_252-b09)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.252-b09, mixed mode)

**Comment by v-jizhang** [comment]
It's weird. Could you do a fresh build, zip and attach the log file buck-out/log/buck-0.log? Please don't forget to remove your personal information from the log. Thanks.

**Comment by cuteworld** [comment]
@v-jizhang      
[buck-0.log.zip](https://github.com/facebook/buck/files/4728826/buck-0.log.zip)

**Comment by cuteworld** [comment]
@v-jizhang    
[buck-0.log.zip](https://github.com/facebook/buck/files/4728841/buck-0.log.zip)
This is another build, I tried many times and it was this error.Hope you can help me find the problem.

**Comment by v-jizhang** [comment]
@cuteworld, could you set verbose level to 10 and create another log (log.txt) by running
`./bin/buck build -v 10 --num-threads=1 buck >log.txt 2>&1`

Thanks

**Comment by cuteworld** [comment]
[log.txt](https://github.com/facebook/buck/files/4764589/log.txt)
@v-jizhang

**Comment by v-jizhang** [comment]
@cuteworld looks like your source code is old (01/21/2020?). Please clone the latest code and try again. Thanks.

**Comment by aqiang11** [comment]
I meet the same problem,did you settle the problem ?

**Comment by cuteworld** [comment]
Downloading the buck and building still has problems, but I looked at the official website and found that it can be installed directly with brew. There is no problem. Of course, I also used jenv to manage java, and deleted all java versions and reinstalled java8. Found that multiple java versions will affect the build buck. @v-jizhang  thank u！

**Comment by cuteworld** [comment]
@aqiang11  I solved this problem, I first deleted all java versions, then installed java8, and installed jenv to manage him, and then used brew to install buck.
//------------
brew tap facebook/fb
brew install buck
//--------------
I did not use the download buck package to build：
git clone https://github.com/facebook/buck.git
cd buck
ant
./bin/buck build --show-output buck

**Comment by aqiang11** [comment]
My OS is windows_x64 , I not sure if it works,let me have a try

**Comment by aqiang11** [comment]
@cuteworld My OS is windows_x64 , I not sure if it works,let me have a try

**Comment by v-jizhang** [comment]
@aqiang11 buck can be installed using Chocolatey:
`choco install buck`

**Comment by aqiang11** [comment]
@v-jizhang  thanks ,I installed it
