### ISSUE TITLE
PEX generation doesn't work on all platforms

### ISSUE THREAD

**Issue by davido** [facebook/buck#247]
It would be probably better to file this issue upstream (https://github.com/twitter/commons/), but the documentation page (http://facebook.github.io/buck/rule/python_binary.html) doesn't claim any platform specific restrictions, so filing it here.

With the Buck script quoted in this issue https://github.com/facebook/buck/issues/245 `python_binary()` rule is failing with `os.link()` not found:

```
AttributeError: 'module' object has no attribute 'link'
```
This diff fixed this:

```
--- a/third-party/py/twitter-commons/src/python/twitter/common/python/common.py
+++ b/third-party/py/twitter-commons/src/python/twitter/common/python/common.py
@@ -266,7 +266,10 @@ class Chroot(object):
     abs_src = self._rootjoin(src)
     abs_dst = os.path.join(self.chroot, dst)
     try:
-      os.link(abs_src, abs_dst)
+      if sys.platform != 'win32':
+        os.link(abs_src, abs_dst)
+      else:
+        self.copy(abs_src, abs_dst)
     except OSError as e:
       if e.errno == errno.EEXIST:
         # File already exists, skip
```

**Comment by sdwilsh** [comment]
@robarnold actually fixed this a few weeks ago; I'm working on pushing the changes right now, and I'll update that commit message to reference this (and close it).
