### ISSUE TITLE
buck run :app is saying "file not found : linker".

### ISSUE THREAD

**Issue by AyusDas** [facebook/buck#2474]
When I enter buck run :app the parsing and building of buck files are successful. However after that instead of showing the output its saying "file not found : linker" Here is a screenshot.
![Screenshot (100)](https://user-images.githubusercontent.com/45256705/84117242-d53df580-aa4e-11ea-96de-80060c572a41.png)

The OS is windows 10
buck version: 2020.05.14.01
I installed buck using Chocolatey ( choco version 0.10.15 )
jvm version "1.8.0_151"

**Comment by v-jizhang** [comment]
@AyusDas Could you share your BUCK and .buckconfig? Thanks

**Comment by AyusDas** [comment]
heres is my BUCK:

[BUCK.txt](https://github.com/facebook/buck/files/4753915/BUCK.txt)

And heres my  .buckconfig:

[.buckconfig.txt](https://github.com/facebook/buck/files/4753945/default.buckconfig.txt)


I could not directly upload BUCK and .buckconfig so I pasted their contents in text file and uploaded that. Thanks.

**Comment by v-jizhang** [comment]
@AyusDas Looks like you did not config the linker(ld). Please take a look at the following cxx examples in buck tests. You can see how [cxx] is configured in .buckconfig file:
https://github.com/facebook/buck/tree/master/test/com/facebook/buck/cxx/testdata/win_llvm_x64
https://github.com/facebook/buck/tree/master/test/com/facebook/buck/cxx/testdata/win_x64
And buck doc at https://buck.build/files-and-dirs/buckconfig.html#cxx
Hope this helps.
