### ISSUE TITLE
jitpack.io builds appear broken with upgrade to py3

### ISSUE THREAD

**Issue by zeroxoneb** [facebook/buck#2478]
I noticed that the latest release of Buck in OSS (2020.05.14.01) doesn't have a working jitpack.io build. It looks like the move to python3 broke jitpack.

Logs from the latest release builds on jitpack.io:

https://jitpack.io/com/github/facebook/buck/v2020.05.14.01/build.log

**Comment by v-jizhang** [comment]
@kageiit , jitpack build failed in release 2020.05.14.01. Looks like python3 was built on a newer linux distribution but jitpack build is running on an outdated distribution. I've created an issue https://github.com/jitpack/jitpack.io/issues/4241 to request for an upgrade to their os version. If my request should be denied, could you recompile python3 using Ubuntu 18? Thanks

**Comment by v-jizhang** [comment]
There is another issue https://jitpack.io/com/github/facebook/buck/2020.06.17.01/build.log

**Comment by v-jizhang** [comment]
@kageiit, "python_tmp/bin" is missing in the new python3 build.

**Comment by zeroxoneb** [comment]
The problem is the `--strip-components=1` arg in the tar command.  The `python-3.8-ubuntu-16.tar.gz` file doesn't have a top level `dist/` dir inside it.  I can put up a fix.

**Comment by v-jizhang** [comment]
@kageiit Could we build Py3 on jitpack? It takes some time to build but we won't have any compatibility issues.

**Comment by kageiit** [comment]
> @kageiit Could we build Py3 on jitpack? It takes some time to build but we won't have any compatibility issues.

Not sure if jitpack would kill the build. py3 takes a WHILE to build and the jitpack cloud nodes are not that powerful to begin with. I also don't know the state of packages like `build-essential` etc on their nodes. They might have runtime packages but not devel

**Comment by v-jizhang** [comment]
Got it. Thank you.
