### ISSUE TITLE
is there an existing alternative for HttpCacheApi ?

### ISSUE THREAD

**Issue by GodofGurus** [facebook/buck#2485]
Dev branch has 'Unimpmented HttpArtifactCache' https://buck.build/concept/http_cache_api.html#binary_http. 

>  Is Binary HTTP Protocol being completely deprecated in favor of Thrift Over HTTP? 

> Is there a thrift server implementation to support this protocol described here .thrift file https://github.com/facebook/buck/blob/master/src/com/facebook/buck/artifact_cache/thrift/buckcache.thrift ? 

I am maintaining an updated version of Ignite based binary implementation from an internal fork of https://github.com/uber-archive/buck-http-cache, I am wondering about the existence of thrift server implementation as an alternative before I attempt implementing my own.

**Comment by v-jizhang** [comment]
Is Binary HTTP Protocol being completely deprecated in favor of Thrift Over HTTP?
The answer is No.

Is there a thrift server implementation to support this protocol described here .thrift file https://github.com/facebook/buck/blob/master/src/com/facebook/buck/artifact_cache/thrift/buckcache.thrift ?
There is an internal one in FB but a lot features are designed for FB only and can't be opensourced. There is a consideration of making some sort of caching backend implementation in the future release but without a date yet.
