### ISSUE TITLE
Buck Project Output Enhancement

### ISSUE THREAD

**Issue by dakkad** [facebook/buck#249]
To allow interpretation of the created project and module files the output of buck project could be rendered in JSON.

For integration with IntelliJ plugin output of Project name / location -> Modules -> Source Content Roots are needed and could be extended to include other types of content root like test roots.

The current output of:

buck project --dry-run 
>Using buckd.
>[+] PROCESSING BUCK FILES...0.1s

Would ideally want JSON output of the project and module information.

**Comment by sdwilsh** [comment]
Generally, we use the `--json` argument of commands to get JSON output.

**Comment by dakkad** [comment]
That would make a lot of sense. For now I am bye-passing the requirement for the import flow.

**Comment by sdwilsh** [comment]
@marcinkosiba - I believe you or @alsutton are looking at the plugin now.  Would this be needed still?

**Comment by alsutton** [comment]
@sdwilsh I'm not convinced this is directly tied to the creation of a buck plugin. We could render the output in any format, not necessarily JSON, so if there is a need for a JSON rendered output then that should be considered, but the lack of it isn't a blocker on a plug-in being created.

**Comment by marcinkosiba** [comment]
This was opened for the plugin, plugin doesn't need this, so closing (re-open if needed).
