### ISSUE TITLE
PEX file is always re-generated, even though the source was not changed

### ISSUE THREAD

**Issue by davido** [facebook/buck#250]
PEX file is always re-generated on other platform. Given the following content of BUCK in tools directory:

```
$ cat tools/BUCK
python_binary(
  name = 'hello',
  main = 'hello.py',
)
```
`buck-out/bin/tools/hello.pex` file is always re-generated:
```
$ buck.cmd build //tools:hello
[-] PARSING BUCK FILES...FINISHED 0,0s
[-] BUILDING...FINISHED 0,5s
$ ls -all buck-out/bin/tools/hello.pex
9. Feb 21:31 buck-out/bin/tools/hello.pex
$ buck.cmd build //tools:hello
[-] PARSING BUCK FILES...FINISHED 0,0s
[-] BUILDING...FINISHED 0,5s
$ ls -all buck-out/bin/tools/hello.pex
9. Feb 21:32 buck-out/bin/tools/hello.pex
```

I suspect that a7e76c362c53f7ae9ca3e7530fd0cf6ba1e27724 may be related.

**Comment by davido** [comment]
I looked into the rule key: the key is preserved:

```
$ buck.cmd targets --show-rulekey tools:hello
//tools:hello fd4d7f62f8c1c91fe48f76f3ed74abeb78e36505
```

But new `PEX` file is generated every time the target is invoked.

**Comment by k21** [comment]
From IRC discussion it looks like no metadata directory is created in buck-out/bin/tools/.hello, which is where the old rule keys should be stored. Without it, Buck doesn't have anything to compare the new rule key against.

**Comment by sdwilsh** [comment]
Can't create . folders on Windows, so https://github.com/facebook/buck/blob/e8190a34ff10bdb55729a8a50669805f833f6a85/src/com/facebook/buck/rules/BuildInfo.java#L48 is no good.  I'm assuming we want it hidden on Windows, so we'd need to get a `DosFileAttributeView` and set it to hidden and not call it `.whatever`

**Comment by davido** [comment]
The problem was different. Artifact upload to cache was failing and as consequence the rule key was removed. 

Apparently ':' char in artifact name is invalid on other platform. This diff fixed this:

```
diff --git a/src/com/facebook/buck/rules/BuildInfoRecorder.java b/src/com/facebook/buck/rules/BuildInfoRecorder.java
old mode 100644
new mode 100755
index a3781f3..8ed6d56
--- a/src/com/facebook/buck/rules/BuildInfoRecorder.java
+++ b/src/com/facebook/buck/rules/BuildInfoRecorder.java
@@ -195,7 +195,9 @@ public class BuildInfoRecorder {
     ImmutableSet<Path> pathsToIncludeInZip = pathsToIncludeInZipBuilder.build();
     File zip;
     try {
-      zip = File.createTempFile(buildTarget.getFullyQualifiedName().replace('/', '_'), ".zip");
+      String tmp = buildTarget.getFullyQualifiedName().replace('/', '_');
+      tmp = tmp.replace(':', '-');
+      zip = File.createTempFile(tmp, ".zip");
```

**Comment by davido** [comment]
Similar issue https://github.com/facebook/buck/issues/265 but build is failing.
