### ISSUE TITLE
Slack workspace invitation

### ISSUE THREAD

**Issue by rafaelhziliao** [facebook/buck#2500]
Hello there,

Can I get an invite to join the buck slack workspace (buckbuild.slack.com)?

Cheers!

**Comment by Relesi** [comment]
opa, Hello!
I don't understand, could you please expel it!

**Comment by rafaelhziliao** [comment]
Traduzindo, queria um invite para o slack do buck

**Comment by v-jizhang** [comment]
@rafaelhziliao 
We need your email address to send an invitation. Thank you

**Comment by v-jizhang** [comment]
Sent.

**Comment by rafaelhziliao** [comment]
tks!!
