### ISSUE TITLE
dependencies should accept targets with omitted colons

### ISSUE THREAD

**Issue by perezd** [facebook/buck#252]
Assuming I had a BUCK file as so:

```
java_library(
  name = "foo",
  deps = [
    "//some/dep"
  ],
)
```

I would expect Buck to understand I am referencing a BUCK file in the some/dep folder with a name of "dep". Instead, I get:

```
BUILD FAILED: //foo parameter 'deps': cannot coerce '//some/dep' to class com.facebo
ok.buck.model.BuildTarget
```
The workaround is to define a dep as `//some/dep:dep` but that seems needlessly noisy.

**Comment by davido** [comment]
> I would expect Buck to understand I am referencing a BUCK file in the some/dep folder with a name of "dep".

In `some/dep/BUCK` file could be different artifacts you may want to depend on:
```
deps = [
    "//some/dep:bar",
    "//some/dep:baz",
    "//some/dep:qux",
    [...]
  ],
```

**Comment by perezd** [comment]
Thats fine. but it should assume the default name, if I don't specify it. Both what you've said and what I've said are supported in the model I am proposing.

**Comment by perezd** [comment]
Did a bit of analysis tonight, I think it'd be a pretty minor change around this area of the code:
https://github.com/facebook/buck/blob/master/src/com/facebook/buck/parser/BuildTargetParser.java#L120

**Comment by Coneko** [comment]
This has come up before, but we decided against it, even though we support those kind of short hand build targets on the command line.

The reason is that unlike the command line, the build files are usually read many more times than they are written to, so it makes sense to optimise for readability.

**Comment by sdwilsh** [comment]
Agreeing with @Coneko.

**Comment by perezd** [comment]
Honestly, it doesn't seem less readable. If there is a target that matches the name of the folder its in, its a clear convention. If anything, being repetitive is less readable in my opinion. I guess its all subjective, however.
