### ISSUE TITLE
Protobuf + Nano Library support

### ISSUE THREAD

**Issue by perezd** [facebook/buck#254]
Its pretty common that I want to use protocol buffers in my android applications. When I do, I like to use nano protobufs because they are much lighter on the overall application DEX method limit. This would be a nice addition to Buck.

More info on protobuf nano:
https://github.com/android/platform_external_protobuf/tree/master/java/src/main/java/com/google/protobuf/nano

More info on protobuf:
https://code.google.com/p/protobuf/

**Comment by sdwilsh** [comment]
Can you accomplish this today with `genrule`?

**Comment by perezd** [comment]
I thought those were on their way out...

**Comment by Coneko** [comment]
`genfile` is out, `genrule` is here to stay.

**Comment by perezd** [comment]
oooh ok, I think genrule might be an option here then!

**Comment by perezd** [comment]
So, I think the issue here would be that, protoc command generates raw java files, and what we really need is java class files...so I'm not sure a pure genrule will satisfy this. Ideally we'd be able to have this auto generate effectively java_library directives and point to the generate source code as the srcs of that generated java_library. Does that make any sense?

**Comment by perezd** [comment]
I was thinking of using a stub java library here w/ exported_deps, but I cannot export a genrule :/

**Comment by perezd** [comment]
From this excerpt:
srcs (defaults to []) The set of .java files to compile for this rule. If any of the files in this list end in .src.zip, then the entries in the ZIP file that end in .java will be included as ordinary inputs to compilation. This is common when using a genrule to auto-generate some Java source code that needs to be compiled with some hand-written Java code.

I have a macro with 2 things, a genrule and a java_library, Is it possible for me to reference the zip file produced by the genrule within the java_library?

**Comment by sdwilsh** [comment]
You should just be able to specify `'//path/to/genrule:rulename'` in your `srcs`, and I think it'll work.

**Comment by perezd** [comment]
You're right, that did work. Took some finagling but its WAI now.

**Comment by sdwilsh** [comment]
Cool, should we close this then?  I'm not sure we want to add explicit support (although at some point we'll add an extension API and you could add the rule to do this via that if you wanted).

**Comment by perezd** [comment]
Yeah, SGTM.
