### ISSUE TITLE
Visibility Macros

### ISSUE THREAD

**Issue by perezd** [facebook/buck#255]
It'd be nice to define a custom visibility macros, much like PUBLIC. I realize that PUBLIC is hardcoded, but it'd be cool to be able to define a custom set of visibility rules, and be able to reference them anywhere.

**Comment by Coneko** [comment]
You can define any constant you want in Python syntax in your build definition file, including lists of strings, then unpack them in the visibility argument.

`.buckconfig`:
```
[buildfile]
  includes = //core/DEFS
```

`core/DEFS`:
```
TEST_VISIBILITY = ['//test/tests/...', '//test/test-utils/...']
```

`test/test-utils/mocking/BUCK`:
```
...
  visibility = [TEST_VISIBILITY*, '//test/test-setup:mocking-setup']
}
```

Or something like that. Let me know if it doesn't work.

More information at:
http://facebook.github.io/buck/concept/buckconfig.html#buildfile

**Comment by perezd** [comment]
That should work nicely, actually. Good tip!
