### ISSUE TITLE
Guide for implementing new build rules

### ISSUE THREAD

**Issue by perezd** [facebook/buck#256]
I would like to contribute new build rules, but its pretty unclear how to do so. Can someone write up a walkthrough? Willing to beta test it!

**Comment by shs96c** [comment]
Not so much an official walk through, but a quick brain dump.

Start by implementing Description. The type parameter of the Description is referred to as the "constructor arg" for historical reasons, but the public fields of the class of the type parameter are used as the parameter names in your Buck files. (Take a look at ExportFileDescription for a lightweight example). The BuildRuleType returned by `getBuildRuleType` gives you the rule name.

Descriptions are typically named after the rule that they (uhh..) describe. That is "GenruleDescription" is the root of how a Genrule is constructed, "JavaTestDescription" is how a JavaTest is constructed and so on. Generally, you can guess the class name by taking the rule name as used in build files, un-snake-casing and appending "Description"

A Description is a factory of BuildRule instances. The Flavor of a BuildTarget can be used to make the Description return a different kind of BuildRule, but in the common case, you don't need to use them. BuildRule implementations typically extend AbstractBuildRule. To keep things simple, you can annotate fields with "@AddToRuleKey" on your BuildRule and it'll automatically be added to the RuleKey (which is used to determine whether or not a rule needs to be rebuilt)

A BuildRule is used to construct Step instances. These are the things that actually do the work, and if you're creating a new type of build rule, it's likely you'll need to add new steps. That's cool.

We like unit tests where possible, so go nuts adding them too. We use junit. If you'd like an end to end test, take a look at calling it something ending with "*IntegrationTest" (ExportFileIntegrationTest is one example). These tend to use files from "testdata" directories to run tiny builds.

Final thoughts:
* Outputs of build rules go in the "gen" directory. Scratch files, that aren't outputs, can be found in the "bin" directory. You can use BuildTargets.get{Bin,Gen}Path to create a Path to one of these quickly and easily.
* A "SourcePath" is something that could either be a Path on the disk (relative to the project root) or the output of a BuildRule. Use the SourcePathResolver to get a concrete Path out of it.
* Good luck, and may the Force be with you.

**Comment by perezd** [comment]
This is great! I think I actually do care about Flavors. Do flavors allow me to run different build rules depending on what type of build rule may depend on me?

**Comment by perezd** [comment]
Also, for posterity, this git commit looks like a good atomic example of adding a new build rule:
https://github.com/LMAX-Exchange/buck/commit/3617f4a5fc3ef8d516fec41e5a0c80937b52bdf5

**Comment by sdwilsh** [comment]
That one is pretty old, and things may have changed a bit since then.  More recently there's https://github.com/facebook/buck/commit/be18959e6c32b59d4b490a7c7bfead115f150db0.

If you do implement your own rule, and wanted to add documentation on how to do it for future folks, we'd be happy to take that pull request :)

**Comment by sdwilsh** [comment]
It also sounds like you might want flavours - we use this for thrift when a `cxx_library` depends on a `thrift_library` - we use the {rule}#cxx (or something like that) version of the rule.

**Comment by perezd** [comment]
Yes, I'm thinking about protocol buffers, specifically. They have a cxx,
java, and go flavor.
