### ISSUE TITLE
cxx_library generates no output

### ISSUE THREAD

**Issue by sk-** [facebook/buck#257]
Related to issue #176, `cxx_library` does not generate any output, so it's not possible to use it directly in other rules.

For example in `weslang` (https://github.com/sk-/weslang/blob/master/java/com/deezer/research/cld2/BUCK) I need to have access to the generated `so` file, so I can create a jar file with a specific layout.

**Comment by Coneko** [comment]
`cxx_library` doesn't produce any output by default, you have to specify which output you want, and the platform to use, for example `//lib/mylibrary:mylibrary#static,default` for a static library built with the system platform or `//lib/mylibrary:mylibrary#shared,android-arm` for a shared library built with the android NDK platform.

**Comment by sk-** [comment]
Thanks for pointing that out. However, building the library in that way does not really allow me to use it, as a `soname` is being set. In my case, the soname includes the path to the library (libthird_party_cld2_cld2_full.so). Is there a way to disable that behavior?

Below is an excerpt of the command executed by `BUCK`:
```
/usr/bin/g++ -o buck-out/bin/third_party/cld2/cld2_full#default,shared/libcld2_full.so -shared -Xlinker -soname -Xlinker libthird_party_cld2_cld2_full.so ...
```

Also could you explain what flavors are and list them, so we could propose a PR to the documentation.

**Comment by Coneko** [comment]
Do you mean you set the `soname` in the BUCK file but the library overrides it when built that way?

**Comment by sk-** [comment]
That was the trick, to manually set the `soname`. Which I didn't in the first place as there is not specified in the documentation.

**Comment by Coneko** [comment]
Glad it all worked out. Yeah sorry the cxx stuff's documentation isn't completely accurate because it changes a lot constantly.
