### ISSUE TITLE
How do I join the slack channel?

### ISSUE THREAD

**Issue by AHassanSOS** [facebook/buck#2587]
Hi Team:

I'm new to buck, but not to the mono repo build system. When I tried to join the slack channel, it doesn't allow me. It allows only few selected domains. 

Could I get an invite to the slack channel?

**Comment by rajyengi** [comment]
Hey @AHassanSOS,  the slack group has an domain whitelist (by email) for joining the workspace. I can either add you directly (share your email address) or whitelist your email domain if other contributors from your company are collaborating on Buck.

**Comment by AHassanSOS** [comment]
Hi @rajyengi,

Could you white list this domain rapidsos.com?

Thank you so much.

**Comment by rajyengi** [comment]
Added - please use this link to sign up: https://join.slack.com/t/buckbuild/signup.

**Comment by askar1680** [comment]
@rajyengi Hi, can you add me please? askar.ulubayev@gmail.com
