### ISSUE TITLE
buck test --no-cache -f 'my.test.class' does not re-run tests that were marked as NOTESTS

### ISSUE THREAD

**Issue by dpursehouse** [facebook/buck#259]
Given a test class that contains the following `@BeforeClass` annotation:

```
  @BeforeClass
  public static void shouldRunUiTests() {
    final String[] RUN_FLAGS = {"yes", "y", "true"};
    String value = System.getenv("GERRIT_DEV_RUN_UI_ACCEPTANCE_TESTS");
    assume().that(value).isNotEmpty();
    assume().that(Arrays.asList(RUN_FLAGS)).contains(value.toLowerCase());
  }
```

and the environment variable `GERRIT_DEV_RUN_UI_ACCEPTANCE_TESTS` is not set, run the command:

```
buck test
```

As expected, all the tests will run except the test with the `@BeforeClass` annotation, which will be marked as `NOTESTS`:

```
...
NOTESTS <100ms  0 Passed   0 Skipped   0 Failed   com.google.gerrit.acceptance.webui.IndexIT
...
```

Now attempt to run the tests again, forcing the previously skipped one to be run by setting the environment variable:

```
buck test -f 'com.google.gerrit.acceptance.webui.IndexIT' --no-cache
```

Expected result is that the previously skipped test is now run, but it isn't:

```
Using buckd.
[-] PROCESSING BUCK FILES...FINISHED 0.4s
[-] BUILDING...FINISHED 0.2s (582/582 JOBS)
Log:
TESTING SELECTED TESTS
PASS    <100ms  4 Passed   0 Skipped   0 Failed   //tools:util_test
TESTS PASSED
```

**Comment by Coneko** [comment]
I think you need `--no-results-cache` for that.

**Comment by dpursehouse** [comment]
Aha, yes, that works.  Thanks.

:facepalm:
