### ISSUE TITLE
[Documentation] Add `cxx` section to `.buckconfig`

### ISSUE THREAD

**Issue by sk-** [facebook/buck#260]
In  https://github.com/facebook/buck/blob/30bc0522883890c4bf5e94e621a76b7b7f7063e0/src/com/facebook/buck/cxx/DefaultCxxPlatforms.java#L39 it is explained that the values can be manually configured in the `cxx` section of `.buckconfig`. However, there's no mention of the available keys for that section.

**Comment by Coneko** [comment]
The cxx rules still haven't been finalised so the documentation isn't very complete, since everything could still change. I'll see if we can figure out at least some of settings.

**Comment by sdwilsh** [comment]
Thanks for the report!  The updated docs are now live.
