### ISSUE TITLE
How to remove unused dependencies?

### ISSUE THREAD

**Issue by hiraditya** [facebook/buck#2606]
Does buck report unused dependencies? This situation arises when I remove an import from source file, and there may be unused dependencies. If there is already a feature like this then please let me know. Thanks,

**Comment by KapJI** [comment]
You can check if `buck autodeps` can detect these unused dependencies.

**Comment by hiraditya** [comment]
can you share an example on how to use `buck autodeps`? I couldn't find in the documentation.

**Comment by KapJI** [comment]
Actually `buck autodeps` should generate Java dependencies for Buck itself. And you question is relevant to https://github.com/facebook/buck/issues/1634

**Comment by KapJI** [comment]
So unfortunately, right now we don't have such tools.
