### ISSUE TITLE
Kotlin library ABI jar sometimes not available for friend_paths config

### ISSUE THREAD

**Issue by jbarr21** [facebook/buck#2614]
In some cases, the Kotlin ABI jar [will not be available](https://github.com/facebook/buck/blob/master/src/com/facebook/buck/jvm/kotlin/KotlinConfiguredCompilerFactory.java#L160) in order to be used to configure the friend_paths.

If the ABI jar target exists (which it always does for Kotlin), then shouldn't we just add a required rule so that we can wait for it to be generated instead of falling back to the original non-ABI source jar?

**Comment by KapJI** [comment]
If you're feeling that would be useful, please submit a PR 🙂
