### ISSUE TITLE
Python 3.10:  third-party python modules need update (setuptools: No module named 'symbol', pex: cannot import name 'iterable' from 'collections')

### ISSUE THREAD

**Issue by rpuntaie** [facebook/buck#2678]
I just wanted to install Buck on Archlinux and got the mentioned error.
See also https://stackoverflow.com/questions/70836444/no-module-named-symbol

Buck has its own setuptools and would need to do without "symbol" to support systems with Python 3.10:
https://github.com/facebook/buck/blob/0e72e40074e1731dd3c9068e5ed23ee10bcc75dd/third-party/py/setuptools/pkg_resources/__init__.py#L32

**Comment by Dgarc359** [comment]
+1 experiencing this issue as well

**Comment by aadsm** [comment]
This pr might fix it, I didn't actually tried it though, I only read the code: https://github.com/facebook/buck/pull/2680/commits/1e57b5c4ba1812807a90c7b15bcacb9e10fe9ef5

**Comment by rpuntaie** [comment]
It fixes "No module named 'symbol'", but then
```
third-party/py/pex/pex/base.py", line 6
ImportError: cannot import name 'Iterable' from 'collections'
```

I made the description a bit more general.

**Comment by bigfootjon** [comment]
I think the real solution might be to upgrade the vendored PEX dep

**Comment by jc65536** [comment]
> It fixes "No module named 'symbol'", but then
> 
> ```
> third-party/py/pex/pex/base.py", line 6
> ImportError: cannot import name 'Iterable' from 'collections'
> ```
> 
> I made the title a bit more general.

Could be related to this issue: https://github.com/Azure/azure-cli/issues/20444#issuecomment-1009648464

**Comment by bigfootjon** [comment]
> > It fixes "No module named 'symbol'", but then
> > 
> > ```
> > third-party/py/pex/pex/base.py", line 6
> > ImportError: cannot import name 'Iterable' from 'collections'
> > ```
> > 
> > I made the title a bit more general.
> 
> Could be related to this issue: https://github.com/Azure/azure-cli/issues/20444#issuecomment-1009648464

I believe `collections` no longer exports `Iterable` in Python3.10 right? 

Ref: https://docs.python.org/3/whatsnew/3.10.html which says:

> Remove deprecated aliases to [Collections Abstract Base Classes](https://docs.python.org/3/library/collections.abc.html#collections-abstract-base-classes) from the [collections](https://docs.python.org/3/library/collections.html#module-collections) module. (Contributed by Victor Stinner in [bpo-37324](https://bugs.python.org/issue37324).)

**Comment by aadsm** [comment]
> I believe collections no longer exports Iterable in Python3.10, it is now exported from collections.abc

Exactly. I believe that's what @jc65536 was referring to in his comment, where a solution is provided by importing the `Iterable` from `collections.abc` instead.

**Comment by aadsm** [comment]
> I think the real solution might be to upgrade the vendored PEX dep

Absolutely, is this something you're planning to work on? If yes, then I'll just cancel my PR, otherwise we can ship this one to unblock people using python 3.10.

**Comment by bigfootjon** [comment]
I went ahead and just patched the `import collections` and `import symbols` lines. Upgrading PEX is what should happen, but I don't have the expertise to do so.

**Comment by bigfootjon** [comment]
@lisroach added support, and I ported this to the OSS version. This should be available in the next weekly release
