### ISSUE TITLE
No "Quick Buck" pun in repo

### ISSUE THREAD

**Issue by nanaze** [facebook/buck#272]
Pun is so good yet does not appear at all in source:

~/buck/docs$ grep -ir 'quick buck' * | wc -l
0

Suggested fix: sed "s/quick\ start/quick\ buck/gI"

**Comment by jamesgpearce** [comment]
Isn't the point that buck is always quick so doesn't need a qualifying adjective?

**Comment by nanaze** [comment]
@jamesgpearce It's more of a marketing thing. Fast cars *look* fast, right? 

Say hi to @bolinfest for me.

**Comment by sdwilsh** [comment]
This doesn't feel worth doing.
