### ISSUE TITLE
Many Undocumented Build Rules: http://facebook.github.io/buck/

### ISSUE THREAD

**Issue by minid33** [facebook/buck#277]
When I browse the code for this project I can see that there are many undocumented build rules. For example Buck seems to be capable of building an iOS app (and do many more undocumented rules) but this is not documented here : http://facebook.github.io/buck/

Are there plans to update this page so that we can use Buck without having to read the source to identify and implement the latest capabilities of Buck?

**Comment by bolinfest** [comment]
It's generally the case that undocumented rules aren't fully baked yet,
including the iOS and OCaml ones. We will certainly document them once they
are ready to use! For now, caveat emptor.

**Comment by sdwilsh** [comment]
Yup, it's intentional that those aren't documented.  You can use them, and file issues about them, but we don't want to encourage their use yet by documenting them.

**Comment by MartinRogalla** [comment]
Thank you so much for your contributions. How stable is Buck currently for iOS? Do you have an ETA for when it will be fully supported and documented?

**Comment by sdwilsh** [comment]
We're using it internally for various parts at Facebook, but there's a long-tail of issues.  We're hoping to have something out there soon that folks can start to provide feedback on.
