### ISSUE TITLE
"buck quickstart" still puts the "target" argument in android_binary(), as well as in .buckconfig

### ISSUE THREAD

**Issue by bmihai** [facebook/buck#279]
`android_binary()` used to be the one to receive the `target=...` argument, but newer versions of buck seem to want it specified in .buckconfig.

That's ok, but `buck quickstart` places it in both .buckconfig and `apps/myapp/BUCK`'s `android_binary()`, which is confusing, since the last one doesn't do anything anymore, I believe? It's not in the manual anymore, in any case.

**Comment by Coneko** [comment]
Thanks for the report, I'm fixing it now.
