### ISSUE TITLE
Error while building gerrit 2.10.2 with buck

### ISSUE THREAD

**Issue by gs-rtummalapalli** [facebook/buck#282]
Hi,

My Gerrit version is V2.10. I want to upgrade to V2.10.2 along with Google oauth fix.

I am actually trying to build plugin gerrit-oauth-provider for my gerrit version 2.10. For this i built that plugin separately and tried to build gerrit.war with extra change guided as per http://comments.gmane.org/gmane.comp.version-control.repo/13994.

Here are the steps i followed to build gerrit

git clone --recursive https://gerrit.googlesource.com/gerrit gerrit_war_with_extra_change
cd gerrit_war_with_extra_change
git reset --hard v2.10.2
git fetch https://gerrit.googlesource.com/gerrit refs/changes/13/66313/4 && git cherry-pick FETCH_HEAD
buck build gerrit

Exception i got:

Traceback (most recent call last):
  File "/home/anjan/git/gerrit_src/anjan/buck/src/com/facebook/buck/python/pex.py", line 24, in <module>
    from twitter.common.python.pex_builder import PEXBuilder
ImportError: No module named common.python.pex_builder
Traceback (most recent call last):
  File "/home/anjan/git/gerrit_src/anjan/buck/src/com/facebook/buck/python/pex.py", line 24, in <module>
    from twitter.common.python.pex_builder import PEXBuilder
ImportError: No module named common.python.pex_builder
BUILD FAILED: //tools:pack_war failed with exit code 1:
pex

I built buck just now with the help of https://gerrit-review.googlesource.com/Documentation/dev-buck.html in directory "/home/anjan/git/gerrit_src/anjan/buck"

Python details on my system:

anjan@rtummalapalli-gsu-hyd:~/git/gerrit_src/anjan/gerrit$ python -V
Python 2.7.5+
anjan@rtummalapalli-gsu-hyd:~/git/gerrit_src/anjan/gerrit$ which python
/usr/bin/python

Platform i am using is Ubuntu 3.10

anjan@rtummalapalli-gsu-hyd:~/git/gerrit_src/anjan/gerrit_war_with_extra_change$ which buck
/home/anjan/bin/buck

anjan@rtummalapalli-gsu-hyd:~/git/gerrit_src/anjan/gerrit_war_with_extra_change$ ls -l /home/anjan/bin/
total 0
lrwxrwxrwx 1 anjan anjan 46 Apr 13 13:45 buck -> /home/anjan/git/gerrit_src/anjan/buck/bin/buck
lrwxrwxrwx 1 anjan anjan 47 Apr 13 13:45 buckd -> /home/anjan/git/gerrit_src/anjan/buck/bin/buckd

Here is my system path

anjan@rtummalapalli-gsu-hyd:~/git/gerrit_src/anjan/gerrit_war_with_extra_change$ echo $PATH
/home/anjan/bin:/usr/lib/lightdm/lightdm:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games

Can someone please help me in getting out of this exception..

**Comment by sdwilsh** [comment]
It seems like somehow our `PYTHONPATH` overrides aren't working correctly.

cc @davido in case he has any ideas

**Comment by davido** [comment]
Yeah, something special is happend on your system, because we never saw this failure.

FWIW: You don't need to build Gerrit and plugin now. Gerrit 2.10.4 contains all needed for OAuth scheme to work properly. Binary plugin distro is also available:

* https://github.com/davido/gerrit-oauth-provider/releases/tag/v0.3

**Comment by gs-rtummalapalli** [comment]
Thanks David for your email. We have upgraded our production system to 2.11

We took this plugin binary from your tag only corresponding to v 2.11

Thanks
Anjan

**Comment by davido** [comment]
Thanks for the update. I guess we can close this issue then?

**Comment by gs-rtummalapalli** [comment]
Sure.. Thank you..!

*Best Regards,*

*Ramanjaneya Kumar (Anjan)* | *Senior Build & Release Engineer* | *Gainsight
<http://www.gainsight.com/how-it-works>*

*(M) +91 99487 42929*
