### ISSUE TITLE
copy_resources fails to delete directory

### ISSUE THREAD

**Issue by mread** [facebook/buck#286]
This commit cc54390bb69dc120d7700842b74e8802fdc27e27 from @Coneko  March 25th introduces a problem during copy_resources.

The error thrown is this:
```
java.nio.file.DirectoryNotEmptyException: /xxx/buck-out/bin/test/com/facebook/buck/java/__java_test_java_tmp__/junit8251078377745712488/buck-out/bin/java/com/example/lib__resources__classes/data
	at sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:242)
	at sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:108)
	at java.nio.file.Files.deleteIfExists(Files.java:1165)
	at com.facebook.buck.io.ProjectFilesystem.createSymLink(ProjectFilesystem.java:726)
	at com.facebook.buck.step.fs.SymlinkFileStep.execute(SymlinkFileStep.java:81)
	at com.facebook.buck.step.CompositeStep.execute(CompositeStep.java:42)
	at com.facebook.buck.java.CopyResourcesStep.execute(CopyResourcesStep.java:75)
	at com.facebook.buck.step.DefaultStepRunner.runStepInternal(DefaultStepRunner.java:69)
```

You can reproduce it by applying this commit 3e364b985ef9878fb9fe289ab52d549b4415bddf and then running the following:
```
ant clean default && \
./bin/buck test //test/com/facebook/buck/java:java --filter CopyResourcesStepFailsIntegrationTest
```

I'm continuing to investigate but it looks like either order in which resources are symlinked or the types of resources that are symlinked has changed. Any help appreciated.

**Comment by Coneko** [comment]
Thanks for spotting it and providing a repro. I'll be looking into this.

**Comment by mread** [comment]
Thanks. Any news or can any pointers on where to look? I reached a dead-end but could spend some time on this later.

**Comment by mread** [comment]
The issues seems to be with the calculate of `com.facebook.buck.step.fs.SymlinkFileStep#getDesiredLinkPath`.

In old working code existing and desired were this:
```
.../java/com/example/data/looping.data
.../java/com/example/lib__resources__classes/data/looping.data
```

in the new code we seem to trim the filename from the desired link name:

```
.../java/com/example/data/looping.data
.../java/com/example/lib__resources__classes/data
```

Investigation continues...

**Comment by mread** [comment]
The hack that works for me is to add a slash at the end of the `javaPackageAsPath` when we use it as a `String` in `CopyResourceStep` line 123.
```
int lastIndex = resource.lastIndexOf(MorePaths.pathWithUnixSeparators(javaPackageAsPath) + "/");
```
Perhaps that should be the responsbility of a method in `MorePaths` though?

**Comment by Coneko** [comment]
Oh dear.

Yes, the whole trailing slash situation was pretty messy, and the reason why so much stuff was being done with strings.

We have this logic for appending a trailing slash in `AbstractUnflavoredBuildTarget` already, so as you say it's a good idea to extract it into a method in `MorePaths`.

Would you like to send a PR?

**Comment by sdwilsh** [comment]
Can we close this now that the pull request has landed?

**Comment by Coneko** [comment]
Yep! Thanks for the fix @mread, let us know if you bump into anything else.
