### ISSUE TITLE
Allow specifying buck-out per-project

### ISSUE THREAD

**Issue by ncalexan** [facebook/buck#293]
All Mozilla products built out of https://github.com/mozilla/gecko-dev build into a configurable object directory.  That object directory can be unrelated to the source directory: for example, the srcdir could be on a read only disk.  To build Mozilla products we need to be able to target many builds out of one srcdir into many objdirs.  This might look like a way to (dynamically) specify the `buck-out` directory at `topsrcdir/BUCK`, or a preference set in `topsrcdir/.buckconfig` -- although that is probably not dynamic enough.

This is similar to #185, although that was closed for suggesting _sharing_ buck-out across projects.

**Comment by sdwilsh** [comment]
I'm a little worried this is a foot-gun still.  I'm not coming up with a good way to prevent sharing of `buck-out` if we did this.

**Comment by ncalexan** [comment]
Could you associate the project with a subdirectory of `buck-out`, so that even asking to share `buck-out` across projects builds into a sandbox?  Perhaps you could hash some portion of the project state and use that to index into `buck-out`?

Personally I think this is not worth it.  At some point folks will abuse the tool.  Yes, we try to prevent footguns; but users can do things with symlinks and hard links that no program should be trying to avoid.

**Comment by sdwilsh** [comment]
It might actually be okay.  Even if someone tried to share it, the rule keys should keep us from having conflicts.

**Comment by k21** [comment]
One issue I see is if people tried to build something in two different projects that share their buck-out at the same time, that would almost definitely break unless we check for that case in Buck and only allow one of those builds at a time.
