### ISSUE TITLE
Add a way to easily build everything in a directory

### ISSUE THREAD

**Issue by luser** [facebook/buck#294]
It would be nice if I could run a simple `buck build` command that would build everything in a directory, like how for autotools projects you can simply `./configure && make`.

**Comment by grp** [comment]
Interesting. Maybe you could add a target that depends on all of them, and add an alias in .buckconfig called `all` pointing to it? Then it'd be as simple as `buck build all`.

**Comment by csdigi** [comment]
It would be nice to support the same syntax for target visibility at the command line

Build all targets under this BUCK file
buck build //package1/package2/...

Build all targets referenced  by this BUCK file
buck build //package1:all 

The same for test would be nice. IMO this much better than messing up your target structure by introducing functionless targets.

**Comment by luser** [comment]
For comparison Bazel has :all:
http://bazel.io/docs/bazel-user-manual.html#target-patterns

**Comment by sdwilsh** [comment]
I'm pretty sure @andrewjcg has a WIP patch to make `...` work on the command line.

**Comment by andrewjcg** [comment]
Yup, this is coming very soon.
