### ISSUE TITLE
Support explicitly building a shared cxx_library

### ISSUE THREAD

**Issue by luser** [facebook/buck#295]
`cxx_library` doesn't let you explicitly request that a shared library be built. I have a project that needs to build a shared library (for LD_PRELOAD usage). @sdwilsh showed me a workaround, where I can do `buck build //:rrpreload#default,shared`, but really buck should let me build the thing I need by default.

The build file in question is here:
https://github.com/luser/rr/blob/buck/BUCK

**Comment by Coneko** [comment]
You mean buck should allow you to specify in the `cxx_library` which type of output it should produce by default?

`cxx_library` will already automatically select the right type of output depending on what depends on it.

**Comment by luser** [comment]
Yes, I'd like to indicate that I want an actual shared library. rr has a shared library that it needs to use with LD_PRELOAD, so it really needs a shared library there. AFAIK there's no way for buck to automatically select anything because nothing else depends on it (rr doesn't actually link to the library).

**Comment by v-jizhang** [comment]
Sorry we haven't update this issue for more than 3 years. At this point, we are closing this because it is quite out of date and it is not clear if the issue still exists. Please create a new one if you still see the problem. Thank you.
