### ISSUE TITLE
buck rebuilding the world when a header changes

### ISSUE THREAD

**Issue by luser** [facebook/buck#298]
I've got a buckfile that describes a cxx_binary (among other things):
https://github.com/luser/rr/blob/28bee6461b876b8da356fde7f9eac78bc1acfb1f/BUCK#L76

It builds and works fine, but if I make a change to a header file, say, adding a line to:
https://github.com/luser/rr/blob/28bee6461b876b8da356fde7f9eac78bc1acfb1f/src/RecordCommand.h

...and rebuild, buck rebuilds all the object files for the binary. It should only have to rebuild RecordCommand.o and main.o, since they're the only things that include RecordCommand.h.

Here's buck-out/log/buck-0.log:
https://gist.github.com/98dc56db48e6d5ce3623

**Comment by Coneko** [comment]
Buck doesn't use header deps, so it's going to preprocess all the files any time any of the headers that can be included in them changes. It should then only recompile the post processed files that changed.

Does that match the behaviour you see?

**Comment by luser** [comment]
No. If you look at the log you can see that it's both preprocessing and compiling every header file.

**Comment by andrewjcg** [comment]
Yeah, this is the current expected behavior, as rule keys are calculated recursively, meaning that even though the preprocessed sources have changed, the rule keys for the compile jobs are still different and so we re-run the compiler.

We're working on a general solution for all rule types, similar to how we avoid re-compilation for Java rules if they're deps change in a way that doesn't affect their ABI, which will allow us to avoid re-compiling in this scenario.  Until then, this is unfortunately expected behavior.

**Comment by luser** [comment]
This is basically a deal-breaker for using buck for C++ projects, FWIW.

**Comment by andrewjcg** [comment]
Understood.  As you can imagine, getting this fixed is certainly hi-pri for us.

**Comment by facebook-github-bot-9** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by sdwilsh** [comment]
Long term, we'll want to build tooling to help folks not over-specify header changes, but for now, @andrewjcg is working on adding support for dep file tracking.

**Comment by sdwilsh** [comment]
@luser - this should be a lot better now if you wanted to check it out again.

**Comment by luser** [comment]
Finally got around to updating and trying this out again and this works as expected now. Thanks!

**Comment by sdwilsh** [comment]
Hurray!
