### ISSUE TITLE
Update to a newer version of the Android Manifest Merger

### ISSUE THREAD

**Issue by joshzana** [facebook/buck#299]
This is either a bug or something so hard to figure out that it should be documented.

I have a debug directory with it's own manifest like this:

<manifest xmlns:android="http://schemas.android.com/apk/res/android"
  package="com.joshzana"
  xmlns:tools="http://schemas.android.com/tools">

    <application
        tools:replace="android:name"
        android:name=".DebugApplication"/>
</manifest>

Which under grade gets picked up in debug build types, overriding the non-debug Application subclass.
    
With buck I have rules that look something like this:

android_manifest(
  name = 'manifest',
  skeleton = 'AndroidManifest.xml',
  deps = [
    ':debug_manifest'
  ],
)

android_resource(
  name = 'debug_manifest',
  manifest = 'build-types/debug/AndroidManifest.xml',
  deps = [ ],
)

And I get this warning:

[AndroidManifest.xml:48, AndroidManifest.xml:3] Main manifest has <application android:name='com.joshzana.MyApplication'> but library uses name='com.joshzana.DebugApplication'. 

The merged manifest in buck-out shows the wrong Application name, and my debug-only code doesn't execute.

Is there a setting I'm missing, or is just incorrect conflict handling?

**Comment by marcinkosiba** [comment]
Hey! The manifest merger wasn't intended for rewriting parts of the manifest like that and I don't think there is a way to make it do what you want. I'm guessing the problematic bit is the fact that you're merging a bunch of manifests and so you need to reference the same application name everywhere? In that case would using a genrule to replace the name be an acceptable solution?

**Comment by joshzana** [comment]
I would much prefer for that logic to live in the manifest with the "tools:*" directives.  In gradle these are called "markers" and they instruct the merger how to deal with conflicts:  http://tools.android.com/tech-docs/new-build-system/user-guide/manifest-merger#TOC-Markers    These are useful for more than just name (eg. icon, label, etc on your debug variant) so duplicating all of that in a general seems duplicative.

Do you think this is something buck could support?

**Comment by marcinkosiba** [comment]
From that link it sounds like gradle upgraded to a newer version of the Manifest merger which has the nice features you're looking for. It's something we might look at in the future but is not a high priority at the moment. If you'd like to speed that along pull requests are always welcome - the instructions under third-party/java/aosp would be a good starting point.

**Comment by facebook-github-bot-9** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by nayrmi** [comment]
If folks hit this in the future, we'd always welcome a pull request. Otherwise, this isn't needed for the time being.
