### ISSUE TITLE
buck test --filter 'foo' executes 'bar'

### ISSUE THREAD

**Issue by davido** [facebook/buck#302]
On Buck master 8204fddf60b25a3c2090f3ef0742fca5d466d562 running the following command on Gerrit master (https://github.com/gerrit-review/gerrit):

```
$ buck test -f 'com.google.gerrit.acceptance.rest.change.SubmitByMergeAlwaysIT'
Using watchman.
Using buckd.
[-] PROCESSING BUCK FILES...FINISHED 2,2s
[-] BUILDING...FINISHED 43,8s (565/565 JOBS, 565 UPDATED, 72,9% CACHE HITS)
Log:
TESTING SELECTED TESTS
PASS    <100ms  4 Passed   0 Skipped   0 Failed   //tools:util_test
ASSUME   12,4s 13 Passed   1 Skipped   0 Failed   com.google.gerrit.acceptance.rest.change.SubmitByMergeAlwaysIT
TESTS PASSED (with some assumption violations)
```

I would expect that `//tools:util_test` isn't executed.

**Comment by sdwilsh** [comment]
What kind of a test rule is that?

**Comment by davido** [comment]
The test rule that is awlays executed is the only python test rules we have:


```
  python_test(
    name = 'util_test',
    srcs = ['util_test.py'],
    deps = [':util'],
    visibility = ['PUBLIC'],
  )
```

All other tests are Java test rules.

**Comment by sdwilsh** [comment]
Yeah, the only tests that actually do any filtering is `java_test`.

**Comment by mread** [comment]
Has behaviour changed here in last month or so? We are also seeing all sorts of other rules match when we specify a filter, e.g.:

```
buck test --dry-run --filter com.package.tests.SomeTest
```
Output:

```
MATCHING TEST RULES (715):
...
```

At first glance it looks like every sh_binary rule in our project, possibly some others too. Shouldn't this only apply to java_test rules?

In fact, if I type this:
```
./bebuck targets --type java_test
```
I get sh_binary rules matching too. That didn't used to happen did it? I might raise a separate issue for that.

**Comment by sdwilsh** [comment]
This hasn't changed.  We've always only filtered for Java since filtering was implemented.

**Comment by mread** [comment]
My mistake, we define a load of rules as java _test that having nothing to do with java tests so that we can run them using labels. Sorry for hijacking this issue.

**Comment by sdwilsh** [comment]
Feel free to file issues (and/or pull requests) on getting label support on the things you need.
