### ISSUE TITLE
Buck doesn't find remote_file dependencies after buck-clean with buck cache set up

### ISSUE THREAD

**Issue by joshzana** [facebook/buck#303]
We are using buck caching in our repo, and recently are trying to switch to remote_file for our third party jar dependencies.  

If I buck clean, buck build, edit a file, then buck build again, I get errors trying to access any of my dependencies. (can't find package, symbol, etc)

Seemingly if I remove the cache directives from my config file, this works fine.

This is on buck version 8204fddf60b25a3c2090f3ef0742fca5d466d562

I've got a minimal repro at https://github.com/joshzana/buck_remote_file_clean that illustrates the issue.

**Comment by sdwilsh** [comment]
We haven't push much effort into the `remote_file` rule yet.  I wouldn't be surprised if this is broken.

**Comment by shs96c** [comment]
I'll have a look at this.

**Comment by sdwilsh** [comment]
This should have been resolved as of 1cda54af4736795c92867762058a0bd7bd9266f3
