### ISSUE TITLE
Android Instrumentation Tests

### ISSUE THREAD

**Issue by tgummerer** [facebook/buck#305]
Hi,

I've recently started exploring buck for android applications.  I've tried searching through the documentation, but couldn't find a mention of it anywhere.  Is there any support to run Android Instrumentation Tests from Buck?

Regards,
Thomas

**Comment by sdwilsh** [comment]
There's nothing preventing you from using them today, but no explicit support currently either.  It probably wouldn't be too much work to add support.

**Comment by tgummerer** [comment]
Thanks for your quick reply.  I'm interested in adding support for this, do you have any pointers on where to start?

**Comment by sdwilsh** [comment]
This is where having #256 done would be super helpful.  There is a braindump in there that would be helpful, however.

If you have more questions, let me know!

**Comment by tdrhq** [comment]
It's still possible to create an instrumentation test, just that you need to add some boilerplate. I'll explain the easier version where you're creating an instrumentation test for a library, which means it's mostly just an android_binary() that includes all your sources and your test code.

The difference is you need to specify the <instrumentation> tag in your AndroidManifest for this binary, make the instrumented package to point to the itself. (i.e. if the AndroidManifest's package is com.foo.bar, the android:targetPackage in the <instrumentation> should point to com.foo.bar):
<code>
  &lt;instrumentation
      android:name="android.test.InstrumentationTestRunner"
      android:targetPackage="com.foo.bar" />
</code>

You can then install it using buck-install, and run it manually using:
<code>
  adb shell am instrument -w com.foo.bar/android.test.InstrumentationRunner
</code>

Obviously, this isn't ideal, and we should definitely make this flow better.

**Comment by tgummerer** [comment]
Thanks!  I also found ```android_instrumentation_apk()```, which seems to work.

I did however run into a few issues trying to run the tests.  I'm trying to use the android test kit, and get the following exception when trying to run the tests via adb:
```
java.lang.NoClassDefFoundError: android.support.test.espresso.matcher.ViewMatchers$12
	at android.support.test.espresso.matcher.ViewMatchers.withId(ViewMatchers.java:393)
	at com.wueventapp.apso.activity.MainActivityTest.testSearchButtonIsShown(MainActivityTest.java:47)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at android.test.InstrumentationTestCase.runMethod(InstrumentationTestCase.java:214)
	at android.test.InstrumentationTestCase.runTest(InstrumentationTestCase.java:199)
	at android.test.ActivityInstrumentationTestCase2.runTest(ActivityInstrumentationTestCase2.java:192)
	at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:169)
	at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:154)
	at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:545)
	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1551)
```

I'm not sure what I'm missing.

I also tried to use AndroidJUnitRunner for running the tests, but android seems to be unable to find it, even though I included it as dependency for ```android_instrumentation_apk()```.  I also tried with ```android_binary()``` with the same result, getting the following error:

```
INSTRUMENTATION_RESULT: shortMsg=java.lang.ClassNotFoundException
INSTRUMENTATION_RESULT: longMsg=java.lang.ClassNotFoundException: android.support.test.runner.AndroidJUnitRunner
INSTRUMENTATION_CODE: 0
```

I'm also trying to implement support for a test rule for instrumentation tests, so they can be fully integrated with ```buck test``` but that might still take some time, as I have limited time available to do that.

**Comment by tgummerer** [comment]
I've finally got some time to play around with this, and come up with some code, but now I'm kind of stuck.  Namely, I'm trying to use the RemoteAndroidTestRunner in ddmlib, but the tests fail wit 
```
java.lang.NoClassDefFoundError: org/kxml2/io/KXmlSerializer
	at com.android.ddmlib.testrunner.XmlTestRunListener.generateDocument(XmlTestRunListener.java:146)
	at com.android.ddmlib.testrunner.XmlTestRunListener.testRunEnded(XmlTestRunListener.java:134)
	at com.android.ddmlib.testrunner.InstrumentationResultParser.handleOutputDone(InstrumentationResultParser.java:605)
	at com.android.ddmlib.testrunner.InstrumentationResultParser.done(InstrumentationResultParser.java:582)
	at com.android.ddmlib.MultiLineReceiver.flush(MultiLineReceiver.java:113)
	at com.android.ddmlib.AdbHelper.executeRemoteCommand(AdbHelper.java:421)
	at com.android.ddmlib.Device.executeShellCommand(Device.java:602)
	at com.android.ddmlib.testrunner.RemoteAndroidTestRunner.run(RemoteAndroidTestRunner.java:219)
	at com.android.ddmlib.testrunner.RemoteAndroidTestRunner.run(RemoteAndroidTestRunner.java:204)
	at com.facebook.buck.android.InstrumentationStep.execute(InstrumentationStep.java:78)
```
I tried to include kxml2 as dependency, but can't figure out what I'm doing wrong.

I've pushed my current code to https://github.com/tgummerer/buck/tree/tg/android, in case you are interested.  It doesn't really work yet, as I'm still stuck at that issue, and I have been for a while now.

@sdwilsh

**Comment by sdwilsh** [comment]
I think you need to add kxml2 as a dep in `third-party/java/ddmlib/BUCK`, although that should be on the `CLASSPATH` already given that you added it as a dep elsewhere.  @shs96c, any ideas?

**Comment by tgummerer** [comment]
@sdwilsh yeah, I tried that too, but neither building buck with ```buck build buck``` or building it with ```ant``` (I added the kxml2 jar to third-party.jars in the build.xml) seemed to help.  I pushed a minimal example to https://github.com/tgummerer/buck_test, where this error message occurs with my tree of buck.

Thanks for the comments on the other commits in my tree, I hope I can get to them during the weekend.

**Comment by sdwilsh** [comment]
Have you verified that that jar actually has the package you need in it?

**Comment by tgummerer** [comment]
@sdwilsh yes, I've tried that, unzipping the jar shows that it has org/kxml2/io/KXmlSerializer.class.  Unless I'm missing something here.

**Comment by sdwilsh** [comment]
Are you still blocked on this?

**Comment by tgummerer** [comment]
Yes, unfortunately.  But I have to admit I didn't really have time to look into it more deeply over the last few days.

**Comment by tgummerer** [comment]
@sdwilsh I took another stab at it, and finally figured out where the issue was.  I needed to add the library to ```JAVA_CLASSPATHS``` in ```programs/buck_repo.py```.

**Comment by sdwilsh** [comment]
*groan*

Yes, I had forgotten about that.  I'm going to be away for the next week, so I won't be able to help much, but I'll let the rest of the team know they should watch out and try to help :)

**Comment by tgummerer** [comment]
Heh yeah, my grep skills left me down for a while there.  No worries, I'll be moving at the end of the next week, so I probably won't have too much time to spend on buck anyway.  Thanks a lot for your help so far :smiley:

**Comment by sdwilsh** [comment]
Thanks so much for this!
