### ISSUE TITLE
MultiDex support

### ISSUE THREAD

**Issue by vovkab** [facebook/buck#309]
Does Buck have any?
Where I can find more info about how to use it?

So far this is what I have:

```
BUILD FAILED: //buck/apps:debug-apk#dex_merge failed on step dx with an exception:
method ID not in [0, 0xffff]: 65536
```

or if I try `use_split_dex = True,`:

```
DexWithClasses buck-out/gen/src/debug-src#dex.dex.jar with cost 5028090 exceeds the max cost 4194304 for a secondary dex file.
```

**Comment by sdwilsh** [comment]
We currently only support it for exopackage. At the time we wrote it, Android didn't support split dexes natively. With Lollipop that changed. We didn't document it, because it wasn't possible for non-FB people to use the feature, and we didn't want to open source our split dex loading code.

I'm not sure if the support library handles this now, or if it just works with Lollipop and newer devices.

**Comment by sschuberth** [comment]
> I'm not sure if the support library handles this now, or if it just works with Lollipop and newer devices.

The multidex-support library transparently handles [loading multiple dex files on pre-Lollipop devices](https://developer.android.com/tools/support-library/features.html#multidex), you just need to derive from [MultiDexApplication](https://developer.android.com/reference/android/support/multidex/MultiDexApplication.html) to use the custom class loader. On Lollipop, where the VM natively supports multiple dex files, using the multidex-support library is a no-op.

That said, adding support for creating multiple dex files by making Buck call `dx` with the `--multi-dex` option would be nice! Also, just like Gradle, Buck should be able to automatically determine the list of classes to pass to the `--main-dex-list` option, see the Android SDKs `mainDexClasses` script.

**Comment by facebook-github-bot-9** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by llj098** [comment]
@sschuberth @sdwilsh 

So, It seems that only pass the `--multi-dex` paramter to dx will be OK. But how can I set this parameter in a buck build rule?

**Comment by sschuberth** [comment]
@llj098 Like I said, this is not sufficient. You also need to determine the list of classes that need to go to the main dex file. Otherwise it's just a matter of luck if all classes that you app needs at startup end up in the main dex file.

**Comment by llj098** [comment]
Oh right , I mised the `mainDexClasses`.

Is it able to pass these parameter to dx in buck build rule?

Thanks.
2015年8月21日 上午12:51于 "Sebastian Schuberth" <notifications@github.com>写道：

**Comment by v-jizhang** [comment]
MultiDex support is supported, #602.
