### ISSUE TITLE
How to make Android Studio support buck

### ISSUE THREAD

**Issue by kymjs** [facebook/buck#318]
I want used buck in Android Studio, will be how do it.

**Comment by marcinkosiba** [comment]
It's possible to generate an IntelliJ project using `buck project`, Android Studio should be able to load the resulting project. You'll still need to run `buck build` from the command line to get a build though.
Or is this about being able to compile with buck from within Android Studio?

**Comment by marcinkosiba** [comment]
http://stackoverflow.com/questions/27758084/how-do-i-use-the-facebook-buck-building-tool-with-android-studio
If that's not what you're looking for please open a new issue and explain your request in more detail.
