### ISSUE TITLE
remote_file sha question

### ISSUE THREAD

**Issue by zserge** [facebook/buck#320]
Most android people are used to how gradle defines maven dependencies, e.g. 'com.squareup:otto:1.3.7' (without specifying the SHA checksum). I believe SHA checksum can be read from the maven server? Why is it a required, not optional field?

Also, since currently it's required - I made a quick macro that is expanded into a remote_file and prebuit_jar, also it fetches the SHA from the maven server, but I currently hard code the url (http://repo1.maven.org/maven2). I also see that it can be defined or overridden in the buckconfig.

So I wonder if a BUCK script can actually read the values from the buckconfig file? If so - I would just use the "maven_repo" variable inside my macro.

**Comment by k21** [comment]
One of Buck's goals is to ensure that the builds are reproducible, e.g. that you can check out an old revision of your repository and build it and get the same result you got when you just created that revision. `remote_file` is a convenience rule that goes against that goal by making the build dependent on external services. If the hash of the downloaded file was not checked, there would be three possible outcomes:

1. The external service works and it gives you the same file as you expect. You get the correct build.
2. The external service is offline or broken and the download fails. The build fails.
3. The external service is broken or malicious and it serves you a different file than you expect. Your build might succeed, but the output will be different than what you would expect.

While it is difficult to address the 2nd point while still keeping the convenience of `remote_file`, the 3rd point can be prevented fairly simply by checking the hash of the downloaded file.

Your approach that downloads the hash from the maven server will not be protected against the silent failure which can happen in the 3rd case. Also, if you are making a network connection every time the BUCK files are parsed, your build times will suffer. If you want to make use of all of Buck's advantages, I would recommend specifying the hash in your BUCK files.

**Comment by zserge** [comment]
But won't making SHA parameter optional solve it?
If one needs reproducible builds - provide the SHA and ensure the dependencies are identical.
If one needs just convenient fast builds - provide no SHA and hope the maven server was not hacked.

**Comment by k21** [comment]
I guess it might make Buck slightly easier to use but repeatable builds are higher priority for us than this convenience. Even making the field optional means that you can no longer trust a Buck project to have repeatable builds unless you are the only developer working on it or you review all of its commits, which is impossible for any bigger project.

**Comment by dcolascione** [comment]
@zserge, I never understood how people could be comfortable with hashless Maven-style dependencies. They scare me. Without a hash, the actual contents of your program can change at any time, without notice, depending on the actions taken by some external server administrator. With a hash, your program changes only when you change it.

**Comment by zserge** [comment]
I agree that it is useful to have hashes. But most developers are too relaxed to worry about it - in Go they simply fetch sources from git's tip, in js they get whatever is in the npm etc etc.

How user is supposed to get the initial hash value? My current way is super-dumb, I just open the URL at maven central and copy `*.jar.sha1` contents from there.

Maybe the quickstart (or any other project skeleton builder) would take the list of dependencies and if no SHA1 is provided - fetch it from maven and generate remote_file() rules with the fetched SHA1?

**Comment by k21** [comment]
> Maybe the quickstart (or any other project skeleton builder) would take the list of dependencies and if no SHA1 is provided - fetch it from maven and generate remote_file() rules with the fetched SHA1?

I think that sounds like a pretty good approach.

**Comment by zserge** [comment]
Great! I'm now still struggling with Buck+Kotlin, but once I see how that can be done (or can't be done) - I will have a look at buck sources to see if I can fix quickstart.

Btw, is there any reason why Buck doesn't contain a standard macro for Maven? Writing (and reading) manually remote_file + java_library can quickly become messy.

**Comment by shs96c** [comment]
I'll document the maven importer, which reads the SHA1 from the maven repo and imports it into your BUCK files.

**Comment by k21** [comment]
@shs96c I have created #327 to add documentation for the maven importer.

@zserge I hope your questions have been answered or will be answered soon in the new documentation. If not, please reopen the task.

**Comment by Coneko** [comment]
Just to clarify @shs96c's comment, the maven importer will import a library, all its dependencies and setup all the prebuilt_jar and remote_file targets, including the shas for you, which is probably exactly what you're looking for.

**Comment by Naveg** [comment]
@Coneko is creation of remote_file targets existing or planned functionality? I'm trying to use the maven importer with some success, but I'm not all the way there. When I do:

```java -jar resolver.jar . lib lib https://repo1.maven.org/maven2 `cat deps.txt | xargs````

the jars get pulled in, and the BUCK files under `/lib` contain the prebuilt_jar rules, but I don't see any remote_file rules. Furthermore, the prebuilt_jar rules aren't visible to the other buck targets.

**Comment by Coneko** [comment]
I don't think the maven importer creates `remove_file` rules. There might be an option to run it again if you want to update the dependencies though. Or maybe it was a different flow.

I'm sorry, @shs96c would know better.
