### ISSUE TITLE
Nailgun for other java apps

### ISSUE THREAD

**Issue by zserge** [facebook/buck#321]
I'm going to use Buck for a Kotlin android application. Kotlin compiler itself is pretty slow to start, so I would like to wrap it into a nailgun server somehow. I know that Buck comes with one. Is it exposed to the BUCK scripts somehow? If not - can I at least guess the path where Buck is installed and probably find it there? Or shall I download a separate copy of nailgun instead?

It would be cool if genrule() allowed to spawn custom java apps form inside the nailgun server. Is it/will it be possible?

**Comment by k21** [comment]
Unfortunately we don't have this functionality in Buck (yet). There were some talks about allowing custom extensions, but it is currently not our top priority. But I think if you wrap the compiler in a nailgun server yourself, Buck will work with it just fine (as long as the compiler itself works with nailgun - it will need to know to use the environment of the client process instead of the server process and so on).

**Comment by zserge** [comment]
I see. As I understand in this case Buck file will have to download and build nailgun server/client? There is no way to reuse the nailgun from the Buck, right (at least know where it's nailgun server JAR and ng app are located)?

**Comment by k21** [comment]
I don't think it is possible to reuse Buck's nailgun. Buck can sometimes be distributed as a Python pex package and then there is no Buck repository with the third-party jars. You can just check-in the nailgun prebuilt jar and c sources into your repo, that is what Buck does.

**Comment by zserge** [comment]
I see. The C side worries me, since that would require a C compiler to be present. Static builds are also not possible. Maybe I will build it dynamically once and download the binaries from inside Buck.

**Comment by k21** [comment]
Having a prebuilt binary and calling it from a `genrule` is also possible, although then you lose portability. But that is a compromise you will need to make yourself. I hope I have answered your questions. I am closing the task, please reopen if you need more information.
