### ISSUE TITLE
dependencies between java and res in android binary

### ISSUE THREAD

**Issue by zserge** [facebook/buck#325]
Sorry to bother you today :)

I'm looking at the project skeleton generated by 'buck quickstart' - it has `android_binary()` rule that depends on android_library and android_resource targets.

However, here (http://buckbuild.com/rule/android_library.html) it's mentioned that it would be typical for android_library (e.g. `java`) to depend on android_resource (which I find pretty logical, since resources normally produce R.java, which can be used in the android_library).

Which approach is the recommended one for typical android apps? Is there any reason in making library and resource targets independent?

**Comment by k21** [comment]
Yes, I think it usually makes more sense to make the `android_resource` a dependency of the `android_library` that uses it. It is likely that `buck quickstart` is outdated. By the way, I saw your https://github.com/zserge/buckbone script. If you would like to get some of that functionality into Buck, pull requests are welcome :)

**Comment by sdwilsh** [comment]
Aye, if you wanted to do a pull request to fix that up, we'd take it.  If not, one of us will get to it eventually.
