### ISSUE TITLE
android_prebuilt_aar should export any prebuilt_jars it has as a dep

### ISSUE THREAD

**Issue by sdwilsh** [facebook/buck#332]
Pulling this out of #328, as it's different from the original ask, but came out of that discussion.

**Comment by sdwilsh** [comment]
@edisonw and @rallat: note that the right fix for this may not do what you wanted, but there is a bug with Buck here.

What I'm going to fix is the case of having an `android_library` (let's call it A) depending on an `android_prebuilt_aar` (let's call it B), which depends on a `prebuilt_jar` (let's call it C).  Today, C isn't visible to A, but I've got a fix for that which will go out today.

If C has any dependencies, they won't be visible to A.  That's how `prebuilt_jar` works today, and it's intentional.  If you wanted that to work, you'd have to change `build.build_dependencies` (which isn't documented; I'll file an issue on that) or use `--build-dependencies=transitive` on the command line.

**Comment by sdwilsh** [comment]
#333 covers the documentation of that.

**Comment by edisonw** [comment]
Thank @sdwilsh, but I can just make C also a dep of A, correct?

**Comment by sdwilsh** [comment]
Yeah, if A needs C to compile, you should be doing that.  I just wanted to make it clear that this won't make all transitive deps work (unless you change that build setting).

**Comment by edisonw** [comment]
I see, sounds good.
