### ISSUE TITLE
android_prebuilt_aar: Add support for source JAR

### ISSUE THREAD

**Issue by mkonicek** [facebook/buck#334]
For example the Android Support Library ships as an .aar and a separate -sources.jar.

When depending on the .aar and generating an IntelliJ/Android studio project using 'buck project', it should be possible to navigate to sources.

Context: http://stackoverflow.com/questions/30533769/source-jar-with-bucks-android-prebuilt-aar

**Comment by winterDroid** [comment]
:+1:
