### ISSUE TITLE
Google APIs not found

### ISSUE THREAD

**Issue by AnthonyUccello** [facebook/buck#336]
I saw 2 other threads on this, but one was about changing 19 to 19-1 and the other didn't seem to have resolution. This error comes when I am doing the quickstart step `buck build app` after getting the success message `At this point, you should move into the project directory and try running: etc`

The specific error I am getting is this

```javascript
BUILD FAILED: Google APIs not found in /Users/username/android-sdk-macosx/add-ons/addon-google_apis-google-21/libs.
Please run '/Users/username/android-sdk-macosx/tools/android sdk' and select both 'SDK Platform' and 'Google APIs' under Android (API 21)
```

If I run

`/Users/username/android-sdk-macosx/tools/android sdk`

I get 
`-bash: /Users/username/android-sdk-macosx/tools/android: No such file or directory`

Any thoughts or suggestions?

**Comment by Coneko** [comment]
How did you install the android sdk? It seems like you either uninstalled it or reinstalled it and the path still points to the old location.

What distro are you using?

**Comment by Coneko** [comment]
> What distro are you using?

Or what package manager. (brew, macports, apt)

**Comment by AnthonyUccello** [comment]
Ok so I fixed the issue, I had set the wrong path to my SDK. But whether the android SDK is right or wrong you still get the 'sucess' message blurb. When I deleted it and set my path the right directory `/Applications/android-sdk-macosx` instead of `~/android-sdk-macosx` it worked. Thanks

**Comment by fabriziobertoglio1987** [comment]
Actually seems that android studio does not install google apis anymore in that path https://stackoverflow.com/a/7860557/11452286
