### ISSUE TITLE
`android_binary`'s `cpu_filters` is undocumented

### ISSUE THREAD

**Issue by sdwilsh** [facebook/buck#340]
test/com/facebook/buck/android/testdata/android_project/apps/sample/BUCK contains some examples

**Comment by bolinfest** [comment]
This should really be reimplemented using flavors, so perhaps it is best
left undocumented for now?

**Comment by sdwilsh** [comment]
@bolinfest while true, it's certainly causing a lot of problems for people (like @Piasy) so probably worth doing.  It's unfortunate we consider `android_binary` to be frozen.
