### ISSUE TITLE
buck project --experimental-ij-generation feedback

### ISSUE THREAD

**Issue by marcinkosiba** [facebook/buck#350]
This is a meta-bug for dumping feedback on the --experimental-ij-generation project generator mode.

**Comment by marcinkosiba** [comment]
@mread was kind enough to provide this piece of feedback in issue 188:

If you were to do the following:
```
git clone https://github.com/mread/spark-redis-bootstrap-buck.git
cd spark-redis-bootstrap-buck
rm -rf .idea
buck project --experimental-ij-generation
```

First issue is that it seems to attempt to build the project, not just configure it so you get a failure due to missing nodejs deps. To fix that
```
npm install
buck project --experimental-ij-generation
```

1. Every package under src/main/java appears to get an entry in the sources, this is unnecessary and for very large projects a bit confusing
2. Exclude folders include lib/, build/ and node_modules/, I'm not sure where this list is coming from but I don't think I want to exclude those. Is it just excluding everything that isn't explicitly part of a rule?
3. If `misc.xml` doesn't exist then it doesn't create one. If it does then it defaults the JDK to
```
<component name="ProjectRootManager" version="2" languageLevel="JDK_1_6" assert-keyword="true" jdk-15="true" />
```
even though we have specified the following in `.buckconfig`
```
[java]
    source_level = 8
    target_level = 8
```
4. Likewise project language level is 6, not 8
5. No output directory set.

That's it for now. Hope it's helpful.

**Comment by marcinkosiba** [comment]
Thanks for the feedback @mread!  Some answers/followup questions:

1. `buck project --experimental-ij-generation` will attempt to build the code. This is because both `buck project --experimental-ij-generation` and `buck project` reference stuff from buck-out. The difference is that plain `buck project` implicitly relies on the developer running the appropriate `buck build` command, so you can get into a state where IntelliJ doesn't index stuff/has even more errors because you haven't built yet. Having the build be part of the project generation is an attempt to address that scenario.
1. I'm aware of the fact that every folder ends up getting a package. I'd assumed it's more of a cosmetic problem (and so fixing it is low-pri). Is it really jarring or is it more of a "huh? that's weird.." sort of thing?
1. Yes, the new `buck project` will end up building a set of folders from the inputs of rules responsible for compiling source code and exclude everything else. This makes IntelliJ a lot faster if you have a lot of source files in your repo but are only working on a small subset. In your case would it be more appealing to take over control of the excludes set (define a list of folders and have those and only those be excluded) or would you prefer to turn excludes off entirely?
1. `buck project --experimental-ij-generation` currently doesn't emit neither misc.xml nor compiler.xml. This will be addressed in the future :)

**Comment by mread** [comment]
Thanks for the detailed responses. 

>buck project --experimental-ij-generation will attempt to build the code. This is because both buck project --experimental-ij-generation and buck project reference stuff from buck-out. The difference is that plain buck project implicitly relies on the developer running the appropriate buck build command, so you can get into a state where IntelliJ doesn't index stuff/has even more errors because you haven't built yet. Having the build be part of the project generation is an attempt to address that scenario.

This is a tricky one - what if the project isn't in a buildable state and I want to configure my IDE as best as I can to work out why? I think your example is the stronger and more common use case though. In most cases once you've built the project once, it's more useful to give IntelliJ the best chance we can of configuring itself properly. Happy to go with whatever you decide.

> I'm aware of the fact that every folder ends up getting a package. I'd assumed it's more of a cosmetic problem (and so fixing it is low-pri). Is it really jarring or is it more of a "huh? that's weird.." sort of thing?

First impression was "that's weird, all the folders are the wrong colour". I haven't worked out whether there's a genuine issue hidden in there but I wouldn't enjoy rolling it out to our team in this form - too many WTFs. I'm wondering whether for very large modules (we have a few because we migrated to Buck from a more monolithic structure) that we might break a limit of some kind but I can't be sure.

> Yes, the new buck project will end up building a set of folders from the inputs of rules responsible for compiling source code and exclude everything else. This makes IntelliJ a lot faster if you have a lot of source files in your repo but are only working on a small subset. In your case would it be more appealing to take over control of the excludes set (define a list of folders and have those and only those be excluded) or would you prefer to turn excludes off entirely?

In our case, not everything is a BUCK module, perhaps it should be. But if it's not, then that doesn't mean we want to exclude it. A configurable exclude set would probably be more useful to us. That's how we do it now.

>buck project --experimental-ij-generation currently doesn't emit neither misc.xml nor compiler.xml. This will be addressed in the future :)

Awesome
