### ISSUE TITLE
Include All Java Files With One Rule In android_binary

### ISSUE THREAD

**Issue by AnthonyUccello** [facebook/buck#352]
Howdy

First this tool seems really amazing, but admittedly my shell scripting skill is quite lacking. I've gone through the docs and the build rules and from what I understand, I can set the dependencies for the android_binary (i.e. the apk) in the deps section.

However my project has only one module, so I don't need multiple BUCK files or anything.

Can I set it to just get ALL Java files in my /java folder, or, as its shown in the example from the quickstart, do I need to manually specify every single file with a fullpath?

```python
android_binary(
  name = 'app',
  manifest = 'AndroidManifest.xml',
  keystore = ':debug_keystore',
  deps = [
    '//java/com/example/activity:activity',
    '//res/com/example/activity:res',
  ],
)
```

Can I do something like:

```python
android_binary(
  name = 'app',
  manifest = 'AndroidManifest.xml',
  keystore = ':debug_keystore',
  deps = [
    '//java/*
  ],
)
```

To just have it grab ALL my java files?

**Comment by sdwilsh** [comment]
On 6/17/2015 2:52 PM, Anthony Uccello wrote:
> However my project has only one module, so I don't need multiple BUCK
> files or anything.
>
> Can I set it to just get ALL Java files in my /java folder, or, as its
> shown in the example from the quickstart, do I need to manually specify
> every single file with a fullpath?
You'd still need an `android_library` rule, which you can keep in the 
same `BUCK` file if you'd like.  If you have any resources, you'd also 
need to have an `android_resource` rule.  The docs on those have 
examples of how to use the `glob` method to get all your source files.

Cheers,

Shawn

**Comment by AnthonyUccello** [comment]
Gotcha I did get that setup but now I've run into so many error outputs I don't know where to begin haha.

Is there a bigger example I could look at somewhere (other than the quickstart)?

**Comment by sdwilsh** [comment]
http://buckbuild.com/article/exopackage.html has some commands to 
checkout our forked version of AtennaPod that uses Buck.

**Comment by AnthonyUccello** [comment]
Gotcha thanks!
