### ISSUE TITLE
Produce an error when referencing folders when we expect files

### ISSUE THREAD

**Issue by newobj** [facebook/buck#356]
I have 

```
headers = [
  'bx/include/compat/osx',
  'bx/include',
  'bgfx/3rdparty/khronos',
  'bgfx/3rdparty',
  'bgfx/examples/common',
  'bgfx/include',
],
```

When I go to build, I get

```
[2015-06-18 22:49:53.742][error][command:db8f1dae-12dc-44bd-a0a0-097fa02e604e][tid:324][com.facebook.buck.event.listener.LoggingBuildListener] failed creating linking "/Users/blo/nisqually/buck-out/gen/lib/lib#default,header-symlink-tree/lib/bgfx/3rdparty/khronos" -> "/Users/blo/nisqually/lib/bgfx/3rdparty/khronos"
java.nio.file.FileAlreadyExistsException: /Users/blo/nisqually/buck-out/gen/lib/lib#default,header-symlink-tree/lib/bgfx/3rdparty
java.nio.file.FileAlreadyExistsException: /Users/blo/nisqually/buck-out/gen/lib/lib#default,header-symlink-tree/lib/bgfx/3rdparty
```

It seems that the symlink "/Users/blo/nisqually/buck-out/gen/lib/lib#default,header-symlink-tree/lib/bgfx/3rdparty" gets created first, then tries to create .../bgfx/3rdparty/khronos and it explodes because .../bgfx/3rdparty is a symlink, not a directory.

For the library in question, this is simply how it expects its headers to be laid out.

**Comment by k21** [comment]
The `headers` parameter is supposed to contain the individual files, not folders (see [cxx_library documentation](http://buckbuild.com/rule/cxx_library.html)). You can use [the `glob` function](http://buckbuild.com/function/glob.html) if you want to use all files from a certain directory. We should  add checks to enforce that those paths are not directories.
