### ISSUE TITLE
buck run deletes lines from terminal

### ISSUE THREAD

**Issue by jiangty-addepar** [facebook/buck#362]
When I run `buck run` on a not-yet-built target, lots of lines get deleted from my terminal.

![buck_run2](https://cloud.githubusercontent.com/assets/4613397/8315236/fc67b682-19a3-11e5-834b-16a9330af822.gif)

**Comment by Coneko** [comment]
What terminal and shell are you running?

**Comment by jiangty-addepar** [comment]
I'm using `xterm` with `bash` on Ubuntu 14.04. This was also reproduced with `xterm` and `bash` on OS X.

**Comment by k21** [comment]
This might be related to #363, which seems to be caused by a bug that broke the logic responsible for stopping the SuperConsole when there is extra output. We have a fix ready and we will publish it either tomorrow or early next week, hopefully it will fix this issue.

**Comment by jiangty-addepar** [comment]
Hmm, I've been seeing this bug for a much longer time (~a month?) than I've been seeing #363 , though.

**Comment by jiangty-addepar** [comment]
Still seeing this happen on https://github.com/liuyang-li/buck/commits/88c2b52bfa8672a559a6bac749d5dcd4650041da .
