### ISSUE TITLE
How to use buck to management the dependencies?

### ISSUE THREAD

**Issue by ruijun** [facebook/buck#370]
Hi,

I am a newer in buck, I want to use buck build android app.In gradle , my app's dependencies like this:

dependencies {
    compile fileTree(include: '*.jar', dir: 'libs')
    compile 'com.android.support:design:22.2.0'
    compile 'com.android.support:appcompat-v7:22.2.0'
    compile 'com.android.support:recyclerview-v7:22.2.0'
    compile 'com.android.support:percent:22.2.0'
    compile 'com.android.support:multidex:1.0.0'
    compile 'com.afollestad:material-dialogs:0.7.6.0'
    compile 'com.github.chrisbanes.photoview:library:1.2.2'
    compile 'com.github.bumptech.glide:glide:3.6.+'
}

When I use buck, how can I management the dependencies?

**Comment by tgummerer** [comment]
Hi,

the preferred way is to check in jars or aars in the repository, and use the [prebuilt_jar](http://buckbuild.com/rule/prebuilt_jar.html) and the [android_prebuilt_aar](http://buckbuild.com/rule/android_prebuilt_aar.html) rules to make them available for the other rules.

If you don't want to check the dependencies into the repository you can use [remote_file](http://buckbuild.com/rule/remote_file.html) rules, but then you have to remember to use buck fetch before running buck build.

**Comment by ruijun** [comment]
@tgummerer Thanks.How can I management the so files?

**Comment by tgummerer** [comment]
Using `prebuilt_native_library`. (http://buckbuild.com/rule/prebuilt_native_library.html)

**Comment by sdwilsh** [comment]
We general prefer to point people at stackoverflow.com and tag the question with "Buck" for support issues these days.

Thanks @tgummerer for answering this!
