### ISSUE TITLE
Buck cannot handle paths with spaces

### ISSUE THREAD

**Issue by subtleGradient** [facebook/buck#38]
```
 aylott in ~/Projects/Design Tools/foo
± |master ✓| → buck targets
Error: Could not find or load main class Tools.foo..buckd
```

**Comment by chriskonstad** [comment]
I think there's been a change that causes this to be an issue again.

I ran the sample commands from @subtleGradient and got this output for the path with a space:

> [chris@mbp][with spaces]$ buck targets
> Using watchman.
> Warning raised by BUCK file parser: Traceback (most recent call last):
> Warning raised by BUCK file parser:   File "/Users/chris/Desktop/buckme/with spaces/.buckd/tmp/buck_run.T3zbEu/buck_python_program1011147366125771223/__main__.py", line 10, in <module>
> Warning raised by BUCK file parser:     from buck_parser import buck
> Warning raised by BUCK file parser: ImportError: No module named buck_parser
> Parse error for build file /Users/chris/Desktop/buckme/with spaces/BUCK:
> No content to map due to end-of-input
>  at [Source: com.google.common.io.CountingInputStream@2164e11d; line: 1, column: 0]
> [-] PARSING BUCK FILES...FINISHED 0.7s

The output of `buck targets` in the path without spaces was as normal.

**Comment by afturner** [comment]
This is still an issue as of v2017.11.16.01

**Comment by ttsugriy** [comment]
The issue have been resolved by https://github.com/facebook/buck/commit/20cea0d6625a614363ef82a26e2c127a23a9832f but we haven't published new releases since then. I'll try to do this next week.

**Comment by afturner** [comment]
@ttsugriy yikes! should have checked the commits.. did try building from source but got some compile errors so didn't pursue further lol. Thanks!

**Comment by ttsugriy** [comment]
fix is now available in https://github.com/facebook/buck/releases/tag/v2018.03.26.01 I'm going to publish deb package soon too.
