### ISSUE TITLE
R.java not exposed as a dependency

### ISSUE THREAD

**Issue by kargs** [facebook/buck#383]
I have an `android_library` which depends on `android_resources`. Classes of this library can reference `R.java` generated for the resources with no problem (obviously). Now, I have a `genrule` which is compiling some classes, for which I need to specify the classpath manually. I want to be able to refer resources. My `genrule` is dependent on the `android_library` of course, however `R.java` never lands on it's classpath.

**Comment by sdwilsh** [comment]
Do you mean it's not in the `$(classpath )` macro in the `genrule`?

**Comment by kargs** [comment]
Yep. I investigated what happens in `buck-out`, and R.java is never really included in jars from what I can tell. There's something going on with so called 'dummy r dot java' and then, from what I can tell, the actual R.java is generated only in `android_binary`. But I might be wrong.

**Comment by kargs** [comment]
Or I might be misusing something as I'm very fresh to Buck. Any pointers / help appreciated :)

**Comment by sdwilsh** [comment]
Yeah, we do not generate it until the very end.  The dummy_r_dot_java stuff is an optimization that we've done to improve build times.  It might have what you need.  @natthu, do you know why we don't add those to the class path?

What does your `genrule` do, by chance?

**Comment by natthu** [comment]
We generate a `dummy_r_dot_java` rule (for every `android_library` rule) which only contains the `R.java` references from resources that the library directly depends on. This dummy `R.java` is only for compiling the android library (so that the `R.*` references are resolved) and _not_ packaged into the jar for the library. As you said, the actual `R.java` is generated by the `uber_r_dot_java` rule (which is generated for the `android_binary` rule).

If you want to compile generated code, you should simply use an `android_library` whose `srcs` is the list of generated files, and which depends on the android resources.

**Comment by kargs** [comment]
In my scenario, I have to use a different compiler. I'm trying to compile Kotlin code and make sure it can refer to Android resources. So the above advice won't work (at least I couldn't make it work trying any configuration I could come up with). The only way I made it 'working', is to have an `android_library` which basically mimics / wraps constants from the R.java, and then make my Kotlin `prebuilt_jar` (which in turn is based on the `genrule`) be dependent on this library. But this is pretty cumbersome of course, so I wonder if any proper solution is possible.

**Comment by sdwilsh** [comment]
Interesting.  I wonder if you could use the `android_library` rule here and just set the `compiler` that @shs96c added (which unfortunately was not documented).

**Comment by kargs** [comment]
Hmm I think we're getting closer. I hooked up `kotlinc` as the target compiler, however it doesn't like the arguments provided by buck. `Invalid argument: -source`. Is there any way to modify them?

**Comment by natthu** [comment]
IIUC, there's an assumption that the custom `compiler` implements the `jsr99` spec.

You could write a wrapper around `kotlinc` that filters arguments passed by Buck.

**Comment by kargs** [comment]
Ok I got a bit hooked and made it working. You can see my simple project [here](https://github.com/kargs/buckexp) (in particular [this directory](https://github.com/kargs/buckexp/tree/master/kotlin/gs.kar.buckexp)). I've made detailed comments in source, but the ugliest hack I had to do was to rename all `.kt` files to `.java` on the fly, so that `android_library` will fetch them in `srcs` - otherwise they seem to be ignored and never reach the compiler. Another thing is that my argument list adaptations for `kotlinc` may not make too much sense, but at least I was able to refer to `R.java` from Kotlin code and have it run on my device.

**Comment by sdwilsh** [comment]
Does that unblock you?  If you were feeling ambitious, you could try to 
implement rules for Kotlin.

**Comment by kargs** [comment]
Yeah it does for now, just wanted to report back. I might come up with a PR once I find time and get myself a bit more familiar with the docs / codebase. Thanks for help!

**Comment by sdwilsh** [comment]
Alright, should we close this then?

**Comment by kargs** [comment]
Sure, it wasn't a bug per se I suppose. :)

**Comment by sdwilsh** [comment]
Well, it may have been at first :)
