### ISSUE TITLE
Support non-integer android sdk versions for preview releases (eg. android-MNC)

### ISSUE THREAD

**Issue by joshzana** [facebook/buck#388]
I am currently porting a gradle/buck android application to Android M preview and would like our buck build to target the same SDK as our gradle build.

The buck docs suggest that I can run android list targets --compact to find the list of valid values that I can set in my .buckconfig.    Here's what I get:

android-15
android-16
android-17
android-18
android-19
android-20
android-21
android-22
android-MNC

But if I put android-MNC in my .buckconfig I get this:

BUILD FAILED: The Android SDK for 'android-MNC' could not be found. Must define a local.properties file with a property named 'sdk.dir' that points to the absolute path of your Android SDK directory, or set ANDROID_HOME or ANDROID_SDK.

The root cause is that AndroidPlatformTarget.java uses  this line:

int apiLevel = Integer.parseInt(platformMatcher.group(1));

which will fail on "MNC"

**Comment by nayrmi** [comment]
Thanks for the report, Josh! We've committed a fix and will have it out in the next push.

**Comment by joshzana** [comment]
Thanks!
