### ISSUE TITLE
Ant build file from buck buid files

### ISSUE THREAD

**Issue by ieugen** [facebook/buck#390]
Hello, 
I'm working on packaging gerrit for Debian. Debian has some strict requirements when it comes to build things: all dependencies should be allready packaged and the build should happen offline. 

Because Buck is not packaged (and I'm trying to avoid packaging it for now -- as it has a lot of dependencies) I'm researching using Ant to build Gerrit. 

To avoid future work I'm looking into converting Buck build files to Ant build files. There seems to be a match, but I'm not familiar enough with Buck to make the assessment. 

I s this possible? If yes, how do you think I should best approach it?

Thanks,

**Comment by Coneko** [comment]
You mean because of reproducible builds right? https://wiki.debian.org/ReproducibleBuilds

You should be able to specify a buildinfo with all the necessary dependencies: java, python and gcc. Then you would be able to package Buck.

Would that be ok?

**Comment by ieugen** [comment]
Hi, 

No. I am not trying to package buck. I wish to package gerrit which uses buck. One way is to have buck export an ant build.xml (similar to export intrllij idea or xcode project). 

I made some progress by transforming the json format that buck outputs to ant build.xml . Looks promissing but is hard to maintain long term. Upstream support for buck to ant xml would be very nice.

I'll share some of my code when I'm done.

**Comment by sdwilsh** [comment]
I don't think this is something that we'd want to support, but I'll let @Coneko chime in.

**Comment by Coneko** [comment]
I don't think so either. The IntelliJ idea and Xcode project generators are very different from translations: the generated projects don't build unless the generation was run. They're meant as an interface to the IDE rather than translating the build to other build tools.
