### ISSUE TITLE
App built with buck is zoomed and poor performance

### ISSUE THREAD

**Issue by bkase** [facebook/buck#392]
Thanks for open-sourcing buck!

Due to excruciatingly slow build times with gradle, I've been porting our mostly-kotlin Android app over to buck on and off for the past week.

At this point, I've managed to get the app building (way faster than with gradle!) and running, but I see some problems at runtime:

a. (testing on a xxxhdpi Nexus 6) the app seems to be trying to render at hdpi and upscaling -- our layouts seem very zoomed in when compared to the gradle output (see screenshots top=buck build, bottom=gradle build)

![bad screenshot](http://i.imgur.com/dWwgit5l.png)

![good screenshot](http://i.imgur.com/GJiu7YBl.jpg)

b. The framerate is extremely slow when a user interacts with views maybe ~5fps in some activities compared to a smooth 60fps when built with gradle

When I use the deprecated since sdk-level 11 `<supports-screen>` tag in AndroidManifest.xml and add `android:xlargeScreens="true"`, the app appears slightly less zoomed in (I assume it is being rendered at xhdpi and upscaling in this case).

I tried decompiling the two apks and diffing the AndroidManifest.xml files and there isn't anything different other than a few `<meta-data>` tags (which are different on purpose).

If it matters, I got multidex working with Google's multidex support library, but not with exopackage --  I can talk more about the problems I saw there if necessary.

Here is the `android_binary` rule

```
android_binary(
	name = 'app',
	manifest = 'AndroidManifest.xml',
	keystore = ':debug_keystore',
        use_split_dex = True,
        primary_dex_patterns = [
            /* snip */
        ],
	deps = [
		'//app:app',
		'//app:res',
		'//kotlin-lib:runtime',
	],
)
```

Does anyone know why these problems are happening and/or a way to fix them?

Thanks!

**Comment by dreiss** [comment]
> I tried decompiling the two apks and diffing the AndroidManifest.xml files and there isn't anything different other than a few <meta-data> tags (which are different on purpose).

Did you use apktool or aapt dump xmltree?  IIRC, apktool doesn't show the target-sdk, which could cause hardware acceleration to be disabled.

P.S.: What's up, Brandon?

**Comment by bkase** [comment]
How did you know! I was using apktool, an aapt dump diff shows my error:

```
<       A: targetSdkVersion=0x16
<       A: minSdkVersion=0x10
---
>       A: android:minSdkVersion=0x10
>       A: android:targetSdkVersion=0x16
```

I can't believe it was that simple -- thanks!

P.S.: Life is good, what's up with you?

**Comment by dreiss** [comment]
We had another user complain of poor performance, and it turned out to be an improper targetSdk, which was disabling hardware acceleration.  "decompiling" suggested apktool, which I know from (painful) experience leaves out targetSdk.

Things are going well here.  I don't really work on Buck anymore, but I'm doing more NDK stuff, which means I'm always tuned in to Buck's NDK support.

**Comment by dreiss** [comment]
Also, you should always use "diff -u".  The output is much easier to read, IMO.
