### ISSUE TITLE
Can not find com.facebook.buck.model.BuildTarget in project.

### ISSUE THREAD

**Issue by reondz** [facebook/buck#393]
![2015-08-12 3 33 06](https://cloud.githubusercontent.com/assets/10429522/9218738/86f9d7dc-4107-11e5-8caf-3a0f7a29e78c.png)
When I pull the buck project down and try to import it into IDEA.
My IDE just tell me the BuildTarget is missing, and I can not find this java file in the package com.facebook.buck too.
Did I miss something?  
Thanks.

**Comment by k21** [comment]
Some of Buck's classes are [autogenerated by the Immutables library](https://buckbuild.com/contributing/immutables.html). In IntelliJ you can use "Build -> Make Project" to generate those classes and get rid of the missing symbol errors.

**Comment by reondz** [comment]
@k21 Got it.Many Thanks！
