### ISSUE TITLE
R.attr.colorPrimary not found

### ISSUE THREAD

**Issue by reondz** [facebook/buck#396]
deps of app has support.
support is a android_library and its deps has appcompat-v7.
but when I buck build app, the error happened, says R.attr.colorPrimary not found.
Is something I miss?
Thanks.

**Comment by tgummerer** [comment]
This is the same issue I had in #375 and will be fixed with #391.  According to @sdwilsh it should be out soon, which usually means the next time it's pushed to GitHub.

If you don't want to wait for that, you can try the design-library branch in my fork in the meantime.

**Comment by reondz** [comment]
I tried that but failed too.I found when I use    srcs = glob(['src/main/java/**/*.java']),   in my android_library rule.It can not     found the R.attr.colorPrimary. I need change it into srcs = glob(['*.java']), .

**Comment by sdwilsh** [comment]
Those globs are going to do two very different things.

**Comment by sdwilsh** [comment]
Is this working for you now?

**Comment by reondz** [comment]
Yes, thanks for your help.
My problem is not like #375, but I understand why my project can not work at last.
