### ISSUE TITLE
Native buffer leaks in buckd

### ISSUE THREAD

**Issue by mread** [facebook/buck#404]
I can't cleanly and reliably shutdown nailgun. The steps below reproduce the issue but it also hangs on the auto restart (MAX_BUCKD_RUN_COUNT = 64) which is going to be a problem in our CI environment.

Steps:
* install watchman
* cd buck-checkout-dir
* ant clean default
* bin/buck test
* bin/buckd --kill <--- HANGS
* ctrl-c
* observe NGServer process still running
* bin/buckd --kill <--- WORKS

**Comment by sdwilsh** [comment]
Fun fact: at Facebook, we don't use `buckd` in CI because it was too flaky.

With that said, @bhamiltoncx has recently switched Buck over to use unix domain sockets instead of tcp sockets.  What version of buck are you running, and is this a recent development?

**Comment by bhamiltoncx** [comment]
Sorry for the trouble! This should have been fixed in commit a323fdf43ac8fee60885ad4603b03519d0073b62.

What commit are you running from?

**Comment by mread** [comment]
Awesome. Looks like we missed that commit by a few hours, I'll pull the latest tomorrow and let you know how it goes.

**Comment by mread** [comment]
@sdwilsh buckd also massively leaks memory for us - is there way of getting watchman without buckd/nailgun? We'd probably go for that.

**Comment by sdwilsh** [comment]
It leaks memory or doesn't give it up?  We've been doing lots of perf fixes around how much memory it uses, but we've found the jvm doesn't like to free much up to the host OS.

We could probably make it so that you can use watchman as the `glob` provider, but, for larger repos especially, a lot of the wins come from the caches that `buckd` keeps around between builds and the improved cache hit rate in the jvm.

**Comment by mread** [comment]
It appears to be outside the JVM's heap so I'm guessing somewhere in nailgun it's leaking - i.e. buckd Xmx is at about 1000m from memory but we often see 11GB+ for the buckd process via top.

**Comment by bhamiltoncx** [comment]
It'd help if you provided the command you're running to check memory as well as its output. You might be seeing OS buffer caches.

**Comment by mread** [comment]
Here's a load of stats from various tools for a ./buckd process that appears to be using too much memory, i.e. after startup and running a build we see RSS of less than 1 GB and now, a few hours later it is 5 GB. Other members of the team have seen this go as far as 16GB on a machine with 24GB total - they tend to kill it at that point.
```
% smem -t

 PID User     Command                         Swap      USS      PSS      RSS 
14584 hancockd buckd -Xmx1000m -Djava.awt.        0  5085732  5088802  5096328

% top

KiB Mem:  24682644 total, 14207416 used, 10475228 free,   196088 buffers
KiB Swap:        0 total,        0 used,        0 free,  2658684 cached

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                          
14584 hancockd  20   0 14.439g 4.852g   5392 S  78.9 20.6  57:15.99 java    
...

% cat /proc/14584/status 
Name:        java
State:        S (sleeping)
Tgid:        14584
Ngid:        0
Pid:        14584
PPid:        1
TracerPid:        0
Uid:        1178        1178        1178        1178
Gid:        100        100        100        100
FDSize:        1024
Groups:        100 1000 1003 4000 4001 4002 4003 4004 4005 4006 4007 4008 4009 11005 11011 
VmPeak:        16936660 kB
VmSize:        15140088 kB
VmLck:               0 kB
VmPin:               0 kB
VmHWM:         6418484 kB
VmRSS:         5087212 kB 
VmData:        14976884 kB
VmStk:             148 kB
VmExe:               4 kB
VmLib:           16772 kB
VmPTE:           14160 kB
VmSwap:               0 kB
Threads:        45
SigQ:        2/193123
SigPnd:        0000000000000000
ShdPnd:        0000000000000000
SigBlk:        0000000000000000
SigIgn:        0000000000000000
SigCgt:        2000000181005ccf
CapInh:        0000000000000000
CapPrm:        0000000000000000
CapEff:        0000000000000000
CapBnd:        0000003fffffffff
Seccomp:        0
Cpus_allowed:        ffffffff,ffffffff
Cpus_allowed_list:        0-63
Mems_allowed:        00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000001
Mems_allowed_list:        0
voluntary_ctxt_switches:        1
nonvoluntary_ctxt_switches:        2
```

**Comment by mread** [comment]
Can confirm that the latest code fixes the shutdown issue. We still have awful memory usage, it seems to creap up even without any activity build activity. I ran a handful of builds before leaving last night, came in this morning and buckd is using 13GB of memory - a jmap heapdump  dumps only 1GB as expected so this is off-heap - we suspect NGUnixDomainSocketLibrary.java in nailgun-server but only because it appears to allocateMemory off-heap.

Any ideas or suggestions for lines of investigation would be gratefully received.

```
cat /proc/27459/status
Name:	java
State:	S (sleeping)
Tgid:	27459
Ngid:	0
Pid:	27459
PPid:	1
TracerPid:	0
Uid:	1265	1265	1265	1265
Gid:	100	100	100	100
FDSize:	256
Groups:	100 209 1000 1003 4000 4001 4002 4003 4004 4005 4006 4007 4008 4009 11005 11011 
VmPeak:	26420152 kB
VmSize:	26368724 kB
VmLck:	       0 kB
VmPin:	       0 kB
VmHWM:	14334604 kB
VmRSS:	14328668 kB
VmData:	26204240 kB
VmStk:	     148 kB
VmExe:	       4 kB
VmLib:	   16864 kB
VmPTE:	   35736 kB
VmSwap:	       0 kB
Threads:	45
SigQ:	4/193123
SigPnd:	0000000000000000
ShdPnd:	0000000000000000
SigBlk:	0000000000000000
SigIgn:	0000000000000000
SigCgt:	2000000181005ccf
CapInh:	0000000000000000
CapPrm:	0000000000000000
CapEff:	0000000000000000
CapBnd:	0000003fffffffff
Seccomp:	0
Cpus_allowed:	ffffffff
Cpus_allowed_list:	0-31
Mems_allowed:	00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000001
Mems_allowed_list:	0
voluntary_ctxt_switches:	1
nonvoluntary_ctxt_switches:	4
```

**Comment by mread** [comment]
With a little bit of profiling we see quite a few instances of ` com.martiansoftware.nailgun.NGUnixDomainSocketLibrary.SockaddrUn` being created within the buckd process. However there's no code in this class to free up the memory that it allocates using `Structure.allocateMemory()`. While this isn't necessarily the source of our large leak it probably needs some attention.

**Comment by bhamiltoncx** [comment]
The memory allocated by `Structure.allocateMemory()` is allocated using a
subclass of the JNA Memory class, `Structure.AutoAllocated`.

When the Structure (and its contained Memory object) is finalized, the
finalizer will free the memory.

There shouldn't be too many `SockaddrUn` objects created (one for each
client that connects). They should also be cleaned up by nailgun (unless
there's an existing bug in nailgun).

My guess is the memory usage you're looking at is not related to the JNA
logic.

**Comment by bhamiltoncx** [comment]
Ah, I see one thing that might cause issues. I declared `SockaddrUn` to implement `Structure.ByReference`, but it doesn't need that (it's not stored inside any other structures). The JNA code which handles that could conceivably hold on to the structure much longer than needed.

I'll try removing that, but I'm extremely doubtful any possible leak from that logic would be more than a few bytes on each Buck client command.

**Comment by bhamiltoncx** [comment]
This smells suspiciously like buffers not being reclaimed to me. I wonder if we're hitting this bug in the JVM? http://bugs.java.com/view_bug.do?bug_id=4469299

**Comment by mread** [comment]
Thanks for all the feedback - I think you're probably right, even if there is a small leak  it doesn't explain the massive memory usage we're seeing.

I'm wondering also about ZipDeflater usage, this ancient issue http://bugs.java.com/view_bug.do?bug_id=4797189 and this comments on 1415c3f09343b1426bf11e84f4241de6c738b873 by @dreiss. Seems like it better matches our symptoms.

**Comment by bhamiltoncx** [comment]
I strongly suspect native buffers as well—either from ZipDeflater, netty, okhttp, or something similar.

Are you using an HTTP cache or HTTP fetching in your build process?

**Comment by bhamiltoncx** [comment]
Also, what version of the JVM are you running? I see lots of reports that particular JREs shipped with lots of issues reclaiming native buffer:

https://github.com/netty/netty/issues/2395

**Comment by bhamiltoncx** [comment]
I built `jemalloc` from source and injected it to the JVM to confirm your theory:

```
export MALLOC_CONF=prof:true,lg_prof_sample:1,prof_accum:false,lg_prof_interval:30,prof_prefix:jeprof.out
export LD_PRELOAD=/path/to/jemalloc/lib/libjemalloc.so.2
% ./bin/buck build buck
[-] BUILDING...FINISHED 0.6s (3/221 JOBS, 0 UPDATED)
% ps auxw | grep java
username     2171615 52.9  2.6 4514108 1724852 pts/0 Sl   09:57   3:33 buckd -XX:MaxPermSize=256m
% /path/to/jemalloc/bin/jeprof --show_bytes /usr/local/bin/java jeprof.out.2171615.16.i16.heap
Using local file /usr/local/bin/java.
Using local file jeprof.out.2171615.16.i16.heap.
Welcome to jeprof!  For help, type 'help'.
(jeprof) top
Total: 198141237 B
90542080  45.7%  45.7% 90542080  45.7% inflateInit2_
85919713  43.4%  89.1% 85919713  43.4% os::malloc
16318464   8.2%  97.3% 16318464   8.2% updatewindow
 3145728   1.6%  98.9%  3145728   1.6% init
  867200   0.4%  99.3%   867200   0.4% readCEN
  848832   0.4%  99.7% 91390912  46.1% Java_java_util_zip_Inflater_init
  221184   0.1%  99.9%   221184   0.1% ObjectSynchronizer::omAlloc
  137216   0.1%  99.9%   137216   0.1% deflateInit2_
   24000   0.0%  99.9%    24000   0.0% _dl_allocate_tls
   17328   0.0%  99.9%    17328   0.0% _dl_new_object
```

So, we are definitely failing to free native buffers allocated by `inflateInit2_`.

**Comment by bhamiltoncx** [comment]
I pushed a potential fix for some leaks from `ZipFile.getInputStream()` to the branch https://github.com/facebook/buck/commits/bhamiltoncx/fix-leaks :

aae858f1ce3a79625fa085571711f4b2fd406fe7

Could you give this a try?

**Comment by mread** [comment]
> Are you using an HTTP cache or HTTP fetching in your build process?

No.

> what version of the JVM are you running?

Java(TM) SE Runtime Environment (build 1.8.0_60-b27)

> I pushed a potential fix for some leaks

Brilliant - we're seeing a steady 2GB total memory usage (as reported by top) when I run our benchmarks. I'm going to push this out to our team and see how we get on but this is really good - thank you!

Matt.

**Comment by bhamiltoncx** [comment]
Huzzah! Thanks for reporting.

**Comment by bhamiltoncx** [comment]
(And my fixes did make it to master as well.)
