### ISSUE TITLE
connection reset by peer if buckd left running overnight

### ISSUE THREAD

**Issue by mread** [facebook/buck#409]
Each time that I've left buckd running overnight, the following day my first attempt to run a build dumps the following followed by nailgun dying. The next attempt restarts nailgun and everything is fine again.

```
recv: Connection reset by peer
Traceback (most recent call last):
  File "<pyrun>/pyrun2.7.py", line 788, in <module>
  File "<pyrun>/pyrun2.7.py", line 664, in pyrun_execute_script
  File "/some-dir/buck/bin/../programs/buck.py", line 52, in <module>
    propagate_failure(main(sys.argv))
  File "/some-dir/buck/bin/../programs/buck.py", line 45, in main
    return buck_repo.launch_buck(build_id)
  File "/some-dir/buck/programs/buck_tool.py", line 130, in launch_buck
    if new_buckd_run_count == 0 or not self._is_buckd_running():
  File "/some-dir/buck/programs/buck_tool.py", line 326, in _is_buckd_running
    stderr=subprocess.STDOUT)
  File "/some-dir/buck/programs/subprocutils.py", line 29, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocutils.CalledProcessError: Command '['/some-dir/buck/build/ng', 'ng-stats', '--nailgun-server', 'local:.buckd/sock']' returned non-zero exit status 227
```

**Comment by sdwilsh** [comment]
Is this a recent regression?  Looks like you are using the unix domain socket version of buckd here.

**Comment by bhamiltoncx** [comment]
Likely related to my Unix domain socket change, although I'm not sure what would be special about buckd running overnight. It's most likely this is due to buckd shutting itself down and the client not knowing about that.

**Comment by mread** [comment]
It's recent for us because we rebased from facebook/buck on 1st Sept for the first time since June. Not sure how I'd go about bisecting for this problem - except very slowly. Anything else I could look at?

**Comment by sdwilsh** [comment]
Oh man, there have been a lot of changes since then.  For a sanity 
check, can you update to before 
3f8af8ea22f6ebf8a9020e2d5b942f523bdc077b?  This will let us rule out the 
Unix domain sockets to be sure (I realize it'll take a day to evaluate).

Is there anything interesting in the log?

**Comment by mread** [comment]
No log produced, only a launch.trace which doesn't reveal anything useful, the tail of it is pasted below. 

Rolling back to the version you suggested is quite tricky for us as we have a number of patches that we apply over the top of buck which tend to require a lot of merging. However, if this problem occurs for buckd running against the buck project itself then I could test that quite easily. I'll try it and let you know.

```
{
        "args": {},
        "cat": "buck-launcher",
        "name": "BuckRepo._is_buckd_running",
        "ph": "B",
        "pid": 23403,
        "tid": 1,
        "ts": 1297151216002
    },
    {
        "args": {},
        "cat": "buck-launcher",
        "name": "BuckRepo._is_buckd_running",
        "ph": "E",
        "pid": 23403,
        "tid": 1,
        "ts": 1297152119090
    },
    {
        "args": {},
        "cat": "buck-launcher",
        "name": "BuckRepo.launch_buck",
        "ph": "E",
        "pid": 23403,
        "tid": 1,
        "ts": 1297152119125
    },
    {
        "args": {},
        "cat": "buck-launcher",
        "name": "BuckProject.__exit__",
        "ph": "B",
        "pid": 23403,
        "tid": 1,
        "ts": 1297152119160
    },
    {
        "args": {},
        "cat": "buck-launcher",
        "name": "BuckProject.__exit__",
        "ph": "E",
        "pid": 23403,
        "tid": 1,
        "ts": 1297152119375
    },
    {
        "args": {},
        "cat": "buck-launcher",
        "name": "main",
        "ph": "E",
        "pid": 23403,
        "tid": 1,
        "ts": 1297152119398
    }
```

**Comment by mread** [comment]
Appears to be fixed with the latest code, perhaps it was related to the race condition in nailgun shutdown. Thanks for your help.

**Comment by sdwilsh** [comment]
Thanks for the report!
________________________________
