### ISSUE TITLE
can't build buck tool with space in directory path

### ISSUE THREAD

**Issue by lukeis** [facebook/buck#410]
git clone https://github.com/facebook/buck.git "my buck"
cd "my buck"
ant

output:

Buildfile: /Users/linman/workspaces/selenium/my buck/build.xml

checkversion:

compile-testrunner:
    [mkdir] Created dir: /Users/linman/workspaces/selenium/my buck/build/testrunner/classes
    [javac] Compiling 13 source files to /Users/linman/workspaces/selenium/my buck/build/testrunner/classes

tracing-api:
    [mkdir] Created dir: /Users/linman/workspaces/selenium/my buck/build/tracing-api/classes
    [javac] Compiling 2 source files to /Users/linman/workspaces/selenium/my buck/build/tracing-api/classes
    [javac] properties file /Users/linman/workspaces/selenium/my does not exist

BUILD FAILED
/Users/linman/workspaces/selenium/my buck/build.xml:269: The following error occurred while executing this line:
/Users/linman/workspaces/selenium/my buck/build.xml:398: Compile failed; see the compiler error output for details.

Total time: 1 second

**Comment by sdwilsh** [comment]
Confirmed.  Something about our `build.xml` file doesn't play nice with spaces.

**Comment by v-jizhang** [comment]
This is the same as #422
