### ISSUE TITLE
arm64-v8a ABI is not supported in NdkCxxPlatform

### ISSUE THREAD

**Issue by ide** [facebook/buck#414]
This is for 64-bit ARMv8-a support: https://developer.android.com/ndk/guides/abis.html#arm64-v8a

**Comment by sdwilsh** [comment]
This should be as simple as adding a new entry in `NdkCxxPlatforms`, if 
you happen to feel mildly ambitious.

**Comment by LegNeato** [comment]
More specifically here:

https://github.com/facebook/buck/blob/ad8f8c246535084cd2bbf8d12ae997def76ee7ce/src/com/facebook/buck/android/NdkCxxPlatforms.java#L169

**Comment by sdwilsh** [comment]
4abf4af792d8bfd48e08148f2433431916135676 is an example of how to add another platform as well.

**Comment by ajtulloch** [comment]
@LegNeato  were you planning on PR'ing https://github.com/LegNeato/buck/commit/9e14600b0ff704ae8574b77cf256f31340b7fbc3?

**Comment by LegNeato** [comment]
@ajtulloch Not currently. Mainly because it has probably bitrotted and I don't have a test project to muck around with to make sure everything works correctly.

**Comment by dreiss** [comment]
This looks fine to me, though the default flags should be updated to match https://android.googlesource.com/platform/ndk.git/+/nougat-release/build/core/toolchains/aarch64-linux-android-4.9/setup.mk .

**Comment by dreiss** [comment]
@LegNeato , can you PR it just so we can use our normal import/CLA machinery?  We can probably get someone else to handle the rebase, cleanup, and test.

**Comment by LegNeato** [comment]
It actually rebased cleanly. I'll PR, do you want me to update the flags? I can't really test anything 😄

**Comment by ajtulloch** [comment]
@LegNeato  sure, that would be great. We'll test internally.
