### ISSUE TITLE
buck cannot find the attribute defined in another package

### ISSUE THREAD

**Issue by llj098** [facebook/buck#415]
I have two projects: `A` and `B`, `A` depends on `B`. In project B, I have a custom view and attribute.

If I build `B` only, it success, if I build `A`(which depends on the resource and source code of `B`) it fails.

I have make a example project at https://github.com/llj098/buck-res-issue

When I run `buck build b:app` success, but I run `buck build a:app` it shows:

```
b/res/layout/main.xml:15: error: No resource identifier found for attribute 'start' in package 'com.example.b'
```

**Comment by llj098** [comment]
buck version *390487558bc1d333c7146bb4e03a7661119012f3

**Comment by sdwilsh** [comment]
the `android_resource` for `A` depends on resources defined in `B`, but you don't declare a dependency.  This fixes it for me:

```diff
--- a/a/BUCK
+++ b/a/BUCK
@@ -5,6 +5,9 @@ android_resource(
   name = 'res',
   res = 'res',
   package = 'com.example.a',
+  deps = [
+    '//b:res',
+  ],
   visibility = ['PUBLIC'],
 )

@@ -34,7 +37,6 @@ android_binary(
   keystore = ':debug_keystore',
   package_type = 'debug',
   deps = [
-    '//b:res',
     '//b:src',
     ':res',
     ':src',```

**Comment by llj098** [comment]
Hi @sdwilsh Thanks for your support!

It works with your change, but after I rename the layout `main.xml` to `m.xml`, I run `buck build a:app`, it shows:

```
Using buckd.
Adding watchman root: .
[-] PROCESSING BUCK FILES...FINISHED 0.1s
[+] BUILDING...0.0s (0/13 JOBS, 0 UPDATED)
 |=> //a:debug_keystore...  0.0s (checking local cache)
 |=> //b:res...  0.0s (checking local cache)
 |=> IDLE
b/res/layout/m.xml:15: error: No resource identifier found for attribute 'start' in package 'com.example.b'
```

So, it seems that only main.xml works,, is it a bug or I missed something?

Thanks.

**Comment by sdwilsh** [comment]
Per http://stackoverflow.com/questions/3441396/defining-custom-attrs, your namespace should be `http://schemas.android.com/apk/res-auto`, not `http://schemas.android.com/apk/res/com.example.b`.  That works locally for me.

**Comment by llj098** [comment]
Yes it works. Thank you very much for your excellent work!
