### ISSUE TITLE
android_prebuilt_aar fails if an aar is missing a classes.jar

### ISSUE THREAD

**Issue by rowillia** [facebook/buck#417]
For example, try creating an `android_prebuilt_aar` for $ANDROID_HOME/extras/google/m2repository/com/google/android/gms/play-services/7.5.0/play-services-7.5.0.aar

**Comment by sdwilsh** [comment]
*sigh*

It is supposed to be mandatory!

http://tools.android.com/tech-docs/new-build-system/aar-format

**Comment by npapanastasiou** [comment]
Looks like Google disagrees with Google on that. Does anybody know of a workaround?

**Comment by sdwilsh** [comment]
We'll have to make Buck tolerate it.  It's possible we can just add a `TouchStep` to create a `classes.jar` file if it doesn't exist.

**Comment by prince-gill** [comment]
Any update on this? Or a workaround? Attempting to use play-services-8.4.0.aar.

**Comment by polycoder** [comment]
I took a quick shot at a fix in #680. This seems to work for me and allows building a project even if the aar does not contain a classes.jar file. @sdwilsh if you think this is an alright approach I can back fill an integration test :smile:
