### ISSUE TITLE
`prebuilt_jar` fails with "Failed when trying to copy" in Gerrit build

### ISSUE THREAD

**Issue by dpursehouse** [facebook/buck#419]
I updated the version of Buck used in Gerrit from 8204fddf60b25a3c2090f3ef0742fca5d466d562 to 60a29692e8822388bf4178907d78c198d06504c0 and the build starts to fail with:

`Failed when trying to copy: cp buck-out/gen/gerrit-antlr/query_parser.jar buck-out/gen/gerrit-antlr/query_parser.jar`

I ran `git bisect` between the previous and new revisions and it says the culprit is 441d33cc08d725225a18d1e11cb8168df4a59223 ("PrebuiltJar: copy wrapped JARs generated from other rules").

The part of the build that's failing is:

```
# Hack necessary to expose ANTLR generated code as JAR to Eclipse.
genrule(
  name = 'query_link',
  cmd = 'ln -s $(location :lib) $OUT',
  deps = [':lib'],
  out = 'query_parser.jar',
)

prebuilt_jar(
  name = 'query_parser',
  binary_jar = ':query_link',
  deps = PARSER_DEPS,
  visibility = ['PUBLIC'],
)
```

It looks like `prebuilt_jar` is trying to copy `query_parser.jar` before the symlink has been created by the previous `genrule`?

**Comment by davido** [comment]
I think this is a collision between the output of `genrule` and `prebuilt_jar` name. I think that another build rule in Gerrit `prolog:common` is also affected from this change: [1]. This diff (will upload it for revew in a minute) fixes the problem:

```
diff --git a/gerrit-antlr/BUCK b/gerrit-antlr/BUCK
index 03c3c1e..d9abc13 100644
--- a/gerrit-antlr/BUCK
+++ b/gerrit-antlr/BUCK
@@ -26,7 +26,7 @@ genrule(
   name = 'query_link',
   cmd = 'ln -s $(location :lib) $OUT',
   deps = [':lib'],
-  out = 'query_parser.jar',
+  out = 'query_link.jar',
 )
```

* [1] http://paste.openstack.org/show/461552

**Comment by davido** [comment]
In case it helps, this diff seems to fix the collision in Gerrit build: [1]. I think there is place for improvement for the error message reporting in this case.

* [1] https://gerrit-review.googlesource.com/70873

**Comment by dpursehouse** [comment]
Thanks @davido that fixes it.  I'll close this issue.

**Comment by sdwilsh** [comment]
@shs96c is trying to better namespace `genrule` so this isn't a problem, but yeah, it's a collision.

**Comment by davido** [comment]
@sdwilsh , @shs96c This collision is kind of unexpected and i consider this as regression and the most painful thing about it, it restricts the naming of `genrule` output artifact and `prebuilt_jar` name.

Before 441d33c it was possible to say smething like that:

```
  genrule(name = 'gen_foo_private_rule',
    cmd = 'ln -s $(location :lib) $OUT',
    deps = [':lib'],
    out = 'foo.jar',
  )

  prebuilt_jar(
    name = 'foo',
    binary_jar = ':gen_foo_private_rule',
    deps = ':deps',
    visibility = ['PUBLIC'],
  )
```

As pointed out by @dpursehouse after 441d33c we lost this naming option. But this is realy bad for us as we would like both to have foo.jar to be named in out final artifact (`gerrit.war`), and we also would like to have self explained name for our public rules `foo` in the example above. So that the consumer of `foo` would immediately see and understand what `foo` is trying to achieve.

**Comment by shs96c** [comment]
I'm trying to land a fix for that now.

**Comment by dpursehouse** [comment]
Thanks @shs96c. I've reopened this issue.  When your fix lands I'll upgrade to that version instead of 60a2969. We're currently trying with f2f6d86ba1de544e7fd825a8a6cafe258512a7e4 plus @davido's workaround.

**Comment by sdwilsh** [comment]
It should go out today.

**Comment by sdwilsh** [comment]
https://github.com/facebook/buck/commit/c92ef212b53fff08a8452649b4d4faadc6b89b11 should do it.

**Comment by dpursehouse** [comment]
I can confirm that it now [works as expected](https://gerrit-review.googlesource.com/#/c/70887/).

Thanks for the quick response and fix.
