### ISSUE TITLE
Compile Failed at line 399 and also at 270

### ISSUE THREAD

**Issue by rambabusaravanan** [facebook/buck#422]
Instead of cloning from git, I downloaded the zip and proceeded.

E:\Program Files\Android\buck>javac -version
javac 1.7.0_25

E:\Program Files\Android\buck>ant -version
Apache Ant(TM) version 1.9.2 compiled on July 8 2013

E:\Program Files\Android\buck>py -V
Python 3.5.0

E:\Program Files\Android\buck>ant
Buildfile: E:\Program Files\Android\buck\build.xml

checkversion:

compile-testrunner:

tracing-api:
    [javac] Compiling 2 source files to E:\Program Files\Android\buck\build\tracing-api\classes
    [javac] properties file E:\Program does not exist

BUILD FAILED
E:\Program Files\Android\buck\build.xml:270: The following error occurred while executing this line:
E:\Program Files\Android\buck\build.xml:399: Compile failed; see the compiler error output for details.

Total time: 1 second

E:\Program Files\Android\buck>

-------------------------------------------------------------------------
`268  <target name="tracing-api" depends="checkversion">`
`269    <mkdir dir="${tracing-api.classes.dir}" />`
`270    <ecj destdir="${tracing-api.classes.dir}" classpathref="tracing-api.classpath">`
`271      <javac-params>`
`272        <include name="${tracing-api.src.dir}/**/*.java"/>`
`273      </javac-params>`
`274    </ecj>`
`275    <jar destfile="${tracing-api.jar}">`
`276      <fileset dir="${tracing-api.classes.dir}"/>`
`277    </jar>`
`278  </target>`

-----------------------------------------------------------------------
`389    <element name="ecj-params" optional="true" />`
`390    <sequential>`
`391      <javac srcdir="@{srcdir}"`
`392             sourcepath=""`
`393             destdir="@{destdir}"`
`394             classpathref="@{classpathref}"`
`395             debug="on"`
`396             deprecation="on"`
`397             includeAntRuntime="no"`
`398             compiler="org.eclipse.jdt.core.JDTCompilerAdapter"`
`399             >`
`400        <javac-params />`

**Comment by tgummerer** [comment]
Building buck currently doesn't work in directories with spaces in them, see #410.

**Comment by sdwilsh** [comment]
@tgummerer beat me to this.  This is the same as #410.
