### ISSUE TITLE
Python syntax error at buck.py and buck_tool.py

### ISSUE THREAD

**Issue by rambabusaravanan** [facebook/buck#424]
OS : Windows 8

E:\ProgramFiles\Android\buck>javac -version
javac 1.7.0_25

E:\ProgramFiles\Android\buck>ant -version
Apache Ant(TM) version 1.9.2 compiled on July 8 2013

E:\ProgramFiles\Android\buck>py -V
Python 3.5.0

E:\ProgramFiles\Android\buck>ant
...
...
Success

E:\ProgramFiles\buck\bin>buck --help
Traceback (most recent call last):
  File "E:\ProgramFiles\buck\bin\..\programs\buck.py", line 9, in <module>
    from buck_tool import BuckToolException, RestartBuck
  File "E:\ProgramFiles\buck\programs\buck_tool.py", line 228
    except OSError **,** e:
                  ^
SyntaxError: invalid syntax

E:\ProgramFiles\buck\bin>

Help me please

**Comment by sdwilsh** [comment]
Buck only works with python 2.6 and 2.7: https://buckbuild.com/setup/install.html
________________________________

**Comment by plinehan** [comment]
For anyone else coming across this, note that Buck now requires Python 2.7.  There's a dict comprehension in buck_tool.py that you'll hit first:

```
envp = {k.encode('utf8'): v.encode('utf8') for k, v in cmd['envp'].iteritems()}
                                                 ^
SyntaxError: invalid syntax
```
