### ISSUE TITLE
Feature request: `buck run`-able tests

### ISSUE THREAD

**Issue by mikekap** [facebook/buck#430]
It would be nice to `buck run` a test to debug timeouts/hangs.

**Comment by sdwilsh** [comment]
Can you elaborate?  I'm not sure what `buck test

**Comment by mikekap** [comment]
Well buck test doesn't output anything to stdout/err for ^C-ed tests. I also found no way to get it to print output of successful tests. The latter came in useful when changing an implementation did NOT break a test as it should have - i ended up putting an assertTrue(false) just to get the test to print something.

In case of deadlocks you can definitely manually set the timeout, but I find it easier to just run the test and see the output asap.

**Comment by sdwilsh** [comment]
Something like `buck test --interactive` might be okay then?

**Comment by mikekap** [comment]
Sounds great - I just remember `blaze run //:test-target` from the original :X

**Comment by sdwilsh** [comment]
I mean, we could probably do that too.  I don't think it would be too 
hard to make happen (you just have to implement the right interface and 
`buck run` should work).
