### ISSUE TITLE
path in cache's http_url being ignored

### ISSUE THREAD

**Issue by mread** [facebook/buck#434]
This commit 8f5949bba7a05fc3a304bbed87a29efd4bc9821a appears to introduce a leading / into the url.resolve() calls at line 98 and 203. If your http_url has a path (as ours does) then this breaks the cache fetches and puts. Ping @marcinkosiba.

**Comment by sdwilsh** [comment]
Can you explain in a bit more details what you mean by a path (an example would probably be sufficient, but I want to make sure I understand the report)?

**Comment by mread** [comment]
Here's our .buckconfig.local. The key part is `/buckcache/` this worked before that commit but not after. I haven't confirmed this myself but I'm told we're seeing cache requests going to the root URL instead.
```
[cache]
  mode = http
  http_url = http://our.cache.server.lmax.com:9090/buckcache/
  http_mode = readonly
  http_timeout_seconds = 5
```

**Comment by sdwilsh** [comment]
@marcinkosiba has fixed this internally, so I should get it out tomorrow.  Thanks for the report.
