### ISSUE TITLE
Buck creates invalid JSON compilation databases

### ISSUE THREAD

**Issue by milch** [facebook/buck#437]
When creating a JSON compilation database using `buck build` and the `compilation-database` flavor for a C++ library, the generated JSON file will be invalid according to the current [specification](http://clang.llvm.org/docs/JSONCompilationDatabase.html). This causes problems when trying to load the compilation database using the [clang tooling interface](http://clang.llvm.org/doxygen/group__COMPILATIONDB.html). 

Also, some weird string is inserted into the parameters, check out the following excerpt: 

```js
[{
// ...
"command":"/usr/bin/clang -g \u0027-std\u003dc11\u0027 -fPIC -g \u0027-std\u003dc11\u0027 -I \
buck-out/gen/common/hello#default,private-headers.hmap -I \
buck-out/gen/common/hello#default,headers.hmap -I \
buck-out -Xclang -fdebug-compilation-dir -Xclang \
.///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// \
-x c -c -MD -MF \
buck-out/gen/common/hello#compile-pic-hello.c.o,default/hello.c.o.dep.tmp \
common/hello.c -o \
buck-out/gen/common/hello#compile-pic-hello.c.o,default/hello.c.o"
// ...
}]
```

### Steps to reproduce

- Clone the [bucksamples](https://github.com/fbsamples/bucksamples) repository.
- `cd` into the `cross-platform-scale-2015-demo` subfolder and run the following command:

```
buck build //common:hello#compilation-database
```

- Find the resulting file named `__hello#compilation-database.json` in the `buck-out/gen/common` folder.

### Expected Results

For each object in the array of compile commands, there should only be `command`, `file` and `directory` properties as per the Clang specification cited above.

**Comment by k21** [comment]
It looks like the `directory` entry contains the directory of the file instead of the working directory from which the command should be executed. That should be fixed. The extra `args` key is not mentioned in the specification, but it is also not forbidden, so I don't think it makes the database invalid. The `command` entry that you have pasted is a valid command if you do JSON unescaping, I don't see an issue there.

Please also let us know how you are using the compilation database output and what errors you are seeing, having a way to test if our changes work will make fixing the issue easier.

Also, can you please try replacing `bucksamples/cross-platform-scale-2015-demo/common` in the `directory` entry with `bucksamples/cross-platform-scale-2015-demo` and try using the modified file? I suspect it might resolve the issues you are seeing.

**Comment by milch** [comment]
> Also, can you please try replacing bucksamples/cross-platform-scale-2015-demo/common in the directory entry with bucksamples/cross-platform-scale-2015-demo and try using the modified file? 

I had already tried that, it works regardless which working directory is used, but I agree it needs to be fixed - some tools might work, some probably won't. 

> The extra args key is not mentioned in the specification, but it is also not forbidden, so I don't think it makes the database invalid.

It isn't explicitly forbidden, but if you try accessing the compilation database through the clang tooling API (the one I posted in the original issue) you get a `CXCompilationDatabase_CanNotLoadDatabase` error.

**Comment by Coneko** [comment]
This is what I get:

```json
[
    {
        "args": [
            "/usr/bin/clang",
            "-g",
            "-std=c11",
            "-fPIC",
            "-g",
            "-std=c11",
            "-I",
            "buck-out/gen/common/hello#default,private-headers.hmap",
            "-I",
            "buck-out/gen/common/hello#default,headers.hmap",
            "-I",
            "buck-out",
            "-Xclang",
            "-fdebug-compilation-dir",
            "-Xclang",
            "./////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////",
            "-x",
            "c",
            "-c",
            "-MD",
            "-MF",
            "buck-out/gen/common/hello#compile-pic-hello.c.o,default/hello.c.o.dep.tmp",
            "common/hello.c",
            "-o",
            "buck-out/gen/common/hello#compile-pic-hello.c.o,default/hello.c.o"
        ],
        "command": "/usr/bin/clang -g '-std=c11' -fPIC -g '-std=c11' -I buck-out/gen/common/hello#default,private-headers.hmap -I buck-out/gen/common/hello#default,headers.hmap -I buck-out -Xclang -fdebug-compilation-dir -Xclang .///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// -x c -c -MD -MF buck-out/gen/common/hello#compile-pic-hello.c.o,default/hello.c.o.dep.tmp common/hello.c -o buck-out/gen/common/hello#compile-pic-hello.c.o,default/hello.c.o",
        "directory": "/Users/coneko/github/fbsamples/bucksamples/cross-platform-scale-2015-demo/common",
        "file": "/Users/coneko/github/fbsamples/bucksamples/cross-platform-scale-2015-demo/common/hello.c"
    }
]
```

The strange output in command doesn't seem to be there. What is your `LANG` set to?

Is `args` being there a problem? Does the clang tooling not ignore it? We can remove it if it is.

cc @bolinfest since https://github.com/facebook/nuclide uses it.

**Comment by Coneko** [comment]
> It isn't explicitly forbidden, but if you try accessing the compilation database through the clang tooling API (the one I posted in the original issue) you get a `CXCompilationDatabase_CanNotLoadDatabase` error.

I guess we should remove it then.

**Comment by bolinfest** [comment]
Ah, I remember why I added this nonstandard `args` property. `args` is an array of string arguments whereas `command` is an opaque string. `command` puts the burden on the caller to safely split the string in order to exec a new clang process with the arguments specified as an array. It is trivial to derive `command` from `args`, but the converse is not true.

**Comment by bolinfest** [comment]
@milch I don't see the instructions for passing the compilation database to the clang tooling you mentioned. I want to be 100% sure that we can't have both `command` and `args` as properties on the compilation database. It seems very strange to me that someone would write a JSON parser that looks for ignored properties and rejects if they are present.

**Comment by milch** [comment]
The docs (and the whole API, really) are a bit weird there, I believe you can't pass a file name directly, only the dir where the file is. [`clang_CompilationDatabase_fromDirectory`](http://clang.llvm.org/doxygen/group__COMPILATIONDB.html#gae0822a6a54afaea92bad5d3b3256bf26) is the name of the function, you can then test to see if worked by inspecting the ErrorCode pointer you pass in. 

The documentation also isn't clear on what to name the compilation database itself, but `compile_commands.json` should be correct.

**Comment by LegNeato** [comment]
They do indeed throw an error on unrecognized key:

http://reviews.llvm.org/diffusion/L/browse/cfe/trunk/lib/Tooling/JSONCompilationDatabase.cpp;248984$307

Also,would be nice for their docs mention xctool and buck as supported tools ;-)

http://reviews.llvm.org/diffusion/L/browse/cfe/trunk/docs/JSONCompilationDatabase.rst

**Comment by bolinfest** [comment]
@LegNeato Thanks for finding the line. It seems like a simple pull request to rip that out: it seems unnecessarily Draconian.

**Comment by LegNeato** [comment]
I added Buck and xctool to the docs (http://reviews.llvm.org/D13327), will put up a patch for the other one hopefully tonight.

**Comment by LegNeato** [comment]
@bolinfest no need! Looks like they added a structured way for arguments:

http://reviews.llvm.org/rL245036

It should be as simple as doing `s/args/arguments/` on the key :clap:

**Comment by bolinfest** [comment]
@LegNeato Sweet! /cc @coneko hopefully we can clean this up in Buck/Nuclide tomorrow.

**Comment by milch** [comment]
Nice! Thanks for the quick solution, everyone.

**Comment by LegNeato** [comment]
https://github.com/facebook/buck/commit/46945e4400e649433b079442dec4be98e964360f doesn't appear to set the new `arguments` value in the clang format?

**Comment by Coneko** [comment]
I added them in 1fc71e1d3a95fb02b91c503cff1a9df7ae6531df.

**Comment by Coneko** [comment]
Latest Buck master only specifies `arguments` and not `args`, so this should be solved.

**Comment by kastiglione** [comment]
Note that this does not work for clang 3.7, which still expects the `command` string and doesn't handle `arguments` array.
