### ISSUE TITLE
iOS Dynamic Frameworks

### ISSUE THREAD

**Issue by crylico** [facebook/buck#440]
Does buck support pre-built dynamic frameworks for iOS? After some digging through the docs, it looks like it only supports static libs

**Comment by sdwilsh** [comment]
It does not currently.

**Comment by crylico** [comment]
gotcha! so is prebuilt_cxx_library() currently the only way to get prebuilt code into a project?

**Comment by sdwilsh** [comment]
That's correct.  If there's some specific thing you are trying to do, we might be able to tell you about a better way (or how to change Buck to do what you need), but that's the generic hammer :)

**Comment by crylico** [comment]
thanks for the feedback :) basically just trying to use [Carthage](https://github.com/carthage/carthage) generated frameworks with a buck project.

I understand it's a work in progress and I really like the ideas behind buck - looking forward to seeing it grow!

**Comment by Coneko** [comment]
I'm sure @jspahrsummers would love to add Buck support to Carthage.

**Comment by petersibley** [comment]
Are there any plans to support dynamic frameworks as a target type?

**Comment by Coneko** [comment]
You can already create dynamic frameworks by using `apple_bundle` and setting its `binary` attribute to refer to a `apple_library` with the `#shared` flavour.

We are planning to make the interface nicer though.

**Comment by petersibley** [comment]
O cool. You might consider updating the docs to reflect this. It wasn't clear to me that you could do that. Thanks.

**Comment by crylico** [comment]
Oh neat! What about embedding a dynamic framework that's already been
compiled?

**Comment by Coneko** [comment]
`prebuilt_cxx_library` helps you a bit there, but in practice it's only supported in the cxx workflow, not in the iOS workflow, so project generation and so on won't work.

Most likely not what you're looking for there, sorry.

**Comment by mindows** [comment]
Any updates on this? How would I add something like facebook sdk to my app? generated xcode project that depends on the framework would be pretty broken without the framework + headers included properly, right?

**Comment by Coneko** [comment]
There is a hacky workaround we use, I mentioned it here: https://github.com/facebook/buck/issues/660#issuecomment-202884912

**Comment by aledalgrande** [comment]
Looks like there was a development here, but it was never documented. https://github.com/facebook/buck/pull/1263 adds docs.
