### ISSUE TITLE
Change Github project description

### ISSUE THREAD

**Issue by LegNeato** [facebook/buck#442]
Currently:

`A build system that encourages the creation of small, reusable modules. http://buckbuild.com`

It has no sizzle! Why not fast? Why not the fact that it spans many platforms?

`A fast build system that encourages the creation of small, reusable modules across Android, iOS, desktop, and server. http://buckbuild.com`

Or something.

**Comment by sdwilsh** [comment]
Set to this:
A fast build system that encourages the creation of small, reusable modules over a variety of platforms and languages.

**Comment by LegNeato** [comment]
:clap:
