### ISSUE TITLE
Does this can help build easily? 

### ISSUE THREAD

**Issue by brucetoo** [facebook/buck#447]
i just find a gradle plugin https://github.com/Piasy/OkBuck, i think may be u offical can offer one like this.

**Comment by Coneko** [comment]
That looks really interesting, thanks for posting it here, we will have a look!

**Comment by brucetoo** [comment]
Yup,ignore buggy and difficult steps,may Buck will be more famous

**Comment by qichuan** [comment]
Yup, that is a useful one, and the developer is responding very fast.

**Comment by sdwilsh** [comment]
I plan to reach out when I get back from time off (next week) and see if we can smooth over some of the bumps too.

**Comment by sdwilsh** [comment]
This isn't really an issue per-se.  @Piasy has been fixing stuff and making it better.

**Comment by Piasy** [comment]
@sdwilsh Thanks! But there is still a big problem on RetroLambda support...
