### ISSUE TITLE
./buck project --ide option says providing a value is optional, but requires value

### ISSUE THREAD

**Issue by baroquebobcat** [facebook/buck#452]
The help text says it will default to intellij if not set [ref](https://github.com/facebook/buck/blob/b8fa3fa7c03a8df28deaa53ece5078d66024d1e4/src/com/facebook/buck/cli/ProjectCommand.java#L181-L182), but instead it asks you to provide or set it:

```
$ ./buck project
...

Using buckd.
[+] PROCESSING BUCK FILES...24.1s [100%]
BUILD FAILED: Please specify ide using --ide option or set ide in .buckconfig
```

**Comment by sdwilsh** [comment]
@beefon changed this, IIRC, but it looks like we missed updating it.

**Comment by baroquebobcat** [comment]
Thanks! That's much better.
