### ISSUE TITLE
Distribute buck via apt-get

### ISSUE THREAD

**Issue by jiangty-addepar** [facebook/buck#453]
I noticed Buck now has releases which are distributed via Homebrew. We'd also like if Buck could be packaged into `.deb` files that can be distributed via `apt-get`.

If facebook can't do this due to company policy or whatever, we might just go ahead and do it ourselves.

**Comment by sdwilsh** [comment]
Homebrew is super easy because we can just point it at a tag and it gets that version.  Making it work in apt-get is a fair bit more work, which is why it hasn't been done yet (same with a Windows installer).

**Comment by nayrmi** [comment]
Closing for now. Feel free to reopen if you want to take a stab at it!
