### ISSUE TITLE
End of input at line 1 column 1

### ISSUE THREAD

**Issue by androidmalin** [facebook/buck#455]
I follow the guidance of this website
https://buckbuild.com/setup/manual_quick_start.html

The following error occurred:
malin@malin:~/my-first-buck-project$ buck build //apps/myapp:app
Using buckd.
[+] PARSING BUCK FILES...0.1s
BUILD FAILED: Parse error for build file /home/malin/my-first-buck-project/apps/myapp/BUCK: End of input at line 1 column 1

**Comment by sdwilsh** [comment]
If you look in `buck-out/logs` there will be a log file with more information.  @Coneko is working on making that error message better.

**Comment by Coneko** [comment]
Fix is ready and will go out during the next sync.
