### ISSUE TITLE
Better pdb support for python

### ISSUE THREAD

**Issue by digwanderlust** [facebook/buck#459]
Currently much of the python/java interaction is handled through system calls to python scripts passing information to the script using standard in.  This is done because passing values via command line arguments sometimes blows through the command line arg limit.  The problem is that pdb has problems if other processes are using stdin/stdout since it also relies on them.  This makes troubleshooting issues within buck difficult.

Ideally you should be able to drop a set_trace anywhere in python code and have it properly drop to pdb.  Also it would be helpful to be able to run the run and test goals with a mode that drops to pdb on failure.

**Comment by v-jizhang** [comment]
Sorry we never got back to this! At this point, we are closing this because it is quite out of date and it is not clear if the issue still exists. Please create a new one if you still see the problem. Thank you.
