### ISSUE TITLE
Default activity is ambiguous when bundling leak canary

### ISSUE THREAD

**Issue by joshzana** [facebook/buck#464]
I am trying to integrate https://github.com/square/leakcanary into my app, but it declares its own launcher activity with intent filter
```
        <intent-filter>
            <action android:name="android.intent.action.MAIN"></action>
            <category android:name="android.intent.category.LAUNCHER"></category>
        </intent-filter>
```

When I install with --run I get this
BUILD FAILED: Default activity is ambiguous.

Using -a works, but is undesirable since the Android Studio plugin doesn't use it.

Any advice?

**Comment by joshzana** [comment]
Just realized the launcher activity in LeakCanary has android:enabled="false", and that buck ignores disabled activity-aliases, but not disabled activities.

Suggested fix: also ignore disabled activities when searching for launcher activities.  The issue can be fixed with a tweak to DefaultAndroidManifestReader.XPATH_LAUNCHER_ACTIVITIES.

Will put up a PR with the fix and a unit test.

**Comment by sdwilsh** [comment]
That sounds awesome!
