### ISSUE TITLE
Autocomplete in #import statements in Xcode

### ISSUE THREAD

**Issue by adamhowardprice** [facebook/buck#473]
It seems that when you use .hmap files for header search paths, it kills Xcode's ability to provide autocomplete suggestions for which files you'd like to import. I wasn't able to find much Xcode documentation about this.

Do you have any suggestions for workarounds? I'm considering using Buck to build my company's large iOS project, and I'm sure the team would consider losing autocomplete for #import statements as a regression, despite the great improvements we would get in build times.

**Comment by Coneko** [comment]
We used to add the header symlinks to the search paths as well, but it turned out to slow down Xcode too much.

Would an [Alcatraz](https://github.com/supermarin/Alcatraz) plugin to enable that be acceptable?

**Comment by adamhowardprice** [comment]
What about an optional argument to the `buck project` command?

**Comment by Coneko** [comment]
We support building without header maps anyway, so it should be easy to add support back in for Xcode.

I'll get back to you.

**Comment by Coneko** [comment]
Ok, we're going to add a switch to have the generated project be backed by header symlink trees as well as header maps.

**Comment by adamhowardprice** [comment]
Sounds great!

**Comment by k21** [comment]
Closed by https://github.com/facebook/buck/commit/9d50192185ae23d300a718018910c7988e28405f.
