### ISSUE TITLE
Get classes.jar out of android_resource() to build Kotlin

### ISSUE THREAD

**Issue by andrzejtokarski** [facebook/buck#474]
I'm trying to build an Android app written in Kotlin using Buck. I started with https://github.com/zserge/buckbone and it builds the APK after fixing some hardcoded paths. The problem is that there is no simple way of providing the Kotlin genrule() with R.class .

**Comment by sdwilsh** [comment]
Buck doesn't generate the `R.class` file until we produce the APK, I believe.  This might not actually be possible.

With that said, how we do Java-like languages has been refactored (there's now a jvm module), so it might be a lot easier to add Kotlin support natively into Buck, which would remove the need for some of the hacks folks currently have to do.

**Comment by sdwilsh** [comment]
I think the only way you are going to be able to do this is to implement Kotlin in Buck.  The good news is that @mikekap and @grumpyjames have been doing a lot of work to make it possible to add new JVM-backed languages.
