### ISSUE TITLE
 package R does not exist although it generated in buck-out

### ISSUE THREAD

**Issue by symphony2512** [facebook/buck#476]
Hi everone,
Please help me for this issue when build with Buck 
Here is result error when I build by buck 

ai@ai-VirtualBox:~/newapp3$ buck build app
Using buckd.
[-] PROCESSING BUCK FILES...FINISHED 0.4s [100%]
[-] BUILDING...FINISHED 0.1s [100%] (1/7 JOBS, 0 UPDATED, 0.0% CACHE MISS)
ai@ai-VirtualBox:~/newapp3$ buck build app
Using buckd.
[-] PROCESSING BUCK FILES...FINISHED 0.4s [100%]
[+] BUILDING...1.6s [41%] (3/7 JOBS, 0 UPDATED, 0.0% CACHE MISS)
 |=> //java/com/androi/example:app...  1.4s (running javac[1.3s])
/home/ai/newapp3/java/com/androi/example/MainActivity.java:10: error: package R does not exist
	String mystring = getResources().getString(R.string.app_name);
                                                    ^
Errors: 1. Warnings: 0.

And here is MainActivity

package com.androi.example;

import android.app.Activity;
import android.os.Bundle;

public class MainActivity extends Activity {
	@Override
	public void onCreate(Bundle b) {
		super.onCreate(b);
	String mystring = getResources().getString(R.string.app_name);
	}
}

here is R java I see it generated in buck-out .../ __app#aapt_package_rdotjava_src__

package com.androi.example;

public class R {

  public static class string {
    public static final int app_name=0x7f020000;
  }

}

**Comment by Piasy** [comment]
@symphony2512 Do you set `android_resource` rule and set the right `package` value in your BUCK file? It seems that the generated R class doesn't locate in the same package with `MainActivity.java`.

**Comment by symphony2512** [comment]
I make this project like buckbonejave file in github

And I see there are 3 buck file
And when I build this project, I cd into root directory of project and enter "buck build app"

Here is a BUCK file in same package with MainActivity.java

android_library(
	name = 'app',
	srcs = glob(['*.java']),
	visibility = [ 'PUBLIC' ],
	deps = [
		# Uncomment this if you want to include otto as a maven dependency
		# ':otto',
	],
)

# Example of maven dependencies
#maven('com.squareup:otto:1.3.7')

project_config(src_target = ':app')


And here is a BUCK file in apps/com/android/example

android_binary(
	name = 'app',
	manifest = 'AndroidManifest.xml',
	keystore = ':debug_keystore',
	deps = [
		'//java/com/androi/example:app',
		'//res/com/androi/example:res',
	],
)

keystore(
	name = 'debug_keystore',
	store = 'debug.keystore',
	properties = 'debug.keystore.properties',
)

project_config(src_target = ':app')


and here is BUCK file in res/com/android/example/


android_resource(
	name = 'res',
	res = 'res',
	assets = 'assets',
	package = 'com.androi.example',
	visibility = [
		'//apps/com.androi.example:',
	],
)

project_config(src_target = ':res', src_roots = None)

**Comment by Piasy** [comment]
@symphony2512 Yes, your BUCK file in same package with MainActivity.java defined a `android_library ` rule, while it didn't depend on `android_resource` rule in BUCK file in apps/com/android/example, so the generated R class isn't visible in your `MainActivity.java`.

You should change your `android_resource` rule into this:
```python
android_resource(
name = 'res',
res = 'res',
assets = 'assets',
package = 'com.androi.example',
visibility = [
'PUBLIC',
],
)
```
and change your BUCK file in same package with MainActivity.java into this
```python
android_library(
name = 'app',
srcs = glob(['*.java']),
visibility = [ 'PUBLIC' ],
deps = [
# Uncomment this if you want to include otto as a maven dependency
# ':otto',
# import resources
'//res/com/androi/example:res',
],
)
```

B.T.W. if your project has gradle build files, and the gradle build system works well, you can try this [OkBuck gradle plugin](https://github.com/Piasy/OkBuck), which can generate the magic BUCK file for you, based on your gradle build system.

**Comment by symphony2512** [comment]
Thank you so much. It works!.
