### ISSUE TITLE
Error: Permission denied (publickey)

### ISSUE THREAD

**Issue by AnthonyUccello** [facebook/buck#486]
For now I've manually downloaded antenna pod from github. But when I try to install from the command line as told to from [here](https://buckbuild.com/article/exopackage.html#check-out) I get:

`Error: Permission denied (publickey)`

I tried with sudo and it still failed.

![screen shot 2015-10-27 at 7 30 25 pm](https://cloud.githubusercontent.com/assets/3809669/10775720/36a82a52-7ce1-11e5-97a1-545162afc1ad.png)

Of course one can manually set the head after checking out the antenna pod from github, just a friendly heads up about a potential issue.
![screen shot 2015-10-27 at 7 53 07 pm](https://cloud.githubusercontent.com/assets/3809669/10776035/636cce82-7ce4-11e5-8c7d-c6c08385e6f1.png)

**Comment by Coneko** [comment]
That means your ssh keys aren't set up correctly, you can refer to https://help.github.com/articles/generating-ssh-keys/ for instructions on how to set them up, or you can clone from the https link instead of the git link.
