### ISSUE TITLE
It's building all the time, can't finish

### ISSUE THREAD

**Issue by rambowding** [facebook/buck#487]
![image](https://cloud.githubusercontent.com/assets/7675778/10779436/abbe02d2-7d6b-11e5-861e-ff29b5fb7a0b.png)

package_type is 'release' with proguard_config

**Comment by sdwilsh** [comment]
Do you have a lot of methods?  Creating the dex is going to scale with the number of methods you have (although I've never seen it take this long).

**Comment by rambowding** [comment]
@sdwilsh Yes, a lot of methods, Gradle build my project successfully with multidex, Buck never build successfully. I think there's some error, but I can't find it, no log to show the error

**Comment by sdwilsh** [comment]
There's nothing in `buck-out/logs/`?  We should have the command we are running in there at the very least.

**Comment by sdwilsh** [comment]
No response from @rambowding, so I'm closing this.
