### ISSUE TITLE
BUILD FAILED: //:dslv-res: parameter 'res': no such file or directory 'submodules/dslv/library/res'

### ISSUE THREAD

**Issue by AnthonyUccello** [facebook/buck#489]
I am on the [first step] (https://buckbuild.com/article/exopackage.html#check-out) of the exopackage tutorial.

I am attempting to run the the complete build.

I added the keystore files:

```
# The files and modifications provided by Facebook are for testing and evaluation purposes only.  Facebook reserves all rights not expressly granted.
key.alias=androiddebugkey
key.store.password=android
key.alias.password=android
```

Then attempt to run
`buck install --run antennapod`

And I get this error:

`BUILD FAILED: //:dslv-res: parameter 'res': no such file or directory 'submodules/dslv/library/res'`

It is indeed correct, the folder isnt there:

![screen shot 2015-10-29 at 3 05 02 pm](https://cloud.githubusercontent.com/assets/3809669/10829091/72ad6bac-7e4e-11e5-80d1-a33fc4ae4b2f.png)

But I dont know why (I have the 'complete' branch checked out).

![screen shot 2015-10-29 at 3 05 50 pm](https://cloud.githubusercontent.com/assets/3809669/10829120/97fb48ca-7e4e-11e5-8680-65a5348a39d4.png)

**Comment by sdwilsh** [comment]
Did you do a recursive clone?  That looks like one of the submodules is 
missing some files.

Cheers,

Shawn

**Comment by AnthonyUccello** [comment]
I did not I checked out [antenna pod] (https://github.com/facebookarchive/AntennaPod) with Tower.

I will now try to do a recursive clone (will need to fix my SSH first).
