### ISSUE TITLE
HTTP cache keys not matching when building same code, despite all settings matching

### ISSUE THREAD

**Issue by adamhowardprice** [facebook/buck#494]
I'm building the same small repo at the same revision with the same version of Buck, Xcode, and OS X on two different machines on the same network, and although the server is reachable from the client by navigating to its IP address in a browser, I still get 100% Cache Misses on the client.

I turned on RuleKey logging on both machines and [compared the logs using `scripts/diff_rulekeys.py`.](https://gist.github.com/adamhowardprice/2701de362d38b8f92bb5).

As you can see from the output of that script, it looks like there are matching keys on the left and right side, but they are out of order, for example,

```
Conflict for name //ios/features/FeatureB:FeatureB#compile-Sources_FeatureBImplementation.m.o,iphonesimulator-x86_64 baa370b55a9188d3b7edc2ade871335f0bb95053 c57ad96dd693bc6bd7832dda66b9fff520f1bea5
Conflict for name //ios/features/FeatureB:FeatureB#compile-Sources_FeatureBImplementation.m.o,iphonesimulator-x86_64 c68eeedf3b51a5ec81a6281025d6041d7f3431dd baa370b55a9188d3b7edc2ade871335f0bb95053
Conflict for name //ios/features/FeatureB:FeatureB#compile-Sources_FeatureBImplementation.m.o,iphonesimulator-x86_64 baa370b55a9188d3b7edc2ade871335f0bb95053 c57ad96dd693bc6bd7832dda66b9fff520f1bea5
Conflict for name //ios/features/FeatureB:FeatureB#compile-Sources_FeatureBImplementation.m.o,iphonesimulator-x86_64 c68eeedf3b51a5ec81a6281025d6041d7f3431dd baa370b55a9188d3b7edc2ade871335f0bb95053
```

So, without understanding much of the internal logic, I suspect there are actually matching artifacts, but something about the order they are built or checked is preventing them from matching. On IRC, @sdwilsh mentioned it was possible there was a bug related to file order, or maybe related to using ImmutableList instead of ImmutableSortedSet.

**Comment by sdwilsh** [comment]
I believe that @Coneko will look at this tomorrow when he gets in.

**Comment by sdwilsh** [comment]
The important diffs from that log you linked to:

```
Change details for [//ios:SPTSmallBuckClientBinary#iphonesimulator-x86_64]
  (destinations.appendableSubKey):
    -[ruleKey(sha1=819206430cccf02442865351c574e74e8d33a39d)]
    +[ruleKey(sha1=deadd8c67d89bd1c7df2a438f92906d232968736)]
Change details for [//ios:SPTSmallBuckClientBinary#binary,iphonesimulator-x86_64]
  (buck.deps.appendableSubKey):
    -[ruleKey(sha1=da39a3ee5e6b4b0d3255bfef95601890afd80709)]
    +[ruleKey(sha1=98d356db75e24a7346ae94f6db31657585bfcbe4)]
Change details for [//ios:SPTSmallBuckClientBinary#binary,iphonesimulator-x86_64]
  (.buck.appendableSubKey):
    -[ruleKey(sha1=da39a3ee5e6b4b0d3255bfef95601890afd80709)]
    +[ruleKey(sha1=98d356db75e24a7346ae94f6db31657585bfcbe4)]
```

`destinations.appendableSubKey` would differ if [any of these](https://github.com/facebook/buck/blob/master/src/com/facebook/buck/apple/AbstractAppleBundleDestinations.java#L72) are different on the machines.

`buck.deps.appendableSubKey` is likely different because `//ios:SPTSmallBuckClientBinary#iphonesimulator-x86_64` had a different rule key.

I think `.buck.appendableSubKey` may be different for the reason that `buck.deps.appendableSubKey` is different too.

**Comment by k21** [comment]
Can you please also share the actual logs that you ran the diff script on? Unfortunately the diff script is not perfect and there seems to be some information missing from its output. I would also like to investigate why it is reporting conflicts for rule names, that should not be happening.

**Comment by adamhowardprice** [comment]
[Log 1](https://gist.github.com/adamhowardprice/7da95368703ac51b7671)
[Log 2](https://gist.github.com/adamhowardprice/7c0bd2c7df448400fe04)

**Comment by k21** [comment]
Based on the logs, this seems to be the root of the difference:
```
RuleKey deadd8c67d89bd1c7df2a438f92906d232968736=string(""):key(metadata_path):string(""):key(resources_path):string(""):key(executables_path):string(""):key(frameworks_path):string(""):key(plugins_path):
RuleKey 819206430cccf02442865351c574e74e8d33a39d=string(""):key(metadata_path):string(""):key(resources_path):string(""):key(executables_path):string(""):key(frameworks_path):string("PlugIns"):key(plugins_path):string("Watch"):key(watch_app_path):
```
The second log has correct paths for plugins and watch apps, the first one uses empty path for plugins and is missing the watch app path entirely. I am fairly sure that can never happen on builds using the same Buck version. Are you sure the Buck versions you are the same on both machines? (BTW, if you are using Buck from a repo, make sure to run `ant clean` in its repo to make sure Buck is rebuilt to the version that you have checked-out, otherwise it reports different version than the one that is actually running).

**Comment by adamhowardprice** [comment]
I am pulling the same version of Buck from a shared Artifactory.

I'm really confused about the relevance of the Watch app path in the cache key if I'm not building a watch app. Isn't that something that can be gleaned from the .buckconfig or BUCK files?

**Comment by k21** [comment]
No, it is hardcoded in the code, that is why I believe that your two machines are running different versions of Buck. In particular it looks like only one of your machines has https://github.com/facebook/buck/commit/085eef778ca3e0ed244b0ddbe1bba97065eea9fd. Are you sure you didn't add another Buck installation or checkout on your `PATH` on one of the machines?

**Comment by k21** [comment]
We have resolved this on IRC, it turned out to be caused by different Buck versions between the machines, plus incorrect configuration of the client.
