### ISSUE TITLE
apple_test doesn't work

### ISSUE THREAD

**Issue by adamhowardprice** [facebook/buck#495]
I created a basic project with a test target with one test. Here is the private bitbucket repo... I've shared it with @sdwilsh and @Coneko --> https://bitbucket.org/adamhowardprice/sptsmallbuckclient

Repro steps:
* Run `buck test Client --verbose 5`. It will fail. 
* Scroll up to grab the xctool command it issued. It looks like this: `/usr/local/bin/xctool -reporter json-stream -sdk iphonesimulator -destination 'platform=iPhone 6s Plus' run-tests -appTest /Users/adamprice/Code/SPTSmallBuckClient/buck-out/gen/ios/tests/SPTSmallBuckClientTests#apple-test-bundle/SPTSmallBuckClientTests.xctest:/Users/adamprice/Code/SPTSmallBuckClient/buck-out/gen/ios/SPTSmallBuckClient/SPTSmallBuckClient.app/SPTSmallBuckClient`.
* Copy that command and run it. It will succeed.

Expected result: Both the raw xctool test command and the `buck test Client` command should succeed.

**Comment by ryu2** [comment]
@adamhowardprice What version of xctool are you on?  I couldn't reproduce the `buck test Client --verbose 5` failure locally.

Buck version: da9e44dde29e5ee7ba5adf2b96ad886b7e83aabc
xctool version: 2a72305de60c30dcf3ba738ab5668beb6da91b2a (current HEAD on github as of now)

**Comment by adamhowardprice** [comment]
Updated xctool, everything works. Thanks for the dummycheck :)
