### ISSUE TITLE
how to pass path to lib to field native_libs

### ISSUE THREAD

**Issue by symphony2512** [facebook/buck#502]
Dear all,
Please check for me this error

I have native library need to use in project and here I wrote in BUCK file in root project folder.
```
prebuilt_native_library (
name = 'native_library'
native_libs= 'lib_android/3rdpartyso/src/com/libs'
)
```
and here is the log error for that rule.

```
native_libs= 'lib_android/3rdpartyso/src/com/libs'
Warning raised by BUCK file parser:               ^
Warning raised by BUCK file parser: SyntaxError: invalid syntax
```

How can i assign value to field native_libs with full path like that.?
Thank you

**Comment by tgummerer** [comment]
Hi,

I think the issue is a missing comma after `name = 'native_library'`.

So what you should have is:
```
prebuilt_native_library (
  name = 'native_library',
  native_libs= 'lib_android/3rdpartyso/src/com/libs',
)
```

**Comment by symphony2512** [comment]
Hi ,
I edited like you comment
prebuilt_native_library (
  name = 'native_library',
  native_libs = 'lib_android/3rdpartyso/src/com/libs',
)
But It still show the same error
Warning raised by BUCK file parser:               ^
Warning raised by BUCK file parser: SyntaxError: invalid syntax

**Comment by tgummerer** [comment]
Strange, it seems to work for me.  Is there something else in your `BUCK` file that could be causing it?

**Comment by Piasy** [comment]
Could it be the tab character problem? The BUCK file is a python script.

**Comment by symphony2512** [comment]
Sorry I lacked of a comma after field 'name'
Thank you

**Comment by symphony2512** [comment]
Here is my new error for aar rules
I write in BUCK file for aar like this

android_prebuilt_aar(
  name = 'examplesdk_aar',
  aar = 'app/libs/examplesdk-v4_full.aar',
)

And here is error when build

Using buckd.
[-] PARSING BUCK FILES...FINISHED 0.9s
BUILD FAILED: //:examplesdk_aar: parameter 'aar': no such file or directory 'app/libs/examplesdk-v4_full.aar'

Could you help me about this error?
Thank you

**Comment by Piasy** [comment]
@symphony2512 How do your refer to `examplesdk_aar` ?

**Comment by symphony2512** [comment]
Here is library I refer to aar

android_library(
  name = 'main-lib',
  srcs = glob(['app/src/main/java/com/cloc/android/anpha/**/*.java']),
  deps = [
    ':all-jars',
    ':presto-aidls',
    ':examplesdk_aar',
    ':build-config',
    ':res',
  ],
)

**Comment by Piasy** [comment]
@symphony2512 Can you paste your full BUCK file?

**Comment by sdwilsh** [comment]
No response from @symphony2512, so I'm closing this.
