### ISSUE TITLE
After Buck upgrade verbose debug statements are issued on unit test failures

### ISSUE THREAD

**Issue by davido** [facebook/buck#505]
Since 1b03b4313b91b634bd604fc3487a05f877e59dee we are getting tons of debug output during the build on unit test failures: [1].

* [1] https://gerrit-ci.gerritforge.com/job/Gerrit-verifier/53/consoleText

**Comment by sdwilsh** [comment]
Did you bisect to that?  That change doesn't have anything that would make anything you are using more verbose.  What I am seeing there is that you have a test failure, and those have been verbose in Buck for as long as I can remember.

**Comment by davido** [comment]
Nope I havn't. It wasn't verbose for us in test failure case AFAICT. Only after recent upgrades it started to behave that way.

**Comment by sdwilsh** [comment]
Are you sure a change to gerrit didn't cause the logs to be more verbose?  I'm quite positive we haven't changing anything here with Buck.

**Comment by Coneko** [comment]
@bhamiltoncx is changing some stuff with regards with logging in tests, it's probably because of that.

Don't think 1b03b4313b91b634bd604fc3487a05f877e59dee is the right commit though.

**Comment by davido** [comment]
So, I was able to track it down:

good revision: ba9f239f69287a553ca93af76a27484d83693563
bad revision: 7e153d4a69044d059288d353fc1a442e07cbea58

Look like one of these commits broke it:

* cc05fdbedc0213ebe8ca38a69eeb0b0ea0b8e567
* a521e6e3e311b92a3904232e97cfcce62f97afb7

With offending commits, the verbose output is: http://paste.openstack.org/show/478799, without them, the correct non-verbose output is: http://paste.openstack.org/show/478798.

**Comment by bhamiltoncx** [comment]
We can add controls to adjust the logging for test failures. The idea is to
provide some idea of what went wrong when a test fails.
2015年11月13日(金) 6:08 David Ostrovsky <notifications@github.com>:

**Comment by bhamiltoncx** [comment]
In this case, these are java.util.logging logs written during the JUnit
test. I believe this is unrelated to the recent work I've been doing with
Robolectric tests that @Coneko mentioned.

You can control the log level in your java_test rule by setting:

  std_out_log_level = info

I think we probably should also offer a global .buckconfig setting or
adjust the default level higher (it's 'fine' currently) since you're not
the first person to mention the defaults are too spammy.

**Comment by davido** [comment]
Well, that's sensible and i believe that the default value is wrong. I would expect it to be at least `info`, if not even `warn`. I also think developer shouldn't configure anything in `.buckconfig` to get sane default behaviour, not to mention passing additional parameter(s) to hundreds of `java_rule()` invocations across the code base. So the only way to make it work on latest master and restore the old behaviour is to monkey patch `java_test` rule:

```
  _buck_java_test = java_test
  def java_test(*args, **kwargs):
    _do_not_spam_std_out(kwargs)
    _buck_java_test(*args, **kwargs)

  def _do_not_spam_std_out(kwargs):
  level = 'std_out_log_level'
  if level not in kwargs:
    kwargs[level] = 'INFO'

**Comment by bhamiltoncx** [comment]
Good feedback, thanks. I think it makes sense to change the default level
to info.
2015年11月13日(金) 9:06 David Ostrovsky <notifications@github.com>:

**Comment by bhamiltoncx** [comment]
Fix is coming shortly. Thanks for reporting, and sorry for the pain.

**Comment by davido** [comment]
Thanks for the quick fix.
