### ISSUE TITLE
android_resource missing documentation for manifest

### ISSUE THREAD

**Issue by AnthonyUccello** [facebook/buck#509]
```
When the 'res' is specified for android_resource() //:appcompat-v7-22.0.0-res, at least one of 'package' or 'manifest' must be specified
```

I got this error but the [android_resource](https://buckbuild.com/rule/android_resource.html) does not have 'manifest' listed as a parameter. I fixed it by using package but thought I'd drop a note about this message vs what the docs say.

**Comment by sdwilsh** [comment]
It should take an xml file or an `android_manifest` rule, much like `android_library`.

**Comment by AnthonyUccello** [comment]
Thats what I figured.
