### ISSUE TITLE
prebuilt_cxx_library not working with .so file

### ISSUE THREAD

**Issue by AnthonyUccello** [facebook/buck#515]
Here is the folder structure we have for a library project:

![screen shot 2015-11-17 at 12 49 39 pm](https://cloud.githubusercontent.com/assets/3809669/11220152/7fea10bc-8d2c-11e5-9170-bcea6244ee91.png)

I used this params setting:

``` python
PREBUILT_CXX_LIBARY_PARAMS = {'name' : 'cxx_libs', 'lib_dir' : 'xwalk_core_library/src/main/jniLibs/$(platform)', 'soname':'libxwalkcore.so} 
```

Is not working. I get a library specific crash for it. (Also note the 'soname' rule is undocumented).

**Comment by sdwilsh** [comment]
@andrewjcg, I think we talked about this very issue a week or two ago.  Also, @dreiss, your recent `soname` changes missed `prebuilt_cxx_library`.

**Comment by andrewjcg** [comment]
The `$(platform)` macro evaluates to one of `android-arm`, `android-armv7`, or `android-x86`, so that `.so` would need to be in a directory with the above names (not `armeabi-v7a`).

**Comment by sdwilsh** [comment]
Oh hey, we actually say that in the docs too: https://buckbuild.com/rule/prebuilt_cxx_library.html

I think my brain, when I was shown this problem in the first place, automatically mapped it to the "right" text.
