### ISSUE TITLE
Buck parses build files in buck-out

### ISSUE THREAD

**Issue by davido** [facebook/buck#527]
Trying to upgrade Buck to recent master: [1] reveals that `buck test` is inherently broken. It interferes with Eclipse output directory (written to `buck-out/eclipse`) with errors like:

```
$ buck test --include api
[-] PARSING BUCK FILES...FINISHED 1,0s
BUILD FAILED: //buck-out/eclipse/test/com/google/gerrit/acceptance/server/project:server-project-flaky: parameter 'srcs': no such file or directory 'buck-out/eclipse/test/com/google/gerrit/acceptance/server/project/ProjectWatchIT.java'
```

Note, that we are using Eclipse and telling it to use `buck-out/eclipse` as output drectory:

```
<?xml version="1.0" encoding="UTF-8"?>
<classpath>
    <classpathentry kind="src" output="buck-out/eclipse/test" path="gerrit-acceptance-framework/src/test/java"/>
    <classpathentry kind="src" output="buck-out/eclipse/test" path="gerrit-acceptance-tests/src/test/java"/>
```

So Eclipse is copying all files (except `*.java`) to this directory:

```
$ ls -1 buck-out/eclipse/test/com/google/gerrit/acceptance/server/project/
BUCK
CustomLabelIT.class
LabelTypeIT.class
ProjectWatchIT.class
```

My impression is that Buck is trying to parse Buck files from this output directory.
I've tracked down the problem to this commit:

35cb495b57f0b804253fbe25937a0000db131a9d is the first bad commit

Steps to reproduce:
1. clone most recent Gerrit master: `git clone https://gerrit.googlesource.com/gerrit`
2. replace Buck version with 35cb495b57f0b804253fbe25937a0000db131a9d in `.buckversion`
3. run `buck test --include api` -> all is fine
4. generate Eclipse project files with: tools/eclipse/project.py
5. start Eclipse, import gerrit project, refresh gerrit project in Eclipse to force building to `buck-out/eclipse`
6. run `buck test --include api` is failing with error mentioned above

[1] https://gerrit-review.googlesource.com/72682

**Comment by Coneko** [comment]
You shouldn't be writing or modifying files in `buck-out`, it will cause problems in general.

Can you change your eclipse project to output to a directory that isn't in `buck-out`?

It's pretty silly of Buck to be parsing build files in there though.

**Comment by davido** [comment]
We could probably introduce `eclipse-out`for that, yes.

**Comment by davido** [comment]
Moving Eclipse output from `buck-out` fixed it. However, I figured out, that Buck even interferes with itself. All you need to shoot yourself in the foot, is to have such innocent rule:

```
genrule():
  name = 'foo',
  srcs =  srcs = glob(['**'])
  [...]
```

Now you are screwed up, because BUCK copying all files to foo__srcs, including BUCK file itself, and later, when you are trying to run `buck test` (Note, that `buck build *` still works) it will complain that

```
//buck-out/.../foo: is not there or something
```

So now, all `glob(['**'])` must be extended with `srcs = glob(['**'], excludes = ['BUCK'])`, as in : [1]. May be this should be added to the documentation? Now it's claiming that:

```
Buck automatically excludes its own output, e.g. <code>buck-out</code>,
```

https://gerrit-review.googlesource.com/#/c/72684/1/polygerrit-ui/app/BUCK@41

**Comment by Coneko** [comment]
Good point.

@shs96c something else to keep in mind for how the new FileHashCache should work.

**Comment by LegNeato** [comment]
From what I can gather not really knowing the code, `DirectoryTraversal` can take ignore paths:

https://github.com/facebook/buck/blob/ad05aa385cfb6d648d61160329b9bf8ae60d3ae5/src/com/facebook/buck/io/DirectoryTraversal.java#L41

It looks like some places it is called don't ever put ignore paths in:

https://github.com/facebook/buck/search?utf8=%E2%9C%93&q=DirectoryTraversal%28

Might be a good place to poke around and send in a patch!
