### ISSUE TITLE
android_resource() not able to depend on android_prebuilt_aar()

### ISSUE THREAD

**Issue by spierce7** [facebook/buck#528]
I have an android_resource() that depends on resources inside of the appcompat, but it seems to get errors while compiling.

```python
android_resource(
  name = 'res',
  res = 'res',
  package = 'com.example.test',
  deps = [
    ':appcompat',
  ],
  visibility = [
    'PUBLIC',
  ],
)

android_prebuilt_aar(
  name = 'appcompat',
  aar = 'libs/appcompat-v7-23.0.1.aar',
)
```

and then I get this error while trying to depend on it:
```
The following resources were not found when processing ...: 
RDotTxtEntry{idType=int, type=color, name=material_blue_500, idValue=0x00000000}
RDotTxtEntry{idType=int, type=layout, name=design_navigation_item_separator, idValue=0x00000000}
RDotTxtEntry{idType=int, type=style, name=ThemeOverlay_AppCompat_Dark_ActionBar, idValue=0x00000000}
```

I originally posted for help here: https://groups.google.com/forum/#!topic/buck-build/yPp5PMv427E

**Comment by marcinkosiba** [comment]
I just un-zipped the .aar file and:
 - material_blue_500 is not present in the R.txt file,
 - design_navigation_item_separator is not in the R.txt file
I can't seem to find them in the .xml files either, so this seems to be a case of referencing non-existent symbols. For the material_blue_500 issue this might be helpful: http://stackoverflow.com/questions/26460389/android-5-0-intellij-gradle-cannot-resolve-symbol-colormaterial-blue-500

ThemeOverlay_AppCompat_Dark_ActionBar is present in the R.txt file and I can see .xml resources for it. I wonder if it's a case of the tooling being confused by previous errors, but it also may be a legit bug. Could you send me the snippet that's trying to reference that style?

**Comment by sdwilsh** [comment]
ping @spierce7

**Comment by nayrmi** [comment]
Closing because we haven't heard back from @spierce7. But we'll be here if you want to reactivate!
