### ISSUE TITLE
refer other package's resource

### ISSUE THREAD

**Issue by zlwen** [facebook/buck#529]
I have a resource file needs to refer other package's resource like 
\<item android:state_enabled="false" android:drawable="@com.example.ui:drawable/normal" /> and I build the referred resource using android_resource(), when I build the refer module, buck outputs
Invalid reference '@com.example.ui:drawable/normal' in 'ui/res/drawable/adding.xml'.
how it can be fixed?

**Comment by sdwilsh** [comment]
Sorry for the delay @zlwen!  Can you provide us with a more detailed example please?

**Comment by nayrmi** [comment]
Closing out since we haven't heard back from @zlwen - but we'll be here if you want to reactivate!
