### ISSUE TITLE
BuildConfig.EXOPACKAGE_FLAGS Is Not Being Generated.

### ISSUE THREAD

**Issue by AnthonyUccello** [facebook/buck#536]
Can 100% confirm my `AppShell` and `DefaultApplicationLike` are working and initializing properly.

However the `BuildConfig.EXOPACKAGE_FLAGS` is not being created in my BuildConfig file so I am forced to explicitly pass 1.

`super("co.pumpup.app.ExopackageApp", 1);`

Here are my binary build params:

``` python

ANDROID_BINARY_PARAMS = {
  'name' : 'pumpup',
  'linear_alloc_hard_limit' : 16 * 1024 * 1024,
  'use_linear_alloc_split_dex' : True,
  'manifest' : 'AndroidManifest.xml',
  'keystore' : ':debug_keystore',
  'use_split_dex' : True,
  'exopackage_modes' : ['secondary_dex'],
  'primary_dex_patterns' : [ 
    '^co/pumpup/app/AppShell^',
    '^co/pumpup/app/BuildConfig^',
    '^com/facebook/buck/android/support/exopackage/',
  ],
  'deps': [
    ':main-lib',
    ':application-lib',
  ],
}
```

**Comment by sdwilsh** [comment]
Do you have an `android_build_config` rule too?

**Comment by AnthonyUccello** [comment]
```python
ANDROID_BUILD_CONFIG_PARAMS = {'name' : 'build-config', 'package' : 'co.pumpup.app'}

# Builds the build config file for the main .apk.
android_build_config(**ANDROID_BUILD_CONFIG_PARAMS)

```

**Comment by sdwilsh** [comment]
I'm at a loss then.  @marcinkosiba, any ideas?

**Comment by dreiss** [comment]
Can you paste the full error message?  Does your AppShell depend on the android_build_config?

**Comment by AnthonyUccello** [comment]
Its not an error message. 

Its that even after many successful Buck builds and installs my BuildConfig file doesn't have the flag:

![screen shot 2015-12-01 at 5 36 01 pm](https://cloud.githubusercontent.com/assets/3809669/11516572/14e6c018-9852-11e5-83d6-be0e66cc3112.png)

**Comment by dreiss** [comment]
Oh, yeah.  I think this is a known issue.  The BuildConfig that IntelliJ sees will be different from what's actually used by Buck to compile.

**Comment by sdwilsh** [comment]
Oh, I wonder if we can fix that to work better (cc @alsutton in addition to @marcinkosiba who was already cc'd)

**Comment by AnthonyUccello** [comment]
>Oh, yeah. I think this is a known issue. The BuildConfig that IntelliJ sees will be different from what's actually used by Buck to compile.

I suspected this, and I tried hardcoding it and ignoring the error and running buck but it crashes still.

**Comment by dreiss** [comment]
Can you paste the error message?

**Comment by AnthonyUccello** [comment]
I stand corrected. I had the spelling wrong. Hardcoding DOES work.

**Comment by sdwilsh** [comment]
@AnthonyUccello, can this be closed then?

**Comment by AnthonyUccello** [comment]
Well the issue is, if its hard-coded, the Android Studio IDE will not compile, its a manual step between being able to compile with Buck and having an ever-present-compile error in Android-Studio. For example, the web team here doesn't need to use Buck, and when they compile they just use the IDE. Having this here adds a manual step.

**Comment by sdwilsh** [comment]
Hmm, I think the Buck plugin for IntelliJ might hide that for you (@alsutton would know).  No idea if that works with Android Studio, however.

**Comment by AnthonyUccello** [comment]
![screen shot 2015-12-08 at 2 17 21 pm](https://cloud.githubusercontent.com/assets/3809669/11665633/6ea85152-9db6-11e5-85d9-6364ec2ba941.png)

When I added Buck files it added this to Android Studio. It apparently does `run buck install` but it doesnt work. Is this the plugin you are referring to (if so can confirm it doesn't work, but perhaps there is something I need to configure somewhere?)

**Comment by sdwilsh** [comment]
We, unfortunately, don't have any docs on how to use the plugin, and I'm not sure myself as I haven't worked on it.

**Comment by sdwilsh** [comment]
@alsutton might be able to point you at docs
