### ISSUE TITLE
main project can't find the res file in library project

### ISSUE THREAD

**Issue by yoohoHusky** [facebook/buck#537]
I create a project by Android studio
    It has two model(main modle, library model)
    But there is some problems in the MainActivity.java in main modle:

terminal show,

```
/Users/yooho/Downloads/work_buck/BuckTest1/abcapp/src/main/java/com/hyxf/bucker/MainActivity.java:17: error: can't find
        setContentView(R.layout.activity_lib);
```
# 

the activity_lib.xml is in my library model (not exits in main model), but referenced in main model

It's ok by gradle build, but error by buck build

my BUCK file in main model is:

```
android_library(
  name = 'app-src',
  srcs = glob(['src/main/java/**/*.java']),
  deps = [
    '//bucklib:lib-src',
    ':build-config',
    ':app-res',
  ],
)

android_resource(
  name = 'app-res',
  res = 'src/main/res',
  package = 'com.hyxf.bucker',
  deps = [
    '//bucklib:lib-res',
  ],
)

android_build_config(
  name = 'build-config',
  package = 'com.hyxf.bucker',
)

android_binary(
  name = 'abcapp',
  manifest = 'src/main/AndroidManifest.xml',
  keystore = '//keystore:app-keystore',
  deps = [
    ':app-src',
  ],
)
```

the BUCK file in my library model is:

```
#prebuilt_jar(
#   name = 'lib-jar',
#   binary_jar = '',
#)

android_resource(
    name = 'lib-res',
    res = 'src/main/res/',
    package = 'com.ss.android.bucklib',
    visibility = [
        'PUBLIC'
    ],
)

android_library(
    name = 'lib-src',
    srcs = glob(['src/main/java/**/*.java']),
    deps = [
        '//third:support-v7',
        '//third:support-v4',
        ':lib-res',
        ':lib-config',
    ],
    visibility = ['PUBLIC'],
)

android_build_config(
    name = 'lib-config',
    package = 'com.ss.android.bucklib',
)
```

It's the problem for me, please help me solve it.

**Comment by yoohoHusky** [comment]
my project is at, https://github.com/yoohoHusky/test_buck

it's very nice if someone can show me a successful buck project which has library model

**Comment by sdwilsh** [comment]
`buck build app` works for me in your sample repository.  What are you actually running to hit that error?

**Comment by yoohoHusky** [comment]
Thanks for you reply very much. Today, buck build app works also works for me.
But it's true that it don't work, and show me the error info in terminal.
Maybe, the environment is different from yesterday which I don't find.
It's very nice that it can work now than yesterday.
Today is the lucky day for me.
Thanks a lot again.   :-)

**Comment by yoohoHusky** [comment]
I'm very sorry that I didn't describe my problem clear.
There are two project In my repository, the app is the sample demo, it can work successfully.

The 'abcapp' is the problem.  You need run 'buck build abcapp:abcapp" can see the problem.
Now I modify the repository, delete the void modle, and modify the .buckconfig

now run 'buck build app' or 'buck build abcapp:abcapp" both show the problem

**Comment by yoohoHusky** [comment]
@sdwilsh I modify repository, now can show the problem.
Please help me. Thanks a lot.

**Comment by sdwilsh** [comment]
Hmm, this is odd.  It's ending up in the `buck-out/gen/bucklib/__lib-res_text_symbols__/R.txt` file Buck generates:
```
int dimen activity_horizontal_margin 0x7f020001
int dimen activity_vertical_margin 0x7f020002
int id action_settings 0x7f050001
int layout activity_lib 0x7f040002
int layout activity_main 0x7f040001
int menu menu_main 0x7f030001
int string action_settings 0x7f010003
int string app_name 0x7f010001
int string hello_world 0x7f010002
int string lib_src 0x7f010004
```

You are properly depping on the `android_resource` so I'm confused why it's not available.  Maybe @andrewjcg or @marcinkosiba have an idea.

**Comment by yoohoHusky** [comment]
I thought many ways to try resolving the problem in the last week, but the result is futile.
Could you help me to check the problem?
I'm expecting your reply, in all sincerity.

Thanks, Thanks a lot, again.  :-)
@andrewjcg and @marcinkosiba

**Comment by v-jizhang** [comment]
Sorry we haven't update this issue for more than 3 years. At this point, we are closing this because it is quite out of date and it is not clear if the issue still exists. Please create a new one if you still see the problem. Thank you.
