### ISSUE TITLE
Install to Physical iOS Device

### ISSUE THREAD

**Issue by crylico** [facebook/buck#540]
After quickstarting an iOS project, downloading iOSConsole binary, and setting it up as explained by the docs, `buck install -d //ios:BuckDemoApp` installs to the simulator.  It's very likely I've missed something, but this seemed like the best place to ask what's going on here.

Thanks!

**Comment by ryu2** [comment]
The default config is for simulator builds. Try to specify a device flavor:  buck install -d //ios:BuckDemoApp#iphoneos-arm64

Sent from my iPhone

On Dec 2, 2015, at 9:06 AM, Kyle Levin <notifications@github.com<mailto:notifications@github.com>> wrote:


After quickstarting an iOS project, downloading iOSConsole binary, and setting it up as explained by the docs, buck install -d //ios:BuckDemoApp installs to the simulator. It's very likely I've missed something, but this seemed like the best place to ask what's going on here.

Thanks!

**Comment by crylico** [comment]
Of course - I had a feeling it had to do with platform, but I wasn't sure how to specify that :) thank you!

However, when running `buck install ios -r` (I changed the default platform and made an alias for my target), It installed successfully, then hangs for a while on the launch image, then displays an error.  I've attached a screenshot of the whole session (note that the installation is fine, and after the error occurs, I can open the app without debugger support).

![screen shot 2015-12-02 at 1 05 34 pm](https://cloud.githubusercontent.com/assets/1025667/11539543/a38f37de-98f5-11e5-8b57-6ba187efc89d.png)

**Comment by ryu2** [comment]
Hmm... I can't repro locally (tried the latest version of iOSConsole and buck quickstart).  Might sound silly, but does it work after you restart your device?

**Comment by crylico** [comment]
Nah, not silly! I do a lot of BLE dev, and CoreBluetooth caches so much about profile data it's ridiculous.  Unfortunately, after a reboot (unlock + no apps running), another clean project creation, latest version of iOSConsole, same issue.  Not sure if it's worth mentioning that the simulator works as expected.

**Comment by ryu2** [comment]
Yeah, the simulator uses a different code path than device.

What you could try doing is try adding a `Thread.sleep()` right before the `runBundleOnDevice` call here: https://github.com/facebook/buck/blob/master/src/com/facebook/buck/cli/InstallCommand.java#L478

See if that helps, and experiment with different values.  If it works for you, feel free to send in a PR.

**Comment by crylico** [comment]
Hmm, interesting issues:

First, with `buck version v2015.11.23.01`, `buck install -r ios`, the `-r` flag seems to be completely ignored after a successful installation (no timeout, no error), which I've not experienced before now.

Second, I decided to `brew uninstall buck; brew install --HEAD buck` before adding the `Thread.sleep()` call you suggested.  Running `buck install ios` with the current HEAD gives me the following:

<img width="893" alt="screen shot 2015-12-04 at 10 49 30 am" src="https://cloud.githubusercontent.com/assets/1025667/11593873/bcd7da72-9a74-11e5-834c-80e67284eb67.png">

**Comment by ryu2** [comment]
The second issue was just fixed: db401ccc62967793c75703469a154553c1b726c5

**Comment by ryu2** [comment]
Hi @crylico -- were you able to resolve your issues?

**Comment by crylico** [comment]
Sorry, just got a chance to get around to this! I tried values ranging from `100ms` to `2500ms` with no success

**Comment by crylico** [comment]
Currently looking through the runBundleOfDevice source

**Comment by crylico** [comment]
It seems to be a problem only with iOSConsole. Calling `iOSConsole -d <uuid> --run <bundle-id>` hangs in the same fashion.  It's even consistent with apps that I didn't write.  However, if the app is running in the background, things proceed as expected

**Comment by ryu2** [comment]
Hmm... since I can't repro this internally, I'd try to delve into `iOSConsole`, in particular `iOSConsole/iOSConsole/run.c` and file a issue against that project if you find out something (feel free to cc: me).

Going to close this for now.
