### ISSUE TITLE
buck should cache previously-built versions of itself

### ISSUE THREAD

**Issue by dborowitz** [facebook/buck#543]
I have a single buck installation but I regularly switch between projects and branches that have different .buckversions. Having to wait 10s+ for buck to rebuild itself gets old pretty quickly. It would be nice if the wrapper script could cache the built version of buck at various old versions so we could avoid the switching overhead.

**Comment by davido** [comment]
I think @dpursehouse already added this feature request.

**Comment by sdwilsh** [comment]
This might be as easy as setting `cache.mode = dir` in the `.buckconfig` file of the repo.  If that helps, do you mind submitting a PR?

**Comment by Coneko** [comment]
I don't think that will work since the buck launcher script will build with ant, not with buck.

**Comment by dpursehouse** [comment]
> I think @dpursehouse already added this feature request.

Yes. See #102.
