### ISSUE TITLE
question - How can I generate an iOS embedded framework target

### ISSUE THREAD

**Issue by avnerbarr** [facebook/buck#547]
Couldn't find any documentation on generating a "not-app" target.

Is this possible?
Also how do I compile swift sources ?

Thanks

**Comment by Coneko** [comment]
Natively Buck doesn't support swift yet, but if you use the Xcode project generation can add swift sources to apple_library and apple_binary, the generated Xcode project will do the right thing.

Creating a framework target is the same as an app target, but with a different extension, and the binary should be specified as `#shared`.

```python
apple_bundle(
  name = 'MyFramework',
  binary = ':MyLibrary#shared',
)
```

See docs at https://buckbuild.com/rule/apple_bundle.html.

There's a couple of issues with them though.

Why do you want to build a framework? Those issues might or might not affect you depending on what you're trying to do.

**Comment by nayrmi** [comment]
Closing because we haven't heard back from @avnerbarr. However, we'll be here if you want to reactivate!
