### ISSUE TITLE
If Buck is installed via Homebrew, .buckversion has no effect

### ISSUE THREAD

**Issue by ndahlquist** [facebook/buck#550]
After installing Buck with Homebrew, it does not respect the `.buckversion` file:

```
nic@nic ~/w/s/snapchat> buck --version
Shutting down nailgun server...
Using watchman.
buck version v2015.11.23.01
```

(However, if I build Buck from source, it does respect .buckversion:)

```
nic@nic ~/w/s/snapchat> ../../buck/bin/buck --version
Buck is at a0be103cb71aabc0cc505229250391e7ec900e8c, but should be 74fdf940a3a8fbca5ca63d9a4e51aab8911a9cf9.
Buck is updating itself. To disable this, add a '.nobuckcheck'
file to your project root. In general, you should only disable
this if you are developing Buck.
Buck does not appear to have been built -- building Buck!
^C⏎      
```

 Thank you for any help; Buck is a life saver :)

**Comment by v-jizhang** [comment]
Sorry we never got back to this! At this point, we are closing this because it is quite out of date and it is not clear if the issue still exists. Please create a new one if you still see the problem. Thank you.
