### ISSUE TITLE
Buck finds non-ascii character in python executable?

### ISSUE THREAD

**Issue by spierce7** [facebook/buck#551]
Every time I run a genrule `buck build //jar:objc_rxjava`, I'm getting the following error:

```
buck clean
Shutting down nailgun server...
Using watchman.
buck build //jar:objc_rxjava
No Android platform target specified. Using default: Google Inc.:Google APIs:21
[-] PROCESSING BUCK FILES...FINISHED 0.0s [100%]
[+] BUILDING...0.7s [85%] (3/4 JOBS, 3 UPDATED, 75.0% CACHE MISS)
 |=> IDLE
 |=> IDLE
 |=> IDLE
 |=> IDLE
 |=> IDLE
 |=> //jar:objc_rxjava...  0.0s (running genrule[0.0s])
 |=> IDLE
 |=> IDLE
 |=> IDLE
 |=> IDLE
  File "/usr/local/bin/python2", line 1
SyntaxError: Non-ASCII character '\xcf' in file /usr/local/bin/python2 on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

I've tried pointing to multiple python executables, all ending with the same issue. I've even downloaded the homebrew python and pointed to it, with the same error message.

Just in case I put `# -*- coding: utf-8 -*-` at the top of my python files which did nothing.

I've even simplified the python script to a simple print statement, removing all the python libraries, and it's still reproducible.

Here is my BUCK file:
```python
RXJAVA_SOURCES_JAR_PATH = './rxjava-1.1.0-sources.jar'

genrule(
  name = 'objc_rxjava',
  srcs = [
    RXJAVA_SOURCES_JAR_PATH,
  ],
  cmd = 'python $(exe :Jar2ObjC) ./rxjava-1.1.0-sources.jar $OUT',
  out = 'out',
)

python_binary(
  name = 'Jar2ObjC',
  main = 'Jar2ObjC.py',
  deps = [
    ':ExtractJar2Dir',
    ':Java2ObjC',
  ],
)

python_library(
  name = 'ExtractJar2Dir',
  srcs = ['ExtractJar2Dir.py'],
)

python_library(
  name = 'Java2ObjC',
  srcs = ['Java2ObjC.py'],
)
```

This is my first time using python, so I'm no wiz, but I don't think I'm doing anything odd. Please advise.

**Comment by spierce7** [comment]
I seem to have figured out the issue.

**Comment by sdwilsh** [comment]
Ah, yeah.  When using the `$(exe ) macro, Buck automatically adds the python invocation line for you, so you ended up having it twice.  That code is here: https://github.com/facebook/buck/blob/master/src/com/facebook/buck/python/PythonPackagedBinary.java#L87

**Comment by spierce7** [comment]
@sdwilsh Thanks for the response. Does that mean the example here is out of date? https://buckbuild.com/rule/genrule.html

**Comment by sdwilsh** [comment]
Oh, whoops.  Yeah, when I change this behavior a while ago I didn't even realize there was an example that used it!  Can you either submit a PR to update the docs or file an issue please? :)
