### ISSUE TITLE
PythonBinaryIntegrationTest breaks locally for me

### ISSUE THREAD

**Issue by grumpyjames** [facebook/buck#555]
In particular, nativeLibsEnvVarIsPreserved (in both STANDALONE and INPLACE modes) fails with:

java.lang.AssertionError: 
Expected: "None"
     but: was "/mnt/scratch/byattj/idea-IU-143.381.42/bin::/mnt/scratch/byattj/buck-all//opt/percona/lib/mysql:/mnt/scratch/byattj/buck-all//opt/percona/lib/mysql"

This could be something wrong in my environment - that looks like a subset of my PATH in the failure.

The change that causes the change in behaviour (according to git bisect) is:

https://github.com/facebook/buck/commit/a4fa44ceeff25eb62a0403539b9d7d5f43c2c790 .

Please ask if more debug information if required: I'm not _that_ familiar with the area of the change or I'd go digging with a little more enthusiasm!

**Comment by sdwilsh** [comment]
@andrewjcg is probably the best person to help with that.

**Comment by andrewjcg** [comment]
What system is this on?  We have known issues on macos X where El Capitan is disallowing use of DYLD_LIBRARY_PATH (and I'll look into muting the tests in this case).

**Comment by grumpyjames** [comment]
This is on Fedora 20.

**Comment by andrewjcg** [comment]
Ah yeah, it looks like this test fails when `LD_LIBRARY_PATH` is non-empty.  Will look into a fix.

**Comment by davido** [comment]
Ah, I missed this issue before opening a new one: [1]. The same test is failing for me as well on Linux OpenSuSE.

* [1] https://github.com/facebook/buck/issues/565
