### ISSUE TITLE
buck publish: allow to publish to local repositories

### ISSUE THREAD

**Issue by davido** [facebook/buck#559]
Currently only remote and central repositories can be specified with `publish` command. So the Publisher needs to be taught how to handle file: URIs:

```
  $ buck publish --remote-repo file:///home/johndoe/.m2/repository //:foo
```

or if it is safe to assume that the local repository is always located in the same directory: `$HOME/.m2/repository`, then it could be sufficient to just say this:

```
$ buck publish --local //:foo
```

**Comment by victorssilva** [comment]
Has this been implemented?

**Comment by davido** [comment]
Nope.

**Comment by davido** [comment]
There is a workaround, though to use [Bucklets](https://github.com/davido/bucklets).

**Comment by victorssilva** [comment]
Any pointers on how to use it? There isn't a readme there.

**Comment by davido** [comment]
Check https://github.com/GerritCodeReview/gitiles where it's used (clone recursively).

Then check this rule in main BUCK file:

```
maven_package(
  repository = 'gerrit-maven-repository',
  url = 'gs://gerrit-maven',
  version = GITILES_VERSION,
  group = 'com.google.gitiles',
  jar = {
    'blame-cache': '//blame-cache:lib',
    'gitiles-servlet': '//gitiles-servlet:servlet',
  },
  src = {
    'blame-cache': '//blame-cache:src',
    'gitiles-servlet': '//gitiles-servlet:src',
  },
  doc = {
    'blame-cache': '//blame-cache:javadoc',
    'gitiles-servlet': '//gitiles-servlet:javadoc',
  },
)
```

This is defined in this [buckets](https://github.com/davido/bucklets/blob/master/maven_package.bucklet).

**Comment by victorssilva** [comment]
I'll check it out. Thanks!

**Comment by davido** [comment]
Check `buck build :mvn_install`:

```
$  buck targets --json mvn_install 
[+] PARSING BUCK FILES...0.1s
[
{
  "bash" : null,
  "buck.base_path" : "",
  "buck.direct_dependencies" : [ "//blame-cache:javadoc", "//blame-cache:lib", "//blame-cache:src", "//bucklets/tools:mvn", "//gitiles-servlet:javadoc", "//gitiles-servlet:servlet", "//gitiles-servlet:src" ],
  "buck.type" : "genrule",
  "cmd" : "$(exe //bucklets/tools:mvn) -g com.google.gitiles -v 0.1-10 -o $OUT -s gitiles-servlet:jar:$(location //gitiles-servlet:servlet) -s blame-cache:jar:$(location //blame-cache:lib) -s gitiles-servlet:java-source:$(location //gitiles-servlet:src) -s blame-cache:java-source:$(location //blame-cache:src) -s gitiles-servlet:javadoc:$(location //gitiles-servlet:javadoc) -s blame-cache:javadoc:$(location //blame-cache:javadoc) -a install",
  "cmdExe" : null,
  "executable" : null,
  "fully_qualified_name" : "//:install",
  "licenses" : [ ],
  "name" : "install",
  "out" : "install.info",
  "srcs" : [ ],
  "tests" : [ ],
  "visibility" : [ ]
}
]
```

But note, that this is wrong approach, because the rule will onl be executed, when there were changes, but deployment shoud be triggered always. So the correct approach is to generate the shell  deployment script from the build. This was recently fixed in [Gerrit Code Review](https://github.com/GerritCodeReview/gerrit):

```
  $ ./tools/maven/api.sh install buck
```

This would generate this shell script with this rule:

```
  $ buck build :gen_api_install
```

in this location:

```
  $ buck targets --show_output //tools/maven:gen_api_install
  //tools/maven:gen_api_install buck-out/gen/tools/maven/gen_api_install/api_install.sh
```
[With this content](http://paste.openstack.org/show/587829/) and execute it and execute it.
