### ISSUE TITLE
How to use the outputs of genrule()?

### ISSUE THREAD

**Issue by spierce7** [facebook/buck#560]
I'm using genrule to compile a java library to a directory structure of .m and .h files. I'm trying to find some way to use that with the buck build. 

For instance I could use apple_library(), and I could list the genrule name as a dependency, but seeing as how genrule ends up placing the output in the buck-out folder, it's difficult to access it. How should I be accessing these files?

The apple_library rule requires headers and srcs to be separate. I could create a script to separate out the .h and .m files into separate directories, but how would I link those files to the apple_library srcs and headers array?

Or perhaps apple_library isn't the best tool to use?

**Comment by spierce7** [comment]
In a related question, if I had a .a library compiled from objc files with objc headers, what would be the best way to compile that into the application? The documentation specify the requirement of C / C++ header files only it seems for the `prebuilt_cxx_library()`

**Comment by Coneko** [comment]
It's a big complicated because genrule can output directories, but very few target types that read files can also read directories containing those files.

What we do is end up creating a genrule to generate the files in a directory, then other genrules to export every single file from that directory. You can use some python to make that easy, for example:

```python
# this would be ['src/Foo.java', 'src/Bar.java']
JAVA_SRCS = glob(['src/*.java'])
# this would be ['Foo.m', 'Bar.m'], you can adjust it to also include a header for each source file
# or add a prefix or whatever you want
OBJC_FILENAMES = [get_objc_filename(x) for x in JAVA_SRCS]
  
genrule(
  name = 'generate-objc-sources',
  srcs = JAVA_SRCS,
  cmd = '$(exe :generator) -o $OUT $SRCS',
  out = 'output',
)

# this is will generate a genrule for each source file that will copy the file out of the directory, like:
# genrule(
#   name = 'Foo.m',
#   cmd = 'cp buck-out/gen/.../generate-objc-sources/output/Foo.m buck-out/gen/.../Foo.m/Foo.m'
#   out = 'Foo.m',
# )
for objc_filename in OBJC_FILENAMES:
  genrule(
    name = objc_filename,
    cmd = 'cp $(location generate-objc-sources)/{}'.format(objc_filename) $OUT,
    out = objc_filename,
  )

# this will create a library that uses the sources exported by the above genrules, like:
# apple_library(
#   name = 'library',
#   srcs = [':Foo.m', ':Bar.m'],
#   ...
# )
apple_library(
  name = 'library',
  srcs = [':' + x for x in OBJC_FILENAMES],
  ...
)
```

If you need help debugging this stuff you can use `buck audit rules path/to/BUCK`, it will print out how Buck is interpreting the functions in the file.

**Comment by spierce7** [comment]
@Coneko Thanks for your response. That's very helpful. I'll give that a shot.

Is there an answer to my second comment? If I had a .a library compiled from objc files with objc headers, what would be the best way to compile that into the application? The documentation specify the requirement of C / C++ header files only it seems for the `prebuilt_cxx_library()`.

**Comment by sdwilsh** [comment]
If you are feeling ambitious, #518 would solve this for you as well if you wanted to submit a PR.

**Comment by Coneko** [comment]
Yeah you need to use `prebuilt_cxx_library` to use a prebuilt static library in your application. We build everything from source so that workflow isn't well tested, and it's not supported in project generation.

**Comment by spierce7** [comment]
So this approach assumes that you are able to predict every file in the output. It seems like a common case that the output file names aren't known at rule generation time, and instead the ability to to deal with the output as a folder is needed. Is there any way to handle this case?

**Comment by spierce7** [comment]
I've migrated to the approach suggested above and I'm having a few issues:
This was my header declaration for my `apple_library()`:

```python
headers = subdir_glob([('source', '**/*.h')]),
```

Now I'm using:
```python
headers = [':' + x for x in OBJC_HEADERS],
```

I'm having difficulty matching the `subdir_glob()` function, and instead I believe what I'm doing would be the same as me using `glob()` function instead of the `subdir_glob()` function. I haven't been able to come up with any creative way around it either.

Any suggestions?

**Comment by Coneko** [comment]
You can do the same thing as `subdir_glob` by specifying a dictionary instead of a list for headers: the key will be the path with which you can include the header, the value is the reference to the header itself.

As long as the keys are different you should be fine. The keys default to the name if you use a list, so having multiple headers with the same name won't work, although multiple headers with the same name in the same target might not work anyway, I'm not sure right now.

As for the code generation not knowing the number and names of the files being generated, there's no way to solve that in Buck. All the actions have to be determined before they are executed. It's a pretty hard limitation to deal with and we're not happy with it either, but that's how it is right now.

**Comment by spierce7** [comment]
Thanks for your response @Coneko . I appreciate it.

>You can do the same thing as subdir_glob by specifying a dictionary instead of a list for headers: the key will be the path with which you can include the header, the value is the reference to the header itself.

I had thought of trying to generate the header dictionary myself, but I believe the header dictionary has access to the actual file paths for the value, doesn't it? The dictionary value is why I chose not to do it in the first place, and it's the part of your suggestion that I don't understand also.

What do you mean by the reference to the header itself for the value? Could the value be a String reference to the build rule, like this:
```
OBJC_HEADER_DICT = { header : (':' + header) for header in OBJC_HEADERS }
```

>As for the code generation not knowing the number and names of the files being generated, there's no way to solve that in Buck. All the actions have to be determined before they are executed. It's a pretty hard limitation to deal with and we're not happy with it either, but that's how it is right now.

Are there any plans / ideas to overcome this in the future, or is this not even on the radar?

**Comment by Coneko** [comment]
Yeah it can be a reference to a target. It should work as you suggested.

The limitation is part of the design. We know how to change the design to support that by making it more like shake, but we haven't yet decided whether we want to.

If you need to support very complex code generation you could look into implementing a target type directly in Buck.

There are some docs on how to do it on the website, and I'm posting some helpful notes on Facebook.

Look at the react native target types after you read the docs to get started.

**Comment by spierce7** [comment]
>The limitation is part of the design. We know how to change the design to support that by making it more like shake, but we haven't yet decided whether we want to.

Is there any discussion around this, or way to track it so that I could follow it and see what's decided? I'd like to better understand the pros / cons.

>Yeah it can be a reference to a target. It should work as you suggested.

When I use the approach I listed above, it's trying to read the files in the wrong location. I get several errors when I try to use all these build targets in an `apple_library()`. I get the same error on each file. Here is an example:

```
error: error reading 'buck-out/gen/rxjava/rx/Observable.m/rx/Observable.m'
1 error generated.
```
It's trying to read `buck-out/gen/rxjava/rx/Observable.m/rx/Observable.m` as the file, but that is actually the folder containing the file, which is what's causing the error. `buck-out/gen/rxjava/rx/Observable.m/rx/Observable.m/Observable.m` is actually the file that it needs to be reading.

For reference, here is my BUCK file. What am I still missing?
```python
RXJAVA_SRC_DIR = 'src-1.1.0'
RXJAVA_JAVA_SRC = glob([RXJAVA_SRC_DIR + '/main/java/**/*.java'])

OBJC_FILES = []
OBJC_HEADERS = []
for javaPath in subdir_glob([(RXJAVA_SRC_DIR + '/main/java', '**/*.java')]):
  javaPathNoSuffix = javaPath[:-4]
  OBJC_FILES.append(javaPathNoSuffix + 'm')
  OBJC_HEADERS.append(javaPathNoSuffix + 'h')

java_library(
  name = 'java',
  srcs = RXJAVA_JAVA_SRC,
  tests = [
    ':java-tests'
  ],
  visibility = [
    'PUBLIC'
  ],
)

java_test(
  name = 'java-tests',
  srcs = glob(['src-1.1.0/test/java/**/*.java']),
)

genrule(
  name = 'objc-generate',
  srcs = [
    RXJAVA_SRC_DIR,
  ],
  cmd = '$(exe //scripts:Java2ObjC) ' + RXJAVA_SRC_DIR + '/main/java $OUT',
  out = 'src-objc',
)

def objcGenRule(objc_filename):
  genrule(
    name = objc_filename,
    cmd = 'mkdir -p $OUT && cp $(location :objc-generate)/' + objc_filename + ' $OUT',
    out = objc_filename,
  )

for src in OBJC_FILES: 
  objcGenRule(src)
for header in OBJC_HEADERS:
  objcGenRule(header)

OBJC_HEADER_DICT = { header : (':' + header) for header in OBJC_HEADERS }

# A sample of what the j2objcc command runs when running for osx
# xcrun clang -fobjc-arc -I /j2objc/j2objc-0.9.8.2.1/include -Werror -Wno-parentheses -fno-strict-overflow -std=c11 -ljre_emul -l icucore -l z -l j2objc_main -l c++ -framework Foundation -framework Security -framework ExceptionHandling -L /j2objc/j2objc-0.9.8.2.1/lib/macosx
apple_library(
  name = 'objc',
  deps = [
    ':objc-generate',
    '//j2objc:include',
    '//j2objc:jre_emul',
  ],
  preprocessor_flags = [
    '-fobjc-arc', 
    '-fno-strict-overflow',
    '-std=c11',
    '-Werror', 
    '-Wno-parentheses',
    '-c',
  ],
  headers = OBJC_HEADER_DICT  ,
  srcs = [':' + x for x in OBJC_FILES],
  exported_linker_flags = [
    '-lc++',
    '-licucore',
    '-lz',
  ],
  frameworks = [
    '$SDKROOT/System/Library/Frameworks/Foundation.framework',
    '$SDKROOT/System/Library/Frameworks/Security.framework',
  ],
  visibility = [
    'PUBLIC',
  ],
)

```

**Comment by spierce7** [comment]
@Coneko I've tried several other approaches based around the first approach that you gave, and I can't seem to get any of them to work.

**Comment by sdwilsh** [comment]
@Coneko started a month of PTO, so I'm not sure he'll be around to respond.  I'm going to jump in and try to answer some of your questions.

> Is there any discussion around this, or way to track it so that I could follow it and see what's decided? I'd like to better understand the pros / cons.

I think these have mostly been in-person discussions.  I'm not aware of anything internally or externally available, unfortunately (and I don't know the details myself, but @shs96c might).

> It's trying to read `buck-out/gen/rxjava/rx/Observable.m/rx/Observable.m` as the file, but that is actually the folder containing the file, which is what's causing the error. `buck-out/gen/rxjava/rx/Observable.m/rx/Observable.m/Observable.m` is actually the file that it needs to be reading.

Because you call `mkdir -p $OUT`, your output will be a variable, not a file.  I think this should do what you want:

```
def objcGenRule(objc_filename):
  genrule(
    name = objc_filename,
    cmd = 'cp $(location :objc-generate)/' + objc_filename + ' $OUT',
    out = objc_filename,
  )
```

You might also try using `ln -s` which will probably take up less space any might even be faster.

**Comment by spierce7** [comment]
@sdwilsh Thanks for stepping in. I appreciate it.

So I believe that's what @Coneko originally recommended. When I run that I get the `No such file or directory` error from the cp command:

```
cp: /Users/myuser/Documents/workspace/j2objc-test/buck-out/gen/rxjava/rx/functions/Func6.h/rx/functions/Func6.h: No such file or directory
cp: /Users/myuser/Documents/workspace/j2objc-test/buck-out/gen/rxjava/rx/internal/operators/OperatorFilter.m/rx/internal/operators/OperatorFilter.m: No such file or directory
cp: /Users/myuser/Documents/workspace/j2objc-test/buck-out/gen/rxjava/rx/internal/util/UtilityFunctions.m/rx/internal/util/UtilityFunctions.m: No such file or directory
cp: /Users/myuser/Documents/workspace/j2objc-test/buck-out/gen/rxjava/rx/subscriptions/RefCountSubscription.h/rx/subscriptions/RefCountSubscription.h: No such file or directory
cp: /Users/myuser/Documents/workspace/j2objc-test/buck-out/gen/rxjava/rx/internal/operators/OperatorSwitch.h/rx/internal/operators/OperatorSwitch.h: No such file or directory
cp: /Users/myuser/Documents/workspace/j2objc-test/buck-out/gen/rxjava/rx/schedulers/TimeInterval.h/rx/schedulers/TimeInterval.h: No such file or directory
cp: /Users/myuser/Documents/workspace/j2objc-test/buck-out/gen/rxjava/rx/internal/util/atomic/LinkedQueueNode.m/rx/internal/util/atomic/LinkedQueueNode.m: No such file or directory
cp: /Users/myuser/Documents/workspace/j2objc-test/buck-out/gen/rxjava/rx/internal/operators/OperatorSampleWithObservable.h/rx/internal/operators/OperatorSampleWithObservable.h: No such file or directory
cp: /Users/myuser/Documents/workspace/j2objc-test/buck-out/gen/rxjava/rx/schedulers/CachedThreadScheduler.m/rx/schedulers/CachedThreadScheduler.m: No such file or directory
```

To give some more explanation to what's happening. The value of `objc_filename` is a path. For the first error, the value would be `rx/functions/Func6.h`. Is the fact that it's a path what's causing this error?
It's because of these errors that I added the `mkdir -p $OUT`.

Any thoughts on where I go from here?

**Comment by Coneko** [comment]
As @sdwilsh said I won't be available for a while sorry.

Try adding `mkdir $(dirname $OUT)` instead, so it creates a directory one level up: by adding `mkdir -p $OUT` you end up creating a directory there and then copying the file inside the directory, that's why you end up with `Foo.m/Foo.m`.

**Comment by spierce7** [comment]
@Coneko When I try that I get the following:

```
BUILD FAILED: Couldn't get dependency '//rxjava:rx/Notification.h' of target '//rxjava:objc':
//rxjava:rx/Notification.h: no such macro "dirname"
```

**Comment by Coneko** [comment]
Try
```
mkdir `dirname $OUT`
```
instead.

**Comment by spierce7** [comment]
That didn't work, I got the `No such file or directory` error again:

```
mkdir: /Users/myuser/Documents/workspace/j2objc-test/buck-out/gen/rxjava/rx/internal/util/unsafe/BaseLinkedQueuePad0.h/rx/internal/util: No such file or directory
...
```

I see what you are trying to do though so I added the `-p` to the mkdir again, and it worked! Thank you so much for your help figuring this out @Coneko and @sdwilsh .

For anyone who finds this and has the same issue, the script above is exactly the same, except for `objcGenRule()` function, which has been changed to:
```python
def objcGenRule(objcFilePath):
  genrule(
    name = objcFilePath,
    cmd = 'mkdir -p `dirname $OUT` && cp $(location :objc-generate)/' + objcFilePath + ' $OUT',
    out = objcFilePath,
  )
```

**Comment by sdwilsh** [comment]
I think we can close this now :)

**Comment by njlr** [comment]
For people stumbling on this, you can now set `executable = True` on a `genrule`.
