### ISSUE TITLE
Architecture of Buck series

### ISSUE THREAD

**Issue by Coneko** [facebook/buck#570]
I'm posting a series of notes on the high level architecture of Buck.

I'm linking them here so I can cc people who might be interested in them.

https://www.facebook.com/notes/uri-baghin/architecture-of-buck-0-introduction/1660888620856197

https://www.facebook.com/notes/uri-baghin/architecture-of-buck-1-graphs/1660525917559134

**Comment by Coneko** [comment]
cc @grumpyjames @davido @mikekap @mread @tgummerer

**Comment by tapthaker** [comment]
The posts don't seem to be available anymore. Can someone repost them?
