### ISSUE TITLE
Linking platform libraries at build time?

### ISSUE THREAD

**Issue by spierce7** [facebook/buck#573]
I'm fairly new to ios / C builds, so I apologize if I'm missing something obvious.

I'd like to link certain platform libraries, but I seem to figure out how. The libraries that I'm talking about are in the following folder:
`/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/lib`

I'm attempting to link the `libc++.dylib`, the `libz.dylib`, and the `libicucore.dylib`, and I don't seem to be able to. Here's what I've tried:

```python
prebuilt_cxx_library(
  name = 'c++',
  lib_dir = '$PLATFORM_DIR/usr/lib',
  visibility = [
    'PUBLIC',
  ],
)

prebuilt_cxx_library(
  name = 'z',
  lib_dir = '$PLATFORM_DIR/usr/lib',
  visibility = [
    'PUBLIC',
  ],
)

prebuilt_cxx_library(
  name = 'icucore',
  lib_dir = '$PLATFORM_DIR/usr/lib',
  visibility = [
    'PUBLIC',
  ],
)
```

It's not finding the referenced library file for 2 reasons:
1. `$PLATFORM_DIR` doesn't seem to work in this context. I noticed that syntax being used to define frameworks, and I hoped that would work here as well.
2. it's looking for a `lib{name}.a` file, and not a `lib{name}.dylib`

How should I be linking these files to my `apple_binary`?

**Comment by sdwilsh** [comment]
I think (caveat: I don't work on our iOS stuff) that you can just do something like this and it should automatically get picked up because the system libraries are already on your include path:

```
prebuilt_cxx_library(
  name = 'c++',
  exported_linker_flags = [
    '-lc++',
  ],
  visibility = [
    'PUBLIC',
  ],
)
```

**Comment by spierce7** [comment]
I see what you were trying there, and it makes sense, but it still ends up trying to find the file:

`BUILD FAILED: java.lang.RuntimeException: java.nio.file.NoSuchFileException: /blah/blah/blah/j2objc-test/j2objc/lib/libz.a`

**Comment by spierce7** [comment]
Your solution did end up leading me to what I needed though. I just added the 
```
  exported_linker_flags = [
    '-lc++',
  ],
```
to my `apple_library`, and that did the trick. I remember reading that in the documentation. Not sure why it didn't occur to me.

Thanks again for your prompt and helpful responses @sdwilsh !
