### ISSUE TITLE
In Buck, Why Module A cannot refer Module B's resources, like R.string.. R.id..

### ISSUE THREAD

**Issue by ASCE1885** [facebook/buck#579]

**Comment by marcinkosiba** [comment]
Please provide a more detailed description of your issue.

**Comment by ASCE1885** [comment]
In Android Studio, I have many modules as library, for example, I have four modules :  app, common, fund, treasure. fund depends on common, treasure depends on common. In fund module, it needs to refer a resource like drawable or string in common module, but when run

```java
buck install --run ...
```

fund module cannot find the R.drawable.* or R.string.* in common module.

**Comment by sdwilsh** [comment]
What does the structure of your `android_resource` and `android_library` rules look like?

**Comment by ASCE1885** [comment]
I have two module, common and safetykeyboardnew,

### common/BUCK

```java
android_resource(
	name = 'res_main',
	res = 'src/main/res',
	package = 'com.pingan.fstandard.common',
	assets = 'src/main/assets',
	deps = [
		'//safetykeyboardnew:res_main',
	],
	visibility = [
		'PUBLIC',
	],
)

android_library(
	name = 'src',
	srcs = glob([
		'src/main/java/**/*.java',
	]),
	manifest = 'src/main/AndroidManifest.xml',
	annotation_processors = [
		'com.paic.hyperion.core.hfjson.compiler.JsonAnnotationProcessor',
	],
	annotation_processor_deps = [
		'//.okbuck/annotation_processor_deps/common:all_jars',
		'//.okbuck/annotation_processor_deps/common:all_aars',
	],
	deps = [
		':res_main',
		':build_config',
		'//safetykeyboardnew:src',
		'//safetykeyboardnew:res_main',
		':native_libs',
	],
	visibility = [
		'PUBLIC',
	],
)
```

In safetykeyboardnew/BUCK

```java
android_resource(
	name = 'res_main',
	res = 'src/main/res',
	package = 'com.soft.safetykeyboardlibery',
	deps = [
	],
	visibility = [
		'PUBLIC',
	],
)

android_library(
	name = 'src',
	srcs = glob([
		'src/main/java/**/*.java',
	]),
	manifest = 'src/main/AndroidManifest.xml',
	deps = [
		':res_main',
		':build_config',
	],
	visibility = [
		'PUBLIC',
	],
)
```

and the error message is:

```java
/common/ImageConfig.java:14: error: 找不到符号
    .showImageOnFail(R.drawable.ic_launcher)    //error  
```

ic_launcher is in safetykeyboardnew/res/drawable-xxhdpi.

**Comment by ASCE1885** [comment]
找不到符号 means cannot find symbol

**Comment by marcinkosiba** [comment]
> ic_launcher is in safetykeyboardnew/res/drawable-xxhdpi.

however you `android_resource` entry in `safetykeyboardnew/BUCK` says `res = 'src/main/res',` which means that, for that target, buck is looking for resources under `safetykeyboardnew/src/main/res` and not under `safetykeyboardnew/res`. Looks like you're missing an `android_resource( ... res ='res' ... )` rule in your `safetykeyboardnew/BUCK` file.

**Comment by nayrmi** [comment]
@ASCE1885 - I'm guessing that this resolved your issue. If not, please reactivate!
