### ISSUE TITLE
LuaBinaryIntegrationTest is failing here

### ISSUE THREAD

**Issue by davido** [facebook/buck#581]
On most recent master (0b5e8863ec2c1bf8e48ceade2877f0078f22d9cc) 4 tests are failing:

```
TESTS FAILED: 4 FAILURES
Failed target: //test/com/facebook/buck/lua:lua
FAIL com.facebook.buck.lua.LuaBinaryIntegrationTest
```

The full log is here: http://paste.openstack.org/show/482223.

**Comment by sdwilsh** [comment]
@andrewjcg, you should add lua to Travis so we can run those tests too.

**Comment by davido** [comment]
Missed to mention, that lua is installed on this laptop:

```
$ lua -v
Lua 5.2.2  Copyright (C) 1994-2013 Lua.org, PUC-Rio
```

**Comment by andrewjcg** [comment]
Thanks for the report.  Fix is incoming.

**Comment by davido** [comment]
Great (and fast)!
