### ISSUE TITLE
genrule: Reintroduce deps parameter again

### ISSUE THREAD

**Issue by davido** [facebook/buck#606]
`deps` parameter was recently removed from `genrule()` with this argumentation: "It doesn't do anything useful" anyway. I think it's not quite true. Even when a dependency doesn't contribute to the output artifact, the fact it's there have (at least) two implications:

#### The dependencies should be (re-)built:

```
genrule(
  name = 'all',
  cmd = 'echo done >$OUT',
  deps = [
    ':foo',
    ':bar',
  ],
  out = '__all_fake__',
)
```

I know i could do it with `zip_file`,

```
zip_file(
  name = 'all',
  srcs = [
    ':foo',
    ':bar',
  ],
  out = 'all.zip',
)
```

But why should i create unnecessary uber-jar? Instead I'm forced to write ugly hacks:

```
genrule(
  name = 'all',
  cmd = 'true $(location :foo); true $(location :bar); echo done >$OUT',
  out = '__all_fake__',
)
```

Note, that `foo` and `bar` targets can be located in different Buck build files.

#### Logical dependency can be expressed:

genrule `foo` depends on genrule `bar` and this could be evaluated at some point with `buck query deps(:foo) --output-attributes=buck.direct_dependencies` to do something useful.

One use case, is to define the dependency between JavaScript artifacts `polymer`, to their corresponding licenses (text files), to generically generate the combined license file for the entire product, as it's done in Gerrit Code Review build toolchain. Note, that this can be easily achieved with `java_library` for JAR artifacts (and is in fact done this way) and it's more then useful to do the same for genrule generated artifacts: [1]. Yet again, we are forced to write ugly hacks:

```
# Add 'license' argument to genrule.
_buck_genrule = genrule
def genrule(*args, **kwargs):
  license = kwargs.pop('license', None)
  if license:
    license = '//lib:LICENSE-%s' % license
    # genrule has no deps attribute, but locations listed in the command show
    # up as deps of the target with `buck query`.
    kwargs['cmd'] = 'true $(location %s); %s' % (license, kwargs['cmd'])
  _buck_genrule(*args, **kwargs)
```

* [1] https://gerrit-review.googlesource.com/Documentation/licenses.html#polymer

**Comment by k21** [comment]
The first case you have mentioned does not guarantee that the dependencies will be rebuilt when they change (they won't be if Buck determines that the `genrule`'s output does not depend on the outputs of the rules) and having the parameter available made it likely that people using the rule will reach the wrong conclusion and rely on broken functionality.

The second use case you mention does not currently have a better workaround, but I think it would be preferable to have a dedicated mechanism to specify meta-rules like this over relying on fake `genrule`s that do nothing.

**Comment by mrkane27** [comment]
Not sure if you're going to add it back, but currently the documentation for [`export_file`](https://buckbuild.com/rule/export_file.html) has an example `genrule()` with a `deps` argument in it.

**Comment by Coneko** [comment]
We added `licenses` to all target types, that could help: https://github.com/facebook/buck/commit/d0223d9d1e5710b38e72ae696517a5e94ce5ded8 .
