### ISSUE TITLE
Poison: inotify_add_watch in wrong tree

### ISSUE THREAD

**Issue by davido** [facebook/buck#616]
I'm using Buck to work on Gerrit Code Review and Buck itself. Beside that I'm working on dozen different projects, among other LibreOffice. So, watchman is complaining during `buck clean` in gerrit tree (`/home/davido/projects/gerrit`), about `inotify-add-watch(/home/davido/projects/libo/workdir/Dep/CxxObject/svl/qa/unit/notify)` in LibreOffice tree. How can I ask watchman to only watch for `gerrit` and `buck` trees and ignore the rest of the world?

The whole truth: [1].

Watchman version:

```
$ watchman --version
3.2.0
```

* [1] http://paste.openstack.org/show/483972/

**Comment by sdwilsh** [comment]
cc @wez, although you might want to file this with the facebook/watchman project instead.

**Comment by davido** [comment]
I considered this, but wasn't sure, if this is somehow related to Buck. I do have sone BUCK file in LibreOffrice tree (`/home/davido/projects/libo/`), though.

**Comment by wez** [comment]
The link at the bottom of your error paste has instructions on how to remediate this situation (increase your system limits so that you don't run out of watch resources).

If you can't or don't want to do that for some reason, you can manually cancel out watches using the `watchman watch-del` command.

With that addressed, I think @davido's question is, how can he ask buck not to use watchman for builds in the projects that he doesn't want to commit watch resources against?

**Comment by davido** [comment]
> With that addressed, I think @davido's question is, how can he ask buck not to use watchman for builds in the projects that he doesn't want to commit watch resources against?

Yes exactly. I'm not working currently on LibreOffice, and this is a project with ~100 thousands files (sources + generated) so how could I control what is being watched and what doesn't?

From the user perspective, when i have three project directory:

```
/home/davido/projects/proj1
/home/davido/projects/proj2
/home/davido/projects/proj3
```

All of them are using Buck build system, how can i restrict my current work (regarding watchman) to project `proj1` and let the rest alone?

**Comment by wez** [comment]
@davido take a look at this watchman configuration option:
https://facebook.github.io/watchman/docs/config.html#root_files

**Comment by davido** [comment]
@wez Thanks.

I added this file:

$ cat /etc/watchman.json

```
{
  "root_files": [".watchmanconfig"]
}
```

and upgraded watchman and increased `fs.inotify.max_user_watches`. After that i executed `shutdown-server` command, with

```
$ watchman shutdown-server
$ watchman --version
4.3.0
```

Now when I'm trying to use `buck build foo` I'm getting:

```
[2016-01-15 21:32:02.657][error][command:d1bdee7f-a15a-4112-812d-d38f02bfed70][tid:824][com.facebook.buck.util.WatchmanWatcher] Error in Watchman output
com.facebook.buck.util.WatchmanWatcherException: unable to resolve root /home/davido/projects/gerrit: directory /home/davido/projects/gerrit is not watched
	at com.facebook.buck.util.WatchmanWatcher.postEvents(WatchmanWatcher.java:295)
	at com.facebook.buck.cli.Main$Daemon.watchFileSystem(Main.java:284)
	at com.facebook.buck.cli.Main$Daemon.access$6(Main.java:273)
	at com.facebook.buck.cli.Main.getParserFromDaemon(Main.java:792)
	at com.facebook.buck.cli.Main.executeCommand(Main.java:603)
	at com.facebook.buck.cli.Main.runMainWithExitCode(Main.java:452)
	at com.facebook.buck.cli.Main.tryRunMainWithExitCode(Main.java:979)
	at com.facebook.buck.cli.Main.runMainThenExit(Main.java:1036)
	at com.facebook.buck.cli.Main.nailMain(Main.java:1065)
	at sun.reflect.GeneratedMethodAccessor58.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.martiansoftware.nailgun.NGSession.run(NGSession.java:338)

Watchman threw an exception while parsing file changes.
```

Buck only worked again after I manually said this:

```
$ watchman watch /home/davido/projects/gerrit
{
    "version": "4.3.0",
    "watch": "/home/davido/projects/gerrit"
}
```

Was there any behavioural change that made this manual intervention necessary?

I also wonder, if there any way to ask, what project roots watchman is watching on my system? Sorry, if it's obviously how to do that, i couldn't figure out.

**Comment by wez** [comment]
Regarding that error, my suspicion is that the `root_files` configuration you pasted was working against you.

You can use `watchman watch-list` to enumerate the watches.

I'm sorry for not elaborating on this earlier; If the only thing you want to put in `root_files` is `.watchmanconfig`, then I don't think you need or want an `/etc/watchman.json` file, as that is a subset of the default configuration.

Rather, you want to focus on how you can tell watchman where the root of your projects are.  If we didn't find a `.watchmanconfig`, then the defaults will stop walking up the tree until we find a source control directory (`.hg`, `.git`, `.svn`), so if those projects are in separate repos, they'll be watched as separate roots.

If that is not the case, then you can create a `.watchmanconfig` file at the location that you consider to be the root of your project; it can just be an empty json object `{}` as the content.

Does that make sense?

Can you share the output from `ls -l /home/davido/projects/proj1 /home/davido/projects/proj2 /home/davido/projects/proj3 /home/davido/projects` to help me understand which of these control files are present on your system?

**Comment by davido** [comment]
I'm confused, as for why LibreOffice `libo` directory was watched, or may be I'm just misunderstading the error from the `Poison: inotify_add_watch`? That's because this directory has 100k files and I would like to avoid that this project is ever watched, even though it is built with Buck. Here is the `libo` directory: [1]. Note, that this directory doesn't have .watchmanconfig file.

I asume, it wouldn't hurt to be explicit about enforcing that `.watchmanconfig` exists in `/etc/watchman.json`?

Listing watches produces this:

```
{
    "version": "4.3.0",
    "roots": [
        "/home/davido/projects/gerrit2",
        "/home/davido/projects/gerrit"
    ]
}
```

Both `gerrit` and `gerrit2` are Gerrit Code Review trees: [2] (they do have .watchmanconfig)

Now, when I'm going to `libo` directory and issue `buck build` it activates wathcing this tree, even though, this directry doesn't have `.watchmanconfig` and global 

```
$ buck build api 
Buck is at 79d36de9f5284f6e833cca81867d6088a25685fb, but should be 6659a474fb2ba6e921bb38c1b55d4c9ba6073cfa.
Buck is updating itself. To disable this, add a '.nobuckcheck'
file to your project root. In general, you should only disable
this if you are developing Buck.
Buck does not appear to have been built -- building Buck!
All done, continuing with build.
Using watchman.
Waiting for Watchman command [/home/davido/bin/watchman watch-project /home/davido/projects/libo/.]...
```

So that now the watch-list was extended with the directory with 100k files:

```
$ watchman watch-list
{
    "version": "4.3.0",
    "roots": [
        "/home/davido/projects/libo",
        "/home/davido/projects/gerrit2",
        "/home/davido/projects/gerrit"
    ]
}
```

So that after every single buck invocation i am forced to delete project tree from the watch list manually:

```
$ watchman watch-del /home/davido/projects/libo
{
    "version": "4.3.0",
    "watch-del": true,
    "root": "/home/davido/projects/libo"
}
davido@linux-ucwl:~/projects/libo (master $%=)$ watchman watch-list
{
    "version": "4.3.0",
    "roots": [
        "/home/davido/projects/gerrit2",
        "/home/davido/projects/gerrit"
    ]
}
```

Of course I could use `NO_BUCKD=1` to ask Buk to skip watchman usage, but this would mean that I always have to think and not to forget it:

```
$ NO_BUCKD=1 buck build api 
Not using buckd because NO_BUCKD is set.
[-] PROCESSING BUCK FILES...FINISHED 0,2s [100%]
[-] BUILDING...FINISHED 0,3s [100%] (1/19 JOBS, 0 UPDATED, 0,0% CACHE MISS)
davido@linux-ucwl:~/projects/libo (master $%=)$ watchman watch-list
{
    "version": "4.3.0",
    "roots": [
        "/home/davido/projects/gerrit2",
        "/home/davido/projects/gerrit"
    ]
}
```

I think I'm asking for more Buck -> Wathcman integration, and offer a feature, that I selctively can activate or deactivate projects that I'm building with Buck to use watchman or not.

In the setting above, `watchman` should refuse to work, and say something like: watch is eactivated for this tree, by enforcing the presense of `.watchmanconfig` file in the project tree, but this file was missing. Buck should recover and build without using watchman, as if the `NO_BUCKD=1` was passed.

```
Waiting for Watchman command [/home/davido/bin/watchman watch-project /home/davido/projects/libo/.]...
```
[1] http://paste.openstack.org/show/484058
[2]

**Comment by Coneko** [comment]
We can do it both ways: either add a setting in `.buckconfig` to be able to specify watchman and buckd should not be used in a project, or have watchman refuse to work and Buck handle that gracefully.

@wez What would you prefer? The former doesn't require any changes in watchman but the latter could support other use cases where watchman could decide whether it wants to enable a watch or not.

**Comment by wez** [comment]
I think we should probably add these options to both buck and watchman.

A couple of reasons why below; maybe not the best reasons in the world :-)

* If watchman isn't yet started and buck spawns it, that will cause watchman to crawl any saved watches.  If it turns out that the project dir of interest to buck is disabled through watchman configuration, buck will then be competing for I/O to run the build.

* The error reporting interface from watchman is textual in nature, so if buck would like to react to the situation where watchman is configured to be disabled for a path (perhaps to show a less scary notice to the user than the default unavailable-watchman messaging), buck would be at the mercy of matching text strings

**Comment by Coneko** [comment]
Sounds good enough to me.

Created #618 to track adding the new feature.
