### ISSUE TITLE
Android Quickstart .hgignore file has invalid pattern

### ISSUE THREAD

**Issue by DanielGrech** [facebook/buck#619]
The command `buck quickstart --type android --dest-dir .` generates a default .hgignore file with the following contents:

```
*.iml
/.idea/compiler.xml
/.idea/libraries/*.xml
/.idea/modules.xml
/.idea/runConfigurations/Debug_Buck_test.xml
/buck-cache
/buck-out
/.buckd
```

Running the command the `hg init && hg status` on the newly generated project gives an error:

`abort: /path/to/project/.hgignore: invalid pattern (relre): *.iml`

Looks like the default .hgignore file is missing a `syntax: glob` at the beginning

Mecurial Version: 3.6.3
Buck Version: v2015.12.14.01

**Comment by sdwilsh** [comment]
If you are interested in doing a PR, the file to change is `src/com/facebook/buck/cli/quickstart/android/.hgignore`
