### ISSUE TITLE
GroovyTestIntegrationTest are flaky in Travis

### ISSUE THREAD

**Issue by ruibm** [facebook/buck#626]
Over the last week we have seen a number of flaky travis builds point to the test => com.facebook.buck.jvm.groovy.GroovyTestIntegrationTest

Here are a couple of pointers to travis:
1. https://travis-ci.org/facebook/buck/builds/103583967
2. https://travis-ci.org/facebook/buck/builds/103575124
3. https://travis-ci.org/facebook/buck/builds/103459312

I'll go ahead and disable this test in travis until this is resolved.

**Comment by ruibm** [comment]
Hi @grumpyjames! Reliable sources tell me you are a strong point of contact to diagnose/fix this. :)
Could you please take a look? Thanks!

**Comment by grumpyjames** [comment]
I can definitely give it a go :-)

The implementation of groovy_test is so embarrassingly similar to java_test that I don't think it is likely to be to blame. Therefore, my first guess is that I've done something unidiomatic in the tests that's causing some sort of corruption when we create the project workspace (those prebuilt jars definitely aren't checked in empty, or the build would always fail).

I can spot one unnecessary thing immediately: the `verify` calls are completely pointless; I'll remove them.

Other than that, the test looks reasonable; certainly it appears very similar to other integration tests (some of the Aapt tests create and setup the workspace in a `@Before`, for example)

This makes me think that, however unlikely, there might actually be something wrong with the implementation. I'll take a closer look to see if there's any differences between Groovy Test/Java Test that I've missed. It's possible this might be uncovering a bug somewhere in the groovy _library_ implementation too, I suppose.

Side note: looks like I have something else to fix in GroovycToJarStepFactory

<pre>
[2016-01-20 11:09:06.173][warn ][tid:143][com.facebook.buck.rules.RuleKeyBuilder] Attempting to add absolute path to rule key. Only using file name: /usr/share/groovy/bin/groovyc
</pre>

**Comment by grumpyjames** [comment]
Looking a bit at how those jars are supposed to get into:

<pre>
/tmp/buck-64555de1-6bb7-43bf-a9a6-aa22c4472bed/test/com/facebook/buck/jvm/groovy/__java_test_groovy_tmp__/junit7935749327569884613/buck-out/gen/com/example/spock/spock-core.jar.
</pre>

It looks like prebuilt_jar is supposed to do this here (`PrebuiltJar:235`):

<pre>
steps.add(CopyStep.forFile(getProjectFilesystem(), resolvedBinaryJar, copiedBinaryJar));
</pre>

That really does suggest that we've managed to end up with empty jar files in our temporary folder. I'll go and check a few of the other test rules to see if I've done anything exceptional with regards to adding those jars or configuring the `prebuilt_jar` rules in addition.

**Comment by grumpyjames** [comment]
Odd: we never see the exception for the `junit` jar

**Comment by grumpyjames** [comment]
I didn't realise that by flaky, you actually meant "it hasn't passed since landing in master".

In more oddness, it did pass in the PR run...

**Comment by grumpyjames** [comment]
OK; this fails reliably for me locally as well on master

@ruibm Please feel free to revert the introducing change. Something's gone awry in the integration process - I'll investigate locally and send a new PR.

**Comment by grumpyjames** [comment]
@ruibm Scratch that. I think I blame either github or the import bot. All five of those jar files are empty on master, so I'm guessing they got truncated somewhere between the PR and there...

**Comment by ruibm** [comment]
Touché!! Thanks for tracking this down @grumpyjames. I'll chase after this @facebook-github-bot now. :)

**Comment by ruibm** [comment]
For reference, here's the commit that added the real jars:
https://github.com/facebook/buck/commit/9491d945304ec53e80f09acd8aa0920474c5749e
