### ISSUE TITLE
groovy_library use argfile for list of sources.

### ISSUE THREAD

**Issue by trevorriles** [facebook/buck#629]
To avoid issues with `ARG_MAX` limits when running the `groovy_library` build rule, the `groovyc` step should work like that `javac` step by writing a list of sources to file then executing the compiler on those sources.

The `javac` build step writes a files to `buck-out/gen/x/__y__srcs` for a build target of `//x:y`

**Comment by sdwilsh** [comment]
cc @grumpyjames

**Comment by grumpyjames** [comment]
Heh; I didn't know this was possible; neither the groovy documentation (www.groovy-lang.org/groovyc.html) or groovyc's usage documents it.

I'll look at adding it: `GroovycToJarStepFactory` already has the information to make the decision, it just deliberately ignores it right now :-)

**Comment by grumpyjames** [comment]
Some notes in case @trevorriles (or indeed anyone else) fancies a bash at this:

- Code with very similar behaviour lives in `ExternalJavac` at the moment.
- We deliberately decided to not give groovy the behaviour java has right now where it can read sources out of zips (so the big `else if` in `getExpandedSourcePaths` is probably irrelevant)

If someone else did want to pick this up, please yell and I'll hold off putting together the PR myself :-)

**Comment by trevorriles** [comment]
> Heh; I didn't know this was possible; neither the groovy documentation (www.groovy-lang.org/groovyc.html) or groovyc's usage documents it.

I noticed that as well, but I tested it out and the command line and it seems to work. I'll look into opening a ticket with the groovy team to get it documented.

**Comment by grumpyjames** [comment]
In other amusing news, it looks like that `Optional<Path>` isn't really that optional; we only ever call `createCompileToJarStep` with `Optional.of(pathToSrcsList)` in `DefaultJavaLibrary` or delegate the call, so a secondary change would be to get rid of the `Optional` and the associated branching code below it. Woot.

**Comment by grumpyjames** [comment]
Possibly even three changes, as I reckon 

<pre>
steps.add(new MkdirStep(getProjectFilesystem(), pathToSrcsList.getParent()));
</pre>

in `DefaultJavaLibrary` is redundant as well. That unlocks the removal of that Optional, and that makes fixing the issue a little easier. Unless I hear otherwise, I'll start work on these tomorrow.

**Comment by trevorriles** [comment]
Awesome, thanks @grumpyjames
