### ISSUE TITLE
How to use genrule output in lib_dir

### ISSUE THREAD

**Issue by cbrauchli** [facebook/buck#630]
I am trying to write a macro that takes an apple `.framework` and statically links with it (as one does when one must support iOS 7). Since frameworks are essentially folders containing a binary and headers and have a predictable layout, I came up with this macro:

```python
def apple_static_framework(
  name,
  header_only                           = False,
  framework_name                        = None, # Defaults to {name}. If framework is called "MyFramework.framework", this should be "MyFramework".
  framework_dir                         = None,
  header_namespace                      = None, # Defaults to {framework_name}.
  exported_preprocessor_flags           = [],
  exported_platform_preprocessor_flags  = [],
  exported_linker_flags                 = [],
  exported_deps                         = [],
  visibility                            = []
  ):
  framework_name   = framework_name or name
  header_namespace = header_namespace or framework_name
  genrule_name     = "Framework{0}Prep".format(name)
  framework_path   = "{0}/{1}.framework".format(framework_dir, framework_name) if framework_dir else framework_name + '.framework'

  genrule(
    name = genrule_name,
    srcs = [ framework_path ],
    bash = "mkdir -p $OUT && cp $SRCDIR/{0}.framework/Versions/Current/{0} $OUT/lib{0}.a".format(framework_name),
    out  = "Framework-{0}".format(framework_name)
  )

  prebuilt_cxx_library(
    name                                 = name,
    header_only                          = header_only,
    lib_name                             = framework_name,
    lib_dir                              = ":" + genrule_name, # maybe "$(location :{0})".format(genrule_name),
    exported_headers                     = glob(["{0}/Versions/Current/Headers/**/*.h"]),
    header_namespace                     = header_namespace,
    exported_preprocessor_flags          = exported_preprocessor_flags,
    exported_platform_preprocessor_flags = exported_platform_preprocessor_flags,
    exported_linker_flags                = exported_linker_flags,
    force_static                         = True,
    exported_deps                        = exported_deps,
    visibility                           = visibility
  )
```

Unfortunately, I cannot figure out how to use the `genrule`'s output directory as the argument to the `lib_dir`. Any suggestions?

**Comment by sdwilsh** [comment]
`lib_dir` is currently a `String` type in Java, which means it won't resolve the name of the target.  We'd have to make that a `SourcePath` for that to work here: https://github.com/facebook/buck/blob/master/src/com/facebook/buck/cxx/PrebuiltCxxLibraryDescription.java#L417

**Comment by sdwilsh** [comment]
...but that likely won't work right because we check for existence of the libraries when we create our action graph for building.  We'd have to change the interface to accomplish this.

I'll get @andrewjcg to comment on a possible API design.

**Comment by andrewjcg** [comment]
Yeah, the `prebuilt_cxx_library` UI is pretty bad.  Ideally we'd get rid of the `lib_dir` and `lib_name` parameters, which we currently use to construct the paths to static, static-pic, and shared libs, and replace them with explicit parameters for the these libraries (e.g. `static_lib`, `static_pic_lib`, `shared_lib`) which would be `SourcePath`s directly pointing to the library.

**Comment by cbrauchli** [comment]
Gotcha. Can you explain how these parameters would be used? E.g., if `static_lib` and `static_pic_lib` are both provided how should Buck decide which one to use? Also, I missed that `cxx_library` even talked about pic—does `static_lib` mean that the library _is_ position-dependent? 

I assumed that the reason `prebuilt_cxx_library` had the weird interface was because compilers have the convention that libraries are named `lib{name}.{a,so}`. If `SourcePath`s to the libraries are passed in directly, what should happen if they happen to not follow that naming convention? Raise an exception?

Thanks for the help!

**Comment by dflems** [comment]
Any updates on this? I'm having a similar issue.

**Comment by andrewjcg** [comment]
Sorry for the delay here.  The convention we've been using is that if *both* `static_lib` and `static_pic_lib` are specified, then the former is PDC and the latter is PIC.  If, however, *only* `static_lib` is specific it is assumed to be PIC.  It is a bit unintuitive, so I wouldn't be against changing this, but I think either way we need to end up using a PIC lib in a non-PIC link if it's the only one available, since this is a pretty common scenario.

We have the weird interface mostly for legacy reasons.  It's true that the linux and darwin linkers have present extensions they looks for when `-l<name>` is used, but I think it's actually linker dependent if it requires these extensions when the full lib path is specified on the link line, and in the case of binutils/linux I believe the actual extension doesn't matter.  That said, I think it's fine to leave the input names unchecked and just let the link through an error if it takes issue with the name.

**Comment by nayrmi** [comment]
@cbrauchli / @dflems - I'm closing this out with @andrewjcg's response, but please reactivate if you're still hitting this!

**Comment by Qix-** [comment]
Still confused as to how to use `genrule()`'s output.

```python
genrule(
    name = 'test-peg',
    srcs = ['src/test.peg'],
    out = 'test-peg.c',
    cmd = 'peg src/test.peg -o $OUT')

cxx_binary(
    name = 'test-project',
    srcs = [
        'src/cli.c',
        '$(location //:test-peg.c)'],  # //:test-peg by itself didn't work either...
    compiler_flags = [
        '-Wall', '-Wextra',
        '-Werror', '-pedantic',
        '-std=c99'],
    licenses = [
        'LICENSE'],
    visibility = [
        'PUBLIC'])
```

**Comment by Coneko** [comment]
@Qix- that's unrelated, can you open a new issue for that?
