### ISSUE TITLE
windows compile failed

### ISSUE THREAD

**Issue by zlwen** [facebook/buck#635]
i download the source code of buck, it works in mac, however when i copy the source code to windows, compile error occurs. it seems that the immutable classes are not generated which should be the output of immutables' annotation processor

**Comment by ryu2** [comment]
Can you paste the output including the errors?

**Comment by ilya-klyuchnikov** [comment]
@zlwen, do you still have problems with windows compilation? I have just checked that buck is built OK on windows.
