### ISSUE TITLE
Any example of using the multi-dex feature when building android_binary?

### ISSUE THREAD

**Issue by achieverForever** [facebook/buck#636]
I am trying to build my APP with Buck. When we are building our apk, we need to perform a dex-merge of tens of classes.dex files into 2 or 3 .dex files, and when we get a DexIndexOutOfFlow exception when merging, we write to another .dex file. Does Buck has any support of this? I know there is a PreDexMerge rule, but are there any example of using this feature.

**Comment by Coneko** [comment]
There some information about that here and in similar stackoverflow questions: http://stackoverflow.com/questions/33910859/buck-exopackage-multi-dex-support

You can also see examples in the tests:
https://github.com/facebook/buck/blob/master/test/com/facebook/buck/android/AndroidBinaryIntegrationTest.java
https://github.com/facebook/buck/tree/master/test/com/facebook/buck/android/testdata/android_project

**Comment by achieverForever** [comment]
Thanks for your information, I will check it out.
