### ISSUE TITLE
Specifying xctool_default_destination_specifier fails

### ISSUE THREAD

**Issue by rmaz** [facebook/buck#639]
Trying to run tests on a different version of the simulator fails. Adding the following to the iOS example app `.buckconfig`:

```
[apple]
  xctool_default_destination_specifier = platform=iOS Simulator,name=iPhone 6,OS=8.4
```

will cause tests to fail with:

```
RESULTS FOR //ios:BuckDemoAppTest
FAIL    CACHED  0 Passed   0 Skipped   1 Failed   Internal error from test runner
FAILURE Internal error from test runner main: Failed to query the list of test cases in the test bundle: dyld: app was built for iOS 9.2 which is newer than this simulator 8.4
```

The issue seems to be that xctool cannot query the test cases due to some linker error, I suspect related to this issue: https://github.com/facebook/xctool/issues/643

**Comment by ExtremeMan** [comment]
I don't think it is actually related to that issue. The error says that you most likely used newer deployment target sdk when building a test bundle.

**Comment by rmaz** [comment]
You are probably right, I dont have the sample project around any more to check
