### ISSUE TITLE
Provide maven_jar() to fetch artifacts from Maven repository

### ISSUE THREAD

**Issue by davido** [facebook/buck#64]
Let's face it: to implement build process in Java eco system third party libraries must be fetched from the Maven repository. Even if we would replace the word Maven repository with Buck repository in the previous statement we still need a native support in Buck to do that.

Gerrit's Buck based build provides such a method [1]:

 ```python
def maven_jar(
    name,
    id,
    license,
    exclude = [],
    exclude_java_sources = False,
    unsign = False,
    deps = [],
    sha1 = '', bin_sha1 = '', src_sha1 = '',
    repository = MAVEN_CENTRAL,
    attach_source = True,
    export_deps = False,
    visibility = ['PUBLIC']):
[...]
 ```

Which uses download_file.py backend script [2].

Here is another use case: tiny Gerrit plugin that can be built outside of the Gerrit tree with Buck, where the `maven_jar()` in simplified form was implemented [3].

[1] https://gerrit.googlesource.com/gerrit/+/master/lib/maven.defs
[2] https://gerrit.googlesource.com/gerrit/+/master/tools/download_file.py
[3] https://gerrit-review.googlesource.com/51225

**Comment by sdwilsh** [comment]
3afdcbd0abcbd7b9f43091b31083f33f2bd3c2de added a `buck fetch` command.  Are we good here now?

**Comment by davido** [comment]
Indeed, 3afdcbd fixed it.
