### ISSUE TITLE
path in cache's http_url being ignored (again)

### ISSUE THREAD

**Issue by sea36** [facebook/buck#640]
Commit 07060eb97af6bb2b53a3b9a239cc614255e1ef35 has caused a regression of issue #434. Ping @ruibm 

We have a requirement that we cannot host our http cache at the root URL.  Our buckconfig looks like:

[cache]
  mode = http
  http_url = http://our.cache.server.lmax.com/buckcache/
  http_mode = readonly
  http_timeout_seconds = 5

Previously this would result is cache reads being resolved to http://our.cache.server.lmax.com/buckcache/artifacts/key/00000000000000000000000000000000 but after this change they new resolve to http://our.cache.server.lmax.com/artifacts/key/00000000000000000000000000000000.

The same is true for cache writes - where they previously resolved to http://our.cache.server.lmax.com/buckcache/artifacts/key they now resolve to http://our.cache.server.lmax.com/artifacts/key.

**Comment by sdwilsh** [comment]
Clearly we need to write a unit test for this...

**Comment by ruibm** [comment]
Unit test and fix on its way. Thanks for reporting @sea36! :)

**Comment by sea36** [comment]
Great news, thanks!

**Comment by ruibm** [comment]
Ok this checkin should have fixed it @sea36 => https://github.com/facebook/buck/commit/a713875dbcccda8210a316d1becb62c26a26be13

Please let me know if it's all fine now. Thanks!

**Comment by ruibm** [comment]
Closing this now, please re-open if it's still a problem. Thanks!

**Comment by sea36** [comment]
Yep, that's fixed the problem. Thank you very much!
