### ISSUE TITLE
"error: cannot find symbol" When using dep android library resource.

### ISSUE THREAD

**Issue by polycoder** [facebook/buck#643]
It seems that we are not able to access a dependent android library resource from within another android library. 

In this scenario we have two android libraries in the `libs` folder:

* `lib1`
* `lib2`

`lib1` depends on `lib2` for a resource, which it accesses directly via R. For example ([excerpt from this file](https://github.com/polycoder/buck-scenario-libraryresourcemerging/blob/master/libs/lib1/src/main/java/com/buckbuild/scenario/lib1/subpackage1/LibOneHelper.java))

```
// lib_two_value comes from lib2 but is available via R in lib1 when using gradle
context.getString(R.string.lib_two_value)
```

When accessing a `lib2` resource like this and running `buck build //libs/lib1:lib`, we get the following output:

```
> buck build //libs/lib1:lib
[-] PROCESSING BUCK FILES...FINISHED 0.2s [100%]
[+] DOWNLOADING... (0.00 B/S, TOTAL: 0.00 B, 0 Artifacts)
[+] BUILDING...1.0s [50%] (4/5 JOBS, 0 UPDATED, 0.0% CACHE MISS)
 |=> //libs/lib1:lib...  0.5s (running javac[0.4s])
 |=> IDLE
 |=> IDLE
 |=> IDLE
 |=> IDLE
/Users/seank/repo/buck-tests/BuckScenarioLibraryResourceMerging/libs/lib1/src/main/java/com/buckbuild/scenario/lib1/subpackage1/LibOneHelper.java:14: error: cannot find symbol
        return context.getString(R.string.lib_two_value);
                                         ^
  symbol:   variable lib_two_value
  location: class com.buckbuild.scenario.lib1.R.string
Errors: 1. Warnings: 0.
```

To help as much as possible, I've created a test buck scenario with additional documentation on the problem [here](https://github.com/polycoder/buck-scenario-libraryresourcemerging)

Perhaps our buck configuration is not correct, or maybe buck does not provide the same lib1 -> lib2 resource merging as Gradle like we would normally expect.

**Comment by sdwilsh** [comment]
Thanks for the super detailed report!  It made it a lot easier to debug this and understand what was going on.  I didn't know about `resource_union_package`, and I'm actually surprised you found it!  8852bda6c1700b62bc99b9a4d18b273380d605b6 is the commit that added it (by @dreiss).  I think the commit message actually documents the difference between Buck and Gradle there.

I would expect that Buck would work if you instead did `com.buckbuild.scenario.lib2.R.string.lib_two_value`.  It's more verbose, but it also enforces the encapsulation of the module better.

**Comment by polycoder** [comment]
Yes @sdwilsh you are entirely correct - changing `R.string.lib_two_value` to `com.buckbuild.scenario.lib2.R.string.lib_two_value` will allow `buck build //libs/lib1:lib` to run successfully.

It sounds like this is expected behavior that is a known deviation from how Gradle packages lib resources. It's a bit of a hindrance for us since our libraries currently heavily utilize the 'convenience' of the resource merging into the library's R file...so we would need to do additional code changes to reference the full paths to get things up and running.

Do you think there is room for a feature to enable '[gradle-like](http://tools.android.com/tech-docs/new-build-system/resource-merging)' merging of resources. It could possibly help other developers with ease of adoption when converting from gradle to buck.

I was hoping the `resource_union_package` would do the trick and couldn't quite figure out why the `lib1` library builds but the app can't find the resource at runtime...@dreiss would you be able to shed any light on why the unioned resources of `lib1` can't be found when running the app after using the `resource_union_package` and adding it to the `//app:app` android_binary target?

**Comment by sdwilsh** [comment]
You might need to set it on the `android_binary` as well (per 11402e09be31733c20f5f13abdd5abf4ae68b94b).  Note that while we have "support" for this, it is unsupported and may break or be removed in the future (which is why it is not documented).  I think setting it on your `android_binary` rules will at least let you live with Gradle and Buck for now.

**Comment by polycoder** [comment]
Thanks @sdwilsh, the pot thickens around this hidden flag! Let me try it out, and see where I can get with this.

**Comment by sdwilsh** [comment]
It certainly isn't something we suggest you do long-term as it adds more work for Buck to do.

**Comment by polycoder** [comment]
Hi @sdwilsh I tried for a long to get our app to build with the hidden resource_union flags, but couldn't find a combination that would allow us to build with buck and gradle at the same time. Basically when using the resource_union for a library the dummyrdotjava contained the resource identifier, but the R.txt did not and this caused issues when using the library as a dep of an android_binary. To resolve this I created a commit that selectively allows resource_union for an android_resource deps, creating a merged R.txt. With this in place I am able to build the [sample project](https://github.com/polycoder/buck-scenario-libraryresourcemerging), as well as a much more complicated project we have here with minimal code changes. Love to know what you think about this.

**Comment by marcinkosiba** [comment]
Just had a look over this. Just to make sure I understand - if you have liba->libb->libc then the `R.java` file for `liba` should contain the union of resources in `libb` and `libc` or just `libb`?

I can see how you'd have problems with `resource_union_package` as it only allows for one union package for the entire app (it's intended for migrating from the single res folder approach).

**Comment by polycoder** [comment]
write now we aren't affected by the need to include a transitive depency to libc, rather we have a series of libraries (mostly theming related - so lots of resources) that rely on a dependent libraries resource (liba->libb, liba->libc) being available.

**Comment by marcinkosiba** [comment]
@polycoder, understood. I assume that's different than gradle?. I'm asking because we have a MergeResourcesSources rule which uses the same code as gradle does to merge resources. The downside to using it is that it actually does a resource merge (sucks in a bunch of folders and spits out a new folder) so it's not as cheap as the thing

**Comment by polycoder** [comment]
it's actually meant to be very gradleesque. We were seeing with libraries build with buck that they were never including merged resources so for the case of liba->libb liba would not contain the resources of libb in it's R.txt file, and this would lead to a runtime exception since the R.class generated for liba did not contain the proper resource entry to a resource in libb. Is there perhaps another issue going on here where MergeResourcesSources is not included as part of liba->libb build scenarios? Although the full resource merging wouldn't be as cheap -  if the functionality exists, we will use it.

**Comment by marcinkosiba** [comment]
> We were seeing with libraries built with buck that they were never including merged resources txt so for the case of liba->libb liba would not contain the resources of libb in it's R.txt file, and this would lead to a runtime exception since the R.class generated for liba did not contain the proper resource entry to a resource in libb

That's in the case of the `resource_union_package`, right? It's kinda fiddly as you need to set the same package on both the android_library and android_binary.

Anyhow. The MergeAndroidResourcesSources thing probably doesn't give you that much win here (it would have been simpler to code up, but whatevs), so stick to the thing you've got.

**Comment by polycoder** [comment]
Yes @marcinkosiba that is true, if would work appropriately for this sample if fiddled with the union packages for both android_library and android_binary. This approach didn't work for our main app thought because we still had resources in the main app (not in library), that needed to exist as well, so we couldn't resource_union_package in android_binary to a dependent library package. 

I've been playing around a lot with MergeAndroidResourceSources and trying to implement something within AndroidResourceDescription to gather resource deps and peform a merge. It works, but when aapt package command is run when using android_binary, it results in creation of duplicate attributes error. This is due to the multiple -S flags for each res dep of android_binary having a merged copy of all the resources causing collisions...I could see this approach working if there was a way to exclude libraries from being packaged via aapt package, but still have there R.class files generated...

Anyways, I think I'll try to revisit the first approach again and add tests as you requested.
