### ISSUE TITLE
Make NOTESTS a failure (maybe configurably)

### ISSUE THREAD

**Issue by mikekap** [facebook/buck#644]
This has caused problems due to e.g. bad class names in JVM-based languages that allow filename != classname (scala in this case) or tests that call `System.exit` at setup when something goes wrong (spark integration tests). Perhaps most annoyingly, this lets people check in empty tests (by accident).

It seems that `NOTESTS` is basically only used in Jvm-land where `java_test` can include utility classes. Buck reports java tests on a per-class basis (rather than per-target), and some of these classes are not test classes, but fulfill all criteria of a test class (i.e. have 1 constructor). Separately, there's also `@Ignored` classes that currently report `NOTESTS` but should probably be skips.

Some potential solutions:
- Add some sort of annotation or a static field (e.g. `NOT_A_TEST`) (checked via reflection) or always make the classes package-private for utility classes. The downside here is that this is probably a non-trivial migration - there's certainly a few instances of this in buck's code. Given that, making (java only?) NOTESTS a failure condition configurable might be a good idea in this case.
- Split `srcs` on `java_test` into `srcs` and `test_srcs` - compiled together, but only `test_srcs` is used for test discovery. Alternatively, we could invert it as `srcs` and `non_test_srcs` or similar. This is very similar to the above, but in BUCK files. IMO it's a bit annoying to keep the distinction in mind when writing `BUCK` files, but this has the benefit of likely being a lot easier to implement since the distinction is available without parsing the java files.
- Change buck to report jvm tests on a per-target level. This is easy to do, but I don't think anybody would be happy with this solution since it loses the fine-grained reporting.

**Comment by sdwilsh** [comment]
For the second option, couldn't we just make a `java_library` and dep it so you don't have to worry about adding a new field?

**Comment by mikekap** [comment]
I think that would work in most cases, but I think it's possible to have circular dependencies (i.e. Test->Util->Test) that make compiling the `java_library` alone impossible. Certainly most buck code I've seen is not in any danger here.

**Comment by v-jizhang** [comment]
Sorry we haven't update this issue for more than 3 years. At this point, we are closing this because it is quite out of date and it is not clear if the issue still exists. Please create a new one if you still see the problem. Thank you.
