### ISSUE TITLE
add possibility to define flavors when having WILDCARD_BUILD_RULE_SUFFIX in target 

### ISSUE THREAD

**Issue by hutm** [facebook/buck#645]
Currently I cannot build all the targets with a flavor defined. E.g. It would be nice to have this:
  `buck build //...#myFlavor`

**Comment by hutm** [comment]
is it a reasonable feature request? I was not able to find a way to launch a flavored "build all" for cpp project.

**Comment by Coneko** [comment]
I'm not sure this is the exact way we would expose such a feature, but we have hit this issue internally as well.

**Comment by ukreator** [comment]
Any way to do that in the latest revisions of Buck?

**Comment by v-jizhang** [comment]
Sorry, we don't have this feature and we don't have a plan to add this feature either.
