### ISSUE TITLE
Add missing option "--target eclipse" to Buck's project command

### ISSUE THREAD

**Issue by davido** [facebook/buck#65]
Let's face it: a big part of the Java community is using Eclipse IDE. Buck provides only native support for InteliJ IDE integration with project command:

```
buck project --target intellij
```

Gerrit's Buck based build implements Eclipse integration in eclipse.py script [1]. Find a way to integrate it or provide another way to generate .project & .classpath from BUCK build files to be able to import a project in Eclipse IDE:

```
buck project --target eclipse
```

[1] https://gerrit.googlesource.com/gerrit/+/master/tools/eclipse/project.py

**Comment by facebook-github-bot-9** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by mnuessler** [comment]
Is the [bounty](https://www.bountysource.com/issues/1338679-add-missing-option-target-eclipse-to-buck-s-project-command) on this still valid? The issue was closed and then reopened.

**Comment by sdwilsh** [comment]
Yeah, the closing was a bug.  We'd like to get this, it just hasn't been a priority for the core team.

**Comment by ashu-22** [comment]
Is it necessary that we are only used the Eclipse for this kind o project!

**Comment by styurin** [comment]
We are not using Eclipse internally so the team is not going to work on that. We would be happy to review any PRs for that, but we would prefer to have a standalone script which is not a part of buck binary.
