### ISSUE TITLE
Android build should fail with incorrect keystore alias

### ISSUE THREAD

**Issue by DanielGrech** [facebook/buck#655]
Trying to build a project with a keystore as such:

Pertinent BUCK file contents:

```
/** 
    release.keystore.properties contents:

    key.alias=some_incorrect_alias
    key.store.password=password1
    key.alias.password=password1
*/

keystore(
    name = 'release',
    store = 'release.keystore',
    properties = 'release.keystore.properties',
    visibility = ['PUBLIC']
)

android_binary(
    name = 'myapp_release',
    manifest = ':release-manifest',
    keystore = '//keystore:release',
    package_type = 'release',
    deps = [
      ':main-lib'
    ]
)
```

The file `release.keystore.properties` has an incorrect alias listed. I expect that the `buck build myapp_release` command should fail if the alias is incorrect. Instead, it fails silently and the resulting APK is not signed.

Validated with the command:

```
jarsigner -verify -verbose -certs buck-out/gen/myapp_release.apk

  s = signature was verified 
  m = entry is listed in manifest
  k = at least one certificate was found in keystore
  i = at least one certificate was found in identity scope

no manifest.
jar is unsigned. (signatures missing or not parsable)
```

**Comment by marcinkosiba** [comment]
Had a quick look. ApkBuilderStep, line 189-ish. If you add a null check on the key returned from keystore.getKey (Preconditions.checkNotNull or just call key.getFormat() or something) will it blow up?

**Comment by polycoder** [comment]
@marcinkosiba I verified that the values for Key and Certificate could be null if an invalid alias is provided, and added null pointer checks.
