### ISSUE TITLE
Buck can not fetch an `snapshot` dependency in maven repository.

### ISSUE THREAD

**Issue by achieverForever** [facebook/buck#661]
I have a remote_file dependency which points to a jar in local maven repository with version `xx-snapshot`. Buck can not fetch an updated version of it unless I run `buck clean`, does Buck support maven's snapshot mechanism?

**Comment by sdwilsh** [comment]
It doesn't.  One of Buck's big things is repeatable builds, and using a snapshot is not repeatable (if someone else were to check out the same revision as you and fetch and build, they could end up with a completely different binary).  When you run clean, you are clearing out `buck-out` where the downloaded artifact is stored, so you have to get an updated copy.

**Comment by Coneko** [comment]
`remote_file` requires `sha1`. You would have to change that to match the new version anyway, then when you run `buck fetch` it should get it.

**Comment by sdwilsh** [comment]
That's true, but that means it shouldn't download it every time either 
(it would be cached if it was not changed).
