### ISSUE TITLE
Authentication and transitive dependencies with Maven

### ISSUE THREAD

**Issue by mrkane27** [facebook/buck#664]
Apologies if this has already been discussed.

I've been digging through the sources, and I haven't been able to find any authentication support with `remote_file()`, and no automatic fetching of transitive dependencies. Are any of these planned?

**Comment by Coneko** [comment]
Transitive dependencies is not planned, but you can look at https://github.com/facebook/buck/blob/master/src/com/facebook/buck/maven/Resolver.java which helps you set up a `remote_file` target for each dependency.

What do you mean by authentication? That sounds like something we should support, and maybe already do.

**Comment by mrkane27** [comment]
Thanks for the reply!

Re: transitive dependencies, what would be a preferred workflow in the context of `SNAPSHOT`s and generally Maven JARs that change rather frequently? Would the resolver need to be invoked before every build to regenerate the rules?

Re: authentication, the use case is accessing artifacts stored in a Nexus Repository that uses a [basic authentication](https://en.wikipedia.org/wiki/Basic_access_authentication) scheme (which as far as I understand is a header dance of `WWW-Authenticate` and `Authorization`).

`git grep`-ping for `auth`, `401` or `realm` suggests it's not currently supported. I think it might just be a matter of allowing credentials to be specified in either `remote_file()` itself or `[maven_repositories]`, and adding support in the downloader to interpret the `401` response code and reissuing the request. I could try writing it and sending a PR, if it seems reasonable.

**Comment by Coneko** [comment]
> I could try writing it and sending a PR, if it seems reasonable.

Yeah, that does sound like something we should support.

We have https://buckbuild.com/concept/buckconfig.html#maven_repositories as a buckconfig section, so something there would make sense, like:

```ini
[maven_repositories]
central = https://repo1.maven.org/maven2
central_user = user
central_pass = pass
```

or something like that.

**Comment by Coneko** [comment]
> Would the resolver need to be invoked before every build to regenerate the rules?

I think so. It's sort of like having submodules or any kind of dependencies that are pinned to certain versions: updating them is an explicit operation.

**Comment by mrkane27** [comment]
@Coneko , thanks for the code review on this. Is there a flow for adding documentation, should I follow up?

**Comment by Coneko** [comment]
Oh yes, I keep forgetting about that.

You should document the new `.buckconfig` options here: https://github.com/facebook/buck/blob/master/docs/concept/buckconfig.soy#L1424

You can run `docs/soyweb-local.sh` to host the documentation locally and preview your changes.

**Comment by Coneko** [comment]
I assume because the pull requests have been merged this has been resolved, let me know if there's anything left.
