### ISSUE TITLE
.buckconfig parser doesn't handle escaping properly on Windows

### ISSUE THREAD

**Issue by mrkane27** [facebook/buck#667]
I ran into this while trying to run `buck project` on Buck:

```
java.nio.file.InvalidPathException: Illegal char <:> at index 27: ; Common temp file patterns:
```

After some debugging, I've traced it back to ini4j. The loaded `Ini` prints as:

```
{java= (...) project=[{ignore=[.git, .buckd, build, bin, ; Common temp file patterns:] (...)
```

where `.buckconfig` looks like:

```
...
[project]
    ; Directories that do not contain input files.
    ; All of these directories should also appear in the "ignore_dirs" list
    ; in .watchmanconfig, with the exception of ".git".
    ignore = \
      .git, \
      .buckd, \
      build, \
      bin, \

    ; Common temp file patterns:
    ; .*\.swp$ (vim)
...
```

Basically, the comment after an empty line after an escape gets merged into the value.

Seems like a bug in ini4j. Doesn't look like it's happening on Linux.
Same behavior with ini4j 0.5.4.

**Comment by mrkane27** [comment]
Trivial workaround I reckon would be removing the trailing `, \`.

**Comment by Nexen23** [comment]
Is there any workaround [for this (pic of my cmd output)](https://postimg.org/image/uf6hj1cvp/)?
Seems like probably the same error as author has.

**Comment by k21** [comment]
Did you wrap some configuration value in double quotes? The values in `.buckconfig` usually shouldn't be using quotes. Send us your `.buckconfig` if this does not resolve your issue.

**Comment by Nexen23** [comment]
@k21, I haven't done anything. Just `git clone` then `ant` then `buck --help`.
Can't find any attaching options here, so uploaded [.buckconfig here](http://www17.zippyshare.com/v/IkDtwf4a/file.html
).
