### ISSUE TITLE
Can Buck's cache on .class file level to avoid recompliation of all java files on just one line of code change?

### ISSUE THREAD

**Issue by achieverForever** [facebook/buck#670]
I am building a `android_binary` which has `//biz:biz` and `//ui:ui` dependencies, and 80% of java code live in `//ui:ui`. Currently even I just modify one line of code in `//ui:ui`, it triggers a whole recompliation of all java files in `//ui:ui`. Can Buck optimize this to make it cache on .class level. (or I may need to split `//ui:ui` into smaller rules?)

```
android_binary(
    	name = 'apk',
    	manifest = ':manifest',
    	keystore = '//keystore:keystore',
    	deps = ['//biz:biz', '//ui:ui']
)
```

￼￼￼

**Comment by Coneko** [comment]
It's not possible to do that because of how java works: classes in the same compilation unit might have cyclical dependencies.

But splitting the target into smaller ones should help.
