### ISSUE TITLE
export_file parameter order has changed

### ISSUE THREAD

**Issue by artemyarulin** [facebook/buck#677]
Consider following code:

``` bash
> mkdir m && echo "export_file('a','a') > m/BUCK" && touch m/a
> buck build m:a
```

With buck v2016.02.01.01: 
``` bash
> buck build m:a
[-] BUILDING...FINISHED 0.7s [100%] (1/1 JOBS, 1 UPDATED, 100.0% CACHE MISS)
```
With buck v2016.02.29.01: 
``` bash
>buck build m:a
BUILD FAILED: //m:a: parameter 'licenses': cannot coerce 'a' to class com.google.common.collect.ImmutableSet
```

If I'll use named arguments everything works fine:
``` bash
>echo "export_file(name='a',out='a')" > m/BUCK
>buck build m:a
[-] BUILDING...FINISHED 0.7s [100%] (1/1 JOBS, 1 UPDATED, 100.0% CACHE MISS)
```

So looks like parameter order has changed when licenses was introduced.

**Comment by Coneko** [comment]
Yeah the order of parameters can change, as new ones are added or old ones are removed.

Always use named parameters.

**Comment by artemyarulin** [comment]
Hm, thanks, probably I've missed this from the docs

**Comment by Coneko** [comment]
I don't think the docs mention any of this, they just never mention you can create targets without using named parameters in the first place.

**Comment by artemyarulin** [comment]
Ahh, OK - I was thinking that all those commands are just Python function calls and I'm free to do usual Python staff here: named, not named arguments, etc.

**Comment by sdwilsh** [comment]
You are, we just wouldn't suggest you do it that way because of things like this :)

**Comment by artemyarulin** [comment]
Got it, thanks for explanation :)
