### ISSUE TITLE
FAQ page "windows not supported" stale

### ISSUE THREAD

**Issue by chenglou** [facebook/buck#678]
https://buckbuild.com/concept/faq.html

AFAIK Buck does work perfectly on windows now right? (Unfamiliar with Buck)

**Comment by sdwilsh** [comment]
It works mostly fine.  Not everything (native code compilation is a bit one) works, but in general, yes it works :)

**Comment by bviktor** [comment]
Just a headsup: the latest Win10 builds will support non-elevated symlinking as well:

https://blogs.windows.com/buildingapps/2016/12/02/symlinks-windows-10/

**Comment by sdwilsh** [comment]
@bviktor, Buck actually works pretty well on Windows.  It's even covered in the getting started guide.  This piece is just some old cruft that hasn't been removed.  I think I'll do so today.

**Comment by bviktor** [comment]
Yeah, cool, didn't work for me.

**Comment by sdwilsh** [comment]
@bviktor, probably worthwhile to file specific issues about what wasn't working then.  We even have CI on Windows these days.
