### ISSUE TITLE
java.lang.UnsatisfiedLinkError: dlopen failed: "*.so" is 32-bit instead of 64-bit

### ISSUE THREAD

**Issue by Piasy** [facebook/buck#683]
Build project with .so library crashed with error: 
```bash
java.lang.UnsatisfiedLinkError: dlopen failed: "*.so" is 32-bit instead of 64-bit
```

When I extract the output apk file of BUCK, it contains six native library flavors:
```bash
arm64-v8a   armeabi     armeabi-v7a mips        x86         x86_64
```
while the output of gradle build apk file only contains one of them:
```bash
armeabi
```
Than's because I specified the `abiFilter` in my build.gradle, we do this because we don't need architecture specific advantage, and want only maintain one copy of .so libraries.

The problem is that BUCK don't support `abiFilter` for `prebuilt_native_library` rule, and my phone attempts to load the .so library as 64-bit version, which caused the above exception. Could  `prebuilt_native_library` add an `abiFilter` parameter?

**Comment by sdwilsh** [comment]
`android_binary` has an (undocumented) `cpu_filters` which you can pass `['armeabi']` to to limit it how you want.

**Comment by Piasy** [comment]
@sdwilsh Thanks! I tried the `cpu_filters` parameter  and fix this problem. The only difference is the values should be one of `[ARM, ARMV7, X86, X86_64, MIPS]`
