### ISSUE TITLE
Cannot access android.support.v4.app.TaskStackBuilder

### ISSUE THREAD

**Issue by arjunpola** [facebook/buck#684]
I am trying to convert the default Empty Application example from Android Studio to use Buck build.
I added the support library jars and aar files. But when I try to build the app I get the following error:

OUTPUT:

GradleToBuck/app/src/main/java/com/example/gradletobuck/MainActivity.java:7: error: cannot access android.support.v4.app.TaskStackBuilder
public class MainActivity extends AppCompatActivity {
       ^
  class file for android.support.v4.app.TaskStackBuilder not found
GradleToBuck/app/src/main/java/com/example/gradletobuck/MainActivity.java:9: error: method does not override or implement a method from a supertype
    @Override
    ^
GradleToBuck/app/src/main/java/com/example/gradletobuck/MainActivity.java:11: error: cannot find symbol
        super.onCreate(savedInstanceState);
        ^
  symbol:   variable super
  location: class com.example.gradletobuck.MainActivity
Buck_Workspace/GradleToBuck/app/src/main/java/com/example/gradletobuck/MainActivity.java:12: error: cannot find symbol
        setContentView(R.layout.activity_main);
        ^
  symbol:   method setContentView(int)
  location: class com.example.gradletobuck.MainActivity
Errors: 4. Warnings: 0.

**Code available [Here](https://github.com/arjunpola/GradleToBuck)**
Any help would be greatly appreciated.
Thank You

**Comment by laaptu** [comment]
Along with appcompat aar, you also need to add following aars

1. support core utils
2. support core ui
3. support fragment
4. support compat
5. support vector drawable

**Comment by Coneko** [comment]
Assuming that fixed it.
