### ISSUE TITLE
build break when I want to build so for arm

### ISSUE THREAD

**Issue by Ray-Ni** [facebook/buck#689]
When I add "android-arm" into supported platform in jsc/BUCK, 
 it build break with follow message:

buck build :android-jsc
/var/folders/wf/flf9r8gj62550hlvlm3p53pc0000gn/T/ccrnqrPx.s: Assembler messages:
/var/folders/wf/flf9r8gj62550hlvlm3p53pc0000gn/T/ccrnqrPx.s:107: Error: invalid immediate: 983040 is out of range
/var/folders/wf/flf9r8gj62550hlvlm3p53pc0000gn/T/ccrnqrPx.s:107: Error: value of 983040 too large for field of 2 bytes at 12

BUILD FAILED: //jsc:jsc#android-arm,compile-pic-JavaScriptCore_bytecode_CallLinkInfo.cpp.o failed with exit code 1:
c++ piped_preprocess_and_compile
[-] PROCESSING BUCK FILES...FINISHED 0.3s
[-] DOWNLOADING... (0.00 B/S AVG, TOTAL: 0.00 B, 0 Artifacts)
[-] BUILDING...FINISHED 18.7s [100%](1258/2589 JOBS, 27 UPDATED, 1.0% CACHE MISS)

**Comment by Ray-Ni** [comment]
for more detail:

I use buck to build android-jsc project:
https://github.com/facebook/android-jsc

after I change the support platform in jsc/BUCK,

it show above error message

**Comment by yiding** [comment]
Might want to use -v 9 and/or look into the buck-out/log and buck-out/log/traces to get the actual command line that's used.
