### ISSUE TITLE
java_binary from Scala code bundles compiler and library

### ISSUE THREAD

**Issue by mrkane27** [facebook/buck#692]
I've tried writing a simple test project with one `scala_library` and one `java_binary` depending on it. The resulting jar bundles the Scala compiler and library, and its manifest seems to suggest it's a bundle as well. @mikekap, I wonder whether this always has to be the case.

My use for Scala is in a project where the Scala library is made available, so bundling it in every jar we build won't help. Would it be possible, in theory, to have `scala_library` reference the Scala compiler and library jars as `provided_deps`?

**Comment by mikekap** [comment]
The compiler is definitely a mistake and shouldn't be there. We should remove it from the class path deps - it's only needed as a compile time dep.

As for the scala library itself - I don't think buck can claim to make uber jars if said jars require you to have scala installed. We could make a scala_binary that does what you're describing, but Java binaries are meant to be run via java -jar, and excluding the scala library would break that.

You can however mark the scala library target as provided (undocumented option on prebuilt_jar) - that might work. Just be aware you would lose the ability to use java_binary targets in genrules if you just use $(exe).

**Comment by mrkane27** [comment]
Ah, thanks for clarifying. I was wrong about the compiler, it's not actually bundled (I just looked for `scala.tools.nsc.Main` in my jar and it wasn't there. Thanks for the tips on the library. I'll close this off.

**Comment by mikekap** [comment]
If you're interested in contributing, improving the docs around this might be awesome. :)
