### ISSUE TITLE
Are there any way to force rebuild specific build_rule?

### ISSUE THREAD

**Issue by achieverForever** [facebook/buck#703]
I want to force rebuild a specific rule, such that a snapshot dependency can be fetched in every incremental build. Are there any way to do this? (By the way, I found that even I modified the RULEKEY in meta/ directory, it won't trigger a cache miss in dependent build targets! )

**Comment by Coneko** [comment]
There isn't. Specifically remote files are assumed to be immutable, which is why they have the md5 attribute.
