### ISSUE TITLE
apple_asset_catalog has no way to specify app icon or launch image

### ISSUE THREAD

**Issue by rmaz** [facebook/buck#711]
It is the default to put app icons and launch images in an assets catalog. Currently which images to use are defined in the Xcode project file, and are passed to actool like:

```
actool --app-icon AppIcon --launch-image LaunchImage --compress-pngs --enable-on-demand-resources YES --filter-for-device-model iPhone7,2 --filter-for-device-os-version 9.2 --target-device iphone --minimum-deployment-target 8.0 --platform iphonesimulator --compile Images.xcassets
```

It would be great to add optional attributes to the `apple_asset_catalog` target to specify these images.

**Comment by beefon** [comment]
Now it is possible to specify these. Please refer to the updated docs, there are 2 new fields: `app_icon` and `launch_image`.
https://buckbuild.com/rule/apple_asset_catalog.html

**Comment by yiding** [comment]
Closed on behalf of @beefon
