### ISSUE TITLE
sh_binary is not documented on buckbuild.com

### ISSUE THREAD

**Issue by eljobe** [facebook/buck#713]
It seems like `sh_binary` is a pretty popular rule in the wild, but it isn't mentioned at all on the [documentation website](http://buckbuild.com).

**Comment by sdwilsh** [comment]
It also doesn't work at all on Windows today.  That would have to be fixed before we documented it.

**Comment by arjenroodselaar** [comment]
Instead of leaving something undocumented, can we add a note that mentions a lack of Windows support? That makes the rule at least more accessible on platforms other than Windows.

**Comment by v-jizhang** [comment]
It is documented now: https://buck.build/rule/sh_binary.html
