### ISSUE TITLE
Empty resource directory gives confusing error message

### ISSUE THREAD

**Issue by iainmerrick** [facebook/buck#72]
I created a BUCK file for some third-party code, and my android_resource rule failed with a weird error:

    BUILD FAILED: [...]#dummy_r_dot_java failed on step android-res-merge with an exception:
    java.io.FileNotFoundException: buck-out/gen/[...]/__res_text_symbols__/R.txt (No such file or directory)

I eventually figured out that the "res" directory didn't contain any files! Surely this shouldn't be an error -- just create an empty R.txt file.

If it remains an error (or warning) then the error message should be made much clearer.

**Comment by Coneko** [comment]
Thanks for the report, this has been fixed, Buck will now create an empty `R.txt`.
