### ISSUE TITLE
buck project does not have a concept of test resources

### ISSUE THREAD

**Issue by writeoncereadmany** [facebook/buck#723]
When building a project_config, there are two sets of roots: src_roots and test_roots. If we have test resources, these folders need to be put in test_roots: however that's not correct, it allows running source from them in the IDE which is just wrong. If we don't put them in test_roots they don't show up on the classpath.

I don't know if test resources are a universal concept between IDEs, but they do exist in IntelliJ, and the concept is recognised by BUCK in terms of building. A few approaches suggest themselves:

1) Adding a new concept to project_config to specify resources
2) Not using project_config to determine the output of buck project, but instead using the model of the project DAG built for regular builds, and adding the concept of resources to that (where available, eg when IntelliJ is the target of project)

I notice there is an option of --experimental-ij-generation - I don't know whether that still generates its output from project_config or if it uses the DAG, but it may be appropriate to scope this to that feature.

**Comment by Coneko** [comment]
`--experimental-ij-generation` ignores `project_config` entirely.

**Comment by Coneko** [comment]
cc @marcinkosiba, @alsutton

**Comment by jiangty-addepar** [comment]
we forked buck to add this a while ago; I guess we should try to push this upstream

https://github.com/Addepar/buck/commit/7350b59d49948b734492b062623e7c595774633a

**Comment by Coneko** [comment]
`project_config` doesn't exist anymore.
