### ISSUE TITLE
Go rules example with third party package?

### ISSUE THREAD

**Issue by raliste** [facebook/buck#733]
Buck for go is great, BUT, creating BUCK files manually for even the most common third party packages seems quite a hassle.

How could you use Buck (from the naive-developer point of view) with, say, `golang.org/x/oauth2`?

Could you provide examples?

**Comment by nemith** [comment]
Good question.  This could be documented better.  Buck should support two ways of handling third-party packages.

1) Use vendor directories.  Just like the go tool Buck will search up the path of your package for a directory called 'vendor' and automatically include it when looking for packages.  Vendor directories still require TARGET files!

2) You can set a global third-party directory with go.vendor_path config option: https://buckbuild.com/concept/buckconfig.html#go.vendor_path.  It works like the vendor directories where a TARGET file for each dep is required.

Right now it is up to you to download the packages, all dependencies and create the TARGET files or create a tool to do this (using go command as a reference)

Probably should leave this issue open to document the vendor directory behavior.

**Comment by raliste** [comment]
Thank you @nemith .

Would you consider to provide an official tool to create TARGET files? The bazel team is working on open sourcing `glaze`, Google's internal tool to create BUILD files for go packages.

Seems like a nice addition to `buck autodeps` https://buckbuild.com/command/autodeps.html

**Comment by EmielM** [comment]
Any news on this? What do you exactly mean by TARGET files?

Slightly off-topic: I'm also still looking for a good way to manage my go dependencies in a buck project (outside a GOPATH), ideally without checking in all the vendored libraries. There's a myriad of different go vendoring/dependency tools, but none seem to fit the bill.

**Comment by fho** [comment]
any updates? :-)

**Comment by vmagro** [comment]
I just wrote a simple tool to do this https://github.com/vmagro/go-buck-generator
It's a bit rough around the edges right now (see the TODO in the README) but it works for a lot of cases making the whole thing a lot less tedious

**Comment by mkaczanowski** [comment]
Closing it. Automation can be used to generate BUCK files (for example @vmagro project)
