### ISSUE TITLE
In java_library(),we used "com.google.android:android:4.4.4" and buck build failed.

### ISSUE THREAD

**Issue by sherryein** [facebook/buck#736]
trouble processing "java/io/DataInputStream.class":

Ill-advised or mistaken usage of a core class (java.\* or javax.*)
when not building a core library.

**Comment by kageiit** [comment]
This error is thrown by dx (only when building with buck, gradle builds just fine). I had a similar error with other core classes like DocumentBuilder and QName.class. You may have to repackage the jar after removing the classes dx complains about and try again. Rinse and repeat till dx is happy.
