### ISSUE TITLE
Tips/Steps For Building facebook/buck Project in IDE

### ISSUE THREAD

**Issue by danoz73** [facebook/buck#749]
I am running into some issues with Buck builds on an extremely large project, and in order to run tests I am building buck from source and examining the build process to understand my issues.

However, I am having trouble syncing the project in my IDE (tried Android Studio and Intellij Community 2016.1). Specifically, I am not sure how to sync some dependencies.

For example: In `DxStep.java`, I cannot import `import com.facebook.buck.step.ExecutionContext`. This file does not exist in the buck source on github. Is this part of some proprietary code that is not shared, or am I missing a dependency somewhere? Other paths that are not found include `com.facebook.buck.io.BuckPaths`, `com.facebook.buck.step.StepExecutionResult`, ... the list goes on. Thanks in advance.

**Comment by k21** [comment]
`ExecutionContext` is generated by [the Immutables library](http://immutables.github.io/) from `AbstractExecutionContext`. Using `Build -> Make Project` in IntelliJ should generate those sources and fix the issues you are seeing. Does that work for you?

**Comment by danoz73** [comment]
Awesome! That solved my issues.

Wow, so all these abstract classes are using annotations to then generate a bunch of boilerplate... I see now. Thanks again. Worth investigating further :)
