### ISSUE TITLE
Need a clean way to use genrule output as genrule input in a separate package

### ISSUE THREAD

**Issue by iainmerrick** [facebook/buck#75]
I'm trying to automate some build helper scripts with Buck:
- Package A contains a genrule() that creates some intermediate file
- Package B contains another genrule() that depends on it
- All of these genrules are created by macros in a separate DEFS file.

Unfortunately this doesn't seem to work in the general case.

genfile() doesn't help -- the docs say it only works within the same build file.

If I try to use A's genrule name, or its output, in B's genrule srcs, I get "java.lang.RuntimeException: Not an ordinary file".

Since A's genrule by definition outputs one file, Buck should be able to copy that file into an appropriate place when it finds it in B's genrule srcs.

**Comment by sdwilsh** [comment]
I think this addresses the issue, and the author hasn't responded in six months, so I'm going to close this.
