### ISSUE TITLE
Error running Buck on Cygwin

### ISSUE THREAD

**Issue by antnguyen** [facebook/buck#767]
I'm doing all these in Cygwin:
After I ran Ant to build Buck, and build successful, I ran
 `$ ./bin/buck --help`

and it shows
```
./bin/buck: line 2: $'\r': command not found
./bin/buck: line 14: syntax error: unexpected end of file 
```

**Comment by Coneko** [comment]
Sorry cygwin isn't really supported.

You can run buck on Windows with cmd or powershell.

**Comment by antnguyen** [comment]
I thought it's not supported on Windows?
When I ran `./bin/buck --help` in Windows cmd, it shows:
```
'.' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by sdwilsh** [comment]
I developed Buck for over a year on Windows.  We have a `.cmd` and a 
`.ps1` file in the `bin` folder to be able to run on Windows, and we 
have CI here on GitHub for PRs that run on Windows :)

**Comment by antnguyen** [comment]
Thank you for your help.

I checked in the bin folder, it has buck.ps1, but it doesn't have any .cmd
file.

Sorry I'm a beginner and not familiar with the terms. What do you mean by
Cl and PRs?

**Comment by sdwilsh** [comment]
Sorry, I meant a `.bat` file, not `.cmd`.

CI = continuous integration
PRs = pull requests
