### ISSUE TITLE
Can buck run in windows cmd?

### ISSUE THREAD

**Issue by antnguyen** [facebook/buck#768]
Coneko said buck is not supported on Cygwin, but can be run on Windows cmd.

When I ran `./bin/buck --help` in Windows cmd, it shows:
```

'.' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by marcinkosiba** [comment]
use the right slashes: `.\bin\buck --help`. The error you're seeing is windows thinking you want to run command `.` with options `/bin` and `/buck`
