### ISSUE TITLE
ndk_library doesn't build shared object file for x86_64 cpu_abis.

### ISSUE THREAD

**Issue by alishir** [facebook/buck#769]
While `[ndk]` section in `.buckconfig` files contains `cpu_abis = x86_64` the build command, `buck build //jni:jni` doesn't build `x86_64` compatible library.

Here is `.buckconfig`:

```
[alias]
    app = //apps/myapp:app
[java]
    src_roots = /java/
[project]
    default_android_manifest = //res/AndroidManifest.xml
[android]
    target = Google Inc.:Google APIs:23
[ndk]
    gcc_version = 4.9
    cpu_abis = x86_64
```

and here is `BUCK` file in `jni` directory:

```
ndk_library(
  name = 'jni',
  deps = [],
  flags = [],
  visibility = [ 'PUBLIC' ],
)
```

**Comment by marcinkosiba** [comment]
Can you elaborate on `doesn't build x86_64 compatible library.`?

**Comment by alishir** [comment]
It doesn't build any .so file for `x86-64` architecture. `buck-out/bin/jni/__libjni/libs/` directory only contains `armeabi` subdirectory and there is no `x86-64` related directory or .so file.

**Comment by v-jizhang** [comment]
Sorry we haven't update this issue for more than 3 years. At this point, we are closing this because it is quite out of date and it is not clear if the issue still exists. Please create a new one if you still see the problem. Thank you.
