### ISSUE TITLE
test --xml does not produce overview file if NoClassDefFoundError occurs

### ISSUE THREAD

**Issue by agoerler** [facebook/buck#77]
In a test, I was missing a dependency which lead to a NoClassDefFoundError.

When running the test with 

buck test --all --xml results.xml

the file results.xml is not written.

If I execute the tests without the option "--xml results.xml" I get individual result xml files, which properly report the NoClassDefFoundError.

If I fix the dependency, I get a proper results.xml file created.

**Comment by Coneko** [comment]
It works now.

I tested it by adding `throw new NoClassDefFoundError();` to `test/com/facebook/buck/ddplist/DdPlistTest.java`.

The xml file gets created both in `buck-out` without `--xml` and wherever `--xml` specifies with it.

Let us know if this is still an issue.
