### ISSUE TITLE
The PEX should be able to parse files

### ISSUE THREAD

**Issue by shs96c** [facebook/buck#770]
Without needing pathlib or pywatchman installed on the device, and without needing a source copy of Buck floating around. 

https://github.com/SeleniumHQ/buck/commit/b56a9522bcf2e29ba228eed682ba31d61ba443e3 contains a way of doing this using PackagedResource. We probably need to remove the definition of "path_to_pathlib_py" from the relevant source files.

**Comment by v-jizhang** [comment]
Sorry we never got back to this! At this point, we are closing this because it is quite out of date and it is not clear if the issue still exists. Please create a new one if you still see the problem. Thank you.
