### ISSUE TITLE
NDK r11c: Build failures using clang 3.8

### ISSUE THREAD

**Issue by lucidsheep** [facebook/buck#776]
Unfortunately, it seems that I'm still having issues getting NDK r11c working with the latest buck. GCC seems to be working but with Clang 3.8 I get this:

> 2016-06-13 16:39:16.131][error][command:1b4645e1-049d-4266-a9b0-f2d47bf1bb67][tid:472][com.facebook.buck.cli.Main] Uncaught exception at top level
> java.lang.IllegalStateException: /Users/kevin/android/android-ndk-r11c/toolchains/llvm-3.8/prebuilt/darwin-x86_64/bin/clang
>     at com.google.common.base.Preconditions.checkState(Preconditions.java:174)
>     at com.facebook.buck.android.NdkCxxPlatforms.getToolPath(NdkCxxPlatforms.java:577)
>     at com.facebook.buck.android.NdkCxxPlatforms.getCTool(NdkCxxPlatforms.java:627)
>     at com.facebook.buck.android.NdkCxxPlatforms.build(NdkCxxPlatforms.java:378)
>     at com.facebook.buck.android.NdkCxxPlatforms.getPlatforms(NdkCxxPlatforms.java:137)
>     at com.facebook.buck.android.NdkCxxPlatforms.getPlatforms(NdkCxxPlatforms.java:101)
>     at com.facebook.buck.rules.KnownBuildRuleTypes.createBuilder(KnownBuildRuleTypes.java:355)
>     at com.facebook.buck.rules.KnownBuildRuleTypes.createInstance(KnownBuildRuleTypes.java:231)
>     at com.facebook.buck.rules.KnownBuildRuleTypesFactory.create(KnownBuildRuleTypesFactory.java:49)
>     at com.facebook.buck.rules.Cell.<init>(Cell.java:121)
>     at com.facebook.buck.rules.Cell.createCell(Cell.java:180)
>     at com.facebook.buck.cli.Main.runMainWithExitCode(Main.java:805)
>     at com.facebook.buck.cli.Main.tryRunMainWithExitCode(Main.java:1505)
>     at com.facebook.buck.cli.Main.runMainThenExit(Main.java:1596)
>     at com.facebook.buck.cli.Main.nailMain(Main.java:1717)
>     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>     at java.lang.reflect.Method.invoke(Method.java:497)
>     at com.martiansoftware.nailgun.NGSession.run(NGSession.java:338)

I went into the ndk folder and changed the folder llvm to llvm-3.8 to see if that fixes anything. This let me get to the build stage, but then I got a ton of these errors:

`/Users/kevin/android/android-ndk-r11c/platforms/android-9/arch-arm/usr/include/malloc.h:50:3: error: unknown type name 'size_t'`

.buckconfig settings:

> [ndk]
>     ndk_version = 11.2.2725575
>     app_platform = android-9
>     cpu_abis = arm
>     compiler = clang
>     clang_version = 3.8
>     gcc_version = 4.9
>     cxx_runtime = libcxx

Buck version: 496908651018eb82111a64110b36031541cfdcd7

**Comment by v-jizhang** [comment]
Sorry we never got back to this! At this point, we are closing this because it is quite out of date and it is not clear if the issue still exists. Please create a new one if you still see the problem. Thank you.
