### ISSUE TITLE
[Improvement] ndk.compiler in .buckconfig should default to clang

### ISSUE THREAD

**Issue by lucidsheep** [facebook/buck#777]
In the release notes for NDK 11, Google 'strongly recommends' switching to clang and has marked GCC as deprecated. In future releases it's likely that GCC will be dropped entirely. Having buck default to clang would follow suit with these changes. Future releases may want to drop GCC entirely since that seems like the future for the NDK.

See https://developer.android.com/ndk/downloads/revision_history.html

**Comment by v-jizhang** [comment]
Sorry we never got back to this! At this point, we are closing this because it is quite out of date and it is not clear if the issue still exists. Please create a new one if you still see the problem. Thank you.
