### ISSUE TITLE
Issue with buck on Windows

### ISSUE THREAD

**Issue by castroflavio** [facebook/buck#778]
Hi. Not sure you guys will be able to help me but I'm having this annoying issue with buck on windows.

I already built buck and I can run it from the cmd or powershell.

now I see this error:

BUILD FAILED: //utils/junit:onlab-junit-osgi failed with exit code 1:
genrule
stderr: The filename or extension is too long.

I suppose this happens because of windows and I'm afraid there will be no easy way to fix it.

**Comment by sdwilsh** [comment]
You are pretty much out of luck here.  What might help you fix this is moving our source try to something higher in the directory tree (even the root).  IIRC, the max length of file names is 255 characters.

**Comment by castroflavio** [comment]
So, this guys claim I can increase the file name this way.

http://stackoverflow.com/questions/27680647/does-max-path-issue-still-exists-in-windows-10

But then, the next question is what faced the error, how can I add/edit a manifest file for it.

For example, if it was python, Can I link a manifest file to python itself

**Comment by sdwilsh** [comment]
I don't think I understand what you are asking.  Can you try to elaborate?
