### ISSUE TITLE
BUNDLE_LOADER is not set correctly when testing bundle with different PRODUCT_NAME

### ISSUE THREAD

**Issue by rmaz** [facebook/buck#781]
Setting the `product_name` attribute on an `apple_bundle` correctly sets the bundle name and executable, but any test targets of the bundle will incorrectly set their `BUNDLE_LOADER` setting to point to the `name` of the bundle instead of the `product_name`. eg

``` lang=python
apple_bundle(
  name = 'BossBundle',
  product_name = 'BossProduct',
  tests = [ ':Tests' ],
  ...
)
```

will generate a test target with:

```
BUNDLE_LOADER = $BUILT_PRODUCTS_DIR/./BossBundle.app/$(BUNDLE_LOADER_BUNDLE_STYLE_CONDITIONAL_$(CONTENTS_FOLDER_PATH:file:identifier))/BossBundle
```

instead of:

```
BUNDLE_LOADER = $BUILT_PRODUCTS_DIR/./BossProduct.app/$(BUNDLE_LOADER_BUNDLE_STYLE_CONDITIONAL_$(CONTENTS_FOLDER_PATH:file:identifier))/BossProduct
```

**Comment by v-jizhang** [comment]
Sorry we never got back to this! At this point, we are closing this because it is quite out of date and it is not clear if the issue still exists. Please create a new one if you still see the problem. Thank you.
