### ISSUE TITLE
Buck Intellij Plugin fails when configured buck binary does not exist

### ISSUE THREAD

**Issue by kageiit** [facebook/buck#784]
We create a symlink to the buck binary in each project and when the project undergoes a clean, the symlink is lost. When the intellij plugin is initially configured to look for buck at this path, it later fails with

```
ProcessNotCreatedException: Cannot run program "/Users/kage/src/test/buck" (in directory "/Users/kage/src/test"): error=2, No such file or directory
```

Ideally the binary would always exist, but in the case it does not, it is better to just show a warning instead of the plugin crashing (which is followed by an intellij prompt to disable the plugin)

**Comment by Coneko** [comment]
cc @cotizo, @cosmin1123

**Comment by cosmin1123** [comment]
Thank you!
I'll better handle that exception.

It shouldn't cause any real problems, but you won't be able to do install, build, project, etc from the plugin.
You can specify the correct path from:
"Preferences/Settings -> Tools -> Buck -> Buck Executable Path"
That suggestion should also be included in the error message.
