### ISSUE TITLE
Buck for IDEA threw an uncaught HumanReadableException

### ISSUE THREAD

**Issue by erva** [facebook/buck#786]
After install plugin and restart Android Studio. Os X Yosemite 10.10.5, Android Studio 2.1.2

**Comment by cosmin1123** [comment]
Can you provide more information?

What was the stack trace and message of the exception?
Was it in the Event Log of Android Studio?
Did Android Studio close?

If it's something about Buck or Adb then the exception is being handled and it tells you how to solve it.
You need to set the buck/adb path in "Preferences/Settings -> Tools -> Buck -> Buck Executable Path/ Adb Executable Path".

**Comment by ervinmartirosyan** [comment]
This error message appeared on "Welcome to Android Studio" on recent project list 
Screen: [http://imgur.com/rRThdi9](url)
Buck has not been installed yet, I have just added plugin

**Comment by kageiit** [comment]
Might be the same as #784

**Comment by ervinmartirosyan** [comment]
@kageiit seems you're right
