### ISSUE TITLE
Generated IntelliJ projects are unable to reference classes from Android prebuilt AAR dependencies.Generated IntelliJ projects are unable to reference classes from Android prebuilt AAR dependencies.

### ISSUE THREAD

**Issue by tonycosentini** [facebook/buck#792]
When generating a project for IntelliJ - classes imported from prebuilt AARs do not resolve properly.

This results in IDE errors like this:
<img width="415" alt="import" src="https://cloud.githubusercontent.com/assets/23467/16365971/c5e588a8-3bc3-11e6-867b-a02f089e04fd.png">

and a broken classpath error:
<img width="525" alt="screen shot 2016-06-24 at 5 51 44 pm" src="https://cloud.githubusercontent.com/assets/23467/16365973/cfa6a1e2-3bc3-11e6-99cf-af718e2f1cce.png">

Here is a sample project that reproduces this: 
[buck_sample.zip](https://github.com/facebook/buck/files/333917/buck_sample.zip)

**Comment by Coneko** [comment]
I think this is a known issue.

See also #795.

cc @marcinkosiba, @michath

**Comment by tonycosentini** [comment]
Going to close this as a duplicate to keep discussion in #795.
