### ISSUE TITLE
genrule() fails on pure Java projects

### ISSUE THREAD

**Issue by joewalnes** [facebook/buck#796]
I'm using Buck in a pure Java project, but `genrule` fails because it cannot find the Android SDK (which I don't have installed).

Example (from https://buckbuild.com/rule/export_file.html):

```python
export_file(
  name = 'example',
  src = 'example.html',
)

genrule(
  name = 'demo',
  out = 'result.html',
  cmd = 'cp $(location :example) $OUT',
)
```

```bash
$ buck build src/example:demo
No Android platform target specified. Using default: Google Inc.:Google APIs:23
[-] PROCESSING BUCK FILES...FINISHED 0.0s [100%]
[+] DOWNLOADING... (0.00 B/S, TOTAL: 0.00 B, 0 Artifacts)
[+] BUILDING...0.1s [100%] (2/2 JOBS, 1 UPDATED, 50.0% CACHE MISS)
 |=> IDLE
 |=> IDLE
 |=> IDLE
 |=> IDLE
BUILD FAILED: Google APIs not found in /usr/local/opt/android-sdk/add-ons/addon-google_apis-google-23/libs.
Please run '/usr/local/opt/android-sdk/tools/android sdk' and select both 'SDK Platform' and 'Google APIs' under Android (API 23)
```

Using `buck version v2016.03.28.01` (installed via brew)

**Comment by marcinkosiba** [comment]
the problem is that you have either set an android sdk version in your .buckconfig or have one of the ANDROID_* environment variables set.

**Comment by joewalnes** [comment]
Ahh it seems that I have ANDROID_HOME set. That fixed it. Thank you.

But this is still a usability hurdle. I now have to explicitly clear ANDROID_HOME for all pure Java projects in case one developer happens to have the SDK installed.

**Comment by Coneko** [comment]
I thought the SDKs are now checked only if you build android. cc @michath
