### ISSUE TITLE
Store submission fails with iCloud entitlements

### ISSUE THREAD

**Issue by rmaz** [facebook/buck#798]
When a provisioning profile has iCloud entitlements enabled, the buck signed binary will not pass store submission. A typical iCloud provisioning profile will have entitlements similar to:

```lang=xml
<key>Entitlements</key>
<dict>
    <key>keychain-access-groups</key>
    <array>
        <string>4ZX4Z3MVHG.*</string>
    </array>
    <key>application-identifier</key>
    <string>4ZX4Z3MVHG.com.appleseedinc.MyProject</string>
    <key>com.apple.developer.ubiquity-kvstore-identifier</key>
    <string>4ZX4Z3MVHG.*</string>
    <key>com.apple.developer.icloud-services</key>
    <string>*</string>
    <key>com.apple.developer.icloud-container-environment</key>
    <array>
        <string>Development</string>
        <string>Production</string>
    </array>
    <key>com.apple.developer.icloud-container-identifiers</key>
    <array>
        <string>iCloud.com.appleseedinc.MyProject</string>
        <string>iCloud.com.appleseedinc.container1</string>
    </array>
    <key>com.apple.developer.icloud-container-development-container-identifiers</key>
    <array>
        <string>iCloud.com.appleseedinc.MyProject</string>
        <string>iCloud.com.appleseedinc.container1</string>
    </array>
    <key>com.apple.developer.ubiquity-container-identifiers</key>
    <array>
        <string>iCloud.com.appleseedinc.MyProject</string>
        <string>iCloud.com.appleseedinc.container1</string>
    </array>
    <key>com.apple.developer.team-identifier</key>
    <string>4ZX4Z3MVHG</string>
    <key>aps-environment</key>
    <string>production</string>
</dict>
```

The default entitlements handling in buck will combine the specified entitlements file with the entitlements in the provisioning profile. This will result in both the `com.apple.developer.icloud-container-development-container-identifiers` and `com.apple.developer.ubiquity-kvstore-identifier` keys being added to the signing entitlements. Trying to submit a binary with either of these present will result in the following iTunes store errors:

```
ERROR ITMS-90045: "Invalid Code Signing Entitlements. Your application bundle's signature contains code signing entitlements that are not supported on iOS. Specifically, key com.apple.developer.icloud-container-development-container-identifiers in Payload/Blah.app is not supported."
```

and:

```
ERROR ITMS-90211: Invalid Code Signing Entitlements. The signature for your app bundle contains entitlement values that are not supported. For the com.apple.developer.ubiquity-kvstore-identifier entitlement, the value must start with the prefix provided by Apple in the provisioning profile, followed by characters that are uppercase or lowercase Roman letters [A-Z, a-z], the digits 0 through 9, dot, or hyphen, and not contain any wildcard characters. Specifically, value 4ZX4Z3MVHG.* for the key com.apple.developer.ubiquity-kvstore-identifier in Payload/Blah.app is not supported.
```
 
I'm not sure where the behaviour of merging the entitlements came from, is this mirroring what Xcode would do? It seems more correct to not merge the entitlements, would this result in a different error though, do we always need to merge certain keys from the provisioning profile?

**Comment by rmaz** [comment]
I've done a bit of digging on this, it does appear that Xcode uses a similar approach with a blacklist of keys not to merge into the entitlements file. The list seems to include:

```
com.apple.developer.icloud-container-development-container-identifiers
com.apple.developer.icloud-container-environment
com.apple.developer.icloud-container-identifiers
com.apple.developer.icloud-services
com.apple.developer.restricted-resource-mode
com.apple.developer.ubiquity-container-identifiers
com.apple.developer.ubiquity-kvstore-identifier
inter-app-audio
com.apple.developer.homekit
com.apple.developer.healthkit
com.apple.developer.in-app-payments
com.apple.developer.associated-domains
com.apple.security.application-groups
com.apple.developer.maps
com.apple.developer.networking.vpn.api
com.apple.external-accessory.wireless-configuration
```

The behaviour is complex enough that it seems pretty risky trying to replicate it inside buck itself. Perhaps a wrapper around the system entitlements merging code is the best approach here?

**Comment by ryu2** [comment]
@rmaz I looked into this, but the entitlements processing seems to be happens in a step called `ProcessProductPackaging` in Xcode.  This doesn't seem to be cleanly exposed for external consumption (e.g. as a command-line tool).

**Comment by rmaz** [comment]
Yes, this is unfortunate. I have tracked down the class that does most of the heavy lifting, it is in an Xcode framework: https://github.com/luisobo/Xcode-RuntimeHeaders/blob/master/IDEFoundation/IDEArchivePackagerEntitlementsMerger.h

So the options we have are:
- Wrap this framework in a command line tool that we optionally build when we have a Mac host
- Reimplement its logic in buck

I was leaning towards the first approach and using JNI to invoke the framework, but this seems to be impossible due to the way that the rpath has been setup for the framework, it would require manually loading every single dependent framework as it seems runpath search flags are not correctly passed down to the JNI framework. Wrapping this in a C tool is still an option, and probably the safest course if a bit fiddly.

Otherwise we just work out what it is doing and replicate the logic, but it is unfortunately doing quite a lot more than you would expect, including adding in defaults, replacing wildcards, blacklisting a whole bunch of keys (which presumably change with every tooling upgrade) and doing some verification of some of the keys.

I think in the short term we should take the second approach and look to make this more solid down the line, thoughts?

**Comment by sdwilsh** [comment]
Currently you can build Buck on any platform and it should run on any 
other platform (there are no binary components).  It'd be unfortunate if 
we had to regress that.

Aside: we use JNA in Buck today, but I'm not sure that makes things any 
easier.

**Comment by ryu2** [comment]
I agree the second approach is better as (platform considerations aside) depending on a private interface is something I'd like only as a last resort.

Either way, we're susceptible to Apple's changes.  The second approach where we do our own  implementation is advantageous in that any future breakage is more visible and presumably easier to fix.

As a side note In the longer term, we're moving away from hard-coding things like this in Java and moving more towards Python for the execution of the build steps themselves.

**Comment by rmaz** [comment]
OK, I added a blacklist to filter out invalid keys for now. There is also some validation behaviour that I left out, but from what I can tell this is to do with `$(TeamIdentifier)` variable substitution that doesn't work with buck anyway, so seems safe to leave out for now.
