### ISSUE TITLE
No rule found when resolving target

### ISSUE THREAD

**Issue by Shaunchenzhaojin** [facebook/buck#801]
I install buck on my Mac, and copy my project to the //ios. There is a error occur:
BUILD FAILED: No rule found when resolving target //ios:LoveFreshBeen in build file //ios/BUCK
Defined in file: /Users/build/my-project/ios/BUCK

**Comment by sdwilsh** [comment]
Do you have something referencing `:LoveFreshBeen`?

**Comment by Shaunchenzhaojin** [comment]
That is the problem I don`t know how to referencing that. If you can offer some detail steps? THX!
