### ISSUE TITLE
IntelliJ plugin does not recognize build failures, cannot be stopped

### ISSUE THREAD

**Issue by ZacSweers** [facebook/buck#804]
This has been a super frustrating issue. When running a build, the following two issues can occur:
- The build cannot be stopped. It continues to run regardless of clicking the "X" button on the indicator in the gutter.
- It does not recognize when builds have failed. It continues to "run", though not clear what it's doing.

Eventually, things "finish" and stop. It's not really clear what's going on under the hood though. Happy to provide logs if I can get some direction on where to look.

**Comment by k21** [comment]
@cosmin1123, can you please take a look?

**Comment by kageiit** [comment]
@k21 @cosmin1123 any updates on this?

**Comment by lowellk** [comment]
Same happening to me.

**Comment by v-jizhang** [comment]
Sorry we never got back to this! At this point, we are closing this because it is quite out of date and it is not clear if the issue still exists. Please create a new one if you still see the problem. Thank you.
