### ISSUE TITLE
Support AppCode for running unit tests

### ISSUE THREAD

**Issue by lyahdav** [facebook/buck#806]
I filed a bug with JetBrains to make it so that Buck generated Xcode projects work correctly with AppCode: https://youtrack.jetbrains.com/issue/OC-13916. Currently in AppCode you cannot run test suites from Buck projects because AppCode doesn't support some of the hacks here:
https://github.com/facebook/buck/blob/2fda51d104cfa6a515fe8bf5a5096f8c7acfdf22/src/com/facebook/buck/apple/project_generator/ProjectGenerator.java#L1246
Ideally this wouldn't require hacks. Why is it that regular Xcode projects never have to do this hack? Isn't there another way to determine the platform of the current target? For example, couldn't you check the base SDK setting of the target under test?

**Comment by Coneko** [comment]
I don't remember the whole story behind that hack, but there are some differences in how Xcode and Buck see targets because for Xcode a target can only be built for a certain platform, but Buck can build them for any platform (macOS vs iOS for example).

**Comment by lyahdav** [comment]
Maybe there should be a way to override the behavior of not specifying a
platform and explicitly specify a platform in which case it would set the
bundle loader to the platform default which would resolve the issue for
AppCode?

**Comment by v-jizhang** [comment]
Sorry we haven't update this issue for more than 3 years. At this point, we are closing this because it is quite out of date and it is not clear if the issue still exists. Please create a new one if you still see the problem. Thank you.
