### ISSUE TITLE
Resources of precompiled aar libraries cannot be used in app code

### ISSUE THREAD

**Issue by hschottm** [facebook/buck#808]
Using resources of precompiled aar libraries in the source code doesn't work. The build process always throws a resource not found error.

Maybe I am not adding the aar libraries correctly to my project. I am using the android_prebuilt_aar build rule.

I [linked an example project](https://dl.dropboxusercontent.com/u/363242/AARTestCase.zip) to reproduce the compile errors.

The code fragment

``` java
FrameLayout customView = (FrameLayout) dialog.getView().findViewById(com.afollestad.materialdialogs.R.id.customViewFrame);
FrameLayout.LayoutParams params = new FrameLayout.LayoutParams(FrameLayout.LayoutParams.WRAP_CONTENT, FrameLayout.LayoutParams.WRAP_CONTENT);
params.gravity = Gravity.CENTER;
ProgressView progressView = new ProgressView(this);
progressView.setPadding(15, 15, 15, 15);
progressView.setProgressText("Progress...");
progressView.setBackgroundColor(Color.rgb(230, 230, 230));
customView.addView(progressView, params);

```

uses a resource ID `R.id.customViewFrame` of the aar library com.afollestad.materialdialogs which is added to the project with the android_prebuilt_aar rule. If you comment out this code block, the compiler runs and installs the app on the device without an error, so the aar-library must be added correctly to the project. It seems that only the resources are not made available for the main app.

I am using the latest buck release 732df36cc36c66e6287a91d76045cf11ac84f6b6 from github

**Comment by marcinkosiba** [comment]
yeath, so it looks like exported_deps are broken in this case. I think it's because AndroidLibraryGraphEnhancer.getBuildableForAndroidResources filters directly on first-order deps instead of filtering on an expanded set.

If you change the code to be this:

```
android_library(
   name = 'main-lib',
   srcs = glob(['src/main/java/**/*.java']),
   deps = [
     ':build-config',
     ':jars__buck-android-support',
     ':all-jars',
     ':all-aars', # <-- This is partially broken, sorry.
     ':res',
   ]  + aar_deps,  # <-- Depend on the prebuilt aar targets *directly*
)
```

it compiles fine.

**Comment by hschottm** [comment]
Great, thanks for the info

**Comment by GunNan** [comment]
Hi, I have a same problem, and I have change my Buck file follow the comment. However, it seems do not work for my project.

Buck file: 

```
import re

aar_deps = []
for aarfile in glob(['libs/**/*.aar']):
  name = 'aars__' + re.sub(r'^.*/([^/]+)\.aar$', r'\1', aarfile)
  aar_deps.append(':' + name)

  android_prebuilt_aar(
    name = name,
    aar = aarfile,
  )

android_library(
  name = 'all-javas',
  srcs = glob([
  'ext/**/*.java',
  'wns/**/*.java',
  'src/**/*.java',
  'upload/**/*.java']),
  deps = [
    ':res',
    ':all-jars',
    ':all_native_libs',
    ':protocol',
  ] + aar_deps,
)

# ...
# ...
# ...
```

And here is my Exception:

`java.lang.RuntimeException: Unable to start activity ComponentInfo{com.tencent.karaoke/com.tencent.karaoke.module.main.ui.MainTabActivity}: android.content.res.Resources$NotFoundException: File res/drawable/abc_ic_ab_back_material.xml from drawable resource ID #0x7f020013`

And the code is:

import android.support.v7.app;

public class MainTabActivity extends AppCompatActivity{
    @Override
    protected void onCreate(Bundle savedInstanceState) {
       super.onCreate(savedInstanceState);
       //....
    }
}

Thanks!

**Comment by GunNan** [comment]
@hschottm Could you please help me? Thanks.
