### ISSUE TITLE
Genrule output cannot be used in apple_resource input

### ISSUE THREAD

**Issue by rmaz** [facebook/buck#809]
Using genrule output as a dir input for an apple_resource target will fail to install the application with a symlink related error:

```
Jul 18 14:53:47 installd[64861]: 0x700000094000 -[MIFileManager realPathForURL:ifChildOfURL:]: Rejecting /Users/blah/Library/Developer/CoreSimulator/Devices/F6DB046F-414E-43D2-9F19-A6CAC65E512C/data/Library/Caches/com.apple.mobile.installd.staging/temp.dVnM8p/extracted/MyApp.app/GenruleResources.bundle -> /Users/blah/path/to/code/GenruleResources.bundle, as absolute symlinks are not allowed
```

The genrule output needs to be copied into the staging app bundle to install correctly.

**Comment by alanzeino** [comment]
Just encountered this problem. Wanted to have a `remote_file` download a file, then have an `apple_resource` add that file to the project as a dep on the `apple_binary`.

**Comment by Coneko** [comment]
That's strange, I don't think `genrule`, `apple_resource` or `remote_file` do anything with symlinks.

I'll try to repro.

**Comment by alanzeino** [comment]
@v-jizhang is it fixed?

**Comment by v-jizhang** [comment]
@alanzeino This issue is closed because there is no updates for more than 3 years.
