### ISSUE TITLE
Use the LinearAlloc heuristic instead of just class size to decide what goes into secondary dex during exopackage

### ISSUE THREAD

**Issue by kageiit** [facebook/buck#815]

**Comment by dreiss** [comment]
For context, this affects debug builds and exopackage.

**Comment by kageiit** [comment]
Followup for #814

**Comment by v-jizhang** [comment]
Sorry we never got back to this! At this point, we are closing this because it is quite out of date and it is not clear if the issue still exists. Please create a new one if you still see the problem. Thank you.
