### ISSUE TITLE
Styleable entries in R.txt and R.java is not generated correctly for libraries.

### ISSUE THREAD

**Issue by raviagarwal7** [facebook/buck#816]
**R.java generated when running with buck:**

```
public static class attr {
    public static final int popupTheme=0x07f010b0;

    public static final int floatingLabelLabelText=0x07f015ea;
    public static final int floatingLabelLabelTextAppearance=0x07f015eb;
    public static final int floatingLabelStartingText=0x07f015ec;
    ...
}

public static class styleable {
    public static final int[] Spinner={  };
    public static final int Spinner_android_dropDownWidth=3;
    public static final int Spinner_android_entries=0;
    public static final int Spinner_android_popupBackground=1;
    public static final int Spinner_android_prompt=2;
    public static final int Spinner_popupTheme=4;

    public static final int[] FloatingLabelEditText={ 0x7f060003,0x7f060004,0x7f060005,0x7f060006,0x7f060007,0x7f060008,0x7f060009,0x7f06000a,0x7f06000b,0x7f06000c,0x7f06000d,0x7f06000e,0x7f06000f,0x7f060010,0x7f060011,0x7f060012,0x7f060013,0x7f060014,0x7f060015,0x7f060016,0x7f060017,0x7f060018,0x7f060019,0x7f06001a,0x7f06001b,0x7f06001c,0x7f06001d };
    public static final int FloatingLabelEditText_android_enabled=23;
    public static final int FloatingLabelEditText_android_imeActionId=25;
    ...
    public static final int FloatingLabelEditText_floatingLabelLabelText=0;
    public static final int FloatingLabelEditText_floatingLabelLabelTextAppearance=3;
    public static final int FloatingLabelEditText_floatingLabelStartingText=1;
    ...
}
```

**R.java generated when running with gradle:**

```
public static final class attr {
    public static final int popupTheme=0x7f010034;

    public static int floatingLabelLabelText=0x7f0100f7;
    public static int floatingLabelLabelTextAppearance=0x7f0100fa;
    public static int floatingLabelStartingText=0x7f0100f8;
    ...
}

public static final class styleable {

    public static final int[] Spinner = {
        0x010100b2, 0x01010176, 0x0101017b, 0x01010262, 0x7f010034
    };

    public static int Spinner_android_dropDownWidth = 3;
    public static int Spinner_android_entries = 0;
    public static int Spinner_android_popupBackground = 1;
    public static int Spinner_android_prompt = 2;
    public static int Spinner_popupTheme = 4;   


    public static final int[] FloatingLabelEditText = {
        0x0101000e, 0x010100e1, 0x010100e2, 0x010100e3,
        0x010100e4, 0x01010153, 0x0101015d, 0x01010160,
        0x01010220, 0x01010264, 0x01010265, 0x01010266,
        0x0101033c, 0x7f0100f7, 0x7f0100f8, 0x7f0100f9,
        0x7f0100fa, 0x7f0100fb, 0x7f0100fc, 0x7f0100fd,
        0x7f0100fe, 0x7f0100ff, 0x7f010100, 0x7f010101,
        0x7f010102, 0x7f010103, 0x7f010104
    };
    public static int FloatingLabelEditText_android_enabled = 0;
    public static int FloatingLabelEditText_android_imeActionId = 11;
    ...
    public static int FloatingLabelEditText_floatingLabelLabelText = 13;
    public static int FloatingLabelEditText_floatingLabelLabelTextAppearance = 16;
    public static int FloatingLabelEditText_floatingLabelStartingText = 14;
    ...

}
```

Some comments from the generated R.java when running with gradle.

> This symbol is the offset where the {@link android.R.attr#dropDownWidth}  attribute's value can be found in the {@link #Spinner} array.
> @attr name android:dropDownWidth
> **public static int Spinner_android_dropDownWidth = 3;**
> 
> This symbol is the offset where the {@link com.floating.label.R.attr#floatingLabelLabelTextAppearance}
> attribute's value can be found in the {@link #FloatingLabelEditText} array.
> **public static int FloatingLabelEditText_floatingLabelLabelText = 13;**

**Issues:**
- Styleable array is missing values.
- If the `attr` is present in the same R.java the styleable array index at attr's offset should have the same integer value as attr's value.
-  If the `attr` is from the android R.java the styleable array index at attr's offset should have the same integer value as attr's value in android R.java.

eg:

```
public static class attr {
    public static final int popupTheme=0x07f010b0;
}

public static class styleable {
    public static final int[] Spinner={ 
            < from android R.java>, 
            < from android R.java>, 
            < from android R.java>, 
            < from android R.java>, 
            0x07f010b0
        };
    public static final int Spinner_android_dropDownWidth=3;
    public static final int Spinner_android_entries=0;
    public static final int Spinner_android_popupBackground=1;
    public static final int Spinner_android_prompt=2;
    public static final int Spinner_popupTheme=4;
```

**Case where it fails with Robolectric**

```
Attribute attribute = new Attribute("android:attr/inputType", "number", "com.floating.label.test");
List<Attribute> attributeList = new ArrayList<>();
attributeList.add(attribute);

ResourceLoader resourceLoader = new CoreShadowsAdapter().getResourceLoader();
AttributeSet attributeSet = new RoboAttributeSet(attributeList, resourceLoader);
Resources.Theme theme = RuntimeEnvironment.application.getTheme();
TypedArray typedArray = theme.obtainStyledAttributes(
        attributeSet,
        R.styleable.FloatingLabelEditText,
        R.attr.floatingLabelStyle,
        0);

assertThat(typedArray.getIndexCount()).isEqualTo(1); // returns 0 when run with buck
```

test_attrs.xml

```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <declare-styleable name="FloatingLabelEditText">
        <attr name="floatingLabelStyle" format="reference"/>

        <attr name="floatingLabelLabelText" format="string"/>
        <attr name="floatingLabelStartingText" format="string"/>
        <attr name="floatingLabelHintText" format="string"/>

        ...
    </declare-styleable>
</resources>
```

Not sure how we can get the attr's values present in android's R.java when generating R.txt or R.java as R.txt is now generated by [MiniAapt](https://github.com/facebook/buck/blob/master/src/com/facebook/buck/android/aapt/MiniAapt.java#L62) instead of `aapt`.

We can probably do it at  [MergeAndroidResourceStep](https://github.com/facebook/buck/blob/master/src/com/facebook/buck/android/MergeAndroidResourcesStep.java#L315) when generating merged R.java instead of duplicating it when generating R.txt as the values anyways changes on merging.

Some relevant [comment](https://github.com/facebook/buck/blob/master/src/com/facebook/buck/android/MergeAndroidResourcesStep.java#L353) about why styleable are not genered correctly.

**Note:** R.txt and R.java is generated correctly for Apps as they get overridden by [uberRDotTxt](https://github.com/facebook/buck/blob/master/src/com/facebook/buck/android/MergeAndroidResourcesStep.java#L192)

**Comment by marcinkosiba** [comment]
Just to be clear (since you mentioned R.txt): for robolectric, we don't have an R.txt as that file is created by running aapt. The values in the R.java file are dummy placeholders. Using aapt for robolectric_test is not acceptable as it would introduce too much overhead.

It's been a long time since I looked at that code. Last I looked robolectric 2 resource loader didn't support styleable correctly, not sure if that changed with robolectric 3. I'm not sure whether it's just the MergeAndroidResources that's broken or whether MiniAapt also needs to be fixed to correctly emit the right styleable entries, but fixing either (or both) of those to correctly support the case would be the preferred approach.

**Comment by raviagarwal7** [comment]
I agree using aapt would be too slow. 

Yes, robolectric 3 resource loader supports styleable now. (we have been using robolectric 3 for a while now). 

Fixing MiniApt would not really help as we will have to modify the values again at MergeAndroidResources step. We only care about entry names from miniAapt which is being returned correctly. Fixing it in MergeAndroidResources would suffice.

I will work on getting the Styleable entries fixed which has base attributes in the same R.java file.

Not sure how to get the attr values which comes from `android.R.java` (some styleable entries depend on it). We can either ignore them or just assign random values to it.

**Comment by marcinkosiba** [comment]
> Fixing MiniApt would not really help as we will have to modify the values again at MergeAndroidResources step.

True. I thought you might need the number of styleable entries in the array, which sounds like information that should be generated by MiniAapt. If you can sort it all out at the MergeAndroidResources step that's fine.

> Not sure how to get the attr values which comes from android.R.java
> We can either ignore them or just assign random values to it.

Whatever works for robolectric :) I think the IDs for `android.R` are effectively hardcoded constants (as they come from the framework), but the SDK doesn't ship with an R.txt (at least I couldn't find one), so if these need to be an exact match then we might have to resort to having a step that reads the SDK jar and generates an R.txt from the R.java (or something along those lines).

**Comment by raviagarwal7** [comment]
This is fixed now:

https://github.com/facebook/buck/pull/879
https://github.com/facebook/buck/pull/1068
