### ISSUE TITLE
Buck Intellij Plugin latest version is not compatible with Intellij 2016.2

### ISSUE THREAD

**Issue by kageiit** [facebook/buck#817]
Only 2.03 of the buck plugin seems to be compatible with the newer intellij version. Unable to install the latest version when browsing the plugin repositories

**Comment by kageiit** [comment]
cc @cosmin1123

**Comment by kageiit** [comment]
The listing confirms it too https://plugins.jetbrains.com/plugin/7826?pr=idea

It is listed as compatible with 139-147. But the current plugin.xml on master is compatible with 162.*

**Comment by mkillianey** [comment]
Now available as 2.7.1, see here: https://plugins.jetbrains.com/plugin/7826?pr=idea
