### ISSUE TITLE
Using BUCK set ProGuard library jars

### ISSUE THREAD

**Issue by hitYOUcry** [facebook/buck#822]
Well,I'm using buck to rebuild my pro. Now when I want to ProGuard the release code I get some trouble.

My lib jars in the project has: 
          zxing-core.jar  
          wup.jar
          libammsdk.jar
          jg_filter_sdk_1.0.jar

The proguard args used by Ant is like that:
             value="-injars ${lib}/zxing-core.jar"
             value="-outjars obfuscated.jar"
             value="-libraryjars ${androidjar}"
             value="-libraryjars ${lib}/wup.jar"
             value="-libraryjars ${lib}/libammsdk.jar"
             value="-libraryjars ${lib}/jg_filter_sdk_1.0.jar"

 There  -injars, -outjars and -libraryjars .
While,when I looking the proguard log gen by buck, I found out that buck will regards all the lib jars as -injars(mReading program jar ...),  

![image](https://cloud.githubusercontent.com/assets/11732730/17205398/816dc9f0-54dd-11e6-9e91-c76668e38801.png)
Consider there are difference between -injars and -libraryjar, How can I config my BUCK file to specific some lib jars as -libraryjars?

(P.s. when I set those config in my proguard file ,buck will find class duplicate ,because no matter what I config in the  proguard file ,buck will reading lib jars as -injars.)

**Comment by hitYOUcry** [comment]
sry ,the mid Ant ProGuard args  seems missing, It's soming like that:
            value="-injars ${lib}/zxing-core.jar"
            value="-outjars obfuscated.jar"
            value="-libraryjars ${lib}/wup.jar"
            value="-libraryjars ${lib}/libammsdk.jar"
            value="-libraryjars ${lib}/jg_filter_sdk_1.0.jar"

**Comment by marcinkosiba** [comment]
buck only puts the 'no_dx' rules on the -libraryjars, however that also removes the .jar from the final .apk
You can instruct proguard to not touch the code from your external .jars by passing the appropriate -keep option as per http://stackoverflow.com/questions/4475074/how-can-i-exclude-external-jar-from-obfuscation-by-proguard-android-project
Does that answer your question?

**Comment by hitYOUcry** [comment]
Thank you, it help me a lot to understand proguard settings in BUCK build project.
I will try it in My pro.
