### ISSUE TITLE
Build Release  smart_dex not stopping(or failed more common)

### ISSUE THREAD

**Issue by hitYOUcry** [facebook/buck#823]
I use buck to build my pro .The debug version is OK ,when I add ProGuard to build the release version I meet some problems.

It usually build failed by GC overhead limit exceeded(OOM,  my .configjavaargs file have set -Xmx8g)
Now  it just running and don't stop,I don't kown what to do with it. 
![image](https://cloud.githubusercontent.com/assets/11732730/17206560/f2f00994-54e2-11e6-987c-245b58bc22b3.png)

(Just now,it failed with 610.9s....,with the error OutOfMemory : Java heap space)

**Comment by hitYOUcry** [comment]
。。。I remove the  **use_linear_alloc_split_dex = True** in rule android_binary(),It works fine , but if I don't use **use_split_dex=True**  build failed again. This is odd.

**Comment by marcinkosiba** [comment]
300 seconds in smart dexing seems like a lot. How big is the final .apk? Are you enabling xz compression?

**Comment by hitYOUcry** [comment]
The final APK is not very big(8-9MB).  xz  compression isn't enabled ,I haven't see this parameter.

**Comment by ldjhust** [comment]
Hi @hitYOUcry @marcinkosiba , does this problem has already sloved? I just have the same problem

Thank you

**Comment by hitYOUcry** [comment]
@ldjhust ，I remember I just removed the **use_linear_alloc_split_dex = True** in rule android_binary() than it worked fine like I said before.If it doesn't work for you,I recommend you review your ProGuard file and the split dex strategy.

**Comment by ldjhust** [comment]
OK, thanks very much, I'll try it.
