### ISSUE TITLE
Not re-running tests when java_test deps change

### ISSUE THREAD

**Issue by mread** [facebook/buck#827]
Hi, my scenario is that I'm adding an entry to a java_test's deps due to a runtime test failure. This is not triggering a re-run of the tests with the new classpath, instead the tests run with the same classpath as before the change.

The work-around is to make an artificial change to a source file to force a recompile of the test classes which will then re-run the tests.

**Comment by marcinkosiba** [comment]
this is a KP, we have a diff up for fixing it internally

**Comment by mread** [comment]
Awesome, let me know if I can help test your patch.

**Comment by mread** [comment]
Hi, you've no doubt got your own priorities but if I could possible help with getting this fix in the please let me know. We're doing a massive migration to Buck and rebuilding classpaths by hand and this issue is really slowing us down. It also gets a lot of wtfs from people when they encounter it for the first time which isn't helping me sell Buck :)

**Comment by mread** [comment]
Looks like this commit introduces the problem 550bbe1de1e4c263056425b57b372eef5df09f86

**Comment by mikekap** [comment]
If that is indeed the commit responsible, you may be able to fix it by setting `java.track_class_usage=false`, e.g.
```
buck test --config java.track_class_usage=false
```
or putting it into `.buckconfig`.

**Comment by mread** [comment]
Thanks, that appears to fix it.

It's also fixed in master somewhere in early Sept, I think between these 2 commits - 090ecd66530504e9e7346dc040ffe1b65319c1a9 and d08ca157b4489cfe7f3f19f0a9319aff45ff83b8.

**Comment by mread** [comment]
I was mistaken in my previous comment - this commit fixes the issue in master d08ca157b4489cfe7f3f19f0a9319aff45ff83b8
