### ISSUE TITLE
uncaught exception at top level java.lang.IllegalStateException: with most buck commands

### ISSUE THREAD

**Issue by mlostekk** [facebook/buck#829]
Hello,

i am new to buck, but i am trying to get the buck running (because i wanted to start working with nuclide).

Well, wenn i try to run `buck --version`it already gives me this output.

`BUILD FAILED: Failed to read NDK version from /Users/mlostek/Library/Android/sdk/ndk-bundle`

I have already found this issue https://github.com/facebook/buck/issues/701 but it does not give me any solution.

I have installed the NDK via the Android Studio SDK Manager. Is this maybe a problem? And there is no RELEASE.TXT in my NDK Folder. When i add a RELEASE.TXT with the content `r12b (64bit)` which is the version i am having installed it gives me this output.

> Using watchman.
> [2016-08-04 00:01:46.358][error][command:35069ec8-54ee-489c-bc4a-bf15c376c71b][tid:16][com.facebook.buck.cli.Main] Uncaught exception at top level
> java.lang.IllegalStateException: /Users/mlostek/Library/Android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.8/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-gcc
>   at com.google.common.base.Preconditions.checkState(Preconditions.java:174)
>   at com.facebook.buck.android.NdkCxxPlatforms.getToolPath(NdkCxxPlatforms.java:580)
>   at com.facebook.buck.android.NdkCxxPlatforms.getCTool(NdkCxxPlatforms.java:629)
>   at com.facebook.buck.android.NdkCxxPlatforms.build(NdkCxxPlatforms.java:373)
>   at com.facebook.buck.android.NdkCxxPlatforms.getPlatforms(NdkCxxPlatforms.java:138)
>   at com.facebook.buck.android.NdkCxxPlatforms.getPlatforms(NdkCxxPlatforms.java:105)
>   at com.facebook.buck.rules.KnownBuildRuleTypes.createBuilder(KnownBuildRuleTypes.java:351)
>   at com.facebook.buck.rules.KnownBuildRuleTypes.createInstance(KnownBuildRuleTypes.java:226)
>   at com.facebook.buck.rules.KnownBuildRuleTypesFactory.create(KnownBuildRuleTypesFactory.java:49)
>   at com.facebook.buck.rules.Cell.<init>(Cell.java:120)
>   at com.facebook.buck.rules.Cell.createCell(Cell.java:182)
>   at com.facebook.buck.cli.Main.runMainWithExitCode(Main.java:779)
>   at com.facebook.buck.cli.Main.tryRunMainWithExitCode(Main.java:1467)
>   at com.facebook.buck.cli.Main.runMainThenExit(Main.java:1552)
>   at com.facebook.buck.cli.Main.nailMain(Main.java:1665)
>   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>   at java.lang.reflect.Method.invoke(Method.java:497)
>   at com.martiansoftware.nailgun.NGSession.run(NGSession.java:338)

So i guess there is a bug? Am i doing something wrong?

**Comment by marcinkosiba** [comment]
@aiked might know more.

**Comment by aiked** [comment]
Hello @mlostekk,

NDK versions > v11 do not contain a RELESE.TXT file, instead they have a machine readable source.properties file. Do you have that file inside /Users/mlostek/Library/Android/sdk/ndk-bundle? Have you defined ANDROID_NDK variable at your problem?

**Comment by mlostekk** [comment]
Yep, thats the content of the `/Users/mlostek/Library/Android/sdk/ndk-bundle/source.properties`

> Pkg.Desc = Android NDK
> Pkg.Revision = 12.1.2977051

And

> echo $ANDROID_NDK
> /Users/mlostek/Library/Android/sdk/ndk-bundle

**Comment by mlostekk** [comment]
Leaving buck behind. Thanks for your help

**Comment by markortiz** [comment]
@mlostekk how do you solve this problem?
I'm facing same error.

**Comment by mlostekk** [comment]
@markortiz not working with buck ;)

**Comment by ceozhu** [comment]
so sad ,I got the same error too

**Comment by aiked** [comment]
@ceozhu can you share your exception and also the contents of source.properties and where ANDROID_SDK, ANDROID_NDK, ANDROID_HOME, or all the env vars point?

A few things have changed in this area the last few months. Also, how you get Buck, as package or you build the source?

**Comment by ceozhu** [comment]
@aiked  thanks for u echo ,echo $NDK_HOME  /Users/zhupei/Documents/adt-bundle-mac-x86_64-20140702/sdk/android-ndk-r7b
I dont think the env is the problem
I got  the file contents of source.properties  

Pkg.Desc = Android NDK
Pkg.Revision = 13.1.3345770

wait....

I dont think the Pke.Revision is right ,So I turn   the value of Pke.Revision  into value  "r7b"

u guess what ,It's working  

thanks again,appreciated u nice comment above

**Comment by aiked** [comment]
@ceozhu glad you managed to resolve this. I will close this now.

**Comment by mlostekk** [comment]
@ceozhu which source.properties did you touch??

**Comment by aiked** [comment]
@mlostekk I think if your project has a source.properties file then you define the NDK as 12.1 or 13.1 and not as r11a or r12c.

**Comment by ceozhu** [comment]
@mlostekk  under path $NDK_HOME /Users/zhupei/Documents/adt-bundle-mac-x86_64-20140702/sdk/android-ndk-r7b/source.properties ,with contents follow as:
Pkg.Desc = Android NDK
Pkg.Revision = 13.1.3345770
