### ISSUE TITLE
Dose Buck split dex according to the 'primary_dex_pattern' exactly?

### ISSUE THREAD

**Issue by hitYOUcry** [facebook/buck#834]
while I **use_split_dex=true** and set the **primary_dex_pattern**to achieve the Multidex build, I found out the main dex(class.dex) contains more classes than the classes I set in  **primary_dex_pattern**.

My   **primary_dex_pattern** contains 5400+ classes(gen by python script);
The dex file in final APK contains 6200+ classes;

**Comment by hitYOUcry** [comment]
Pictures of main_dex and primary_dex_pattern can't upload successfully ,don't know why..

**Comment by marcinkosiba** [comment]
if you use the linear_alloc_split_dex mode then more classes will go into the primary dex, see: https://buckbuild.com/javadoc/com/facebook/buck/dalvik/DalvikAwareZipSplitter.html

**Comment by hitYOUcry** [comment]
I haven't use linear_alloc_split_dex mode .
 I modified the split strategy in buck source(DexSplitStrategy -> MINMIZE_PRIMARY_DEX_SIZE)  and the main dex become smaller.
It seems work fine.
