### ISSUE TITLE
buck project does not generate correct resource and manifest paths

### ISSUE THREAD

**Issue by kageiit** [facebook/buck#836]
the iml files generated by `buck project` only set the `RES_FOLDERS_RELATIVE_PATH` attribute and not the `RES_FOLDER_RELATIVE_PATH` in the android facet. This prevents the resources from being recognized by intellij. iml files generated by gradle set both these properties and work as expected.

Also, the generated `MANIFEST_FILE_RELATIVE_PATH` points to `../../android_res/AndroidManifest.xml`. This seems like a FB specific setting and does not work as a default for other projects. Seems like the detection is broken for manifest path as well even though the module has the correct manifest paht set via the `android_mainfest` rule

**Comment by marcinkosiba** [comment]
Not sure what the difference between `RES_FOLDERS_RELATIVE_PATH` and `RES_FOLDER_RELATIVE_PATH` is? Do you know whether it triggers different behavior or is one of those supported only by newer plugin versions? 

I was a bit surprised to discover the hardcoded manifest path in `IjProjectTemplateDataPreparer .addAndroidManifestPath`, but it's there :/ It also only seems to kick in if a manifest path wasn't found, so I'm assuming you have a separate BUCK file for resources and a separate one for the android_binary target (this is fine, just asking).

The tricky bit with the manifest is picking the correct one. An `android_resources` target could be part of multiple applications, and any subset of those could be present in the graph, so which is the right manifest to use in that case? The legacy project generator used a fixed fake manifest for all of the resource modules, which only works if you have one app in your repo.
I uploaded a pretty old WIP diff here https://github.com/marcinkosiba/buck/tree/guess_manifest_for_res for what that would look like

**Comment by felipecsl** [comment]
i'm seeing the same issue

**Comment by kageiit** [comment]
#892 will adresses this
