### ISSUE TITLE
BUCK  Proguard Resource ID problems

### ISSUE THREAD

**Issue by hitYOUcry** [facebook/buck#837]
I found out the **dex** file build by buck is a lit big than before(ant build).
So I decompile those dex files and make some comparisons.
Than ,I found sth odd.
Usually, those Res IDs will be replaced by int values after proguard,like this:
**Toast.makeText(AstApp.d(), this.a.getString(2131493689), 0).show();**

While,the same code in the dex file build by my buck scripts I found it's like this:
 **Toast.makeText(AstApp.d(), this.a.getString(j.rec_create_fail), 0).show();**

I think this if one of the reason why the dex file is bigger,so I had to solve this problem.

Is my proguard.cfg(same with ant build script) have problems or some else problems?
Need help  555.....
Thank you

**Comment by hitYOUcry** [comment]
I found the reason.
buck will read in the **proguard-android.txt** file in SDK/tools/proguard.
The file has same base android proguard  -keeps.
While my proguard.cfg file have consider every keep and drop situation,so the file is redundant.
Remove the content of  **proguard-android.txt** and rebuild release apk, apk file size become normal.

**Comment by marcinkosiba** [comment]
Instead of modifying the SDK dir take a look at the `android_sdk_proguard_config` option https://buckbuild.com/rule/android_binary.html

**Comment by hitYOUcry** [comment]
Sry for missed the infos.
That's awesome ,I missed this config.
Thank you!
