### ISSUE TITLE
how to use Buck in Multi-project

### ISSUE THREAD

**Issue by zongwu233** [facebook/buck#838]
My Android project is a set of some projects.
I build the whole project  with gradle . in gradle you can add a module from another project very easy. in setting.gradle like this:
```groovy
 include(':core')
 project(':core').projectDir = new File('../sdk/core')
```
sdk is anther project,and it has a module named `core` 

Recently I want to use Buck to build my project for saving build time.  But I find  multi-project is not supported in Buck.  #116  which was created in 2014, still keeps opened status.
is there any suggestion for  workaround in multi project?

**Comment by Coneko** [comment]
There is a feature for this:

```
# .buckconfig
[repositories]
  core = ../sdk/core
```

```
# ../sdk/core/lib/BUCK

android_library(
  name = 'lib',
  ...
)
```

```
# BUCK

android_binary(
  name = 'MyApp',
  deps = core//lib:lib
  ...
)
```

It's still pretty experimental which is why it's not documented. Let us know how it goes.

**Comment by zongwu233** [comment]
Thanks for your guidance~
It's very useful. I'll try.
