### ISSUE TITLE
Visibility attribute is not respected in the same BUCK file

### ISSUE THREAD

**Issue by davido** [facebook/buck#846]
We are on this commit: e64a2e2ada022f81e42be750b774024469551398.

Consider the following two rules located in the same BUCK file:

```
java_library(
  name = 'plugin-lib',
  srcs = glob(['java/**/*.java'],
  deps = [':utils'],
  provided_deps = ['//:commons-io'],
)

prebuilt_jar(
  name = 'commons-io',
  binary_jar = 'libs/commons-io-1.4.jar',
  source_jar = 'libs/commons-io-1.4-sources.jar',
  visibility = [],
)
```

The rule ':plugin-lib' can be successfully built, even though, the visibility set is empty. However, if I move the `commons-io` rule in another directory/file, say `libs/BUCK`, with the following content:

```
BUCK:

java_library(
  name = 'plugin-lib',
  srcs = glob(['java/**/*.java']),
  deps = [':utils'],
  provided_deps = ['//libs:commons-io'],
)

libs/BUCK:

prebuilt_jar(
  name = 'commons-io',
  binary_jar = 'commons-io-1.4.jar',
  source_jar = 'ommons-io-1.4-sources.jar',
  visibility = [],
)
```

Now I'm getting the expected behaviour:

```
  buck build :plugin-lib
  BUILD FAILED: //:plugin-lib depends on //libs:commons-io, which is not visible
```

**Comment by Coneko** [comment]
This is intended, see https://buckbuild.com/concept/visibility.html:

```
Build rules are visible to the other targets inside the same build file by default.
```

Is there a situation where you want to enforce visibility within the same build file?

**Comment by davido** [comment]
Thanks for clarification.

> Is there a situation where you want to enforce visibility within the same build file?

Kind of. The idea was to whitelist the deps on some third party dependency, that Gerrit core shouldn't depend on. We (ab-)used visibility attribute this way until we realized, that the visibility rules aren't enforced in the same build file:

```
maven_jar(
  name = 'jsr305',
  id = 'com.google.code.findbugs:jsr305:3.0.1',
  sha1 = 'f7be08ec23c21485b9b5a1cf1654c2ec8c58168d',
  license = 'Apache2.0',
  attach_source = False,
  # Whitelist lib targets that have jsr305 as a dependency. Generally speaking
  # Gerrit core should not depend on these annotations, and instead use
  # equivalent annotations in com.google.gerrit.common.
  visibility = [
    ':guava-retrying',
  ],
)
```
