### ISSUE TITLE
Parameters for annotation processors are disabled and undocumented

### ISSUE THREAD

**Issue by dreiss** [facebook/buck#85]
android_library and java_library support the arguments "annotation_processors", "annotation_processor_deps", "annotation_processor_params", and "annotation_processor_only".  Currently these are undocumented.

**Comment by Coneko** [comment]
These are now available:

https://github.com/facebook/buck/blob/master/src/com/facebook/buck/java/JavaLibraryDescription.java#L168-170

They're still undocumented though.

**Comment by facebook-github-bot-9** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by davido** [comment]
`java.safe_annotation_processors` doesn't implemented either.

What I wonder: FB does use a code review system: (phabricator?) internally? At least we see, "Reviewed By:" footer in commit messages.

So how comes that those lines: https://github.com/facebook/buck/blame/master/src/com/facebook/buck/jvm/java/JavaBuckConfig.java#L81-L83 added in this commit: https://github.com/facebook/buck/commit/97a8dc08acce6b0bf04820f2d29bc1fb85957ad1 missing documentation bits? Was that intended not to be documented? In which case i would expect that commit message states that this config options intentionally documented.

**Comment by dreiss** [comment]
We do use code review.  We do frequently leave options undocumented if we think they aren't ready for public consumption.  You're right that it would probably be a good idea to state that explicitly in the commit messages.

**Comment by rahul-a** [comment]
Any update around annotation processing feature being available in open source version? Can't get this to work

**Comment by Coneko** [comment]
cc @jkeljo

**Comment by v-jizhang** [comment]
Hi, this issue is closed because it has not been updated for over 3 years. Thanks
