### ISSUE TITLE
new buck daemon is including files named buck by default

### ISSUE THREAD

**Issue by kageiit** [facebook/buck#851]
Old daemon used to only include build files named `BUCK` and was case sensitive.

recent changes made it include `buck` as well which breaks certain tools as we create a symlink to a buck installation in the project and call it `buck`.

This makes all buck commands invoked from the symlink with invalid syntax errors

**Comment by marcinkosiba** [comment]
I don't know of a change that would have done this intentionally. Define "new" and "old"? Revision ranges would be nice, also this does sound like something that could be easily bisected :)

**Comment by kageiit** [comment]
e3c0eab - broken

d5491b2969418c2ef3922318a60cf25ba8135682 - works

**Comment by kageiit** [comment]
Git bisect points to 2910f2ecf78ca93d660114e7af90ab4639b7e067 as the first bad commit

**Comment by kageiit** [comment]
@marcinkosiba can you see anything obvious from the bad commit?

**Comment by marcinkosiba** [comment]
I think it's this line https://github.com/facebook/buck/commit/2910f2ecf78ca93d660114e7af90ab4639b7e067#diff-f0f5420cbf056f7af10df1883a3681dfR267 which in turn tries to read all TargetGroups from the root BUCK file.

We could hack around this and have `PerBuildState.getAllGroups` double-check the case of the file, but I'm surprised you didn't have issues with this before. Effectively you've added a malformed BUCK file to your repo, so things like `buck query 'set(//...)'` would have been broken before the commit anyway.

**Comment by kageiit** [comment]
I see. But nowhere in the documentation of buck it ever states that it is case sensitive/insensitive when it comes to configuration files. Maybe we can make that clear as well?

**Comment by marcinkosiba** [comment]
@kageiit 
It's not buck, it's HFS+, the underlying filesystem. Buck is asking 'gimme `./BUCK` and HFS+ is returning the contents of `./buck`.

**Comment by kageiit** [comment]
ah gotcha. That makes sense. This is probably a rare quirk. I would be ok if this was not fixed too. Because we have moved away from using `./buck` and are using `./buckw` instead as the wrapper script.

But I'll leave it up to you. I think we can mention this somewhere in the docs still especially for case sensitive file systems. All the docs talk about `BUCK` files and if someone is not aware of this behavior, it can lead to unpleasant surprises
