### ISSUE TITLE
Junk char issued in the ui after upgrade

### ISSUE THREAD

**Issue by davido** [facebook/buck#856]
After upgrading Buck to this version:  6a19cf921c107ea0f1751e4f84c639e5050e2da7 i'm getting strange char in the output:

```
[-] PROCESSING BUCK FILES...FINISHED 0.3s [100%] 🐳  Symlink caused cache invalidation
```

**Comment by Coneko** [comment]
That's intended: it reflects the level of cache invalidations.

See f5ddbd3448bac2f36c2bb1dd1fd9b89bd1f730b8.
