### ISSUE TITLE
Add Kotlin Android support

### ISSUE THREAD

**Issue by dsyang** [facebook/buck#857]
Vanilla kotlin library support was added in https://github.com/facebook/buck/pull/810. the next big step would be to add android support. 

From @bkase's comment on https://github.com/facebook/buck/pull/810#issuecomment-238069818 it looks like the problem is we need the equivalent of `android_library()` for kotlin. I think that could be pretty straight-forward.

 We would need create a new `AndroidKotlinLibraryDescription` that behaves almost exactly like `AndroidLibraryDescription` excepts it compiles with kotlinc instead of javac.  

A quick look through the source code suggests we'd need to do the following:
 - [ ] Refactor `AndroidLibrary` to take in a `BaseCompileToJarStepFactory` (it currently defaults to javac)
 - [ ] Copy `AndroidLibraryDescription` into a `AndroidKotlinLibraryDescription`. Basically doing the same thing except passing in `KotlincToJarStepFactory` to the `AndroidLibrary`
 - [ ] Refactor the common stuff out of the two android library descriptions.

I'm not sure when I'll have time to tackle this yet. If someone else wants to take a shot go for it!

**Comment by bolinfest** [comment]
@bkase Want to sign up for this one?

**Comment by bkase** [comment]
Very busy through September, but afterwards I may have some spare cycles

**Comment by kageiit** [comment]
Does this account for `kapt` support as well?

**Comment by zbsz** [comment]
Got something similar in #913, but instead of creating specific `Android{LANG}LibraryDescription` I opted to use `language` config parameter. So far have it implemented for Scala, adding Kotlin and other jvm languages should be quite straightforward then, just wanted to get it accepted for Scala first.

**Comment by dsyang** [comment]
#937  enables this.  @kageiit I don't think so, but I think it'd be best to open up a new issue for that
