### ISSUE TITLE
Implicitly include kotlin runtime libraries in kotlin_{library|test} targets

### ISSUE THREAD

**Issue by dsyang** [facebook/buck#858]
See https://github.com/facebook/buck/pull/810#issuecomment-233732498

**Comment by bolinfest** [comment]
The comment from @mikekap makes the good suggestion of breaking down `DefaultJavaLibrary` to better separate its concerns.

From the Scala example, it seems like we could fix this issue without refactoring `DefaultJavaLibrary`, but it would be nice if we actually cleaned things up.

**Comment by kageiit** [comment]
what version will be included? can that be configured via the kotlin library rule description?

**Comment by dsyang** [comment]
It would be whatever version of the .jar you include in the repo and set in `.buckconfig`.  It should probably match the version of the compiler you specify too. 

If we use https://github.com/dsyang/buckotlin as an example. That repro has version 1.0.3 in the `libs/` folder. It's `.buckconfig` is configured to use the kotlinc in `libs/`.  We want the buck target `//libs/kotlin/lib:runtime` to  be implicitly included in any `kotlin_library()` rules.  To do this we can add a `runtime = //libs/kotlin/lib:runtime` property in the project's `.buckconfig` and update KotlinLibraryDescription.java to implicitly add the buck target to each `kotlin_library()` invocation. 

> configured via the kotlin library rule description

Do you mean allowing each `kotlin_library()` rule to decide which version of the runtime to include? or allow them to say whether or not to implicitly include the runtime? If the former, I'm not sure if we want to support multiple kotlin versions in the same project. If the latter, then definitely :)

**Comment by kageiit** [comment]
The later :)

**Comment by dsyang** [comment]
Yea we should definitely have a flag for that then :)

**Comment by brettwooldridge** [comment]
Pull request #1054 addresses this issue.
