### ISSUE TITLE
 Main manifest has <uses-sdk android:minSdkVersion='14'> but library uses minSdkVersion='16'

### ISSUE THREAD

**Issue by coofee** [facebook/buck#863]
I use buck first time and run into this problem，please tell me how to solve this problem? thanks.

``` xml
[AndroidManifest.xml:1, AndroidManifest.xml:3] Main manifest has <uses-sdk android:minSdkVersion='14'> but library uses minSdkVersion='16'
```

**Comment by v-jizhang** [comment]
Sorry we never got back to this! At this point, we are closing this because it is quite out of date and it is not clear if the issue still exists. Please create a new one if you still see the problem. Thank you.
