### ISSUE TITLE
Android res/raw resources from libraries are not included in the final APK

### ISSUE THREAD

**Issue by felipecsl** [facebook/buck#877]
We're seeing this issue while trying to integrate Buck into our project. We first noticed this due to a crash on the [jodatime-android](https://github.com/dlew/joda-time-android) library, which uses reflection to load resources from `R.raw`.
Turns out that the raw class for library dependencies (aar) is completely empty when building with buck. 
The same class is correctly populated when building with gradle. Is this a known issue/limitation?

**Comment by felipecsl** [comment]
One interesting finding here is that this doesn't happen if we disable predexing with `disable_pre_dex = True`

**Comment by felipecsl** [comment]
OK finally found the root cause. This was caused by having `trim_resource_ids = True`.
Removing that setting fixed the problem

**Comment by kageiit** [comment]
@felipecsl you may want to keep `trim_resource_ids = True` to keep your primary dex minimal and so that you can lower your `linear_alloc_hard_limit` values. To do so, you need atleast a sha that includes #830 or higher in your `.buckversion`

**Comment by felipecsl** [comment]
@kageiit we were using the `HEAD` sha from Buck when we ran into this issue, so I'm pretty sure it still exists

**Comment by felipecsl** [comment]
Just tried it with current master of Buck, issue still exists

**Comment by felipecsl** [comment]
So it turns out this was caused by jodatime-android accessing its `R.raw` resources via reflection. Apparently Buck is trimming them since they are not directly referenced anywhere in the code.
Our workaround was to create a simple class that keeps references to all those `R.raw` fields and that worked fine.
