### ISSUE TITLE
TypeError: android_binary() got an unexpected keyword argument 'includes_vector_drawables'

### ISSUE THREAD

**Issue by GunNan** [facebook/buck#880]
Hi, I have a problem when using Buck to build Android project.

In the BUCK file:

```
android_binary(
  ###
  #...
  ###
  includes_vector_drawables = True,
)
```

When I try to build application, there is a problem occurred, here is log: 

```
BUILD FAILED: Parse error for build file D:\KaraokeBuck\BUCK:   File "D:\KaraokeBuck\buck-out\tmp\buck_run.mrjs_e\buck_python_program6825092295362292241\buck.py", line 1283, in process_with_diagnostics
    diagnostics=diagnostics)
  File "D:\KaraokeBuck\buck-out\tmp\buck_run.mrjs_e\buck_python_program6825092295362292241\buck.py", line 1194, in process
    implicit_includes=self._implicit_includes)
  File "D:\KaraokeBuck\buck-out\tmp\buck_run.mrjs_e\buck_python_program6825092295362292241\buck.py", line 1134, in _process_build_file
    implicit_includes=implicit_includes)
  File "D:\KaraokeBuck\buck-out\tmp\buck_run.mrjs_e\buck_python_program6825092295362292241\buck.py", line 1057, in _process
    exec(code, module.__dict__)
  File "D:\KaraokeBuck\BUCK", line 33, in <module>
    'debug_mode': True,
  File "D:\KaraokeBuck\buck-out\tmp\buck_run.mrjs_e\buck_python_program6825092295362292241\buck.py", line 139, in invoke
    return self.func(*args, **updated_kwargs)
TypeError: android_binary() got an unexpected keyword argument 'includes_vector_drawables'

[-] BUILDING...FINISHED 0.3s
Not using buckd because watchman isn't installed.
```

Thanks!

**Comment by k21** [comment]
Hi, does your version of Buck include the commit that added support for this argument (https://github.com/facebook/buck/commit/4b81d63ac18a6f626f2fd23c088eb29e0ebba4b6)? What is the output when you run `buck --version`?

**Comment by GunNan** [comment]
Hi, here is my buck version:

```
>buck --version
buck version *edff8b2b8818bb64982837158dd546a66b6ef6c2
```

**Comment by k21** [comment]
That might be an issue, this revision is from May, `includes_vector_drawables` has been implemented in Buck just a few weeks back. Please update your version of Buck and try again. Reopen the issue if you encounter additional difficulties.

**Comment by felipecsl** [comment]
I'm getting this error during aapt: `error: No resource identifier found for attribute 'fillType'`.
This is being used inside a vector drawable xml inside `drawable-v24`. Tried to use the `includes_vector_drawables` but didnt help, but not sure if that's related. Is that known?
