### ISSUE TITLE
[Project generation] Bundle identifier could not be substituted using `info_plist_substitutions`

### ISSUE THREAD

**Issue by nguyentruongtho** [facebook/buck#887]
We should be able to do this:
-  Put place holder in the info.plist:

```
    <key>CFBundleIdentifier</key>
    <string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
```
- Use `info_plist_substitutions` for project generation to generate the project with correct bundle identifier.

**Comment by Coneko** [comment]
This should work correctly if you use `buck project --build-with-buck`.

**Comment by nguyentruongtho** [comment]
unfortunately, it doesn't. Let put this issue up here so we won't forget. The fix should be easy, I guess.

**Comment by ryu2** [comment]
We pass `configs` to Xcode, not `info_plist_substitutions`.  The latter is used by Buck builds only.

In pretty much all cases though, `configs` are just the same value as `info_plist_substitutions` wrapped in an additional layer for Xcode project settings:

`{ 'Debug': <configs>, 'Release': <configs> }`

**Comment by nguyentruongtho** [comment]
You are saying that we can use `configs` as an attribute of `apple_bundle` for xcode project generation? is it documented somewhere?

**Comment by Coneko** [comment]
Please don't, that way leads to madness, and divergence of Xcode vs Buck builds.

**Comment by bopbi** [comment]
hi recently i created a build using buck, but it always failed and the output contains: 

`Unrecognized plist variable: $(PRODUCT_BUNDLE_IDENTIFIER) when reading from the Info.plist file`

and after i to change the $(PRODUCT_BUNDLE_IDENTIFIER) on the plist to a hardcoded value it work, so does my issue related with this issue?
