### ISSUE TITLE
buck audit classpath: different results are produced if '--dot' option is used or not

### ISSUE THREAD

**Issue by davido** [facebook/buck#888]
After upgrade to most recent master (fd3105a0b62899f74662f4cdc156de6990bdc24c) we are missing some dependencies in our home made script for Eclipse project generation. What we do is using `buck audit classpath` command for some root targets.

We've noticed that after the upgrade the dependencies that are used by `java_test` rules aren't pulled anymore. On the old Buck version (e64a2e2ada022f81e42be750b774024469551398), the `//lib:jimfs` dependency was reached here:

Without '--dot' option:

```
  buck audit classpath tools/eclipse:classpath | grep -i jimfs
  /home/ehugare/workspaces/gerrit/gerrit/buck-out/gen/lib/jimfs.jar
```

With '--dot' option:

```
  buck audit classpath --dot tools/eclipse:classpath | grep -i jimfs
  [-] PARSING BUCK FILES...FINISHED 0.1s
  "//lib:jimfs__download_bin" -> "//tools:download_file";
  "//lib:jimfs__download_src" -> "//tools:download_file";
  "//lib:jimfs" -> "//lib:jimfs__download_bin";
  "//lib:jimfs" -> "//lib:guava";
  "//lib:jimfs" -> "//lib:jimfs__download_src";
  "//lib:jimfs" -> "//lib:LICENSE-DO_NOT_DISTRIBUTE";
  "//gerrit-httpd:httpd_tests" -> "//lib:jimfs";
```

On the newer version it's missed, even though: `//gerrit-httpd:httpd_tests` depends on `//lib:jimfs` but then and only then if no '--dot' option is used:

Correct:

```
  $ buck audit classpath --dot //gerrit-httpd:httpd_tests | grep jimfs 
  [-] PARSING BUCK FILES...FINISHED 0.0s
  "//lib:jimfs__download_src" -> "//tools:download_file";
  "//lib:jimfs__download_bin" -> "//tools:download_file";
  "//lib:jimfs" -> "//lib:jimfs__download_bin";
  "//lib:jimfs" -> "//lib:jimfs__download_src";
  "//lib:jimfs" -> "//lib:LICENSE-DO_NOT_DISTRIBUTE";
  "//lib:jimfs" -> "//lib:guava";
  "//gerrit-httpd:httpd_tests" -> "//lib:jimfs";
```

Broken:

```
  buck audit classpath tools/eclipse:classpath | grep -i jimfs
  [-] PARSING BUCK FILES...FINISHED 0.2s [100%]
```

**Comment by davido** [comment]
It's transitive dependency through the `java_test` rule:

```
  tools/eclipse:classpath -> //gerrit-httpd:httpd_tests -> //lib:jimfs
```

The workaround is to put `//lib:jimfs` as a direct dependency to `tools/eclipse:classpath`, in which case `buck audit classpath` would work as expected even without '--dot' option: [1]

```
  $ buck audit classpath tools/eclipse:classpath | grep -i jimfs
  [-] PARSING BUCK FILES...FINISHED 0.3s [100%]
  /home/davido/projects/gerrit/buck-out/gen/lib/__jimfs__/jimfs-1.0.jar
```

* [1] https://gerrit-review.googlesource.com/86374

**Comment by Coneko** [comment]
cc @yiding, @asp2insp this is most likely related to the recent refactorings.

**Comment by asp2insp** [comment]
This is caused by d08ca15 since `JavaTest` no longer inherits from `JavaLibrary` I'll take it on.

**Comment by asp2insp** [comment]
@davido do you also expect the `//gerrit-httpd:httpd_tests` jar to appear in the the classpath output?

**Comment by davido** [comment]
This is actually a good quesion. I would expect that the command behave in smilar way, no matter what options are passed, unless it's documented that the dependency chain is cut for some edges. But then I would expect that it would be cut in the same way, no matter if I pass specific options or not (unless it's defined to have differen semantic for different options).

So yes, 

```
 $ buck audit classpath --dot tools/eclipse:classpath | grep gerrit-httpd:httpd_tests
 [-] PARSING BUCK FILES...FINISHED 0.3s [100%]
  "//gerrit-httpd:httpd_tests" -> "//lib:servlet-api-3_1";
  "//gerrit-httpd:httpd_tests" -> "//lib/joda:joda-time";
  "//gerrit-httpd:httpd_tests" -> "//lib/guice:guice-servlet";
  "//gerrit-httpd:httpd_tests" -> "//lib:jimfs";
  "//gerrit-httpd:httpd_tests" -> "//lib:gson";
  "//gerrit-httpd:httpd_tests" -> "//gerrit-util-http:http";
  "//gerrit-httpd:httpd_tests" -> "//gerrit-reviewdb:server";
  "//gerrit-httpd:httpd_tests" -> "//lib:junit";
  "//gerrit-httpd:httpd_tests" -> "//lib/easymock:easymock";
  "//gerrit-httpd:httpd_tests" -> "//gerrit-util-http:testutil";
  "//gerrit-httpd:httpd_tests" -> "//gerrit-extension-api:api";
  "//gerrit-httpd:httpd_tests" -> "//gerrit-httpd:httpd";
  "//gerrit-httpd:httpd_tests" -> "//lib:gwtorm";
  "//gerrit-httpd:httpd_tests" -> "//lib:guava";
  "//gerrit-httpd:httpd_tests" -> "//gerrit-server:server";
  "//gerrit-httpd:httpd_tests" -> "//lib/guice:guice";
  "//gerrit-httpd:httpd_tests" -> "//lib/jgit/org.eclipse.jgit:jgit";
  "//gerrit-httpd:httpd_tests" -> "//gerrit-common:server";
  "//gerrit-httpd:httpd_tests" -> "//lib:truth";
  "//gerrit-httpd:httpd_tests" -> "//lib/jgit/org.eclipse.jgit.junit:junit";
  "//tools/eclipse:classpath" -> "//gerrit-httpd:httpd_tests";
```

If I see this line with '--dot' option:

```
"//tools/eclipse:classpath" -> "//gerrit-httpd:httpd_tests";
```

it's kind of unexpected to not see the output file for this rule:

```
$ buck targets --show_output gerrit-httpd:httpd_tests
//gerrit-httpd:httpd_tests buck-out/gen/gerrit-httpd/lib__httpd_tests#testsjar__output/httpd_tests#testsjar.jar
```

if I remove '--dot' option:

```
$ buck audit classpath tools/eclipse:classpath | grep httpd_tests
[-] PARSING BUCK FILES...FINISHED 0.3s [100%]
```

But then again, i can live with both behaviours as far as it is well defined and documented.

**Comment by asp2insp** [comment]
Okay, so this issue really addresses several points

1. The `--dot` option produces different output.
   a. The dot traversal uses a different mechanism for traversing the graph under the hood, thus the variation in output. I'll update the documentation to note this.
2. The classpath no longer includes transitive dependencies from a `java_test` rule
  a. I've uploaded a patch which is going through review, and should land within the next few days which restores transitive dependencies from `java_test` rules to the classpath
3. "It's kind of unexpected to not see the output file for this rule"
  a. This is actually working as intended. As you can see in the command line output produced, there is a jar listed for the `httpd_tests` target. The `#testsjar` is a "build flavor" but the output still belongs to the rule that you are querying.

**Comment by davido** [comment]
> As you can see in the command line output produced, there is a jar listed for the httpd_tests target.

What do you mean? Following the principle of least surprise, I would expect to see the following:

```
  $ buck audit classpath --dot tools/eclipse:classpath | grep gerrit-httpd:httpd_tests
  [...]
  "//tools/eclipse:classpath" -> "//gerrit-httpd:httpd_tests";

  $ buck audit classpath tools/eclipse:classpath | grep httpd_tests
  //gerrit-httpd:httpd_tests buck-out/gen/gerrit-httpd/lib__httpd_tests#testsjar__output/httpd_test
```

**Comment by asp2insp** [comment]
Apologies for not being more clear. My point three above was specifically addressing these lines:

> it's kind of unexpected to not see the output file for this rule:

> $ buck targets --show_output gerrit-httpd:httpd_tests
> //gerrit-httpd:httpd_tests buck-out/gen/gerrit-httpd/lib__httpd_tests#testsjar__output/httpd_tests#testsjar.jar

The jar listed (`http_tests#testsjar.jar`) is in fact the output file for the rule `gerrit-httpd:httpd_tests`

In regards to the behavior with `--dot` vs without, I agree that it's incorrect that the result is different, and that's covered in point 1 above. I'm in the process of updating the documentation.

**Comment by davido** [comment]
Thanks for the quick fix.
