### ISSUE TITLE
Duplicated settings in generated xcode project

### ISSUE THREAD

**Issue by nguyentruongtho** [facebook/buck#890]
This bug was there since version v2016.03.28.01.

![image](https://cloud.githubusercontent.com/assets/1457567/18711035/60c61de6-8008-11e6-971e-91141a26f748.png)
![image](https://cloud.githubusercontent.com/assets/1457567/18711063/828b1d3c-8008-11e6-8b3e-ea249e19a9ce.png)

**Comment by v-jizhang** [comment]
Sorry we never got back to this! At this point, we are closing this because it is quite out of date and it is not clear if the issue still exists. Please create a new one if you still see the problem. Thank you.
