### ISSUE TITLE
IntelliJ project generation not working on quickstart project

### ISSUE THREAD

**Issue by lucidsheep** [facebook/buck#897]
When trying to get an IntelliJ project to work with the android quickstart project, the following is observed:
- No configurations exist when the project is opened
- When trying to create a configuration with one of the two modules (apps_myapp or project_root), the configuration gives a "Please Select Android SDK" error
- If you set a SDK in File -> Project Structure, the error changes to "AndroidManifest.xml doesn't exist or has incorrect root tag"

As a result, I can't run any configuration through IntelliJ.

This was observed on buck version `7329cb8e190cba9d6fc37621726a287b362024be` on both Android Studio 2.1 and IntelliJ IDEA 2016.2.4. Similar problems are also occurring on our own buck projects, which prompted me to try reproducing it on the quickstart project.

**Comment by Coneko** [comment]
cc @mkillianey

**Comment by mkillianey** [comment]
@lucidsheep - do you have this problem on projects generated by `buck project` before commit 7329cb8e ?  If you temporarily your `.buckversion` file back to whatever it was before you upgraded it and run `buck project`, do you still have the problem?  If not, could you add that sha1 here to help bisect the problem?

**Comment by lucidsheep** [comment]
I've confirmed IntelliJ generation works, including building the project and running on a device, with the following settings:
Android Studio 2.2
Android API level 21
Java 1.8
macOS Sierra
buck version `4fae534820183f5c71afbca0300ebfffb7e30b39`

**Comment by styurin** [comment]
Quickstart was removed in b3c1dd90071594758febf17ccb25469597710207
