### ISSUE TITLE
java.lang.RuntimeException:android.content.res.Resources$NotFoundException

### ISSUE THREAD

**Issue by GunNan** [facebook/buck#904]
Hi, I have a problem when using `aar` library, I have put this problem in #875 and #808 . 

Here is my `BUCK` file

```
import re

aar_deps = []
for aarfile in glob(['libs/**/*.aar']):
  name = 'aars__' + re.sub(r'^.*/([^/]+)\.aar$', r'\1', aarfile)
  aar_deps.append(':' + name)

  android_prebuilt_aar(
    name = name,
    aar = aarfile,
  )

android_library(
  name = 'all-javas',
  srcs = glob([
  'ext/**/*.java',
  'wns/**/*.java',
  'src/**/*.java',
  'upload/**/*.java']),
  deps = [
    ':res',
    ':all-jars',
    ':all_native_libs',
    ':protocol',
  ] + aar_deps,
)

# ...
# ...
# ...
```

And here is my Exception:

`java.lang.RuntimeException: Unable to start activity ComponentInfo{com.tencent.karaoke/com.tencent.karaoke.module.main.ui.MainTabActivity}: android.content.res.Resources$NotFoundException: File res/drawable/abc_ic_ab_back_material.xml from drawable resource ID #0x7f020013`

And the code is:

```
import android.support.v7.app;

public class MainTabActivity extends AppCompatActivity{
    @Override
    protected void onCreate(Bundle savedInstanceState) {
       super.onCreate(savedInstanceState);
       //....
    }
}
```

Thanks!

**Comment by marcinkosiba** [comment]
I can't determine what's wrong based on the information you provided. Could you please create a minimal repro and share it as a .zip or github repository?

**Comment by GunNan** [comment]
Thank you very much!

https://github.com/GunNan/BuckProblem/tree/master

This reposistory contains 'Buck' file, 'log' file, 'libs' list file, and part of source code. I'm sorry for that I cannot put all source code here because of some licence in my company.

**Comment by marcinkosiba** [comment]
@GunNan 
unfortunately that still doesn't allow me to reproduce the issue. If you can't share all of the code then perhaps you could create a small sample app that demonstrates the problem?

Also, the internets say that you might need to add an option to AAPT: `--no-version-vectors`. Buck does not do this by default, so on you `android_binary` target, try setting `includes_vector_drawables = True,` and see if it helps.

**Comment by marcinkosiba** [comment]
26 days without activity, closing.

**Comment by dmays** [comment]
@marcinkosiba for any that find this in the future, your proposed solution worked perfectly for me.  

I created a project with the AS new project wizard and experienced this issue immediately.  Setting `includes_vector_drawables = True` on `android_binary` of my app module's build file fixed the `android.content.res.Resources$NotFoundException` crash at runtime that I was experiencing.
