### ISSUE TITLE
GHC linking fails due to comma in "#default,static"

### ISSUE THREAD

**Issue by dajmaki** [facebook/buck#906]
Having a dependant haskell library will generate a linker command line that contains
`-Wl,-rpath '-Wl,/path/to/buck-out/gen/some-library/some-library#default,static'`

This causes the clang linker to interpret 'static' as a separate path and to fail with:
`ld: file not found: static`

I've fixed this for now by changing the comma to a plus: '#default+static'. Would
it be feasible to change this?

**Comment by Coneko** [comment]
cc @andrewjcg 

According to https://github.com/facebook/buck/blob/master/src/com/facebook/buck/cxx/Linkers.java#L40 we should be using `-Wlinker` when the argument contains `,`, not `-Wl`.

Can you add instructions on how to repro this?
