### ISSUE TITLE
Support Visual C++ build system

### ISSUE THREAD

**Issue by mattpodwysocki** [facebook/buck#908]
Currently, the Cxx build system only supports Clang or GCC.  Clang [is supported on Windows](http://llvm.org/releases/download.html) and although Clang [has some compatibility with MSVC](http://clang.llvm.org/docs/MSVCCompatibility.html) it's nowhere near what is needed with a complete build system.

**Comment by Coneko** [comment]
cc @ilya-klyuchnikov

**Comment by ilya-klyuchnikov** [comment]
@mattpodwysocki, Visual C++ support is work in progress right now.
