### ISSUE TITLE
Generate module map files for Apple framework targets

### ISSUE THREAD

**Issue by jernejstrasner** [facebook/buck#914]
http://clang.llvm.org/docs/Modules.html

Buck has to generate a module map file for an ObjC (or mixed Swift) framework for it to be usable from Swift. This will also allow `@import` style includes in ObjC.

Fill add more details later, I'm exploring what needs to be done.

**Comment by nguyentruongtho** [comment]
@robbertvanginkel has some WIP on generating module map for an apple library: https://github.com/facebook/buck/pull/842/files. 
For swift framework, we need to add the generated header to module map as well.

**Comment by jernejstrasner** [comment]
@nguyentruongtho sweet!
@robbertvanginkel any updates on that pull request?

**Comment by stowy** [comment]
The PR is open here https://github.com/facebook/buck/pull/983
