### ISSUE TITLE
[plugin] Delegate all builds in IJ to Buck

### ISSUE THREAD

**Issue by shs96c** [facebook/buck#918]
Ctl-shift-f10 in a file under the control of Buck should cause the target to be built and run through Buck, not IJ.

Failing this, allowing a buck build step to be executed before IJ does its magic (as can be done with ant)  would be very useful.

Context: on selenium, we repackage jetty as part of our build. It'd be nice to also be able to run tests and what-not in IJ without leaving the IDE.

http://stackoverflow.com/questions/11044955/intellij-idea-run-batch-script-before-and-after-run-debug-configuration
https://www.jetbrains.com/help/idea/2016.2/configuring-triggers-for-ant-build-target.html

**Comment by v-jizhang** [comment]
Sorry we never got back to this! At this point, we are closing this because it is quite out of date and it is not clear if the issue still exists. Please create a new one if you still see the problem. Thank you.
