### ISSUE TITLE
Including Findbugs and Lint into buck build for android

### ISSUE THREAD

**Issue by rmahfoud** [facebook/buck#919]
I'm migrating from Gradle and looking for examples on how to invoke Findbugs and lint as part of my build. What's the recommended way to do that? There seems to be a scarcity of examples online for custom scripts. Could someone share a sample of this or similar integration?

Thanks,

**Comment by v-jizhang** [comment]
Sorry we never got back to this! At this point, we are closing this because it is quite out of date and it is not clear if the issue still exists. Please create a new one if you still see the problem. Thank you.
