### ISSUE TITLE
Using brew install buck still requires Java

### ISSUE THREAD

**Issue by zardra** [facebook/buck#920]
The Downloading and Installing Buck doc (https://buckbuild.com/setup/install.html) indicates there are system requirements for a manual build but not for using brew install.  However, I received the following error after following the instructions in the Install with Homebrew section. 

> ==> Installing buck from facebook/fb
buck: Java 1.7+ is required to install this formula.JavaRequirement unsatisfied!

>You can install with Homebrew Cask:
  brew cask install java

>You can download from:
  http://www.oracle.com/technetwork/java/javase/downloads/index.html
Error: An unsatisfied requirement failed this build.

**Comment by Coneko** [comment]
Thanks for the report, I will update the docs.
