### ISSUE TITLE
genrule() doesn't appear to be outputting files.

### ISSUE THREAD

**Issue by Qix-** [facebook/buck#929]
`genrule()` isn't really doing me any favors, and I'm wondering if this is a bug, poor documentation, or if I'm just flatout unable to do this using Buck.

```python
genrule(
    name = 'test-peg',
    srcs = ['src/test.peg'],
    out = 'test-peg.c',
    cmd = 'peg src/test.peg -o $OUT')

cxx_binary(
    name = 'test-project',
    srcs = [
        'src/cli.c',
        '$(location //:test-peg.c)'],  # //:test-peg by itself didn't work either...
    compiler_flags = [
        '-Wall', '-Wextra',
        '-Werror', '-pedantic',
        '-std=c99'],
    licenses = [
        'LICENSE'],
    visibility = [
        'PUBLIC'])
```

`buck targets` gets me

```console
$ buck targets
[+] PARSING BUCK FILES...0.1s [100%]
BUILD FAILED: Unable to find repository '$(location ' in cell rooted at: /src/test-project-grammar
```

What's the proper way of doing this?

**Comment by k21** [comment]
You need to use the name of the target that generates the source file, so in your case it would be either `'//:test-peg'` or `':test-peg'`. What is the output when you try one of those?

**Comment by Qix-** [comment]
Do you mean `$(location //:test-peg)`? or just `//:test-peg` as a source?

**Comment by k21** [comment]
Just by itself, without the `$(location )` part.

**Comment by Qix-** [comment]
Ahh okay. I'll try that again.
