### ISSUE TITLE
Expecting keyword 'allowshrinking', 'allowoptimization', or 'allowobfuscation' before 'includedescriptorclasses'

### ISSUE THREAD

**Issue by wv1124** [facebook/buck#932]
react native project 
rn: 0.34

build release config
`
android_binary(
  name = 'app-release',
  package_type = 'release',
  manifest = 'src/main/AndroidManifest.xml',
  keystore = '//app/keystore:qianmi',
  proguard_config = 'proguard-rules.pro',
  android_sdk_proguard_config='none',
  deps = [
    ':app-code',
  ],
)`

`o Android platform target specified. Using default: Google Inc.:Google APIs:23
Error: Expecting keyword 'allowshrinking', 'allowoptimization', or 'allowobfuscation' before 'includedescriptorclasses' in line 46 of file '/Users/wv/work/d2papp/src/master/android/app/proguard-rules.pro',
  included from line 34 of file 'buck-out/gen/app/**app-release#aapt_package__proguard**/.proguard/command-line.txt',
  included from argument number 1

BUILD FAILED: //app:app-release failed with exit code 1:
proguard_obfuscation
stderr: Error: Expecting keyword 'allowshrinking', 'allowoptimization', or 'allowobfuscation' before 'includedescriptorclasses' in line 46 of file '/Users/wv/work/d2papp/src/master/android/app/proguard-rules.pro',
  included from line 34 of file 'buck-out/gen/app/**app-release#aapt_package__proguard**/.proguard/command-line.txt',
  included from argument number 1

[-] PROCESSING BUCK FILES...FINISHED 0.0s
[-] DOWNLOADING... (0.00 B/S AVG, TOTAL: 0.00 B, 0 Artifacts)
[-] BUILDING...FINISHED 6.2s [100%](69/69 JOBS, 6 UPDATED, 6 [8.7%] CACHE MISS)
`

here is my proguard file
'-keepclassmembers,includedescriptorclasses class \* { native <methods>; }'

[proguard-rules.pro.zip](https://github.com/facebook/buck/files/520935/proguard-rules.pro.zip)
[BUCK.zip](https://github.com/facebook/buck/files/520942/BUCK.zip)

**Comment by MichaelEvans** [comment]
I'm seeing this as well (not a react native project, FWIW). Any suggestions for a workaround/fix?

**Comment by v-jizhang** [comment]
Sorry we never got back to this! At this point, we are closing this because it is quite out of date and it is not clear if the issue still exists. Please create a new one if you still see the problem. Thank you.
