### ISSUE TITLE
Allow export_file() to export an executable

### ISSUE THREAD

**Issue by Qix-** [facebook/buck#938]
`genrule()` takes the argument `executable=True` in order to allow substitutions such as `$(exe //some:rule)` to occur.

However, `export_file()` does not, forcing simple executable scripts to be exported under aliased names using `genrule()`.

``` python
genrule(
     name='some-name',
     srcs=['file.sh']
     out='file.sh',
     executable=True,
     cmd='cp $SRCS $OUT',
     visibility=['PUBLIC'])
```

which is terribly verbose and clunky. It would be great to support `executable=` in `export_file()`.

**Comment by v-jizhang** [comment]
Sorry we never got back to this! At this point, we are closing this because it is quite out of date and it is not clear if the issue still exists. Please create a new one if you still see the problem. Thank you.
