### ISSUE TITLE
Buck project points to empty BuildConfig, Manifest and R classes

### ISSUE THREAD

**Issue by felipecsl** [facebook/buck#942]
I see this in the IML file:
```
<option name="GEN_FOLDER_RELATIVE_PATH_AIDL" value="/../buck-out/android/core/gen" />
```

However, the gen directory only has empty stubs, for example:
```java
/*___Generated_by_IDEA___*/

package com.foo.lib;

/* This stub is only used by the IDE. It is NOT the BuildConfig class actually packed into the APK */
public final class BuildConfig {
  public final static boolean DEBUG = Boolean.parseBoolean(null);
}
```
and 
```java
/*___Generated_by_IDEA___*/

package com.foo.lib;

/* This stub is only used by the IDE. It is NOT the R class actually packed into the APK */
public final class R {
}
```
Is that the correct path? 
I also see a correctly generated BuildConfig in the following path:
```
buck-out/gen/foo/__bin_debug#gen_java_android_build_config_com_foo_android__/BuildConfig.java
```

Using latest HEAD of Buck

**Comment by felipecsl** [comment]
Looks like this can be disabled by unchecking `Generate sources automatically` in the Project Structure > Project Settings > Facets dialog and removing the files manually.
Still ideally this should be disabled when running `buck project`

**Comment by styurin** [comment]
> <option name="GEN_FOLDER_RELATIVE_PATH_AIDL" value="/../buck-out/android/core/gen" />

This option in iml tells IntelliJ where to keep files generated inside IntelliJ.

> Looks like this can be disabled by unchecking Generate sources automatically in the Project Structure > Project Settings > Facets dialog and removing the files manually.

This folder still can be created if sources are generated manually.

> Still ideally this should be disabled when running buck project

This can be disabled by adding the following section to `.buckconfig`:

```
[project]
  disable_r_java_idea_generator = true
```

We should document this option in our docs though.

**Comment by felipecsl** [comment]
Using that option in the buckconfig indeed fixed the problem. Thanks!
