### ISSUE TITLE
Use of track_class_usage causes unexpected build failure

### ISSUE THREAD

**Issue by seanabraham** [facebook/buck#945]
I noticed a build failure like:

```
error: method fooBar in class com.foo.Bar cannot be applied to given types;
        baz.fooBar(1, 2);
           ^
required: int
found: int,int

reason: actual and formal argument lists differ in length
```

Roughly what I believe happened was:
1) Add method `fooBar(int)` and use it in a separate module
2) Build with buck
3) Add method `fooBar(int, int)` and use it in a separate module
4) Attempt to build with buck and get the above failure.

Setting

``` yaml
[java]
    track_class_usage = false
```

in my `.buckconfig` and building again resolved the problem. So I'm assuming `track_class_usage` isn't handling something about overloaded method signatures properly yet.

**Comment by Coneko** [comment]
cc @jkeljo, @asp2insp

**Comment by kageiit** [comment]
We saw the same problem and had to turn the option off because it was causing flaky CI builds due to bad cache

**Comment by kageiit** [comment]
Any update on this? the feature seems very useful to have

**Comment by asp2insp** [comment]
We identified a couple of issues around manifest-based caching that caused stale cache hits. These should be fixed now, so feel free to try again with the `track_class_usage` config. I'll leave this issue open for a little while if you run into more problems.

**Comment by kageiit** [comment]
builds work fine, but we are seeing code coverage completely gone with `track_class_usage` set to true. We are going to disable ti again. @justinmuller will post back repro steps and findings about this issue

**Comment by Coneko** [comment]
Closing since it seems the initial issue has been solved. Create a new issue to discuss the code coverage being broken.
