### ISSUE TITLE
If no RELEASE.txt, Buck can't find NDK version

### ISSUE THREAD

**Issue by LegNeato** [facebook/buck#952]
Newer versions of the NDK don't contain RELEASE.txt, but that's all Buck seems to be looking for:

http://stackoverflow.com/questions/36623681/how-to-find-the-ndk-revision-number-for-your-android-setup

Buck should also read from `source.properties` if it exists.

This would be a good first bug.

**Comment by Coneko** [comment]
Are you sure? It's supposed to be looking at `source.properties` as well: https://github.com/facebook/buck/blob/master/src/com/facebook/buck/android/DefaultAndroidDirectoryResolver.java#L49 .

**Comment by LegNeato** [comment]
I'm pretty sure. I'll repro it, perhaps that logic is busted with the way I have my stuff set up (via Homebrew)

**Comment by LegNeato** [comment]
Actually, I think this was a problem with my setup.
