### ISSUE TITLE
Need a way to use a genrule() as input to android_resource()

### ISSUE THREAD

**Issue by iainmerrick** [facebook/buck#96]
The android_resource() has "res" and "assets" parameters, both of which are documented as paths to existing directories. You can't build these output directories via genrule(), as it only outputs a single file, and the result goes into the buck-out tree.

**Comment by plinehan** [comment]
For anyone else who comes across this, generating an .aar of resources is more straightforward than it might seem.  Buck only requires that you have an AndroidManifest.xml and classes.jar in addition to your resources.  The ["mandatory"](http://tools.android.com/tech-docs/new-build-system/aar-format) R.txt is not actually required.

Here's a script that generates a skeletal AndroidManifest.xml, an "empty" classes.jar, and a string resource file, and then creates the .aar from those:

https://gist.github.com/plinehan/e9604555fd0c0cf2aa4e

**Comment by k21** [comment]
It is now possible to have `genrule`s that output directories. `android_resource` unfortunately still does not accept outputs of other targets in its `res` and `assets` parameters, but that should not be too hard to change.

**Comment by k21** [comment]
This should now work as expected.
