### ISSUE TITLE
Missing icon on certain devices.

### ISSUE THREAD

**Issue by plinehan** [facebook/buck#969]
On certain devices, e.g. a Galaxy S3, our app's icon defaults to the standard "Bugdroid" icon when built with Buck.  On most devices we test with the icon is fine, and the bug seems to depend on how the app is installed.  If we install via ADB ("install -r") the bug almost never presents itself, but sideloading the APK first will reliably induce it on buggy devices.

We initially noticed the bug via reports from users downloading it from the Play Store, and realized that reverting to an older version of Buck solved the problem.

I finally got around to bisecting it and it appears that 6ac44db66e0209dc7ea5b5cebe5396ab2611f33c is to blame.  @Coneko , as the original author, does this make any sense to you?  Any help would be greatly appreciated.  I suspect that this is mostly our fault given that nobody else has reported the bug in nearly a year.

**Comment by Coneko** [comment]
I don't know how that commit could cause that bug, is it possible you bisected wrong?

**Comment by plinehan** [comment]
Ha, a good guess!  I also suspected that I bisected wrong, so I went back and double-checked that the problem appears right at this commit.

The icon is missing in this scenario:

```
/uninstall app from phone/
$ buck kill & rm -fr buck-out/ buck-cache/
$ echo 6ac44db66e0209dc7ea5b5cebe5396ab2611f33c > .buckversion
$ buck build, install, etc
```

And present in this scenario:

```
/uninstall app from phone/
$ buck kill & rm -fr buck-out/ buck-cache/
$ echo 4c071483996bf84450438ccf20723a845086be85 > .buckversion
$ buck build, install, etc
```

The first two steps of each process (uninstalling the app, `buck kill`-ing, and clearing caches) are just me being extremely paranoid about making the process as hermetic as possible.

**Comment by plinehan** [comment]
So it turns out that the app isn't missing the icon, it is just picking up a default-looking icon from one of our external dependencies, specifically the Dropbox Chooser SDK.  They include ic_launcher.png images for a few display densities, and as a result of this change they are now being used instead of our ic_launcher.png files.

If I just delete the images from the Dropbox Chooser SDK, the problem goes away.  I'm assuming this commit now considers the resources equivalent, so it is arbitrarily picking the Dropbox resources?

I'm totally fine to delete the Dropbox images and just move forward, but this does seem like a bug.  The Dropbox resources are in their own package, as evidenced by our `dropbox-chooser/BUCK` file:

```
android_resource(
  name = "res",
  res = "res",
  package = "com.dropbox.chooser.android",
)
```

Is the package name not considered when merging or comparing resources?  I'm just confused as to why this is happening, even if it was odd for us to have the duplicate resources.

Also, thanks for building Buck.  It is a fantastic piece of software.
