### ISSUE TITLE
Buck doesn't error-check $location expansions inside a macro

### ISSUE THREAD

**Issue by nicks** [facebook/buck#971]
Consider the following BUCK file

```
genrule(
   name = 'out',
   out = 'out.txt',
   cmd = 'echo \$(dirname $(location :x)) > $OUT')
```

Expected Result:
I should get an error like "No rule found when resolving target //:x in build file ///BUCK"

Actual result:
Buck generates a broken shell script then tries to execute it

```
echo $(dirname $(location :x)) > $OUT
```

Note that if I use a command `cmd = 'echo $(location :x) > $OUT'`, buck gives a correct error message.

Also note that if :x resolves to a valid target, this genrule works.

**Comment by v-jizhang** [comment]
Sorry we never got back to this! At this point, we are closing this because it is quite out of date and it is not clear if the issue still exists. Please create a new one if you still see the problem. Thank you.
