### ISSUE TITLE
Documentation: No way to link build rule attributes

### ISSUE THREAD

**Issue by davido** [facebook/buck#979]
When quoting one rule specific attribute, it's indispensable to be able to link to this attribute. Say, I would like to file an issue specific to `manifest_file` in `java_binary` rule. Unless I'm missing something, I've not found a way to do it. In Bazel, [it just works](https://www.bazel.io/versions/master/docs/be/java.html#java_binary.deploy_manifest_lines).

**Comment by sdwilsh** [comment]
Should be easy to add id's here that we can link to: https://github.com/facebook/buck/blob/master/docs/__common.soy#L451

Then adding the little bit of extra markup to take advantage of the CSS classes added in 04ce5bf674bed4ed8da9da67cfec97b899ebc9ad should make this work.
