### ISSUE TITLE
File copy error when trying to make android_aar package from library using android_prebuilt_aar

### ISSUE THREAD

**Issue by baustinanki** [facebook/buck#987]
I set up an example that will cause this error here: https://github.com/baustinanki/buckerror-example

Basically, with a BUCK file that...
a.) creates an `android_prebuilt_aar` rule using `support-v4-23.0.1.aar` from the Android Support Repository in the Android SDK
b.) creates an `android_library` rule dependent on (a)
c.) creates an `android_aar` package dependent on (b)
like so:
```python
android_prebuilt_aar(
  name = 'android-support-v4-23',
  aar = 'support-v4-23.0.1.aar',
)

android_library(
  name = 'foo_lib',
  srcs = glob(['**/*.java']),
  deps = [':android-support-v4-23'],
)

android_aar(
  name = 'foo',
  manifest_skeleton = 'AndroidManifest.xml',
  deps = [':foo_lib'],
  visibility = ['PUBLIC'],
)
```

I get this very cryptic error (which tends to only happen once and then not repeat until I clean out my `buck-out` folder and rebuild):

```
[~/buckexample (master) $] buck build :foo
Not using buckd because watchman isn't installed.
Failed when trying to copy: cp -R /Users/baustinanki/buckexample/buck-out/bin/__unpack_android-support-v4-23#aar_unzip__/assets/* buck-out/gen/__assembled_foo#aar_assemble_assets__
java.nio.file.NoSuchFileException: /Users/baustinanki/buckexample/buck-out/bin/__unpack_android-support-v4-23#aar_unzip__/assets
java.nio.file.NoSuchFileException: /Users/baustinanki/buckexample/buck-out/bin/__unpack_android-support-v4-23#aar_unzip__/assets
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	<...more callstack redacted>
BUILD FAILED: //:foo#aar_assemble_assets failed with exit code 1:
cp
```

**Comment by anoever** [comment]
I have the same issue here. Running the build a few times seems to fix this issue. I have seen that
```
unzip /Users/.../buck-out/gen/root/appcompat-v7_aar/appcompat-v7-23.1.1.aar -d /Users/.../buck-out/bin/root/__unpack_appcompat-v7#aar_unzip__
```
runs after the cp -R task which seems to be an ordering issue. Once the unzip task has run the next build succeeds.

**Comment by v-jizhang** [comment]
Sorry we never got back to this! At this point, we are closing this because it is quite out of date and it is not clear if the issue still exists. Please create a new one if you still see the problem. Thank you.
