### ISSUE TITLE
ObjC imports not found when trying to importing inter-op apple_library()

### ISSUE THREAD

**Issue by stowy** [facebook/buck#991]
Check out the Readme at https://github.com/stowy/buck_swift_test/tree/dependencyTests

Or just do:

```
git clone git@github.com:stowy/buck_swift_test.git
git checkout origin/dependencyTests
buck build :MainBinary
```

### Bug description
- The problem is, building `:MainBinary`, when imported any headers from a MixedDependency, fails with header not found. 
- When not importing a header, even with the dependency still in place, it builds correctly
- To test, just clone this branch and run `buck build :MainBinary` and you should get the following error:

```
$ fbuck build :MainBinary
Not using buckd because watchman isn't installed.
MainApp/AppDelegate.m:5:9: fatal error: 'MixedDependency1/MixedDep1.h' file not found
#import "MixedDependency1/MixedDep1.h"
        ^
1 error generated.

BUILD FAILED: //:MainBinary#compile-AppDelegate.m.o4513ea3e,iphonesimulator-x86_64 failed with exit code 1:
objective-c compile_munge_debuginfo
[-] PROCESSING BUCK FILES...FINISHED 0.1s [100%] 🐳  New buck daemon
[-] DOWNLOADING... (0.00 B/S AVG, TOTAL: 0.00 B, 0 Artifacts)
[-] BUILDING...FINISHED 0.6s [100%] (11/13 JOBS, 0 UPDATED, 0 [0.0%] CACHE MISS)
```
- Note that if you remove the line `#import "MixedDependency1/MixedDep1.h"` from the AppDelegate in `MainApp/AppDelegate.m`, it will build successfully.
- Note also that the other apple_libraries with the same dependency (eg `:MixedDependency2`, `:MixedDependency3`) also build and run tests successfully, with dependencies

@robbertvanginkel

**Comment by stowy** [comment]
Looking into this further, it seems that the file organisation in the 'buck-out/gen' folder for the ObjC headers changes when the 'swift-compile' step is included in the build process (because of the presence of swift in the library).

See this file output below, notice that the headers are included in a single flat directory for the ObjC output, but in a hierarchical directory structure for the swift one. The libraries that rely on this MixedDependency1 then fail to compile because headers are not found. 

@nguyentruongtho

<img width="771" alt="screenshot 2016-11-04 09 16 31" src="https://cloud.githubusercontent.com/assets/5924628/20013204/8fd985e4-a26f-11e6-8926-0a2e2e5d8e41.png">

**Comment by nguyentruongtho** [comment]
Cool, thanks for being very descriptive about this 💃 
I'll take a look during this weekend, was too busy with other stuffs recently.

**Comment by stowy** [comment]
No problems. I've had a further look into it and it seems that the header
key maps for the library containing swift do not have the correct,
shortened keys. I'm thinking it's caused by the swift companion build rule.
If I'm able I may write a test for this and try to debug, I'll post a link
here if I get one created.

**Comment by stowy** [comment]
The above PR should fix this issue - it fixes the headermap for the SwiftCompile step.
