### ISSUE TITLE
Swift libraries as dependencies don't build when building a fat binary

### ISSUE THREAD

**Issue by ryu2** [facebook/buck#992]
it has something todo with `AppleLibraryDescription#hasFlavors` & `SwiftLibraryDescription#hasFlavors`

you can't have more than one platform flavors there, but for swift, there is something to do with multiple platform flavors

```
BUILD FAILED: In build target //Foo:Bar#dwarf-and-dsym,iphoneos-arm64,iphoneos-armv7,strip-non-global,swift-companion: multiple "C/C++ platform" flavors: iphoneos-arm64, iphoneos-armv7
```

**Comment by ryu2** [comment]
cc: @nguyentruongtho

**Comment by v-jizhang** [comment]
Hi, this issue is closed because there is no updates for more than 3 year. thanks
