### ISSUE TITLE
Consider to integrate error prone out of the box in java build tool chain

### ISSUE THREAD

**Issue by davido** [facebook/buck#994]
Gerrit Code Review can be compiled with most recent Buck version (d6949e1440ef2048d697c637a4adae1b509bf72d) without any issues.

With vanilla Bazel 0.4.0 Gerrit is failing to compile, though, and tells me that:

```
  $ bazel build gerrit
INFO: Found 1 target...
ERROR: /home/davido/projects/gerrit/gerrit-sshd/BUILD:5:1: Java
compilation in rule '//gerrit-sshd:sshd' failed: Worker process sent
response with exit code: 1.
bazel-out/local-fastbuild/bin/gerrit
-sshd/_javac/sshd/libsshd_sourcegenfiles/com/google/gerrit/sshd/AutoAnn
otation_Commands_named.java:52: error: [ConstantOverflow] Compile-time
constant expression overflows
        ((127 * 111972721) ^ (value.hashCode()));
                           ^
    (see http://errorprone.info/bugpattern/ConstantOverflow)
1 error
Target //:gerrit failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 2.393s, Critical Path: 2.17s
```

It turns out, this is a bug in auto-value dependency, that was fixed here: [1].

* [1] https://github.com/google/auto/pull/371

**Comment by kageiit** [comment]
@davido #1019 might be useful in this regard

**Comment by davido** [comment]
@kageiit Now, that #1019 is it already possible to seamlessly integrate error prone with Buck?

**Comment by kageiit** [comment]
Yes. We have been using it internally. Just set the javac jar to the error prone javac jar (I used the one that ships with bazel) and set the compiler class name to the error prone compiler and it's good to go

**Comment by davido** [comment]
@kageiit thanks! it was harder as expected, though. Quoting here my comment on Buck integration feature request on error prone issue tracker: https://github.com/google/error-prone/issues/318.

So, it seems, that if I borrow thoses dependencies from Bazel tree (9bde9d09a83cdca2dc884d322ab50f7542c062cf)

* third_party/java/jdk/langtools/javac.jar
* third_party/error_prone/error_prone_annotations-2.0.13.jar
* third_party/error_prone/error_prone_annotation-2.0.13.jar
* third_party/error_prone/error_prone_core-2.0.13.jar
* third_party/checker_framework_dataflow/dataflow-1.8.10.jar

Now, the other two missing dependencies `jformatstring` and `libchecker_framework_javacutil.jar` must be compiled from the source:

```
 bazel build third_party/jformatstring:jformatstring
 cp bazel-bin/third_party/jformatstring/libjformatstring.jar <to uber JAR>

  bazel build checker_framework_javacutil
  cp bazel-bin/third_party/checker_framework_javacutil/libchecker_framework_javacutil.jar <to uber JAR>
```

After building a uber JARs with all those dependencies above I've added these lines to my `.buckconfig.local` file in Gerrit Code Review project:

```
  [tools]
    javac_jar = lib/error_prone_2.13_all_in_one.jar
    compiler_class_name = com.google.errorprone.ErrorProneJavaCompiler
```

Now, after bumping Buck to the most recent master (45c405cf2ba2735e8c06cf76eed224d6f81d666e) and patching `gerrit-server` sub-project with this diff: http://paste.openstack.org/show/592031/ and building with `buck build gerrit-server:server` we are getting error prones warning and errors: http://paste.openstack.org/show/592032.

So, error prone activation must be really trivial. Ideally Buck should ship the current version of error-prone-all-in-one.jar, so that all i have to do is to add those three line to my .buckconfig:

```
 [tools]
    javac_jar = lib/error_prone_<current-version>_all_in_one.jar
    compiler_class_name = com.google.errorprone.ErrorProneJavaCompiler
```

done.

**Comment by kageiit** [comment]
We compiled error prone from source ourselves. It's better that way because buck cannot anticipate what versions of javac and error prone can be shipped with it. But for out of box Integration of error prone into buck, I am not the right person to ask :)

**Comment by kageiit** [comment]
You have to use a project relative path. You cannot use an absolute path for the javac jar

**Comment by kageiit** [comment]
I would recommend checking in all jars into a module and make a java_binary out of it and make all rules that need error prone depend on it in the rules

**Comment by kageiit** [comment]
You can also use remote_file and make that a dependency of a Java binary and depend on it that way. Even if buck shipped with error prone, we would probably use our own built version for greater control

**Comment by kageiit** [comment]
Building error prone from source let's us wrote our own error prone rules as well, which can be lot more than what the standard checks are. I won't mind if buck supported error prone out of the box, but given the custom compiler options, you can write your own bucklets as well to tie it all together nicely.

**Comment by davido** [comment]
OK, I'm trying the native integration, using `remote_file`, basicaly the same way we are adding annotation processor support, by monkey patching native `java_library` rule and referencing the entry point for patching in `.buckconfig`.

.buckconfig:

```
[buildfile]
  includes = //tools/default.defs
```

where the interesting part of `default.defs` is:

```
# Set defaults on java rules:
#  - Add error prone as default compiler (doesn't work)
#  - Add AutoValue annotation processing support.
#  - Treat source files as UTF-8.

_buck_java_library = java_library
def java_library(*args, **kwargs):
  _munge_args(kwargs)
  _buck_java_library(*args, **kwargs)

_buck_java_test = java_test
def java_test(*args, **kwargs):
  _munge_args(kwargs)
  _buck_java_test(*args, **kwargs)

# Munge kwargs to set Gerrit-specific defaults.
def _munge_args(kwargs):
  _set_errorprone(kwargs)
  _set_auto_value(kwargs)
  _set_extra_arguments(kwargs)

def _set_auto_value(kwargs):
  apk = 'annotation_processors'
  if apk not in kwargs:
    kwargs[apk] = []
  aps = kwargs.get(apk, [])

  apdk = 'annotation_processor_deps'
  if apdk not in kwargs:
    kwargs[apdk] = []
  apds = kwargs.get(apdk, [])

  all_deps = kwargs.get('deps', []) + kwargs.get('exported_deps', [])
  if AUTO_VALUE_DEP in all_deps:
    aps.extend(AUTO_VALUE_PROCESSORS)
    apds.extend(AUTO_VALUE_PROCESSOR_DEPS)

def _set_errorprone(kwargs):
  kwargs['javac_jar'] = 'buck-out/gen/lib/__errorprone__/error_prone_ant-2.0.15.jar'
  kwargs['compiler_class_name'] = 'com.google.errorprone.ErrorProneJavaCompiler'
```

There are two problems here:

* 1. there is no way to specify the dependency for `javac_jar`. So what I would expect is to say:

```
  java_library(
    name = "foo",
    javac_jar_dep = ['//lib/errorprone'],
    [...]
```

where `//lib/errorprone` could be defined as follow:

```
  maven_jar(
    name = 'errorprone',
    id = 'com.google.errorprone:error_prone_ant:2.0.15',
    sha1 = '607e3866e2ee25b74708c2898f84eac2f5452d2f',
    license = 'Apache2.0',
  )
```

Note, that `maven_jar` is gerrit specific bucklet and can be replaced by native `remote_file` rule.

* 2. relative path is relocated to sub-project directory

If i disable monky patching first, and fetch the error prone dependency manually:

```
$ buck build lib:errorprone --show-output
[+] PARSING BUCK FILES...0.2s
The outputs are:
//lib:errorprone buck-out/gen/lib/__errorprone__/error_prone_ant-2.0.15.jar
```

and define the `javac_jar` to be:

```
def _set_errorprone(kwargs):
  kwargs['javac_jar'] = 'buck-out/gen/lib/__errorprone__/error_prone_ant-2.0.15.jar'
  kwargs['compiler_class_name'] = 'com.google.errorprone.ErrorProneJavaCompiler'
```

the jar is for some reasons rellocated to the sub-project being compiled:

```
$ buck build gerrit-server:server
[+] PARSING BUCK FILES...0.9s
BUILD FAILED: //gerrit-server:testutil: parameter 'javacJar': no such file or directory 'gerrit-server/buck-out/gen/lib/__errorprone__/error_prone_ant-2.0.15.jar'
```

I guess something here is still broken?

**Comment by davido** [comment]
Bottom line (unless I'm missing something very obvious here): `javac_jar` and `compiler_class_name` support in `java_library` and friends is broken.

What does work on most recent Buck master (45c405cf2ba2735e8c06cf76eed224d6f81d666e) is to fetch the error prone dependency manually and copy it to `lib` directory:

```
  $ buck build lib:errorprone --show-output
[+] PARSING BUCK FILES...0.2s
The outputs are:
//lib:errorprone buck-out/gen/lib/__errorprone__/error_prone_ant-2.0.15.jar
  cp buck-out/gen/lib/__errorprone__/error_prone_ant-2.0.15.jar lib/
```

and add these lines to `.buckconfig.local`:

```
[tools]
  javac_jar = lib/error_prone_ant-2.0.15.jar
  compiler_class_name = com.google.errorprone.ErrorProneJavaCompiler
```

This is all wrong. Instead, I should be able to say just that:

```
  maven_jar(
    name = 'errorprone',
    id = 'com.google.errorprone:error_prone_ant:2.0.15',
    sha1 = '607e3866e2ee25b74708c2898f84eac2f5452d2f',
    license = 'Apache2.0',
  )
```

and now, provide those dependency for the custom compiler class (exactly the same way its already possible with `annotation_processors` and `annotation_processor_deps`):

```python
  java_library(
    name = "foo",
    compiler_class_name = 'com.google.errorprone.ErrorProneJavaCompiler',
    compiler_class_deps = ['//lib/errorprone'],
    [...]
```

**Comment by davido** [comment]
Actually it only works when passing a `//lib:errorprone` rule to `javac_jar` in `java_library`. When I'm defining the same in `.buckckonfig`, it's failing with:

```
# This is failing with: BUILD FAILED: Rule for target '//:errorprone' could not be resolved.
#
#[tools]
#  javac_jar = //:errorprone
#  compiler_class_name = com.google.errorprone.ErrorProneJavaCompiler
```

I'v created a reproducer repository: https://github.com/davido/buck_error_prone_integration .

Anyway, with monkey patching it just works:

```
  $ buck build :util
  /home/davido/projects/buck_error_prone_integration/java/org/ostrovsky/buck/Util.java:5: error: [DeadException] Exception created but not thrown
    new Exception();
    ^
    (see http://errorprone.info/bugpattern/DeadException)
  Did you mean to remove this line?
Errors: 1. Warnings: 0.

BUILD FAILED: //:util failed with exit code 1:
javac
stderr: /home/davido/projects/buck_error_prone_integration/java/org/ostrovsky/buck/Util.java:5: error: [DeadException] Exception created but not thrown
    new Exception();
    ^
    (see http://errorprone.info/bugpattern/DeadException)
  Did you mean to remove this line?
Errors: 1. Warnings: 0.
```

**Comment by kageiit** [comment]
I think javac_jar only supports source paths in buckconfig, but the individual rules can support java build targets. using `DEFS` file might be a way to achieve that

**Comment by brettwooldridge** [comment]
@kageiit @Coneko I'm running into something similar working on the improved Kotlin compiler support.  I really want to be able to reference a target in ``.buckconfig``...
```
[kotlin]
  compiler_jar = //ThirdParty/deps:kotlin-compiler
```
where there is a rule:
```
prebuilt_jar(
   name = 'kotlin-compiler',
   binary_jar = 'kotlin-compiler-1.1.1.jar',
   visibility = ['PUBLIC'],
)
```
But for the life of me I cannot figure out how to get the resolve to work.  I get a similar error to that above:
```
BUILD FAILED: Rule for target '//ThirdParty/deps:kotlin-compiler' could not be resolved.
```
It would be nice to be able to simply change the jar version in the rule.  If the ``.buckconfig`` must contain a path the user has to update multiple places.  Is there any workaround to inject *kotlin-compiler* into the target graph without having a rule explicitly depend on it?  ``SourcePathResolver`` clearly finds it, but ``BuildRuleResolver`` of course fails.

**Comment by kageiit** [comment]
I think if the usage is in `.buckconfig`, SourcePath is the only way to go as the target graph is not ready yet.

Also, why would the user need to update the path in multiple places?

**Comment by sdwilsh** [comment]
I'm a bit rusty with Buck code, but IIRC, there is a `Tool` class that can take a `SourcePath` you define in the `.buckconfig`.  You just need to add the dependency to the build rule when you construct it in the Description.
