### ISSUE TITLE
Add support for optional package contents in android_aar

### ISSUE THREAD

**Issue by kageiit** [facebook/buck#995]
The aar format used by the current `android_aar` rule is obsolete. The new spec is detailed here: https://developer.android.com/studio/projects/android-library.html#aar-contents

This allows bundling consumer proguard rules, custom lint jars etc.

**Comment by sdwilsh** [comment]
For anyone doing this work, I wouldn't expect `R.txt` to exist.  Google has previously published (might still be publishing) AARs without it, and I'm sure others exist out there too.

**Comment by kageiit** [comment]
`R.txt` is not mandatory if there are no resources

**Comment by v-jizhang** [comment]
Sorry we haven't update this issue for more than 3 years. At this point, we are closing this because it is quite out of date and it is not clear if the issue still exists. Please create a new one if you still see the problem. Thank you.
